### ISSUE TITLE
Converted addons have stopped working

### ISSUE THREAD

**Issue by Bfgeshka** [MoonchildProductions/Pale-Moon#1001]
As for commit 4c6d070, addons converted via moon tester tool are not working. 
Is this a bug or an intended change in progress?

Can give configuration information if needed.

**Comment by JustOff** [comment]
Fixed by [7a724f3](https://github.com/MoonchildProductions/Pale-Moon/commit/7a724f3dfc7f1d5e5a12d12b072fb0cabced0866).

**Comment by wolfbeast** [comment]
The risk of running from tip. Sometimes the tree is in an unusable state.
Safer bet is using the unstable channel binaries.
