### ISSUE TITLE
treeView.js - Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsINavHistoryContainerResultNode.getChildIndex]

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1020]
On a clean profile upon right-clicking on an RSS Live Bookmark and reloading it <b>in the Bookmarks Manager</b>, both the Error and the Browser consoles of the <b>unstable</b> build shows the following:

<tt>Error: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsINavHistoryContainerResultNode.getChildIndex]
Source File: chrome://browser/content/places/treeView.jsLine: 172</tt>

* This happens upon right-clicking and reloading the Live Bookmark in the <b>LEFT</b> pane of the Bookmarks Manager, never in the right pane. However, should you right-click and reload it in the <b>RIGHT</b> pane, and <b>immediately</b> select it on the <b>LEFT</b> pane after this, the error <b>does appear</b> this time round.

* It seems like at least a few of the latest <b>stable</b> releases are affected; this error <b>initially appears in the Browser Console only</b>, but over time, when the profile isn't fresh anymore, <b>the same error can also be seen in the Error Console</b>.
<b>UPDATE:</b> After reinstalling, both of the latest stable Pale Moon releases I've tried show this error in both consoles from the very beginning.

* <b>UPDATE:</b> At a first glance, the Live Bookmarks are "auto-updated" upon every selection without the need to reload (this is indicated by their timestamps in the right pane), and without any errors; however, sometimes upon selection they're "auto-reloaded", and then the error in question appears in the consoles too. Unfortunately, it's all rather confusing, and since I'm not an expert, unable to explain this correctly; sorry for the inconvenience.

---

This has also been checked very briefly in the Browser Consoles on the clean profiles of the following browsers for Windows desktop, so <b>please kindly report this error to Bugzilla if it's confirmed</b>:

* Firefox 45.7.0 x86 ESR:
<tt>NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsINavHistoryContainerResultNode.getChildIndex] treeView.js:182:0</tt>

* Firefox 52.0 x86 ESR:
<tt>NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsINavHistoryContainerResultNode.getChildIndex] treeView.js:173:0</tt>

* Waterfox 52.0.1 x64:
<tt>NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsINavHistoryContainerResultNode.getChildIndex] treeView.js:173:0</tt>

---

Hopefully, someone will be able to contribute to better understand and successfully fix this issue.

**Comment by janekptacijarabaci** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1110794

Maybe it would be sufficient (it's a special "bookmark")...
``` javascript
      try {
        row = useNodeIndex ? aNodeIndex : this._rootNode.getChildIndex(aNode);
      } catch (e) {
        // Feeds throws an errors - ignore.
        // See also https://bugzilla.mozilla.org/show_bug.cgi?id=1110794
      }
```

But I don't know...

**Comment by wolfbeast** [comment]
I've added this info to the BMO bug

**Comment by Lorienna** [comment]
I've done some additional testing, and completely reinstalled the latest Pale Moon 27.2.1 x86 stable; both consoles now show this error from the very beginning, not over time.

Also, since a Live Bookmark is <b>empty upon each startup</b>, if it hasn't already been automatically filled in, then the <b>left-clicking</b> fills it and results in the error in question too; so far I've seen this happen only <b>once a session</b>.

And thank you for Pale Moon, and for helping out.

**Comment by Lorienna** [comment]
So far, after a bit more extensive testing in the same Win7x64, it looks like this error happens upon:
1. clicking a newly added livemark, anytime before any other one;
2. right-clicking + reloading a livemark in the left pane;
3. right-clicking + reloading a livemark in the right pane, and immediately selecting it in the left pane;
4. clicking any livemark in the left pane anytime for the first time after a browser startup;
5. clicking any non-selected livemark in the left pane after 30+ minutes since the last feeds update (seems like <b>PM-only</b>).

To be succesfully reproduced, all this should be done solely in the Bookmarks Manager, and after a new browser startup.

---

In Mozilla archive, <b>the first nightly "central"</b> FF build throwing the error in question is <tt>36.0a1</tt> (dated 14 Nov 2014):
https://archive.mozilla.org/pub/firefox/nightly/2014/11/2014-11-14-03-02-06-mozilla-central/

Here's the build info (dated 13 Nov 2014):
https://hg.mozilla.org/mozilla-central/rev/7f0d92595432
* There's a file in the list named <tt>browser_library_left_pane_commands.js</tt>:
https://hg.mozilla.org/mozilla-central/diff/7f0d92595432/browser/components/places/tests/browser/browser_library_left_pane_commands.js
* And there's another file named <tt>browser_graphs-09.js</tt>:
https://hg.mozilla.org/mozilla-central/diff/7f0d92595432/browser/devtools/shared/test/browser_graphs-09.js
The description line says <tt>// Tests that line graphs properly create the gutter and tooltips.</tt> Not sure IIUC all this, but there ARE problems with the livemark tooltips in PM and FF, as well as some other random discrepancies in this area, but unfortunalely they're unreproducible step-by-step to me so far.

---

Likewise, here's <b>the last UNaffected nightly "central"</b> build <tt>36.0a1</tt> in Mozilla archive (dated 13 Nov 2014):
https://archive.mozilla.org/pub/firefox/nightly/2014/11/2014-11-13-03-02-01-mozilla-central/

And here's the build info (dated 12 Nov 2014):
https://hg.mozilla.org/mozilla-central/rev/ab137ddd3746

---

<b>The first affected beta</b> is <tt>36b1</tt> (not <tt>35beta3</tt>, as the initial Bugzilla reporter claimed):
https://archive.mozilla.org/pub/firefox/releases/36.0b1/
https://archive.mozilla.org/pub/firefox/candidates/archived/36.0b1-candidates/

The build info (dated 14 Jan 2015):
https://hg.mozilla.org/releases/mozilla-beta/rev/521859f9eae2

---

And <b>the first affected major release</b> is, apparently, FF 36.0 :
https://archive.mozilla.org/pub/firefox/releases/36.0/
https://archive.mozilla.org/pub/firefox/candidates/archived/36.0-candidates/

The build info (dated 23 Feb 2015):
https://hg.mozilla.org/releases/mozilla-release/rev/88c5342693e3

---

In all these builds, the error is essentially alike, although the problematic line is numbered <tt>180</tt>:
<tt>NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsINavHistoryContainerResultNode.getChildIndex]  treeView.js:180</tt>

And as it appears, the line at issue in <tt>chrome://browser/content/places/treeView.js</tt> is always one and the same everywhere:
<tt>row = useNodeIndex ? aNodeIndex : this._rootNode.getChildIndex(aNode);</tt>

---

Any feedback?

**Comment by janekptacijarabaci** [comment]
__Last good: 36.0a1 (2015-01-13)__
Built from https://hg.mozilla.org/mozilla-central/rev/ab137ddd3746

__First bad: 36.0a1 (2015-01-14)__
Built from https://hg.mozilla.org/mozilla-central/rev/7f0d92595432

Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=ab137ddd3746&tochange=7f0d92595432

[Bug 1083462](https://bugzilla.mozilla.org/show_bug.cgi?id=1083462) (maybe [bug 1095069](https://bugzilla.mozilla.org/show_bug.cgi?id=1095069)) is the suspect.

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
My suggestion is below:

Ad https://github.com/MoonchildProductions/Pale-Moon/blob/27.2.1_Release/browser/components/places/content/treeView.js#L171

From:
``` javascript
    if (parent == this._rootNode)
      row = useNodeIndex ? aNodeIndex : this._rootNode.getChildIndex(aNode);
    else if (useNodeIndex && typeof(aParentRow) == "number") {
```
To:

1)
``` javascript
    if (parent == this._rootNode) {
      if (aNode instanceof Ci.nsINavHistoryResultNode) {
        row = useNodeIndex ? aNodeIndex : this._rootNode.getChildIndex(aNode);
      }
    } else if (useNodeIndex && typeof(aParentRow) == "number") {
```
or

2)
``` javascript
    if (parent == this._rootNode) {
      if (aNode.itemId != -1) {
        row = useNodeIndex ? aNodeIndex : this._rootNode.getChildIndex(aNode);
      }
    } else if (useNodeIndex && typeof(aParentRow) == "number") {
```

See https://github.com/MoonchildProductions/Pale-Moon/blob/27.2.1_Release/toolkit/components/places/nsINavHistoryService.idl#L236

Maybe it will be temporary, maybe it won't. But:
`aNode instanceof Ci.nsINavHistoryResultNode` condition does not apply to livemarks (nodes).

**Comment by Lorienna** [comment]
Thank you for making the research!

<blockquote>as it appears, the line at issue in <tt>chrome://browser/content/places/treeView.js</tt> is always one and the same everywhere: <br><tt>row = useNodeIndex ? aNodeIndex : this._rootNode.getChildIndex(aNode);</tt></blockquote>

Since there's still more info needed, here's how, from the look of it, the numbering of this line has been changing in the <b>purely "central"</b> builds as the development progresses.

---

The last errorless one: <b>36.0a1 (2014-11-13):</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/11/2014-11-13-03-02-01-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/ab137ddd3746

* <tt>treeView.js:<b>180</b></tt>

First seen: <b>36.0a1 (2014-11-14):</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/11/2014-11-14-03-02-06-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/7f0d92595432

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=ab137ddd3746&tochange=7f0d92595432

Last seen: <b>44.0a1 (2015-09-28)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-28-03-02-06-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/6256ec9113c115141aab089c45ee69438884b680

---

* <tt>treeView.js:<b>182</b></tt>

First seen: <b>44.0a1 (2015-09-29)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-29-03-02-25-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/acdb22976ff86539dc10413c5f366e1fb429a680

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=6256ec9113c115141aab089c45ee69438884b680&tochange=acdb22976ff86539dc10413c5f366e1fb429a680

Last seen: <b>52.0a1 (2016-10-29)</b>
https://archive.mozilla.org/pub/firefox/nightly/2016/10/2016-10-29-03-02-04-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/1561c917ee27c3ea04bd69467e5b8c7c08102f2a

---

* <tt>treeView.js:<b>173</b></tt>

First seen: <b>52.0a1 (2016-10-29)</b>
https://archive.mozilla.org/pub/firefox/nightly/2016/10/2016-10-29-06-26-01-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/1b170b39ed6bdbde366233ab84594bdaaa960a5a

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1561c917ee27c3ea04bd69467e5b8c7c08102f2a&tochange=1b170b39ed6bdbde366233ab84594bdaaa960a5a

Last seen: <b>53.0a1 (2017-01-03)</b>
https://archive.mozilla.org/pub/firefox/nightly/2017/01/2017-01-03-03-02-04-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/c91249f41e3766274131a84f9157a4d9d9949520

---

* <tt>treeView.js:<b>172</b></tt>

First seen: <b>53.0a1 (2017-01-04)</b>
https://archive.mozilla.org/pub/firefox/nightly/2017/01/2017-01-04-03-02-14-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/57ac9f63fc6953f4efeb0cc84a60192d3721251f

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=c91249f41e3766274131a84f9157a4d9d9949520&tochange=57ac9f63fc6953f4efeb0cc84a60192d3721251f

Last seen: <b>55.0a1 (2017-04-11)</b>
https://archive.mozilla.org/pub/firefox/nightly/2017/04/2017-04-11-03-02-08-mozilla-central
Built from https://hg.mozilla.org/mozilla-central/rev/f914d40a48009c5acd1093e9939cc0ec035696dd

---

* <tt>treeView.js:<b>173</b></tt>

First seen: <b>55.0a1 (2017-04-12)</b>
https://archive.mozilla.org/pub/firefox/nightly/2017/04/2017-04-12-03-02-52-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/f40e24f40b4c4556944c762d4764eace261297f5

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=f914d40a48009c5acd1093e9939cc0ec035696dd&tochange=f40e24f40b4c4556944c762d4764eace261297f5

Last seen: the latest Nightly.

**Comment by Lorienna** [comment]
Works for me. :+1:
