### ISSUE TITLE
palemoon master started to ignore fontconfig font selection preferences

### ISSUE THREAD

**Issue by l29ah** [MoonchildProductions/Pale-Moon#1021]
And maybe started to scale bitmap fonts, i'm not sure. It have occurred during the last 10 days.

**Comment by wolfbeast** [comment]
Which O.S.? Linux?

**Comment by l29ah** [comment]
Yes, Gentoo.

**Comment by wolfbeast** [comment]
Can you check if using the officially-built binaries also show this behavior? The unstable channel should have the same patch level as what you indicate.

**Comment by l29ah** [comment]
I don't see where to get nightlies for linux.

**Comment by l29ah** [comment]
Okay, after a few palemoon builds it seems like the problem is somewhere else in my system. Sorry for the noise.

**Comment by wolfbeast** [comment]
FTR: unstable official binaries can always be found from the relevant thread on the forum.
https://forum.palemoon.org/viewtopic.php?f=37&t=14482
