### ISSUE TITLE
Livemarks are lacking their special icons in the Bookmarks Manager

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1022]
For some reason, the livemarks are lacking their special icons in the Bookmarks Manager of Pale Moon, looking like the ordinary folders.
However, if the "Bookmarks Toolbar" is being selected in the left pane, upon adding a new livemark there, its special icon can be seen in the right pane. But should you select anything other than the "Bookmarks Toolbar", and go back again, you'll see that this new livemark now looks like a common folder.

This has been checked in Pale Moon for Windows 27.2.0, 27.2.1, and in the latest unstable.

<b>STR:</b>
1. Open the Bookmarks Manager;
2. Select the "Bookmarks Toolbar" in the left pane;
3. Add a new livemark to the "Bookmarks Toolbar", e.g. https://blog.mozilla.org/feed/
4. Look at the right pane of the Bookmarks Manager and see that the special icon is present;
5. Select any folder other than the "Bookmarks Toolbar";
6. Select the "Bookmarks Toolbar" in the left pane again;
7. Look at the right pane of the Bookmarks Manager and see...

<b>Actual results:</b>
...the icon of a common folder.

<b>Expected results:</b>
All the livemarks being iconized.

**Comment by wolfbeast** [comment]
Publishing a new unstable now, should be available within half an hour. Please check if this fixes your icons?

**Comment by Lorienna** [comment]
Yes, it does fix it, thank you. However, it looks like nobody else here except me uses this Pale Moon feature :) Is there a better alternative for this?

And btw, in all the builds I've checked there's still a Pale Moon-specific error <tt>uncaught exception: 2147500033</tt> upon clicking the "Subscribe Now" button on RSS page; I'm sure you're aware of it by now :)

**Comment by wolfbeast** [comment]
Thanks for verifying!

**Comment by Lorienna** [comment]
@janekptacijarabaci or someone, please take a look at [1190350](https://bugzilla.mozilla.org/show_bug.cgi?id=1190350), and kindly verify if there are any problems that might have been overlooked:

---

<b>Last iconified: `22.0a1 (2013-03-04)`</b>
https://archive.mozilla.org/pub/firefox/nightly/2013/03/2013-03-04-03-09-33-mozilla-central/
Built from http://hg.mozilla.org/mozilla-central/rev/86c98c4d36da

<b>First iconless: `22.0a1 (2013-03-05)`</b>
https://archive.mozilla.org/pub/firefox/nightly/2013/03/2013-03-05-03-08-33-mozilla-central/
Built from http://hg.mozilla.org/mozilla-central/rev/015da7030aab

<b>Pushlog:</b> https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=86c98c4d36da&tochange=015da7030aab

---

<b>Last iconless: `44.0a1 (2015-10-14)`</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/10/2015-10-14-03-02-23-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/2387ada864282880d3a498d643abe3d8b887ee59

<b>First iconified: `44.0a1 (2015-10-15)`</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/10/2015-10-15-03-02-33-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/e193b4da0a8c1025aa76a403c64663ff1cd41709

<b>Pushlog:</b> https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=2387ada864282880d3a498d643abe3d8b887ee59&tochange=e193b4da0a8c1025aa76a403c64663ff1cd41709

**Comment by janekptacijarabaci** [comment]
I do not see any problems.

**Comment by wolfbeast** [comment]
Why are you asking for anything additional? This was already fixed and verified.

**Comment by Lorienna** [comment]
Just in case :)

Have you been able to determine the cause of this regression, by the way?
