### ISSUE TITLE
Throws an error: uncaught exception: 2147500033 upon clicking the "Subscribe Now" button on RSS page

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1024]
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1022#issuecomment-294291346

> I've checked there's still a Pale Moon-specific error  uncaught exception: 2147500033  upon clicking the "Subscribe Now" button on RSS page.

Thank you. I've been thinking about it for a long time... But I found only this:

---

# 1)

`uncaught exception: 2147500033`
\==
`ERROR(NS_ERROR_NOT_IMPLEMENTED, 0x80004001)`

---

# 2)

Still bad: Firefox 44.0 (2016-01-26)
(it does not always!)

Firefox 45.0a1
from 2015-10-29:
Built from https://hg.mozilla.org/mozilla-central/rev/acb3f4ac5424181d3d4d73283668162137918cf1
to 2015-12-14:
Built from https://hg.mozilla.org/mozilla-central/rev/99137d6d4061f408ae0869122649d8bdf489cc30

Maybe:
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=acb3f4ac5424181d3d4d73283668162137918cf1&tochange=99137d6d4061f408ae0869122649d8bdf489cc30

throws an errors:
```
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111
(NS_ERROR_NOT_AVAILABLE) [nsIPrefBranch.setCharPref]
FeedWriter.js:1195:0
```
which is just before:
```
var feedService = Cc["@mozilla.org/browser/feeds/result-service;1"].
                  getService(Ci.nsIFeedResultService);
```
where this problem begins.

"First?" good: Firefox 45.0a2 (2015-12-14)
https://hg.mozilla.org/releases/mozilla-aurora/rev/e2031358e2a6d6d686b7a6b592d07cfb874bacae

http://hg.mozilla.org/releases/mozilla-aurora/pushloghtml?fromchange=0f9c2337da96fde3cc8f2c63200b56ee2578b6fd&tochange=e2031358e2a6d6d686b7a6b592d07cfb874bacae

(because I don't have anything better yet)

---

# 3)

This error occurs here:
https://github.com/MoonchildProductions/Pale-Moon/blob/27.2.1_Release/browser/components/feeds/FeedConverter.js#L492
because:
`iid.equals(Ci.nsIClassInfo)`
== Components.ID("`{986c11d0-f340-11d4-9075-0010a4e73d9a}`")

---

But I haven't found an entry point yet...

**Comment by wolfbeast** [comment]
Looks like the caller is https://github.com/MoonchildProductions/Pale-Moon/blob/27.2.1_Release/browser/components/feeds/FeedConverter.js#L400 (CreateInstance in the catch() block)
So it seems to occur that we don't have a shell service to use. The whole feedconverter/feedwriter setup is rather messy though, juggling sandboxes.

**Comment by Lorienna** [comment]
<blockquote>Thank you.</blockquote>

You are welcome.

## I.

<blockquote>throws an errors:

<tt>NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111
(NS_ERROR_NOT_AVAILABLE) [nsIPrefBranch.setCharPref]
FeedWriter.js:1195:0</tt></blockquote>

Mozilla has been testing [Electrolysis multi-processing](https://wiki.mozilla.org/Electrolysis) for a long time now, and this error in all its subtle diversity was thrown <b>in e10s-windows</b> of the earlier unstable builds. In these special windows, RSS pages were looking neutered to varying degrees _(leastways on my Win7x64 setup)_, with the never-working "Subscribe Now" button throwing <tt>0x80040111</tt>-type of errors when clicking it:

![36 0a1](https://cloud.githubusercontent.com/assets/26753987/25755995/c7a5cdaa-31cd-11e7-95cc-8fff90b38436.jpg)

<b>36.0a1 (2014-11-07) nightly "central" build</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/11/2014-11-07-03-02-02-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/17e190839086

<br>
...on other builds, however, RSS pages in e10s-windows seemed too dummy to even throw any kind of errors at all:

![43 0a2](https://cloud.githubusercontent.com/assets/26753987/25756133/4d656928-31ce-11e7-8c10-b63853cb3e57.jpg)

<b>43.0a2 (2015-10-06) "aurora" build</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/10/2015-10-06-00-40-17-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/7921dfde86c7355b614385c06d2d3cadf8c1da82

---

Initially, two preferences were introduced by Mozilla: <tt>layers.offmainthreadcomposition.enabled</tt> and <tt>layers.offmainthreadcomposition.testing.enabled</tt>, both set <tt>false</tt> by default. When later it became possible to open a new e10s-window via UI, a user had to set <tt>layers.offmainthreadcomposition.enabled</tt> to <tt>true</tt> to be able to open a new e10s-window from the drop-down main menu. Later, it became <tt>true</tt> by default, and afterwards the checkbox appeared in the _General_ tab of the modernized _Options_ menu to enable multi-processing. Today, [this preference seems to be outdated](https://www.reddit.com/r/firefox/comments/4j0tzz/what_happened_to/).

I've omitted the details here, although below's a glimpse of how it evolved:

---

Last unaffected: <b>23.0a1 (2013-04-10)</b>
https://archive.mozilla.org/pub/firefox/nightly/2013/04/2013-04-10-03-10-44-mozilla-central/
Built from: http://hg.mozilla.org/mozilla-central/rev/9db46ddfb517

First about-configured: <b>23.0a1 (2013-04-11)</b>
https://archive.mozilla.org/pub/firefox/nightly/2013/04/2013-04-11-03-09-25-mozilla-central/
Built from: http://hg.mozilla.org/mozilla-central/rev/2949e808ed33

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=9db46ddfb517&tochange=2949e808ed33

---

Last UI-less: <b>30.0a1 (2014-02-21)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/02/2014-02-21-03-02-02-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/7010ab83a06e

First UI-fied: <b>30.0a1 (2014-02-22)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/02/2014-02-22-03-02-04-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/84c9885475e7

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=31113754db3b&tochange=e3daaa4c73dd

UI-fied error: <tt>NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIPrefBranch.setCharPref] FeedWriter.js:1250</tt>

---

Last errorized nightly "central": <b>46.0a1 (2016-01-05)</b>
https://archive.mozilla.org/pub/firefox/nightly/2016/01/2016-01-05-03-02-11-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/29258f59e5456a1a518ccce6b473b50c1173477e

First error-free nightly "central": <b>46.0a1 (2016-01-06)</b>
https://archive.mozilla.org/pub/firefox/nightly/2016/01/2016-01-06-03-02-25-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/9d6ffc7a08b6b47056eefe1e652710a3849adbf7

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=29258f59e5456a1a518ccce6b473b50c1173477e&tochange=9d6ffc7a08b6b47056eefe1e652710a3849adbf7

Error: <tt>NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIPrefBranch.setCharPref] FeedWriter.js:1195:0</tt>

---

Last errorized "aurora": <b>45.0a2 (2016-01-19)</b>
https://archive.mozilla.org/pub/firefox/nightly/2016/01/2016-01-19-00-40-10-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/fa70a928f11132bd6d1d94399121ad96ef031426

First error-free "aurora": <b>45.0a2 (2016-01-21)</b>
https://archive.mozilla.org/pub/firefox/nightly/2016/01/2016-01-21-00-40-39-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/7fc6b3d4c26f654144e4c7b90702b91f3ad31ea7

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=fa70a928f11132bd6d1d94399121ad96ef031426&tochange=7fc6b3d4c26f654144e4c7b90702b91f3ad31ea7

Error: <tt>NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIPrefBranch.setCharPref] FeedWriter.js:1195:0</tt>

---

...and the problematic line in <tt>FeedWriter.js</tt> is always this:

<tt>prefs.setCharPref(getPrefReaderForType(feedType), "bookmarks");</tt>

## II.

In a <b>normal, NON-e10s</b> window, the error evolved like this:

Last errorless: <b>32.0a1 (2014-05-21)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/05/2014-05-21-03-02-00-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/9d8d16695f6a

First <tt>uncaught exception: 2147500033</tt>: <b>32.0a1 (2014-05-22)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/05/2014-05-22-03-02-04-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/b40296602083

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=9d8d16695f6a&tochange=b40296602083
_(<b>Note:</b> there's a line <b><tt>Bug 1003839 - Live bookmark is still created despite cancelling the subscription.</tt></b>)_

---

Last <tt>uncaught exception: 2147500033</tt>: <b>36.0a1 (2014-11-06)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/11/2014-11-06-03-02-01-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/2114ef80f6ae


First <tt>uncaught exception: 2147500033 < unknown ></tt>: <b>36.0a1 (2014-11-07)</b>
_(<b>Note: this is the exact flavor of the error currently being thrown in Pale Moon.</b>)_
https://archive.mozilla.org/pub/firefox/nightly/2014/11/2014-11-07-03-02-02-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/17e190839086

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=2114ef80f6ae&tochange=17e190839086

---

Last <tt>uncaught exception: 2147500033 < unknown ></tt>: <b>41.0a1 (2015-06-16)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/06/2015-06-16-03-02-01-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/ce863f9d8864

First <tt>uncaught exception: 2147500033 FeedWriter.js:1284:27</tt>: <b>41.0a1 (2015-06-17)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/06/2015-06-17-03-02-05-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/d7c148c84594

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=ce863f9d8864&tochange=d7c148c84594

---

Last <tt>uncaught exception: 2147500033 FeedWriter.js:1284:27</tt>: <b>43.0a1 (2015-09-18)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-18-03-02-02-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/11dc79e232110ba6de5179e46dfbda77b52a88c3

First <tt>uncaught exception: 2147500033 FeedWriter.js:1203:27</tt>: <b>43.0a1 (2015-09-19)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-19-03-02-07-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/4313752f69956ae248bd4e7ff3913c8dd4252698

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=11dc79e232110ba6de5179e46dfbda77b52a88c3&tochange=4313752f69956ae248bd4e7ff3913c8dd4252698

---

Last <tt>uncaught exception: 2147500033 FeedWriter.js:1203:27</tt>: <b>43.0a2 (2015-10-06)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/10/2015-10-06-00-40-17-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/7921dfde86c7355b614385c06d2d3cadf8c1da82

First <tt>uncaught exception: 2147500033 FeedWriter.js:1198:27</tt> : <b>43.0a2 (2015-10-07)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/10/2015-10-07-00-40-48-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/ef920d4dd41c3e1554429fbe362d169d7592a291

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=7921dfde86c7355b614385c06d2d3cadf8c1da82&tochange=ef920d4dd41c3e1554429fbe362d169d7592a291

And then <tt>1198:27</tt> continues until the release of <b>FF 43.0</b>, apparently.

---
---

And there's the separate "central" <b>44.0a1</b> brunch which opens by the first 3 builds throwing <tt>1203:27</tt> error, while the following ones starting to throw <tt>1198:27</tt>:

First <tt>uncaught exception: 2147500033 FeedWriter.js:1203:27</tt>: <b>44.0a1 (2015-09-21)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-21-07-34-55-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/039a8490891595736b16a3ccb17f025f4dcf13eb

---

Last <tt>uncaught exception: 2147500033 FeedWriter.js:1203:27</tt>: <b>44.0a1 (2015-09-23)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-23-03-02-30-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/19b4265d0d568d232fb3a34705f947b6db7496dc

First <tt>uncaught exception: 2147500033 FeedWriter.js:1198:27</tt>: <b>44.0a1 (2015-09-24)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-24-03-02-31-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/bf2bc1aa78c0b72d9b6b13f7a8c6ae61c60a51dc

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=19b4265d0d568d232fb3a34705f947b6db7496dc&tochange=bf2bc1aa78c0b72d9b6b13f7a8c6ae61c60a51dc

---

Last <tt>uncaught exception: 2147500033 FeedWriter.js:1198:27</tt>: <b>45.0a1 (2015-12-03)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/12/2015-12-03-03-02-26-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/31fc97d173b3e3da5de35d54018855e6c905787e

First errorless: <b>45.0a1 (2015-12-03)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/12/2015-12-03-05-35-21-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/85cf2e720a8405c43eabc9b34cce381b66d25ef9

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=31fc97d173b3e3da5de35d54018855e6c905787e&tochange=85cf2e720a8405c43eabc9b34cce381b66d25ef9

---

...and problematic piece, apparently, is always this:

<blockquote><tt>var feedService = Cc["@mozilla.org/browser/feeds/result-service;1"].
                  getService(Ci.nsIFeedResultService);</tt></blockquote>

---

<b>Conclusion:</b> error <tt>uncaught exception: 2147500033</tt> was <b>not</b> the Pale Moon-specific error ad initium. :)

**Comment by Lorienna** [comment]
@janekptacijarabaci 


Looks like the original RSS page header:

![old](https://cloud.githubusercontent.com/assets/26753987/26049791/e46b1fdc-3964-11e7-886e-01c4e2e6e241.png)


...was changed to this one:

![new](https://cloud.githubusercontent.com/assets/26753987/26049814/01759ff8-3965-11e7-9970-1ad23583c005.png)


Although I prefer the laconic brevity of the latter one, cannot help but wondering why was it nessesary to do that?

**Comment by janekptacijarabaci** [comment]
@Lorienna 
It's not a bug, it's a property of Pale Moon (and Firefox) :-)

See: `about:config`
`browser.feeds.showFirstRunUI`

You can reset this value.

**Comment by Lorienna** [comment]
Sorry, now I see :) 

Thanks for making it clear.
