### ISSUE TITLE
Add WebP support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#103]
WebP support is actually on the rise again, so it's time to add an implementation of it.
0.3.0 supports animation which is a must-have if we want to replace animated gifs, but for the moment focus on decoding the base formats only.

-> G branch

**Comment by jpenguin** [comment]
Yes, it improved a lot since it was first proposed (and rejected)

**Comment by wolfbeast** [comment]
0.3.0 was problematically patched, focusing on 0.2.1 lossy+lossless+alpha decoder-only support first.
(which would be Chrome/Opera parity)

**Comment by wolfbeast** [comment]
So.. after trying both 0.3.0 and 0.2.1 I'm still having the issue that everything works except for the actual decoding :(
"The image '{filename}' cannot be displayed because it contains errors" is all I get when trying in the portable test setup I use... Please see the relevant branches - if anyone has an idea why it doesn't work as it should, then I'm all ears because I'm kind of brickwalling here.

**Comment by jpenguin** [comment]
I have minimal coding knowledge, but I'll take a look at it tomorrow.  Maybe the latest Firefox patches could help though https://bugzilla.mozilla.org/show_bug.cgi?id=856375

**Comment by wolfbeast** [comment]
I've been porting those patches, actually. And repairing some obvious mistakes in them that made it fail building on Windows. I have the feeling I'm overlooking something really simple here, so just a fresh pair of eyes may help.

**Comment by wolfbeast** [comment]
It's been something really simple. As I thought.
The problem was that I fixed a crash bug due to async decoding a while back, and needed to port the same change over to the ported patches to make it work, otherwise the calls are incorrect (and simply don't do anything).

**Comment by Axiomatic-** [comment]
There is a patch for WebP 4.2 for Firefox [here](https://groups.google.com/a/webmproject.org/forum/#!topic/webp-discuss/VTdSMSw0nRc). Not sure if it will be any harder to port, but since it is the newer version of WebP I am just noting it here.

**Comment by wolfbeast** [comment]
Actually a patch like that is completely useless since I've already implemented it! Also, it's a diff against the Mozilla tree from March which is a far cry from what we are currently at as far as e.g. build system files goes, etc, so it'd be rather pointless.
It'll have to be applied and diffed on top of our current state to be useful.

**Comment by wolfbeast** [comment]
I;ve pinged the person who posted the 0.4.3 patch, and will have to examine the interface changes to apply it. With that, we should eb good on WebP support, although animations and color profiles are not implemented.

**Comment by Axiomatic-** [comment]
So as of now there is there a working WebP 0.3.0 implementation in Pale Moon (by working I mean just parity to Chrome/Opera as you mentioned) or is it a WebP 0.2.1 implementation?

**Comment by wolfbeast** [comment]
Currently the branch has 0.3.0 merged in.
There is no support for animation because that would take a lot more tricky work. 0.4 would also not enable these, but would provide better decoding of more kinds of WebP files. I tested 0.2.1 (which is Chrome/Opera parity) and ran into the same problem that I fixed and then applied to 0.3.0 as well, to merge the latter in. (see 0.2.1 branch that dead-ends, vs. libwebp-work branch that was merged)

**Comment by wolfbeast** [comment]
Libwebp 0.4.3 has been merged in in commit 39812d09854aa850553b6256cd199d23a3d8f32b. This should bring us completely up-to-date (including encoder support) with the WebP format for quite a while to come.

**Comment by wolfbeast** [comment]
Some build bustage issues as discussed on the forum should now all be fixed with commit dd2bb29
Please build and verify on linux?

**Comment by Axiomatic-** [comment]
The Goanna branch built correctly on my custom kernel running Linux 4.0.6-1, and GCC 5.1.0. See the image below for visual conformation of WebP images displaying correctly. 
![Image of WebP decoder working.](https://i.imgur.com/6f3IBFT.png?raw=true)

**Comment by trav90** [comment]
All good here with CentOS and GCC 4.7.2

**Comment by wolfbeast** [comment]
Fantastic! Considered solved and verified :)
