### ISSUE TITLE
Yet another video playing issue

### ISSUE THREAD

**Issue by sergeevabc** [MoonchildProductions/Pale-Moon#1034]
27.2.1 x64

1. Open [specific page][1].
2. Scroll down a bit and try to play one of videos listed.
3. If “Enable MSE for MP4 video” is on, then error is reported instead of expected playback.

![](https://vgy.me/2fpPn7.png)

[1]: http://russnov.ru/voskresnyj-vecher-s-vladimir-solovevym-16-04-2017/

**Comment by trav90** [comment]
Known issue. Should be fixed by #1033.

**Comment by sergeevabc** [comment]
Fixed in 27.4.0a1.
