### ISSUE TITLE
Pretty-print the bookmarks HTML output, please

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1046]
Pretty-print the bookmarks.html content during the export, please, and if it's not too inconvenient for you, kindly prompt on Bugzilla to do the same.
Because for an average user it's rather difficult now after this tiny regression to check and edit the file manually, especially if it's large.

FYI: The file was beautified in Pale Moon 26.5.0, likewise in other earlier releases of Mozilla-based browsers.

**Comment by wolfbeast** [comment]
Please be more specific. It's completely unclear what you mean here -- the bookmarks export process is silent; it will just write out a file, there is no display during export.

Please provide exact information, steps to reproduce, add screenshots if it's useful to illustrate...?

**Comment by Lorienna** [comment]
Sorry, I thought it was obvious...

<b>STR:</b>
1. Open Pale Moon 27+ or e.g. any recent FF release;
2. Open the Bookmarks Manager there;
3. Import the bookmarks;
4. Export the bookmarks into HTML;
5. Open the bookmarks.html file in Notepad.

<b>Actual result:</b>

Unwrapped, it looks like this:

![later](https://cloud.githubusercontent.com/assets/26753987/25305407/36670128-2783-11e7-9488-de3ba2a89335.jpg)

<b>Expected result:</b>

It should look like this being unwrapped:

![former](https://cloud.githubusercontent.com/assets/26753987/25305427/83eee62c-2783-11e7-95df-e52277eb2b2a.jpg)

**Comment by JustOff** [comment]
@Lorienna, try [better Notepad](https://notepad-plus-plus.org/).

**Comment by wolfbeast** [comment]
The problem is that notepad doesn't like Unix-style line endings (which is the default for pretty much everything in Mozilla-land).

You can try a different text editor that understands this, as suggested, or you can (alternatively) process the exported bookmarks file with a tool or command to convert line endings. Conveniently, windows' `more` command offers this option:

`more /P <input_file >output_file`
e.g.:
`more /P <bookmarks.html >bookmarks_fixed.html`

**Comment by wolfbeast** [comment]
Should be simple enough to make it conditional based on system info -- and write CRLF on Windows systems, and LF on others.

**Comment by Lorienna** [comment]
Thank you! Until the next milestone, then.
