### ISSUE TITLE
Add TLS 1.3 support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1057]
Main implementation is in PR #1055 

Verification needed for various TLS versions:
- [ ] TLS 1.0 (older servers)
- [ ] TLS 1.1 (anyone know of a testcase?)
- [x] TLS 1.2 (mainstream)
- [x] TLS 1.3 (new services)

**Comment by janekptacijarabaci** [comment]
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1337791
But it is not implemented.

Maybe it would be good to look at it. I personally do not plan to make a PR.

**Comment by wolfbeast** [comment]
Not necessary. HTTP shouldn't be tasked to perform DNS tasks. Draft-based httpbis extensions are really not crucial, especially this kind of stuff. On top, it could be abused to snoop on/find out addresses of origin servers of traffic. So not without its security/privacy risks.

**Comment by wolfbeast** [comment]
SSLLabs provides basic feedback on all four protocol versions being OK after I fixed the issues with a clobber.

Live website testing is required. I'll update the unstable channel with this enhancement today.

**Comment by wolfbeast** [comment]
TLS 1.2 tested OK on various sites both with CBC and GCM modes, AES and Camellia.

**Comment by janekptacijarabaci** [comment]
> TLS 1.1 (anyone know of a testcase?)

`security.tls.version.max` = `2`

I have no other idea.

**Comment by wolfbeast** [comment]
I meant does anyone know of a test-case where a server doesn't support TLS 1.2, but does support 1.1?

**Comment by janekptacijarabaci** [comment]
TLS 1.0 yes, TLS 1.1 unfortunately no.

**Comment by wolfbeast** [comment]
TLS 1.3 verified with Cloudflare and Mozilla services.

**Comment by janekptacijarabaci** [comment]
TLS 1.3 see also: https://devhub.io/

**Comment by wolfbeast** [comment]
devhub.io uses cloudflare. It's not separate.

**Comment by janekptacijarabaci** [comment]
Test backward compatibility (SSL3 - vulnerable):
`security.ssl3.rsa_rc4_128_sha` - true
https://lotus.visotec.pl/

Do these settings (`security.ssl3`...) still make sense?
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1127339

**Comment by wolfbeast** [comment]
lotus.visotec.pl negotiates TLS 1.2 and AES-GCM...

**Comment by janekptacijarabaci** [comment]
> lotus.visotec.pl negotiates TLS 1.2 and AES-GCM...

Now... Yes. At the time of writing - no.

**Comment by wolfbeast** [comment]
I haven't seen any issues so far. If there are specific https issues as a result of this, open a new issue.

**Comment by janekptacijarabaci** [comment]
Ad `UXP-task` - see also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1337791
