### ISSUE TITLE
comit 8b3e92a broke site icetrade.by

### ISSUE THREAD

**Issue by Feodor2** [MoonchildProductions/Pale-Moon#1059]
regarding https://forum.palemoon.org/viewtopic.php?f=12&t=15299

These code pile do affect
`  if (aType == MIN_ISIZE &&
     (((styleISize.HasPercent() || styleMaxISize.HasPercent()) &&
       aFrame->IsFrameOfType(nsIFrame::eReplacedSizing)) ||
     (styleISize.HasPercent() &&
      aFrame->GetType() == nsGkAtoms::textInputFrame))) {
`
After i restored it to previous, the site problem was gone. Notice that there is no problem with other browsers. It is to find more sites with similar elements to test.

**Comment by JustOff** [comment]
See #786.

**Comment by JustOff** [comment]
Last bad: 2016-02-24
First good: 2016-02-25
Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=5b2baa5e9356644a7ed0b73e422eaff62e159ffb&tochange=918df3a0bc1c4d07299e4f66274a7da923534577

**Comment by JustOff** [comment]
Probably https://bugzilla.mozilla.org/show_bug.cgi?id=1250342

**Comment by janekptacijarabaci** [comment]
@JustOff 

:+1:

**Comment by JustOff** [comment]
@janekptacijarabaci 
It seems my initial guess was wrong and actually the fix is https://bugzilla.mozilla.org/show_bug.cgi?id=1247929, but since you ported  both of them it solves the case. Nice shot!
