### ISSUE TITLE
[Compatibility] Cloudflare can't handle Cloudflare website properly

### ISSUE THREAD

**Issue by yoursoftwarebug** [MoonchildProductions/Pale-Moon#1061]
1. Log in to https://www.cloudflare.com
2. On your account, click any button, such as "DNS" blue box.
3. Nothing happens - DNS box is just spinning.

But when I use latest Firefox, Cloudflare show webpage normally. It is clear that palemoon failed to handle this website.

**Comment by JustOff** [comment]
Can't confirm, worksforme.

**Comment by wolfbeast** [comment]
I use cloudflare's interface very regularly. Today even because of release -- never an issue.

**Comment by wolfbeast** [comment]
Closing for now as WFM. Please go to the forum to ask for assistance if you can't get it to work. If it turns out to be a bug in the browser somehow from discussions there, this can be re-opened.
