### ISSUE TITLE
WDR Mediathek is not watchable (Flash Video)

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/Pale-Moon#1070]
Version: 27.3.0 (64-bit)
Linux Mint 18.1 (Ubuntu 16.04)
Tried to start the video on the top of the page.
It doesn't start.
(Same error on previous version)

[http://www1.wdr.de/fernsehen/tiere-suchen-ein-zuhause/sendungen/uebersicht-tiere-suchen-ein-zuhause-230.html](http://www1.wdr.de/fernsehen/tiere-suchen-ein-zuhause/sendungen/uebersicht-tiere-suchen-ein-zuhause-230.html)

**Comment by janekptacijarabaci** [comment]
Have you used a "pop up"?

![1](https://cloud.githubusercontent.com/assets/2373486/25580472/8a37fc1c-2e81-11e7-90d0-3a74d1d5b0fe.png)

**Comment by MartinX3** [comment]
I already activated flash, of course

**Comment by Atavic** [comment]
Not only Flash:

```
/*!
 * JavaScript: Embedding Videos with iFrames
 * Umsetzung: WDR mediagroup digital GmbH, Koeln
 * (c) 2017
 * Date: 20170309
 * Version 2.1.1 b08
 */
```

**Comment by MartinX3** [comment]
Every JavaScript is allowed, if you ask.

**Comment by Atavic** [comment]
I looked at the site and there's a lot of scripts. Maybe there's a resctriction based on the User Agent string?

I too can't start the video on various browsers (all based on gecko) that are hardened and optimized for a few sites I use.

**Comment by wolfbeast** [comment]
I've just tested this on Win7 with 27.3.0 x86, no issues. It runs the flash player with a control layer overlayed on top.
![image1](https://cloud.githubusercontent.com/assets/3359132/25890276/381eb0c2-356d-11e7-8951-d05dd0628907.png)

**Comment by MartinX3** [comment]
Maybe, if you use Linux Mint 18.1 (Ubuntu 16.04), this problem happens.

And on my system is the "adobe-flashplugin" package installed
From DL-Flash Player Ubuntu <FlashPlayerUbuntu@adobe.com>
Version 1:20170509.1-0ubuntu0.16.04.1

**Comment by JustOff** [comment]
I see no flash at all on this page and html5 player works well for me on both win7 & linux.

**Comment by MartinX3** [comment]
There is no HTML5 player
There is only a flash player at the top of the screen

**Comment by JustOff** [comment]
Hm ... looks like this page design confused me. Then I've to say it works well on both win7 & linux (mint 17).

**Comment by trav90** [comment]
It works for me as well with Flash enabled.

**Comment by MartinX3** [comment]
How i can investigate, what is wrong with my browser setup?
what do you need?

**Comment by wolfbeast** [comment]
@MartinX3 you might have better luck troubleshooting on the forum. Since this isn't a browser issue as far as we can tell, I'll be closing this as WFM.

**Comment by MartinX3** [comment]
Found a solution.
The PaleMoon Browser Addon "Encrypted Web v5.1.5" is causing the trouble.
Disabling it let me watch the video.
Maybe there are some parts of the website which can't be access by https.
The plugin is a fork from https://www.eff.org/https-everywhere.

**Comment by wolfbeast** [comment]
Thanks for the follow-up.

**Comment by MartinX3** [comment]
It was my pleasure, I hope it helps others, who maybe get the same problem.
