### ISSUE TITLE
Implement auto-recovery module

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1073]
We need a way to automatically recover from a few disaster scenarios. One important one being incorrect language packs, another being extensions that prevent startup.

Hooking this into the web progress listener in a separate XUL context is an easy way to catch these errors (previously this was hacked into padlock.js, but that's not a safe place to do so).

@JustOff -- you mentioned a check to see if we're running in Safe Mode or not. Do you know off-hand how that can be checked programmatically?

**Comment by JustOff** [comment]
> Do you know off-hand how that can be checked programmatically?

Services.appinfo.inSafeMode
