### ISSUE TITLE
SVG <use> elements misaligned in some cases.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1076]
e.g. misaligned stars on the USA flag at:
https://upload.wikimedia.org/wikipedia/commons/0/05/US_flag_51_stars.svg

This is caused by the use of inaccurate display lists in SVG -- a very long-standing bug in Mozilla code.

Workaround: 01f632951f482a6202fd04ce41bd18e7db33579c 

Keeping an eye on https://bugzilla.mozilla.org/show_bug.cgi?id=844258 for a potential permanent solution in display list/SVG code.

**Comment by Atavic** [comment]
Interesting issue. I take the occasion to thank the people in this repository because I learned alot just by reading thre comments. Feel free to delete my comment, as it is simply a plause for your work and nothing more.

**Comment by wolfbeast** [comment]
Note, the workaround will cause issues because non-display-list paths have NOT been kept updated by Mozilla and there are an unknown number of issues with it.

**Comment by wolfbeast** [comment]
The misalignment occurs with very large scale factors (the flag uses a 650x scale!). It's a rounding/precision issue.

Analysis of what's happening here:

It seems that Mozilla code uses a precision of 1/60 of a pixel for the displacement lengths when replicating the stars, so, for example, 0.0448 becomes 0.0333.  This 0.0115 px error may not seem like much, but when multiplied by a scale factor of 650 it becomes more than 7 px, and after several accumulated errors the discrepancy in spacing sizes becomes apparent.

I'm not sure if this should be fixed by us or if the creator of the SVG is at fault for using such small scales.

**Comment by janekptacijarabaci** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1361366#c0

IMHO is a bug. More accurate numbers can be obtained.

**Comment by wolfbeast** [comment]
The question is where this precision is determined. The SVG code is not the easiest to read, and is very poorly documented.

**Comment by janekptacijarabaci** [comment]
Maybe (AFAIK) it's here somewhere:
https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/layout/svg/nsSVGUseFrame.cpp#L193
https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/layout/base/nsLayoutUtils.cpp#L2123
https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/gfx/2d/BaseRect.h#L467

There is a lot of rounding, i.e. `float` -> `double`.

**Comment by wolfbeast** [comment]
`float` -> `double` increases precision, so that won't round anything.

The line numbers indicated are all about placing/snapping the whole image/rect to whole pixels (which is what we want). It has to be further into the SVG path calculations. Since not using display lists does this correctly, there has to be an issue with the precision of placing display list elements inside the SVG code.

**Comment by wolfbeast** [comment]
What it boils down to here is that fast integer math is being used for layout, not floats, not doubles. Everything is translated to "application pixels" which Mozilla has set to 1/60 of a CSS pixel. While this suffices in most cases for normal layout, it is also dangerously close to the precision limit for anything that is scaled down, and even more so for vector graphic that in general assume real numbers being in use everywhere to scale without loss, also into fractions of pixels.

Setting this arbitrary resolution to, e.g. the initially-proposed 1/720th of a CSS pixel should correct all common cases of misalignment-by-rounding. it will only leave the small corner cases where designers have chosen arbitrarily large or small numbers to work with that have no reflection on actual presentation sizes.

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
I give a warning: Browser's menu toolbar does not work after this change (clicking it will not do anything)!

**Comment by JustOff** [comment]
I am also concerned about the possible impact on performance ...

**Comment by janekptacijarabaci** [comment]
> I am also concerned about the possible impact on performance ...

Unfortunately it is so...
![windows-has-detected-that-your-computers-performance-is-slow](https://cloud.githubusercontent.com/assets/2373486/26006016/3a3ac09c-373b-11e7-8e9d-819e0ed089df.png)

**Comment by wolfbeast** [comment]
There shouldn't be any performance impact since all that was done is change the size of application units.

**Comment by wolfbeast** [comment]
I'm reverting the commit for now - there are clearly a few odd things going on. the whole point of having these units is so that the rest of the application's layout is independent of internal measurements, but it looks like a few things were overlooked that cause the classic menu bar (and possibly others) to be drawn in incorrect locations and/or with incorrect sizes.
Side effect for performance *may* be too large size layers.

**Comment by janekptacijarabaci** [comment]
> There shouldn't be any performance impact

For some reason apparently it has an impact on the performance. This may or may not be related to another bug. I don't know.

**Comment by wolfbeast** [comment]
The smart approach here to prevent anything from going awry is to keep the application pixels at what we have now, but to stop using integer math and use (commonly 32-bit) floats. There shouldn't be any performance impact in real-world scenarios, and fast FP math can be expected on any reasonably supported CPU.

**Comment by wolfbeast** [comment]
Closing this - it won't be solved on v27 -- further handling in https://github.com/MoonchildProductions/UXP/issues/437
