### ISSUE TITLE
"Delete all bookmarks except for backups" in Safe Mode doesn't work

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1083]
Ad https://forum.palemoon.org/viewtopic.php?f=57&p=113494

It will restore bookmarks, but the following line:
```
Services.prefs.setBoolPref("browser.bookmarks.restore_default_bookmarks", false);
```
...it will turn back again (respectively - it will be evaluated earlier).

If it is omitted, it works.

Why?

See also:
https://github.com/janekptacijarabaci/Pale-Moon/tree/_testBranch_places_bookmarks_restore

**Comment by wolfbeast** [comment]
Once the bookmarks are restored, this flag must always be reset. it's a one-shot state. So yes, that is 100% correct.

flag set -> if (flag) { reinstate bookmarks + reset flag }

**Comment by janekptacijarabaci** [comment]
Yes, but it was not a problem. This problem was that `browser.bookmarks.restore_default_bookmarks`,`true` was ignored (as though).

**Comment by wolfbeast** [comment]
Can you let me know then what the exact behavior is now?

**Comment by janekptacijarabaci** [comment]
That it is done independently by `Task.spawn`. I have used it several times, e.g.:
https://github.com/greasemonkey/greasemonkey/pull/2262
