### ISSUE TITLE
Post-Australis AMO Integration features missing from Pale Moon

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1094]
FF:
<img width="1234" alt="2017-05-11 20_15_16-calculator" src="https://cloud.githubusercontent.com/assets/15178410/25955392/b7e5206e-369b-11e7-9249-8f3a8aa0f3c5.png">

PM:
<img width="1234" alt="2017-05-11 20_15_51-calculator" src="https://cloud.githubusercontent.com/assets/15178410/25955395/bb1d434c-369b-11e7-9040-86482639dad9.png">

**Comment by mattatobin** [comment]
Pale Moon has not acceded to Mozilla's latest integration features and indeed is attempting to untangle any remaining integration with Mozilla that may still exist.

tl;dr never had it and won't in the future by design

**Comment by wolfbeast** [comment]
Requesting that information also relies on sending AMO telemetry data which is not a thing we do.
