### ISSUE TITLE
Please fix the blocklist for 27.3.0 and unstables

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1095]
There are errors like these in the Browser console:

<tt>XML Parsing Error: mismatched tag. Expected: < /hr >.
Location: http://blocklist.palemoon.org/27.4.0a1/blocklist.xml
Line Number 6, Column 3:1 blocklist.xml:6:3</tt>

<tt>The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.1 blocklist.xml</tt>

<tt>GET http://blocklist.palemoon.org/favicon.ico [HTTP/1.1 404 Not Found 69ms]</tt>

<tt>GET http://blocklist.palemoon.org/favicon.ico#-moz-resolution=20,20 [HTTP/1.1 404 Not Found 69ms]</tt>

**Comment by mattatobin** [comment]
That doesn't matter for unstable versions. However, if it is not working with current release then that is indeed an issue.

**Comment by JustOff** [comment]
That's [normal](https://github.com/MoonchildProductions/Pale-Moon/issues/715#issuecomment-262977956).

**Comment by mattatobin** [comment]
Release versions should always have a valid blocklist where-as http://blocklist.palemoon.org/27.3.0/blocklist.xml 404's.

As I said previously, unstable builds don't need it.

**Comment by wolfbeast** [comment]
27.3.0 doesn't 404 -- shouldn't anyway because the file is there.

**Comment by wolfbeast** [comment]
I'll see about making a better construction with try_files on the server to make sure nonexistent versions are served empty XMLs

**Comment by wolfbeast** [comment]
Please check if it works any more acceptably now.

**Comment by JustOff** [comment]
Yes, it's even better.

**Comment by mattatobin** [comment]
Could have been a bad cache entry on CF side. Works now but I tried earlier and it was deff a 404.

**Comment by Lorienna** [comment]
All's better that ends better, as they say, and the blocklist for 27.3.0 isn't 404 anymore, thank you.

<blockquote>unstable builds don't need it.</blockquote>

Why?

**Comment by wolfbeast** [comment]
Unstable builds don't need it because the builds themselves are going to be updated more regularly than the blocklist.
