### ISSUE TITLE
Unstable: Strange error message on quite a number of pages in the status bar

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1096]
Getting since quite a while in the unstable builds some error message when loading pages: "an unknown error has ocured". Number is not always the same, this is just an example which happened when i was reloading the Google startpage.

![detail-error](https://cloud.githubusercontent.com/assets/25885496/26009174/e8923592-3747-11e7-8960-f13b9e318808.jpg)

Happens in all kind of pages, like Youtube, Hotmail, Gmail, even on simple pages like http://www.pouet.net i have seen it today.

Perhaps anyone has some idea what that is? No logged entry in the error console either, which could give some light into that strange thing, but other than that, the pages still do load, only that strange error is sometimes appearing in the page loading status.

Not present in the stable version.

**Comment by Atavic** [comment]
No problems for me, site's on GH... [here](https://github.com/pouetnet/pouet2.0/issues).

**Comment by FranklinDM** [comment]
The error also appears for me even when visiting the forum. I think it started when TLS 1.3 was implemented (stable doesn't have it yet)
![untitled](https://cloud.githubusercontent.com/assets/11641537/26021832/77496622-37c8-11e7-8365-4417d3b1784c.png)

**Comment by Sa-Ja-Di** [comment]
Works now, no error message anymore after the new update and that fix which was inserted, thanks :1st_place_medal:  ;)
