### ISSUE TITLE
Bookmark tag completion is broken

### ISSUE THREAD

**Issue by nobrowser** [MoonchildProductions/Pale-Moon#1100]
In Firefox, when I create a new bookmark with Control-D and start filling in the properties, I can start typing a tag name and it will auto-complete to a full existing tag, plus maybe a drop-down list of secondary matches if there is more than one match.  Hitting Tab or End puts the cursor at the end of the completion, so I can type a comma and start typing the next tag, etc.  At least this is how it worked with the last Firefox versions I used (around 45 or so).

In Pale-Moon, it looks as if someone had an idea to improve this, but in fact they made it unusable for me.  The completion list is now not for the single tag I am typing, but for **all combinations** of tags that start with my incomplete input.  Most of the time the first match will be some very long combination of tags that I definitely don't want to set for this new bookmark _in toto_ , and worse, all the visible items in the drop-down list will be such combinations, so I cannot even easily select the single tag from the drop-down.

Maybe an example is in order.  I am creating a new bookmark which I want to have the tags "Chess , Games , Web" (and no others).  In Firefox, I would do this:

"Che" - Firefox auto-fills "Checkers" but also shows a drop-down where "Chess" is the second item.  I select this item by hitting Down twice, and Firefox now auto-fills "Chess" in the entry field. I hit End, Space, Comma, Space, and start typing the second tag "Ga".  This time "Games" is the only match, so Firefox auto-fills it and I can immediately hit End, Space, Comma, Space to start entering the third tag with "We".  There are two matches "Web" and "Weekend" but "Web" is the first one so it is auto-filled.  I hit End, Enter, and I'm done.

If I try the same sequence with Pale-Moon, after I type "Che", the browser auto-fills something like "Checkers,Games,Web,Money" and the first few items in the drop-down will be like "Chess,Games,Strategy,Web" , "Chess,Entertainment,Strategy" etc. , because these are the combinations of tags that already existing bookmarks have.  This is not useful, because it is far more typing work to trim such combinations to remove the unwanted extra tags than it is to type the tags I do want, one after another.

What's worse, after I enter "Chess , " and start entering the second tag with "Ga", the browser now auto-completes and displays all existing combinations starting with "Games" - including the ones where "Chess" already occurs!  There is simply no chance that any of these choices will be correct.

Maybe I missed a config switch enabling the Firefox behavior?  Or maybe this is just a bug?  But if it is as intended, please consider that it sucks for this user.

Thanks.

**Comment by janekptacijarabaci** [comment]
Not confirmed. For me it works ok when using:

(1) A new bookmark:
Tags: `Checkers,Games,Web,Money`
(2) A new bookmark:
Tags: `Chess,Games,Strategy,Web`
(3) A new bookmark:
Tags: `Che`...:
![1](https://cloud.githubusercontent.com/assets/2373486/26089447/20e431f8-39fe-11e7-87d3-1fdba256c0ff.png)

> Maybe I missed a config switch enabling...?

AFAIK: I cannot see any settings.

---

You can also try in anew profile.

**Comment by nobrowser** [comment]
I tried it in a fresh profile, and it also works for me 8-0  Now what?  How can I narrow down the cause?

I have backups of the bookmarks.  Will deleting all bookmarks from the Organize dialog wipe out the database and start from fresh?  I could try that and then restore from the backup.

**Comment by wolfbeast** [comment]
Try making a full bookmark backup in your existing profile, and restoring that in the new profile, to see if it is actually an issue with tags stored in the db or something else in your profile.
If they also show up "glued together" in the new profile after importing then I'm afraid they are incorrectly stored in the db in your current profile and the only way around that would be to mangle the data (e.g. run a tool over the json export to split things out)

**Comment by nobrowser** [comment]
@wolfbeast  , that was an excellent idea.  Did that and saw it was okay in a new profile even after importing the backup.  So I just re-imported that backup into my regular profile, and now it's "fixed"! Yay!

I have no idea what could've caused that, though.  sqlite problem maybe?

**Comment by nobrowser** [comment]
Maybe I should note that the bookmark database came directly from my Firefox profile when I switched, I didn't do any migration, maybe I should have?

**Comment by wolfbeast** [comment]
It depends on what version of Firefox you took the db from. Quite possible a one-way db migration on the Firefox end screwed up compatibility.
