### ISSUE TITLE
Windows 10 should have a solid top window border

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#1101]
As part of work for #149, support for Windows 10's custom caption buttons were added. It's bugged me for a while, but I finally managed to find out why we aren't able to visually reproduce the same effect as in upstream on Windows 10: we don't seem to manipulate the top window border correctly. This isn't so much an issue if the titlebar is transparent, however if there is an image there (either a `background-color` or a persona) it becomes more noticeable:

![Windows 10 borders](http://i.imgur.com/dWZwwth.png)

It appears that this work was completed [here](https://hg.mozilla.org/releases/mozilla-aurora/rev/001ba3f6d572) as part of bug [1173725](https://bugzilla.mozilla.org/show_bug.cgi?id=1173725), and while we incorporate parts of this bug we don't seem to include the linked patch which fixes this issue.

**Comment by wolfbeast** [comment]
Applying that change will break hover for the window buttons.

**Comment by Lootyhoof** [comment]
In what way? I would've figured that since we control the caption buttons on Windows 10 that we could manipulate them however we need. If it breaks things re: our overlaying the system-drawn ones, I'm currently keeping a close eye on some Mozilla bugs which might help us once they're done (namely, 1196266, 1344910 and 1344917 - I'll go into more detail on these once they're ready); if that's the case then maybe this can be put on hold?

I don't actually know how this ends up, though, so I'm just curious.

**Comment by wolfbeast** [comment]
It seems to be that making any part of the caption bar "cut out", whether it's for buttons or just a 1 pixel top rim messes with the windows events in a way that prevents our overlays from receiving mouse hover events. I'm not sure why this happens.

**Comment by wolfbeast** [comment]
Putting this on hold for now because I really don't have a working solution for this. ill require research into why Windows 10 suddenly ignores the hover events when this is done.

**Comment by Lootyhoof** [comment]
Does this also occur if we draw the entire window (i.e.: have some sort of `background-color` on `#main-window`) and also draw the caption buttons completely? To test, you could install [this](https://userstyles.org/styles/120013/firefox-pale-moon-for-windows-10) userstyle and select the Pale Moon 26+ styling.

**Comment by wolfbeast** [comment]
No idea. Seems the user style is empty but maybe I'm missing something -- I never played with that.
Here's the x86 binary with the border patch applied:
https://www.dropbox.com/s/i4hztnnx93ehtsy/palemoon-27.4.0a1.win32.zip?dl=0

**Comment by Lootyhoof** [comment]
I can confirm this works as expected in Australium (in which the window behavior is as implemented in the linked bug and in our original Windows 10 implementation). 

![Caption button hover](http://i.imgur.com/a9om1Mi.png)

In an unrelated note it looks as though there's some odd tab behavior here (tabs that are closed act like the below, and new tabs don't open properly)?

![Oddity](http://i.imgur.com/9uaKv8O.png)

If the tab issue is related then it might be a bit more serious, though if not then this can certainly be put on hold for when the Mozilla bugs I mentioned earlier are done and ready for use.

**Comment by wolfbeast** [comment]
It certainly does something weird with the tabs with this change in as well... maybe the issue is that all UI CSS animations get screwed up (which would explain the hover problem), or rather, Windows 10 might not handle "glass" properly this way and refuse to tick the refresh driver. Either way, it's a no-no using clearRegion on Windows10 window frames by the looks of it.

**Comment by wolfbeast** [comment]
Windows 10's window manager is half-broken from our perspective. They've removed a few key functions that make glass surfaces work the way they do -- most likely on purpose. On Windows 10, it's simply not possible to have the combination of transparent+cutout or it will immediately stop refreshing. In fact, just marking a surface transparent+cutout stops all refreshes+events. As such, we can't cut out *anything* from the window, including the top pixel border. it works on your theme + Firefox because both paint the background, so it's not a transparent color.

**Comment by Lootyhoof** [comment]
For the issue regarding the transparent background I'm hoping those Mozilla bugs will help, as they paint the entire background but use the system accent colour instead of a solid grey (something I've been looking for for a long while, to be honest). This will also fix the issue with our caption buttons looking wrong on anything other than the default theme.

**Comment by wolfbeast** [comment]
Indeed. What we do now is relying on apparently unspecified behavior of the Windows 10 WM to get the accent color through glass-tagged surfaces. That only works if the surface is fully transparent (I tested with a low-alpha color, and that immediately kills the accent color completely). A funny observation is that that does allow us to "tint" the glass on Windows 7 with a custom color. ;)

**Comment by Lootyhoof** [comment]
That said though...this does still leave us with the tab issue (and maybe others?). I experienced it in Australium, too, so I don't think just painting the background helps there.

I'll certainly get a new issue up once those bugs are done, as I think those are definitely desirable while this seems glitchy at best. Maybe we can review this at a later date?

**Comment by wolfbeast** [comment]
... the tab issue doesn't occur if we don't cut out from the window. 
Also, if we can paint our window completely with the correct colors, then we no longer need glass, so Windows 10 can be happy with a standard custom-painted window.

**Comment by Lootyhoof** [comment]
Right, good to know. Once those bugs are ready for consumption I'll let you know, as this can probably be done at the same time.

**Comment by wolfbeast** [comment]
Let me verify what I said though. if the tab issue is present even without these patches, then there's soemthing else interfering (and I have an idea what it might be)

**Comment by wolfbeast** [comment]
Right, the tab issue is linked to gfx.vsync.hw-vsync.enabled -- I guess that doesn't work well on Windows 10.

**Comment by wolfbeast** [comment]
I can patch the widget code after all. Clearly, hw vsync doesn't tick the refresh driver properly in our combination of cutout+glass transparency, but if we just use the normal software vsync ticks, we're good.
