### ISSUE TITLE
Sourcebuffer/Trackbuffer re-entrant crash OOM 

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1109]
Blocks #1033 

Current trunk build of 21 may 2017 (post-merge of #1108) crashed on YouTube after having an ad interjected into a live stream (ISS feed). https://www.youtube.com/watch?v=RtU_mdL2vBM

````
-		msg	0x18a4f4f4 "[6244] ###!!! ABORT: Can't allocate mozilla::ReentrantMonitor: file e:\\mozdev\\palemoon\\build-x86-unstable\\dist\\include\\mozilla/ReentrantMonitor.h, line 53"	const char * const
````

Stack:
````
>	mozalloc.dll!mozalloc_abort(const char * const msg) Line 37	C++
 	xul.dll!NS_DebugBreak(unsigned int aSeverity, const char * aStr, const char * aExpr, const char * aFile, int aLine) Line 396	C++
 	xul.dll!mozilla::SourceBufferResource::SourceBufferResource(const nsACString_internal & aType) Line 250	C++
 	xul.dll!mozilla::TrackBuffersManager::InitializationSegmentReceived() Line 795	C++
 	xul.dll!mozilla::TrackBuffersManager::SegmentParserLoop() Line 690	C++
 	xul.dll!nsRunnableMethodImpl<void (__thiscall mozilla::MediaDecodeTask::*)(void),1>::Run() Line 710	C++
 	xul.dll!mozilla::AutoTaskDispatcher::TaskGroupRunnable::Run() Line 177	C++
 	xul.dll!mozilla::MediaTaskQueue::Runner::Run() Line 257	C++
 	xul.dll!nsThreadPool::Run() Line 227	C++
 	xul.dll!nsThread::ProcessNextEvent(bool aMayWait, bool * aResult) Line 807	C++
 	xul.dll!NS_ProcessNextEvent(nsIThread * aThread, bool aMayWait) Line 265	C++
 	xul.dll!mozilla::ipc::MessagePumpForNonMainThreads::Run(base::MessagePump::Delegate * aDelegate) Line 374	C++
 	xul.dll!MessageLoop::RunHandler() Line 227	C++
````

Potentially OOM because of recursive calls/allocation?
Memory use inflated to 2.8 GB (crashing the x86 process with OOM)

**Comment by trav90** [comment]
Our new MSE code is not as optimized as our previous code (yet), so higher memory usage is expected and very likely is the issue here. I'm looking into it.

**Comment by wolfbeast** [comment]
FYI: I didn't enable the new format reader for this. This is using our existing reader.

**Comment by trav90** [comment]
My bad; I seen the TrackBuffersManager in the stack and assumed that this was with the new format reader.

**Comment by trav90** [comment]
I've been watching this live stream at 1080p for the past three hours now (including several ads) with a current trunk build and clean profile on my x86 CentOS 6 box and never saw memory usage exceed 1GB?

That said, I do have patches that fix several memory leaks in our MSE code (including one in SourceBufferResource) that I will be testing tomorrow and submitting a PR for if it checks out.

**Comment by wolfbeast** [comment]
I'm not really sure. It's possible that the ad injection screwed up on YT's side as well (yay for JS taking on the task of stream handling instead of media). Feel free to close as WFM if it looks like a one-off.

**Comment by trav90** [comment]
OK sounds good. Considering I saw multiple ads over the 3 hours testing period and never reproduced the issue, and combined with the fact that I do have patches incoming that should improve our memory usage when playing MSE video I'm closing this issue. If it happens again please reopen and I'll look into it.
