### ISSUE TITLE
Error Console doesn't display CSS-Warnings until the "sub-CSS-filter" is changed

### ISSUE THREAD

**Issue by LL25255252** [MoonchildProductions/Pale-Moon#1110]
STR 
Create a new/fresh Pale Moon profile.
Open the Error Console (ctrl-shift-j)
Open a tab. e.g.  https://palemoon.start.me/start
After the page loads there are no CSS errors in the Error Console.

Now in the error Console toggle the light-blue css icon from On to Off and then from Off to On.
Suddenly all the CSS errors of the page are displayed.

This behavior happens only once. After that the Error Console correctly shows the CSS errors (without the need to toggle the light-blue button).

Was this bug introduced by mistake here https://github.com/MoonchildProductions/Pale-Moon/issues/631#issuecomment-265120352 ?

Tested on Pale Moon 27.3.0
Win 7 x64

**Comment by janekptacijarabaci** [comment]
Not confirmed. There is the difference between the error and the warning. If `CSS - Warnings` is not on by default, warnings not displayed.

**Comment by LL25255252** [comment]
1. @janekptacijarabaci can you please explain "If CSS - Warnings is not on by default" ? As I reported I opened a new/fresh profile without changing anything.
2. You are correct. I only managed to reproduce the issue with CSS warnings and not with CSS errors. Should I then correct the title of this issue ? 
3. I  consider it as a bug ? Do you ?

**Comment by janekptacijarabaci** [comment]
The default setting (for warnings) is here:
https://github.com/MoonchildProductions/Pale-Moon/blob/master/modules/libpref/init/all.js#L1072

and I just tested this in a new profile:
![1](https://cloud.githubusercontent.com/assets/2373486/26301305/19b68efc-3ee1-11e7-889f-40f8ab126962.png)

> I consider it as a bug.

I'm sorry, but I do not see a problem. But maybe I don't understand it.

**Comment by LL25255252** [comment]
Thank you @janekptacijarabaci .This is indeed related to the default "sub-filtering" of the Browser Console. I just noticed that Firefox Browser Console uses the same behavior.
The default display of CSS Warning was changed changed in Firefox 28 (2013).
https://bugzilla.mozilla.org/show_bug.cgi?id=909756
But IMHO, the default shouldn't have been changed. (in order to avoid confusion and to keep consistency with the other parts of the Browser Console like JS, Security, Logging and more)).

**Comment by wolfbeast** [comment]
CSS warnings are often spurious on websites and would flood the browser console.
I'm not inclined to change it, as a result. If you want this enabled by default, then just flip the pref.

**Comment by LL25255252** [comment]
I still think the default should be ON. 
> CSS warnings are often spurious on websites and would flood the browser console.
>
A solution to that can be (a one time ?) displaying a recommendation message (with an option to close it) at the top of the Browser Console (something like : "Tip - Usually you can easily reduce the size of the the Browser Console by filtering out the CSS - warnings).

Anyway, feel free to close this issue whenever you want.

**Comment by wolfbeast** [comment]
I'm pretty sure the vast majority of people looking at the browser console don't care about Pale Moon not understanding vendor-prefixed CSS in websites that target other browsers (which is usually what CSS warnings are).
