### ISSUE TITLE
Remove b2g

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1111]
`/b2g` (Firefox OS) is completely dead code for us. We shouldn't have it in our tree or weaved into our build system.

This needs to go.

**Comment by Feodor2** [comment]
Hey i would like to help, think i can handle this.
B2g easy to remove because it already distinguished in the code.

**Comment by wolfbeast** [comment]
I can assign you, but if you want to do this properly you'll have to do some research -- there are a few small direct dependencies, and it looks like Gonk widget/rendering code is b2g specific as well and not used for other operating systems (but you'd have to check in the Android part, too)

**Comment by wolfbeast** [comment]
You may also want to look at the UXP version of the same task and see what all Tobin's been doing there.
https://github.com/MoonchildProductions/moebius/issues/8

**Comment by Feodor2** [comment]
Have deleted bg2 folder and MOZ_MULED entries.
Also entries from xpcom and dom folders.
What about camera and bluetooth? I left them, but I think browser is not to mess with them even in android, going delete too.

Now only tests are remain for cleaning

Also i don't know at all how to build palemoon for android, so i can't check for it. On windows its fine.

**Comment by wolfbeast** [comment]
Camera should not be needed, but bluetooth is probably needed for e.g. bluetooth audio. You should separate those in their own commits/pull requests though since it may cause problems and that will make it easier to back out if we need support for either.

**Comment by Feodor2** [comment]
I keep bluetooth and rename its entries as MOZ_BT...
What about GONK? seems it is not needed anywhere beside b2g, and to be removed as well

**Comment by wolfbeast** [comment]
Gonk should probably be a separate issue since it's all over the place and may be a lot trickier to properly take care of.

**Comment by Feodor2** [comment]
New thing uncertain what to do
MOZ_B2G_RIL so called **radio interface layer**

**Comment by Feodor2** [comment]
I decide to divide the whole into 3 patches
RemoveB2g
RemoveGonk
RemoveOther  where other are telephony, *mobile*, wifi, voicemail and more.... i not found where it can be used beside firefoxOS.

**Comment by wolfbeast** [comment]
Please limit yourself to removing b2g and things directly related to it/solely required by it for this issue. Although we currently don't have a Fennec build we support (mostly because I didn't get around to figuring out building it on Goanna yet) it should not become collateral of removing something that is truly dead and abandoned.

**Comment by Feodor2** [comment]
Understood, i shall do according the UXP version.
But what about tests, i see that here is another issue to remove them, shall i care to remove b2g out of tests?

**Comment by wolfbeast** [comment]
Assuming B2G is specifically listed in tests outside of /b2g, they should be removed from there as well, or tests adjusted to remove b2g conditionals.

**Comment by wolfbeast** [comment]
Since it's been another month, I'm assuming this won't be ready anytime soon. Do you still want to remain assigned or should I open it up for others?

**Comment by mattatobin** [comment]
It is my opinion, for `Tycho` I would just leave it not worth the duplicated effort at this point.. I already have started work on this in `UXP` but I got distracted.. Will likely have to rebase and do what I have done again over there..

**Comment by wolfbeast** [comment]
Fair point. closing this as wontfix.

**Comment by Feodor2** [comment]
I did it but no tests, however i do not know how to add patch here and done another copy of palemoon
And test it for windows, now way to test for android though
you can it see there https://github.com/Feodor2/Pale-Moon/commits/master

Also i have a question about thing named webapps. is it used beside b2g?
