### ISSUE TITLE
IndexedDB "Always Ask" option sometimes allows without asking.

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1112]
Ad https://forum.palemoon.org/viewtopic.php?f=3&p=114654#p114654

In my opinion it is a problem.
Even:
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria

__Steps to reproduce__
Go to https://demo.agektmr.com/storage/
(but e.g.: http://clb.demon.fi/dump/html5_popups/?persistent - OK)
Page Info - Permissions - Maintain Offline Storage -> `Always Ask` (or `Block`)

## `Always Ask`

Pale Moon 26:
![1](https://cloud.githubusercontent.com/assets/2373486/26440308/fdb0a57e-412b-11e7-98a3-9ebdc318a5d2.png)

Pale Moon 27 (and Firefox - a last version):
`[No prompt will appear]`

## `Block`

Pale Moon 26:
![2](https://cloud.githubusercontent.com/assets/2373486/26440778/24a8347e-412e-11e7-97c7-bcd5a197818e.png)

Pale Moon 27 (and Firefox - a last version):
![3](https://cloud.githubusercontent.com/assets/2373486/26440872/84ef6fdc-412e-11e7-85e0-72bfd106fe7d.png)

__AFAIK:__

After this change...:
https://bugzilla.mozilla.org/show_bug.cgi?id=994190

...this observer:
https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/browser/base/content/browser.js#L5651
should be called for `indexedDB-permissions-prompt`

See also:
http://xref.palemoon.org/palemoon-trunk/search?string=kPermissionPromptTopic
http://xref.palemoon.org/palemoon-trunk/search?string=PromptIfNeeded

But that will not happen (if it's not `persistent`).

IMHO: The user should always decide (for `Always Ask`), no matter what type it is.

**Comment by wolfbeast** [comment]
no, no, no, no.

I'm not going to break web compatibility when it was just fixed. If you want prompts, you have to use the master switch, as I explained already, in options.
![image1](https://cloud.githubusercontent.com/assets/3359132/26445977/7b052778-4142-11e7-943f-e3032b7be9c4.png)

**Comment by janekptacijarabaci** [comment]
Here I am confused.

Files (e.g. in `storage\default`) are still being created (without any prompts).
And it seems that the limit is 2 GB
(AFAIK - I don't see other settings: https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/dom/quota/QuotaManager.cpp#L72)

See also:
https://forum.palemoon.org/viewtopic.php?f=3&t=14023#p99724

**Comment by wolfbeast** [comment]
Now, for once can you please make a full explanation instead of "see here [link] because [link] so [link] and then [link]"? Because it makes it very hard to even understand a single sentence. Thanks.

**Comment by wolfbeast** [comment]
FTR: Application storage != DOM storage != offline app cache != IndexedDB

**Comment by wolfbeast** [comment]
OK I'm not sure what is going on here. is that demo page using workers or something? is that broken? because base functionality seems to work exactly as it is supposed to.

**Comment by wolfbeast** [comment]
So, we're talking purely about IndexedDB here.
If the main switch in options is set to deny, then indexeddb calls fail. That's correct.
If it's set to "always ask" then it sometimes asks, and sometimes doesn't?
Default behavior will allow storage.

**Comment by wolfbeast** [comment]
Note: if data is not "persistent" then it will not be stored offline. So the option chosen only applies to persistent data. That is 100% correct and it will not ask for transient data. Is that the issue you're having here, that transient data does not prompt the user?
Wanting to block transient data is not something that should be done here, because all that will do is break web applications with no gain. why would you want to block it? Tracking? That won't matter since the data will be discarded offline.

**Comment by janekptacijarabaci** [comment]
Using read-only flag is functional in this case. This solution has already been suggested many times on forum.palemoon.org.
And if you think it's OK, please leave it as it is.

IMHO:
But "Delete All" ("Clear Recent History" / "Clear All History") should work better. Manually deleting the contents of the folders... This is not a user friendly solution.
This information should be written at least in the prompt window. Or somewhere visible. When "all" isn't all.

**Comment by wolfbeast** [comment]
This isn't history...

**Comment by janekptacijarabaci** [comment]
But it's on the disk. And the user should know about it.

**Comment by wolfbeast** [comment]
I doubt you are aware of everything that is saved on disk temporarily.
So, what do you suggest is done about it then that will not break websites?

**Comment by janekptacijarabaci** [comment]
I have no suggestion (in addition to delete files - or informing the user). Everything else has already been said in the previous comments (bugs [527667](https://bugzilla.mozilla.org/show_bug.cgi?id=527667) and [1047098](https://bugzilla.mozilla.org/show_bug.cgi?id=1047098)).

**Comment by wolfbeast** [comment]
Considering this will only disturb certain levels of paranoia or above, I'll be closing this as-is.
