### ISSUE TITLE
CSS - Add support for "q" (quarter mm) absolute length units

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1126]
Standard: https://www.w3.org/TR/css-values/#absolute-lengths

> Q’ 	quarter-millimeters 	1q = 1/40th of 1cm

**Comment by wolfbeast** [comment]
Of note, anyone using this unit can expect it to not work in any browser except Firefox 49+ and Pale Moon. Consider this change one for completeness that will likely not see any practical use in the wild.

**Comment by wolfbeast** [comment]
Verified on latest unstable.
