### ISSUE TITLE
nsIWebContentHandlerRegistrar is overly restrictive

### ISSUE THREAD

**Issue by ThosRTanner** [MoonchildProductions/Pale-Moon#1136]
Given this:

     const WebContentHandlerRegistrar = Components.classes[
        "@mozilla.org/embeddor.implemented/web-content-handler-registrar;1"
        ].getService(Components.interfaces.nsIWebContentHandlerRegistrar);

I'd expect to be able to register content handlers with this:

      WebContentHandlerRegistrar.registerContentHandler(
        content_type
        url,
        handler_name,
        null);

However, this only works if content_type is "application/vnd.mozilla.maybe.feed". I can't register handlers for maybe.video.feed or maybe.audio.feed.

Moreover this doesn't make any checks to see if the content handler is already registered - if I register the same content handler twice, I get two instances of it (you can see this in about:config). That might be working as designed, but there isn't any method to deregister a handler.

All this means the only way I can reliably control my content handlers is to faff around in the preference tree. And that brings up the 3rd problem:

Once I've finished fiddling, the browser doesn't realise I've added/removed content handlers until I restart it.

This issue exists in firefox too: See https://bugzilla.mozilla.org/show_bug.cgi?id=391286 

See also https://html.spec.whatwg.org/multipage/webappapis.html#dom-navigator-registercontenthandler

**Comment by wolfbeast** [comment]
Right, the restriction in the Mozilla platform is the following:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerContentHandler#Notes

It uses a whitelist for a few feed protocols only, instead of a blacklist as specced in http://www.w3.org/TR/html5/webappapis.html#type-blacklist

That should be easy enough to flip around, and go with a blacklist as per the spec, at least for mime types. Care must be taken to prevent hijacking possibilities there.

**Comment by JustOff** [comment]
According to http://www.w3.org/TR/html5/webappapis.html#type-blacklist difines `All types that the user agent supports displaying natively in a browsing context during navigation, except for application/rss+xml and application/atom+xml` should be also blacklisted. How does https://github.com/MoonchildProductions/Pale-Moon/commit/217cfbbb233f1a451182841b0b4911d771e55549 conform to this requirement?

**Comment by JustOff** [comment]
@wolfbeast, could you please dispel my doubts outlined above?

**Comment by wolfbeast** [comment]
The blacklist should be complete as far as types that the user supports displaying natively in a browsing context during navigation.

**Comment by JustOff** [comment]
It seems to me that at least all [image](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3_RelBranch/netwerk/mime/nsMimeTypes.h#L88) and [text](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3_RelBranch/netwerk/mime/nsMimeTypes.h#L132) mime types that Pale Moon supports natively should be blacklisted too. I suspect that the list is not exhaustive and I don't know how to handle this check correctly without whitelist, even if it's against the W3C recommendations.

**Comment by wolfbeast** [comment]
Check the list... it contains all common, natively-supported image and text formats that can be expected **in a navigation context**. e.g. we would not want to block text/vcard or text/calendar or text/javascript since those have very little meaning in a navigation context.
