### ISSUE TITLE
Strange error when deleting folder of livemarks

### ISSUE THREAD

**Issue by ThosRTanner** [MoonchildProductions/Pale-Moon#1137]
I have an extension which can create a folder of livemarks of rss/atom feeds from its configuration. This works fine, but should I attempt to delete this folder, I get this in the console log:

    [Exception... "Illegal value"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/components/nsLivemarkService.js :: LS_getLivemark/< :: line 397"  data: no]

I think that this is likely to be due to a livemark where the feed or the website no longer exists (or is returning some other sort of error). The folder appears to get deleted OK but it's a little disconcerting.

**Comment by wolfbeast** [comment]
Can you please check if this is fixed in the current unstable builds?

**Comment by janekptacijarabaci** [comment]
May I  suggest a better solution that:
https://bugzilla.mozilla.org/show_bug.cgi?id=1370051#c3

But...
https://bugzilla.mozilla.org/show_bug.cgi?id=1370051#c4:
> The view should already know if it's a livemark or not, IIRC we keep some sort of local property to track those.

AFAIK: I don't know about it.

**Comment by wolfbeast** [comment]
so.. if you had a better solution... why did you make a pull request?

**Comment by janekptacijarabaci** [comment]
Because I had it later... And I don't know if it's the better solution:
https://github.com/janekptacijarabaci/Pale-Moon/compare/master...janekptacijarabaci:places_bookmarks_feeds_delete_1
(IMHO yes)

**Comment by wolfbeast** [comment]
OK, I'm backing out your previous change. Looks like more info is needed from the Mozilla side. Once that BZ bug has an acceptable solution, ping me again and I'll have another look to see what we should do.

**Comment by Lorienna** [comment]
## The flavor of error currently thrown on Pale Moon:

```javascript

[Exception... "Illegal value"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/components/nsLivemarkService.js :: LS_getLivemark/< :: line 397"  data: no]
Source File: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js
Line: 870
```

Line:

```javascript
        nextValue = this.onReject.call(undefined, nextValue);
```

Piece of code:

```javascript
      // If a handler is defined for either resolution or rejection, invoke it
      // to determine the state of the next promise, that will be resolved with
      // the returned value, that can also be another promise.
      if (nextStatus == STATUS_RESOLVED) {
        if (typeof(this.onResolve) == "function") {
          nextValue = this.onResolve.call(undefined, nextValue);
        }
      } else if (typeof(this.onReject) == "function") {
        nextValue = this.onReject.call(undefined, nextValue);
        nextStatus = STATUS_RESOLVED;
      }
```

## The earliest error flavor thrown on a Nightly FF build:

```javascript
[Exception... "Illegal value"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/components/nsLivemarkService.js :: LS_getLivemark/< :: line 428"  data: no]
Source File: resource://gre/modules/Promise.jsm
Line: 785
```

Line:

```javascript
        nextValue = this.onReject(nextValue);
```

Piece of code:

```javascript
      // If a handler is defined for either resolution or rejection, invoke it
      // to determine the state of the next promise, that will be resolved with
      // the returned value, that can also be another promise.
      if (nextStatus == STATUS_RESOLVED) {
        if (typeof(this.onResolve) == "function") {
          nextValue = this.onResolve(nextValue);
        }
      } else if (typeof(this.onReject) == "function") {
        nextValue = this.onReject(nextValue);
        nextStatus = STATUS_RESOLVED;
      }
```

## The Nightly changeset originally introduced the error:

__Last Good: `30.0a1 (2014-03-12)`__
https://archive.mozilla.org/pub/firefox/nightly/2014/03/2014-03-12-03-02-01-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/44ae8462d6ab

__First Bad: `30.0a1 (2014-03-13)`__
https://archive.mozilla.org/pub/firefox/nightly/2014/03/2014-03-13-03-02-02-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/46041cc216fd

__Pushlog:__ https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=44ae8462d6ab&tochange=46041cc216fd

__Changeset `173276`__ - _Mute "A promise chain failed to handle a rejection" error from the livemarks service. r=mano:_ 
https://hg.mozilla.org/mozilla-central/rev/60c1af78091a

__Bug `969318`__ - _"A promise chain failed to handle a rejection" from the livemarks service (deprecate passing a callback):_
https://bugzilla.mozilla.org/show_bug.cgi?id=969318

**Comment by wolfbeast** [comment]
You may want to pass that info to the BZ bug. There's nothing actionable for us here.

**Comment by Lorienna** [comment]
@wolfbeast, there's a ___child changeset 173277___ which was implemented after the one above, IIUC:
https://hg.mozilla.org/mozilla-central/rev/56ac183ad1e2

...and it fixes `Bug 981592` - _Double click folder in right side pane does not work_:
https://bugzilla.mozilla.org/show_bug.cgi?id=981592

Might this have affected the folder deletion as well?

**Comment by janekptacijarabaci** [comment]
@Lorienna
The fix already exists. Though not the fastest method (the query asks the database).

**Comment by wolfbeast** [comment]
Fixes have been merged -- closing.
