### ISSUE TITLE
Menu and tooltip fade effect

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1142]
Firefox isomorphic: https://bugzilla.mozilla.org/show_bug.cgi?id=333564

## Step
1. turn "Use the following transition effect for menus and tooltips"
2. Open a menu or hover to show a tooltip

## Now
No fade effect.

## Expect
demo by Windows Explorer

https://cloud.githubusercontent.com/assets/15178410/23990947/93c47fe0-0a72-11e7-8758-6201ba289b4d.gif
https://cloud.githubusercontent.com/assets/15178410/26762846/7c707fae-497b-11e7-919b-ffcf79e98c16.gif

**Comment by wolfbeast** [comment]
These menus are not native application menus. At most it can be emulated, but likely it'll just be a perf drain if we do.

**Comment by wolfbeast** [comment]
Considering our way of handling these menus (pop-up layers), this can't even be easily emulated. I'm wontfix-ing this because it need a lot of added complexity and performance trade-off, not to mention all sorts of ways that this can introduce bugs, for a minimal visual effect.
