### ISSUE TITLE
TelemetryStopwatch.jsm - key "PLACES_AUTOCOMPLETE_URLINLINE_DOMAIN_QUERY_TIME_MS" was already initialized

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1145]
On Win7x64 (didn't test elsewhere), the error below appears in the Pale Moon consoles:

```javascript
Error: TelemetryStopwatch:
key "PLACES_AUTOCOMPLETE_URLINLINE_DOMAIN_QUERY_TIME_MS" was already initialized
Source File: resource://gre/modules/TelemetryStopwatch.jsm
Line: 52
```

...with the referred <tt>Line: 52</tt> being:

```javascript
      Cu.reportError("TelemetryStopwatch: key \"" +
```

...and a piece of code where it rests:

```javascript
    if (timers.hasOwnProperty(aHistogram)) {
      delete timers[aHistogram];
      Cu.reportError("TelemetryStopwatch: key \"" +
                     aHistogram + "\" was already initialized");
      return false;
    }
```

...whenever the following data is entered via `Paste & Go`:

1. `about:`... addresses:
   * _the error is thrown every 2nd tab/window where these addresses haven't been `Pasted & Gone` yet_.
2. Top-level IP addresses and domain names without a <b>final forward</b> slash`/` attached, e.g. `192.168.0.1` or `example.com`, but <b>not</b>`192.168.0.1/` or `example.com/` :
   * _the error appears after every 2nd `Pasting & Going` in any tab/window_.
3. Random symbol combinations lacking <b>forward</b> slash`/` among them:
   * _the error here can also be observed after every 2nd `Pasting & Going` in any tab or window_.

---

### What Happens on FF Builds:

1. Please have a look at the point 1 for PM.
2. The same as the point 2 for PM, albeit occurs every 2nd tab/window like in point 1.
3. Please see point 3 for PM listed above.
4. Additionally, the error won't emerge if <b>an already opened</b> top-level IP or domain are copied slashless <b>in URL bar</b>, and then `Pasted & Gone` 2 times in any tab or window; however, it'll show up if the said addresses auto-redirect elsewhere (e.g. `https://en.wikipedia.org` auto-redirects to `https://en.wikipedia.org/wiki/Main_Page`).

 
The piece of code is identical to that of PM:

```javascript
    if (timers.hasOwnProperty(aHistogram)) {
      delete timers[aHistogram];
      Cu.reportError("TelemetryStopwatch: key \"" +
                     aHistogram + "\" was already initialized");
      return false;
    }
```

...likewise is the `Line: 53` referenced on the first series of FF builds:

```javascript
                     aHistogram + "\" was already initialized");
```

...superseded by the `Line: 52` since <b>33.0a1 (2014-06-24)</b> nightly build: 

```javascript
      Cu.reportError("TelemetryStopwatch: key \"" +
```

#

Last non-affected: <b>25.0a1 (2013-06-27)</b>
https://archive.mozilla.org/pub/firefox/nightly/2013/06/2013-06-27-03-10-27-mozilla-central/
Built from: http://hg.mozilla.org/mozilla-central/rev/3b955f306226

First <tt>TelemetryStopwatch.jsm:<b>53</b></tt>: <b>25.0a1 (2013-06-28)</b>
https://archive.mozilla.org/pub/firefox/nightly/2013/06/2013-06-28-03-11-49-mozilla-central/
Built from: http://hg.mozilla.org/mozilla-central/rev/8e3a124c9c1a

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=3b955f306226&tochange=8e3a124c9c1a

#

Last <tt>TelemetryStopwatch.jsm:<b>53</b></tt>: <b>33.0a1 (2014-06-23)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/06/2014-06-23-03-02-01-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/366b5c0c02d3

First <tt>TelemetryStopwatch.jsm:<b>52</b></tt>: <b>33.0a1 (2014-06-24)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/06/2014-06-24-03-02-00-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/e86b84998b18

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=366b5c0c02d3&tochange=e86b84998b18

#

Last <tt>TelemetryStopwatch.jsm:<b>52</b></tt>: <b>34.0a1 (2014-07-24)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/07/2014-07-24-03-02-01-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/a91ec42d6a9c

First errorless: <b>34.0a1 (2014-07-25)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/07/2014-07-25-03-02-02-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/613e79262240

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=a91ec42d6a9c&tochange=613e79262240

#

Last errorless: <b>34.0a2 (2014-09-12)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/10/2014-09-12-00-40-04-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/1d4b0fc511dc

First <tt>TelemetryStopwatch.jsm:<b>52</b></tt>: <b>34.0a2 (2014-09-13)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/10/2014-09-13-00-40-04-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/0807d8ab3e5a

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1d4b0fc511dc&tochange=0807d8ab3e5a

And this seemingly lasts up until <b>FF 34.0 (2014-11-26)</b> full release:
https://archive.mozilla.org/pub/firefox/releases/34.0/
https://hg.mozilla.org/releases/mozilla-release/rev/456394191c90

#

Last errorless: <b>35.0a2 (2014-10-21)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/10/2014-10-21-00-40-01-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/a5e4cb815494

First <tt>TelemetryStopwatch.jsm:<b>52</b></tt>: <b>35.0a2 (2014-10-22)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/10/2014-10-22-00-40-03-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/e49b50024257

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=a5e4cb815494&tochange=e49b50024257

Once again, by the look of it, full <b>FF 35.0 (2015-01-09)</b> release is the final 'point of affection' here:
https://archive.mozilla.org/pub/firefox/releases/35.0/
Built from: https://hg.mozilla.org/releases/mozilla-release/rev/32e36869f84a

#

Last errorless: <b>36.0a1 (2014-11-26)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/11/2014-11-26-03-02-07-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/ced1402861b8

First <tt>TelemetryStopwatch.jsm:<b>52</b></tt>: <b>36.0a1 (2014-11-27)</b>
https://archive.mozilla.org/pub/firefox/nightly/2014/11/2014-11-27-03-02-08-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/cef590a6f946

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=ced1402861b8&tochange=cef590a6f946

#

Last <tt>TelemetryStopwatch.jsm:<b>52</b></tt>: <b>41.0a1 (2015-05-29)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/05/2015-05-29-03-02-05-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/f986e55c4e0b

First errorless: <b>41.0a1 (2015-05-30)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/05/2015-05-30-03-02-05-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/45a4d6336c73

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=f986e55c4e0b&tochange=45a4d6336c73

#

Last errorless: <b>41.0a2 (2015-07-13)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/07/2015-07-13-00-40-06-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/95ff4ba30e93

First <tt>TelemetryStopwatch.jsm:<b>52</b></tt>: <b>41.0a2 (2015-07-14)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/07/2015-07-14-00-40-06-mozilla-aurora/
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/1f4185f18537

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=95ff4ba30e93&tochange=1f4185f18537

This one also apparently persists until the release of <b>FF 41.0 (2015-09-18)</b> inclusively:
https://archive.mozilla.org/pub/firefox/releases/41.0/
https://hg.mozilla.org/releases/mozilla-release/rev/78c82e5cd777

#

Last errorless: <b>42.0a1 (2015-08-10)</b>
https://archive.mozilla.org/pub/firefox/nightly/2015/08/2015-08-10-03-02-05-mozilla-central/
Built from: https://hg.mozilla.org/mozilla-central/rev/0e269a1f1beb

First <tt>TelemetryStopwatch.jsm:<b>52</b></tt>: <b>42.0a2 (2015-08-10)</b>
Built from: https://hg.mozilla.org/releases/mozilla-aurora/rev/7308dd0a6c3b
https://archive.mozilla.org/pub/firefox/nightly/2015/08/2015-08-10-12-29-08-mozilla-aurora/

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=0e269a1f1beb&tochange=7308dd0a6c3b

And finally, this error seemingly goes away after <b>FF 42.0 (2015-10-30)</b> release:
https://archive.mozilla.org/pub/firefox/releases/42.0/
Built from: https://hg.mozilla.org/releases/mozilla-release/rev/e2f9a0ed50bc

---

All in all, the telemetry error on FF is rather inconstant; sometimes it disappears only to reappear later on another builds, so it's fairly possible that the list of its 're-incarnations' above isn't complete.

Hopefully, this overview would be helpful in fixing it on PM.

**Comment by janekptacijarabaci** [comment]
See:
https://forum.palemoon.org/viewtopic.php?f=3&t=15795&p=114775

See also:
https://github.com/MoonchildProductions/Pale-Moon/pull/754

**Comment by wolfbeast** [comment]
Telemetry is of no consequence. No need to open issues for console warnings/errors about telemetry since it's not used for anything.

**Comment by Lorienna** [comment]
@wolfbeast 
There's also `NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a` error when I `Paste & Go` an incorrect `about:`... address. Should this be considered an issue?

**Comment by wolfbeast** [comment]
No, if it's an incorrect about: address then that is expected.
