### ISSUE TITLE
feature request - filterable network monitor output

### ISSUE THREAD

**Issue by leedoyle** [MoonchildProductions/Pale-Moon#1147]
I think many web developers and power users would enjoy being able to filter the output of the network monitor in a more convenient way. Afaik, to implement this feature one would only have to port the code from Mozilla FF.

Attached is my suggestion (arrow **2**)
![devtoolsdream](https://cloud.githubusercontent.com/assets/25978190/26825429/09a89ec4-4ac6-11e7-9e53-9a309bd54365.png)

**Comment by janekptacijarabaci** [comment]
The `Clear` button is at the bottom right.

**Comment by leedoyle** [comment]
Thank you, I've amended the issue.
