### ISSUE TITLE
Investigate switching to VS2015 CE

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#115]
We should investigate what is needed to switch our code base over to VS2013.
VS2012 is exceedingly good at what it does, but has a few shortcomings that are likely not going to be addressed by Microsoft at this point anymore (e.g. some CRT functions that are glaringly absent), as well as being less C++ 11 compliant than other current compilers. Probably we'll also have some added advantages from compiler improvements as a bonus.

The easy parts will be adding VC12 support to our build system and packaging manifests. The more difficult area will be finding and solving the code-breaking changes between VC11 and VC12, although I don't think these will be extensive in our code base (considering it does cater to multiple, cross-platform, compilers) but there may be a few snags.

**Comment by mattatobin** [comment]
BMO Meta-bug: Bug 914596 - (VC12) Support building with Visual C++ 2013
https://bugzilla.mozilla.org/show_bug.cgi?id=vc12

The dependent bugs that deal with foundational build system adjustments seem to be targeted fairly close to us (Gecko 25 and 26)

Some of the basic ones are::
Bug 888158 - Make configure to detect Visual Studio 2013 compiler
Bug 918164 - Add -FS option to NSS config when using VS2013
Bug 915973 - Need -FS option for parallel build on VS2013
Bug 915522 - VS2013 support for NSPR
Bug 889823 - ipc fail to compile using Visual Studio 2013
Bug 888159 - mfbt fail to compile using Visual Studio 2013

**Comment by Lootyhoof** [comment]
Be aware that work has begun at Mozilla to transition to VS2015, so just posting this one here in case it's ever decided to move to it:

[1119082] (https://bugzilla.mozilla.org/show_bug.cgi?id=1119082) - (VC14) Add Microsoft Visual Studio 2015 (VS2015) as a supported compiler

**Comment by wolfbeast** [comment]
Adding support for != transitioning to.

**Comment by wolfbeast** [comment]
If we'll switch, this will have to be to VS2015 -- VS2013 is too much a "work in progress" for VC++11 standards compliance. Preliminary investigation shows VS2015 CE still supports Windows XP as a target platform, so this works for our Atom/WinXP build.

**Comment by wolfbeast** [comment]
Marking this a wontfix. with the Tycho work we'll be on VS2013 and the language feature set offered by 2015 doesn't seem to be particularly useful, nor the probability of us porting VS2015-unique code across from Mozilla.
