### ISSUE TITLE
Vsync test fail 

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1151]
http://www.vsynctester.com/

I see the frame-losing.
It is not too important, would you like to fix it?

**Comment by mattatobin** [comment]
See the Pale Moon website about artificial benchmarks.

**Comment by zcyzcy88** [comment]
Not artificial benchmarks.
v-sync test fail == v-sync fail == is not proper v-sync == frame losing (jitter/stutter/jerkiness on a regular periodic basis) == not smooth animation

**Comment by wolfbeast** [comment]
This has already been addressed. Check unstable.
Also, if you want to have even more vsynciness, you can sync it to your HW clock (this is disabled by default for now because it doesn't work well on non-dedicated graphics)

**Comment by wolfbeast** [comment]
![vsync-ok](https://user-images.githubusercontent.com/3359132/26873903-c4caded2-4b7b-11e7-96e3-325b47877fd1.png)
