### ISSUE TITLE
Text spacing is worse when ClearType is off

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1155]
Firefox isomorphic: https://bugzilla.mozilla.org/show_bug.cgi?id=1341007

## Environment

As far as my test, the bug is always happen in Windows whatever environment, I write here for someone need it.

- 2560x1440 resolution
- Windows 10
- 150% DPI
- with MacType Patch 

### When off, the render mode seen in "snap to pixel"

<img width="1280" alt="2017-06-05 17_58_31-greenshot" src="https://user-images.githubusercontent.com/15178410/26973194-d04d3624-4d47-11e7-9ab2-d4b36b2e1a35.png">
<img width="390" alt="2017-06-09 19_24_24-millions - google search - pale moon" src="https://user-images.githubusercontent.com/15178410/26973581-c601a072-4d49-11e7-8af4-f5647e73387a.png">
<img width="290" alt="2017-06-09 19_24_33-millions - google search - pale moon" src="https://user-images.githubusercontent.com/15178410/26973586-ce44a568-4d49-11e7-89fa-d574d3e62c99.png">

### When on, the render mode seen in "natural"

<img width="1280" alt="2017-06-05 17_58_40-greenshot" src="https://user-images.githubusercontent.com/15178410/26973193-d0492016-4d47-11e7-8895-39d64d006aef.png">
<img width="380" alt="2017-06-09 19_24_44-millions - google search - pale moon" src="https://user-images.githubusercontent.com/15178410/26973594-d5118d3e-4d49-11e7-9c7a-51c4bd2d3871.png">
<img width="300" alt="2017-06-09 19_24_40-millions - google search - pale moon" src="https://user-images.githubusercontent.com/15178410/26973596-d723bd0e-4d49-11e7-851e-6498f02b412d.png">

This is unusual, because Edge (which use also use DirectWrite & D2D) always in "natural" mode whatever Cleartype on or off, and "even spacing" is more important than "sharp".
I think Pale Moon should always in "natural" mode if use DirectWrite backend.

Not about GDI, I ensured I turn it off.

**Comment by wolfbeast** [comment]
Wontfix.
Cleartype has to be assumed on on all supported Windows operating systems since that is the default.

If you switch it off, and you prefer (subjectively) the "natural" D2D font rendering method, you should adjust the appropriate pref `gfx.font_rendering.cleartype_params.rendering_mode`

> "even spacing" is more important than "sharp"

Your opinion, not mine.

**Comment by zcyzcy88** [comment]
I tried turning anti-aliasing setting but I find nothing.
This bug is unrelated to anti-aliasing setting:
Even force anti-aliasing setting to "natural", when ClearType (Windows setting) off, text spacing is still "snap to pixel".

And sometime the situation is reversal:
ClearType on: "snap to pixel"
ClearType off: "natural"

This bug is not important, feel free to wontfix.
(Maybe I don't find the answer until I read the source code)
