### ISSUE TITLE
Tooltip shadow

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1156]
Firefox isomorphic.

Menu have but Tooltip not.
I think it is easy to implement, use the same shadow as menu.

**Comment by wolfbeast** [comment]
Please provide more information. Which tooltip? Which OS? What exactly is the perceived issue?

**Comment by zcyzcy88** [comment]
- HTML `title` Attribute, XUL `tooltiptext` Attribute
- Windows (or more)

Now Menu:
<img width="229" alt="2017-06-09 22_37_24-tooltip shadow issue 1156 moonchildproductions_pale-moon" src="https://user-images.githubusercontent.com/15178410/26980303-5331bb0c-4d64-11e7-9265-f5b6562df16d.png">

Now Tooltip:
<img width="97" alt="2017-06-09 22_37_31-tooltip shadow issue 1156 moonchildproductions_pale-moon" src="https://user-images.githubusercontent.com/15178410/26980304-54247fb8-4d64-11e7-9349-18083414cb62.png">

Expect Tooltip:
<img width="158" alt="2017-06-09 22_38_40-downloads" src="https://user-images.githubusercontent.com/15178410/26980389-9fddf38a-4d64-11e7-8fbe-8f432386a9ae.png">

**Comment by wolfbeast** [comment]
Those tooltips are not native, so to implement this, it would need to be done specifically per OS and OS theme flavor.

**Comment by janekptacijarabaci** [comment]
> Windows (or more)

I see shadows everywhere. Which theme do you use?

**Comment by wolfbeast** [comment]
Not taking this on Tycho.
