### ISSUE TITLE
DevTools Inspector tooltip get element width/height wrong when browser zoomed

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1157]
Firefox isomorphic: https://bugzilla.mozilla.org/show_bug.cgi?id=1341580

I don't talk about image tooltip(white), I mean the element tooltip(black).

### Actual results
The value showed on the tooltip is considered DPI, but not considered zoom rate.
When I zoom in, the value will bigger.

<img width="1280" alt="2017-06-09 19_58_35-greenshot" src="https://user-images.githubusercontent.com/15178410/26974512-4172ac02-4d4e-11e7-843f-2e964f07786b.png">
<img width="1280" alt="2017-06-09 19_58_57-greenshot" src="https://user-images.githubusercontent.com/15178410/26974511-41715f50-4d4e-11e7-93f5-2c375525d539.png">

### Expected results:
Always same as `getComputedStyle()`

**Comment by wolfbeast** [comment]
Can you please verify in the current unstable that it's fixed?

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
Ad #1154 and #1160
I'm sorry, but these changes are not included in this update (last unstable version).
You see also this file: omni.ja in the Pale Moon folder.

**Comment by wolfbeast** [comment]
@janekptacijarabaci They should be (build of 2017-06-13)

**Comment by wolfbeast** [comment]
Thanks for the crickets. I've verified this myself as working.
