### ISSUE TITLE
When zoom in, checkbox and radio pixelated

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1159]
Firefox isomorphic.

Because OS checkbox and radio are not designed to other size-scale.

<img width="40" alt="2017-06-09 20_45_41-checkboxes vs radio buttons" src="https://user-images.githubusercontent.com/15178410/26976028-c780b32e-4d54-11e7-9d03-a65523ba72f2.png">
<img width="29" alt="2017-06-09 20_45_48-checkboxes vs radio buttons" src="https://user-images.githubusercontent.com/15178410/26976027-c7806a86-4d54-11e7-98b8-5bc1dc9fc5c6.png">

You should:
- Implement own (like Chrome & Edge), or
- Don't scale it when zoom

**Comment by wolfbeast** [comment]
Please provide more details. Exact steps to reproduce etc.

also, what's this "firefox isomorphic" on your issue reports? does it render it isomorphic? comparison?...

**Comment by zcyzcy88** [comment]
## Step
1. view a page that contains checkbox and radio (demo: https://jsfiddle.net/ffL0357n/)
<img width="99" alt="2017-06-09 22_43_31-tryit editor v3 5" src="https://user-images.githubusercontent.com/15178410/26980561-23e68728-4d65-11e7-9ba1-a010e6993626.png">

2. zoom in page
<img width="124" alt="2017-06-09 22_43_42-tryit editor v3 5" src="https://user-images.githubusercontent.com/15178410/26980567-25ff265a-4d65-11e7-885d-6213465c37d7.png">

## Result
checkbox and radio pixelated


Isomorphic mean: the bug inhered from Firefox

**Comment by wolfbeast** [comment]
I think your translator gave you the wrong term ;)

Also, unable to reproduce. On Windows 7, these controls are not scaled when zooming in. Implementing our own is not a good idea because it will prevent controls from being system-themed.

**Comment by zcyzcy88** [comment]
> _Off topic_
In mathematics, an isomorphism (from the Ancient Greek: ἴσος isos "equal", and μορφή morphe "form" or "shape")
Same as Firefox (because **inherited** from Firefox).
Ah, misspelling... Auto-correcter not point it out.

Unable to reproduce?
I have installed the latest unstable and try again.

Zoom 100%:
<img width="1280" alt="2017-06-09 23_18_04-greenshot" src="https://user-images.githubusercontent.com/15178410/26982123-f14e8248-4d69-11e7-8b91-05117dd09014.png">

Zoom in:
<img width="1280" alt="2017-06-09 23_18_08-greenshot" src="https://user-images.githubusercontent.com/15178410/26982122-f149c9a6-4d69-11e7-8440-3fc8f48a047b.png">

**Comment by zcyzcy88** [comment]
And, if scale up it by another way (such as CSS), these controls will worse too.
https://jsfiddle.net/ffL0357n/1

<img width="1280" alt="2017-06-09 23_28_10-greenshot" src="https://user-images.githubusercontent.com/15178410/26982542-52e30672-4d6b-11e7-9161-974b55682768.png">

Same on Bugzilla:
OS X: https://bugzilla.mozilla.org/show_bug.cgi?id=746440

**Comment by janekptacijarabaci** [comment]
> On Windows 7, these controls are not scaled when zooming in.

Also on Linux.

I suggest adding the label `OSX`.

**Comment by wolfbeast** [comment]
you can't apply mathematical terms to general conversation... ;-)

As said, these controls are handed off to the operating system. this means that depending on OS you will have different behavior. Win 7 and Linux don't scale, Win 10 apparently does but in a bad way. So the pixelation in this issue is Win 10 only.

**Comment by janekptacijarabaci** [comment]
Ad Windows 10

IMHO it is not a tragedy:
![w10](https://user-images.githubusercontent.com/2373486/27032570-bf93d29a-4f75-11e7-86c2-a69a66e1f671.png)
![w10_1](https://user-images.githubusercontent.com/2373486/27032566-ba60f816-4f75-11e7-948e-d5599152085a.png)

**Comment by wolfbeast** [comment]
@janekptacijarabaci Apparently your windows 10 also does as expected and doesn't actually scale the controls... So it's even more of a corner case then? I'd mark this worksforme in that case.

**Comment by janekptacijarabaci** [comment]
@wolfbeast 

Yes. MSIE / EDGE:
![w10_1](https://user-images.githubusercontent.com/2373486/27033123-38b7ae6a-4f78-11e7-98a9-2252d0a4eac0.png)
but Pale Moon / Firefox (last nightly version) does not have this function.

**Comment by janekptacijarabaci** [comment]
Btw, I don't know if this difference (between `checkbox` and `radio` - and their alignment) is right there:
![2](https://user-images.githubusercontent.com/2373486/27033469-b9ed1ea6-4f79-11e7-8f6c-73f7f756a9b0.png)
See:
https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/layout/style/forms.css#L496
and
https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/layout/style/forms.css#L506

**Comment by zcyzcy88** [comment]
@janekptacijarabaci
Because MS **simulate** Windows-10-style controls in Edge, not use OS controls.
(You can see these also in IE 11 on Windows 7)

**Comment by janekptacijarabaci** [comment]
Yes. But both solutions make sense.

**Comment by Lorienna** [comment]
On my Win7, the issue is reproducible at DPI display resolutions other than the default 96 DPI (100%).

Here's how it looks at the `Medium - 125%` (120 DPI) display setting:

<img src="https://user-images.githubusercontent.com/26753987/36935328-a966c952-1f07-11e8-8c43-e2bb05029fa9.gif" alt={screenshot}>
