### ISSUE TITLE
Support "SourceMap" header (along with "X-SourceMap")

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1163]
Source Map Revision 3 Proposal:
https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/

> The HTTP header should supply the source map URL reference as:
SourceMap: \<url\>
Note: previous revisions of this document recommended a header name of “X-SourceMap”. This is now deprecated; “SourceMap” is now expected.

**Comment by wolfbeast** [comment]
Spec change. Very straightforward.

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
I suggest you add the label `UXP task`.

**Comment by wolfbeast** [comment]
I've already fixed it in UXP.
