### ISSUE TITLE
Pale Moon crashes shortly after graphic driver resets

### ISSUE THREAD

**Issue by Domochevsky** [MoonchildProductions/Pale-Moon#1165]
At effectively random my graphic driver (nvidia) will be reset by my system (Win7 HP), likely due to a failing mainboard and the connections thereof. ("...graphic driver has stopped responding and was reset...")

As a result Pale Moon will become unstable and eventually crash.
For example, when opening a menu, which will only display its frame, but no contents. Or when stopping/starting a HTML5 video. Anything that messes with graphics features, basically.

A crash dump can be found here, if I got the right one. -> [Link](https://wildwestscifi.net/Misc/palemoon_crash_dump.zip)

**Comment by wolfbeast** [comment]
It's not possible to prevent crashes if the graphics driver gets yanked out from under us.
You may mitigate some of it by disabling hardware acceleration in options, but no guarantees it will keep the browser stable even then.
Kindly fix your failing system :)
