### ISSUE TITLE
keyword-aware navbar suggestions

### ISSUE THREAD

**Issue by Bfgeshka** [MoonchildProductions/Pale-Moon#1167]
I'd like to suggest this feature.

What it means: if you're using keywords for search engines, writing them adds autosuggestion search in "search engine domain + search query".

I.e. if you're using, for example, google search with `gg` keyword, writing `gg abc` will find suggestions (in history, bookmarks etc.) for `google.com abc` too. So, with this feature you can avoid some steps in repeated search routine.

**Comment by wolfbeast** [comment]
Not taking this on Tycho. The address bar search has been changed in UXP -- if this is still a desired enhancement there please open an issue on the UXP repo.
