### ISSUE TITLE
Share CSS rule processors between documents

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#117]
Reference bug: https://bugzilla.mozilla.org/show_bug.cgi?id=77999

Code in https://bugzilla.mozilla.org/show_bug.cgi?id=77999#c49 commits needs to be evaluated for portability (and probably un-refactored for us)

Pros: reduce memory footprint with large CSS sheets with many @-moz-document statements (like ABL)
Cons: Tricky caching that may result in stale CSS data, especially if rule evaluation results change on dynamic sites.

**Comment by DragoonAethis** [comment]
Some tests were made by dobreprogramy site, under pessimistic conditions [this does wonders](http://gallery.dpcdn.pl/imgc/News/64049/g_-_-x-_-_-_64049x20150630131609_0.png), under a bit saner load [still saves a lot of memory](http://gallery.dpcdn.pl/imgc/News/64049/g_-_-x-_-_-_64049x20150630131613_0.png) ([article in Polish](http://www.dobreprogramy.pl/Firefox-bedzie-wymagal-jeszcze-mniej-pamieci-operacyjnej,News,64049.html), mostly readable via Google Translate or such). Test done with stable FF 38.0.6 vs recent Nightly 42 with ABP (according to authors).

**Comment by wolfbeast** [comment]
Assigning this to myself for now, see if i can port the necessary code across.

**Comment by wolfbeast** [comment]
I've got the preliminary cache key work in, but unfortunately, refactoring has been extensive prior to this addition in the Mozilla codebase, so porting this is severely complicated. I don't understand enough of the refactoring changes present (specifically the class changes and memory reporting) to realistically fit this into my current workload.

Please see the branch CSS-unification for the preliminary work which implements the first of the Mozilla commits in the previous comment. Feel free to take this bug if you are familiar with the type of code and feel like a challenge! Note that this should be implemented very similar to nsLayoutStylesheetCache and that can likely be used as a base to work from for the new code.

**Comment by wolfbeast** [comment]
Since we're rebasing, this may have become easier to implement now.
Someone should consider re-evaluating the feasibility of this.

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
