### ISSUE TITLE
Non-breaking spaces from a bookmarks HTML file disappear after importing

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1170]
_This has been tested on Win7x64._

### Steps to reproduce:

1. Launch the Pale Moon.
2. Open the Library.
3. Create a new bookmark/folder or choose an already existing one.
4. Add non-breaking spaces to `Name`/`Tags`/`Keyword`/`Description` fields.
5. Export the bookmarks to HTML.
6. Import the bookmarks from the HTML file created in the step 5.

### Actual results:
Almost all spaces are gone, except those enclosed by other symbols, and those in the `Name` fields of the common folders.

### Expected results:
All NBS should be recognized and left intact.

---

### Regression range:

<b>Last Good: `14.0a1 (2012-03-24, 03:11:00)`</b>
https://archive.mozilla.org/pub/firefox/nightly/2012/03/2012-03-24-03-11-00-mozilla-central/
Built from http://hg.mozilla.org/mozilla-central/rev/df1f94b2bdee

<b>First Bad: `14.0a1 (2012-03-24, 04:02:34)`</b>
https://archive.mozilla.org/pub/firefox/nightly/2012/03/2012-03-24-04-02-34-mozilla-inbound/
Built from http://hg.mozilla.org/integration/mozilla-inbound/rev/6bbe864b5162

<b>Pushlog:</b> https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=df1f94b2bdee&tochange=6bbe864b5162

**Comment by JustOff** [comment]
@Lorienna, what exactly do you mean by non-breaking spaces?

**Comment by wolfbeast** [comment]
Probably means `&nbsp;` entities.
Looks like the change is that https://bugzilla.mozilla.org/show_bug.cgi?id=482911 changes the import from the old Netscape tokenizer to the HTML5 parser.

@Lorienna, when you say "spaces are gone" do you mean that the spaces have been collapsed into single spaces, or that the entities are completely gone and there is 0 space between words?

**Comment by JustOff** [comment]
AFAIU &nbsp; is not supported in Name/Tags/Keyword/Description fields, at least it is not parsed to space by browser interface and displayed as is.

**Comment by Lorienna** [comment]
By _non-breaking space_ I mean a space symbol obtainable from a standard Windows Charmap (it's named `U+00A0 No-Brake Space` there, being marked red):

![nbs](https://user-images.githubusercontent.com/26753987/27252785-37e453f8-536f-11e7-8af9-4e82af91a9cc.png)

...or by pressing `Alt` + `255` keys on a keyboard's numeric keypad  (which is marked red below):

![keyboard](https://user-images.githubusercontent.com/26753987/27252783-2b2ede44-536f-11e7-91c6-fe3aa70f6417.png)

**Comment by janekptacijarabaci** [comment]
Non-breaking spaces are whitespace chars - see `trim()` function.

**Comment by JustOff** [comment]
Then fix seems rather simple, we can add following `_weakTrim()` function
```
  _weakTrim: function weakTrim(aStr) {
    return aStr.replace(/^\s+|\s+$/g, '');
  },
```
and use it instead of [ES5 trim()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/trim) in [BookmarkHTMLUtils.jsm](https://github.com/JustOff/Pale-Moon/blob/master/toolkit/components/places/BookmarkHTMLUtils.jsm), but I'm not sure we should ignore `U+00A0` completely.

**Comment by Lorienna** [comment]
Please make sure NBS will be treated in those text fields like they had been before the regression, i.e. no visible difference from a usual alphabetic character.

**Comment by JustOff** [comment]
@Lorienna, could you please give a meaningful example of bookmarks.html with non-breaking spaces which is imported incorrectly?

**Comment by wolfbeast** [comment]
`trim()` only removes leading and trailing whitespace.
I'm not inclined to change that behavior if it's about leading and trailing whitespace since that should not be retained, regardless of whether it's non-breaking or not.

Once again, please see my previous comment. Kindly answer my question what exactly is observed (with examples) and provide an example export file that is apprently incorrectly imported so the behavior can be verified?

**Comment by Lorienna** [comment]
I've been thinking about how to clarify this to you...

Looks like NBS have become treated like __ordinary spaces__ which are entered via the `Space` key on a keyboard.

Ordinary spaces are dropped out upon HTML importing, except any amount of those __between characters__, e.g.:

`a     a`
`a     a     a`
`a     a     a     a`

...and except those __kept completely intact__ in the `Name` field of __a folder__, e.g.:

`     `
`     a`
`a     `
`     a     `
`     a     a     `

Is this a bug or a feature? Should only a single ordinary space be kept between characters, e.g.:

`a a`

...I don't know. Do you?

But I strongly believe that NBS, on the other hand, should be __always kept everywhere a normal character is usually kept__, otherwise there's simply no point in using them.

I'll provide a file a little later :)

---

Also, please do the following and see what happens:

1. Open the Browser/Error Console.
2. Open the Library.
3. Right click and select `New Bookmark...`
4. Paste NBS from the Charmap to `Location` field (or type `255` on a numeric keypad while holding `Alt` key).
5. Click `Add`.

The bookmark becomes undeletable, unexportable, and there are a lot of different errors in the consoles.

**Comment by Lorienna** [comment]
Here's the file, please remove the .txt extension:


[bookmarks.html.txt](https://github.com/MoonchildProductions/Pale-Moon/files/1083038/bookmarks.html.txt)

**Comment by JustOff** [comment]
@Lorienna, sorry, but this example looks purely artificial. Do you have any real issue with your bookmarks?

**Comment by Lorienna** [comment]
That file illustrated my point above...

> Do you have any real issue with your bookmarks?

I'm heavily using NBS to create extra spaces between the bookmarks on the Bookmarks Toolbar to make them easier on the eyes, since as an average user I consider this being much more simple than dealing with third-party styles or scripts.

**Comment by wolfbeast** [comment]
Collapsing spaces into a single space is normal for HTML display so this works as-intended. Non-breaking spaces in webpages are also not suitable for creating defined spaces (that's why we have `<pre>`)

Simply use a userChrome selector to add more space between the bookmarks toolbar entries. Using non-breaking spaces in each and every bookmark to achieve this display effect is nonsense.

**Comment by Lorienna** [comment]
@wolfbeast , please explain for which purpose `U+00A0 No-Break Space` exists, then? I really don't understand.

**Comment by wolfbeast** [comment]
> In word processing and digital typesetting, a non-breaking space (" ") (also called no-break space, non-breakable space (NBSP), hard space, or fixed space) is a space character that prevents an automatic line break at its position.

https://en.wikipedia.org/wiki/Non-breaking_space

**Comment by Lorienna** [comment]
Well, thank you, and pardon my ignorance.
