### ISSUE TITLE
Tags disappear after importing bookmarks HTML file upon a clean installation or on a new profile

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1172]
_This was tested on Win7x64._

### Steps to reproduce:

1. Launch the Pale Moon.
2. Open the Library.
3. Create a new bookmark or choose an existing one.
4. If the `Tags` field is being empty, type something there.
5. Export the bookmarks to HTML.
6. Close the Pale Moon.
7. Create a new browser profile or select another old one.
8. Launch the Pale Moon once again.
9. Import the HTML file created in the step 5.

### Actual results:

Tags have disappeared.

### Expected results:

Tags should be present.

---

### Regression range:

Looks like FF had been affected since at least v. 3.0.x . . .

__Last Bad: `43.0a1 (2015-09-14)`__
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-14-03-02-05-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/9ed17db42e3e46f1c712e4dffd62d54e915e0fac

__First Good: `43.0a1 (2015-09-15)`__
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-15-03-02-32-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/c69e31de9aec2b9e8c0b3128ac6dc3897aa7381f

__Pushlog:__ https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=9ed17db42e3e46f1c712e4dffd62d54e915e0fac&tochange=c69e31de9aec2b9e8c0b3128ac6dc3897aa7381f

__Bug 416611:__ https://bugzilla.mozilla.org/show_bug.cgi?id=416611

**Comment by wolfbeast** [comment]
Not really a regression since we never had this functionality.
As an enhancement, it's easy enough to add. Taking.
