### ISSUE TITLE
[suggestion] UI Events (draft) - implement auxclick

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1174]
UI Events (but `W3C Working Draft` only):
https://w3c.github.io/uievents/#event-type-auxclick

> The auxclick event type MUST be dispatched on the topmost event target indicated by the pointer, when the user presses down and releases the non-primary pointer button, or otherwise activates the pointer in a manner that simulates such an action. The actuation method of the mouse button depends upon the pointer device and the environment configuration, e.g., it MAY depend on the screen location or the delay between the press and release of the pointing device button.

> The auxclick event should only be fired for the non-primary pointer buttons (i.e., when button value is not 0, buttons value is greater than 1). The primary button (like the left button on a standard mouse) MUST NOT fire auxclick events. See click for a corresponding event that is associated with the primary button.

> The auxclick event MAY be preceded by the mousedown and mouseup events on the same element, 
disregarding changes between other node types (e.g., text nodes). Depending upon the environment configuration, the auxclick event MAY be dispatched if one or more of the event types mouseover, mousemove, and mouseout occur between the press and release of the pointing 
device button.

---

You add the label `Standards Compliance` / `Web Compatibility` (?), please.

**Comment by wolfbeast** [comment]
Draft specs are not considered standards. What is the general adoption rate of this draft in the mainstream browsers?

**Comment by THEtomaso** [comment]
Seems to have been implemented for both Firefox and Chromium:
https://bugzilla.mozilla.org/show_bug.cgi?id=1304044
https://bugs.chromium.org/p/chromium/issues/detail?id=625847

**Comment by wolfbeast** [comment]
What about Opera, IE, Edge and Safari?

**Comment by THEtomaso** [comment]
Apparently, Opera implemented it in v42:
https://dev.opera.com/blog/opera-42/

I guess when it has been adopted by Chromium, most of its derivatives will implement this feature blindly.

**Comment by wolfbeast** [comment]
IE doesn't implement this. I have no way to test Edge or Safari.

The only issue I have with this is that it gives websites yet another way to control availability of the context menu (it can be used to disable it by preventing the default action). Closing this for now but with that in mind that it might be abused.

**Comment by JustOff** [comment]
I just checked that neither EDGE nor Safari supports `event-type-auxclick` at the moment.

**Comment by wolfbeast** [comment]
Thanks.
