### ISSUE TITLE
Videos on coub.com stall

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1176]
Videos on coub.com stall after a few seconds.

- Verified an issue on stable and unstable
- New format reader makes no difference
- Disabling MSE fixes it

Mozregression puts this as fixed in FF50:
Nightly range:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=4c05938a64a7fde3ac2d7f4493aee1c5f2ad8a0a&tochange=711963e8daa312ae06409f8ab5c06612cb0b8f7b
Inbound:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=4c05938a64a7fde3ac2d7f4493aee1c5f2ad8a0a&tochange=9ee862a030f350e481e3fa3a09d6dc28d4dbf591

**Comment by wolfbeast** [comment]
Inbound has several MSE bugs that seem relevant.
@trav90 -- this is probably best handled by you since you pretty much own the media/MSE subsystem at this point.

BMO MSE bugs in the fix range:
https://bugzilla.mozilla.org/show_bug.cgi?id=1286796 - Replace InvalidAccessError usage with TypeError.
https://bugzilla.mozilla.org/show_bug.cgi?id=1286723 - Add support for live seekable attribute.
https://bugzilla.mozilla.org/show_bug.cgi?id=1286722 - Add mediasource event handler attributes.
https://bugzilla.mozilla.org/show_bug.cgi?id=1287021 - Set delaying-the-load-event-flag to false when attaching media source.
https://bugzilla.mozilla.org/show_bug.cgi?id=1287244 - Remove check for not 'updating' in {set,clear}LiveSeekableRange().

**Comment by trav90** [comment]
Looks like we will need patches ported from each of those BMO bugs in order to attain MSE spec compliance.

**Comment by wolfbeast** [comment]
So this is a blocker for #1033 then, correct?

**Comment by wolfbeast** [comment]
If you want me to tackle any of these, let me know. I just don't want to get in your way.

**Comment by trav90** [comment]
Yes it blocks #1033. And no worries about getting in my way. :) But seeing as these are all pretty trivial changes I went ahead and ported them myself.

**Comment by wolfbeast** [comment]
Confirmed fixed on Windows with #1179 merged.
