### ISSUE TITLE
SVG icons on GitHub are blurry (and unevenly so)

### ISSUE THREAD

**Issue by spectatorBH** [MoonchildProductions/Pale-Moon#1188]
**Test environment**
Win7 x64, PM 27.4.0a1 (32-bit), build 20170620195942, no zoom
_Although the issue also applies to PM 26.5.0 (64-bit) and Fx 52.2.0 ESR (32-bit)_.

Graphics HW details | _
--- | ---
Adapter Description: | NVIDIA GeForce GT 240M
Adapter Drivers: | nvd3dumx, nvwgf2umx, nvwgf2umx, nvd3dum, nvwgf2um, nvwgf2um
Adapter RAM: | 1024
ClearType Parameters: | Gamma: 2200, Pixel Structure: R, ClearType Level: 100, Enhanced Contrast: 50
Device ID: | 0x0a34
Direct2D Enabled: | true
DirectWrite Enabled: | true (6.2.9200.22164)
Driver Date: | 8-17-2015
Driver Version: | 9.18.13.4181
GPU #2 Active: | false
GPU Accelerated Windows: | 2/2 Direct3D 11 (OMTC)
Subsys ID: | 021e1025
Vendor ID: | 0x10de
WebGL Renderer: | Google Inc. -- ANGLE (NVIDIA GeForce GT 240M Direct3D11 vs_4_1 ps_4_1)
windowLayerManagerRemote: | true
AzureCanvasBackend: | direct2d 1.1
AzureContentBackend: | direct2d 1.1
AzureFallbackCanvasBackend: | cairo
AzureSkiaAccelerated: | 0

**Steps to reproduce**
* open https://github.com/MoonchildProductions/Pale-Moon/commits/master
* compare the rendering of the blue icons on the right hand side of each commit row (the issue is more apparent on the ones with the pop-up text "Copy the full SHA");
* try to do the same on any [not too old] Chromium-based browser and compare icons' rendering.

**Expected results**
* all SVG icons are rendered crisp and clear;
* all the same SVG icons are rendered the same;
* SVG rendering should be if not as good then at least not _much_ worse than in Chromium.

**Actual results**
* all small SVG icons are blurry;
* some icons look much more blurry than the others, although their SVG code is the same;
* even the best-looking ones are not rendered as crisp as in Chromium-based browsers.

**Screenshots**

Zoom (pixel accurate) | Pale Moon 27.4.0a1 | SRWare Iron 58.0.3050.0
--- | --- | ---
100% | ![svg on goana](https://user-images.githubusercontent.com/21036474/27447177-bf15e234-5788-11e7-83e9-2b4ab45931f9.png) | ![svg on blink](https://user-images.githubusercontent.com/21036474/27447190-c670bc34-5788-11e7-8525-62f3f3839da7.png)
400% | ![svg on goana 400 part](https://user-images.githubusercontent.com/21036474/27447156-a8082660-5788-11e7-84b4-2f319cd6752f.png) | ![svg on blink 400 part](https://user-images.githubusercontent.com/21036474/27447163-ac3bd358-5788-11e7-80dd-dbe2afd93650.png)

**Comment by spectatorBH** [comment]
The exact issue presented above might look as very minor per se, but it definitely shows that SVG rendering in Goanna needs to be seriously improved -- to both look good and be on par with Blink. Especially considering SVG-based elements on the web are being used more and more nowadays.

**Comment by mattatobin** [comment]
I can confirm this behavior but I haven't seen any sites other than Github do this.. Perhaps just an issue with them?

Please seek out other sites that show this behavior.

**Comment by wolfbeast** [comment]
Please file a bug at bugzilla.mozilla.org (confirmed in nightly) so the people who have written the svg scaling code can have a look at it.

Kindly post the bug number here when you've done so.

**Comment by spectatorBH** [comment]
Well, here it comes: https://bugzilla.mozilla.org/show_bug.cgi?id=1375720

**Comment by mattatobin** [comment]
In the future please do not mention Pale Moon even as an example link in Mozilla bugs.. Hopefully, they will not use it as a reason to ignore the issue.

**Comment by wolfbeast** [comment]
CSS that seems to be at the root of this: line-height statements.

The `<body>` gets a line height set to `1.5` (no unit). The buttons containing the hash links (and svg) are having their line height set to `20px` via the `btn` class.
Apparently this causes a sub-pixel shift/sizing of the button's position (probably half a pixel), "de-snapping" the SVG from pixel boundaries and having AA kick in, resulting in the blur.

Setting the button's height to an odd number of px blurs all buttons. Setting it to even has them sharp.
Setting the body line height to `1.5em` (with unit) fixes all issues, as well, so there's something odd going on with inheritance.

**Comment by wolfbeast** [comment]
Reducing the layout to the attached test case it became clear that it's not necessarily related to mixing units or having a height set on the button. Looks like SVGs are simply not pixel-snapped and have to happen to land on an integer in the final layout to be drawn crisp. I hope the people at Mozilla find the cause since I'm not entirely sure what's going on here.

[svgblur.zip](https://github.com/MoonchildProductions/Pale-Moon/files/1100385/svgblur.zip)
