### ISSUE TITLE
Google.com Hangs Pale Moon 27.3.0 on Linux

### ISSUE THREAD

**Issue by linuxrocks123** [MoonchildProductions/Pale-Moon#1189]
Going to www.google.com (which apparently has some special video or something today) causes Pale Moon 27.3.0 to hang until killed.  I'm using the official Linux binaries on Slackware64-current.

This appears on the console directly before the hang:
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Can't find symbol 'glXCreateContextAttribsARB'.
WebGL(0x7fffbbacb800)::ForceLoseContext

**Comment by mattatobin** [comment]
When using AlienBob's slackbuild you must report issues to him as a first responder because he is not using official build configuration.

However, could you please check this out with khronosschoty's build at http://repo.khronosschoty.org/Slackware/Pale-Moon/14.2/ and our generic binary at http://linux.palemoon.org/ for this behavior.

**Comment by khronosschoty** [comment]
Tested out the "generic binary", AlienBOB's package for current , and the Slackware package that  khronosschoty (me) maintains; and was unable to reproduce the error described. Test was done using AlienBOB's ffmpeg package and the ffmpeg package found in default Slackware-current. Test OS was Slackware64-current. 

>  ATTENTION: default value of option force_s3tc_enable overridden by environment.
Can't find symbol 'glXCreateContextAttribsARB'.
WebGL(0x7fffbbacb800)::ForceLoseContext

is present using all three versions. 

The browser remains responsive (does not hang or freeze), however, and google's video / music app appears to work without issue.

**Comment by linuxrocks123** [comment]
I found the problem: it was the old "Pale Moon finds apulse and proceeds to roll over and die" problem again.  Hiding apulse so Pale Moon couldn't find it anymore fixed the issue.

(I mean, there's no sound, but that's normal.)

**Comment by khronosschoty** [comment]
There should be sound even if you do not have Pulse, I wonder what your sound issue could be?
