### ISSUE TITLE
Disable screensaver when playing HTML5 video on Linux/Mac

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/Pale-Moon#119]
My patches have resulted in successful builds, but the browser segfaults when playing HTML5 videos on YouTube. At this point I'm at a loss of where to go. If anyone has any suggestions, please let me know.

You can view the in-progress patch on my ["wakelocklistener-linux"] (https://github.com/trav90/Pale-Moon/tree/wakelocklistener-linux) branch

Mozilla bugs for reference: [811261] (https://bugzilla.mozilla.org/show_bug.cgi?id=811261) & [1168090] (https://bugzilla.mozilla.org/show_bug.cgi?id=1168090)

**Comment by squarefractal** [comment]
[**@trav90**](https://github.com/trav90) commented on [Friday, July 3, 2015 3:48:33 AM](https://github.com/MoonchildProductions/Pale-Moon/issues/119#issue-92747559 "2015-07-02T22:18:33Z - Replied by Github Comment Enhancer"):
> At this point I'm at a loss of where to go.

Obtain a trace from a debug build?

**Comment by trav90** [comment]
I did, but am still unsure of what needs done to fix the issue.

**Comment by stevenschlansker** [comment]
This affects Mac as well, see #334.

**Comment by stevenschlansker** [comment]
https://github.com/MoonchildProductions/Pale-Moon/compare/master...trav90:wakelocklistener-linux#diff-222345ed97a9414da442f01c4c233a50R45

`nsClassHashtable<nsStringHashKey, WakeLockTopic> mTopics;`

I don't see anywhere this hash table has `.Init()` called on it, that ended up being the problem in #368, maybe it's relevant here?

**Comment by trav90** [comment]
It likely is. I'll look into it. Thanks!

**Comment by stevenschlansker** [comment]
I think with #368 merged we can close this, yes?

**Comment by trav90** [comment]
It still affects Linux at this point. I tried using a patch similar to #368, but it caused build bustage on Linux. I've been spending all my time on GStreamer support lately, and haven't had a chance yet to dig into this (though it is next on my to-do list).

**Comment by trav90** [comment]
I still have been unable to get a working build that resolves this. It is however, working in Tycho.
