### ISSUE TITLE
'browser.search.defaultenginename' pref cannot be modified via user.js or prefs.js on PM, but it works again on FF now

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1193]
On Pale Moon, the value of `browser.search.defaultenginename` cannot be changed by manually editing `user.js` or `prefs.js` files, but this appears to be a security measure implemented by Mozilla developers:

__Last Good: `34.0a1 (2014-08-05)`__
https://archive.mozilla.org/pub/firefox/nightly/2014/08/2014-08-05-03-03-00-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/7f81be7db528

__First Bad: `34.0a1 (2014-08-06)`__
https://archive.mozilla.org/pub/firefox/nightly/2014/08/2014-08-06-03-02-01-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/6cbdd4d523a7

__Pushlog:__ https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=7f81be7db528&tochange=6cbdd4d523a7

__`Bug 1029148` - store "current search engine" configuration outside of prefs:__
https://bugzilla.mozilla.org/show_bug.cgi?id=1029148

<blockquote>Goal: we want to make it as difficult as possible to hijack the search engine by dropping a file or editing prefs.js in the profile folder. ... Proposed changes:<br>
...<br>
- ignore user values of <tt>browser.search.defaultenginename</tt> (we still need to respect the default value, because that's the way the default search engine is customized for different locales, or for ESR users).<br>
...<br>
<i>https://bugzilla.mozilla.org/show_bug.cgi?id=1029148#c3</i></blockquote>

---

However, on FF this pref is now modifiable again, with the devs citing addons compability as one of the reasons for restoring this, IIUC (but it's still not possible to actually set a search engine this way):

__Last Bad: `46.0a1 (2016-01-09)`__
https://archive.mozilla.org/pub/firefox/nightly/2016/01/2016-01-09-03-02-08-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/0f363ae95dc90d593394ef464aa500804c824962

__First Good: `46.0a1 (2016-01-10)`__
https://archive.mozilla.org/pub/firefox/nightly/2016/01/2016-01-10-03-02-14-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/c33f30666b37dbceffb9fbe5089a668db8893a85

__Pushlog:__
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=0f363ae95dc90d593394ef464aa500804c824962&tochange=c33f30666b37dbceffb9fbe5089a668db8893a85

__`Bug 1237648` - The defaultEngine attribute should just be an alias to the currentEngine attribute:__
https://bugzilla.mozilla.org/show_bug.cgi?id=1237648

<blockquote>... The way forward I'm proposing is to keep both attributes (to avoid breaking add-ons), but with a single implementation behind them, so that they are guaranteed to always have matching values.<br><br>
<i>https://bugzilla.mozilla.org/show_bug.cgi?id=1237648#c0</i></blockquote>

---

Please take a closer look at the situation, and whether there's something that should be addressed on PM as well.

**Comment by wolfbeast** [comment]
Search engine hijacking is a serious issue that is very commonly used to misdirect users. Our current state of things (no direct access to the search engine via preferences) is desired.

**Comment by Lorienna** [comment]
Well, I'm closing the issue, then.
