### ISSUE TITLE
Javascript bug on Steam Store

### ISSUE THREAD

**Issue by HouyiTheArcher** [MoonchildProductions/Pale-Moon#1196]
![2017-06-23 17_24_48-pale moon](https://user-images.githubusercontent.com/13876697/27557790-8407874a-5ac3-11e7-826d-d4743dfba6c8.png)
http://store.steampowered.com

Steps to reproduce:
1. Sign-in;
2. Add something to the shopping cart;
3. Go to the cart and press "Remove all items".

Expected result: dialog pop-up with confirmation.

What actually happens: pop-up shows for half a second, then a blank page with "[object Object]" text opens. Text in URL bar:
`javascript:ShowConfirmDialog( '', 'Are you sure you want to remove all items from your shopping cart?', 'Yes', 'No').done( function() { ForgetCart(); } );`

Reproduced it with a clean profile. Pale Moon 27.3 x64, Win64, 8.1. Also reproducible with the latest Unstable build.

**Comment by janekptacijarabaci** [comment]
AFAIK: The issue is not on the browser side.

See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1268047
but also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1306472

**Comment by HouyiTheArcher** [comment]
I've done some additional research... The same problem is reproducible with the latest FF, but Webkit/Blink browsers handle this "correctly". Looks like another "made-for-Chrome" thing. Shall I close the issue?

**Comment by mattatobin** [comment]
Well Steam uses webkit/blink internally so least it is somewhat more understandable they would cater to it. Doesn't excuse the behavior but it is slightly more understandable.

Would be nice know what is causing it and eval actually fixing it at some point..

**Comment by wolfbeast** [comment]
@janekptacijarabaci the bugs you indicate are unrelated. It's behavior introduced in FF48 and backed out in FF49 -- not something we should have in our tree.

What needs to be investigated is what exactly goes wrong in the site scripting (i.e.: why this javascript is launched in a new browsing context) and why.

**Comment by wolfbeast** [comment]
Yeah, so breaking compatibility with the web makes Steam's website work. No thanks.
