### ISSUE TITLE
Pentadactyl error on scrolling certain pages

### ISSUE THREAD

**Issue by tidux** [MoonchildProductions/Pale-Moon#1197]
`resource://dactyl/buffer.jsm: 1742: TypeError: options is undefined`

Manifests on: https://forum.palemoon.org/viewtopic.php?t=15806&p=116121 and certain Twitter pages.

**Comment by tidux** [comment]
This now manifests on typing `gg` on ANY page.  Uninstalling Pentadactyl for now.

**Comment by tidux** [comment]
Looks like an upstream issue: https://github.com/5digits/dactyl/issues/12

**Comment by tidux** [comment]
Disabling and re-enabling smooth scrolling seems to make the issue go away at least temporarily.

**Comment by wolfbeast** [comment]
Please don't file extension bugs against the browser repo.
