### ISSUE TITLE
Add -moz-os-version support

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#120]
Using wholesale CSS media queries to determine the version of Windows we're using would make styling for them much easier, especially for Windows 8+, where selectors currently are several nested media queries.

BMO: [810399] (https://bugzilla.mozilla.org/show_bug.cgi?id=810399), [907373] (https://bugzilla.mozilla.org/show_bug.cgi?id=907373) & [1166867] (https://bugzilla.mozilla.org/show_bug.cgi?id=1166867).

**Comment by wolfbeast** [comment]
Good call -- would actually simplify what I've done with the window title as well (using tricks to determine Win 8 with compositor etc.)

**Comment by Lootyhoof** [comment]
Confirmed, it works! Thanks! (25.6b2)

**Comment by wolfbeast** [comment]
Only one problem.. on Win 10, it apparently doesn't work right and it still thinks it's Win 8, causing the issue with toolbar borders (apparently).

> Mozilla/5.0 (Windows NT 10.0; WOW64; rv:25.6) Gecko/20150801 Firefox/31.9 PaleMoon/25.7.0a1

Means that the OS passes the right info to the browser (it's manifested correctly) but wilfully putting an error inside the CSS block that should be excluded in commit 7e09f7235d90d8065cf8bb693a9d9d96928e299e makes it show up in the error console. So, Win10 support still seems to be broken somehow, that it thinks it's win vista, 7 or (most likely) 8

**Comment by wolfbeast** [comment]
Either that or I've just been dumb XD Sorry for the noise.
