### ISSUE TITLE
Errors on about:feeds page

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1200]
Below are the errors thrown on the `about:feeds` page every time it gets reloaded:

```c
Warning: Use of Mutation Events is deprecated. Use MutationObserver instead.
Source File: chrome://global/content/bindings/menulist.xml
Line: 240:0
```

```c
Error: TypeError: result is null
Source File: resource://app/components/FeedWriter.js
Line: 644:0
```

```c
Error: NS_ERROR_UNEXPECTED: 
Source File: chrome://browser/content/feeds/subscribe.js
Line: 17:0
```

Another one, thrown after hitting the `Subscribe Now` button:

```xul
Error: nsNavHistory::GetPageTitle is deprecated and will be removed in the next version.
<unknown>
```

---

More info will be provided later, if the need be.

**Comment by janekptacijarabaci** [comment]
See:
https://forum.palemoon.org/viewtopic.php?f=56&t=12683&p=94188#p94188
and
https://forum.palemoon.org/viewtopic.php?f=56&t=12683&p=94188#p94508

**Comment by Lorienna** [comment]
## NS_ERROR_UNEXPECTED:

```java
NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "result is null" {file: "resource://app/components/FeedWriter.js" line: 633}]'[JavaScript Error: "result is null" {file: "resource://app/components/FeedWriter.js" line: 633}]' when calling method: [nsIFeedWriter::writeContent] subscribe.js:18
```

__Last Affected: `31.0a1 (2014-03-20)`__
https://archive.mozilla.org/pub/firefox/nightly/2014/03/2014-03-20-03-02-03-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/e84a391b604b

### +

```javascript
NS_ERROR_UNEXPECTED: subscribe.js:17
```

__First Affected: `31.0a1 (2014-03-21)`__
https://archive.mozilla.org/pub/firefox/nightly/2014/03/2014-03-21-03-02-03-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/c148f0b0c8b4

### =

__Pushlog:__ https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=e84a391b604b&tochange=c148f0b0c8b4

__Changeset 174326__ - *Port nsIFeedWriter to WebIDL and stop exposing BrowserFeedWriter to the Web; r=bzbarsky:*
https://hg.mozilla.org/mozilla-central/rev/e9ea1662020a

__Bug 983845__ - *Stop exposing BrowserFeedWriter to the Web:*
https://bugzilla.mozilla.org/show_bug.cgi?id=983845

---

Consider it being FYI, if nothing else.

**Comment by janekptacijarabaci** [comment]
See also `about:about`:
`And some are omitted because they require query strings.`

I don't know if it makes sense to fix (correct) it.

**Comment by Lorienna** [comment]
@wolfbeast 
Should `about:feeds` page be put on `about:about` list of pages, given the `And some are omitted because they require query strings.` part, or not?

**Comment by Lorienna** [comment]
### nsNavHistory::GetPageTitle is deprecated and will be removed in the next version:

---

__Last Good: `24.0a1  (2013-06-19)`__
https://archive.mozilla.org/pub/firefox/nightly/2013/06/2013-06-19-03-10-48-mozilla-central/
Built from http://hg.mozilla.org/mozilla-central/rev/d2a7cfa34154

__First Bad: `24.0a1  (2013-06-20)`__
https://archive.mozilla.org/pub/firefox/nightly/2013/06/2013-06-20-03-10-10-mozilla-central/
Built from http://hg.mozilla.org/mozilla-central/rev/8ea92aeab783

__Pushlog:__ https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=d2a7cfa34154&tochange=8ea92aeab783

__Changeset 135565__ - Replace `getPageTitle` with an async API. r=mak. sr=gavin.:
https://hg.mozilla.org/mozilla-central/rev/734147446def

__Bug 834539__ - Implement `getPlacesInfo`, async successor for `getPageTitle`:
https://bugzilla.mozilla.org/show_bug.cgi?id=834539

---

__Last Bad: `44.0a1 (2015-09-28)`__
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-28-03-02-06-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/6256ec9113c115141aab089c45ee69438884b680

__First Good: `44.0a1 (2015-09-29)`__
https://archive.mozilla.org/pub/firefox/nightly/2015/09/2015-09-29-03-02-25-mozilla-central/
Built from https://hg.mozilla.org/mozilla-central/rev/acdb22976ff86539dc10413c5f366e1fb429a680

__Pushlog:__
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=6256ec9113c115141aab089c45ee69438884b680&tochange=acdb22976ff86539dc10413c5f366e1fb429a680

**Comment by Lorienna** [comment]
@janekptacijarabaci 
Thank you for repairing these errors, and for all the contributions you consistently keep making!

 :+1: :+1:

**Comment by Lorienna** [comment]
Unfortunately, I still see all these errors on PM 27.4.0 and 27.4.1, except the one below:

```c
Warning: Use of Mutation Events is deprecated. Use MutationObserver instead.
Source File: chrome://global/content/bindings/menulist.xml
Line: 240:0
```

@janekptacijarabaci, I thought you did successfully fix them, now didn't you?..

**Comment by janekptacijarabaci** [comment]
@Lorienna 
Should you try the unstable version.

**Comment by Lorienna** [comment]
My apologies, @janekptacijarabaci.

But why weren't these fixes included into the stable releases?

**Comment by wolfbeast** [comment]
You do realize that fixes in the unstable version will be in the next major release right? The fixes aren't included **yet**, but **will be**.
