### ISSUE TITLE
WebRTC doesn't build on MSVC

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1206]
Although we don't use it (and haven't tested it with Tycho), it should at the very least build on Windows with MSVC.

Linker error on MSVC:

````
13:58.61 transportlayerdtls.obj : error LNK2019: unresolved external symbol __imp__SSL_NamedGroupCon
fig referenced in function "private: bool __thiscall mozilla::TransportLayerDtls::Setup(void)" (?Set
up@TransportLayerDtls@mozilla@@AAE_NXZ)
13:58.61
13:58.61 Unified_cpp_webrtc_modules0.obj : error LNK2019: unresolved external symbol _opus_custom_mo
de_create referenced in function "public: __thiscall webrtc::AudioClassifier::AudioClassifier(void)"
 (??0AudioClassifier@webrtc@@QAE@XZ)
13:58.61
13:58.61 Unified_cpp_webrtc_modules0.obj : error LNK2019: unresolved external symbol _downmix_int re
ferenced in function "public: bool __thiscall webrtc::AudioClassifier::Analysis(short const *,int,in
t)" (?Analysis@AudioClassifier@webrtc@@QAE_NPBFHH@Z)
13:58.61
13:58.61 Unified_cpp_webrtc_modules0.obj : error LNK2019: unresolved external symbol _run_analysis r
eferenced in function "public: bool __thiscall webrtc::AudioClassifier::Analysis(short const *,int,i
nt)" (?Analysis@AudioClassifier@webrtc@@QAE_NPBFHH@Z)
13:58.61
13:58.61 xul.dll : fatal error LNK1120: 4 unresolved externals
````

**Comment by mattatobin** [comment]
When something is added or removed from media one needs to make sure that symbols.def.in in layout/media is updated to reflect any external symbols because Windows uses a shared lib by default.

**Comment by wolfbeast** [comment]
Actually, it only contains the symbols of functions that are actually in use by the rest of the code (a flawed setup, but I can how it would otherwise be a maintenance nightmare to keep the symbols definition up-to-date).

3 of the 4 are from media, and no problem and I'll add that in a commit soon. The only headscratcher for me is `SSL_NamedGroupConfig` which is part of NSS 3.27+ and which is defined in its .def file, but for some reason not picked up by `mozilla::TransportLayerDtls::Setup`

**Comment by wolfbeast** [comment]
Right, so... Apparantly our current build system does NOT pick up symbols from `/security/nss/lib/ssl/ssl.def` and have to be manually ported to `/config/external/nss/nss.def` instead.
At least UXP will have this a bit better organized.

**Comment by wolfbeast** [comment]
Confirmed building with these changes.
