### ISSUE TITLE
Would it be possible to clarify what page is blocking console output

### ISSUE THREAD

**Issue by ThosRTanner** [MoonchildProductions/Pale-Moon#1208]
Currently you just get this:

The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.

but 'this page' doesn't say which page it is referring to (so I can't give you an example to check, because I have no idea which page is doing this)

**Comment by janekptacijarabaci** [comment]
It can be done simply. But...
IMHO: It makes no sense to me. Web Console is separate for all tabs.

**Comment by ThosRTanner** [comment]
But the trace is coming on the **browser** console. I have no idea if it's me doing it  inadvertently with my extension or something else doing it

**Comment by wolfbeast** [comment]
If it **only** shows in the browser console and not the web console, then it's being prevented in the browser context (i.e.: by an extension) and not site context (page scripting). If it's a page script then it would show up in both.

**Comment by janekptacijarabaci** [comment]
See also:
https://stackoverflow.com/questions/8212373/firefox-web-console-disabled

I don't know about another extension.

**Comment by ThosRTanner** [comment]
Well, no, I maintain one for fun and for learning javascript.

**Comment by janekptacijarabaci** [comment]
If it's a extension, "this page" does not exists.

You can gradually shut down extensions.

**Comment by ThosRTanner** [comment]
Surely it must know where the code it's executing comes from?

**Comment by wolfbeast** [comment]
If it's an extension, then there is no content page, since it "comes from" the browser itself.
