### ISSUE TITLE
[suggestion] DOM - Selection API (draft) - implement selection events

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1213]
DOM - Selection API - implement selection events (`W3C Working Draft`):

http://w3c.github.io/selection-api/#selectstart-event

> 6.1 selectstart event

> When the user agent is about to associate a new range newRange to the selection in response to a user initiated action, the user agent must fire ([DOM4]) an event with the name selectstart, which bubbles and is cancelable, at the node associated with the boundary point of newRange's start prior to changing the selection if the selection was previously empty or the previously associated range was collapsed.

> If the event is canceled, the user agent must not change the selection.

> The user agent must not fire the event when the user agent sets the selection empty.

> 6.2 selectionchange event

> When the selection is dissociated with its range, associated with a new range or the associated range's boundary point is mutated either by the user or the content script, the user agent must queue a task to fire an event with the name selectionchange, which does not bubble and is not cancelable, at the document associated with the selection.

---

You add the label `Web Compatibility`, please.

**Comment by wolfbeast** [comment]
Can someone please verify this is working in the unstable builds so I can close this issue?

**Comment by JustOff** [comment]
[Search box now works fine for me on OP's site](https://forum.palemoon.org/viewtopic.php?f=29&p=116802#p116889) and I also can confirm this.

**Comment by janekptacijarabaci** [comment]
So there is some problem somewhere. `selectstart` does not work.

**Comment by h1z1** [comment]
Curious little change.  Does this not mean sites are able to further spy on these events as well?

**Comment by wolfbeast** [comment]
Closing as verified.

@h1z1 there is no issue with websites being able to see when a user selects text. The benefits certainly outweigh any potential corner case where you might want to prevent a site knowing when you interact with its content.
