### ISSUE TITLE
Blank favicon when first visiting faviconless site is still an issue

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1217]
_Tested on Win7x64; reproducible **once per session** on each faviconless web-site._

* Launch Pale Moon.
* Open the Browser Console and check `Net` => `Log` _(optionally)_.
* Go to a web-site lacking a favicon by design, e.g. `example.com`

## Expected results:

![http_expected](https://user-images.githubusercontent.com/26753987/27917006-6b968118-6273-11e7-9121-e4dfb70a368e.png)
![https_expected](https://user-images.githubusercontent.com/26753987/27917018-74346614-6273-11e7-8108-60e4e44100e5.png)

## Actual results:

![http_actual](https://user-images.githubusercontent.com/26753987/27917051-8ae9c89a-6273-11e7-9ff0-1082725bb9f7.png)
![https_actual](https://user-images.githubusercontent.com/26753987/27917062-92019a86-6273-11e7-9959-4c98c47a113f.png)

There are also 4 errors thrown by the Browser Console:

```
GET 
http://example.com/favicon.ico [HTTP/1.1 404 Not Found 181ms]
GET 
http://example.com/favicon.ico [HTTP/1.1 404 Not Found 165ms]
GET 
http://example.com/favicon.ico#-moz-resolution=20,20 [HTTP/1.1 404 Not Found 162ms]
GET 
http://example.com/favicon.ico [HTTP/1.1 404 Not Found 171ms]
```

Once the page is refreshed, the globe icon shows up as expected, with no more errors; however, switching between tabs without refreshing it causes yet another error of this type thrown every time you select the affected tab:

```
GET 
http://example.com/favicon.ico [HTTP/1.1 404 Not Found 172ms]
```

---

More info available here:
https://forum.palemoon.org/viewtopic.php?t=2141

**Comment by janekptacijarabaci** [comment]
You can try setting the following preferences in `about:config`:
`browser.chrome.site_icons`
or
`browser.chrome.favicons`
= `false`

**Comment by Lorienna** [comment]
`browser.chrome.site_icons` forbids loading favicons and image thumbnails completely, while `browser.chrome.favicons` seems to be a precisely fitting workaround solution, thank you.

Is this a wontfix issue otherwise? If so, could `browser.chrome.favicons` be set `false` by default, perhaps?

**Comment by Lorienna** [comment]
## Nightly range:

__Last old IB: `14.0a1 (2012-04-21)`__
https://archive.mozilla.org/pub/firefox/nightly/2012/04/2012-04-21-21-58-38-mozilla-central/
Built from http://hg.mozilla.org/mozilla-central/rev/7fda4d02d3ca

__First new IB: `14.0a1 (2012-04-22)`__
https://archive.mozilla.org/pub/firefox/nightly/2012/04/2012-04-22-03-06-38-mozilla-central/
Built from http://hg.mozilla.org/mozilla-central/rev/990f6542747b

__Pushlog:__ https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=7fda4d02d3ca&tochange=990f6542747b

__Changeset 92073:__ - Implement new identity block design (browser/base, browser/app, and Windows). r=dao:
https://hg.mozilla.org/mozilla-central/rev/479edc4c0af4

__Bug 742419:__ - Implement new identity block design (lighter weight with a generic icon):
https://bugzilla.mozilla.org/show_bug.cgi?id=742419

---

FYI

**Comment by wolfbeast** [comment]
It's already closed as wontfix. adding more details won't make a difference (and I was already aware when this was changed in Firefox -- and out code is not the same anyway).

**Comment by Lorienna** [comment]
This is for any potential contributor who might have expressed a desire to fix this sometime in the future, and thereby wanted to know a bit more.
