### ISSUE TITLE
Remove URLbar bindings for status bar code

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1219]
Since this code is causing all sorts of XBL binding issues, it should be removed. The whole premise of having status indicators in the address bar is from the short-lived pre-Firefox4 beta era. Our status bar code should focus on just what it is intended to handle: the status bar.

If anyone insists they need this corner case functionality, they should write an extension based on the removed code.

**Comment by wolfbeast** [comment]
Commits [d8c63e7] and [a222ebf] should take care of this change.
@Lootyhoof I'm not sure if this requires theme changes, but it should at least take care of needing the workaround for people on FF themes. Can you verify interop here?

**Comment by Lootyhoof** [comment]
Other than the rest of the incompatibilities with FF themes, this looks to be fine.

No theme changes should be required; it'll just mean that there's a bit of extra styling around that's not being used anymore.

LGTM!

**Comment by wolfbeast** [comment]
This has been baking on unstable for 3 weeks without reports, so assuming this is complete.
