### ISSUE TITLE
Allow chrome://../skin/ overrides for chrome://../skin/ in theme's chrome.manifest

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#122]
Currently skin packages (themes) cannot override content that is in chrome://../skin/. If such feature were implemented, this would **significantly** improve efficiency when producing themes, as developers would only need to provide a simple toolbar.png replacement in order to create a theme, as opposed to having to copy the entire interface style in order to make simple changes. Among other things, this also allows for platform-specific overrides of particular files (for example, use a browser.css for Windows, Linux, ...), where currently this requires setting up a new skin package to implement.

BMO: [1170207] (https://bugzilla.mozilla.org/show_bug.cgi?id=1170207).

**Comment by trav90** [comment]
Should be resolved by PR #123

**Comment by wolfbeast** [comment]
If you're interested, I can send you a beta version once built to test this functionality (as well as OS selection) since it's all been merged in now. Let me know if so!

**Comment by wolfbeast** [comment]
Verified by @Lootyhoof as working in practice. (25.6 b2)

**Comment by trav90** [comment]
Great!
