### ISSUE TITLE
Use accent color on Windows 10 titlebar more reliably

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#1222]
I've been tracking the related Mozilla bugs for these for a while, and it looks like they're done, so time to put a fork in them.

To work around issues in Windows 10, we've tried multiple methods: the original Mozilla approach (draw everything ourselves but use a light grey window background permanently), as well as attempting to emulate the Windows Vista/7/8 method (let the system render the background and overlay our caption buttons). The former was met with criticism because Windows 10 started to allow people to use accent color in titlebars, while the latter is inconsistent in unusual DPIs and with non-standard system themes.

The new Mozilla approach, though, is to add a few new CSS selectors and media queries. In particular:
`-moz-win-accentcolor` (e.g. `background-color: -moz-win-accentcolor`) to get the system accent color.
`-moz-win-accentcolortext` (e.g. `color: -moz-win-accentcolortext`) to get the text styling associated with this - this could also help with our browser title code...
`-moz-windows-accent-color-applies` (e.g. `@media (-moz-windows-accent-color-applies)`) for when the user has set the accent color to the titlebar (by default Windows 10 just leaves it pure white).

This way, the approach is very much the same as their previous approach, except now with more color involved.

The patches for this are listed in BMO [1344910](https://bugzilla.mozilla.org/show_bug.cgi?id=1344910) and [1344917](https://bugzilla.mozilla.org/show_bug.cgi?id=1344917), with the theme changes in [1196266](https://bugzilla.mozilla.org/show_bug.cgi?id=1196266) (I will take this one, though the former two patches will need completing first).

Please add the labels `Theme/UI`, `CSS` (new label?) and `UXP-task` (or would you prefer this be raised over there instead?).

**Comment by wolfbeast** [comment]
Jeez, annoying, both dependent bug have exactly the same push date and time.
I'll figure out which one was applied first.

**Comment by Lootyhoof** [comment]
Not from what I've seen? According to [the commit](https://hg.mozilla.org/mozilla-central/rev/d07b25fd6533) it looks like 1344917 was pushed first, on 2017-06-08 (though it seems the tests were applied earlier, [here](https://hg.mozilla.org/mozilla-central/rev/d7dca95a5bc8)).

1344910 was applied on 2017-06-29 [here](https://hg.mozilla.org/mozilla-central/rev/963efb32d822) then [here](https://hg.mozilla.org/mozilla-central/rev/a4d028c197ef) (and requires the other bug done first, since it seems Moz themselves noticed build failure otherwise).

**Comment by wolfbeast** [comment]
No, you're wrong. Both hg commits have the same date and time, and in fact, 1344910 defines a function getAccentColor() that 1344917 needs. So if it was pushed the way you say, it wouldn't build.

**Comment by wolfbeast** [comment]
And there's another issue, since `nsIWindowsUIUtils` doesn't exist.

**Comment by wolfbeast** [comment]
I think I have what's needed ported now. No real way to quickly test it but it was relatively straighforward, since the interface mentioned was only in use for "tablet mode" which isn't applicable here for us.

**Comment by Lootyhoof** [comment]
Thanks, I'll give it a go when the next unstable is out and let you know how things are.

On the theme front, I can see that Mozilla works around the Windows 10 white titlebar default by using a sane default value instead of the Windows 10 default - this looks to be `hsl(235,33%,19%)` for active windows and `-moz-dialog` for inactive windows as per below screenshots of Nightly with CTR enabled:

![Nightly](http://i.imgur.com/DmgKU5Z.png) ![Nightly Inactive](http://i.imgur.com/QobaFKt.png)

What do you think for the design of this? We could keep it as-is, though I was thinking possibly of something a bit more blue - `hsl(239,67%,38%)` perhaps:

![Nightly Blue](http://i.imgur.com/ZB7EvJf.png)

As for the inactive window design, I was thinking of maybe using the style we'd used in our initial Windows 10 implementation - `hsl(0, 0%, 90%)`:

![Nightly Inactive Grey](http://i.imgur.com/bqsFUsK.png)

Let me know what you think and I'll try to work something out.

**Comment by wolfbeast** [comment]
Silver-grey for inactive is always good in my book. As for the blue... not too happy about that; probably want something less saturated.

**Comment by Lootyhoof** [comment]
Understood. I've taken that value and just reduced the saturation of it to produce `hsl(239,33%,38%)`, though I've also tried `hsl(240,47%,25%)` and `hsl(240, 47%, 60%)` and look reasonable enough (though maybe too extreme in dark/light respectively):

![1](http://i.imgur.com/gpaaHi0.png) ![2](http://i.imgur.com/L5fQiVZ.png) ![3](http://i.imgur.com/6zhpnw8.png)

**Comment by wolfbeast** [comment]
Yeah, `hsl(239,33%,38%)` looks good to me. I'm uploading a new unstable right now that has the (untested) parameters and query in it. Let me know if it works.

**Comment by Lootyhoof** [comment]
Confirmed, it works! 👏

I made a slight typo in the initial comment, though: the media query is `-moz-windows-accent-color-applies`, not `-moz-win-accent-color-applies`; I've updated it so we're clear.

I'll send a PR with the patch soon.

**Comment by Lootyhoof** [comment]
Another patch has just been made on the Mozilla side that will be useful for us (also in relation to [your comment](https://github.com/MoonchildProductions/Pale-Moon/pull/1229#issuecomment-314615802)):

BMO [1379269](https://bugzilla.mozilla.org/show_bug.cgi?id=1379269); Toggling "Show accent color on title bar" in Windows settings is not picked up until restart

**Comment by wolfbeast** [comment]
I'm ported that bug across in 41cfa9a53a1ce7a645679f1c2442698dbafefd57

**Comment by wolfbeast** [comment]
OK, I've experimented a little with different things on Windows 10. Initially I couldn't get the accent color text to change _at all_, but I realized it's because of the darkwindowframe property. If that's set, then darkwindowframe rules get priority, and that code doesn't work with dynamic changes in Windows 10.

Disabling that code on Win10 to test, the titlebar text now changes properly, but the caption controls do not -- I'm guessing it's because of caching of the SVG files, so my idea to use -moz-win-accentcolor for stroke in internal CSS is likely not going to work.

Unless you have a better idea how to use separate SVG files (white/black) depending on the value of -moz-win-accentcolortext, we might be forced to use BMO [1058040](https://bugzilla.mozilla.org/show_bug.cgi?id=1058040)

**Comment by Lootyhoof** [comment]
At the moment no `darkwindowframe` property is used at all on any text or caption buttons on Windows 10 - it's only used for the hover background of the caption buttons. The dark/light style changes when the browser is closed and opened again, which is the same as previously.

To get the caption buttons to react to changes like that though (as the titlebar text now does)...is a whole other problem. Looking into it it would seem the only other way is to embed the SVG itself - though I'd really prefer that NOT happen.

It looks like that BMO will be our best option here, unfortunately.

**Comment by wolfbeast** [comment]
I looked at the BMO bug and that's a big mess even from the most basic implementation approach.
I'll think about alternatives some more.

**Comment by wolfbeast** [comment]
Can you tell me what you were thinking about when talking about embedding the SVG itself? I'm still exploring other options but it doesn't look promising, and the mentioned BMO bug doesn't seem at all compatible with Goanna 3.

**Comment by wolfbeast** [comment]
I think I have a solution. it's a little more expensive on the drawing side but it can be restricted to Windows 10 only. New `@media (-moz-windows-accent-color-is-dark)` media query to use, and to make it live I can (on Win10 only) will trigger a re-check of the media parameters (and refresh the theme) to make sure the media parameters are re-filled and re-evaluated. Refreshing the theme is expensive, but it's the only other way around it. I'll have a commit to this effect soon.

**Comment by Lootyhoof** [comment]
With regards to embedding the SVG I was thinking of something like [this](https://codepen.io/yoksel/pen/xiLen), though I'm not sure how viable that is in an XUL context.

I do like the idea of that media query though - once it's through I'll test it out.

**Comment by wolfbeast** [comment]
Hmm.. Well, if:
```
  fill: currentColor;
  filter: url(#shadow);
  stroke: rgba(255,255,255,0);
```
just works, then I really don't understand why this BMO bug is even needed? Because you could just set fill and stroke in CSS then... Am I missing something?

**Comment by Lootyhoof** [comment]
The implementation is one I found, rather than one I crafted. In our case we can't use `fill`, but we can use `stroke`. We can only use these when the SVGs are embedded though, rather than linked externally (at least where HTML is concerned). It's really not an elegant solution in our case unless you want to bloat `browser.xul`, though, and I'm not sure if the caching on the SVG will still take effect (though hopefully with it being embedded it shouldn't).

**Comment by wolfbeast** [comment]
Considering caption buttons are system controls, there's no real reason why we shouldn't be able to embed them. It's not something that is supposed to be theme-able, which would be the only concern in that case.
It's certainly an option to explore, and actually a pretty decent and elegant enough solution, that's likely cheaper on the paint side. We'll have to see what the impact is in actual use.

Of note, we already have some SVG paths in `browser.xul` (clip paths for forward button keyholes) so it's not anything new ;)

I've merged the work I've put in, I'll make a new unstable build and publish it.

**Comment by Lootyhoof** [comment]
Initial tests of this are looking good. I'll give it some time before making a proper conclusion but I think we might have a winner here.

**Comment by wolfbeast** [comment]
Is there still something else needed for this?

**Comment by Lootyhoof** [comment]
Don't think so. I've not noticed any issues personally.

**Comment by wolfbeast** [comment]
Okay!
