### ISSUE TITLE
Implement ES6 class support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1243]
ES6 classes are mostly sugar to cater to web developers who somehow can't understand basic prototype use and want everything to be C++. Widely-used libraries are using this sugar (looking at you, React!) without checking or using shims for anything, so we need at least a basic interpreted version of classes to keep sites from borking and having the whole dance again "we only support the big 3 current and current-1" nonsense because outsourcing and re-using libs maintained by people obsessed with shinies instead of accessibility.

**Comment by THEtomaso** [comment]
Will this finally fix the menu issues at Asus' ROG forum, Philips' product site, and other places that uses that kind of sloppy (but allowed) form of coding?:
https://github.com/MoonchildProductions/Pale-Moon/issues/892/
..or is that a different beast entirely?

**Comment by wolfbeast** [comment]
No, ES6 classes has nothing to do with block-scoped functions.

**Comment by wolfbeast** [comment]
Since I'll be focusing on Basilisk for a while, opening this back up. The ground work so far is in https://github.com/MoonchildProductions/Pale-Moon/tree/ES-work -- which will still need at least BMO bugs 1141862, 1141863 and 1105463 (in that order) ported to come to something halfway usable.

**Comment by wolfbeast** [comment]
Tagging this as bounty material. Whomever wants to implement the rest of this syntactic sugar can claim a bounty on it.

**Comment by wolfbeast** [comment]
Disappointed nobody bothered with this. I'll be giving this a shot myself, see how far I get.

**Comment by wolfbeast** [comment]
Ugh. The more I see about Classes and get to understand how it all hooks together, the more I think it is terribly broken and should really be avoided. Potential impacts of using this (especially with `super`) is that you are creating a dependency hell inside your JS constructs. JS was never designed to do this kind of thing by its very nature. It's not C++ and won't work like C++ no matter how hard you try.

But it's in the standard now so.. I'll have to work around it best I can.

**Comment by wolfbeast** [comment]
Dependency hell here.

Class depends on ES6 [Super](https://bugzilla.mozilla.org/show_bug.cgi?id=1141862), Super for class use depends on [SuperCall](https://bugzilla.mozilla.org/show_bug.cgi?id=1141863), which depends on having ES6's [new.target](https://bugzilla.mozilla.org/show_bug.cgi?id=1141865) implemented.
Each of these are large, multi-part implementations spread out over about 8 Firefox dev cycles (because this apparently can never be done in one go even though they are closely related).

Not sure at this point if it's worth the time, also considering the debatable nature of ES6 Classes.

**Comment by wolfbeast** [comment]
Clearing assignment. If anyone else wants to take over this estafette marathon, feel free. Start with new.target, then supercall, then finishing classes.

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
