### ISSUE TITLE
Investigate and solve compiler warnings

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1244]
There's a whole bunch of compiler warnings emitted in Spidermonkey. These indicate potential coding problems (e.g. comparing bool with int, using unary minus on unsigned variables, etc.) and should be analyzed and fixed.

**Comment by janekptacijarabaci** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=187528

**Comment by wolfbeast** [comment]
Since this has become a meta for general build warnings, making this less specific.
