### ISSUE TITLE
facebook events not viewable

### ISSUE THREAD

**Issue by kutykurutty** [MoonchildProductions/Pale-Moon#1261]
Hi! I am not sure if it's user related  or everyone is affected by this bug, but I can't see the Events of any Facebook site.

Palemoon 27.4.0 x64 Portable (on Win 7), no addons
![ge](https://user-images.githubusercontent.com/30394410/28503370-9742ee10-7005-11e7-8418-d27abcef4165.PNG)

**Comment by wolfbeast** [comment]
No indication of anything in the console. No errors or warnings.
So, from a browser perspective, it looks like there simply are no events to display.
```
GET 
https://www.facebook.com/gunsnroses/events/ [HTTP/2.0 200 OK 243ms]
POST 
XHR 
https://www.facebook.com/ajax/bz [HTTP/2.0 200 OK 75ms]
GET 
https://www.facebook.com/rsrc.php/v3iaFh4/yH/l/en_US/98LC11JqsUc.js [HTTP/2.0 200 OK 13ms]
GET 
https://www.facebook.com/rsrc.php/v3iNSE4/yF/l/en_US/V0-nsXyhrXA.js [HTTP/2.0 200 OK 13ms]
GET 
https://www.facebook.com/rsrc.php/v3i6Md4/yE/l/en_US/OvdRYhoYEOl.js [HTTP/2.0 200 OK 12ms]
GET 
https://www.facebook.com/rsrc.php/v3iq1N4/y_/l/en_US/hJShTh91nxN.js [HTTP/2.0 200 OK 13ms]
GET 
https://www.facebook.com/rsrc.php/v3i1Bc4/y7/l/en_US/0wS3oMF2Eq0.js [HTTP/2.0 200 OK 12ms]
GET 
https://www.facebook.com/rsrc.php/v3ipjF4/yF/l/en_US/VMzIjw46yNC.js [HTTP/2.0 200 OK 11ms]
POST 
XHR 
https://www.facebook.com/api/graphqlbatch/ [HTTP/2.0 200 OK 317ms]
```

**Comment by janekptacijarabaci** [comment]
See also https://forum.palemoon.org/viewtopic.php?f=29&t=15897

For me - Pale Moon throws an error in Browser Console:
```
Error: Minified exception occurred; use the non-minified dev environment
for the full error message and additional helpful warnings.
n_b70lDE5Nf.js:53:142
```

```
__d('invariant', [
'ex',
'sprintf'
], (function a(b, c, d, e, f, g) {
'use strict';
var h = c('ex');
function i(j, k) {
  if (!j) {
    var l = void 0;
    if (k === undefined) {
      l = new Error('Minified exception occurred; use the non-minified dev environment ' + 'for the full error message and additional helpful warnings.');
    }
```
---

__Last bad: Firefox 52.0a1 (2016-10-29)__
Built from https://hg.mozilla.org/mozilla-central/rev/1561c917ee27c3ea04bd69467e5b8c7c08102f2a

__First good: Firefox 52.0a1 (2016-10-29)__
Built from https://hg.mozilla.org/mozilla-central/rev/1b170b39ed6bdbde366233ab84594bdaaa960a5a

__Pushlog__
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1561c917ee27c3ea04bd69467e5b8c7c08102f2a&tochange=1b170b39ed6bdbde366233ab84594bdaaa960a5a

---

See also:
https://facebook.github.io/react/blog/2016/07/11/introducing-reacts-error-code-system.html
...but on beta.facebook.com: the message is still the same.
Possible contacts:
https://github.com/facebook/react/
https://www.facebook.com/groups/reactfiberbeta/

MSIE 11 also does not work.

**Comment by kutykurutty** [comment]
latest Chrome, FF shows the Events like this:

![image](https://user-images.githubusercontent.com/30394410/28522071-dc055292-7076-11e7-905f-5004d3395a16.png)

**Comment by wolfbeast** [comment]
Fixed in v27.6.0

**Comment by janekptacijarabaci** [comment]
> Pretty sure this was a vendor-locked feature that got solved with the useragent update.

IMHO/AFAIK - It was solved due to MSIE 11:
https://forum.palemoon.org/viewtopic.php?f=29&t=15897#p122050
(works on an older version of PM)

**Comment by wolfbeast** [comment]
We're not MSIE and I know for a fact that Facebook spits out completely different code for it. So I don't see how that would have been a fix applying to our Firefox UA?

**Comment by wolfbeast** [comment]
So, nobody bothered to update this issue with info then.
Either way. solved. case closed.
