### ISSUE TITLE
JS - DOM - implement node.isSameNode()

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1262]
https://dom.spec.whatwg.org/#dom-node-issamenode

> The isSameNode(otherNode) method, when invoked, must return true if otherNode is context object, and false otherwise.

You add the label `Standards Compliance` / `Web Compatibility` (?), please.

**Comment by wolfbeast** [comment]
Current unstable has this implemented.

**Comment by wolfbeast** [comment]
@janekptacijarabaci a tip, if you make a commit that resolves a specific issue, you can add, to the commit message:

`This resolves #number.` e.g. `This resolves #1262.` and Github will automatically pick it up and refer to the PR and merged commit, and close the issue, when merged.

**Comment by janekptacijarabaci** [comment]
OK, thank you.
