### ISSUE TITLE
[suggestion] DOM - CSSOM View Module (draft) - implement scrollingElement

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1266]
DOM - CSSOM View Module - implement scrollingElement (`W3C Working Draft`):

https://drafts.csswg.org/cssom-view/#dom-document-scrollingelement

> The scrollingElement attribute, on getting, must run these steps:
    - 1. If the Document is in quirks mode, follow these substeps:
      -- 1. If the HTML body element exists, and it is not potentially scrollable, return the HTML body element and abort these steps.
      -- 2. Return null and abort these steps.
    - 2. If there is a root element, return the root element and abort these steps.
    - 3. Return null.

> Note: For non-conforming user agents that always use the quirks mode behavior for scrollTop and scrollLeft, the scrollingElement attribute is expected to also always return the HTML body element (or null if it does not exist). This API exists so that Web developers can use it to get the right element to use for scrolling APIs, without making assumptions about a particular user agent’s behavior or having to invoke a scroll to see which element scrolls the viewport.

> Note: The HTML body element is different from HTML’s document.body in that the latter can return a frameset element.

---

You add the label `Web Compatibility`, please.

**Comment by wolfbeast** [comment]
Current unstable has this implemented.
