### ISSUE TITLE
crash while browsing

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [MoonchildProductions/Pale-Moon#1273]
while browsing: palemoon crashes, often.
see e.g. trace,... [here](https://gist.github.com/Erkan-Yilmaz/aa425b675c54b27ce4da43646cdcfd13)

<br>

on request further info available
* e.g. I have a 1 GB large core dump (unzipped), but would rather avoid uploading even a zipped file
* it happens with different websites: e.g. if you need to I could run a specific version with symbols included?
<br>

version: 27.4.0 (32-bit), linux, [binary download](https://linux.palemoon.org/download/mainline/) from website

**Comment by wolfbeast** [comment]
@trav90 maybe you can help getting a usable trace here -- the Gist doesn't have any useful information in it.

**Comment by wolfbeast** [comment]
@Erkan-Yilmaz can you at least provide details about your operating environment? O.S., architecture, version of kernel, system libs, X, GTK, desktop environment, and if there is anything specific you do before the crash occurs?

**Comment by trav90** [comment]
@Erkan-Yilmaz I have symbols on my machine and should be able to get a usable trace if you can provide a specific URL/exact steps to reproduce.

**Comment by Erkan-Yilmaz** [comment]
* I can't yet pinpoint it, but it happens a lot in the binary version
* I compiled the 27.4.0 source version also, as suggested on irc, but unfortunately there seem no symbols available ("Reading symbols from ./pmbuild/dist/palemoon/palemoon...(no debugging symbols found)...done.")
* I am available on your irc channel for further steps

**Comment by wolfbeast** [comment]
Per IRC, closed as incomplete for not getting necessary info/STR.
