### ISSUE TITLE
JS - DOM - implement document.onvisibilitychange

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1276]
https://w3c.github.io/page-visibility/#extensions-to-the-document-interface

> The Page Visibility API defines a means to programmatically determine the visibility state of a top level browsing context, and to be notified if the visibility state changes. Without knowing the visibility state of a page, web developers have been designing web pages as if they are always visible. This not only results in higher machine resource utilization, but it prevents web developers from making runtime decisions based on whether the web page is visible to the user. Designing web pages with knowledge of the page's visibility state can result in improved user experiences and power efficient sites. 

> With this API, web applications can choose to alter their behavior based on whether they are visible to the user or not. For example, this API can be used to scale back work when the page is no longer visible. 

---

You add the label `Web Compatibility` and `UXP-task`, please.

**Comment by wolfbeast** [comment]
I see a problem with this, namely in the realm of abuse and privacy.
For example: state changes from visible to not visible, and the content script can either force visibility again, or perform undesired tasks "when the user isn't looking". In addition it opens up for more tracking/metrics and other privacy issues. I think the potential advantages for legit applications (you do know that we already scale back JS processing for background tabs, right?) do not outweigh the potential risk of passing this user state to the page content.

**Comment by wolfbeast** [comment]
By the way, your URL comes up blank. I can't even read what this is all supposed to be advantageous for, anyway.

**Comment by janekptacijarabaci** [comment]
OK, events... Some of these things are abusive. But you can create a new setting (default off).
But also this is just a suggestion.

**Comment by janekptacijarabaci** [comment]
> Your URL comes up blank
Because:
`TypeError: Object.entries is not a function`

You can try to turn off Javascript temporarily.

**Comment by wolfbeast** [comment]
Since we already have VisibilityState, abusive scripts can already abuse it anyway, so it's just a convenience function.
