### ISSUE TITLE
History configuration bug

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1282]
I've always configured Pale Moon's history settings in a certain way, and I just noticed a problem..

Steps to reproduce (under 'Tools' > 'Options' > 'Privacy' > 'History'):

1) Select "Use custom settings for history", and configure like this:
https://www.mediafire.com/convkey/f9b7/nqtcoql33bdaga16g.jpg
https://www.mediafire.com/convkey/96cb/ybepdzsyjpivt2p6g.jpg

2) Press OK and restart Pale Moon.

3) Select "Remember History" and press OK.

4) Now, open your history settings again..
Pale Moon has now enforced this configuration:
https://www.mediafire.com/convkey/6997/vdkgrp9jm1kdugv6g.jpg

--

(Pale Moon v27.4.1,x64 / Win8.1Pro)

**Comment by wolfbeast** [comment]
There is no issue. if you select "remember history" then your history settings will be configured as in your latest screenshot. You can have custom settings or predefined settings, not both at the same time.

**Comment by wolfbeast** [comment]
PS: if you want to include screenshots, please attach them to issues using GitHub, and don't host them externally. That way we can be sure the context of the issue remains preserved regardless of availability of image hosting services in the future.

**Comment by THEtomaso** [comment]
To me, logic dictates that by selecting "Remember History", all custom settings will be overridden.
The history settings should reflect this by displaying the "Remember History" alternative.
But you're telling me that once the user has told PM to "Use custom settings for history", there's no way of making it display the "Remember History" alternative again?
This is confusing behaviour, IMO.

--

*Picture instructions noted*

**Comment by wolfbeast** [comment]
No, there's something wrong there. you're correct. "Remember browsing and downloads history" should be checked in your third screenshot, and it isn't.
`places.history.enabled` does not get reset when choosing "remember history" -- not sure where this regressed. Will have to look into it.

**Comment by wolfbeast** [comment]
OK, so, for some reason the code to set this is different for the places history; it tries to set the checkbox control directly. Should be simple enough to fix by setting the pref, instead, like the others.

**Comment by THEtomaso** [comment]
But you still consider the issue about never being able to return to the default "Remember History" alternative to be correct behaviour?

**Comment by wolfbeast** [comment]
That's just a symptom.
