### ISSUE TITLE
Can't unselect "Load this bookmark in the sidebar"

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#1283]
Noticed a curious bug recently which impacts how users can interact with bookmarks..

1. Right click on a bookmark (either on the bookmarks toolbar or elsewhere) and click Properties
2. Select "Load this bookmark in the sidebar" and click Save
3. Again, right click bookmark and click properties
4. Attempt to _uncheck_ "Load this bookmark in the sidebar"

Doing this you would expect to be able to uncheck this option and click Save, where you can then load bookmarks via the main page again. However, it's actually not possible, meaning affected bookmarks must always be loaded in the sidebar (unless the user removes and re-adds the bookmark).

There doesn't appear to be any error in the browser console while doing this, as far as I can see.

This occurs on both latest stable (27.4.1) and unstable (27.5.0), tested on Windows 10.

**Comment by wolfbeast** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=912855
