### ISSUE TITLE
Actively scrolling boxes

### ISSUE THREAD

**Issue by hook54321a** [MoonchildProductions/Pale-Moon#1285]
The boxes on http://dashboard.at.ninjawedding.org/ are supposed to stop scrolling when they are hovered over, but on Pale Moon you usually have to interact with the boxes first before it will stop while you hover over them. I've had this issue on all platforms that I am able to test it on, Manjaro and Windows 10.

**Comment by janekptacijarabaci** [comment]
It works for me (PM 27.4.1 / 27.5.0a1 unstable).

**Comment by hook54321a** [comment]
oh shoot. I'll update to to 27.4.1 and report back real quick.

**Comment by hook54321a** [comment]
Seems to work now, at least on Windows 10. Can't test on Manjaro right now but it most likely works there too now.

**Comment by trav90** [comment]
Works for me using 27.4.1 on my Manjaro box.

**Comment by hook54321a** [comment]
Had the issue again, but after I restarted PM it started working again. I'm going to try to narrow down when it doesn't work as intended.
