### ISSUE TITLE
Make 'Open All in Tabs' work for livemarks again

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1287]
Once upon a time, there was an "Open All in Tabs" menu item that had been sitting at the bottom of a feed list:

<img src="https://user-images.githubusercontent.com/26753987/29251998-13775512-8068-11e7-9ff1-838a7a925e51.png" width="395.2" height="186.4" alt="old feed list">

The same item was active in a livemark's context menu, and it was possible to middle-click a livemark to open all feeds in tabs as well:

<img src="https://user-images.githubusercontent.com/26753987/29252009-2e640424-8068-11e7-9d2a-78603f315d69.png" width="218.4" height="254.4" alt="old context menu">

This livemarks' functionality was available until FF 13, when it suddenly disappeared - probably due to a regression.

Last good: [`13.0a1 (2012-02-24)`](https://hg.mozilla.org/mozilla-central/rev/2b1a53905350) [`files`](https://archive.mozilla.org/pub/firefox/nightly/2012/02/2012-02-24-16-34-27-mozilla-central/) → First bad: [`13.0a1 (2012-02-25)`](https://hg.mozilla.org/mozilla-central/rev/ce20e9b47e9c) [`files`](https://archive.mozilla.org/pub/firefox/nightly/2012/02/2012-02-25-03-17-23-mozilla-central/) → [Pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=2b1a53905350&tochange=ce20e9b47e9c)

[Changeset 87645](https://hg.mozilla.org/mozilla-central/rev/4edcd7c29408): (Interfaces) - Load-on-demand livemarks.
[Changeset 87646](https://hg.mozilla.org/mozilla-central/rev/f45eebebc41b): (Backend) - Load-on-demand livemarks.
[Changeset 87647](https://hg.mozilla.org/mozilla-central/rev/08a7bb3f5c92): (Frontend) - Load-on-demand livemarks.
[Changeset 87649](https://hg.mozilla.org/mozilla-central/rev/4814a8d64b8d): (Tests) - Load-on-demand livemarks.
[Changeset 87650](https://hg.mozilla.org/mozilla-central/rev/7925703fbce6): (Sync) - Load-on-demand livemarks.

[Bug 613588](https://bugzilla.mozilla.org/show_bug.cgi?id=613588): (livemarksIO) - Replace livemarks with asynchronous load-on-demand livemarks (was: Livemarks cause synchronous I/O during txul).

---

Eventually the menu item was restored, but only to the feed list:

<img src="https://user-images.githubusercontent.com/26753987/29252011-40bf606e-8068-11e7-98b3-d2514cbe0421.png" width="395.2" height="194.4" alt="new feed list">

FF 41 Aurora range:

* Last bad: [`41.0a2 (2015-07-09)`](https://hg.mozilla.org/releases/mozilla-aurora/rev/13a122fedbc3) [`files`](https://archive.mozilla.org/pub/firefox/nightly/2015/07/2015-07-09-00-40-07-mozilla-aurora/) → First good: [`41.0a2 (2015-07-10)`](https://hg.mozilla.org/releases/mozilla-aurora/rev/7b18c0ff979a) [`files`](https://archive.mozilla.org/pub/firefox/nightly/2015/07/2015-07-10-00-40-07-mozilla-aurora/) → [Pushlog](https://hg.mozilla.org/releases/mozilla-aurora/pushloghtml?fromchange=13a122fedbc3&tochange=7b18c0ff979a)
* [Changeset 270190](https://hg.mozilla.org/releases/mozilla-aurora/rev/2cbf9115f558): Make 'open all in tabs' work for livemarks. r=mak, a=ritu

FF 42 Nightly range:

* Last bad: [`42.0a1 (2015-07-02)`](https://hg.mozilla.org/mozilla-central/rev/f5e3bacfb60e) [`files`](https://archive.mozilla.org/pub/firefox/nightly/2015/07/2015-07-02-03-02-07-mozilla-central/) → First good: [`42.0a1 (2015-07-03)`](https://hg.mozilla.org/mozilla-central/rev/8445e75f3116) [`files`](https://archive.mozilla.org/pub/firefox/nightly/2015/07/2015-07-03-03-02-16-mozilla-central/) → [Pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=f5e3bacfb60e&tochange=8445e75f3116)
* [Changeset 251189](https://hg.mozilla.org/mozilla-central/rev/663108a1d580): Make 'open all in tabs' work for livemarks. r=mak

[Bug 730829](https://bugzilla.mozilla.org/show_bug.cgi?id=730829): Restore "Open all in tabs" to the bottom of livemarks popups (was: "Open all in tabs" missing after [bug 613588](https://bugzilla.mozilla.org/show_bug.cgi?id=613588)).

**Comment by wolfbeast** [comment]
Considering this closed, assuming it's been verified during implementation.
