### ISSUE TITLE
Update Brotli to more recent upstream

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1290]
We need to update the Brotli compression lib to 0.6 to be able to pull woff2 updates from upstream.

**Comment by Gpower2** [comment]
I'm happy to give it a go, since I got familiar with the relevant code.
Indeed updating to brotli v0.6 will require changes to WOFF2 too.

**Comment by wolfbeast** [comment]
This may also be needed to fix up the issues in #921

**Comment by wolfbeast** [comment]
0.6 has some restructuring done. I'm just going to update it to the same level we have in UXP since that definitely seems to be working for accept-encoding `br`. It's still a 0.4 variant, but the brotli development seems to be a bit of a mess.

**Comment by Gpower2** [comment]
I can't believe it was done with so little changes in the build files! I was desperately trying to update to v0.6 but I never managed to make it build. Seeing the required changes makes me want to bang my head on the wall...
Nice job once again!

**Comment by wolfbeast** [comment]
For 0.6, you likely need to grab the /common directory as well and adjust the mozbuild manifest accordingly, but I didn't really have the reserve right now to do do too much build system mangling.
They very recently did release a version 1.0 of Brotli (which has no further C API changes compared to 0.6; they pretty much decided that is going to be the way it's used), so we might in the future want to try and update to that, instead.
