### ISSUE TITLE
JS - DOM - implement Object.values / Object.entries

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1292]
https://tc39.github.io/ecma262/2017/#sec-object.values

> 19.1.2.21Object.values ( O )

> When the values function is called with argument O, the following steps are taken:
> Let obj be ? ToObject(O).
> Let nameList be ? EnumerableOwnProperties(obj, "value").
> Return CreateArrayFromList(nameList).

**Comment by JustOff** [comment]
Unfortunately the test failed: https://jsfiddle.net/3pq5pc9q/

**Comment by janekptacijarabaci** [comment]
See #1293 
PropertyDescriptor.enumerable/configurable is not implemented.

**Comment by wolfbeast** [comment]
So, we have a partial implementation then. It should still be OK to ship in 27.5 as-is, but this issue should remain open until the full spec is implemented.

**Comment by JustOff** [comment]
Something really weird is going here. The test running directly in jsfiddle gives me an error from this test:
```
o = { a: 3, b: 2 };
values = Object.values(o);
assertDeepEq(values, [3, 2]);
```

`Error: Assertion failed: got "false", expected "true at _[0].[[Configurable]]`


But when I run it in the scratchpad first chunk is passed and I get completely different error from: 
```
var o = {get a() {delete this.b; return 1}, b: 2, c: 3};
values = Object.values(o);
assertDeepEq(values, [1, 3]);
```
`Error: got own properties ["0", "1", "2", "length"], expected ["0", "1", "length"]`

**Comment by wolfbeast** [comment]
jsfiddle probably interferes.
Are you sure the test is correct?
If this is taken from the marionette/automated tests then you can't just apply it in most cases.

**Comment by JustOff** [comment]
> jsfiddle probably interferes.

It runs well in both Firefox & Chrome.

Unfortunately I'm not so familiar with marionette ...

**Comment by wolfbeast** [comment]
Firefox also converted this entire implementation to C++, so it's not the same code.

**Comment by JustOff** [comment]
I checked Firefox nightlies from the range between [1208464](https://bugzilla.mozilla.org/show_bug.cgi?id=1208464) and [1232639](https://bugzilla.mozilla.org/show_bug.cgi?id=1232639) (js->c++) and they are also pass the test on jsfiddle.

**Comment by janekptacijarabaci** [comment]
``` javascript
if ("values" in Object) {
  var o, values;
  o = { a: 3, b: 2 };
  values = Object.values(o);
  var na = Object.getOwnPropertyNames(values);
  alert(JSON.stringify(na));
}
```

Pale Moon:
`["length", "0", "1"]`

Firefox:
`["0", "1", "length"]`

See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1175111
https://bugzilla.mozilla.org/show_bug.cgi?id=1218111
https://bugzilla.mozilla.org/show_bug.cgi?id=1219363

**Comment by JustOff** [comment]
@janekptacijarabaci 
I think that this is not the case, because the [test on jsfiddle](https://jsfiddle.net/3pq5pc9q/) calls na.sort() + nb.sort() before comparison.

**Comment by janekptacijarabaci** [comment]
@JustOff 
You're right.

**Comment by JustOff** [comment]
Now the basic implementation using self-hosted js looks complete and the only thing we can do here is to improve it by replacing with a c++ version based on [bug 1232639](https://bugzilla.mozilla.org/show_bug.cgi?id=1232639).

**Comment by wolfbeast** [comment]
I honestly don't think converting this to C++ is necessary. It'll make it more difficult to maintain, and there won't be a functional improvement (only performance at the risk of causing crash bugs, and I don't see `Object.values()` or `Object.entries()` easily ending up on any sort of hot path for web applications). 

So, I'd prefer to keep it self-hosted.
