### ISSUE TITLE
[Feature Request] Add support for Gopher Protocol

### ISSUE THREAD

**Issue by hook54321a** [MoonchildProductions/Pale-Moon#1296]
Other than the advantages of having support for the protocol, I think that it could get more people to switch to Pale Moon.

**Comment by wolfbeast** [comment]
Hate to say it but gopher is really something from the distant past. There's no point in adding built-in support for it in the browser.

**Comment by hook54321a** [comment]
Drat, I kinda was expecting this sort of response though. I wish gopher had kept on going, the web would have had more consistency if it kept on going.

**Comment by hook54321a** [comment]
@wolfbeast Is there a palemoon version of Overbite? I can't seem to get the firefox version to work.

**Comment by wolfbeast** [comment]
v3.0 variants should work? if not, you may have to edit the install.rdf of 3.1 to add a Pale Moon targetApplication block.
