### ISSUE TITLE
Black display glitches

### ISSUE THREAD

**Issue by hook54321a** [MoonchildProductions/Pale-Moon#1297]
On dashboard.at.ninjawedding.org weird black display glitches happen sometimes. (See attached screenshot)
![palemoon](https://user-images.githubusercontent.com/7744057/29398007-c8e9b3a2-82d6-11e7-8466-14fab45aa0c1.PNG)

**Comment by wolfbeast** [comment]
Please add the details of help -> troubleshooting information.

**Comment by hook54321a** [comment]
Application Basics
Version 	27.4.1
Build ID 	20170801005511
Update Channel 	default
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:45.9) Gecko/20100101 Goanna/3.2 Firefox/45.9 PaleMoon/27.4.1
OS 	Windows_NT 10.0
Multiprocess Windows 	0/2 (default: false)

Extensions (all enabled):
Cookies Export/import, Decentraleyes, Export Cookies. HTTPS Everywhere, OverbiteFF, uBlock Origin

Graphics
Adapter Description	Intel(R) HD Graphics
Adapter Drivers	igdumd64 igd10umd64 igd10umd64 igdumd32 igd10umd32 igd10umd32
Adapter RAM	Unknown
Device ID	0x0102
Direct2D Enabled	true
DirectWrite Enabled	true (10.0.14393.1358)
Driver Date	5-19-2016
Driver Version	9.17.10.4459
GPU #2 Active	false
GPU Accelerated Windows	2/2 Direct3D 11 (OMTC)
Subsys ID	1495103c
Vendor ID	0x8086
WebGL Renderer	Google Inc. -- ANGLE (Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0)
windowLayerManagerRemote	true
AzureCanvasBackend	direct2d 1.1
AzureContentBackend	direct2d 1.1
AzureFallbackCanvasBackend	cairo
AzureSkiaAccelerated	0

**Comment by wolfbeast** [comment]
I had a look at that dashboard and it creates a lot of surfaces because of all the constantly-updated controls. I think you may simply be running into a driver issue here (there are no glitches on my ATI/AMD card) or running low on VRAM/having VRAM contested with too many objects.

I don't think there's anything actionable here.

**Comment by hook54321a** [comment]
That would likely make sense because it seems to happen more when there's more stuff happening on the dashboard. I'll see if it happens on other browsers tomorrow.

**Comment by wolfbeast** [comment]
It _may_ not happen on other browsers if they use a different rendering engine. One of the problems is that your GPU/driver doesn't report the total adapter RAM so the first indication that it has run out will be when it's already out of memory.

**Comment by hook54321a** [comment]
It appears to not happen in other browsers.
I'm not sure if this will provide any insight or not:
![info](https://user-images.githubusercontent.com/7744057/29492295-20130ed8-852c-11e7-8f89-695f4d334fd3.PNG)

**Comment by wolfbeast** [comment]
There's nothing here for us to do. It's a corner case with integrated graphics using shared memory. You're likely running out of GDI handles or directly allocatable VRAM. You can disable hardware acceleration in the browser to work around it, but that obviously has other drawbacks. Your choice/priority.

**Comment by hook54321a** [comment]
This might just be fluke, but I think I found another way to work around it. I changed HardwareInformation.MemorySize in the registry from 00 00 c0 83 to 00 00 c0 32.

**Comment by hook54321a** [comment]
Could this damage my hardware?

**Comment by wolfbeast** [comment]
Damage your hardware? Haha, no, I really don't think so.
Do let me know if it's a permanent fix so others might be informed.

**Comment by hook54321a** [comment]
I'm not exactly sure what the value means though, I was kinda hoping that it would make applications think that the GPU has less memory than it does and maybe make a little wiggle room for when it does run out of memory.
