### ISSUE TITLE
Portable installer should extract to a subdirectory by default

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/Pale-Moon#1299]
* User downloads a portable Pale Moon installer, e.g. `Palemoon-Portable-27.4.1.win64.exe` and saves it to `C:\PrettyDir`.
* He executes the installer and just click on "next, next, next", as most users do. Here there is only one step, "extract".
* The files were extracted to `C:\PrettyDir` and now it's all messed up.

To be more foolproof, I think the archive shouldn't contain the files in its root, but in a subdirectory. Probably some users would dislike the change, but I think the added safety would be a big plus.

**Comment by wolfbeast** [comment]
You extract the application to a folder of your choice. Making a new folder and dumping everything in a subfolder is not what the user indicates when they extract the application to a named folder.
If a user extracts to `C:\Pale Moon Portable`, the application should end up in `C:\Pale Moon Portable`, not `C:\Pale Moon Portable\Some Other Folder\`.

**Comment by vlakoff** [comment]
I suggested the subdirectory solution, because apparently the default extraction path can't be changed in the 7z SFX module (unless I missed it).

Otherwise, an indeed better solution would have been to change the default extract path to
`<current dir>\<installer name without ext>`

**Comment by wolfbeast** [comment]
No. Using the installer name as a folder name is even worse.
