### ISSUE TITLE
Middle-clicking to open/close tabs sometimes causes double events.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1304]
It looks like the change in #1175 caused unwanted behavior:
See: https://forum.palemoon.org/viewtopic.php?f=29&t=16437

I've also noticed an issue with occasional double-opening/double-closing tabs when using middle-mouse on a link/tab respectively. Gestures also seems to be afftected.

I've backed this out in ce61607af29f915948863e6ca1745323c3b96a19 (trunk) and 82a5c709e3c219d4600801a73c447b85bf5c6d87 (relbranch). This should be re-examined and a an updated version should be created. Potentially, our front-end needs additional patches for this to work right.

**Comment by janekptacijarabaci** [comment]
See also [bug 1374096](https://bugzilla.mozilla.org/show_bug.cgi?id=1374096) - comment 4 and higher.

I suggest adding the `UXP-task` label.

**Comment by JustOff** [comment]
I never use middle mouse click so I never experienced this problem, i.e. right click always works fine for me after auxclick was implemented. Probably this observation could be useful to investigate and resolve the issue.

**Comment by wolfbeast** [comment]
I'm re-applying the auxclick one -- this was not the reason for double tab open/close. The behavior is rather odd: on middle-clicking a link, if the click is long, it will always open 2 new tabs (similarly for closing).

**Comment by wolfbeast** [comment]
I'm guessing this is a slightly older bug from previous patches to changes to our event handling for tabs.

**Comment by wolfbeast** [comment]
Then again, maybe it is actually ancient... 
https://bugzilla.mozilla.org/show_bug.cgi?id=265036 seems to describe the issue I'm seeing perfectly.

**Comment by JustOff** [comment]
> The behavior is rather odd: on middle-clicking a link, if the click is long, it will always open 2 new tabs (similarly for closing).

Unfortunately I can't reproduce this issue too.

**Comment by wolfbeast** [comment]
I've found a few more bugs with similar behavior, unfortunately all of them closed as "invalid" or "worksforme".
We probably need one or more `preventDefault()` and/or `stopPropagation()` calls to prevent spurious recorded middle-clicks on links or tabs (perhaps a double-click event is erroneously recorded?)

**Comment by satrow** [comment]
Is the reproducibility of this not mouse switch dependent?

My MS Compact USB mouse uses the central scroll wheel for middle-click, which is actuated on release; press/hold doesn't trigger anything.

**Comment by wolfbeast** [comment]
actuate-on-release sounds odd, but if that's the case then it may be triggered on both down and up; that would be a mistake.

**Comment by wolfbeast** [comment]
Firefox-release displays the same behavior for me.
And.. in fact I'm seeing the same in Chrome... so it may not be a browser issue, but rather on the mouse end (maybe jitter in the button or an issue with scroll and click being triggered at the same time -- I guess a reason why I hate mousewheel clicking ;) )

**Comment by satrow** [comment]
I get no action on the downstroke or on hold, only on release, though a quick check using X-Mouse Button Control detects as 'on' on the downstroke, 'off' on release.

It feels like the logic behind it is: on click, wait for rotation input; if rotation then (switch to scroll mode) no click on release; if no rotation then (switch to middle-click mode) click on release. No repeat on hold is possible with this method (there's nothing to repeat).

http://www.highrez.co.uk/downloads/XMouseButtonControl.htm

Note: I've never installed the MS drivers, it's using only the native Windows 7 HID-class drivers.

**Comment by wolfbeast** [comment]
As far as i can gather this isn't a Pale Moon issue, at this point. Closing.
