### ISSUE TITLE
[Bug] Website rendering bug

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/Pale-Moon#1306]
Ubuntu Mate x64 17.04
PaleMoon 27.4.1
[Website]( https://www.abgeordnetenwatch.de/ueber-uns/spendenformular?recurring=1&pk_campaign=4000Foerderer&pk_kwd=Header)

I scroll down this page and during the middle of the page, the content on the right side is on the left side.
![bug](https://user-images.githubusercontent.com/4518092/29496587-c8812402-85d5-11e7-83a6-b222ed7aef16.png)

PS: I love your work!

**Comment by wolfbeast** [comment]
Unable to reproduce; the content you see on the left should remain on the right and "stick" when you scroll. I;ve tried several window widths in case that was the problem -- all looks OK to me.

**Comment by MartinX3** [comment]
This bug appears only on my 1280 x 1024 17" monitor.
My 1680 x 1050 20" monitor is fine, without this problem. :)

**Comment by wolfbeast** [comment]
As said I tried different window sizes. If I make it really small it switches to a mobile layout -- perhaps you're blocking the necessary scripting for their responsive design?

**Comment by MartinX3** [comment]
I deactivated every addon, but this error still remains. :)
Do you need additional informations, I need to provide? :)

**Comment by wolfbeast** [comment]
Did you also clear the cache after disabling the add-ons? Have you tried safe mode?

**Comment by MartinX3** [comment]
1. I cleared the cache and restarted the browser.
    1. Still remaining. :)

2. I tried safe-mode.
    1. Still remaining. :)

**Comment by wolfbeast** [comment]
Strange. Please post the output of Help -> troubleshooting information (copy as text)

**Comment by MartinX3** [comment]
> 
> Name | Pale Moon
> -- | --
> 27.4.1
> 20170805022314
> Mozilla/5.0 (X11; Linux x86_64; rv:45.9) Gecko/20100101 Goanna/3.2 Firefox/45.9 PaleMoon/27.4.1
> Linux 4.10.0-32-generic
> Open Directory
> about:plugins
> about:buildconfig
> about:memory
> 0/1 (default: false)
> false
> 
>

**Comment by wolfbeast** [comment]
Please use the "copy text to clipboard" button on that page... :P

**Comment by MartinX3** [comment]
I did :P 


Name | Pale Moon
-- | --
27.4.1
20170805022314
Mozilla/5.0 (X11; Linux x86_64; rv:45.9) Gecko/20100101 Goanna/3.2 Firefox/45.9 PaleMoon/27.4.1
Linux 4.10.0-32-generic
Open Directory
about:plugins
about:buildconfig
about:memory
0/1 (default: false)
false

**Comment by wolfbeast** [comment]
That's incorrect. That looks like you selected the text yourself and then copied it... :( There should be a lot more data, and not formatted in a table like that.... did you paste the correct clipboard? Since you're on Linux... -- also, which build is this? is this from a specific distro package, and if so, who maintains it?

**Comment by MartinX3** [comment]
Oh, that's sad :(

I pressed the button and pasted the text in this comment field :(

And use the repo builds from steven pusser.
The one, which builds did crashed months ago because of a wrong gcc. :(

**Comment by wolfbeast** [comment]
All right. If you don't mind, could you please do two things for me to narrow things down further:

- Please call up `about:buildconfig` and post the output here
- Please download our official "generic" binaries and see if the problem also occurs with those as well?

**Comment by MartinX3** [comment]
Okay, I will do it :D

> about:buildconfig
> Build Machine
> 
> cloud136
> Build platform
> target
> x86_64-pc-linux-gnu
> Build tools
> Compiler 	Version 	Compiler flags
> gcc-4.9 	4.9.4 	-Wall -Wdeclaration-after-statement -Wempty-body -Wpointer-to-int-cast -Wsign-compare -Wtype-limits -Wno-unused -Wcast-align -g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -fgnu89-inline -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -pipe
> g++-4.9 	4.9.4 	-Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wempty-body -Woverloaded-virtual -Wsign-compare -Wwrite-strings -Wno-invalid-offsetof -Wcast-align -g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -fno-exceptions -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe -DNDEBUG -DTRIMMED -g -O2 -msse2 -mfpmath=sse -fomit-frame-pointer -Wdate-time -D_FORTIFY_SOURCE=2
> Configure arguments
> 
> --enable-official-branding --enable-application=browser --enable-release --disable-installer --disable-updater '--enable-optimize=-O2 -msse2 -mfpmath=sse' --disable-debug --with-pthreads --enable-shared-js --enable-jemalloc --enable-strip --x-libraries=/usr/lib --prefix=/usr --enable-devtools --disable-necko-wifi
>

**Comment by MartinX3** [comment]
Same bug, while visiting this page in safe mode and your vanilla build [http://linux.palemoon.org/download/mainline/](http://linux.palemoon.org/download/mainline/) on my small monitor :(

**Comment by JustOff** [comment]
> I pressed the button and pasted the text in this comment field :(

@MartinX3, it seems you have confused "Copy raw data to clipboard" and "Copy text to clipboard" buttons.

**Comment by MartinX3** [comment]
@JustOff I found my mistake.
I need to paste the clipboard in my standard text editor first, befor copying it again and pasting it on this site.
But thanks trying to help. :)

**Comment by JustOff** [comment]
> This bug appears only on my 1280 x 1024 17" monitor.

I checked this site on my Ubuntu 14.04 and Mint 17 virtual boxes: it appears without any glitches.

**Comment by MartinX3** [comment]
> I checked this site on my Ubuntu 14.04 and Mint 17 virtual boxes: it appears without any glitches.

But how can it be, if i even tested it in the "safe mode" on my Ubuntu Mate 17.04? :(

**Comment by JustOff** [comment]
Oops, I'm sorry, my resolution in the test above was 1024x768. Now I can confirm the problem when setting it to 1280x1024. But I see the same mess in Firefox 55 at this resolution, so **it's probably just wrong site design**.

**Comment by MartinX3** [comment]
Thank you, I'm glad, that this isn't a bug in palemoon/firefox/my laptop, but on this site. :)

**Comment by wolfbeast** [comment]
It's a site design error. I've been able to reproduce it by very carefully adjusting the width of the window to a very specific value (around 1135-1140 px). There is a specific width where their design borks (probably because it's "in between" two defined widths in their design). Not anything we can fix browser-side.

**Comment by MartinX3** [comment]
Thank you for your help. :)
