### ISSUE TITLE
media.block-play-until-visible - bug?

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1314]
Don't know if this can be classified as a bug, but at least for me, it's an undesireable side effect.

Steps to reproduce:
1) In about:config, set 'media.block-play-until-visible' to "true".
2) Start playing some random video @ YouTube.
3) Switch to another tab while the video is still playing.
4) Wait until the video has ended, then switch back to its tab..

Consequence:
The video automatically starts to play from the beginning again.

Prefered behaviour, IMO:
The video should remain in a stopped state.

--

(Pale Moon v27.4.2,x64 / Windows 8.1 Pro)

**Comment by wolfbeast** [comment]
It's an unintentional side-effect when combined with autoplay/auto-replay scripting. There is no real way to work around that, as the option is meant to prevent first-play when not in view.
