### ISSUE TITLE
After toolbar customization, context menu items of bookmarks in bookmarks menu section are greyed

### ISSUE THREAD

**Issue by SilmorSenedlen** [MoonchildProductions/Pale-Moon#1315]
After update Pale Moon 27.4.1 to 27.4.2 I noticed that if I customize toolbar, then context menu items of bookmarks in bookmarks menu section are greyed. Also the Menu Bar should be activated to reproduce the problem.
Before toolbar customization:
![pm_before](https://user-images.githubusercontent.com/6761903/29751677-2c2d96d8-8b59-11e7-93bc-574ef5d7530e.png)
After toolbar customization:
![pm_after](https://user-images.githubusercontent.com/6761903/29751675-283ee324-8b59-11e7-9c6f-2cf5ccd165cd.png)
I tried to reset PM settings, as well as uninstall PM and delete all PM profile directories, but nothing helped. Also tested on portable version (x64) and under the same conditions on another computer with the same OS.
OS: Windows 7 Pro (x64)

**Comment by janekptacijarabaci** [comment]
Confirmed.

This is very old bug, see: https://bugzilla.mozilla.org/show_bug.cgi?id=625778
(AFAIK, I can not try it now)
