### ISSUE TITLE
error: ‘major’ was not declared in this scope

### ISSUE THREAD

**Issue by l29ah** [MoonchildProductions/Pale-Moon#1324]
f1e858a6bf2e07b47f9e397b72802c8b7a9c0ba8
```
14:07.31 /var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/xpcom/io/nsLocalFileUnix.cpp: In member function ‘virtual nsresult nsLocalFile::GetDiskSpaceAvailable(int64_t*)’:
14:07.31 /var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/xpcom/io/nsLocalFileUnix.cpp:1396:46: error: ‘major’ was not declared in this scope
14:07.31    if (!GetDeviceName(major(mCachedStat.st_dev),
14:07.31                                               ^
14:07.31 /var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/xpcom/io/nsLocalFileUnix.cpp:1397:46: error: ‘minor’ was not declared in this scope
14:07.32                       minor(mCachedStat.st_dev),
14:07.32                                               ^
14:07.42 In the directory  /var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/obj-x86_64-unknown-linux-gnu/xpcom/io
14:07.42 The following command failed to execute properly:
14:07.42 c++ -o nsLocalFileUnix.o -c -I../../dist/stl_wrappers -I../../dist/system_wrappers -include /var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/config/gcc_hidden.h -DOS_POSIX=1 -DOS_LINUX=1 -DSTATIC_EXPORTABLE_JS_API -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DMOZ_GLUE_IN_PROGRAM -DAB_CD=en-US -DNO_NSPR_10_SUPPORT -I/var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/xpcom/io -I. -I/var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/obj-x86_64-unknown-linux-gnu/ipc/ipdl/_ipdlheaders -I.. -I/var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/ipc/chromium/src -I/var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/ipc/glue -I../../dist/include -I/var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/obj-x86_64-unknown-linux-gnu/dist/include/nspr -I/var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/obj-x86_64-unknown-linux-gnu/dist/include/nss -fPIC -DMOZILLA_CLIENT -include ../../mozilla-config.h -MD -MP -MF .deps/nsLocalFileUnix.o.pp -Wall -Wempty-body -Woverloaded-virtual -Wsign-compare -Wwrite-strings -Wno-invalid-offsetof -Wcast-align -O2 -pipe -O2 -pipe -march=nehalem -fno-exceptions -fno-strict-aliasing -fno-rtti -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe -DNDEBUG -DTRIMMED -g -fno-omit-frame-pointer /var/tmp/paludis/www-client-palemoon-9999-r2/work/palemoon-9999/xpcom/io/nsLocalFileUnix.cpp
```

**Comment by wolfbeast** [comment]
Can't be related to the listed commit since that doesn't touch anything C++.

**Comment by wolfbeast** [comment]
Please indicate your O.S., build environment and paste your mozconfig or build script.

**Comment by Yamakuzure** [comment]
I have the same "problem", which isn't really one.

I was using gcc-6.4, now gcc-7.2, and there is just one include missing:
````
#include <sys/sysmacros.h>
````
must be added to nsLocalFileUnix.cpp, that file is no longer implicitly included via other system includes.

Adding that include does not hurt anybody, but makes the file compilable with gcc-6+

**Comment by wolfbeast** [comment]
Thanks, that's an easy fix. Can you point me to some documentation where this implicit inclusion was changed and why?

**Comment by Yamakuzure** [comment]
@wolfbeast Well, that is hard to find, but here are some sources:

  * [RedHat Bug 130601 - identifier major macro expanded into gnu_dev_major](https://bugzilla.redhat.com/show_bug.cgi?id=130601#c6) (Last comment)

> In some future release, glibc's  <sys/types.h> will not include <sys/sysmacros.h> anymore.  As of 2.25, it still does, but you get deprecation warnings if you use the macros without including <sys/sysmacros.h>.  We have not decided exactly which future release will finally remove the #include; to help us decide, please send reports of software that trips the deprecation warnings to libc-alpha.

> (We have just begun development of 2.25.  2.24, which will be released in a few days, does not change anything wrt this bug.)

I have glibc-2.25 installed, but did not get a deprecation warning. It was just removed.

  * [(glibc) NEWS for version 2.25](https://sourceware.org/ml/libc-alpha/2017-02/msg00079.html)

> * The inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated.
>   This means that in a future release, the macros “major”, “minor”, and
>   “makedev” will only be available from <sys/sysmacros.h>.
>
>   These macros are not part of POSIX nor XSI, and their names frequently
>   collide with user code; see for instance glibc bug 19239 and Red Hat
>   bug 130601.  <stdlib.h> includes <sys/types.h> under _GNU_SOURCE, and
>   C++ code presently cannot avoid being compiled under _GNU_SOURCE,
>   exacerbating the problem.

**Comment by wolfbeast** [comment]
Can you please verify that our tip of the master branch builds now?

**Comment by l29ah** [comment]
On Fri, Sep 08, 2017 at 03:12:23AM -0700, Moonchild wrote:
> Can you please verify that our tip of the master branch builds now?

Yes, it builds now, thank you.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
