### ISSUE TITLE
Improve button messages for removing cookies

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/Pale-Moon#1325]
Options > "Privacy" tab > "remove individual cookies" link

Here are the current Pale Moon messages:
* when there is no search filter:
Remove Cookie - Remove All Cookies
* when there is a search filter:
Remove Cookie[s] - Remove All Cookies

I found it confusing ("a search filter is applied, if I click "Remove All Cookies", will it remove only the shown cookies or all the cookies?")

Then I gave a run with Firefox, and noticed they are using much less ambiguous messages:
* when there is no search filter:
Remove Selected - Remove All
* when there is a search filter:
Remove Selected - Remove All Shown

I think these clearer messages should be ported to Pale Moon.

**Comment by vlakoff** [comment]
The change is slightly more complex than just changing strings.

Refs :
* https://bugzilla.mozilla.org/show_bug.cgi?id=1338036
* https://hg.mozilla.org/mozilla-central/rev/fc4ac23cf72b

**Comment by vlakoff** [comment]
There is also the subsequent https://bugzilla.mozilla.org/show_bug.cgi?id=1338757, for updating access keys.

**Comment by vlakoff** [comment]
Also, similar changes have been made to the "Saved Logins" dialog.

**Comment by wolfbeast** [comment]
I don't think anything beyond clarifying the strings is needed here.

**Comment by wolfbeast** [comment]
This should be trivial to implement in UXP.

**Comment by adeshkp** [comment]
UXP doesn't change a thing because it is all front-end code.

Coincidentally, I started working on this just yesterday but my pace is slow in these waters and it might take me a few days to complete this. If this is not required urgently, you can assign it to me.

**Comment by wolfbeast** [comment]
Front-end code still relies on back-end code being present. Why do you think it's a big task to port Pale Moon across to UXP? But in this case you may be right that it would be relatively independent.

I'll mark it assigned, there's no rush here.
