### ISSUE TITLE
Youtube starts playing when it should not

### ISSUE THREAD

**Issue by silver13** [MoonchildProductions/Pale-Moon#1328]
Hi, and great work on Palemoon.

I don't have a lot of info on this, and sorry if it's something already known

I have youtube videos paused in tabs from time to time, I have found sometimes they start playing when they should not.

Some instances when this happens:
When pressing play on another video, say, dailymotion, a youtube vid might start playing in it's tab
When closing a pale moon window sometimes I think
When I open a link from my mail program with pale moon

This issue happens very rarely , and I can't reproduce it by doing the same thing a second time. Sorry, I can't be more specific

**Comment by danykey** [comment]
It's reproduced for me also.
I am use Linux.
Paused videos starting play without my order.

**Comment by wolfbeast** [comment]
This is by design in YouTube's scripting. It's not under our control.
