### ISSUE TITLE
Help page for Security settings needs updating

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/Pale-Moon#1329]
In "Options > Security", I see added settings about HSTS and HPKP security protocols. I don't know what this is, so I click on the "Help" button.

It opens http://www.palemoon.org/support/prefs-security, but it doesn't even mention these settings.

Also note it mentions XSS settings, which have been removed in Pale Moon 27.

**Comment by wolfbeast** [comment]
Resolved.

Also, XSS settings clearly indicate that it applies to v26 only. I've made the font color red to make sure it stands out now.

**Comment by vlakoff** [comment]
Thank you!

I just had some difficulties to understand this part: "it will be possible to determine which HSTS sites have been visited before when this is enabled."

A quick googling led me to https://forum.palemoon.org/viewtopic.php?t=9999 and in particular [this message](https://forum.palemoon.org/viewtopic.php?p=68698#p68698).

Back to the help page, I can't think of a better phrasing, so it should be fine as it is.
