### ISSUE TITLE
High CPU usage on a website

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/Pale-Moon#1331]
Ubuntu Mate 17.04 x64
PaleMoon 27.4.2 (64-bit) by Steven Pusser

The following URL takes long to load and consumes a high amount of CPU-usage, when it loads.
[http://atboox.de/app/](http://atboox.de/app/)
In the normal Firefox, it only loads long, but doesn't take a high amount of my CPU.
I deactivated every addon during this test.

**Comment by wolfbeast** [comment]
CPU usage is as-expected for them loading a huge JS framework.

**Comment by MartinX3** [comment]
But why not in Firefox?
Why not in Chrome?
Why only in PaleMoon?

**Comment by wolfbeast** [comment]
once you can answer that question we might have something actionable. I don't see anything wrong and Firefox displays the exact same CPU usage when loading this on my system.

**Comment by MartinX3** [comment]
I was confused, because the Firefox was still smooth and runned at only 7-20%, while PaleMoon was frozen and at 50% on my Quadcore. :)

But I saw my mistake, there is a second process called "Web Content", which was at 40% while processing the website :)
Because that, Firefox runs still smooth.

Fun fact:
I wrote the developer of the site, that his site needs time to load and causes a high cpu load.
He told me, that the site is running fast and smooth on his safari and his chrome.
Weird.

**Comment by wolfbeast** [comment]
Both Safari and Chrome use webkit derivatives and a different JavaScript engine than Mozilla-based browsers.
Firefox would not be running smooth either; it would have the same task compiling everything as we do. The only difference is that it uses a different process, so the UI will remain more responsive in such edge cases; the content process would be just as "frozen".
