### ISSUE TITLE
Add Windows platform support for trusting enterprise roots (windows certstore)

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1332]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1265113 -- this would enable people in a managed environment to use Pale Moon without needing manual certificate imports.

**Comment by wolfbeast** [comment]
This BZ bug depends on other changes that are unlisted (Family Safety stuff and base import of certs from windows along with it). If we want to implement this, then we need to find out where these other changes were made first and port the relevant dependencies.

**Comment by Lorienna** [comment]
The "Family Safety" bugs:

[Bug 1239166](https://bugzilla.mozilla.org/show_bug.cgi?id=1239166)
platform work to support Microsoft Family Safety functionality

[Bug 1277240](https://bugzilla.mozilla.org/show_bug.cgi?id=1277240)
The Microsoft Family Safety certificate is still imported in the Authorities tab in the Certificate Manager

[Bug 1282871](https://bugzilla.mozilla.org/show_bug.cgi?id=1282871)
enable importing Family Safety root by default
