### ISSUE TITLE
AdNauseam blocked 

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#1336]
AdNauseam is not malware and it is not appropriate to block it.

**Comment by THEtomaso** [comment]
It's malware.
Here's the explanation by Moonchild:
https://forum.palemoon.org/viewtopic.php?f=26&t=16555/

**Comment by chaoskagami** [comment]
CPC has largely fallen out of use in favor of CPI/CPM, hasn't it?

This is targeted at CPC ads; on CPI/CPM not only does this *not* harm ad revenue, but doesn't it worsen privacy for the end user?

Perhaps not malware - it's not deliberately malicious, but the byproduct of it is harmful either way. Seriously, people should just use uBlock or something. Perhaps add greasemonkey and aak on top if you're really paranoid.

**Comment by wolfbeast** [comment]
> CPC has largely fallen out of use in favor of CPI/CPM, hasn't it?

No

![bidtypes](https://user-images.githubusercontent.com/3359132/30234940-b9f94e28-9502-11e7-9021-e706a037a59d.png)
