### ISSUE TITLE
Android: OpenSL usage is broken

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#134]
The updated libcubeb wants to use OpenSL, but since commit 13bb44a it depends on an OpenSLESProvider.h to do so.

This was added in BMO [Bug 1015932](https://bugzilla.mozilla.org/show_bug.cgi?id=1015932) - Create a way to share the OpenSLES engine between cubeb and WebRTC.
The parts for libcubeb need to be ported, likely parts 1 and 2 of that bug, excluding WebRTC.

**Comment by trav90** [comment]
The BMO bug listed above was added in Mozilla 34, and is contained in our tree. As such, this should be solved by Tycho.
