### ISSUE TITLE
Improve MP3 meta handling

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1342]
Because of people tacking all sorts of arbitrary data onto MP3 files (album covers, etc.) it sometimes causes issues with our meta parsing, e.g. wrong duration, playback issues, even hangups.

Mozilla changed this in 1202286 to using a bytereader, with follow-ups 1263334 and 1291543 to fix issues with the new reader.
@trav90 do we have any of this in our media back-end yet? If not, is it easily portable?

**Comment by trav90** [comment]
I'll take a look into this tonight.

**Comment by trav90** [comment]
The patches in the bugs listed are not in our tree. Shouldn't be too difficult to port. I'll be working on this.

**Comment by trav90** [comment]
While apparently not documented, my research shows that there are a couple other bugs containing improvements to MP3 parsing that need to be ported in addition to the 2 followup bugs listed in the first comment here. Am still working on it.

**Comment by trav90** [comment]
Were there any specific sites/MP3 files where issues were seen so I can try to reproduce with the patches in #1348?

**Comment by wolfbeast** [comment]
This is what made me look into it (IRC):

```
[16:08] m712: hello, there's a bug in palemoon where the duration on audio files won't be shown correctly when the audio file has an album cover
[16:08] m712: mp3">https://dev.nextchan.org/.file/13714a80474a357b8cef90f670359ea5696d3194824fecd132ee1d81315a1eb9/ypm.mp3 test file
[16:09] m712: shows 3:52 on palemoon
[16:10] m712: but correct duration is shown on other browsers
[16:10] m712: this is palemoon 27.4.0
```

Which had me run a mozregression resulting in a regression range listing the main bug mentioned here.

**Comment by wolfbeast** [comment]
I can confirm that a windows build now shows the correct duration and no longer hangs the browser when searching/parsing. So looks like your work on this is 100% A-OK!

**Comment by trav90** [comment]
Thanks for that. I too can confirm that the above MP3 file displays the correct duration and seeking causes no hangs.
