### ISSUE TITLE
Consider implementing X-Content-Type-Options: nosniff

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1343]
* Spec: https://fetch.spec.whatwg.org/#x-content-type-options-header.
* Tests: http://w3c-test.org/fetch/nosniff/

This feature has been landed in Firefox 50 (see bugs [471020](https://bugzilla.mozilla.org/show_bug.cgi?id=471020), [1302539](https://bugzilla.mozilla.org/show_bug.cgi?id=1302539) and [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options)).

**Comment by JustOff** [comment]
I [have tried](https://github.com/MoonchildProductions/Pale-Moon/pull/1339#issuecomment-328374089) to backport the bugs mentioned above, but have not achieved success. 

With [this patches](https://github.com/JustOff/Pale-Moon/commit/c09653208257eb287a8c35be34fe743fe2491a16) I can pass _image.html_ and _stylesheet.html_ tests, but _parsing-nosniff.html_ and _script.html_ give timeouts, while _importscripts.html_ and _worker.html_ lead to the browser crash. 

It seems the verification part works fine, because when I remove `return rv;` [here](https://github.com/JustOff/Pale-Moon/blob/c09653208257eb287a8c35be34fe743fe2491a16/netwerk/protocol/http/nsHttpChannel.cpp#L962), all errors are displayed in console at the right moment. Something wrong is going when I try to actually exit with `return`.

Does anyone have any idea what's wrong and how to fix it?

**Comment by JustOff** [comment]
I made progress with this task [moving](https://github.com/JustOff/Pale-Moon/commit/b611bb944d449c095b979e6c6d762208906e2cb5) `ProcessXCTO()` call to `ProcessResponse()`, like it was initially proposed [here](https://bugzilla.mozilla.org/attachment.cgi?id=8770524&action=diff#a/netwerk/protocol/http/nsHttpChannel.cpp_sec3). This results to no more timeouts and crashes occur when running [tests](http://w3c-test.org/fetch/nosniff/), but I still don't understand why they happen when `ProcessXCTO()` called from `CallOnStartRequest()`. Probably this is because of some other changes in the platform code that were performed during last two years, but I can't figure exactly which ones were the cause.

Now `XCTO: nosniff` works as it should and all [tests](http://w3c-test.org/fetch/nosniff/) are successful, except for two minor flaws:

* [importscripts](http://w3c-test.org/fetch/nosniff/importscripts.html) test expects `NetworkError` when the script is blocked because of `nosniff`, but our platform code always return `Error` in such cases (see [bug 1251369](https://bugzilla.mozilla.org/show_bug.cgi?id=1251369))
* [worker](http://w3c-test.org/fetch/nosniff/worker.html) test expects the script loader will not throw the exceptions when the script is blocked (see [bug 1288768](https://bugzilla.mozilla.org/show_bug.cgi?id=1288768))

I think that these shortcomings are not essential and can be corrected later when needed.

Thus, I'm almost ready to fill the PR for `nosniff`, but first we should implement one important prerequisite: add `text/json` and `text/vtt` to the known mime types (see [bug 1209658](https://bugzilla.mozilla.org/show_bug.cgi?id=1209658)). This will also be required if we decide to block scripts with wrong mime types (see bugs [1288361](https://bugzilla.mozilla.org/show_bug.cgi?id=1288361), [1299267](https://bugzilla.mozilla.org/show_bug.cgi?id=1299267) and [1333995](https://bugzilla.mozilla.org/show_bug.cgi?id=1333995)).

@wolfbeast, what do you think about this plan?

**Comment by wolfbeast** [comment]
Sorry for not getting back to you sooner -- sounds like a good plan. The tests are of minor consequence here.

**Comment by JustOff** [comment]
@wolfbeast, should I open separate issues for prerequisites or can I simply refer to this one?

**Comment by wolfbeast** [comment]
You can just refer to this one, but do please make separate PRs for individual prerequisites so it's easier to manage (unless they are really small) :)
I'll mark this assigned to you then, assuming you're taking this.

**Comment by JustOff** [comment]
Strings changes were pushed to CrowdIn.

**Comment by wolfbeast** [comment]
Re-opening due to it causing issues. See #1488

**Comment by JustOff** [comment]
I suspect the problem is that my implementation uses `aLoadInfo->GetContentPolicyType()` while original one uses `aLoadInfo->GetExternalContentPolicyType()` introduced in [bug 1182571](https://bugzilla.mozilla.org/show_bug.cgi?id=1182571). The latest is absent in our tree, and it seems it properly handles redirect cases (30x), while `GetExternalContentPolicyType()` - is not. 

I tried to track the changes, but failed so far.

**Comment by JustOff** [comment]
I also think that "[If we have XCTO: nosniff, we should have a content-type as well.](https://github.com/MoonchildProductions/Pale-Moon/commit/8167b87bc3f0cb68e53dea50a2bd990d6115cab0)" is wrong approach, we **should** reject in such situations, if it's not redirect.

**Comment by JustOff** [comment]
I have an idea how to fix this, now making some tests.

**Comment by wolfbeast** [comment]
> I also think that "If we have XCTO: nosniff, we should have a content-type as well." is wrong approach, we should reject in such situations if it's not a redirect.

I disagree. The header is there to prevent issues with **mis-matching** MIME type and content, e.g. providing a script instead of a display resource which has been a known way to circumvent security when the client detects script content and parses it as such, instead of the intended MIME type (e.g. someone uploading JS with a `.jpg` file suffix that the web server serves as an `image/jpg` but the browser would parse as JavaScript anyway because it sniffed the content). The header is not there to prevent loading of content altogether when no content-type is supplied.

The spec isn't explicit about what to do with a failure; I've opened an issue against it to get this clarified, but in the meantime I want to leave this exception in place for cases where needed headers are missing.

**Comment by JustOff** [comment]
[Should response to request be blocked due to nosniff?](https://fetch.spec.whatwg.org/#should-response-to-request-be-blocked-due-to-nosniff?):
* If response’s header list does not contain `X-Content-Type-Options`, then return allowed.
* Let nosniff be the result of extracting header values from the first header whose name is a byte-case-insensitive match for `X-Content-Type-Options` in response’s header list.
* If nosniff is failure, then return allowed.
* Let mimeType be the result of [extracting a MIME type](https://fetch.spec.whatwg.org/#concept-header-extract-mime-type) from response’s header list.
    * To extract a MIME type from a header list (headers), run these steps:
       *  Let mimeType be the result of extracting header list values given `Content-Type` and headers.
       *   **If mimeType is null or failure, then return the empty byte sequence.**
       *   Return mimeType, byte-lowercased.
* Let destination be request’s destination.
* If destination is script-like and mimeType (ignoring parameters) is not a JavaScript MIME type, then return blocked.
* If destination is "style" and mimeType (ignoring parameters) is not `text/css`, then return blocked.
* Return allowed.

I think the spec is explicit enough: we should block in case of `nosniff` and MIME type is empty.

**Comment by wolfbeast** [comment]
Thank you, I'm familiar with the wording and the spec since I read all relevant parts of it already.

It just states that if there is a failure or it's null when getting the content-type header, that is should return `""` and not null or throw. So in out case, mimeType becomes an empty string (hence my check for `.IsEmpty` in the code.

Extracting a mime type says nothing about what to do with an empty byte sequence in the comparison further down!
The spec isn't explicit at all. You can either interpret `""` as a valid MIME type (which you seem to want to do, which is incorrect IMHO) or treat it separately, in which case no comparison is possible, and the spec says nothing about that.

**Comment by JustOff** [comment]
I just mean that `empty byte sequence` `is not a JavaScript MIME type` and `is not text/css` whether it interpreted as `null`, `""`, `invalid MIME type` or something else. But let's wait for the clarification.

**Comment by wolfbeast** [comment]
I understood what you were saying the first time :) 
But: **An empty byte sequence isn't a MIME type**, at all, of any kind. So there is no mis-match in MIME type _because matching isn't possible_. If there's no mis-match, then IMHO the load should be allowed.

**Comment by JustOff** [comment]
I made some test using a local test environment with the following nginx config:
```
location ~* ^.+\.(js|css)$ {
    types         { }
    default_type  "";
    add_header    X-Content-Type-Options nosniff;
}
```
and this is how other browsers behave:

Resourse | Firefox | Chrome | Edge | IE11
-- |-- | -- | -- | -- 
*.js | block | block | allow | allow
*.css | block | allow | allow | block

**Comment by wolfbeast** [comment]
Thanks for taking the time to test this. So, as you can see, the spec isn't clear and implementation differs depending on browser as a result right now. Looks like the intention in the whatwg/fetch bug states it is to block strictly, so in that case I'll back out the change to allow on empty content-type.

**Comment by wolfbeast** [comment]
This feature should now be complete and working according to spec. Closing.
