### ISSUE TITLE
Back/Forward/Reload menu items of the Web Panel are still broken

### ISSUE THREAD

**Issue by FranklinDM** [MoonchildProductions/Pale-Moon#1344]
How to reproduce:
1. Edit any bookmark.
2. Check the "Load this bookmark in the sidebar".
3. Now, click the edited bookmark and it will open a web panel.
4. Once the page loads, right click and you'll notice that the stop button is stuck and when I try to allow navigation in the web panel (by removing the onclick handler) and navigate further, the back/forward buttons stay disabled.

Related bug (which is quite old already): https://bugzilla.mozilla.org/show_bug.cgi?id=483919

**Comment by wolfbeast** [comment]
Hmm.. looks like a clear case of an unresolved regression that got forgotten about because it's such a corner case.

**Comment by FranklinDM** [comment]
This fixed the broken back/forward menu items but the stop menu item is still stuck even if the page has already finished loading and the reload menu item never appears.
![Sidebar@Mdn](https://user-images.githubusercontent.com/11641537/30321219-e53b4798-97e7-11e7-92b1-a32ac42539e1.png)

**Comment by wolfbeast** [comment]
Question: why do you need the side bar to act like a full navigator window, anyway? That's not exactly its purpose.

**Comment by FranklinDM** [comment]
I'm currently extending TGS' multipanel to have navigation-like abilities (ie. Adding a urlbar and navigation buttons by using an overlay on the web panel). However, when I try to set the commands of the nav buttons (Browser:Back, etc) it stays in the disabled state.

Now, since I need to allow navigation for it to become a full fledged mini browser/panel. I used an overlay to do so.

But this is also possible without using my add-on, just open DOM inspector on the browser panel element and remove the onclick attribute.

**Comment by wolfbeast** [comment]
I'm sorry but that is outside of scope for default behavior. it's a web panel; if you want to extend its capabilities you have to overlay them with own functionality as you've done.
