### ISSUE TITLE
glx X11 detection fails because it assumes pipefds are never 0

### ISSUE THREAD

**Issue by ProhtMeyhet** [MoonchildProductions/Pale-Moon#1353]
already reported a bugzilla from mozilla, but since i use palemoon i'd like it fixed here, too :-)

https://bugzilla.mozilla.org/show_bug.cgi?id=1400839

Steps to reproduce:

i'm using 52.2, but this is probably there since version 12.

over at enlightenment we have a strange issue: if firefox is started via enlightenment, glx X11 detection fails because strace shows the reply from /source/toolkit/xre/glxtest.cpp is correctly written, but never read. if started via a terminal - terminolgy - the detection works. bug report: https://phab.enlightenment.org/T5606

after reading the source code, i noticed in source/widget/GfxInfoX11.cpp:59 glxtest_pipe is tested against 0 to determine if GfxInfo::GetData() was already called. however glxtest_pipe is filled from pipefd[0] from a pipe(pipefd) call which can be 0. the solution should be simple, however i havn't tested it, initialise glxtest_pipe with -1 and check against -1 in  /widget/GfxInfoX11.cpp

Actual results:
glx detection fails.

Expected results:
glx detection should work.

following patch should fix that, however fully untested:

```
--- a/GfxInfoX11.cpp	2017-09-18 13:54:22.874081027 +0200
+++ b/GfxInfoX11.cpp	2017-09-18 13:55:08.790931935 +0200
@@ -28,7 +28,7 @@
 #endif
 
 // these global variables will be set when firing the glxtest process
-int glxtest_pipe = 0;
+int glxtest_pipe = -1;
 pid_t glxtest_pid = 0;
 
 nsresult
@@ -55,8 +55,8 @@
     // to understand this function, see bug 639842. We retrieve the OpenGL driver information in a
     // separate process to protect against bad drivers.
 
-    // if glxtest_pipe == 0, that means that we already read the information
-    if (!glxtest_pipe)
+    // if glxtest_pipe == -1, that means that we already read the information
+    if (glxtest_pipe == -1)
         return;
 
     enum { buf_size = 1024 };
@@ -65,7 +65,7 @@
                              &buf,
                              buf_size-1); // -1 because we'll append a zero
     close(glxtest_pipe);
-    glxtest_pipe = 0;
+    glxtest_pipe = -1;
 
     // bytesread < 0 would mean that the above read() call failed.
     // This should never ha
```ppen. If it did, the outcome would be to blacklist anyway.

**Comment by wolfbeast** [comment]
Reopened for verification. see the PR comment.

**Comment by trav90** [comment]
I just pushed out a new unstable build. @ProhtMeyhet can you please verify that this works as intended on Enlightenment?

**Comment by ProhtMeyhet** [comment]
i can only find unstable builds on https://www.palemoon.org/unstable/ which states 

> These versions are only available in 32-bit for Windows.

so no, apparently i can't test with unstable builds.

**Comment by JustOff** [comment]
@ProhtMeyhet 
http://linux.palemoon.org/download/unstable/

**Comment by ProhtMeyhet** [comment]
@JustOff thank you!

i can confirm under enlightenment in unstable graphic detection is now the same as when started from terminology.

sha256
effba89cf37f6ddc14a3dc34233430196f97c35a91e0dc2364e56fb188a17378
palemoon-unstable-latest.linux-x86_64.tar.bz2

**Comment by ProhtMeyhet** [comment]
it's also fixed in firefox nightly/aurora

**Comment by wolfbeast** [comment]
Thanks!

**Comment by wolfbeast** [comment]
Uplifted to release in 2e23f439c514196a6d9dc7bb4863512c1dbc09f4

**Comment by trav90** [comment]
@ProhtMeyhet thanks for verifying!
