### ISSUE TITLE
W3C DRM status in Pale Moon

### ISSUE THREAD

**Issue by Symbian9** [MoonchildProductions/Pale-Moon#1354]
> https://www.palemoon.org/survey2017/
> ...
> DRM: We're aware that in-browser DRM is being pushed pretty hard by several big players (who, not-so-coincidentally, are also involved in editing and publishing the very HTML specifications that make this possible in-browser) and our approach is that "black-box" DRM content decoding modules have no place in an Open Source browser. It is even debatable whether DRM actually does anything to combat what it is supposed to be designed for.
> In light of this, and also following the results from this survey, we remain firm in that, out of principle as well as our users' desire, we will keep the browser completely free of DRM. People who have commented that this approach was (one of) the main reason(s) to choose Pale Moon as their browser can rest easy in the knowledge that it will not find its way into this browser.

So, now DRM approved by W3C
* https://www.w3.org/blog/news/archives/6521

What final status of DRM in Pale Moon would be?

REFERENCE:
https://forum.palemoon.org/viewtopic.php?t=15245

**Comment by mattatobin** [comment]
You just posted the final decision.. Was there something about it that you misunderstood?

**Comment by Symbian9** [comment]
So, Pale Moon (atleast official default builds) will newer include DRM module as in-built plugin, right?

**Comment by wolfbeast** [comment]
See also our roadmap:

> The following specific media streaming feature(s) is/are not on Pale Moon's roadmap:
> 
>     In-browser DRM (EME)

http://www.palemoon.org/roadmap.shtml

**Comment by Symbian9** [comment]
For the record, if look inside full text of press-release provided by W3C...

> https://www.w3.org/2017/09/pressrelease-eme-recommendation.html.en
> 
> https://www.w3.org/ — 18 September 2017 — Furthering its goal to make the Web a first-class platform for media and entertainment, the World Wide Web Consortium (W3C) published Encrypted Media Extensions (EME) as a W3C Recommendation or Web standard...


... we could see that there no word "**freedom**". And that's all what we should to know about W3C.

**Comment by Symbian9** [comment]
W3C **-1**
> https://www.eff.org/deeplinks/2017/09/open-letter-w3c-director-ceo-team-and-membership
> 
> EFF is resigning from the W3C.

Who will be next?
* https://www.w3.org/Consortium/Member/List

**Comment by wolfbeast** [comment]
I'm not sure what the point is you're trying to make, but if you want to discuss this, please go to the forum.

EME will just be a recommendation by the W3C, nothing more. The W3C's decision-making process is wholly subject to the votes of its paying members. Those members by sheer force of finances exclude the populous, exclude small projects and exclude true non-profits (therefore most FOSS). The value of its recommendations are therefore directly weighed against the exclusive nature of this process. W3C candidate recommendations are no longer a compelling argument for implementation.
