### ISSUE TITLE
Minor gtk style issue

### ISSUE THREAD

**Issue by Yanpas** [MoonchildProductions/Pale-Moon#136]
Transition between menu bar and panels is ugly. This transition is in all themes
![_2015-07-26_12-55-14](https://cloud.githubusercontent.com/assets/7345761/8893396/61bef2e0-3397-11e5-9e56-932addfbd816.png)

**Comment by Lootyhoof** [comment]
Appears to be a style used intentionally by the default theme, though I agree it's a bit jarring. Line 40 of `browser.css`, the first `#nav-bar` declaration should be removed:

    #nav-bar:not(:-moz-lwtheme),
    #nav-bar[collapsed=true] + toolbar:not(:-moz-lwtheme),
    #nav-bar[collapsed=true] + #customToolbars + #PersonalToolbar:not(:-moz-lwtheme),
    #nav-bar[tabsontop=true],
    #nav-bar[tabsontop=true][collapsed=true]:not([customizing]) + toolbar,
    #nav-bar[tabsontop=true][collapsed=true]:not([customizing]) + #customToolbars + #PersonalToolbar {
      background-image: linear-gradient(rgba(255,255,255,.3), rgba(255,255,255,0));
    }

Additionally, `-moz-appearance: none` should be set to `#toolbar-menubar` to remove any additional borders (not shown on the above, but I noticed it on other GTK styles). The following should fix this, for those curious:

    #toolbar-menubar {
      -moz-appearance: none !important;
    }

    #main-window[tabsontop=false] #nav-bar {
      background-image: none !important;
    }

![Pale Moon fixed style] (http://i.imgur.com/sXa0qPw.png)

**Comment by Yanpas** [comment]
Guess you are talking about /browser/themes/linux/browser.css
Line 40 there is empty, you may be talking about line 53. And further I do not understand what to replace. From your comment I can't make pull request. Please make Pull request or send me updated css (via gist e.g.) :smiley_cat:

**Comment by wolfbeast** [comment]
Is this still an issue? If so, shall we tweak the Linux theme a bit, then?

**Comment by Yanpas** [comment]
I think it's not an issue since I don't use palemoon

**Comment by trav90** [comment]
Considering the length of time this has been open and the only followup being that the user no longer uses Pale Moon, I am closing this. Someone can re-open if this is still an issue.
