### ISSUE TITLE
Add animated WebP support

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1361]
Since we advertise `image/webp` via `image.http.accept` we should support animated WebP as well.

Here is the [test page](https://cloudinary.com/blog/animated_webp_how_to_convert_animated_gif_to_webp_and_save_up_to_90_bandwidth).

**Comment by wolfbeast** [comment]
This is already supported in UXP. It'll become available to Pale Moon once we move over to that platform.

**Comment by wolfbeast** [comment]
Unless, of course, i misunderstood the reason for this issue and you'd prefer a cross-porting of the UXP code to here?

**Comment by JustOff** [comment]
It would be nice, but if it takes too much effort, I definitely can wait UXP. Unfortunately, I can't handle this on my own.

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
