### ISSUE TITLE
Dropbox.com - Regression in PM v27.5.0

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1363]
Seems that elements @ Dropbox.com can't be shown anymore in Pale Moon v27.5.0, although the pages rendered just fine in v27.4.2.
Examples:
https://www.dropbox.com/s/n8n2bu2tshtetnb/
https://www.dropbox.com/sh/wackcyek8nzziaf/wJ1hAkF49U/
No elements are shown at all..
Just a white page.

(Pale Moon v27.5.0,x64 / Win8.1Pro)

**Comment by JustOff** [comment]
Once more UserAgent sniffing issue. Setting `general.useragent.override.dropbox.com` to `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.9) Gecko/20100101 Firefox/45.9` resolves it.

**Comment by Sa-Ja-Di** [comment]
Works with native user agent mode without issues in the latest unstable

**Comment by JustOff** [comment]
Well, then it's only version sniffing issue :stuck_out_tongue_winking_eye:

**Comment by THEtomaso** [comment]
Confirmed.
I used the UA string from PM v27.4.2, and the pages work again. :)
You should include this override in the next point release.

**Comment by wolfbeast** [comment]
Dropbox should be served the native UA in that case. Patches welcome to that effect to the UA override include in `browser/branding/shared`

**Comment by JustOff** [comment]
@wolfbeast 
Btw, what about new GRE_VERSION? You bumped it [twice in a row](https://github.com/MoonchildProductions/Pale-Moon/commits/master/config/milestone.txt) in `milestone.txt`, but not in `uaoverrides.inc`.

**Comment by wolfbeast** [comment]
Taken care of. thanks for the reminder.

**Comment by THEtomaso** [comment]
This UA override works for dn.no (which I posted a link to in my previous post):
Mozilla/5.0 (Windows NT 6.3; rv:45.9) Gecko/20100101 Firefox/45.9
Don't know if it's the "best" string to use though.
Could someone take a look at it, and perhaps make sure that it's included in the next point release?
