### ISSUE TITLE
Expose SOCKS DNS lookup preference in the UI

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1364]
SOCKS5 offers an option to perform DNS lookups through the proxy. This is used for e.g. TOR browsing and other closed networks that use SOCKS gateways with internal DNS names.

This option has been available for a very long time in Mozilla products, but has never been exposed in the UI. A simple addition to the proxy/connection window should take care of this. Of course it means string changes, so this will not be in any point release but will have to be published in a major release.

**Comment by JustOff** [comment]
If you have not already started working on this, I can take it ([bug #665319](https://bugzilla.mozilla.org/show_bug.cgi?id=665319) + [bug #1249494](https://bugzilla.mozilla.org/show_bug.cgi?id=1249494)) + also expose preference for proxy autologin ([bug #910670](https://bugzilla.mozilla.org/show_bug.cgi?id=910670)).

**Comment by wolfbeast** [comment]
Please don't take already-assigned bugs in the future; it risks double work being done.
