### ISSUE TITLE
Revert Windows 10 non-accent color to grey

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1368]
@Lootyhoof Looks like our choice to go for the dark indigo when accent colors aren't applied to title bars wasn't a good idea after all.

There are a few usability issues with it:
- Bookmark toolbar items (and likely also extension items) don't adjust, and if put in an accent-color area become black on dark indigo, which is very hard to see.
- Contrast is relatively low for navigation controls.
- In general, people who don't want the accent color want the browser to behave like other applications, meaning a light toolbar color.
- The only easy way to work around it is with a lightweight theme, which has other drawbacks.

So we either have to supply a choice to the user or simply revert to what we had before and use a light grey (or other very light color).
This needs to be uplifted to -release to be in 27.5.1.

**Comment by Lootyhoof** [comment]
I wouldn't recommend fully reverting as this fixes other things (namely, HiDPI caption button alignment). However, we certainly can tweak this value. It depends what we think should be a sane default though when there isn't an accent colour applied.

Based on feedback people seem to want the `#FFFFFF` style back instead of the current `hsl(239, 33%, 38%)`. On inactive windows we also have `hsl(0, 0%, 90%)` (though I've not seen any feedback about that). We could make it use `#FFFFFF` for both active and inactive windows, use `#FFFFFF` for active and `hsl(0, 0%, 90%)` for inactive, or `hsl(0, 0%, 90%)` for both. This wouldn't affect the styling with accent colours applied, which we can still keep the same.

With regards to the bookmarks toolbar this is probably something I should look into anyway. We'd want this to change to a brighter version in a `brighttext` situation regardless.

Let me know what you think.

**Comment by wolfbeast** [comment]
I wasn't saying we revert all the work done, just the colors.
I don't think pure white is good for anything that isn't a workspace (despite what "modern" designers tend to do) so `hsl(0, 0%, 90%)` for both would be best.

**Comment by JustOff** [comment]
And besides changing the palette, is it possible to make these color tricks just optional so that the Pale Moon window can behave like all others in the OS?

**Comment by wolfbeast** [comment]
@JustOff No, that's not possible - we must define something if it's not the accent color from Windows. We can't fall back to "native" because our window isn't a tradition GUI window.

**Comment by JustOff** [comment]
Wow, how lucky I'm that I don't use Win10 at all :stuck_out_tongue_winking_eye:

**Comment by wolfbeast** [comment]
We actually moved away from native to solve a whole bunch of problems (native being background=transparent)

**Comment by wolfbeast** [comment]
I compared other windows, and actuall using straight up `#FFFFFF` for the active window seems to be the norm for Win 10 (yuck), so.. changed my mind (sorry!) and `#FFFFFF` for active, `hsl(0, 0%, 90%)` for inactive is the best choice.

**Comment by wolfbeast** [comment]
@Lootyhoof I'll take this one myself. it's pretty much a 1-liner anyway.

**Comment by kerframil** [comment]
In Windows 10, #FFFFFF is also the [correct colour](https://forum.palemoon.org/download/file.php?id=8803&mode=view) for inactive Windows. Opinions may differ as to whether it is aesthetically pleasing, but it is the standard and one that prior versions of Pale Moon observed.

**Comment by wolfbeast** [comment]
Thanks for your input but I do not agree with using white as an inactive window color, especially not sine it complete washes out the Pale Moon appmenu button if used.

**Comment by kerframil** [comment]
In that case, may I ask whether there will be any method to override this decision e.g. by way of a custom userChrome.css?

**Comment by Lootyhoof** [comment]
It's already possible to do this. The below forces a specific `background-color` for the window frame, in both active and inactive windows.

````
#main-window:not(:-moz-lwtheme),
#main-window:-moz-window-inactive:not(:-moz-lwtheme) {
  background-color: #FFFFFF !important;
}
````
You can of course change that with any other you'd prefer.

**Comment by wolfbeast** [comment]
A bit more than a one-liner (because caption buttons) but still simple enough.
I'll build a new unstable and publish in 30 or so. Please verify.

**Comment by wolfbeast** [comment]
Uploading is taking forever for no apparent reason (my 10Mbit upstream is giving me 20 KB/s???), so just keep an eye on any unstable with date 2017-09-28 in the coming hours. it'll be done eventually.

**Comment by JustOff** [comment]
This looks definitely much better!

**Comment by wolfbeast** [comment]
Assuming verified judging by the various comments.
Uplifted in [cfc885f]
