### ISSUE TITLE
Palemoon its impossible to build

### ISSUE THREAD

**Issue by nyancat18** [MoonchildProductions/Pale-Moon#1378]
host: manjaro testing 64 *17.0.5*

dependencies

python2 2.7.14

llvm 5.0.0-1

lld 5.0.0-1

clang 5.0.0-1

dbus-glib 0.108

m4 1.4.18-1 

libxt 1.1.5

startup-notification 0.12-5

icu 59.1

autoconf2.13 2.13

gcc5 5.4.0-1

yasm 1.3.0-2

arch: 64 bit

ram: 16

cpu: fx 8350

build command: python2 mach build

flags:  
  >export CFLAGS="${CFLAGS//-fno-plt/}"
  >export CXXFLAGS="${CFLAGS//-fno-plt/}"

  >export MOZBUILD_STATE_PATH="$srcdir/mozbuild"
  >export MOZCONFIG="$srcdir/mozconfig"
  >export CPPFLAGS="$CPPFLAGS -O2"

buildlog 

https://p.teknik.io/Raw/kgCuw

**Comment by nyancat18** [comment]
**i cant build it**

but *official binary*   works

**Comment by trav90** [comment]
Manjaro currently uses GCC 7 by default (which does not work to compile Pale Moon). You'll need to add EXPORT lines to use your GCC 5 instead (though GCC 4.9 is highly recommended instead).

**Comment by nyancat18** [comment]
i use gcc5

**Comment by trav90** [comment]
Please post the mozconfig you use.

**Comment by tony-aln** [comment]
It seems by the log that the compiler used was the current one on manjaro and arch repos (gcc 7.2) maybe you should take a look at https://aur.archlinux.org/packages/palemoon/ I have successfully built Pale Moon 27.5.0 2 days ago on Arch Linux, using gcc5 from the the link above. The PKGBUILD and mozconfig on this AUR package work great for me, please check it out.
PS.: I know gcc v4.9 is the recommended one, but I've been building Pale Moon for more than a year with stable results (as far as I can tell) on gcc5...

**Comment by wolfbeast** [comment]
> PS.: I know gcc v4.9 is the recommended one, but I've been building Pale Moon for more than a year with stable results (as far as I can tell) on gcc5...

Then let me quote Mozilla who should be considered as much of authority in that respect as anyone.

```
GCC 4.9 is required as of Firefox 50. The Firefox codebase relies on some C++ features that are not supported in earlier versions of GCC, and as of December 2016 causes some errors in GCC 5.x or later.
```
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation

**Comment by tony-aln** [comment]
Thank you for the reply @wolfbeast , I will revise the more recent build logs to see if errors have appeared and I haven't noticed (since the builds have been successful).

**Comment by wolfbeast** [comment]
@tony-aln The issues with gcc 5 builds are generally not at compile-time, but at run-time. A build log is likely not going to show anything of substance (although it might) but binaries can display erratic, unexpected and hard-to-reproduce incorrect behavior.

**Comment by tony-aln** [comment]
Hmm, interesting. Even with that, the resulting binaries don't seem to display incorrect behavior. Thanks for the clarification, and for bringing Pale Moon to us.

**Comment by nyancat18** [comment]
@trav90 
i've tried to use this :)

https://aur.archlinux.org/packages/palemoon/

**Comment by trav90** [comment]
As tony-aln mentioned above, according to the log it appears the compiler used was the default (gcc 7). So were you trying to build manually or using the AUR package?

**Comment by nyancat18** [comment]
i'm trying to  *steal*  some settings frompalemoon-git **aur too**

https://p.teknik.io/Raw/ZpGE9

**Comment by wolfbeast** [comment]
Can you please move this discussion to the forum's Linux board?
It's clearly a build issue that isn't a Pale Moon bug.
