### ISSUE TITLE
Add Linux CSS detection support

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#138]
It would be much more helpful on the theme front if it were possible to detect if the user is using a variant of Linux (or *nix, if you want to aim for a wider group), preferably via a value in `-moz-os-version`, so we can work around any issues on this platform without resorting to using chrome skins to solve what could in some cases be minor issues. I suspect this could be possible by seeing if GTK is being used.

Note that Mozilla does not appear to have a bug set up for this, so this is just basically making aware that such a feature would be appreciated. The only such way I have found is [this] (https://jeffclayton.wordpress.com/2015/02/01/css-os-platform-specific-hacks/), using this very hacked-together approach (note that `-moz-osx-font-smoothing` is only available in Firefox 25+):

    @supports (-moz-appearance:none)
        and (background-attachment:local)
        and (not (-moz-osx-font-smoothing:auto)) {
            @media not screen and (-moz-os-version) {
            }
    }

**Comment by wolfbeast** [comment]
FreeBSD and Linux have been added in Commit: b1ae9ed81fdcf71c5c712a076f73004af749096a
