### ISSUE TITLE
Update libpng and enable SSE2 support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1381]
Looks like we need to update libpng if we want to update the zlib module.
Updating the zlib module without updating libpng first will expose a bug in libpng.

This blocks #1377

**Comment by wolfbeast** [comment]
LibPNG 1.6.22+ supports optimized SSE2 decoding for Intel architecture. Enabling this with the update will be a Good Thing™

**Comment by chaoskagami** [comment]
FYI, there's a rather annoying bug in libpng 1.6.32 that causes about 1-2% of all images I've seen to fail to load. Assuming you don't want to wait for the next stable release, you may want to apply the relevant patch yourself.

https://sourceforge.net/p/libpng/bugs/270/

On September 29, 2017 3:52:35 AM EDT, Moonchild <notifications@github.com> wrote:
>LibPNG 1.6.22+ supports optimized SSE2 decoding for Intel architecture.
>Enabling this with the update will be a Good Thing™
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MoonchildProductions/Pale-Moon/issues/1381#issuecomment-333057437

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wolfbeast** [comment]
We're not using 1.6.32 the update was to 1.6.28. Does it affect us?
Also, the bug link doesn't actually give me any sort of related code changes, only bug discussion...

**Comment by wolfbeast** [comment]
OK, found the diff in question after too long digging. Doesn't look like that applies to us as it's code added to 1.6.32. We'll just skip that version when we update next anyway ;)
