### ISSUE TITLE
SSL received a record that exceeded the maximum permissible length

### ISSUE THREAD

**Issue by TimZwart** [MoonchildProductions/Pale-Moon#1387]
when trying to access an internal company web site, i receive this error.

 Error code: ssl_error_rx_record_too_long. 

this web site is hosted on Adobe AEM. i'm not sure what other info i can provide except that it works on Firefox and Chrome.

**Comment by janekptacijarabaci** [comment]
Maybe this server doesn't send the correct TLS/encrypted content (an user agent sniffing?).

An example:
https://www.palemoon.org:80/

**Comment by adeshkp** [comment]
If it's an internal site, most likely it is not "true" SSL/TLS. In the worst case, it might be plain http being served on port 443. In the best case, there is a server misconfiguration. Ask the administrator to fix the setup or simply serve it over plain http.

And about Chrome/Firefox SSL implementation: it is utterly broken (intentionally).

**Comment by TimZwart** [comment]
I'm pretty sure we do use true https but i cannot be sure about whether it does not sniff user agents.

**Comment by wolfbeast** [comment]
Examining the traffic with wireshark would probably provide more insight.

**Comment by wolfbeast** [comment]
Closing stale bug
