### ISSUE TITLE
Improve logic/flow in XPIinstaller

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1396]
As it is now, in at least one location, code flow relies on implied behavior of callees that can be completely opaque (e.g. C++ modules behind IDL). This should be rewritten to make all code flow explicit and contained within the JS module itself so we don't create bugs here by having unrelated code changing in the platform.

See also #1393 for discussion.

**Comment by JustOff** [comment]
I'm probably a little short sighted, but still I see no problems here. Almost everywhere in Pale Moon we rely on the fact that C++/IDL modules trow errors in a way they can be properly handled by js code. Therefore, if for some weird reason nsIZipReader will not throw an error when it try to get a stream from non-existent file, then not only XPIProvider, but also many other modules will be irreparably broken.

**Comment by wolfbeast** [comment]
I have a problem with this particular thing because it's an implicit throw followed by an explicit throw in the same scope. That isn't at all clear behavior, and risky for future changes of code.
There's just room for improvement in logic and clarity.

**Comment by JustOff** [comment]
I have to admit that originally I wrote the following:
```
  try {
    zis = aZipReader.getInputStream(FILE_INSTALL_MANIFEST);
  } catch (e1) {
    try {
      let zws = aZipReader.getInputStream(FILE_WEBEXT_MANIFEST);
    } catch (e2) {
      throw e2;
    }
    zws.close();
    throw {
      name: e1.name,
      message: e1.message,
      webext: true
    };
  }
```
but then I have realized that this is just equal to:
```
  try {
    zis = aZipReader.getInputStream(FILE_INSTALL_MANIFEST);
  } catch (e) {
    let zws = aZipReader.getInputStream(FILE_WEBEXT_MANIFEST);
    zws.close();
    throw {
      name: e.name,
      message: e.message,
      webext: true
    };
  }
```
and the second version seemed to me more simple and clear.

Perhaps we should just add comments to the code to explain the logic?

**Comment by wolfbeast** [comment]
I'm revisiting this to fix it today.
Neither is actually correct, because you'd be re-throwing the wrong error, so it needs nested try-catch with explicit throws no matter what way you look at it. I'll add comments to clarify the logic as well.

**Comment by wolfbeast** [comment]
Closing this since I didn't see any other clear issues with `XPIProvider.jsm`
