### ISSUE TITLE
PM crashes when dragging a tab into a new windows and back

### ISSUE THREAD

**Issue by Domochevsky** [MoonchildProductions/Pale-Moon#1397]
**How to reproduce:**
1. Grab a tab, drag it off the Palemoon window, so it creates a new window for the tab to sit into.
2. Grab that tab again and drag it back into your main Palemoon window. (The previously created new window closes itself, since there are no tabs left.)
3. (Maybe optional) Close that tab.
4. Watch PM fall over and die a few seconds later.

A crashdump of the event in question has been sent to the usual email address.

The system:
Windows 7 (64bit)
Palemoon 27.5.0 (64bit)
No admin rights for the process (it's running inside Sandboxie. And to catch that horse at the hill: no, I won't run it outside, even for testing purposes.)

**Comment by wolfbeast** [comment]
I'm unable to reproduce this. The crash dump indicated you have taskbar tab previews enabled, which is where the crash occurs. Specifically, it crashes not being able to get the window hook for the preview window. This is most likely interference with sandboxie preventing the hook into the taskbar proxy window (which is required to clean up the monitor in it), so if you insist on running sandboxie, you should disable taskbar tab previews.

**Comment by Domochevsky** [comment]
Disable the taskbar previews... I'm ok with that.

That does indeed resolve this issue for me. Thanks.
