### ISSUE TITLE
Recent code wont compile

### ISSUE THREAD

**Issue by Feodor2** [MoonchildProductions/Pale-Moon#1398]
dom\base\ScriptSettings.cpp(522) : error C2065: 'mIsMainThread' : undeclared identifier

I have edited as it was in the firefox put that thing into ScriptSettings.h and assign it in AutoJSAPI::InitInternal.

Compiling continues fine, shall i do patch?

**Comment by wolfbeast** [comment]
Is this resolved with the merge?

**Comment by Feodor2** [comment]
Turned out this error only happens with -enable-debug. And it resolved with above merge
