### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Self-Referential-Drama** [MoonchildProductions/Pale-Moon#14]
I saw this [thread](http://forum.palemoon.org/viewtopic.php?f=5&t=6437) on the Pale Moon forums, so I thought I could help apply patches from the BMO to Pale Moon. 

I have a repository [forked](https://github.com/Self-Referential-Drama/Pale-Moon), and applied a few small patches, I plan to continue doing this, but I am wondering if that is okay with the Pale Moon development road map. If it is I will go ahead and submit a pull request.

Thank you.

**Comment by wolfbeast** [comment]
That's awesome, and thanks in advance for your efforts! 

There's plenty to do yet on Pale Moon and help this way is greatly appreciated. I do ask that you communicate any important feature-changing bugs with me/us (preferably by way of the forum) so we keep a good overview over what happens in your fork and preventing you from doing double/unwanted work for Pale Moon.

Of course you're free to keep changing things yourself for your own use as well, but for contributing patches it needs to stay in line with what is planned overall. :)

Current small patches look good (had a quick look over them) so feel free to make a pull request!

**Comment by Self-Referential-Drama** [comment]
All right, thank you for the information.
