### ISSUE TITLE
Altibox's TV streams doesn't play in Firefox Compatibility mode anymore

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1403]
Altibox is one of Norway's and Denmark's largest broadband providers.
Read about them here:
https://en.wikipedia.org/wiki/Altibox

Customers can view all the channels that they subscribe to online here:
http://tvoveralt.altibox.dk/tv/
http://tvoveralt.altibox.no/tv/
..but unfortunately, in the latest version of Pale Moon (v27.5.0), the video streams (Silverlight) won't play with the default User Agent Mode anymore (works just fine in v27.4.2).

Native mode still works, so I guess perhaps it should be added as UA overrides (one for altibox.dk and one for altibox.no) in the next point release (considering the rather large amount of Altibox customers and all)?

**Comment by wolfbeast** [comment]
Step 1: contact the website owners.

**Comment by THEtomaso** [comment]
> Step 1: contact the website owners.

Already have.
I'll let you know when I get an answer.

**Comment by THEtomaso** [comment]
Update:
I just sent Altibox another mail, pointing out the issue in great detail again, and requesting a response from them.

**Comment by THEtomaso** [comment]
3 months went by, and there was no response from Altibox.

I wish I could say that this kind of silent treatment is unusual, but unfortunately it seems to be very typical when it comes to these sort of problems.

How about it, Moonchild?
Do you think you could add UA overrides to PM for the two URLs that I mentioned in the first post?
Like I wrote, serving them PM's native string seems to do the trick!
Of course, I'll check in on this issue from time to time, so if anything changes in the future, and the overrides aren't needed anymore, I'll let you know.

**Comment by mattatobin** [comment]
Serving them our native UA string likely just causes it to fall back to something.. Also, why should we add a UA for this site...

You do know there is a performance hit for every SSUAO we add.. Granted it is VERY small but it can add up.. Also, we add an SSUAO it is one more thing we have to keep tabs on. So adding one in is reserved for most commonly used sites by more than just yourself.

Sure, have a post on the forum about it.. Do it yourself.. But don't expect us to add an override for every site ever...

**Comment by THEtomaso** [comment]
Yes, I understand.
MC has explained this to me before.

These sites might not be very big in a World context, but like I pointed out in my first post; Altibox is one of the largest broadband providers in Norway and Denmark.
Personally, I'm OK with adding UA overrides, but this is exactly the type of issue that prevents me from recommending Pale Moon to "average" users (which of course I'm eager to do).
As you probably know, most people don't want to fiddle around with stuff like UA overrides..
They just want things to work out-of-the-box.

Like I said, if you add these overrides, I will still continue to check in on the issue from time to time.
If the overrides are no longer needed, I'll notify you guys here right away!

**Comment by mattatobin** [comment]
How about taking the discussion of overrides back to the forum where it belongs.. You are creating noise on the issue tracker.

**Comment by wolfbeast** [comment]
Assuming this is solved by UXP with its media back-end completion.

**Comment by THEtomaso** [comment]
This issue is not solved by UXP.
(Tested with Pale Moon v28.0.0a2)
