### ISSUE TITLE
Not working progressive load with option browser.sessionstore.cache_behavior

### ISSUE THREAD

**Issue by zgwerby** [MoonchildProductions/Pale-Moon#1404]
browser.sessionstore.cache_behavior = 1
browser.sessionstore.max_concurrent_tabs = 3 (default)
All pinned tabs load together, when I (need for some sites) force update it on browser start, ignore second pref.
My browser info
[info.txt](https://github.com/MoonchildProductions/Pale-Moon/files/1373557/info.txt)

**Comment by mattatobin** [comment]
Pinned Tabs I believe have special behavior compared to ordinary tabs. Not sure these prefs affect them.

**Comment by wolfbeast** [comment]
Pinned tabs will always be loaded, and always be loaded concurrently. They are indeed treated specially and do not adhere to settings that apply to normal tabs.
Pinned tabs are meant to be used specifically for pinned web applications, not "normal sites"

**Comment by wolfbeast** [comment]
Marking closed as invalid without further response from reporter.
