### ISSUE TITLE
Exception in TabsProgressListener.onStateChange

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1406]
Pale Moon 27.5.1 & 27.6.0a1 x86 @ Win7x64.

STR:
1. `general.useragent.override.rozetka.com.ua` -> `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9`
2. Open https://rozetka.com.ua
3. Pass captcha (if asked)

`[Exception... "Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIWebProgress.DOMWindow]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: chrome://browser/content/browser.js :: TabsProgressListener.onStateChange :: line 10671"  data: no]`

Subsequent site navigation constantly causes this error on all pages.

See: https://forum.palemoon.org/viewtopic.php?f=12&t=17001

PS: In addition: the browser significantly slows down until the site is closed.

**Comment by wolfbeast** [comment]
No component failure is thrown for me on that site (after forcing desktop with UA override). No slowness experienced either. Works for me?

**Comment by JustOff** [comment]
It's very odd. As well as original reporter, I always get this error on my PC and on my wife's laptop. 

Could someone else try to reproduce it? @janekptacijarabaci ?

**Comment by janekptacijarabaci** [comment]
Confirmed for me.

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1125822
and Firefox (trunk/latest nightly 58.0a1) - e10s: off - this problem persists...

**Comment by wolfbeast** [comment]
Ah, I see, it shows up in the browser console only.
I looked at the relevant code and there isn't really much to be done there. It seems to be a problem with the website intercepting clicks and mouse events (most likely also the reason for higher-than-normal processor use causing sluggishness).

**Comment by JustOff** [comment]
Well, it seems we can do nothing more here.
