### ISSUE TITLE
vk.com: Can't play audio tracks

### ISSUE THREAD

**Issue by danykey** [MoonchildProductions/Pale-Moon#1407]
Hi,

Palemoon can't play audio tracks on vk.com
Firefox(include android version) without Flash player is working well.

vk.com throws a message for Palemoon:
```
Flash Player is required for playing music.
You can install it here.
```
Thanks.

**Comment by Bfgeshka** [comment]
Works for me.

**Comment by danykey** [comment]
I am using Linux.
Maybe issue on Linux only?

**Comment by Kokokokoka** [comment]
27.6.2 (32-bit)
gentoo 32-bit
works for me.

**Comment by benrob0329** [comment]
Do you have the appropriate codecs installed? (Dunno if PM loads its own codecs or not, but I think FF does)

**Comment by danykey** [comment]
PM 27.6.2
Still not working for me.
I think codecs are installed.
ffmpeg and media players like VLC are installed.

**Comment by trav90** [comment]
Please ensure that the libavcodec is available on your system. It is a component of FFmpeg, but some distros move it to its own package (I believe Ubuntu does this if memory serves).

**Comment by whitebyte** [comment]
PM 27.7.1 Gentoo x64 is able to play music from vk.com with https://gstreamer.freedesktop.org/modules/gst-libav.html installed

**Comment by trav90** [comment]
Considering lack of response and no reproducible by others, I'm closing this. Feel free to reopen if it is still an issue.
