### ISSUE TITLE
http://icanhas.cheezburger.com/lolcats won't display certain images.

### ISSUE THREAD

**Issue by MegamanXtreme** [MoonchildProductions/Pale-Moon#1409]
Forum thread in question:
https://forum.palemoon.org/viewtopic.php?p=124491

**Comment by janekptacijarabaci** [comment]
Pushlog
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=9ce31e9f90cb0e534611b0f617c5bbc232ffe748&tochange=ab0044bfa1df858919797bcd6a9aef76a668cd4a

**Comment by wolfbeast** [comment]
Verified fixed with #1410 by merging #1411
