### ISSUE TITLE
Implement DOM methods: prepend(), append(), before(), after() and replaceWith()

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1410]
https://dom.spec.whatwg.org/

> The prepend(nodes) method, when invoked, must run these steps:
>
> Let node be the result of converting nodes into a node given nodes and context object’s node document.
> Pre-insert node into context object before the context object’s first child.

> The append(nodes) method, when invoked, must run these steps:
>
> Let node be the result of converting nodes into a node given nodes and context object’s node document.
> Append node to context object.

> The before(nodes) method

> The after(nodes) method

> The replaceWith(nodes) method

**Comment by wolfbeast** [comment]
Actually, this isn't part of the DOM4 spec (which is a W3C spec that does NOT include these functions).
Specs are in conflict, so websites shouldn't implicitly use this.

**Comment by wolfbeast** [comment]
Verified with lolcatz.

**Comment by wolfbeast** [comment]
Re-opened because of build bustage on gcc/linux. See discussion on PR #1411.
