### ISSUE TITLE
xmlHttpRequest attempts to parse the response when it really shouldn't

### ISSUE THREAD

**Issue by ThosRTanner** [MoonchildProductions/Pale-Moon#1413]
Two slightly separate situations:

1. Firstly, when you get an error back (status >= 400) the response generally seems to contain either an HTML page or plain text
1. Secondly for a 304 status, when the spec says you should return nothing but some sites return a bit of text

In neither of those cases does it make sense to attempt to decode the response as xml - doing so  (a) presumably imposes some sort of overhead and (b) outputs annoying messages on the browser console (especially so in the 2nd case, as an empty response isn't valid xml).

Wouldn't it be possible to do a simple check and just not do anything with the response in those cases.

**Comment by wolfbeast** [comment]
When using XHR, you should _always_ check headers returned with `getResponseHeader()`, and get the MIME type from there (`xhr.getResponseHeader("Content-Type")`). If you fail to do so, then you can expect the browser to assume defaults for the request. An error state's content page for the response can just as well be XML, depending on what server you talk to; assuming it's a web server spitting out an HTML page is a bit short-sighted..

Please see the [XHR spec](https://xhr.spec.whatwg.org/#xmlhttprequest-response) about what is available and what should be used to check headers. They even show examples there. When manually generating a request from a script, it is your own responsibility to do response processing.

As for number 2, it's not our task to compensate for poorly configured servers.

**Comment by wolfbeast** [comment]
Closing based on forum discussion.
