### ISSUE TITLE
Build fails with python-2.7.14

### ISSUE THREAD

**Issue by Bfgeshka** [MoonchildProductions/Pale-Moon#1414]
mach drops building with this error:
```
IOError: poll() gave POLLNVAL or POLLERR
```

More info: https://bugs.gentoo.org/633582

**Comment by walterdnes** [comment]
I've got 2.7.13 (manually installed) in a Centos 6.5 chroot that also dies. It may be the same bug, so I'm piggy-backing. The attached gzipped buildlog is from a failed attempt to build linux unstable 32-bit. An error very early in the build process, but the build appears to continue, and dies later on.

 0:23.16 checking for keytool... /usr/bin/keytool
 0:23.16 <built-in>: fatal error: when writing output to : Broken pipe
 0:23.16 compilation terminated.

buildlog0.txt.gz is attached

[buildlog0.txt.gz](https://github.com/MoonchildProductions/Pale-Moon/files/1389901/buildlog0.txt.gz)

Walter Dnes

**Comment by trav90** [comment]
As stated in the Gentoo bug linked above, it appears python is to blame for this.

@walterdnes the build error you're seeing is completely unrelated to this and instead is due to recent code changes (see #1411).

**Comment by Bfgeshka** [comment]
Well, yes, python to blame, but isn't `mach` guilty aswell? Can this situation be worked around somehow?

2.7.14 is upstream for about a month already, soon other users will fail to compile palemoon more and more often.

**Comment by wolfbeast** [comment]
So, Python breaks their API in a point release, and it's been made our task to compensate?

**Comment by Bfgeshka** [comment]
You're saying it in a way that your answer on your question is "not interested". But then, how are you gonna handle it in the future? Using current toolchain without any further update?

**Comment by wolfbeast** [comment]
Don't read into my expression of disbelief, please.

**Comment by wolfbeast** [comment]
So:
- What exactly changed?
- Why does this impact us?
- Is it Gentoo-specific?
- What needs changing? Can it be done in a way that doesn't break our current toolchain?

**Comment by Bfgeshka** [comment]
I hope that you've got the idea of situation anyway.

I will disable support of 2.7.14 in palemoon ebuilds until further notice.

**Comment by Bfgeshka** [comment]
@wolfbeast no idea what exactly changed, but I haven't noticed any other breakage anywhere else. Checked gentoo bugzilla and found nothing similar.

Here goes release notes page: https://raw.githubusercontent.com/python/cpython/84471935ed2f62b8c5758fd544c7d37076fe0fa5/Misc/NEWS

**Comment by wolfbeast** [comment]
As far as I can gather from data available it trips hard over `while self._pipe.poll(1)` because `1` isn't written as a float (`1.0`). Mozilla dodged this by having a few changes previously that made it written like a float already.

Please let me know if commit f43d521bdaf1c81deeb0645a69e30795a87f5a87 fixes your issue.

**Comment by wolfbeast** [comment]
Ack. pushed to the wrong branch. I meant. Proper commit at master is e6ea83af9ec1eff8f9cced801b63dfa45cf52f03

**Comment by Bfgeshka** [comment]
Build wasn't successfull,

https://gist.github.com/Bfgeshka/8f0dd7c2d3e8f4a08140e0ac944caa27

**Comment by wolfbeast** [comment]
OK, well I'm at a loss then. Someone more familiar with Python will have to look at this, and indicate what exactly the problem is with the `poll()` command as-used.

**Comment by alaviss** [comment]
Also happens on Arch Linux, python 2.17.14

P/s: Bug of interest [1384062](https://bugzilla.mozilla.org/show_bug.cgi?id=1384062)

**Comment by wolfbeast** [comment]
Thanks for finding the (poorly-described) bug. That seems to be exactly what's going on.
So.. Python behaves fundamentally different depending on O.S., and on Linux a pipe isn't actually a pipe... _Wonderful_... :disappointed:

**Comment by wolfbeast** [comment]
@Bfgeshka @alaviss Please let me know if building from tip of master still fails now or if this finally fixes it.

**Comment by trav90** [comment]
Python 2.7.14 is installed on my Manjaro box and I can confirm that commit d3e2e53 fixes this issue. Considering this solved.

**Comment by Bfgeshka** [comment]
Confirming, current master builds fine with python-2.7.14 on Gentoo.
