### ISSUE TITLE
Instagram site hangs browser for 20 second, loads too long

### ISSUE THREAD

**Issue by Yanpas** [MoonchildProductions/Pale-Moon#142]
Instagram site hangs browser for 20 second, loads too long. Firefox deals fine with instagram.com.  (you should be logged in) Version 25.6

**Comment by wolfbeast** [comment]
Bad site design, is what it boils down to -- but there's a workaround for it.

**Comment by wolfbeast** [comment]
This has been addressed. Please verify with v26.0.0 public beta 1?

**Comment by Yanpas** [comment]
Downloaded from here. Still slow ftp://ftp.palemoon.org/

**Comment by wolfbeast** [comment]
So what, exactly, is slow for you, then? Please provide an as-detailed description as possible.

**Comment by Yanpas** [comment]
Here is screenrec with web console https://youtu.be/2FjnB2Gfh84

**Comment by Yanpas** [comment]
I've created instagram account for you 
ed82saqx
qwerty1234
ed82saqx9 at one-time.email

**Comment by wolfbeast** [comment]
OK.. Instagram seems to be doing something really strange regarding network traffic. The timeout you see is the fact that their servers are not responding in a timely fashion to requests, keeping the browser waiting on half-open connections. I'm not sure if I can do much about that -- and it's unrelated to what I initially thought. Specifically, the "instagramstatic-*" at akamai are your initial hangup, and once again shortly after at more similar requests, before the page finally loads.

**Comment by Yanpas** [comment]
I've tested Qupzilla, Epiphany and Midori, they work good with instagram. Don't think such browsers have implemented something special for correct work of instagram. Guess it's palemoon's problem, maybe firefox, from which palemoon was worked works the same bad.
Ouput from qupzilla 
```
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: not all, (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) instagram.com:123
The "fb-root" div has not been created, auto-creating 
```
Output from midori
`The "fb-root" div has not been created, auto-creating`

**Comment by wolfbeast** [comment]
the fb-root remark is irrelevant, so is the css issue.

i don't know what drives Qupzilla, epiphany or midori at the network/core, so those references really don't help me.
It's definitely a server-side issue, but I agree that Pale Moon could potentially handle this situation a little more graceful.

**Comment by squarefractal** [comment]
@Yanpas can you try disabling pipelining and report your results here?

**Comment by Yanpas** [comment]
I've tried, still the same slow
![_2015-08-13_12-47-37](https://cloud.githubusercontent.com/assets/7345761/9247162/92aee86c-41b9-11e5-8567-786ae7a4d4e3.png)

**Comment by wolfbeast** [comment]
is this still an issue in v27 beta?

**Comment by wolfbeast** [comment]
Lacking further feedback or info, considering this resolved by Tycho.
