### ISSUE TITLE
Issues with the context menu in the Downloads Panel

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/Pale-Moon#1427]
## 1) The intricate problem of mouse-hovering

If you use the mouse to select "Remove From History", "Open Containing Folder", "Go To Download Page", "Copy Download Link" context menu items of an entry in the Downloads Panel, clicking won't work on them if hovering (or re-hovering) over the context menu from __outside__ the "good" areas approximately marked out below:

<kbd><img src="https://user-images.githubusercontent.com/26753987/31986275-8a814eb0-b970-11e7-860f-aba275b06782.png" width="411" height="84" alt="A download entry" title="A download entry"></kbd>

Depending on how you move the mouse between the "bad" and the "good" areas and hover over the opened context menu, the 4 items may or may not be actionable, as well as some keys such as <kbd>Delete</kbd> and <kbd>Enter</kbd> may or may not work on the download entry (see the STR for the 2nd issue).

#### Steps to reproduce:

1. Make 2 or 3 savings.
2. Click the icon that invokes the Downloads Panel.
3. Hover the mouse cursor over an upper download entry.
4. Right-click the entry from within its topmost "bad" narrow area (see the picture above) to open the context menu.
5. Hover over the opened context menu from within that area.
6. Move the cursor down to the "Open Containing Folder" item, for example.
7. Click or press it, or press <kbd>Esc</kbd> to turn off the context menu.
8. Move the mouse within the "good" area you are now in, and see that <kbd>Enter</kbd> and <kbd>Delete</kbd> keys don't function within it.
9. Press <kbd>Shift</kbd> + <kbd>F10</kbd> to open the context menu again.

#### Actual result:

The context menu shows up under the bottommost download entry.

#### Expected result:

The context menu should appear under the original entry it belongs to.

#### Steps to reproduce:

1. Save something.
2. Click the icon that invokes the Downloads Panel.
3. Hover the cursor over a download entry.
4. Hover it over the Panel's outer white border surrounding the downloads.
5. Right-click the border or press <kbd>Shift</kbd> + <kbd>F10</kbd> to open the context menu.

#### Actual result:

<img src="https://user-images.githubusercontent.com/26753987/31986299-a68e157a-b970-11e7-8d12-c9d4fb9b64cd.png" width="178" height="72" alt="Actual result" title="Actual result">

This happens once per browsing session, and it can be avoided/repaired by either opening the download's context menu or by re-opening the Panel and repeating the steps 4 and 5, but skipping the step 3.

#### Expected result:

<img src="https://user-images.githubusercontent.com/26753987/31986312-b1273f34-b970-11e7-8e19-1c70bb0a1f5d.png" width="184" height="110" alt="Expected result" title="Expected result">

...or maybe a _border_ doesn't need a context menu, at all.

#### Steps to reproduce:

1. Make 2 or 3 savings.
2. Click the icon that invokes the Downloads Panel.
3. Hover the mouse cursor over a download entry.
4. Right-click it or press <kbd>Shift</kbd> + <kbd>F10</kbd> to open the context menu.
5. Leaving the menu open, hover the cursor over another download.
6. Press one of the above-mentioned 4 context menu items.
_<b>Note:</b> it might be easier to interact with the context menu using the keyboard, bearing in mind the offending areas._

#### Actual result:

The action was applied to another download.

#### Expected result:

The action should be applied to the original one.

## The cause

[Bug 851519](https://bugzilla.mozilla.org/show_bug.cgi?id=851519) - <q>Keyboard commands may apply to the wrong downloads panel entry</q>.

`FF 23 Central:`
* Last good: [23.0a1 (2013-04-17)](https://hg.mozilla.org/mozilla-central/rev/50ab959f4bd1) — First bad: [23.0a1 (2013-04-18)](https://hg.mozilla.org/mozilla-central/rev/3ada6a2fd0c6) — [Pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=50ab959f4bd1&tochange=3ada6a2fd0c6)
* [Changeset 129077](https://hg.mozilla.org/mozilla-central/rev/63c003375416) - <q>Keyboard commands may executed on the wrong download in the panel</q>.</li></ul>

`FF 22 Aurora:`
* Last good: [22.0a2 (2013-04-19)](https://hg.mozilla.org/releases/mozilla-aurora/rev/29961e1f97e6), [files](https://archive.mozilla.org/pub/firefox/nightly/2013/04/2013-04-19-00-40-13-mozilla-aurora/) — First bad: [22.0a2 (2013-04-20)](https://hg.mozilla.org/releases/mozilla-aurora/rev/29579236eefc), [files](https://archive.mozilla.org/pub/firefox/nightly/2013/04/2013-04-20-00-40-13-mozilla-aurora/) — [Pushlog](https://hg.mozilla.org/releases/mozilla-aurora/pushloghtml?fromchange=29961e1f97e6&tochange=29579236eefc)
* [Changeset 133446](https://hg.mozilla.org/releases/mozilla-aurora/rev/85f86270a707) - <q>Keyboard commands may executed on the wrong download in the panel</q>.</li></ul>

**Comment by janekptacijarabaci** [comment]
Ad 1), 3) and 4)
This issue fixes: https://bugzilla.mozilla.org/show_bug.cgi?id=950058

**Comment by Lorienna** [comment]
@janekptacijarabaci 

The thing is that by the time that patch was committed, the Downloads Panel had already been redesigned:

<table>
<tr><td align="center">Last with old design: <a href="https://hg.mozilla.org/mozilla-central/rev/f03e2740d604d339ed553dad62a3fc54c317f8fa">52.0a1 (2016-10-13)</a></td>
<td><a href="https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=f03e2740d604d339ed553dad62a3fc54c317f8fa&tochange=1391a2889aeb2bdd61ad6ef838e65826e35aabc2">Pushlog</a></td>
<td align="center">First with new design: <a href="https://hg.mozilla.org/mozilla-central/rev/1391a2889aeb2bdd61ad6ef838e65826e35aabc2">52.0a1 (2016-10-14)</a></td></tr>
</table>

As a result of the redesign, the "bad" area had shrunk to a 1-pixel border between the download entries, the 3rd issue had become irrelevant, and the STR for the rest, too, had changed a little, so I was having my doubts here.

But __please don't hesitate to make a pull request if the patch works for you!__ ;)
