### ISSUE TITLE
Beta Hotmail not fully functionable in Pale Moon unstable

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1433]
As the topic said, while the "normal" Hotmail variant works without issues, it is impossible to move the cursor with the cursor keys inside a written mail text, the buttons for text formatting are not working, it is not possible to mark text which was written for example.

Checked the error console and found only 2 things inside, perhaps someone can bring a bit light into that darkness :D

Timestamp: 29.10.2017 11:04:46
Error: Error: Cache timeout must be a positive number
Source File: https://ow1.res.office365.com/owamail/20171027.02/scripts/owa.SearchActions.js
Line: 1

Timestamp: 29.10.2017 11:04:32
Error: XML Parsing Error: no root element found
Location: https://outlook.live.com/mail/bootr.ashx?bret=ok&app=Mail&cId=A413C97F4FC04F7BBB8C20A9A1295ADD&cver=20171027.02&csev=AM5PR0602MB3284&dag=EURPR06DG206&fost=eurprd06.prod.outlook.com&fe=AM0PR0202CA0014&be=AM5PR0602MB3284&cbe=AM5PR0602MB3284.eurprd06.prod.outlook.com&wsver=15.20.178.11&te=1&puid=00016170A0A4D948&tid=84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa&mbx=00016170-a0a4-d948-0000-000000000000&prem=0&br=0&ns=1509271467950&ues=216&uee=658&fs=102&dls=102&dle=102&cs=102&ce=102&reqs=102&ress=215&rese=253&doml=216&domcles=3204&domclee=3204&nt=0&redc=0&pe=2258&pltnav=3503&pltnonav=2788
Line Number 1, Column 1:
Source File: https://outlook.live.com/mail/bootr.ashx?bret=ok&app=Mail&cId=A413C97F4FC04F7BBB8C20A9A1295ADD&cver=20171027.02&csev=AM5PR0602MB3284&dag=EURPR06DG206&fost=eurprd06.prod.outlook.com&fe=AM0PR0202CA0014&be=AM5PR0602MB3284&cbe=AM5PR0602MB3284.eurprd06.prod.outlook.com&wsver=15.20.178.11&te=1&puid=00016170A0A4D948&tid=84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa&mbx=00016170-a0a4-d948-0000-000000000000&prem=0&br=0&ns=1509271467950&ues=216&uee=658&fs=102&dls=102&dle=102&cs=102&ce=102&reqs=102&ress=215&rese=253&doml=216&domcles=3204&domclee=3204&nt=0&redc=0&pe=2258&pltnav=3503&pltnonav=2788
Line: 1

**Comment by wolfbeast** [comment]
Can you please see if the 2017-10-31 unstable works for you?

**Comment by Sa-Ja-Di** [comment]
Works, can format text and use the buttons and can jump around in my written text, thanks :)
