### ISSUE TITLE
Mono audio only plays on the left channel on multichannel devices

### ISSUE THREAD

**Issue by elvissteinjr** [MoonchildProductions/Pale-Moon#1437]
Seems to affect 5.1 soundcards and headsets with virtual surround sound on Windows at the very least. May not be reproduceable on all hardware setups.

Was fixed in Firefox 40: https://bugzilla.mozilla.org/show_bug.cgi?id=979705

It's a bit of an annoyance, so it would be nice if the patch could be applied to pale moon as well.

**Comment by wolfbeast** [comment]
Easy, low-risk patch. I'm surprised Mozilla dragged their feet so long on that bug.
I'll have this in the tree in a jiffy.
