### ISSUE TITLE
Facebook videos don't play well

### ISSUE THREAD

**Issue by badnick1** [MoonchildProductions/Pale-Moon#1441]
Very long buffer untill starts and many interruptions during playback. Some videos don't work if the option "HD" is checked or, opposite, some don't work if "HD" is unchecked.
Tests made on clean profile.
About the same behavior as on release 27.5.1/64

OS=Win 10/64
PM-portable 27.6.0a1 (64-bit) (2017-10-31)

**Comment by wolfbeast** [comment]
I don't experience any buffering issues so I don't necessarily think that this would be a browser bug, but rather something with your local network.

**Comment by badnick1** [comment]
If there were problems with the network then it happens with other browsers or other pages, but is not. I have this kind of issue only with PaleMoon and Facebook (or other page containing some kind of embeded videos). For example  videos from Tweetter plays very well with PM. Take a little time to watch this:
https://sendvid.com/0uqil32v

**Comment by wolfbeast** [comment]
It seems your particular problem isn't so much buffering as it is not looping at the END of the video.
This probably has to do with the state machinery @trav90 is working on.

**Comment by badnick1** [comment]
It is a strange issue, with 27.5.1 happens mostly near start after few seconds. Now is opposite.

**Comment by wolfbeast** [comment]
Assuming this will be solved by Pale Moon on UXP.
