### ISSUE TITLE
Dragging icons from or on toolbar layout is causing disappearance of others icons from navigation toolbar

### ISSUE THREAD

**Issue by badnick1** [MoonchildProductions/Pale-Moon#1442]
https://sendvid.com/f2xsu5lh

Win 10/64
PM -portable 27.7.0a1 (64-bit) (2017-11-02)

**Comment by JustOff** [comment]
I'm pretty sure this is caused by some of the add-ons installed. Try to disable or install them one by one on a clean profile until you find the culprit.

**Comment by janekptacijarabaci** [comment]
> I'm pretty sure this is caused by some of the add-ons installed. Try to disable or install them one by one on a clean profile until you find the culprit.

AFAIK it is different...

See:
https://forum.palemoon.org/viewtopic.php?f=3&t=17107&p=125286#p125286
and
https://github.com/MoonchildProductions/Pale-Moon/blob/27.5.1_Release/browser/base/content/browser.css#L155

A "solution" (e.g.) - `userChrome.css`:
```
#urlbar-container[combined] + #reload-button + #stop-button,
  visibility: visible !important;
}
```

All these (default) buttons (before, forward, reload, stop, bookmarks...) have their rules...

**Comment by badnick1** [comment]
I have no one addon installed. Is clean default profile. I  just put  PM unstable in my PC  2 days ago just for tests, my main browser is 27.5.1. The only things I installed was some themes from PM site but I removed them.

**Comment by JustOff** [comment]
Hm... I probably missed that the issue is only about stop/reload buttons, is it so?

**Comment by badnick1** [comment]
Yes, after I checked again, is about those 2 buttons. But if I insert some separators seem they do not disappear anymore.

**Comment by JustOff** [comment]
Well, then this is by design, I'm surprised you paid attention to it just now. There are three ways to change this behavior:
* Swap the order of stop and reload buttons
* Use css provided by @janekptacijarabaci
* Install [Active Stop Button](https://addons.mozilla.org/addon/active-stop-button/) (it also makes the stop button always available to use)

**Comment by badnick1** [comment]
I thought it was a bug. So, case closed.

**Comment by JustOff** [comment]
So, press the close button :sunglasses:
