### ISSUE TITLE
Inform our contributors of guidelines

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1443]
Using this issue as a vessel to make active contributors aware of preferred organization of issues and pull requests.

@janekptacijarabaci @JustOff @trav90 @mattatobin @Lootyhoof @adisib @Axiomatic- @chaoskagami @FranklinDM @Gpower2 @MingcongBai @rhinoduck @stevenschlansker please take a moment to read the document at https://github.com/MoonchildProductions/Pale-Moon/wiki/Code-contribution-guidelines, thanks!

**Comment by adisib** [comment]
Are there any preferences on coding style? e.g. tabs vs space, Hungarian Notation good or bad, should flow control structures that only have a single statement in their scope always include braces, etc...

**Comment by mattatobin** [comment]
My opinion is use prevailing code style in the file you are working with.. When in doubt use Mozilla coding style at https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style

This will need ported to our wiki along with other repo wiki documents one of these years.

**Comment by JustOff** [comment]
> Issues should be [...] properly labeled

Since contributors have no rights to assign labels what does this rule mean in practice?

**Comment by mattatobin** [comment]
We with, will assign but if a contributor suggests ones it could be helpful.. That is what @janekptacijarabaci has been doing.

**Comment by JustOff** [comment]
Could you please clarify what is the recommended procedure of submitting pull requests according this guideline? Should we just create them in pair with corresponding issues or is it necessary to do it sequentially according with certain rules?

**Comment by mattatobin** [comment]
Did you read the guidelines?

**Comment by wolfbeast** [comment]
I've added a brief coding style guideline to it as well, now.

@JustOff Please re-read the guidelines. PRs should have an accompanying Issue. Don't create a PR unless there's an Issue to go with it (with the exception of minor edits)
