### ISSUE TITLE
[minor] Throws an error in Browser Console after update on version 27.6

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1448]
__Actual results:__
```
formatURLPref: Couldn't get pref: app.update.url.details
nsURLFormatter.js:135:0
```
`about:config`
`app.update.url.details` - it doesn't exist

---
__Expected results:__

[no errors]

`about:config`
`app.update.url.details` - I suppose it should exist this value

---
See also:
https://github.com/MoonchildProductions/Pale-Moon/commit/117926d02604304018798d39792644b84eb58b53

**Comment by wolfbeast** [comment]
It's of no consequence, really.

**Comment by wolfbeast** [comment]
What operating system are you using?
