### ISSUE TITLE
Build failure in BatteryManager.cpp with gcc-7.2 on Linux

### ISSUE THREAD

**Issue by Hoshpak** [MoonchildProductions/Pale-Moon#1449]
I tried to build Pale Moon on Void Linux following the [build instructions](https://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/Linux) from the wiki except for the fact that I am using gcc-7.2 instead of the recommended versions. The build fails while building BatteryManager.cpp ([relevant part of the build log](https://pastebin.com/f2NzwDVh)). I tried to execute the command manually and received [this](https://pastebin.com/GJYK143i) from the compiler.

The issue at least at first glance resembles [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1269171).

**Comment by wolfbeast** [comment]
GCC 7.* is not supported. it's know to not build.
