### ISSUE TITLE
Improve Windows 10 start tile appearance

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#1450]
On Windows 10 the start tile for Pale Moon (for either official or unofficial/unstable branding) uses a generic styling given by Windows, that has a rather small icon take up a large space. Firefox and other Mozilla applications use this more effectively. See below:

![Windows 10 start tiles](https://i.imgur.com/sTA4Fhh.png)

To improve this I suggest we add logos and a background colour (all that is available to us by Windows 10).

The initial Firefox implementation was in [1232679](https://bugzilla.mozilla.org/show_bug.cgi?id=1232679), with further icon size adjustments made in [1284829](https://bugzilla.mozilla.org/show_bug.cgi?id=1284829) (to fix alignment) and [1283909](https://bugzilla.mozilla.org/show_bug.cgi?id=1283909) (to improve HiDPI compatibility). For this we will need correctly sized logos (to add into `VisualElements_150.png` and `VisualElements_70.png`), and a background colour of choice (to add into `firefox.VisualElementsManifest.xml` (depending whether you want to change `firefox` to `palemoon`, of course). We can only select `dark` or `light` text for the tile text colour.

Further information: https://msdn.microsoft.com/en-us/library/windows/apps/dn393983.aspx

**Comment by Lootyhoof** [comment]
Addition: Looks like a typo in the filename for the logos in `firefox.VisualElementsManifest.xml` was fixed in [124827](https://bugzilla.mozilla.org/show_bug.cgi?id=1284827). There doesn't appear to be anything else related to this that needs to be looked into.

**Comment by wolfbeast** [comment]
FYI: The file should be called `{appname}.VisualElementsManifest.xml`, where `{appname}` is the name of the executable that should be referenced. So in our case it definitely MUST be `palemoon`.
