### ISSUE TITLE
Twitch controls disappearing

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1451]
Visiting Twitch.tv but not logging in, clicking on a random video on the start page, pressing then settings button and video controls disappear.

Using the latest unstable.

Error console puts out this one:

Timestamp: 08.11.2017 22:24:20
Error: TypeError: Property 'handleEvent' is not callable.

https://forum.palemoon.org/viewtopic.php?f=3&t=17149&p=126458&hilit=twitch#p126458

**Comment by wolfbeast** [comment]
Twitch has updated their player which resolves this issue.
