### ISSUE TITLE
[regression] Pale Moon launches twice

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1452]
See also:
https://forum.palemoon.org/viewtopic.php?f=3&t=17284

__Steps to reproduce (Windows):__
- The menu: `Tools` - `Options` - `[ ] Open new windows in a new tab instead` (is not checked)

- Run the Command line
`"[drive]:\[path]\palemoon.exe" "http://www.palemoon.org/"`
The first run: OK
The second run:
1) Pale Moon launches twice (two windows)
2) Throws an error in Browser Console:
```
TypeError: newWindow.isBlankPageURL is not a function
browser.js:10801:12
```

---

Affected versions (stable):
27.6.0

See:
https://github.com/MoonchildProductions/Pale-Moon/issues/1386
https://github.com/MoonchildProductions/Pale-Moon/commit/babcb02fb7d0133a589871715f552c8fa907dd20
(after the regression - OK = only one window)

**Comment by wolfbeast** [comment]
Can you please clarify what you mean with "after the regression - OK = only one window"? because I'm confused if there is a bug or not, now.

**Comment by janekptacijarabaci** [comment]
"after the regression" = "after deleting these lines" ("after deleting this commit"):
https://github.com/MoonchildProductions/Pale-Moon/commit/babcb02fb7d0133a589871715f552c8fa907dd20#diff-cef53509552274ae809ff183f3394680R4247
(no errors, only one window)

**Comment by wolfbeast** [comment]
So you meant to say "after backing this out". ;)
