### ISSUE TITLE
Problem with event.dataTransfer.files

### ISSUE THREAD

**Issue by deb00t** [MoonchildProductions/Pale-Moon#1453]
Drag and drop of binary files doesn't seem to work with 27.6
Been using **event.dataTransfer.files** to get dropped file objects, but it returns **null** now.
Found a workaround using **event.dataTransfer.mozItemCount** (which correctly returns number of dropped files) and successively **event.dataTransfer.getDataAt** to get the files, but **getDataAt** doesn't correctly return value for octet stream mime type.

**Comment by janekptacijarabaci** [comment]
Confirmed. For 27.6.0+. I don't have more information yet...

**Comment by deb00t** [comment]
It does work in HTML mode, not so in XBL.
Anyway, got over this by not using **application/x-moz-file** as the data flavour. With **text/x-moz-url** I at least get the file's url.
Now I'm stuck at
```
var file = Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);
file.initWithPath(path);
```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsILocalFile.initWithPath]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame ..."  data: no]

By using the file instance instead of a file url, this wasn't an issue :/

**Comment by wolfbeast** [comment]
Please test in UXP (Unstable) and if still problematic, open a new issue on UXP.
