### ISSUE TITLE
DOM - XMLHttpRequest - the synchronous mode - withCredentials

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1455]
Ad https://forum.palemoon.org/viewtopic.php?f=29&t=17203

__Steps to reproduce:__

Go to: https://devtalk.nvidia.com/

> At first, the login form appears to work, but then once you pressed the login button in the form, you are left still un-logged on the site and cannot attempt another relog before first clearing all cookies.

__Actual results (Browser Console):__
Throws an errors:
```
Use of XMLHttpRequest's withCredentials attribute is no longer supported
in the synchronous mode in window context.
dz-auth.js:134:0

InvalidAccessError: A parameter or an operation is not supported by the underlying object
dz-auth.js:134:0
```

__Expected results (Browser Console):__
`Checking if the user is logged in...` (still)

See (this specification has been modified):
https://github.com/whatwg/xhr/commit/90d7058031aca487f4480be07dc26cefbc4103c4

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1260515

An example (for Scratchpad):
``` javascript
var xhr = new XMLHttpRequest()
xhr.open("GET", "https://www.palemoon.org/", false)
xhr.withCredentials = true;
```

__Affected versions:__
all

**Comment by wolfbeast** [comment]
Verified it no longer throws.
Requested verification in the wild with build 2017.11.10.1420 or later

**Comment by wolfbeast** [comment]
Rationale: We were spec compliant before. Unfortunately all browsers but Firefox failed to implement the
standard properly, so ultimately, the spec was changed to allow `withCredentials` in synchronous mode. This does not change the fact that synchronous XMLHttpRequest is deprecated.

**Comment by wolfbeast** [comment]
Verified: https://forum.palemoon.org/viewtopic.php?f=29&t=17203#p126786
Closing
