### ISSUE TITLE
forum inaccessible

### ISSUE THREAD

**Issue by joey04** [MoonchildProductions/Pale-Moon#1457]
For at least a week I've been unable to access the forum:

```
Pinging forum.palemoon.org [144.217.16.169] with 32 bytes of data:
Request timed out.
Request timed out.
```

But the main site and app update checks are fine:

```
Pinging palemoon.org [104.20.60.158] with 32 bytes of data:
Reply from 104.20.60.158: bytes=32 time=19ms TTL=55
Reply from 104.20.60.158: bytes=32 time=21ms TTL=55
```

I don't recall having any type of problem like this in many years of being online. Is this a problem with my ISP's DNS or is it something on Pale Moon's side?

**Comment by wolfbeast** [comment]
If you can't ping the server, then there's a problem with your ISP's routing. You should be able to ping it.
Of note, the web server and forum server are not the same (as you can see by IP, if anything).

**Comment by joey04** [comment]
Definitely a problem with my ISP. I confirmed I can access the forum from a different computer with a different ISP, and the forum is the same IP address as above.
