### ISSUE TITLE
DOM - Buttons - Events - calling focus() from a focus handler

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1460]
Ad https://forum.palemoon.org/viewtopic.php?f=12&t=17324

__Steps to reproduce:__
Go to: https://www.pinterest.com/
Sign in to the site

__Actual results:__
Click the search box does not work

__Expected results:__
Click the search box works

__Affected versions:__
all

**Comment by wolfbeast** [comment]
The funny thing is, the test cases (both the one on the bugzilla bug and the fiddle) work for me in the release version of Pale Moon. I click the button and the input gets focus, and typing will type in the input.

So, what exactly is the bug that needs fixing?

**Comment by janekptacijarabaci** [comment]
See an example in: https://github.com/MoonchildProductions/Pale-Moon/pull/1461

> I don't have a pinterest account

Setting up free user account is a matter of minutes: Click the search box does not work
But... I can create an animated gif.

**Comment by wolfbeast** [comment]
Like I said, the fiddle (example) works just fine as well for me.
It does jumps back and forth twice between the button and the input; is that the bug that makes the issue occur on pinterest?

**Comment by JustOff** [comment]
In my case the fiddle ([example](https://jsfiddle.net/68rw9cL2/8/)) produces the following results when I press the button:

PM: Focus on button -> Focus on input -> Blur on input -> Focus on button -> Focus on input
FF: Focus on button -> Focus on input

**Comment by janekptacijarabaci** [comment]
> It does jump back and forth twice between the button and the input; is that the bug that makes the issue occur on pinterest?

IMHO yes. This events (onClick - with `e.stopPropagation()` and `e.preventDefault()`; onFocus) are used on the button and it just does not work.

**Comment by wolfbeast** [comment]
Verified after patching that the double focus change no longer occurs. Closing.

**Comment by mattatobin** [comment]
Are there any repercussions to extensions?

**Comment by wolfbeast** [comment]
There shouldn't be any issues for extensions - essentially the behavior hasn't changed, it just works more reliably now without the double flipping.

**Comment by mattatobin** [comment]
Understood and thanks :)
