### ISSUE TITLE
DevTools - gcli - screenshot - the vertical mode

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1466]
__Steps to reproduce:__
Go to: http://www.asahi-net.or.jp/~sd5a-ucd/freefonts/Oradano-Mincho/
(CSS: `writing-mode: vertical-rl`)
Open: `Tools - Web Developer - Developer Toolbar`
Insert this command: `screenshot --fullpage`

__Actual results:__
The screenshot is cut off (+ the black color).

__Expected results:__
The screenshot is complete.

__Affected versions:__
all (i.e. Firefox trunk; I'm creating an ticket - afterwards...)

**Comment by wolfbeast** [comment]
Merged in.
