### ISSUE TITLE
Remove "Ask me every time" cookies option.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1475]
People still trying to use this option in 2017 will likely end up with a cookie confirmation dialog storm that can end up with the browser being locked (modal dialog storm + confused z-order in some window managers = inaccessible UI). This is a terrible footgun, and cookie acceptance is best controlled with one of the many extensions available for this purpose.

This will need:
- Removal the backend code related to `ASK_BEFORE_ACCEPT` cases.
- Adding comments reserving value 1 not to be used in the future (in `idl` , `nsCookiePermission.cpp` files)
- Treating `ASK_BEFORE_ACCEPT` like `ACCEPT_NORMALLY` (in favor of trying to migrate prefs messily)
- Removal of the exposed UI option to set this destructive value.

**Comment by JustOff** [comment]
I predict a lot of butthurt when it's done :stuck_out_tongue_winking_eye:

**Comment by wolfbeast** [comment]
Yeah, people will just have to get over it.

**Comment by JustOff** [comment]
Strings changes were pushed to CrowdIn.

**Comment by h1z1** [comment]
For a second I thought this came from Mozilla, it's certainly something they'd pull.   Why on earth would this be removed?   If someone goes through the trouble of using that option, they're aware of the impact.

The cookie "storm" will still happen for several reasons, one of which are parallel connections.   Why prompts were never made as one dialog I'll never understand.
