### ISSUE TITLE
Add "My home page" option for new tab url

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1482]
Setting the newtab URL to the user's set home page is an often-requested feature. This blocks on the fact that the home page can be complex (including multiple tabs) and needs a way to properly handle custom URLs (when set in `about;config`) in the UI.

Making this a sanitized version, stripping anything but the first entry, should work, though, but will require a bit of tinkering with strings.

**Comment by JustOff** [comment]
Strings changes were pushed to CrowdIn.
