### ISSUE TITLE
Add an option and enable it by default - Detect and terminate Cloudflare connection as insecure

### ISSUE THREAD

**Issue by AmACloudflared** [MoonchildProductions/Pale-Moon#1486]
https://github.com/mozilla-mobile/focus-android/issues/1743
More details above.

If Cloudflare's header is found in response, raise "Insecure connection"(like self-signed cert) error.
Both protocol, HTTP - HTTPS, should be terminated.

**Comment by JustOff** [comment]
Sorry, but this is utter nonsense.

**Comment by wolfbeast** [comment]
So, you want our users to not be able to visit any of the millions of Cloudflare-backed sites XD

Most CF users will use the flexible HTTPS-option and will not have own SSL certificates. In addition, CF also issues individual certificates to paying members and they use trusted CA signers. Doing this would impact millions of CF sites around the globe; it's clearly a crusade against CloudFlare started by disgruntled TOR users about being challenged by CF's captcha policy for TOR traffic and has no valid background other than political.
