### ISSUE TITLE
Issue with a site element

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1487]
see that topic here:

https://forum.palemoon.org/viewtopic.php?f=3&t=17459

Topic opener has the problem that the map on that link is only half shown:

 http://downdetector.fr/statut/bouygues-telecom/carte/

Same result here, using latest unstable.

**Comment by janekptacijarabaci** [comment]
(copied) Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1a157155a4fe0074b3d03b54fe9e466472c2cd56&tochange=f7b746b4e91307448cb0746a41f677bfc23908b0

I don't see the obvious cause...

**Comment by wolfbeast** [comment]
There's a whole bunch of:

```
22:52:28.651 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://v-tiles2.downdetector.com/planet_2016-06-20_7088ce06a738dcb3104c769adc11ac2c_z0-z8/4/9/5.pbf. (Reason: CORS request failed).1 <unknown>
```

So it's likely got something to do with CORS.

**Comment by Lorienna** [comment]
- Pushlog - https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=c70e4ab053432b5e11fccd2a91bdeeb78021568d&tochange=ae826f6849c430ad1c32f5e1c89c4fb5aaa44831

- [Bug 1182571](https://bugzilla.mozilla.org/show_bug.cgi?id=1182571) - Use `channel->asyncOpen2` in `/dom/base/nsXMLHttpRequest.cpp`

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
