### ISSUE TITLE
strange error message in the error console

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1488]
Since the latest unstable i get quite a lot of these here in the error console:

Error: The resource from “whatever” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

For example the page 

http://pamelageller.com/

was shown before that new unstable without issues - now it looks really destroyed.

**Comment by Sa-Ja-Di** [comment]
Also present for example when visiting google mail - hangout part can't be loaded because of that error as it seems ;)

Timestamp: 21.11.2017 21:34:39
Error: The resource from “https://hangouts.google.com/webchat/u/0/host-js?prop=gmail&b=1&zx=jf5doscmkcnf” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).
Source File: https://mail.google.com/mail/u/0/#inboxLine: 0

**Comment by JustOff** [comment]
> http://pamelageller.com/

There actually are answers with `text/html` MIME type for css and js and `XCTO: nosniff`, this requires further investigation.

**Comment by wolfbeast** [comment]
Yeah it looks like we're following the spec, but it's breaking the web. text/html is incorrect for js and css.
I don't see this issue in Basilisk, so either it was disabled again in Firefox after it landed, or it was changed to be more lenient?

**Comment by JustOff** [comment]
I'll look into it tomorrow.

**Comment by Sa-Ja-Di** [comment]
just saying, it affects also the Pale Moon board itself, see here ;)

https://forum.palemoon.org/viewtopic.php?f=17&t=17471

**Comment by wolfbeast** [comment]
The forum doesn't always send a content-type header. Seems if it's missing, it will be considered "wrong type"

**Comment by JustOff** [comment]
At first glance the problem occurs on 30x responses, I'll re-check the implementation.

**Comment by wolfbeast** [comment]
Indeed, it seems to all be redirects.
At the very least the empty content-type can be solves with a simple `.IsEmpty()` check on contentType after getting it from the headers, and returning an OK in that case (if there's no `content-type`, then `nosniff` is pointless and the load should be allowed). I'll add a commit for that on #1343 and push out a new unstable overnight.

**Comment by JustOff** [comment]
> At the very least the empty content-type can be solves with a simple .IsEmpty() check on contentType after getting it from the headers, and returning an OK in that case

This will not help with http://pamelageller.com/ and in general ...

**Comment by wolfbeast** [comment]
No, it won't help there, but these are two distinct issues: empty content-type and redirects with a wrong content-type on the redirect itself.
We probably should not check XCTO at all when it's a redirect; it's probably not very useful. I think inthe case of the Galler site it's defaulting in the web front-end to text/html (that's Apache for you) and the redirect is blocked as a result (while the actual document load might still have the correct type, but we never get there).
