### ISSUE TITLE
Windows 10 caption buttons are larger than the cutouts

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#149]
On Windows 10, the caption buttons were made larger, so they no longer fit in the cutouts available anymore. On Firefox, this was worked around by adding a grey background and placing some caption button images where they normally would be, effectively hiding the system ones. This requires changes in both the theme(s) and code.

BMO: [1173725] (https://bugzilla.mozilla.org/show_bug.cgi?id=1173725).

**Comment by wolfbeast** [comment]
BMO bug is clearly completely unusable because of UX/CustomizableUI refactoring.

**Comment by Lootyhoof** [comment]
Additional BMOs:

[1184934] (https://bugzilla.mozilla.org/show_bug.cgi?id=1184934) - [Windows 10] Add different SVG files for lightweight theme support for the caption buttons
[1178548] (https://bugzilla.mozilla.org/show_bug.cgi?id=1178548) - Clean up more SVGs 

One to watch potentially:

[1196266] (https://bugzilla.mozilla.org/show_bug.cgi?id=1196266) - Firefox title bar should pick up the Windows 10 accent color when in the foreground

**Comment by wolfbeast** [comment]
I looked at what FF did for reworking the icons, and they went from anaemic to fugly, cutting corners having inverted ones on light LWTs as well. I'll look at redesigning my own icons for LWTs

**Comment by Lootyhoof** [comment]
I suspect that's to increase clarity given some LWTs use a range of colours, though I'll admit it still doesn't look great.

**Comment by wolfbeast** [comment]
I think the current solution is complete, closing this issue.

**Comment by Lootyhoof** [comment]
Poking this issue again due to conflict over the use of "hard-coded" window colours that conflict with window stylings in Windows 10 as of late. It appears that the following [userstyle](https://userstyles.org/styles/126206/simple-white-theme-windows-10-colored-titlebar) largely solves the issue, though, as we can't detect a dark theme (see #219), it won't look right on a dark theme (for the record, this is currently an issue on Windows 8 anyway, as that can also have dark windows, and we don't control `#main-window` colouring there).
