### ISSUE TITLE
[FIXED] Subtitles on TED

### ISSUE THREAD

**Issue by sergeevabc** [MoonchildProductions/Pale-Moon#1492]
Windows 7 x64, PM 27.6.1

1. Play [some talk][1] on TED.
2. Subtitles are not displayed, although switched on.

I tried to spoof user agent string with the help of [HeaderControlRevived][2] extension:
```Mozilla/5.0 (Windows NT 6.1; rv:48.0) Gecko/20100101 Firefox/48.0``` made no difference.

Should be fixed here or there?

P.S. Basilisk, if it matters, displays subtitles without a hassle.

[1]: https://www.ted.com/talks/barry_schwartz_on_the_paradox_of_choice
[2]: https://addons.mozilla.org/en-US/firefox/addon/headercontrolrevived/

**Comment by wolfbeast** [comment]
Latest unstable should fix this. Could you please verify?

**Comment by sergeevabc** [comment]
It works as expected under conditions you mentioned, sir.

**Comment by sergeevabc** [comment]
This fix is not included in the recent 27.6.2, right?
