### ISSUE TITLE
HTML - editor (improvements)

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1498]
## 1) Wrong font

- https://bugzilla.mozilla.org/attachment.cgi?id=8721897
Actual results:
![001_no](https://user-images.githubusercontent.com/2373486/33227259-848839aa-d19f-11e7-92ea-3fbb02c825a1.png)
Expected results:
![001_yes](https://user-images.githubusercontent.com/2373486/33227261-8ff26892-d19f-11e7-9e10-32db8da338b5.png)

## 2) Wrong font

- https://bugzilla.mozilla.org/attachment.cgi?id=8575532
Actual results:
![003_no](https://user-images.githubusercontent.com/2373486/33227268-a0f52b7a-d19f-11e7-8101-264141b96668.png)
Expected results:
![003_yes](https://user-images.githubusercontent.com/2373486/33227269-a6735748-d19f-11e7-97f5-b894f0747fe7.png)

## 3) Wrong cursor position

- https://bugzilla.mozilla.org/attachment.cgi?id=8731471
Actual results:
![002_no](https://user-images.githubusercontent.com/2373486/33227262-964bbb3a-d19f-11e7-90bf-5282f31c848f.png)
Expected results:
![002_yes](https://user-images.githubusercontent.com/2373486/33227266-9b2806fe-d19f-11e7-923c-2ceb5c715d08.png)

## 4) Wrong selection of the word

about:config
`layout.word_select.eat_space_to_next_word` = `true`

__Steps to reproduce:__
Try to create empty html file. Insert a div with contenteditable attribute set to `true`.
After created div please insert some html node, it can be span.
Write some random text in contenteditable div. Try to select subsequent words with ctrl+shift+right arrow key shortcut and deselect them in ctrl+shift+left arrow.
You have this situation recreated in simple js fiddle:
https://jsfiddle.net/yszqhoz3/1/

__Actual results:__
Last word cannot be selected with ctrl+shift+right arrow.

__Expected results:__
Last word should be properly selected just as previous words.

**Comment by wolfbeast** [comment]
May I please remind you _yet again_ of the "one bug, one issue" guideline?
Having changes lumped together like this makes it very difficult to pinpoint causes of bugs later on. Where-ever possible, split bug out into separate issues with their own PR.

**Comment by wolfbeast** [comment]
Merged in the batch, please add details as requested.

**Comment by wolfbeast** [comment]
PR was backed out due to build bustage.

**Comment by janekptacijarabaci** [comment]
> May I please remind you yet again of the "one bug, one issue" guideline?

Those are issues that are very much related. I'll try to separate it on my head...

**Comment by wolfbeast** [comment]
I understand if they are related, and touching the same pieces of code, but it makes it harder to deal with any issues that might come up in the future. If there's a problem (e.g. a regression that causes something critical like a crash) with ONE of the things that were fixed with this batch, how would we know what to back out or what code to look at? I've tried to explain this to you before already -- Please do keep things separated, I can't stress it enough.

**Comment by janekptacijarabaci** [comment]
IMHO solved.
