### ISSUE TITLE
recent git build fail on fedora 21

### ISSUE THREAD

**Issue by kuh3h3** [MoonchildProductions/Pale-Moon#151]
failed version 
commit e75cb13dbfef8b2c3bfc54c33e7b197f415cc52d

c++ -o nsXPCOMGlue.o -c  -I../../../dist/system_wrappers -include /home/reandr/pm-build/pmsrc/config/gcc_hidden.h -DMOZ_GLUE_IN_PROGRAM -DNO_NSPR_10_SUPPORT -DXPCOM_GLUE -DTARGET_XPCOM_ABI=\"x86-gcc3\" -I/home/reandr/pm-build/pmsrc/xpcom/glue/standalone/../../build  -I/home/reandr/pm-build/pmsrc/xpcom/glue/standalone -I. -I../../../dist/include  -I/home/reandr/pm-build/pmbuild/dist/include/nspr -I/home/reandr/pm-build/pmbuild/dist/include/nss       -fPIC  -Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Wtype-limits -Wempty-body -Wsign-compare -Wno-invalid-offsetof -Wcast-align -fno-exceptions -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -std=gnu++0x -pthread -pipe  -DNDEBUG -DTRIMMED -O3 -msse2 -mfpmath=sse -fomit-frame-pointer   -DMOZILLA_CLIENT -include ../../../mozilla-config.h -MD -MP -MF .deps/nsXPCOMGlue.o.pp  /home/reandr/pm-build/pmsrc/xpcom/glue/standalone/nsXPCOMGlue.cpp
In file included from /home/reandr/pm-build/pmsrc/xpcom/glue/standalone/nsXPCOMGlue.cpp:471:0:
../../../dist/system_wrappers/glib.h:3:23: fatal error: glib.h: no such file or directory
 #include_next glib.h
                       ^
compilation terminated.
/home/reandr/pm-build/pmsrc/config/rules.mk:1104: recipe for target 'nsXPCOMGlue.o' failed
make[7]: *** [nsXPCOMGlue.o] Error 1
make[7]: Leaving directory '/home/reandr/pm-build/pmbuild/xpcom/glue/standalone'
/home/reandr/pm-build/pmsrc/config/makefiles/target_libs.mk:59: recipe for target 'libs' failed
make[6]: *** [libs] Error 2
make[6]: Leaving directory '/home/reandr/pm-build/pmbuild/xpcom/glue'
/home/reandr/pm-build/pmsrc/config/makefiles/target_libs.mk:59: recipe for target 'libs' failed
make[5]: *** [libs] Error 2
make[5]: Leaving directory '/home/reandr/pm-build/pmbuild/xpcom'
/home/reandr/pm-build/pmsrc/config/makefiles/target_libs.mk:16: recipe for target 'libs_tier_platform' failed
make[4]: *** [libs_tier_platform] Error 2
make[4]: Leaving directory '/home/reandr/pm-build/pmbuild'
/home/reandr/pm-build/pmsrc/config/rules.mk:723: recipe for target 'tier_platform' failed
make[3]: *** [tier_platform] Error 2
make[3]: Leaving directory '/home/reandr/pm-build/pmbuild'
/home/reandr/pm-build/pmsrc/config/rules.mk:656: recipe for target 'default' failed
make[2]: *** [default] Error 2
make[2]: Leaving directory '/home/reandr/pm-build/pmbuild'
/home/reandr/pm-build/pmsrc/client.mk:372: recipe for target 'realbuild' failed
make[1]: *** [realbuild] Error 2
make[1]: Leaving directory '/home/reandr/pm-build/pmsrc'
client.mk:172: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by kuh3h3** [comment]
can`t write tag?

so i use { } for tag

#include_next {glib.h}

**Comment by trav90** [comment]
Commit 33708ea is most likely the culprit (although I'm not sure why is is failing for you, as a full clobber build was successful for me on both CentOS and Manjaro).

**Comment by trav90** [comment]
What's your .mozconfig look like?

**Comment by kuh3h3** [comment]
ac_add_options --enable-official-branding
	export MOZILLA_OFFICIAL=1

	mk_add_options MOZ_CO_PROJECT=browser
	ac_add_options --enable-application=browser
       mk_add_options AUTOCLOBBER=1
	mk_add_options MOZ_OBJDIR=/home/reandr/pm-build/pmbuild/

	ac_add_options --disable-crashreporter
	ac_add_options --disable-accessibility
	ac_add_options --disable-parental-controls
	ac_add_options --disable-webrtc
	ac_add_options --disable-logging
	ac_add_options --disable-necko-wifi
	ac_add_options --disable-installer
	ac_add_options --disable-updater
	ac_add_options --disable-websms-backend

	ac_add_options --disable-tests
	ac_add_options --disable-mochitests
	ac_add_options --disable-debug
	ac_add_options --disable-debug-symbols

	ac_add_options --enable-strip
	ac_add_options --enable-jemalloc
	ac_add_options --enable-optimize="-O3 -msse2 -mfpmath=sse"

	ac_add_options --enable-safe-browsing
	ac_add_options --enable-url-classifier
	ac_add_options --enable-chrome-format=omni

	ac_add_options --x-libraries=/usr/lib

**Comment by trav90** [comment]
Try building without jemalloc (it shouldn't be used on such a recent distro anyway) e.g. comment out or remove the enable-jemalloc line.

**Comment by wolfbeast** [comment]
Your glib_slice code would only be triggered with jemalloc enabled -- I thought you had tested that? because otherwise all this is n/a (only if MOZ_MEMORY is used, i.e.: (moz)jemalloc.)

**Comment by trav90** [comment]
I tested without jemalloc on Manjaro and with jemalloc on CentOS. Let me double check and make sure I didn't get my mozconfig's mixed up.

**Comment by trav90** [comment]
Shoot, I did build without jemalloc on CentOS as well. Sorry, totally my fault...

**Comment by wolfbeast** [comment]
@kuh3h3 Can you try to build from master and see if it is resolved for you?

**Comment by kuh3h3** [comment]
no .after clean, rebuild (without jemalloc ), segfault
git  6efbdda4960d85c388ab76a10433085cb9e9d6ca


[reandr@kuh3h3 palemoon]$ gdb ./palemoon
GNU gdb (GDB) Fedora 7.8.2-39.fc21
Reading symbols from ./palemoon...(no debugging symbols found)...done.
(gdb) r
Starting program: /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/palemoon 
Missing separate debuginfos, use: debuginfo-install glibc-2.20-8.fc21.i686
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0xb35d6b40 (LWP 5640)]
[Thread 0xb35d6b40 (LWP 5640) exited]
Detaching after fork from child process 5641.
[New Thread 0xb35d6b40 (LWP 5642)]
[New Thread 0xb1e8bb40 (LWP 5643)]
[New Thread 0xb14ffb40 (LWP 5644)]
[New Thread 0xb0cfeb40 (LWP 5645)]
[New Thread 0xb02ffb40 (LWP 5646)]
[New Thread 0xaf7ffb40 (LWP 5647)]
[New Thread 0xaebd9b40 (LWP 5648)]
[New Thread 0xae3d8b40 (LWP 5649)]
[New Thread 0xadbd7b40 (LWP 5650)]
[New Thread 0xad3d6b40 (LWP 5651)]
[New Thread 0xac9ffb40 (LWP 5653)]
[New Thread 0xac003b40 (LWP 5654)]
[New Thread 0xabb04b40 (LWP 5655)]
[New Thread 0xab1ffb40 (LWP 5656)]
[New Thread 0xaa803b40 (LWP 5657)]
[New Thread 0xa9dffb40 (LWP 5658)]
[Thread 0xadbd7b40 (LWP 5650) exited]
[New Thread 0xadbd7b40 (LWP 5659)]
[Thread 0xa9dffb40 (LWP 5658) exited]
[Thread 0xabb04b40 (LWP 5655) exited]
[New Thread 0xa95a1b40 (LWP 5660)]
[New Thread 0xa9dffb40 (LWP 5661)]
[Thread 0xadbd7b40 (LWP 5659) exited]

Program received signal SIGSEGV, Segmentation fault.
0x4dd797cf in _int_malloc () from /lib/libc.so.6
Missing separate debuginfos, use: debuginfo-install GConf2-3.2.6-11.fc21.i686 ORBit2-2.14.19-13.fc21.i686 adwaita-gtk2-theme-3.14.2.2-1.fc21.i686 alsa-lib-1.0.28-2.fc21.i686 atk-2.14.0-1.fc21.i686 avahi-glib-0.6.31-32.fc21.i686 avahi-libs-0.6.31-32.fc21.i686 bzip2-libs-1.0.6-14.fc21.i686 cairo-1.14.2-1.fc21.i686 dbus-glib-0.104-1.fc21.i686 dbus-libs-1.8.20-1.fc21.i686 elfutils-libelf-0.163-1.fc21.i686 elfutils-libs-0.163-1.fc21.i686 expat-2.1.0-10.fc21.i686 gdk-pixbuf2-2.31.1-1.fc21.i686 glib2-2.42.2-1.fc21.i686 gnome-vfs2-2.24.4-17.fc21.i686 graphite2-1.2.4-3.fc21.i686 gtk2-2.24.28-1.fc21.i686 gvfs-1.22.4-2.fc21.i686 harfbuzz-0.9.36-1.fc21.i686 ibus-gtk2-1.5.10-5.fc21.i686 ibus-libs-1.5.10-5.fc21.i686 keyutils-libs-1.5.9-4.fc21.i686 krb5-libs-1.12.2-17.fc21.i686 libICE-1.0.9-2.fc21.i686 libSM-1.2.2-2.fc21.i686 libX11-1.6.2-2.fc21.i686 libXScrnSaver-1.2.2-8.fc21.i686 libXau-1.0.8-4.fc21.i686 libXcomposite-0.4.4-6.fc21.i686 libXcursor-1.1.14-4.fc21.i686 libXdamage-1.1.4-6.fc21.i686 libXext-1.3.3-2.fc21.i686 libXfixes-5.0.1-4.fc21.i686 libXi-1.7.4-2.fc21.i686 libXinerama-1.1.3-4.fc21.i686 libXrandr-1.4.2-2.fc21.i686 libXrender-0.9.8-4.fc21.i686 libXt-1.1.4-10.fc21.i686 libart_lgpl-2.3.21-12.fc21.i686 libbluray-0.7.0-1.fc21.i686 libbonobo-2.32.1-8.fc21.i686 libbonoboui-2.24.5-8.fc21.i686 libcanberra-0.30-7.fc21.i686 libcom_err-1.42.12-4.fc21.i686 libdrm-2.4.60-1.fc21.i686 libffi-3.1-7.fc21.i686 libgcc-4.9.2-6.fc21.i686 libgcrypt-1.6.3-4.fc21.i686 libgnome-2.32.1-9.fc21.i686 libgnome-keyring-3.12.0-4.fc21.i686 libgnomecanvas-2.30.3-9.fc21.i686 libgnomeui-2.24.5-10.fc21.i686 libgpg-error-1.17-2.fc21.i686 libselinux-2.3-10.fc21.i686 libstdc++-4.9.2-6.fc21.i686 libtdb-1.3.1-1.fc21.i686 libtool-ltdl-2.4.2-31.fc21.i686 libuuid-2.25.2-3.fc21.i686 libvorbis-1.3.4-3.fc21.i686 libwayland-client-1.6.0-1.fc21.i686 libwayland-server-1.6.0-1.fc21.i686 libxcb-1.11-5.fc21.i686 libxml2-2.9.1-7.fc21.i686 mesa-libEGL-10.4.7-1.20150323.fc21.i686 mesa-libgbm-10.4.7-1.20150323.fc21.i686 mesa-libglapi-10.4.7-1.20150323.fc21.i686 nss-mdns-0.10-15.fc21.i686 nss-softokn-freebl-3.19.2-1.0.fc21.i686 openssl-libs-1.0.1k-11.fc21.i686 pango-1.36.8-6.fc21.i686 pcre-8.35-12.fc21.i686 pixman-0.32.6-4.fc21.i686 popt-1.16-5.fc21.i686 systemd-libs-216-25.fc21.i686 xz-libs-5.1.2-14alpha.fc21.i686 zlib-1.2.8-7.fc21.i686
(gdb) bt full
#0  0x4dd797cf in _int_malloc () at /lib/libc.so.6
#1  0x4dd7c3a2 in malloc () at /lib/libc.so.6
#2  0x4dfce161 in g_malloc () at /lib/libglib-2.0.so.0
#3  0x4dfe8732 in g_strdup () at /lib/libglib-2.0.so.0
#4  0xffffffff in gtk_label_set_text () at /lib/libgtk-x11-2.0.so.0
#5  0xffffffff in gtk_label_init () at /lib/libgtk-x11-2.0.so.0
#6  0x4e3cc3cb in g_type_create_instance () at /lib/libgobject-2.0.so.0
#7  0x4e3aca0c in g_object_new_internal () at /lib/libgobject-2.0.so.0
#8  0x4e3ae6d8 in g_object_newv () at /lib/libgobject-2.0.so.0
#9  0x4e3aed80 in g_object_new () at /lib/libgobject-2.0.so.0
#10 0xffffffff in gtk_menu_item_ensure_label () at /lib/libgtk-x11-2.0.so.0
#11 0xffffffff in gtk_real_menu_item_set_label () at /lib/libgtk-x11-2.0.so.0
#12 0xffffffff in gtk_menu_item_set_label () at /lib/libgtk-x11-2.0.so.0
#13 0x4e3ace50 in g_object_new_internal () at /lib/libgobject-2.0.so.0
#14 0x4e3aeadd in g_object_new_valist () at /lib/libgobject-2.0.so.0
#15 0x4e3aed60 in g_object_new () at /lib/libgobject-2.0.so.0
#16 0xffffffff in gtk_menu_item_new_with_label () at /lib/libgtk-x11-2.0.so.0
#17 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#18 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#19 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#20 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#21 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#22 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#23 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#24 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#25 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#26 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#27 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#28 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#29 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#30 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#31 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#32 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#33 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#34 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#35 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#36 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#37 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#38 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#39 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#40 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#41 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#42 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#43 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#44 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
---Type <return> to continue, or q <return> to quit---
#45 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#46 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#47 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#48 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#49 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#50 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#51 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#52 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#53 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#54 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#55 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#56 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#57 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#58 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#59 0xffffffff in  () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#60 0xffffffff in XRE_main () at /run/media/reandr/48fed7c3-c2ce-49e5-8eaa-3bdf47cff596/palemoon/libxul.so
#61 0x0804aed1 in _start ()
(gdb) q

**Comment by wolfbeast** [comment]
*facepalm* Build WITH jemalloc, please. Like you did before posting this issue.
Your segfault is likely unrelated.

**Comment by kuh3h3** [comment]
after clean, rebuild (with jemalloc ), build ok , run ok
git 6efbdda

**Comment by wolfbeast** [comment]
Considered fixed after verification

**Comment by trav90** [comment]
I'm unable to recreate the segfault you get without jemalloc. Try using --enable-optimize="-O2 instead of O3.
