### ISSUE TITLE
Mac application menu intermittently doesn't populate

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1511]
Apparently, the Mac OSX application menu for Pale Moon intermittently doesn't populate with menu choices. This may be caused by a race condition upon browser startup/initialization.

**Comment by JustOff** [comment]
AFAK, this is [known issue](https://forum.palemoon.org/viewtopic.php?p=99226#p99226) for first run of PM 27.x on OSX.

**Comment by wolfbeast** [comment]
Why do you think I created this issue in the tracker? :P

**Comment by JustOff** [comment]
It seems here is the solution - https://bugzilla.mozilla.org/show_bug.cgi?id=1151345, @stevenschlansker could you check this?

**Comment by wolfbeast** [comment]
From that bug, this minimal commit should do it (it was ported to 38 for Thunderbird): https://hg.mozilla.org/releases/mozilla-esr38/rev/07b9ccbfb490

**Comment by wolfbeast** [comment]
@stevenschlansker -- maybe you can verify that the patch I added in [f054802] fixes the problem?

**Comment by stevenschlansker** [comment]
Queueing up a build now.  I can't reproduce the problem on demand, it was always intermittent for me, but I can at least verify build and launch.

**Comment by JustOff** [comment]
I have always had this issue in previous builds, so I can check when you make a new one.

**Comment by stevenschlansker** [comment]
@JustOff new build is up at same location, http://mac.palemoon.org/dist/palemoon-27.6.1.mac64.dmg

**Comment by JustOff** [comment]
I confirm this change fixes the issue: all items are displayed on the first start!

PS: How about 27.6.2? :stuck_out_tongue_winking_eye:

**Comment by stevenschlansker** [comment]
Oh, totally missed 27.6.2 landing.  Building now.

**Comment by JustOff** [comment]
Perhaps you may want to include this fix in 27.6.2, since the OSX build is in any case unofficial.

**Comment by stevenschlansker** [comment]
Yup, it'll be included.

**Comment by wolfbeast** [comment]
Since people have verified, marking this solved.
