### ISSUE TITLE
Embedded tweets are broken

### ISSUE THREAD

**Issue by sergeevabc** [MoonchildProductions/Pale-Moon#1512]
Windows 7 x64, Pale Moon 27.6.2

1. Open Medium’s article with embedded tweets ([example][1]).
2. Tweet’s text is visible, images and styles are not.

Actual
![](https://images.vfl.ru/ii/1511880972/94e5c1cb/19604996.png)

Expected (taken in Basilisk)
![](https://images.vfl.ru/ii/1511879118/a218dd8f/19604658.png)

[1]: https://medium.com/@copyconstruct/small-functions-considered-harmful-91035d316c29
[2]: https://sub.god.jp/f/RUIM0Hbh.mp4

**Comment by wolfbeast** [comment]
> 11:42:03.783 Content Security Policy: The page's settings blocked the loading of a resource at https://syndication.twitter.com/settings ("connect-src https://localhost https://*.instapaper.com https://*.stripe.com https://getpocket.com https://medium.com:443 https://*.medium.com:443 https://*.medium.com https://medium.com https://*.medium.com https://*.algolia.net https://cdn-static-1.medium.com https://dnqgz544uhbo8.cloudfront.net https://cdn-videos-1.medium.com https://cdn-audio-1.medium.com https://*.lightstep.com https://app.zencoder.com https://medium.com").1 <unknown>

It's not in the CSP, so Pale Moon blocks it. Correct, no?

**Comment by sergeevabc** [comment]
I see the very error in PM (there is none of that sort in Basilisk), sir, but am not sure how to proceed.

**Comment by wolfbeast** [comment]
I disabled CSP to check, but it still looks the same -- what, exactly, is supposed to be the difference? What's missing? Your screencast doesn't show what to expect.

**Comment by wolfbeast** [comment]
Ah wait, there are other errors -- unfortunately those are custom errors and they are empty, so whatever they used to "protect their code" doesn't allow debugging.

**Comment by sergeevabc** [comment]
Sorry for providing the textual description of expected state without a picture.
Screencast has been replaced with screenshots.

**Comment by sergeevabc** [comment]
It seems this issue is website related, because I see embedded tweets in others places ([here][1] and [there][2]).
Do you believe I should contact the webmaster of Medium and tell him to fix CSP then?
Also, do you mind me asking why Basilisk renders tweets on Medium without a hassle?

[1]: https://www.rt.com/news/411177-kim-dotcom-bitcoin-plan/
[2]: https://www.theguardian.com/books/booksblog/2014/may/27/10-authors-who-are-brilliant-at-twitter

**Comment by wolfbeast** [comment]
It rendered incorrectly even with CSP disabled, so that's not the issue (although it is an issue, it's a different one). 

As for your question: I don't know, but quite certainly it's because they are using javascript to render the tweet images. That JS is all minified and as I said, it throws custom, empty errors. Impossible to garner anything from that.

You can try contacting Medium, but it'll likely be moot -- they will just tell you to use "a supported browser like Chrome".

**Comment by sergeevabc** [comment]
Dear @ktzhu, being an engineer and product manager at Medium, could you be so kind to tell who of [your colleagues][1] is the appropriate person to contact about this website bug?

[1]: https://github.com/orgs/Medium/people

**Comment by sergeevabc** [comment]
I contacted recently active Medium developers such as @adrianlee44, @andybons, @jcrosby, @ktzhu, @reyner, and @dokipen. My appeal was straightforward and polite, 2 weeks passed, yet only the last one deigned to reply. 

He told me that Medium used Embedly API and advised to contact its support, which turned out to be lackadaisical at best. They compelled me to reiterate the point instead of clicking the link that leads here, then wondered what kind of browser Pale Moon was instead of at least visiting Wikipedia, then refused to troubleshoot, just like you predicted. 

Quite a disheartening experience, given that Medium [states][1] to be “a platform built for people, quality, original ideas, clean reading experience, engagement & depth, viewpoints”, but the observed attitude rather encourages major vendors lock-in than praises the diversity.

It leaves me with no choice but to mark the issue as invalid and close it.

[1]: https://medium.com/about

**Comment by andybons** [comment]
I’m not sure where you got the idea that I’m an active developer at Medium since the last commit I made to the github.com/medium org was https://github.com/Medium/variants/commit/2db37605def8e61e764622da06eceb5c1cd3e3b7 in December of 2014.

I don’t speak for the Medium team (I’ve never worked there; only contributed some code), but the expectation that they prioritize a browser with a [market share of 0.02%](https://en.wikipedia.org/wiki/Pale_Moon_(web_browser)#Market_share) over the massive amount of other tasks they have on their plate is asking a lot, and chastizing them as not being true to their mission after they actively responded to help you (regardless of whether you are satisfied with the outcome) is a bad look.

**Comment by sergeevabc** [comment]
> Where you got the idea that I’m an active developer at Medium

Slow down, you’ve missed a pause. Let’s try with comma: “recently active, Medium related”. Your profile’s heatmap indicated activity and organization’s field had a Medium icon, so you might have helped, even if not engaged anymore. But you neglected an opportunity to soothe a suffering soul and remained silent until you felt diminished by a public report. Fear prevailed over [love][5], but it doesn’t have to be this way.

> Expectation they prioritize a browser with a market share of 0.02%…

Slow down, you’ve cited outdated data in a misleading way. Recent growth (0.05% right below the chart) shows a positive dynamics as Pale Moon inspires confidence faster than other hobby browsers. They are made not to compete, but to satisfy the needs of [minorities][4]. Also, browser forks inherit abilities of parents more or less (e.g. to render Javascript), which in this case was Firefox ESR, a major shareholder.

> …over the massive amount of other tasks they have on their plate is asking a lot

Slow down, you’re an outsider to Medium, yet weighing its backlog. When Mr. Putin — [in one day][3] — visits Syria to declare victory over ISIS, then visits Egypt and Turkey to mitigate US decisions on destabilizing the Middle East, I call it a massive amount. But when a worldwide service with 100+ million USD in investment has a support team too feather-bedded to visit a search engine, it smells like a rotten management.

> Chastizing them as not being true to their mission is a bad look

Slow down, you’re obsessed with [being offended][2]. Reporting back about the initiatives taken to address Pale Moon issues is a way to stay synchronized and evolve together. Let alone calling spade a spade is neither a crime nor a sin, but a pure aspiration to express oneself most accurately — some words are meant to awaken and to describe man-made pitfalls posed by the lack of a holistic awareness.

---

Slow down, haste makes waste. Should you wish to reply, my inbox and [Pale Moon forum][1] awaits you.

[1]: https://forum.palemoon.org/
[2]: http://www.theblaze.com/contributions/you-arent-really-offended-all-the-time-so-please-stop-pretending
[3]: http://news.xinhuanet.com/english/2017-12/12/c_136820843.htm
[4]: https://hooktube.com/watch?v=mqp8_ROAIJY
[5]: https://hooktube.com/watch?v=ABSXJiYQFuI

**Comment by mattatobin** [comment]
Further discourse is to be taken to the Pale Moon forum or to another medium. The latter if politics will be involved.

Peace!
