### ISSUE TITLE
Can't open teamviewer.com

### ISSUE THREAD

**Issue by spectatorBH** [MoonchildProductions/Pale-Moon#1514]
PM fails to open `teamviewer.com` site as of recently, shows an error after a while:

![broken_site_teamviewer_com](https://user-images.githubusercontent.com/21036474/33383368-c953053a-d52b-11e7-93e0-99c2a9495b32.png)

*Checked on Windows 7 x64, Pale Moon 27.7.0a2 x64 (2017-11-26) portable, clean profile, no add-ons, default settings.*

Browser console log:
```
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 459ms]
POST http://g2.symcb.com/ [HTTP/1.1 200 OK 151ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 82ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 84ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 92ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 85ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 81ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 81ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 83ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 84ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 80ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 82ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 81ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 365ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 82ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 85ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 80ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 80ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 86ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 84ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 86ms]
GET https://www.teamviewer.com/ [HTTP/2.0 302 Found 85ms]
```
The issue manifests itself on Firefox 52.5 ESR, too, although the latest Basilisk 2017.11.12, Firefox Quantum 57+ and Chromium 62 have no problems opening the site.

**Comment by wolfbeast** [comment]
Works for me on 27.6.2 -- it forwards to a regional site (based on unknown criteria). I don't think this is a browser bug.

**Comment by spectatorBH** [comment]
You're right. Seems they have totally broken their regional redirection config: if your preffered content language in the browser is not set to either [en] or [en-us], the site could not be redirected properly. Please close the issue. Sorry for bothering...

**Comment by wolfbeast** [comment]
The strange thing is, if you used a clean profile as you said, then you'd have [en] and [en-us] in your content languages. Also, they forward me based on location, not content language (because i don't get English first off), so yeah, definitely more than a few things broken on their end.

**Comment by spectatorBH** [comment]
Well, I created a clean profile a couple of weeks ago just for testing purposes (using a dedicated shortcut with custom command line), then forgot that I was tinkering with content language setting after a while, so it was not as default as I thought.
