### ISSUE TITLE
Allow users to disable 4th button and/or 5th button of mouse on Windows

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1517]
Windows doesn't provide a way to customize the behavior of the 4th or 5th button of a mouse.
If a 5-button mouse works with standard mouse driver of Windows, users cannot disable the 4th button (browser back) nor the 5th button (browser forward).

We should allow disabling these buttons with our prefs since we can prevent Windows from generating WM_APPCOMMAND messages if WM_XBUTTONUP messages are processed by us (and not sent to DefWindowProc).

I'll take this myself since I already researched MSDN and know how it works.
See: https://msdn.microsoft.com/en-us/library/windows/desktop/ms646245%28v=vs.85%29.aspx
> Unlike the `WM_LBUTTONDOWN`, `WM_MBUTTONDOWN`, and `WM_RBUTTONDOWN` messages, an application should return `TRUE` from this message if it processes it. Doing so allows software that simulates this message on Windows systems earlier than Windows 2000 to determine whether the window procedure processed the message or called `DefWindowProc` to process it.

**Comment by wolfbeast** [comment]
Since I don't use a 5-button mouse, someone else should verify this ;)

**Comment by JustOff** [comment]
I have verified this with my son's gaming mouse, everything works as expected.
