### ISSUE TITLE
Layout in a forum is broken in Pale Moon

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1524]
While browsing a bit around the web i visited a forum which rather looks broken layout wise in Pale Moon if i compare it with IE or Otter browser.

Getting this in the error console while viewing the page:

Timestamp: 01.12.2017 22:26:41
Error: ReferenceError: quantserve is not defined
Source File: http://www.city-data.com/forum/
Line: 5107

Url is: http://www.city-data.com/forum/

Using latest unstable.

**Comment by janekptacijarabaci** [comment]
The site uses User-Agent sniffing.

__Some solution__

about:config:
`general.useragent.override.city-data.com`
\=
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9`

**Comment by Sa-Ja-Di** [comment]
That again.. Well, in that case that issue can be closed of course, thanks :)
