### ISSUE TITLE
Consider blocking top level window data: URIs

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1528]
As discussed on the forum, seems to be a desired enhancement.

Main implementation: [Bug 1331351](https://bugzilla.mozilla.org/show_bug.cgi?id=1331351)
Follow-ups that need to be added: [Bug 1395948](https://bugzilla.mozilla.org/show_bug.cgi?id=1395948) and [Bug 1394554](https://bugzilla.mozilla.org/show_bug.cgi?id=1394554)

Being able to enable this feature is essential for development and testing, so it MUST have the pref control from that implementation.

**Comment by janekptacijarabaci** [comment]
I suggest adding the label `UXP-task`.

**Comment by wolfbeast** [comment]
Is this complete? i.e.: can this be safely switched on in releases by default?

**Comment by janekptacijarabaci** [comment]
> Is this complete?

IMHO/AFAIK - yes (at least now).

> Can this be safely switched on in releases by default?

I will not make this decision (thorough testing ?).

**Comment by SpockMan02** [comment]
I don't feel too strongly about this, but are we sure blocking navigation to `data:` URIs is the best default behavior? It'll be good to have as a preference, of course, but maybe just making users aware* that it's not `https:` or something more commonly expected would be a better way to go by default.

*(e.g. highlighting the scheme, warning on password input, suggestions thrown around in the Bugzilla bug)

**Comment by wolfbeast** [comment]
@SpockMan02 navigation to `data:` URIs from scripted web content is an issue and it can be abused.

`data:` URLs are generally a source of confusion for users. Because of their unfamiliarity and ability to encode arbitrary untrusted content in a URL, they are widely being used in spoofing and phishing attacks. Another problem is that they can be passed along without a backing page that runs JavaScript (e.g. a data URL can be sent via email). For that reason, Chrome, IE and Edge block top-frame navigations to data URLs already, and although they are very useful for developers, for most end-users they are just a trap waiting to be fallen into.
Devs can flip this pref if they need it, they generally know what they are doing.

**Comment by wolfbeast** [comment]
Right, so, I got slightly confused as to what all was done -- this needs to be ported from moebius to Pale Moon. Any takers?

**Comment by wolfbeast** [comment]
So, the work done on this was for UXP -- while the issue was filed against Pale Moon/Tycho. Any reason why that happened instead of on the actually repo the issue was filed on? 
I'll create an issue for this solved part on the correct repo, but we still don't have an implementation here (which needs rebasing for our platform, e.g. for `nsContentSecurityManager`)

**Comment by mattatobin** [comment]
If someone wants this for Tycho they are going to have to solve it a different way. The ported Mozilla patch relies on things such as (as mentioned above) `nsContentSecurityManager` which became a thing in m-r42.

**Comment by wolfbeast** [comment]
I looked at the code again that was submitted for Möbius, and that simply can't be ported. If this needs to be blocked in Pale Moon/Tycho it will require a different approach (and probably can be done a LOT simpler then what Mozilla has done)
