### ISSUE TITLE
recent git build on fedora21 segfaults

### ISSUE THREAD

**Issue by kuh3h3** [MoonchildProductions/Pale-Moon#153]
[reandr@kuh3h3 pmsrc]$ gcc -v
Using built-in specs.
COLLECT_GCC=/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/i686-redhat-linux/4.9.2/lto-wrapper
Target: i686-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-i686-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-i686-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch=i686 --build=i686-redhat-linux
Thread model: posix
gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC) 

[reandr@kuh3h3 pmsrc]$ uname -a
Linux kuh3h3 4.1.4-100.fc21.i686+PAE #1 SMP Tue Aug 4 05:10:46 UTC 2015 i686 i686 i386 GNU/Linux

[reandr@kuh3h3 pmsrc]$ git log
commit 6efbdda4960d85c388ab76a10433085cb9e9d6ca
Merge: c75632c 7432143
Author: Moonchild <wolfbeast@users.noreply.github.com>
Date:   Fri Aug 14 07:54:41 2015 +0200

    Merge pull request #152 from trav90/glib-work
    
    Linux: Fix build bustage when using jemalloc

[reandr@kuh3h3 pmsrc]$ more .moz*
::::::::::::::
.mozconfig
::::::::::::::
	ac_add_options --enable-official-branding
	export MOZILLA_OFFICIAL=1
       export MOZ_DEBUG_SYMBOLS=1
       ac_add_options --enable-debug-symbols="-gdwarf-2"
	ac_add_options --disable-install-strip
	mk_add_options MOZ_CO_PROJECT=browser
	ac_add_options --enable-application=browser
       mk_add_options AUTOCLOBBER=1
	mk_add_options MOZ_OBJDIR=/home/reandr/pm-build/pmbuild/

	ac_add_options --disable-crashreporter
	ac_add_options --disable-accessibility
	ac_add_options --disable-parental-controls
	ac_add_options --disable-webrtc
	ac_add_options --disable-logging
	ac_add_options --disable-necko-wifi
	ac_add_options --disable-installer
	ac_add_options --disable-updater
	ac_add_options --disable-websms-backend

	ac_add_options --disable-tests
	ac_add_options --disable-mochitests

	ac_add_options --enable-optimize="-O3 -msse2 -mfpmath=sse"

	ac_add_options --enable-safe-browsing
	ac_add_options --enable-url-classifier
	ac_add_options --enable-chrome-format=omni

	ac_add_options --x-libraries=/usr/lib

-----------------------------------------------------------------

**Comment by wolfbeast** [comment]
Please use an attachment, gist, pastebin or similar to include large amounts of data!

GCC 4.9 + -O3 has been problematic for others. Please try building with -O2 or use GCC 4.7

**Comment by kuh3h3** [comment]
ok i`l try "02".

pastebin link

 http://pastebin.com/PsMamfLk

**Comment by kuh3h3** [comment]
commit 6efbdda

gcc 4.9.2 -02 without jemalloc 
build ok, run ok.

**Comment by wolfbeast** [comment]
-O3 is risky -- don't use it. Closing this, since it's not really a code issue any longer at this point.
