### ISSUE TITLE
Make add-on update logic more intuitive

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1532]
Currently, our update logic has 2 controls: a global setting for automatic updates of add-ons, and a per-add-on selection of automatic updates `default/on/off`. This does not provide a way for the user to control whether to check for updates or not, is difficult to understand, and it's relatively easy to unintentionally update an add-on by clicking "update" or "update all" if automatic updates are disabled, because the manager will notify for all add-on states in that case.

We have 2 options here, either add an explicit (new) option to "never check", but I think that one would just add to the confusion and we should keep things simple.

The other option is to simplify things, and make it a simple "check for updates" selection on the individual add-ons (and removing the "default" there) and keeping the behavior of the global setting to automatically update as-is. I'll outline this as the "new behavior" below.

Current behavior | add-on **default** | add-on **on** | add-on **off**
----------------- | ------------------- | --------------- | ----------------
Global **on** | update | update | notify
Global **off** | notify | update | notify

New behavior | add-on **on** | add-on **off**
-------------- | --------------- | ---------------
Global **on** | update | nothing
Global **off** | notify | nothing

The only thing we lose in the new behavior would be for a user to be notified of an available update if they have the add-on checking state "off", but we already have the individual link on the individual add-ons to "check for updates to this add-on", so that would be covered if the behavior of that link isn't touched.

**Comment by graciecat** [comment]
The result values update/notify/nothing refer to what Add-ons Manager does automatically, right?

What about when the user selects "Check for updates now" [globally] ?
Are the results the same?

**Comment by wolfbeast** [comment]
> What about when the user selects "Check for updates now" [globally] ?
Are the results the same?

If I recall correctly the "check for updates now" simply triggers the same update check as the one used on automatic intervals, so yes, the results would be the same.

**Comment by JustOff** [comment]
1. There is a mistake in the current behavior matrix: `global on` + `add-on off` = `notify`, i.e. currently there is no state that can lead to `nothing`.
2. If you want to introduce `nothing` state, then, IMHO, we should at least:
    * add some visual indicator for add-ons with disabled update
    * provide a way to check all add-ons with disabled update at once, not one by one

**Comment by wolfbeast** [comment]
Hmm.. seems you're right, so that's even worse then regarding point 1. I'll update the matrix.

A simple added icon/glyph would probably suffice for 2a, indicating update checks are disabled. We can probably use one of the extended UTF-8 characters for that for the fonts that are in use in the add-on manager (I believe a "no" roadsign is available in all common fonts used for the UI there...)

As for 2b, no, I don't think that's a good idea -- the whole point of _accidentally updating_ that we want to _avoid_ stems from the fact that notifications are displayed, and "update all" picking up any add-on that has been marked as having an update available! We want to avoid performing _any_ sweeping checks for extensions that are set to explicitly **not** check for updates, and get rid of the confusing state of "checking/updating anyway, even if individual add-ons have updates disabled"

**Comment by JustOff** [comment]
If there will be no more major releases of Pale Moon 27, I'd recommend not to change any strings or we will have problems with language packs.
