### ISSUE TITLE
HTML - media - setting currentTime when readyState is HAVE_NOTHING incorrectly throws an exception: Invalid State

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1535]
Ad https://forum.palemoon.org/viewtopic.php?f=29&t=17685

http://celticmusicpodcast.com/celtic-rock-for-2-hours

> When I go to this page, about 1/3 the page down is a button (Celtic Rock... For 2-Hours).
Press the button and you hear the podcast ...and nothing happens.

Throws an error in Browser Console:
```
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
337ab7:344:0
```
= `player.currentTime = 0;`

**Comment by trav90** [comment]
Resolved by #1536
