### ISSUE TITLE
nsIWebBrowserChrome.h ?

### ISSUE THREAD

**Issue by marcelomelofreitas** [MoonchildProductions/Pale-Moon#1538]
where is the nsIWebBrowserChrome.h file?

**Comment by mattatobin** [comment]
It's a header file seemingly generated by processing for XPCOM IDL files.

See: http://xref.palemoon.org/palemoon-trunk/find?string=nsIWebBrowserChrome

**Comment by marcelomelofreitas** [comment]
sim eu achei depois, obrigado mesmo assim, vou tentar incorporar em um aplicativo win32 feito em delphii VCL, acredito que poderei contribuir com o projeto de uma forma ou outra, obrigado por enquando

**Comment by marcelomelofreitas** [comment]
sim eu achei depois, obrigado mesmo assim, vou tentar incorporar em um aplicativo win32 feito em delphii VCL, acredito que poderei contribuir com o projeto de uma forma ou outra, obrigado por enquando

**Comment by mattatobin** [comment]
I'm sorry? Could you please use English on the Issue Tracker please?

**Comment by wolfbeast** [comment]
FTR: MT(G)
> yes I found it later, thanks anyway, I will try to incorporate in a win32 application made in delphii VCL, I believe I can contribute the project in one way or another, thanks for while
