### ISSUE TITLE
Load temporary add-on

### ISSUE THREAD

**Issue by svnpenn** [MoonchildProductions/Pale-Moon#1540]
In the "add-ons manager", Firefox has a "debug add-ons" option:

> ![1][1]

Which takes you to the page "debugging with firefox developer tools":

> ![2][2]

However Pale Moon seems to have no way to load temporary add-ons.

[1]:
http://user-images.githubusercontent.com/926619/33806699-8cd86668-dd91-11e7-8350-ba88166f9518.png
[2]:
http://user-images.githubusercontent.com/926619/33806700-8f299dd8-dd91-11e7-838f-ce5604623df9.png

**Comment by JustOff** [comment]
The temporary add-on feature was introduced in Firefox to [give developers the ability to run unsigned extensions](https://blog.mozilla.org/addons/2015/12/23/loading-temporary-add-ons/), but Pale Moon does not require signing, so it's simply not needed.
