### ISSUE TITLE
WebExtensions

### ISSUE THREAD

**Issue by svnpenn** [MoonchildProductions/Pale-Moon#1541]
Currently if you try to install a WebExtension you get this message

> This add-on could not be installed because Pale Moon does not support WebExtensions

Please allow WebExtensions to be installed, thank you

**Comment by mattatobin** [comment]
Pale Moon does not and will not support WebExtensions for a very very long time.. If ever.

Sorry.

**Comment by Sa-Ja-Di** [comment]
Webextensions as far as i know are not coming to Pale Moon. You have to use Basilisk to use them. Bit i also do not believe that Webextensions feature parity is a goal of Basilisk, so most likely without anyone back-porting further Mozilla additions  to Webextensions there will be not much "progress"

**Comment by svnpenn** [comment]
https://github.com/OtterBrowser/otter-browser/issues/42

**Comment by svnpenn** [comment]
https://github.com/textbrowser/dooble/issues/19

**Comment by svnpenn** [comment]
https://github.com/CrustaBrowser/CrustaBrowser/issues/7

**Comment by svnpenn** [comment]
https://github.com/felipedaragon/sandcat/issues/3

**Comment by wolfbeast** [comment]
@svnpenn What's the point in referring to this issue from many other repos?

**Comment by mattatobin** [comment]
He is spamming everywhere.

**Comment by svnpenn** [comment]
https://github.com/MoonchildProductions/UXP/issues/343
