### ISSUE TITLE
Ugly rendering on HiDPI display

### ISSUE THREAD

**Issue by elimohl** [MoonchildProductions/Pale-Moon#1542]
Horiziontal scrolling, HUGE github avatars, too wide github menu. And low resolution icons.
(I have a 12-inch display with 1920x1080 resolution.)
![screenshot_2017-12-13_01-51-32](https://user-images.githubusercontent.com/10729543/33912755-30e7be44-dfa8-11e7-9dbf-cdd64784f7f6.png)
![screenshot_2017-12-13_01-47-45](https://user-images.githubusercontent.com/10729543/33912631-bf12403c-dfa7-11e7-8fc8-1bfd75c0ccaf.png)
![screenshot_2017-12-13_01-48-02](https://user-images.githubusercontent.com/10729543/33912632-bf34cd32-dfa7-11e7-97cc-f90604cbc31f.png)
![screenshot_2017-12-13_01-48-21](https://user-images.githubusercontent.com/10729543/33912634-bf530586-dfa7-11e7-8f89-e5d952356bbc.png)

**Comment by wolfbeast** [comment]
Not a browser issue. Please set up your system to use lower DPI if you don't want websites to scale accordingly for HD-in-12" resolution.

**Comment by l29ah** [comment]
It's an issue with palemoon's site then.

**Comment by mattatobin** [comment]
The issue is with your odd combo of choices.

**Comment by wolfbeast** [comment]
The only "issue" with Pale Moon's site is that it sets a minimum design width. Your choice of DPI makes that too wide to fit in your screen resolution, so you get a horizontal scroll bar. The "huge" github avatars are the result of the very same thing.

If you want more content to fit on your screen, lower your DPI accordingly. if you can't do that system-wide and want it just in the browser, change layout.css.devPixelsPerPx to a positive value that scaled things to your liking (-1 = use device DPI)

**Comment by l29ah** [comment]
On Thu, Dec 14, 2017 at 06:55:59AM -0800, Moonchild wrote:
> The only "issue" with Pale Moon's site is that it sets a minimum design width. Your choice of DPI makes that too wide to fit in your screen resolution, so you get a horizontal scroll bar. The "huge" github avatars are the result of the very same thing.
> If you want more content to fit on your screen, lower your DPI accordingly. if you can't do that system-wide and want it just in the browser, change layout.css.devPixelsPerPx to a positive value that scaled things to your liking (-1 = use device DPI)

Do you mean one should adjust the Xorg's/browser idea about the screen pixel size per each site manually for the site to be usable on non-96ppi displays? As this sounds quite cumbersome and broken, especially given such high ppi displays are mainstream on portable devices like laptops and smartphones now.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Lootyhoof** [comment]
You could edit the value of `layout.css.devPixelsPerPx` in `about:config` to suit your needs. Default (`-1.0`) is to use system default, but if you use a positive value (1.0, 1.5 etc) it will scale accordingly based on zoom level (1.0 is 100%, AKA 96ppi). 

Additionally, the toolbar icons (home, back/forward etc) are from your GTK theme. If you want those to be higher quality it would be worth finding a more HiDPI-friendly theme.

**Comment by elimohl** [comment]
> Do you mean one should adjust the Xorg's/browser idea about the screen pixel size per each site manually for the site to be usable on non-96ppi displays?
With `layout.css.devPixelsPerPx` one can adjust it for all sites at once. Not an obvious solution though.

> Additionally, the toolbar icons (home, back/forward etc) are from your GTK theme.
They are not. These icons are from a Pale Moon theme. And I did not find any theme where these icons have a decent quality.

**Comment by wolfbeast** [comment]
>>    Additionally, the toolbar icons (home, back/forward etc) are from your GTK theme.

> They are not. These icons are from a Pale Moon theme. And I did not find any theme where these icons have a decent quality.

Since you're absolute about this, can you then please point to the location in our source code where we can find these navigation control graphics? Our theme elements are stored in `/browser/themes/linux` for Linux operating systems.

**Comment by elimohl** [comment]
You are right, they are from GTK theme. I was confused because the icons change when I change the Pale Moon theme. But there are Pale Moon icons that have the same problem: the rss, bookmarks and history signs.
![screenshot_2017-12-16_18-37-41](https://user-images.githubusercontent.com/10729543/34072088-385e3e04-e292-11e7-99ab-9f8a07bae154.png)


And why GTK icons looks like this only in Pale Moon? In PCManFM they are smaller and looks normal because of it.

**Comment by wolfbeast** [comment]
Any raster-based toolbar icons in the default theme will not scale to very high DPI gracefully. That is inevitable -- and as you have seen it's not just Pale Moon that isn't necessarily catering to (very) high DPI like your setup is.

If you want to discuss the drawbacks of using HiDPI further, kindly take it to the forum at this point.
