### ISSUE TITLE
Make various WebIDL interfaces have array-like iterable results

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1546]
Because apparently writing `Array.from()` is too hard. :roll_eyes: 

And, because Mozilla dragged their feet on getting `iterable<>` support in WebIDL, this is more involved because we have to port Python code generation across.

Needs, in order:
- [x] Fix/Implement JSAPI accessors for ES6 Map/Set for WebIDL maplike/setlike [Bug 1159469](https://bugzilla.mozilla.org/show_bug.cgi?id=1159469) (JS)
- [x] Implement support for maplike/setlike in Web IDL bindings [bug 1123516](https://bugzilla.mozilla.org/show_bug.cgi?id=1123516) (DOM/Python)
- [ ] Implement support for `iterable<>` in WebIDL Codegen [bug 1085293](https://bugzilla.mozilla.org/show_bug.cgi?id=1085293) (Python)
- [ ] Expose iterator stuff on NodeList and DOMTokenList [bug 1290636](https://bugzilla.mozilla.org/show_bug.cgi?id=1290636) (DOM, trivial)
- [ ] Implement URLSearchParams `iterable<>` [Bug 1085284](https://bugzilla.mozilla.org/show_bug.cgi?id=1085284) (DOM, trivial)

The only reason we need the first 2 is because iterables are folded into maplike/setlike (and we'd probably want those anyway). Otherwise these 5 steps should have no real other dependencies and be pretty self-contained.

**Comment by wolfbeast** [comment]
If anyone has time before I do, feel free to take it.

**Comment by JustOff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1290636 ?

**Comment by wolfbeast** [comment]
Updated issue comment with a plan of action.

**Comment by wolfbeast** [comment]
Step 1 (JS part) has been implemented, this should lay the ground work for the Python/WebIDL changes.

**Comment by wolfbeast** [comment]
Even though flying blind without a Python peer to bounce things off of, I'll be working through this slowly. If anyone has more Python experience, I'd love to get their review for basic code sanity before merging into master.

**Comment by wolfbeast** [comment]
I'm going to have to throw in the towel here. This needs someone who is fluent in Python **and** has the explicit knowledge of the Python-based transcoder in use (which you won't find outside of Mozilla offices, I'm afraid).

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
