### ISSUE TITLE
Crash in video playback

### ISSUE THREAD

**Issue by mattenklicker** [MoonchildProductions/Pale-Moon#1548]
1. Set the user agent to something firefox-ish (i.e. `Mozilla/5.0 (X11; Linux x86_64; rv:52.9) Gecko/20100101 Goanna/3.4 Firefox/52.9 PaleMoon/27.6.2`)
2. Play a video on http://www.sat1gold.de/

Crashes with
```
Thread 90 "MediaPl~back #9" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd2971700 (LWP 12016)]
mp4_demuxer::MP4Metadata::GetNumberTracks (this=0x0, aType=mozilla::TrackInfo::kVideoTrack)
    at /usr/x86_64-vm-linux-gnu/tmp/portage/www-client/palemoon-27.6.2/work/palemoon-27.6.2/media/libstagefright/binding/MP4Metadata.cpp:111
```

**Comment by wolfbeast** [comment]
Unfortunately this is impossible to verify because the videos are region-locked.

**Comment by mattenklicker** [comment]
Oh, I see... Closing this then. I didn't manage it to reproduce in another way.  
Let me know, if a core dump with debug symbols would help.
