### ISSUE TITLE
Private Browsing window has issues with "Save As..."

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#155]
See: https://forum.palemoon.org/viewtopic.php?f=29&t=5267

Apparently, "Save As" in a PB window doesn't add the entry to the PB download manager list, but the file is still downloaded.
Sounds like a relatively small fix, but it needs some research to know when this was fixed in FF and what patch we need. Feel free to jump in and take this ;)

**Comment by win7-7** [comment]
Tested this. It is issue in the current stable version but not in alpha 2. Solved by Tycho.
