### ISSUE TITLE
"Open Link in New Private Window" broken in 27.7.0a2 (2017-12-16 build)

### ISSUE THREAD

**Issue by cimarronline** [MoonchildProductions/Pale-Moon#1550]
Running the new unstable build 27.7.0a2 (2017-12-16) on linux 64-bit, I noticed the "Open Link in New Private Window" in the right-click menu does nothing. Testing with a new profile shows the same behavior. The previous unstable build (2017-12-06) works properly.

**Comment by mattatobin** [comment]
Deff works on Windows.. @trav90

**Comment by wolfbeast** [comment]
Doesn't work on Windows. this is a regression; I know what's up. should be easy to fix.

**Comment by mattatobin** [comment]
OH 64bit.. Ok.. Odd it works in 32bit.. For me.

**Comment by wolfbeast** [comment]
No, it doesn't work in any arch/OS :P This is caused by 35d294a86d5fd3eb021e457f5718c0dcd9eda8fc
