### ISSUE TITLE
Stop searching AMO from the add-ons manager.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1552]
AMO really has no practical use for us anymore at this point, and only serves to cause confusion for the majority of users with nothing being available for Pale Moon that comes up.

We should disable search short-term and when search is working on our own add-ons site we should integrate it into the add-on manager.

**Comment by Atavic** [comment]
I have met many issues where users say that PM has no addons. I don't know if these people can't see the menu on the Project homepage.
Maybe the Add-ons Site should list the extensions without another click on the menu?

**Comment by wolfbeast** [comment]
With the landing of phoebus 1.9.2 and the link with AMO being broken, we now have no search results in the add-on manager, effectively solving this.
