### ISSUE TITLE
27.6.2 Build Fails with GCC 5.4

### ISSUE THREAD

**Issue by MingcongBai** [MoonchildProductions/Pale-Moon#1553]
Error message as follows...

```
15:16.06 In file included from /var/cache/acbs/build/acbs.b1irsl91/palemoon/pmbuild/dom/canvas/Unified_cpp_dom_canvas0.cpp:11:0:
15:16.06 Warning: -Wunknown-pragmas in /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp: ignoring #pragma omp parallel
15:16.06 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp:1635:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
15:16.06  #pragma omp parallel for
15:16.06  ^
15:18.98 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp: In function ‘bool mozilla::dom::ValidateRect(double&, double&, double&, double&)’:
15:18.98 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp:2420:8: error: ‘__builtin_isfinite’ is not a member of ‘std’
15:18.98    if (!std::isfinite((float)aX) | !std::isfinite((float)aY) |
15:18.98         ^
15:18.98 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp:2420:8: note: suggested alternative:
15:18.98 <built-in>: note:   ‘__builtin_isfinite’
15:18.98 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp:2420:36: error: ‘__builtin_isfinite’ is not a member of ‘std’
15:18.98    if (!std::isfinite((float)aX) | !std::isfinite((float)aY) |
15:18.98                                     ^
15:18.98 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp:2420:36: note: suggested alternative:
15:18.98 <built-in>: note:   ‘__builtin_isfinite’
15:18.98 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp:2421:8: error: ‘__builtin_isfinite’ is not a member of ‘std’
15:18.98        !std::isfinite((float)aWidth) | !std::isfinite((float)aHeight)) {
15:18.98         ^
15:18.98 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp:2421:8: note: suggested alternative:
15:18.98 <built-in>: note:   ‘__builtin_isfinite’
15:18.98 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp:2421:40: error: ‘__builtin_isfinite’ is not a member of ‘std’
15:18.98        !std::isfinite((float)aWidth) | !std::isfinite((float)aHeight)) {
15:18.98                                         ^
15:18.98 /var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas/CanvasRenderingContext2D.cpp:2421:40: note: suggested alternative:
15:18.98 <built-in>: note:   ‘__builtin_isfinite’
15:19.85 In the directory  /var/cache/acbs/build/acbs.b1irsl91/palemoon/pmbuild/dom/canvas
15:19.85 The following command failed to execute properly:
15:19.85 g++5.4 -o Unified_cpp_dom_canvas0.o -c -I../../dist/stl_wrappers -I../../dist/system_wrappers -include /var/cache/acbs/build/acbs.b1irsl91/palemoon/config/gcc_hidden.h -DNOMINMAX -DOS_POSIX=1 -DOS_LINUX=1 -DSTATIC_EXPORTABLE_JS_API -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DMOZ_GLUE_IN_PROGRAM -DAB_CD=en-US -DNO_NSPR_10_SUPPORT -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/canvas -I. -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/pmbuild/ipc/ipdl/_ipdlheaders -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/js/xpconnect/wrappers -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/ipc/chromium/src -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/ipc/glue -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/base -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/html -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/svg -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/dom/xul -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/gfx/gl -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/image/src -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/js/xpconnect/src -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/layout/generic -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/layout/style -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/layout/xul -I../../dist/include -I/usr/include/nspr -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/pmbuild/dist/include/nss -I/usr/include/pixman-1 -fPIC -D_FORTIFY_SOURCE=2 -DMOZILLA_CLIENT -include ../../mozilla-config.h -MD -MP -MF .deps/Unified_cpp_dom_canvas0.o.pp -D_FORTIFY_SOURCE=2 -Wall -Wempty-body -Woverloaded-virtual -Wsign-compare -Wwrite-strings -Wno-invalid-offsetof -Wcast-align -pipe -Wno-error -fstack-protector-strong --param=ssp-buffer-size=4 -fomit-frame-pointer -O2 -march=x86-64 -mtune=core2 -msse -msse2 -msse3 -fira-loop-pressure -fira-hoist-pressure -ftree-vectorize -specs=/usr/lib/gcc/specs/hardened-cc1 -flto=jobserver -fpermissive -fdeclone-ctor-dtor -ftree-vectorize -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2 -fno-exceptions -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe -DNDEBUG -DTRIMMED -D_FORTIFY_SOURCE=2 -pipe -Wno-error -fstack-protector-strong --param=ssp-buffer-size=4 -fomit-frame-pointer -O2 -march=x86-64 -mtune=core2 -msse -msse2 -msse3 -fira-loop-pressure -fira-hoist-pressure -ftree-vectorize -specs=/usr/lib/gcc/specs/hardened-cc1 -flto=jobserver -I/usr/include/pixman-1 -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2 -fomit-frame-pointer -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/pmbuild/dist/include/cairo -I/var/cache/acbs/build/acbs.b1irsl91/palemoon/widget/gtk/compat -pthread -I/usr/include/gtk-2.0 -I/usr/include/gtk-unix-print-2.0 -I/usr/include/gtk-2.0 -I/usr/include/atk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include /var/cache/acbs/build/acbs.b1irsl91/palemoon/pmbuild/dom/canvas/Unified_cpp_dom_canvas0.cpp
15:19.85 make[5]: *** [/var/cache/acbs/build/acbs.b1irsl91/palemoon/config/rules.mk:938: Unified_cpp_dom_canvas0.o] Error 1
15:19.85 make[4]: *** [/var/cache/acbs/build/acbs.b1irsl91/palemoon/config/recurse.mk:74: dom/canvas/target] Error 2
15:19.85 make[3]: *** [/var/cache/acbs/build/acbs.b1irsl91/palemoon/config/recurse.mk:37: compile] Error 2
15:19.85 make[2]: *** [/var/cache/acbs/build/acbs.b1irsl91/palemoon/config/rules.mk:541: default] Error 2
15:19.85 make[1]: *** [/var/cache/acbs/build/acbs.b1irsl91/palemoon/client.mk:399: realbuild] Error 2
15:19.85 make: *** [client.mk:171: build] Error 2
15:19.89 11 compiler warnings present.
```

I can provide `mozconfig` if needed.

**Comment by wolfbeast** [comment]
Did your glibc get updated recently?

**Comment by wolfbeast** [comment]
Strange thing is that that code hasn't been touched recently that I'm aware of.
Maybe more missed dependencies because of unified building?

**Comment by wolfbeast** [comment]
Ah wait, no, that was touched relatively recently. @janekptacijarabaci this was your patch 3bdf77c837423765c13da6769aaeeb2c7d54d92c -- did you forget to include the necessary headers creating this dependency hole?

**Comment by wolfbeast** [comment]
Walking the includes for dependencies: `Canvasrenderingcontext2D` includes `nsMathUtils.h` which includes `<cmath>` that _should_ have std::isfinite available as a built-in. At least according to http://en.cppreference.com/w/cpp/numeric/math/isfinite

**Comment by janekptacijarabaci** [comment]
IMHO/AFAIK - you see:
https://aur.archlinux.org/packages/palemoon/?setlang=el&comments=all
(`wolf commented on 2017-10-29 00:36` - and later/upwards)

**Comment by wolfbeast** [comment]
just post here what the problem is please. I can't constantly be redirected to random externals and it doesn't help keeping an overview.

**Comment by wolfbeast** [comment]
@MingcongBai Please provide mozconfig and your specific OS and build environment details.

**Comment by janekptacijarabaci** [comment]
> just post here what the problem is please.

I don't know exactly what is the problem in your case. I don't have a simple answer (I won't copy the entire discussion - it would also be wrong - I suppose...).

**Comment by wolfbeast** [comment]
@janekptacijarabaci  You're referring to a discussion as something to look at, so I am assuming you found that it provides concrete clues; why otherwise would you refer to it? ... Or are you just blindly linking anything that happens to have the same error in it from using a search engine? You have to understand that that is not at all helpful and just detracts from getting to the cause of this.

**Comment by wolfbeast** [comment]
At this point I'm assuming this is yet another case of glibc 2.26 breaking things, which was my initial response to ask. From what I can gather, some versions of GCC5 built on distros use the math parts or it, and others do not. If glibc is the problem, then someone needs to file a bug against glibc for not containing expected math functions that are part of the `std` built-in class. I'm not considering this a Pale Moon bug.

**Comment by janekptacijarabaci** [comment]
> so I am assuming you found that it provides concrete clues

Sure. But I don't use Linux for PM building - so I sent it complete.

But... I figure that it's probably better not to write anything.

**Comment by MingcongBai** [comment]
@wolfbeast Sorry about the delay, but our build configuration could always be found here https://github.com/AOSC-Dev/aosc-os-abbs/tree/staging/extra-web/palemoon/autobuild

**Comment by wolfbeast** [comment]
@MingcongBai your `mozconfig` used is not sane, to begin with, and you're altering preferences that are unnecessary. **That MUST be fixed if you want to carry official branding because your setup right now is not as-intended and is not following the redist license for officially-branded binaries.**

You also seem to make changes that allow bundling of extensions in your package -- are you bundling anything?

**Comment by wolfbeast** [comment]
It still doesn't answer which environment you're building in though. What glibc is used?

**Comment by MingcongBai** [comment]
> You also seem to make changes that allow bundling of extensions in your package -- are you bundling anything?

Well no. It's carried over from our Firefox with little research - I admit.

> It still doesn't answer which environment you're building in though. What glibc is used?

Glibc 2.26.

**Comment by MingcongBai** [comment]
Build still fails for the same reason a compliant mozconfig, https://github.com/MoonchildProductions/Pale-Moon/issues/1558.

**Comment by wolfbeast** [comment]
Use glibc < 2.26 -- people have seriously broken glibc by removing essential functions that are part of the C++ lib specification.

**Comment by wolfbeast** [comment]
I did file an [upstream bug](https://sourceware.org/bugzilla/show_bug.cgi?id=22650) for this; it would help greatly if you can build with an earlier version of glibc to confirm.

**Comment by wolfbeast** [comment]
The upstream bug was closed pointing to gcc as the responsible party, but gcc 5.4 has been used successfully to build Pale Moon. @MingcongBai it is imperative that we know which combination of gcc and glib works, and which does not. Can you find this out?

**Comment by MingcongBai** [comment]
Using Glibc 2.26, neither 5.4 nor 7.3 works. I will have to test 2.25 later.

**Comment by wolfbeast** [comment]
Official reply:

> Update to tip of 2.26 branch and then rebuild GCC, this is one of the issues
with macro definitions that are normally only used in C getting used by the
libstdc++ configure tests and breaking their detection of C library features.

i.e.: This is a problem with glibc needing gcc to be rebuilt against it, and not a Pale Moon issue/nothing we have any influence over.

**Comment by MingcongBai** [comment]
> Apparently glibc 2.27 also fixes this, but will still need a gcc rebuild afaict? There's more info here but that's really out of my area.

Yes, GCC needs to be built against the new Glibc. However, the current 2.26 tag does not work either - one has to build a Glibc on the HEAD of 2.26 branch.

Also at the moment, `ac_add_options --disable-startupcache` is needed in mozconfig to make the build pass.

Plus, GCC 5.4 is the only version that builds the browser, 7.2 won't work.

**Comment by wolfbeast** [comment]
So, they busted 2.26, and didn't bother to make a `-1` release to fix it and one has to build against the `HEAD` of their branch instead? Seriously. :-1:

If you would have read basic building information on our website you would have known 7.* can't build Pale Moon, and that LTO doesn't work (build bustage and/or unstable binaries). That would have saved you some unnecessary trial and error.

**Comment by mattatobin** [comment]
As much is said on the forum and this very issue tracker.
