### ISSUE TITLE
Provide an option to disable CJK character caret width auto increasing

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1555]
https://github.com/MoonchildProductions/Pale-Moon/blob/5214789d035f4e4c08899a6e281116520f605ec6/layout/base/nsCaret.cpp#L191-L193

Demo:
<img width="73" alt="demo1" src="https://user-images.githubusercontent.com/15178410/34325369-7f8e87a0-e8ca-11e7-92c2-7d8d4202ad84.png">
<img width="74" alt="demo2" src="https://user-images.githubusercontent.com/15178410/34325368-7f491576-e8ca-11e7-9e47-52fd8f50d74a.png">

It is annoying when I type mixing languages.

**Comment by wolfbeast** [comment]
Please provide a CLEAR description of the issue. I have no idea what you're trying to say, or why the quoted code is considered incorrect or what the expected result would be or what exactly is "annoying".

**Comment by zcyzcy88** [comment]
1. When caret is not located before CJK character, it will be normal width
2. When caret is located before CJK character, it will thick width
