### ISSUE TITLE
Use unbiased pixel rounding for borders.

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1556]
Same as: https://bugzilla.mozilla.org/show_bug.cgi?id=1348327

Steps to reproduce:
Make a decimal border pixel, and look it

Actual results:
Always Rounding down:
1.2 calculated pixel -> 1 rendered pixel on screen
1.5 calculated pixel -> 1 rendered pixel on screen
1.8 calculated pixel -> 1 rendered pixel on screen

Expected results:
Rounding nearest:
1.2 calculated pixel -> 1 rendered pixel on screen
1.5 calculated pixel -> 2 rendered pixel on screen
1.8 calculated pixel -> 2 rendered pixel on screen

This is how Firefox and Pale Moon works now
example_1.5px: https://cloud.githubusercontent.com/assets/15178410/24051629/a5e62aec-0b6d-11e7-9b5a-9457ee2c52d9.png

This is how IE 11+ and Chrome 58+ works
example_1.5px: https://cloud.githubusercontent.com/assets/15178410/24051628/a5db432a-0b6d-11e7-941a-82034f72b48e.png

**Comment by wolfbeast** [comment]
This will also affect caret width.

**Comment by wolfbeast** [comment]
Verified with attached test case.
[border width test.zip](https://github.com/MoonchildProductions/Pale-Moon/files/1586318/border.width.test.zip)
