### ISSUE TITLE
Question,  build Palemoon with Clang 

### ISSUE THREAD

**Issue by bn0785ac** [MoonchildProductions/Pale-Moon#1557]
GCC may be crazy (because you need use OUTDATED versions)

and if you've a ryzen cpu you may have troubles (you could say to gcc that you need haswell code,  but may fail,  and use piledriver flags ma produce faulty code)

https://wiki.gentoo.org/wiki/Ryzen

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80313

BUT clang its safe

https://www.reddit.com/r/Amd/comments/5ze26t/llvm_50_should_offer_better_amd_ryzen_performance/

and 
Archlinux had DROPPED gcc5 (only has at repos 6 and 7)

and gcc5 package its faulty (you can compile it via makepkg)
https://aur.archlinux.org/packages/gcc5/

PD if palemoon works with gcc 6/7  its fine (gcc 6+ had zen support)

**Comment by wolfbeast** [comment]
Please take this discussion to the forum in the dev board.
