### ISSUE TITLE
Rename Options to Preferences and unify location.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1561]
This is the Pale Moon version of MoonchildProductions/moebius#270

@mattatobin said there:
> Pale Moon on the other hand will likely have to maintain the status quo pretty much forever without a poll being conducted.

I think we should just go ahead and do this in Pale Moon. It's not like we are removing anything; we're just re-labeling something and making it be found in _one_ location, which only benefits being able to provide support without having to ask what O.S. someone is on when they just have a basic usage question for something that isn't at all O.S.-specific.

In addition, moving/renaming this will not interrupt workflow because changing preferences should not be a daily occurrence or part of working with the browser.

**Comment by wolfbeast** [comment]
Turns out Pale Moon actually uses all 3 terms intermixed (`about:home` has "Settings") so it's an improvement either way to reduce confusion.

**Comment by janekptacijarabaci** [comment]
@wolfbeast:
Maybe also (to think):
http://xref.palemoon.org/palemoon-trunk/search?string=settingsChangeOptions.label&filter=%5E%5B%5E%5C0%5D*%24&tree=palemoon-trunk
http://xref.palemoon.org/palemoon-trunk/search?string=editPopupSettings.label&filter=%5E%5B%5E%5C0%5D*%24&tree=palemoon-trunk
http://xref.palemoon.org/palemoon-trunk/search?string=cmd.preferencesWin&filter=%5E%5B%5E%5C0%5D*%24&tree=palemoon-trunk
http://xref.palemoon.org/palemoon-trunk/search?string=optionsTitle&filter=%5E%5B%5E%5C0%5D*%24&tree=palemoon-trunk

**Comment by wolfbeast** [comment]
No! 

Just blindly renaming everything that is called options or settings is stupid.Think for a moment. Use your brain. This should only apply to the Application Preferences. Only the first one is one that slipped under the radar; the others are most definitely NOT desired.

**Comment by janekptacijarabaci** [comment]
I did not start with it... And `to think` = `you can do just what you want` (as always - and just like the first change with `Settings`/`Options`/`Preferences`).

**Comment by wolfbeast** [comment]
...? The fact that i can make a design decision has nothing to do with making suggestions that are just completely out of scope. Sure I can do whatever I want, but at least have some sense of the scope of things.

**Comment by JustOff** [comment]
Strings changes were pushed to CrowdIn.

**Comment by tmtisfree** [comment]
I think the new "Preferences" menu string misses an ellipsis (…), as it opens up a new window (see https://en.wikipedia.org/wiki/Ellipsis#Usage_in_menus).

**Comment by wolfbeast** [comment]
Actually, I think have too many ellipses in the menus. It should only really be used if there is a **simple choice** following (confirmation or file/folder selection or similar); otherwise it just signifies switching to a different function of the program. I'll open a new issue for that.

**Comment by wolfbeast** [comment]
See #1612
