### ISSUE TITLE
Issue with a certain page element - as reported  by a user on the forum

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1562]
As the topic opener wrote here: https://forum.palemoon.org/viewtopic.php?f=3&t=17894

Problematic page is

https://monitoringpublic.solaredge.com/solaredge-web/p/site/public?name=Arno#/dashboard

Scrolling down the page a bit at Power and Energy until you find the button apply and previous/next month - there is on the left a filed with month and one with year - clicking on them should open a selection of months or years. Works in IE, Otter Browser for example.

Pale Moon just shows nothing.

The only thing which can be found in the error console when pressing on that 2 buttons is that here:

Timestamp: 01.01.2018 18:18:27
Warning: XUL box for dropmarker element contained an inline _moz_generated_content_before child, forcing all its children to be wrapped in a block.
Source File: chrome://browser/content/browser.js
Line: 13658

**Comment by janekptacijarabaci** [comment]
Pushlog (for those who are interested):
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=341344bdec8f10bf50646cd6ef2355361435cbf6&tochange=fefe2bc3e54fa101dc12e2858546ab5df2ee6d20

**Comment by wolfbeast** [comment]
As remarked on the forum: this is a good example of how not to create web content. Why not use a `<select>` element? that's what it's there for. Why trying to fudge a recreation of standard html elements?

> Pale Moon just shows nothing.

Incorrect. Pale Moon shows a 6px high div with no visible/usable content. The content can still be selected and the drop-down closed, but of course it's limited to whatever the top element is.

The error console message is pointless; that's browser internals, not web content. Please use the correct console if you want to report feedback? Web console for web pages.

**Comment by wolfbeast** [comment]
Thanks for doing the find-fix run, @janekptacijarabaci -- unfortunately nothing stands out as obvious there; no real surprise because it's all display-only static code, and it's any one's guess exactly how this code is generated. It's not even clear whether this is a CSS, DOM, HTML or JS issue.

**Comment by janekptacijarabaci** [comment]
IMHO - this is the problem: `Implement ES6 Symbol.unscopables` ([bug 1054759](https://bugzilla.mozilla.org/show_bug.cgi?id=1054759))

For example, after implementation:
![symbol unscopables](https://user-images.githubusercontent.com/2373486/34510978-b07f160a-f058-11e7-96b4-47558014a651.png)

**Comment by wolfbeast** [comment]
@janekptacijarabaci I'm not entirely sure how you took such offense to what Tobin said, but fine, I'll do the quadruple work when I find the time then and somehow do everything myself -- or maybe I'll just not do anything and mark it "solved by UXP" and put all my eggs in one basket?

Seriously though, if you have code that works and that implements parts of ES6 we don't have, please do make a PR. It doesn't have to be neat or perfect.

**Comment by wolfbeast** [comment]
Also, we really don't need tests. Let's focus primarily on functional implementations and do manual verification. Tests are going to be a time sink for stuff we don't really use anyway (have YOU ever run the test suite?)

**Comment by wolfbeast** [comment]
I'm plugging in your repo as remote and cherry-picking this, and performing a test build. Did you have the "ghosts" implemented there so I know what's included?

**Comment by janekptacijarabaci** [comment]
> On Moebius/UXP we do have to be more careful what we port because we want to avoid complicating matters more there or porting parts that are "in the wrong direction"

IMHO: This is somewhat different... than has been said (if that little difference is visible). But it's your thing, of course. If this (that) style attracts more developers... But even if it was not, of course.

> Did you have the "ghosts" implemented there so I know what's included?

`Did you have the "ghosts" (Symbol.match / species / toPrimitive) implemented` - No.
It was just the note - if anyone wanted to take it... IMHO it is probable that this could also be useful.

But - ad `maybe I'll just not do anything and mark it "solved by UXP"` - it is certainly an option, especially for more complicated things. My opinion is not important, but I personally have no problem with it.

---

It's just a little humor. if I should take things seriously, I would not be here anymore.
Though if it isn't, it can be...

**Comment by janekptacijarabaci** [comment]
> have YOU ever run the test suite?

No. It was part of it... But I keep in mind: #813 Now exceptionally so.
