### ISSUE TITLE
Rename "Restart with addons disabled" to "Restart in Safe Mode"

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1563]
What it says on the tin. Our restart in safe mode offers a lot more than just disabling add-ons; the menu entry should be renamed accordingly to be accurate.

**Comment by JustOff** [comment]
Strings changes were pushed to CrowdIn.

**Comment by janekptacijarabaci** [comment]
@wolfbeast (maybe also @JustOff):
You see also on: `aboutSupport.restartInSafeMode.label`

**Comment by JustOff** [comment]
Yes, it seems @wolfbeast  just missed it, thanks for noticing.

**Comment by wolfbeast** [comment]
Yup, sure did. I pushed the according string to en-US in `/toolkit` in the source.

**Comment by wolfbeast** [comment]
Speaking of, I'll branch off for release of 27.7, meaning that should be the last of the string changes and langpacks can be finalized whenever translators get around to it.

**Comment by JustOff** [comment]
@wolfbeast 
Ok, I filled https://github.com/MoonchildProductions/pale-moon-localization/issues/210 issue for this, please keep me informed of the schedule.
