### ISSUE TITLE
The Browser does not start -- when starting Pale Moon built from latest commits.

### ISSUE THREAD

**Issue by khronosschoty** [MoonchildProductions/Pale-Moon#1564]
Tests were done with a newly created user / new profile etc and  results were the same. 
No errors found logged in stdnerr when browser is started via terminal.
Test OS Slackware64-current
gcc 4.9.4

![imgur-2018_01_02-14 34 41](https://user-images.githubusercontent.com/2358071/34503287-5beb865a-efcc-11e7-9e57-63ae81faf755.png)
Selecting "continue in safe mode" results in this: 

![imgur-2018_01_02-14 35 11](https://user-images.githubusercontent.com/2358071/34503576-f195c7b4-efcd-11e7-993f-f9cb5c7ac903.png)

**Comment by wolfbeast** [comment]
Right, I skipped a step for the appmenu in #1561 -- would have helped if you let me know the follow-up XML error when we chatted on IRC ;)
