### ISSUE TITLE
JS - add support for Symbol.species

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1565]
https://tc39.github.io/ecma262/#sec-symbol.species

> A function valued property that is the constructor function that is used to create derived objects.

**Comment by wolfbeast** [comment]
You know, I've looked at the spec and the mention and the test case... and I have absolutely no clue what this is for, where it would be used, or why. I don't even understand the summarized description. XD

**Comment by janekptacijarabaci** [comment]
I'm sorry, I will not invent examples... But if this is enough "definition" (and examples):

---

__`Symbol.species`__

It points to the constructor value of a class, which allows classes to create new versions of themselves within methods.

``` javascript
Array.prototype.map = function (callback) {
    var Species = this.constructor[Symbol.species];
    var returnValue = new Species(this.length);
    this.forEach(function (item, index, array) {
        returnValue[index] = callback(item, index, array);
    });
    return returnValue;
}

class Foo extends Array {
    static get [Symbol.species]() {
        return this;
    }
}

class Bar extends Array {
    static get [Symbol.species]() {
        return Array;
    }
}

assert(new Foo().map(function(){}) instanceof Foo);
assert(new Bar().map(function(){}) instanceof Bar);
assert(new Bar().map(function(){}) instanceof Array);
```

`Symbol.species` provides a customisable entry-point for what type to create - you might not always want to subclass and have methods create your subclass:
``` javascript
class TimeoutPromise extends Promise {
    static get [Symbol.species]() {
        return Promise;
    }
}
```
`Symbol.species` can be used to tell TimeoutPromise to return Promise from it’s prototype methods.

Reference: https://www.keithcirkel.co.uk/metaprogramming-in-es6-symbols/

---

But it uses classes... I will not search for other examples (and than in the PR itself).

---

Ad `if this is enough "definition"`: If not, you can reject it.

I don't even use it. And I did not write those definitions (ES5/ES6...).

**Comment by wolfbeast** [comment]
I'm sorry. I didn't ask for you to provide more examples than you already did -- sorry if I wasted your time with this remark, it was not intended! I was just making a remark that I have no idea what this is and why it's in the standard, let alone who would ever use it and why...

If it doesn't bear a high risk I'm fine with merging it in regardless, but I have absolutely no way to verify that it actually does what it is supposed to do (because I don't understand it) and will just assume Mozilla's approach here is OK.

**Comment by janekptacijarabaci** [comment]
@wolfbeast
There was very little time to search - nothing happened :-)
