### ISSUE TITLE
Crash in MP4Metadata::GetNumberTracks

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1567]
As [reported on the forum](https://forum.palemoon.org/viewtopic.php?f=3&t=17906).

Most likely the website in question has some auto-playing video that is either corrupt or yanked out from under us before the meta-data can be read. Possibly video advertising considering the semi-random nature of it...
The crash address points at the following line of code crashing:
```C++
size_t tracks = mPrivate->mMetadataExtractor->countTracks();
```

Since no stack trace or dump is available, this is all we have to go on for now. Possibly adding some null checks with early exits (on `mPrivate` and `mMetadataExtractor`) would solve this issue?

**Comment by trav90** [comment]
Investigating.

**Comment by trav90** [comment]
I have been unable to reproduce this crash myself, however I have found several Mozilla reports of crashes in MP4Metadata::GetNumberTracks. PR to follow shortly.

**Comment by wolfbeast** [comment]
I'll build an unstable today with this merged in; the original reporter should be able to verify if this solves the problem.

**Comment by wolfbeast** [comment]
Can we assume this is fixed in UXP?

**Comment by trav90** [comment]
Yes it should be.
