### ISSUE TITLE
Investigate typos found by PVS studio

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#157]
For reference, see: http://www.viva64.com/en/b/0262/

Potentially, Pale Moon code could be run through this standalone tool - there is, however, no indication of any limits on the trial for the tool or how expensive it would be to purchase (a "contact us for a quote" price always reeks of "too expensive to list openly because nobody will buy it").
At the very least the published typos can be investigated (the first I already stumbled across the other day by chance and is fixed)

**Comment by squarefractal** [comment]
You could use [Cppcheck](http://cppcheck.sourceforge.net/) for performing such analyses. I'm not sure if it would be a good fit for your workflow, though.

Results of running the tool on the commits that fix typos, with settings to exclude informational messages:

* Fix Webaudio doppler calculation:
```
PannerNode.cpp style 464 Same expression on both sides of '/'.
```

* Fix misc typos
```
DataChannel.cpp style 1043 Suspicious condition (assignment + comparison); Clarify expression with parentheses.
```

**Comment by wolfbeast** [comment]
Cppcheck didn't want to run on my system, even after going through the steps of grabbing a new .net and everything, so it's obviously in need of work and I don't trust my code to it.

All typoes analyzed in the PVS studio article have been examined and fixed where needed. Closing this issue.

**Comment by squarefractal** [comment]
You actually needed to install [Visual C++ Redistributable for VS2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by wolfbeast** [comment]
> You actually needed to install Visual C++ Redistributable for VS2015. Note that the error complains about msvcp140.dll, which clearly implies a problem with a MSVC runtime.

Did I even mention a specific error? No, I didn't.
So I guess they *also* didn't include the runtime needed? XD Hah.

> In addition, fixing the few typos that are listed in that article does not mean that the codebase is free of such errors or that they will not occur in the future.

... what?
This particular issue was... see title. They have been fixed so this issue is closed.
