### ISSUE TITLE
Dailymotion.com - UA override needed

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1570]
I know that you're trying to limit these things to a bare minimum.
..but considering that dailymotion.com is the 3rd most popular video site after YouTube and Vimeo, perhaps PM should include a UA override by default?

A working one has already been posted by coffeebreak in the forum here:
https://forum.palemoon.org/viewtopic.php?f=37&t=17577/#p128779

**Comment by wolfbeast** [comment]
Is this also needed for Basilisk?...

**Comment by THEtomaso** [comment]
> Is this also needed for Basilisk?...

No, not at my end.

(Win8.1Pro,x64)
