### ISSUE TITLE
Exclude default theme from update checks

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1571]
For some reason (probably to get a ping from Firefox installations that don't have extensions or themes installed) Mozilla treats the default theme as something to include in extension update checks.

This is pointless, and causes unnecessary traffic. We need to exclude this from update checks completely.
ID is  `{972ce4c6-7e08-4474-a285-3208198ce6fd}`.

**Comment by wolfbeast** [comment]
Seems like this is a UXP only issue.

**Comment by mattatobin** [comment]
This has been mitigated on the Phoebus side of things with a no-updates response. This has the effect of suppressing the warning message presented when the timer hits.

Still, this should be tackled at some point on the platform side.

**Comment by wolfbeast** [comment]
This might also be considered a privacy concern; connections are made for this update check that should not be needed if no extensions or themes are installed.
