### ISSUE TITLE
Finally found a problem with MSE and blinking black screen videos after start system and Palemoon

### ISSUE THREAD

**Issue by SGvagon** [MoonchildProductions/Pale-Moon#1574]
Hello,

I finally found a problem with blinking black screen after start system (i have W7 PRO x64bit) , Palemoon (x86) and play any HTML5 video (for ex. on Youtube) in fullscreen . I have set 98% of CPU power (frequency) in my Power plan settings (because max frequency of my i7 4720HQ is 3,6 GHz and then my CPU temperature is too high) . But if I have 98% (still 2.5 GHz on max) videos not play smoothly and after start system and Palemoon, they are blinking black for a 5-10 sec in fullscreen.
I don't know if this problem is in only HQ Intel CPUs, but I had this problem on i7 7600HQ too.

Here is a thread on PM forum https://forum.palemoon.org/viewtopic.php?f=29&t=17840&p=131417 .

2nd problem I have, when I play any HTML5 video and then start game (Rocketleague for ex. ) , I have less FPS in game (45-55) . But if I play videos in any other browser (basilisk, firefox, chrome, ... ) , I have stable 60 FPS. Maybe MSE in Palemoon uses dedicated GPU and not only Intel GPU? (I have Nvidia GTX960M 2GB in my Lenovo Y50-70) .

There is some problem with Palemoon and Intel HQ processors? I tried wrote on Intel forum too, but they didn't know where is problem (because other browsers works) . Here is my thread on intel support from last year https://communities.intel.com/thread/119375 .

Thank you in advance. Sorry if I spamming, but this is little big problem for me and I try to help you describe it.

**Comment by wolfbeast** [comment]
Not actionable, multiple issues in a single ticket, and no details that help troubleshoot.
Please continue your discussion of this on the forum and open an issue when sufficient data is available to take action.
