### ISSUE TITLE
Linux Ubuntu 17.10 Repository missing Palemoon

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/Pale-Moon#1577]
At
http://download.opensuse.org/repositories/home:/stevenpusser/xUbuntu_17.10/
there is no PaleMoon Build.
I saw it today, because it was weird, that I was still on 27.5.2.

**Comment by trav90** [comment]
I have sent Steve a message regarding this.

**Comment by mattatobin** [comment]
Why is this being brought up on GitHub? Steve's builds nor himself, despite their stellar quality and commitment, are apart of our development team or our relese engineering process.

This is something that AT MOST should be posted to the forums or otherwise taken up with the packager them selves.
