### ISSUE TITLE
[27.6.2] Github Site Rendering Issues

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/Pale-Moon#1578]
In 27.5.2 I got the same problem.
Every addon got deactivated to test this behavior.

![bildschirmfoto zu 2018-01-13 13-55-03](https://user-images.githubusercontent.com/4518092/34906526-3538324e-f867-11e7-8da9-9a07263b151a.png)

**Comment by adeshkp** [comment]
It will be fixed in 27.7; see commits about HTML _summary_ and _details_ tags.

**Comment by wolfbeast** [comment]
Duplicate of #1497
