### ISSUE TITLE
Build with gcc4

### ISSUE THREAD

**Issue by awissu** [MoonchildProductions/Pale-Moon#1581]
Hi! 
I bumped into rpmlint erros when building rpm in OBS:
```
[ 2321s] I: Expression compares a char* pointer with a string literal.
[ 2321s]    Usually a strcmp() was intended by the programmer
[ 2321s] E: palemoon stringcompare /home/abuild/rpmbuild/BUILD/Pale-Moon-27.7.0_Release/toolkit/xre/nsAppRunner.cpp:3597
```

**Comment by wolfbeast** [comment]
rpmlint needs to go back to school.
`MOZ_APP_NAME` is a string literal, too.

**Comment by janekptacijarabaci** [comment]
I suggest:
``` javascript
-         aKey = (MOZ_APP_NAME == "palemoon") ? "firefox" : MOZ_APP_NAME;
+         if (strcmp(MOZ_APP_NAME, "palemoon") == 0) {
+           aKey = "firefox";
+         } else {
+           aKey = MOZ_APP_NAME;
+         }
```

**Comment by wolfbeast** [comment]
That would still not make sense, and is just a way to shut rpmlint up on that one particular comparison. if rpmlint would be doing its job it would then error out again on the assignment statements if it thinks MOZ_APP_NAME is a char* instead of a literal.

**Comment by awissu** [comment]
>  But I don't know if it helps... 

Thanks.
This completely solves the problem.

> rpmlint needs to go back to school.

rpmlint is based on GCC-warnings:
```
[  468s] /home/abuild/rpmbuild/BUILD/Pale-Moon-27.7.0_Release/toolkit/xre/nsAppRunner.cpp:3597:35: warning: comparison with string literal results in unspecified behaviour [-Waddress]
[  468s]            aKey = (MOZ_APP_NAME == "palemoon") ? "firefox" : MOZ_APP_NAME;
```

**Comment by wolfbeast** [comment]
> rpmlint is based on GCC-warnings:
Then rpmlint should not treat this warning as an error.

**Comment by mattatobin** [comment]
MOZ_APP_NAME doesn't always == 'palemoon' it depends where in the build system it is called.. Regardless..

RESOLVED INVALID

**Comment by wolfbeast** [comment]
I'll work around this broken check so it will shut up and people can stop complaining about it -- not the first time that's done, anyway.

**Comment by StefanBruens** [comment]
Obviously you, @wolfbeast, have a hard time understanding C code.

Both MOZ_APP_NAME and "palemoon" are string literals. As both are immutable (effectively const char[]), the compiler is free to merge both constants into one. Thats the warning GCC is giving you - the pointers on the left and the right hand of the "==" may be the same or not, but thats undefined.

You are comparing pointers to the storage, not contents. I.e.
```
const char a[] = MOZ_APP_NAME;
const char b[] = "palemoon";
if (a == b) {...}
```

Thats different to e.g.
`std::string(MOZ_APP_NAME) == "palemoon"` or the equivalent in any other high-level language.

**Comment by mattatobin** [comment]
How about we add code that breaks your static analysis more instead if you are gonna get insulting about it.

**Comment by StefanBruens** [comment]
The GCC warning is completely correct, and LLVM gives the same warning.

Your code does the following:
```
const char* a = ...
const char* b = ...
if (a == b) { /* match */ }
```
while the check you want to do is:
```
const char* a = ...
const char* b = ...
int i;
for (i = 0; i < strnlen(a); i++) {
    if (a[i] != b[i]) break;
}
if (i = strnlen(a)) { /* match */ }
```
There is no guarantee two identical string literals are located at the same address.

Read the C++ standard, 5.13.5 String Literals.

**Comment by wolfbeast** [comment]
I have absolutely no problem understanding C code. Asserting as much based on how specific compilers optimize "something" == "something" and there being no guarantee that the optimization takes place is just being abrasive for no reason. The standard actually leaves this undefined as implementation specific (see C++11 §2.14.5/12). Considering this has not caused issues so far I can only assume that compilers in general are smart enough to understand this comparison between a macro-defined static string and a string literal.

So, instead of bashing me for using a quirk, you could have been nicer and calling it a recommended enhancement of the code to guarantee more cross-compiler compatibility.
