### ISSUE TITLE
GreenManGaming.com - Search results drop-down issue

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1585]
https://www.greenmangaming.com/

The Search box's drop-down results are placed behind other objects.

Screenshot (Pale Moon v27.7.0,x64):

![palemoon-bug-gmg-pm](https://user-images.githubusercontent.com/9382674/34953929-5ea57974-fa16-11e7-81a0-1ee2d6443b35.jpg)

Screenshot (SeaMonkey v2.49.1):

![palemoon-bug-gmg-sm](https://user-images.githubusercontent.com/9382674/34953945-6fb3e30e-fa16-11e7-9f03-2bdb8d3ddd9b.jpg)

**Comment by wolfbeast** [comment]
Web design error. Both containers are given the same z-index (10) so it will depend on what order the elements happen to be rendered in which happens to turn out on top.
