### ISSUE TITLE
Closing a tab using ctrl-w doesn't add it to the recently-closed stack

### ISSUE THREAD

**Issue by medavox** [MoonchildProductions/Pale-Moon#1586]
Version used: 27.7.0, Linux x64 
Operating System: Linux Mint 17

Steps to reproduce:
---

1. Close a tab by using the Ctrl-W keyboard shortcut.
2. Check the Recently Closed Tabs list in "History -> Recently Closed Tabs >". 
    * The tab is not listed.
2. Attempt to re-open the closed tab by using Ctrl-shift-T. 
    * A different tab is instead opened -- probably the last tab to be closed with middle-click, or the close-tab button.

This also happened on version 27.5. I tried updating, but that didn't fix it.

**Comment by wolfbeast** [comment]
Unable to reproduce on Pale Moon 27.7.0-win32 -- Ctrl-W properly adds the closed tab to history.

**Comment by JustOff** [comment]
Unable to reproduce on Pale Moon 27.7.0 / Linux Mint 17 either.

**Comment by medavox** [comment]
Hmm, seems to be intermittent for me too, which may explain why I've taken so long to report this.

Sorry for wasting your time, I'll get back to you if/when I can reliably reproduce his.
