### ISSUE TITLE
Eyedropper doesn't show up under "Web Developer" in the app menu.

### ISSUE THREAD

**Issue by CybertronicToon** [MoonchildProductions/Pale-Moon#1588]
The Eyedropper option doesn't show up under "Web Developer" in the app menu. It does show up under the tools menu, however. This is a minor inconvenience.

**Comment by janekptacijarabaci** [comment]
To verify that it is set correctly:
![eye](https://user-images.githubusercontent.com/2373486/35027572-5eb79a76-fb49-11e7-9477-1d0c9af53410.png)
