### ISSUE TITLE
Add more form input types

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#159]
Pale Moon does not support the month, week, datetime and datetime-local attributes for <input> fields.

Relevant BMO bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=888324
https://bugzilla.mozilla.org/show_bug.cgi?id=825294
https://bugzilla.mozilla.org/show_bug.cgi?id=888331
https://bugzilla.mozilla.org/show_bug.cgi?id=888328

**Comment by Axiomatic-** [comment]
Also the color attribute is non-functioning, or not implemented. (In likelihood the HTML5Test is wrong, and it is not implement, yet.)

**Comment by wolfbeast** [comment]
This should all be solved by Tycho.
