### ISSUE TITLE
New UA Override needed for HumbleBundle.com

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1596]
Looks like the UA override for humblebundle.com needs to be updated.
The bundle offers are now shown as huge boxes, which covers most of the screen.
I tried changing PM's compatibility mode, and the override itself, but I didn't find one that works.
Could it be some kind of a rendering problem instead?

URL:
https://www.humblebundle.com/

**Comment by wolfbeast** [comment]
A new UA wouldn't make a difference. In good HumbleBumdle fashion, they use the latest shinies in their web layout (in this case CSS `grid`) with no regard for actually doing feature checks.

**Comment by THEtomaso** [comment]
SeaMonkey seems to be unaffected.

**Comment by wolfbeast** [comment]
Then use SeaMonkey for it.

**Comment by Sa-Ja-Di** [comment]
Seamonkey uses an engine revision which is supporting this feature. That is the reason why it works with Seamonkey.

**Comment by mattatobin** [comment]
Watch this.. SOLVED BY UXP.. need to create that lable.

**Comment by THEtomaso** [comment]
Confirmed solved by UXP! :)
