### ISSUE TITLE
Window dragging problem on recent macOS

### ISSUE THREAD

**Issue by SpockMan02** [MoonchildProductions/Pale-Moon#1598]
macOS 10.12 Sierra is affected, OS X 10.9 Mavericks is not. All versions of Pale Moon since at least 27.3 are affected (earlier versions untested). I am not sure of their OS version, but Goodydino [reported](https://forum.palemoon.org/viewtopic.php?f=57&t=17581&p=129144) the same behavior on the forum.

Clicking and dragging on the titlebar of a Pale Moon window does not move the window. Includes child windows and DOM Inspector windows, but not windows from other extensions. The workaround is to hover over the top edge of the titlebar so that the cursor becomes a vertical resizing arrow, drag the window horizontally, and then move as desired. This workaround [does not work for the Preferences window](https://forum.palemoon.org/viewtopic.php?f=41&t=17606&p=128930); it is not resizable and therefore impossible to move.

I would assume that at some point between Mavericks and Sierra, the way macOS handles titlebars/dragging windows changed. /widget/cocoa/nsCocoaWindow.mm (written in Objective-C++) seems to contain relevant code, although I don't understand a lot of it. Changes I have tried making either don't seem to affect anything or break window handling entirely.

This issue has been present at least since I started using Pale Moon, and while it does not render the browser unusable, it is annoying, so I've decided to report it here.

Suggested labels: OSX, Front-end, possibly Theme/UI and/or Help Wanted

**Comment by wolfbeast** [comment]
No significant changes will be made on Tycho. Please continue on UXP if this is still a problem with the next milestone.
