### ISSUE TITLE
Pale Moon fails to build with Clang.

### ISSUE THREAD

**Issue by Axiomatic-** [MoonchildProductions/Pale-Moon#16]
A possible bug, I have not had time to research into it, but it seems to be related to libpvx. (Tested on Linux, can anyone else confirm?) 

Can someone also please check, and see if Clang compiles Pale Moon on Windows?

**Comment by wolfbeast** [comment]
Building with clang is completely untested (it's never used for production) It's very likely that clang on windows also fails on libvpx -- libvpx is a tricky library because of some very very odd ways of going about compiling it.

**Comment by Self-Referential-Drama** [comment]
I see, well I am going to go ahead, and try to get Clang to work for compiling Pale Moon if that is alright with you.

**Comment by wolfbeast** [comment]
Absolutely!

**Comment by Axiomatic-** [comment]
Progress has been made, the issue is because libvpx uses in-line assembly code causing Clang to fail, using a compiler flag as a work around should fix that problem. (See commit: 5be82262925aac103cffd44837b01482b488c98e)

All that needs to be done is test if Clang fully builds Pale Moon, which I am planning to do soon. 

Upstream bug was labelled as WontFix. (https://code.google.com/p/webm/issues/detail?id=729)

**Comment by Axiomatic-** [comment]
Clang version 3.5.1 fails to build Pale Moon, due to an upstream [bug](http://llvm.org/bugs/show_bug.cgi?id=20879).

I have yet to test Clang 3.4, or the SVN working commit, I will try to test either one later today.

**Comment by wolfbeast** [comment]
Thanks for the updates!
Is commit you mentioned a working workaround, and only failing because of a different upstream bug, or is it actually not a working solution (in which case it would need something else)?

**Comment by Axiomatic-** [comment]
No problem, the commit is a working solution for the libvpx inline assembly code issue with Clang, the current issue with Pale Moon not building with Clang is related to mozjemalloc. (However it is a Clang upstream bug as it seems.)

```
 3:43.87 jemalloc.c
 3:46.31 fatal error: error in backend: Cannot select: 0x2b8a4a0: i64 = X86ISD::WrapperRIP 0x2af2918 [ORD=12] [ID=12]
 3:46.31   0x2af2918: i64 = TargetGlobalTLSAddress<i1* @mmap_unaligned_tls> 0 [TF=10] [ORD=12] [ID=9]
 3:46.31 In function: chunk_alloc
 3:46.32 clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
 3:46.32 clang version 3.5.1 (tags/RELEASE_351/final)
 3:46.32 Target: x86_64-unknown-linux-gnu
 3:46.32 Thread model: posix
 3:46.32 clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
 3:46.41 clang: note: diagnostic msg:
 3:46.41 ********************
 3:46.41 
 3:46.41 PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
 3:46.41 Preprocessed source(s) and associated run script(s) are located at:
 3:46.41 clang: note: diagnostic msg: /tmp/jemalloc-e8b7d5.c
 3:46.41 clang: note: diagnostic msg: /tmp/jemalloc-e8b7d5.sh
 3:46.41 clang: note: diagnostic msg:
 3:46.41 
 3:46.41 ********************
 3:46.42 
 3:46.42 In the directory  /run/media/ruby/BUILDBOT/Pale-Moon/pmbuild/memory/mozjemalloc
 3:46.42 The following command failed to execute properly:
 3:46.42 clang -o jemalloc.o -c -fvisibility=hidden -DMOZ_JEMALLOC_HARD_ASSERTS -DMOZ_TEMP_INVESTIGATION -Dabort=moz_abort -DMOZ_JEMALLOC_IMPL -DMOZ_GLUE_IN_PROGRAM -DNO_NSPR_10_SUPPORT -I/run/media/ruby/BUILDBOT/Pale-Moon/memory/build -I/run/media/ruby/BUILDBOT/Pale-Moon/memory/mozjemalloc -I. -I../../dist/include -I/run/media/ruby/BUILDBOT/Pale-Moon/pmbuild/dist/include/nspr -I/run/media/ruby/BUILDBOT/Pale-Moon/pmbuild/dist/include/nss -fPIC -Qunused-arguments -Wall -Wpointer-arith -Wdeclaration-after-statement -Werror=return-type -Wtype-limits -Wempty-body -Wsign-compare -Wno-unused -pipe -std=gnu99 -fgnu89-inline -fno-strict-aliasing -ffunction-sections -fdata-sections -pthread -pipe -DNDEBUG -DTRIMMED -mcmodel=large -include ../../mozilla-config.h -DMOZILLA_CLIENT -MD -MP -MF .deps/jemalloc.o.pp /run/media/ruby/BUILDBOT/Pale-Moon/memory/mozjemalloc/jemalloc.c
 3:46.42 /run/media/ruby/BUILDBOT/Pale-Moon/config/rules.mk:1069: recipe for target 'jemalloc.o' failed
```

I will try to see if there is any possible workarounds for now.

**Comment by wolfbeast** [comment]
Looking at the output that does indeed look like a compiler bug choking on a specific cast.
You can always build without jemalloc when using clang, of course.

**Comment by wolfbeast** [comment]
I've gone ahead and merged your libvpx fix into the master branch. I assume it won't influence other (gcc) builds - we'll find out soon enough, I guess ;)

**Comment by WorMzy** [comment]
It does. :(
```
 7:28.36 gcc: error: unrecognized command line option '-fno-integrated-as'
 7:28.36 /build/palemoon-beta/src/Pale-Moon/config/rules.mk:1125: recipe for target 'vp8_asm_enc_offsets.s' failed
 7:28.36 make[5]: *** [vp8_asm_enc_offsets.s] Error 1
 7:28.36 make[5]: *** Waiting for unfinished jobs....
 7:28.54 /build/palemoon-beta/src/Pale-Moon/config/makefiles/target_libs.mk:16: recipe for target 'libs_tier_platform' failed
 7:28.54 make[4]: *** [libs_tier_platform] Error 2
 7:28.55 /build/palemoon-beta/src/Pale-Moon/config/rules.mk:723: recipe for target 'tier_platform' failed
 7:28.55 make[3]: *** [tier_platform] Error 2
 7:28.55 /build/palemoon-beta/src/Pale-Moon/config/rules.mk:656: recipe for target 'default' failed
 7:28.55 make[2]: *** [default] Error 2
 7:28.55 /build/palemoon-beta/src/Pale-Moon/client.mk:372: recipe for target 'realbuild' failed
 7:28.55 make[1]: *** [realbuild] Error 2
 7:28.55 client.mk:172: recipe for target 'build' failed
 7:28.55 make: *** [build] Error 2
 7:28.58 118 compiler warnings present.
```

**Comment by wolfbeast** [comment]
OK, backed it out -- it'll need some conditionals for building with clang then.

**Comment by Axiomatic-** [comment]
All right, should be fixed now. Originally I thought commit 2ea3cee52a73c2e12de4accc4117db618668c2a9 should work, but it seems that Clang trys to preserve GCC compatiabilty so it applies GNUC flags, so properly fixed in commit 3d8b9d89cc8ee8f7ea8b12f8991751f8e38a3d3f. (Tested it this time, it should work for you, if not let me know.) 

I tried disabling jemalloc however it seems that the Clang bug not only effects jemalloc, it could also possibly be that this bug is specific towards my machine, so I will see if I can try it on another machine.

**Comment by wolfbeast** [comment]
Just in case, I'm making a try build on Windows from your clang-work branch just to verify the latest fix isn't impacting that (it shouldn't, but the mozbuild system can be fickle).

**Comment by WorMzy** [comment]
Compiles fine with gcc on Linux with https://github.com/MoonchildProductions/Pale-Moon/commit/5be82262925aac103cffd44837b01482b488c98e https://github.com/MoonchildProductions/Pale-Moon/commit/2ea3cee52a73c2e12de4accc4117db618668c2a9 and https://github.com/MoonchildProductions/Pale-Moon/commit/3d8b9d89cc8ee8f7ea8b12f8991751f8e38a3d3f applied on top of current master (https://github.com/MoonchildProductions/Pale-Moon/commit/91e2f2689acdf204fa5436d170b54d8bbd2400c4).

Trying to build Clang-work (+https://github.com/MoonchildProductions/Pale-Moon/commit/2ea3cee52a73c2e12de4accc4117db618668c2a9 and https://github.com/MoonchildProductions/Pale-Moon/commit/3d8b9d89cc8ee8f7ea8b12f8991751f8e38a3d3f) with clang results in a number of undefined reference warnings in Decimal.cpp and a linker error for me.

```
[...]
 3:17.47 /build/palemoon-beta/src/Pale-Moon/mfbt/decimal/Decimal.cpp:(.text._ZNK7WebCore7Decimal8toStringEPcm+0xb6): undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
 3:17.47 clang: error: linker command failed with exit code 1 (use -v to see invocation)
 3:17.47 /build/palemoon-beta/src/Pale-Moon/js/src/config/rules.mk:841: recipe for target 'js' failed
 3:17.47 make[6]: *** [js] Error 1
 3:17.47 /build/palemoon-beta/src/Pale-Moon/js/src/config/makefiles/target_libs.mk:59: recipe for target 'libs' failed
 3:17.47 make[5]: *** [libs] Error 2
 3:17.47 /build/palemoon-beta/src/Pale-Moon/js/src/config/rules.mk:664: recipe for target 'default' failed
 3:17.47 make[4]: *** [default] Error 2
 3:17.47 /build/palemoon-beta/src/Pale-Moon/config/rules.mk:723: recipe for target 'tier_js' failed
 3:17.47 make[3]: *** [tier_js] Error 2
 3:17.47 /build/palemoon-beta/src/Pale-Moon/config/rules.mk:656: recipe for target 'default' failed
 3:17.47 make[2]: *** [default] Error 2
 3:17.47 /build/palemoon-beta/src/Pale-Moon/client.mk:372: recipe for target 'realbuild' failed
 3:17.47 make[1]: *** [realbuild] Error 2
 3:17.47 client.mk:172: recipe for target 'build' failed
 3:17.47 make: *** [build] Error 2
 3:17.50 44 compiler warnings present.
```

**Comment by trav90** [comment]
I too can confirm that the current master branch builds successfully using gcc 4.7.2. I am going to attempt to build with Clang as well, and will report back later.

**Comment by trav90** [comment]
Building with Clang failed:

```
/home/palemoon/PaleMoon/pmbuild/config/nsinstall -R -m 644 "_xpidlgen/xpcom_base.xpt" "../../dist/bin/components"
In file included from /home/palemoon/PaleMoon/pmsrc/xpcom/base/nsMemoryInfoDumper.cpp:14:
In file included from ../../dist/include/mozilla/dom/ContentParent.h:10:
In file included from /home/palemoon/PaleMoon/pmsrc/ipc/chromium/src/base/waitable_event_watcher.h:13:
In file included from /home/palemoon/PaleMoon/pmsrc/ipc/chromium/src/base/message_loop.h:8:
In file included from ../../dist/stl_wrappers/deque:55:
In file included from ../../dist/system_wrappers/deque:3:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/deque:61:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algobase.h:66:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h:60:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:57:14: error: rvalue reference to type
      'typename std::remove_reference<RPCFrame &>::type' (aka 'mozilla::ipc::RPCChannel::RPCFrame') cannot bind to lvalue of type 'mozilla::ipc::RPCChannel::RPCFrame'
    { return __t; }
             ^~~
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:747:27: note: in instantiation of function template specialization
      'std::move<mozilla::ipc::RPCChannel::RPCFrame &>' requested here
      { emplace_back(std::move(__x)); }
                          ^
../../dist/include/mozilla/ipc/RPCChannel.h:223:35: note: in instantiation of member function 'std::vector<mozilla::ipc::RPCChannel::RPCFrame,
      std::allocator<mozilla::ipc::RPCChannel::RPCFrame> >::push_back' requested here
            mThat.mCxxStackFrames.push_back(RPCFrame(direction, msg));
                                  ^
In file included from /home/palemoon/PaleMoon/pmsrc/xpcom/base/nsMemoryInfoDumper.cpp:14:
In file included from ../../dist/include/mozilla/dom/ContentParent.h:10:
In file included from /home/palemoon/PaleMoon/pmsrc/ipc/chromium/src/base/waitable_event_watcher.h:13:
In file included from /home/palemoon/PaleMoon/pmsrc/ipc/chromium/src/base/message_loop.h:9:
In file included from ../../dist/system_wrappers/queue:3:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/queue:62:
In file included from ../../dist/stl_wrappers/vector:55:
In file included from ../../dist/system_wrappers/vector:3:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/vector:69:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/vector.tcc:96:9: error: no matching function for call to 'forward'
                                    std::forward<_Args>(__args)...);
                                    ^~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:747:9: note: in instantiation of function template specialization
      'std::vector<mozilla::ipc::RPCChannel::RPCFrame, std::allocator<mozilla::ipc::RPCChannel::RPCFrame> >::emplace_back<mozilla::ipc::RPCChannel::RPCFrame>' requested
      here
      { emplace_back(std::move(__x)); }
        ^
../../dist/include/mozilla/ipc/RPCChannel.h:223:35: note: in instantiation of member function 'std::vector<mozilla::ipc::RPCChannel::RPCFrame,
      std::allocator<mozilla::ipc::RPCChannel::RPCFrame> >::push_back' requested here
            mThat.mCxxStackFrames.push_back(RPCFrame(direction, msg));
                                  ^
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:51:5: note: candidate function [with _Tp = mozilla::ipc::RPCChannel::RPCFrame] not
      viable: no known conversion from 'mozilla::ipc::RPCChannel::RPCFrame' to 'typename std::identity<RPCFrame>::type &&' (aka 'mozilla::ipc::RPCChannel::RPCFrame &&')
      for 1st argument
    forward(typename std::identity<_Tp>::type&& __t)
    ^
2 errors generated.
make[6]: *** [nsMemoryInfoDumper.o] Error 1
make[6]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/xpcom/base'
make[5]: *** [libs] Error 2
make[5]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/xpcom'
make[4]: *** [libs_tier_platform] Error 2
make[4]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[3]: *** [tier_platform] Error 2
make[3]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[2]: *** [default] Error 2
make[2]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[1]: *** [realbuild] Error 2
make[1]: Leaving directory `/home/palemoon/PaleMoon/pmsrc'
make: *** [build] Error 2
```

**Comment by Axiomatic-** [comment]
@trav90 what Clang version are you using? Make sure you have CXX set to clang++ not g++ in your mozconfig. Somewhere in your mozconfig should be these two lines:
```
export CC=clang
export CXX=clang++
```

@WorMzy I will look into that.

**Comment by trav90** [comment]
I used Clang 3.3 per [this page] (https://developer.mozilla.org/en-US/docs/Compiling_Firefox_With_Clang_On_Linux).

Yes, I added both of those export lines to my mozconfig.

**Comment by WorMzy** [comment]
@Axiomatic- disregard my previous error, after a quick sanity check, I'd put "clang" as CXX, instead of clang++.

I've tried building with the correct CXX set, and it tripped up at vp8_asm_enc_offsets.c (which the -fno-integrated-as is supposed to workaround). Apparently __clang__ isn't getting defined on my system. Do I need an additional line in my mozconfig? If I override the GCC fix and add -fno-integrated-as manually, the build gets to:

```
22:41.17 ../../layout/svg/nsSVGFilterFrame.o: In function `nsSVGFilterFrame::GetFilterContent(nsIContent*)':
22:41.17 /build/palemoon-beta/src/Pale-Moon/layout/svg/nsSVGFilterFrame.cpp:(.text._ZN16nsSVGFilterFrame16GetFilterContentEP10nsIContent+0x31): undefined reference to `nsSVGFE::COMTypeInfo<int>::kIID'
22:41.17 /usr/bin/ld: ../../layout/svg/nsSVGFilterFrame.o: relocation R_X86_64_PC32 against undefined hidden symbol `_ZN7nsSVGFE11COMTypeInfoIiE4kIIDE' can not be used when making a shared object
22:41.17 /usr/bin/ld: final link failed: Bad value
22:41.17 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Clang 3.5.1

**Comment by Axiomatic-** [comment]
@trav90 odd I cannot reproduce error. See if the latest version of Clang version 3.5.1 works?

@WorMzy all right the the libvpx issue should now be settled with the latest commit (2d7ebc1e32dd82f9be96f29c6c73bda89c1d8aaa) if not let me know. 

My Clang build also stops at nsSVGFilterFrame so I will see what I can do there.

**Comment by trav90** [comment]
My particular error appears to be related to the older version of gcc on my system (CentOS 6). https://btorpey.github.io/blog/2015/01/02/building-clang/
I will attempt to point clang to gcc 4.7.2 (which I already have installed in an alternate directory, and is what I usually build Pale Moon with), and try again when I have time (probably won't be until this weekend).

**Comment by WorMzy** [comment]
@Axiomatic- That commit seems to fix the problem, and works fine for both gcc and clang builds.

**Comment by wolfbeast** [comment]
Assuming this is fixed? issue #65 also hinted at building with clang and it working, so I assume so. Please reopen if not.

**Comment by Axiomatic-** [comment]
I never followed up after saying, "I have yet to test Clang 3.4, or the SVN working commit, I will try to test either one later today." 

However I did do the tests, Clang 3.4 builds Pale Moon fine albeit the output is too verbose (fixed in the PR). 

Clang 3.5+ (3.6 being the latest stable) does not. (This includes the latest SVN build of Clang.) 

(I cannot reopen this issue, if you could that would be nice, as it seems currently though it may be a upstream bug, as added a variable definition does not fix the issue. (That, or Clang has a different way of defining global symbols.))

**Comment by wolfbeast** [comment]
Merged the pul request for the output and reopened this for follow-up.

**Comment by BitVapor** [comment]
This did solve one of the build problems I experienced on the Mac side with Xcode 6.3 (clang 3.6.0).  Another is clang 3.6.0's additions of reserved words that are used by the IDPL code generator.  I've pushed a fix for that to commit 0b0a397240b2ebbbedf3afc80a0692366702ad46.  I'm sure we could collaborate on this further.  Please let me know how I can further assist.

**Comment by wolfbeast** [comment]
Commit 0b0a397 looks fairly safe to merge right into master, so you could help by making it a pull request for easy merging on my end - we can then see if we run into any build issues on clang and non-clang as a result.

**Comment by BitVapor** [comment]
Done and done!  The only remaining issue blocking a Mac clang 3.6 build was an undefined symbol error:

```
Undefined symbols for architecture x86_64:
  "mozilla::dom::SVGComponentTransferFunctionElement::COMTypeInfo<int>::kIID", referenced from:
      mozilla::dom::SVGFEComponentTransferElement::Filter(nsSVGFilterInstance*, nsTArray<nsSVGFE::Image const*> const&, nsSVGFE::Image const*, nsIntRect const&) in SVGFEComponentTransferElement.o
  "nsSVGFE::COMTypeInfo<int>::kIID", referenced from:
      nsSVGFilterFrame::GetFilterContent(nsIContent*) in nsSVGFilterFrame.o
      nsSVGFilterInstance::BuildPrimitives() in nsSVGFilterInstance.o
ld: symbol(s) not found for architecture x86_64
```

I finally decided to tinker with the build optimization setting and found that dropping the optimization to -O1 rectified the issue.  I can now successfully build Pale Moon with clang 3.6.0 on the Mac (my recent build that I posted to the forum was created with Xcode 6.2/clang 3.5 on a Mavericks VM).

**Comment by Axiomatic-** [comment]
@wolfbeast GCC built Pale Moon without a problem. I am about to try to compile Pale Moon with the ```-O1``` switch optimization on Clang for Linux, in hope that what fixed the issue on @BitVapor side for Mac works on Linux. If it does, then I am certain that the issue is a Clang bug.

In the mean time, @wolfbeast can this question be labelled to *NIX, rather than Linux since Clang is used on Mac, and FreeBSD as the primary compiler, and on Linux as an alternative compiler.

**Comment by wolfbeast** [comment]
I've just added a new label "Other OS" to cover OSes we don't primarily support (including BSD flavors at this time) as well as the OSX label. That should cover it.

**Comment by BitVapor** [comment]
"Other OS"?  Sweet!!
/pulls Commodore 128 and GEOS diskettes out of closet

Anyway, the only mention I could find of this last issue is from a year ago.  There's no follow-up so I assumed that it's due to clang becoming more aggressive regarding optimization.

https://llvm.org/bugs/show_bug.cgi?id=19658

**Comment by Axiomatic-** [comment]
Good news Clang builds with the ```-O1``` switch, and no longer stop at ```nsSVGFilterFrame```.

Bad news is for Linux, ```-O1``` switch does not allow a full Clang compile. (Clang 3.6)
```
../../gfx/skia/SkFontHost_FreeType.o: In function `SkFontHost::GetAdvancedTypefaceMetrics(unsigned int, SkAdvancedTypefaceMetrics::PerGlyphInfo, unsigned int const*, unsigned int)':
/buildbot/Pale-Moon/gfx/skia/src/ports/SkFontHost_FreeType.cpp:(.text._ZN10SkFontHost26GetAdvancedTypefaceMetricsEjN25SkAdvancedTypefaceMetrics12PerGlyphInfoEPKjj+0xe4): undefined reference to `FT_Get_X11_Font_Format'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/buildbot/Pale-Moon/config/rules.mk:989: recipe for target 'libxul.so' failed
```

I will try a build without any optimization when I can, to see if that works on Linux. I guess bumping that bug is the proper thing to do. However as for now, @BitVapor is there a noticeable performance difference between your past builds, and current builds?

**Comment by trav90** [comment]
Current master branch builds successfully for me using clang 3.6 and the -O1 switch.

**Comment by wolfbeast** [comment]
> "Other OS"? Sweet!!
> /pulls Commodore 128 and GEOS diskettes out of closet
You're absolutely free to try, but somehow I think it's going to fail ;)

So, on Linux, clang 3.6 builds with -O1 for @trav90 but not for @Axiomatic- ?... Have you both tried a clobber build after changing the optimization parameters to verify?

**Comment by trav90** [comment]
I clobbered when I did my build.

**Comment by BitVapor** [comment]
@Axiomatic- I haven't detected a performance difference between the two optimization levels though I've not run them through any benchmarking.

**Comment by trav90** [comment]
I have seen a very noticeable performance difference when built with clang on Linux. Pale Moon takes around 15-20 seconds longer to start, and there have been a couple times now the browser has gone unresponsive when scrolling on a site I normally visit daily or very regularly (e.g. the PM forum, my bank). Neither issue occurs with my GCC build.

**Comment by trav90** [comment]
Clicking anywhere in the address bar or search bar results in a segmentation fault in my clang build (current trunk).

**Comment by wolfbeast** [comment]
Let's just not use clang to build on Linux? It's obviously problematic.

**Comment by BitVapor** [comment]
Clang does appear to be problematic--especially on Linux--but it's what I'm stuck with on the Mac.  Though there's no rush in using it for production builds on other platforms, I feel that the more eyes that are on this, the better.  Perhaps @squarefractal can weigh in on this.

**Comment by wolfbeast** [comment]
using a known working version to build binaries on Mac is the smart thing to do -- I'm not using the latest version of GCC for production on Linux either, nor the latest version of VC++ on Windows.

**Comment by BitVapor** [comment]
Agreed.  That said, I'd prefer that this ticket remain open as a central point for further clang-related collaboration despite a clang build capability on non-Mac platforms being a low priority.

**Comment by stevenschlansker** [comment]
FWIW, I have it building on
```
 0:12.49 checking compiler version... Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
 0:12.49 Target: x86_64-apple-darwin12.5.0
```
with only minor modifications, which I believe can eventually be merged back to master: https://github.com/MoonchildProductions/Pale-Moon/compare/master...stevenschlansker:macosx

**Comment by wolfbeast** [comment]
Can we consider this solved, since we have successful clang builds at the moment?

**Comment by stevenschlansker** [comment]
The 26-branch still won't build without a very hacky removal of libvpx's SSE2 support.  It's definitely possible to get it working but I am focusing my efforts on Tycho now, which builds without any such hack.

So if you only care about Tycho, yes, I think this issue is closed.  Pale Moon 26 can be hacked to build relatively easily but a clean checkout does not build.

**Comment by wolfbeast** [comment]
Support for and focus on 26 from this point forward is going to be minimal. We really do need to focus on Tycho.

I'll label this solved by Tycho then, and close it as such, with milestone 27.0
