### ISSUE TITLE
Change the way the UX caption buttons are handled on Windows

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#160]
Currently, the UX skin handles the caption buttons in different ways depending on OS.
For Windows 10, we've already had to implement our own buttons. For Windows Vista and 7, we have a decent solution cutting out the caption buttons and letting DWM handle it. On Windows 8, this still works but looks odd (especially with the 7/Vista cutout when using personas, since the Win 8 caption buttons are shaped differently).

A proper solution (with the only drawback being the "out of window glow" not being present on aero glass) would be to always draw our own buttons using XUL, and never use the DWM buttons. This avoids a good number of problems, not in the least issues where these buttons may come up black, being drawn with a delay, or not being drawn at all.

Once this is done, it'll also become possible to move to always using active layers for accelerated layers which avoids more rendering quirks that are currently present.

**Comment by Lootyhoof** [comment]
Been thinking about this one a bit more lately. I think what would be ideal would be something like:

```
@media (-moz-windows-default-theme) {
  @media (-moz-os-version: ...) {
    /* Caption buttons for each OS. Repeat this for every supported Windows version */
  }
}

@media not all and (-moz-windows-classic) {
  @media not all and (-moz-windows-default-theme) {
    /* If we're not default (or Classic), we're on a third-party theme. Provide a generic styling */
  }
}
```
The Windows 10 styling already does something similar, though honestly if this were implemented I'd recommend replacing the current non-default styling with the generic one, then we can remove that `moz-field` background on the caption buttons (that admittedly don't look great).

As for implementing the caption buttons, shouldn't be too hard. As long as SVGs are used for the icons themselves, you can style the rest with CSS. I actually implemented a caption button-style appmenu in [PMChrome](https://github.com/Lootyhoof/pmchrome/commit/67a4b88e9d30ee0a6099894ef84ad109fb262921) not that long ago, so perhaps some of that styling could be applied here.
