### ISSUE TITLE
All compilled builds put here in releases section

### ISSUE THREAD

**Issue by D0ve** [MoonchildProductions/Pale-Moon#1606]
Wold be great if will be possible to take any already compilled build here in release section!
Many thanks in advance!

**Comment by mattatobin** [comment]
No.

**Comment by D0ve** [comment]
Why?

**Comment by mattatobin** [comment]
Because GitHub is not a file hosting service and its storage is not limitless. It would also add additional release engineering. We have our own servers and infra for a reason.

**Comment by mattatobin** [comment]
Additionally, our issue tracker is not the proper place for questions. Please use the forums.

**Comment by wolfbeast** [comment]
301 -> http://www.palemoon.org/archived.shtml
