### ISSUE TITLE
Android Full Ported version of PM (FF xul UI, not Fennec natural android UI)

### ISSUE THREAD

**Issue by D0ve** [MoonchildProductions/Pale-Moon#1607]
Is it possible to port for Android that use natural UI (not Fennec poor UI) with existent PM source?
Because Fennec has its own code, and has very poor UI(natural Android UI), - it will cause some problems to support PM based on Fennec imho.
So I would like to see exactly the same PM browser with its xul UI like Linux and Win versions, but only may be with scale UI extension installed/implemented(for variouse screen sizes). And it will use existent PM source code (not Fennec).
We would hope for that Android version, please !!!

**Comment by mattatobin** [comment]
That would be a no. However, one can compile to target ARM Linux which is what the OpenPandora people have done.

**Comment by mattatobin** [comment]
Additionally, our issue tracker is not the proper place for questions. Please use the forums.

**Comment by D0ve** [comment]
I thought its easier and better than Fennec code supporting....
And popularity of Android is very high ... . And UI of natural android Fennec UI is very poor... . And the code vill be the same... . It's the idea!!!
