### ISSUE TITLE
Make the display of emoji more consistent across platforms

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1610]
Since it's a bit of a wild west when it comes to system support for emoji, we should ship an emoji font with the browser and prefer that over a system font, to provide users with a consistent display of emoji in web content.

**Comment by benrob0329** [comment]
EmojiOne is no longer free, but the fork [EmojiTwo](https://github.com/EmojiTwo/emojitwo) is.

**Comment by wolfbeast** [comment]
Looks like the assets pointed to in EmojiTwo are just raw graphics -- this will need conversion to a font format for inclusion in the browser in an efficient way (e.g. TTF). A conversion tool is required, or a community contribution of a font file here.

**Comment by Lootyhoof** [comment]
Seems [1231701](https://bugzilla.mozilla.org/show_bug.cgi?id=1231701) does this, if we're able to port. It's likely their font has updated since then, though we could always grab that from the latest source.

**Comment by wolfbeast** [comment]
I'll be tackling this next.

**Comment by wolfbeast** [comment]
The Linux part is not portable because our current state of thebes on Linux doesn't implement `PlaformFontList` structures (this is also one of the reasons why Linux doesn't yet have Unicode Range support that requires this to mix&match fonts -- the Pango back-end doesn't support that). Linux will therefore have to rely on system support for emoji -- not that I think that that is a particularly big issue.

I'll do my best to at least get this into Windows.

**Comment by wolfbeast** [comment]
Success!

![image1](https://user-images.githubusercontent.com/3359132/36454285-213f0200-1693-11e8-9cdb-de10af5ff198.png)

**Comment by wolfbeast** [comment]
We'll have to rely on system support for emoji fonts in Linux until we can move to UXP which will have the correct duct work for this.

**Comment by wolfbeast** [comment]
I'm moving us to Twemoji instead for the time being: Open license, COLR version available from Mozilla, and support for up to Unicode 10 emoji(s).

**Comment by wolfbeast** [comment]
Twemoji update in e9a220677000b9b53b4dfe739519a18b7fdce272
