### ISSUE TITLE
SVG paths with image fill properties are not rendered

### ISSUE THREAD

**Issue by SpockMan02** [MoonchildProductions/Pale-Moon#1611]
`<path>` elements with the `fill` property set to images are invisible. For example, see [this page](https://www.nationstates.net/nation=far_tholk/detail=government), which should have a pie chart with images as the slice backgrounds. Compare with [this page](https://www.nationstates.net/nation=far_tholk/detail=people), which uses colors as the slice backgrounds, and is rendered just fine.

Expected:
<img width="748" alt="screenshot 2018-02-04 12 04 31" src="https://user-images.githubusercontent.com/11634417/35781803-c05e1664-09e6-11e8-81fa-7467fefef28f.png">

Actual:
<img width="756" alt="screenshot 2018-02-04 12 04 54" src="https://user-images.githubusercontent.com/11634417/35781804-c0789746-09e6-11e8-8d98-ae657a726b5c.png">

Tested with 27.6.2 and 27.7.2 on macOS Sierra 10.12.6 and 27.7.1 on Windows 7.

**Comment by JustOff** [comment]
I can't confirm, this chart looks correct in my Pale Moon 27.7.2 on Windows.

**Comment by adisib** [comment]
Odd you can't confirm, since it is broken for me as well in Pale Moon 27.7.2 on Windows, even in Safe Mode.

**Comment by joey04** [comment]
No problem for me either. Renders exactly like the screenshot.
32bit 27.7.2 on Windows

**Comment by Sa-Ja-Di** [comment]
Another case of user agent sniffing. Needs Firefox to have in the user agent

**Comment by SpockMan02** [comment]
Ah, okay—Confirmed, Firefox user agent fixes it. I suppose this issue should be closed, and I'll ask Max Barry to look into it. ;)

**Comment by joey04** [comment]
@SpockMan02 and @adisib -- do you guys go without Firefox compatibility for your regular browsing? If so, what's that like in practice?

**Comment by Sa-Ja-Di** [comment]
@joey04 I do always. Native user agent mode - And for pages which have issues, a temporary single page override.

Works rather nice, i can not complain.

**Comment by joey04** [comment]
Thanks for the response. That's cool non-Firefox mode works for you. How often does breakage like this issue happen?
(I'm just curious; I won't be turning off Firefox compatibility.)

**Comment by wolfbeast** [comment]
Could you guys please take the chatter to the forum? Thanks.
