### ISSUE TITLE
Remove superfluous ellipses in menus

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1612]
There are currently many menu entries that have ellipses. While for some it would make sense, when there is a simple choice following (a confirmation, simple one-shot dialog, or file/folder selection or similar), it should not be used if there is a complex feature following the menu choice.

`Print` is a special case to indicate that the user will be presented with options before initiating a print (both methods are equal in use and should be distinguished).

We should remove ellipses from any menu entries in the AppMenu and main menu that do not have a simple choice following them.

**Comment by tmtisfree** [comment]
The ellipsis usually indicates that a new window or dialogue will open on menu selection (except for the "New window" string which is self explanatory), and on which the user will have to do something.

Complexity, or supposed complexity (which is a matter of judgment anyway), has nothing to do with this ergonomic and visual indication of flow breaking.

**Comment by wolfbeast** [comment]
I don't want to start an argument but this would make it also directly related to how this would be implemented then. e.g. in-content vs XUL window. the user flow would be the same, but one would have an ellipsis, the other would not. Of note: the add-ons manager is equivalent to the preferences in terms of the type of function is performs for the user.

So you can't use the "opens a new window or dialog" as a hard criterion here. I think an ellipsis is only in place if you are being directly asked a one-shot continuation of what the menu entry is for, and should NOT be used when it opens a new window with a distinct, complex function. Compare also "Organize bookmarks" and "Show all History" that neither have an ellipsis, nor perform a direct continuation of the task by asking the user for input directly related to the task. So I think the changes I made are all correct in that case, except for _maybe_ `"set up sync"`.

**Comment by tmtisfree** [comment]
Browsing a tree to "Open..." a file 10 levels deep is hardly a "one-shot continuation" criterion at least quantitatively (worst, on Windows at least, you can rename/delete/etc. files while still in the opening dialog) and it also needs no direct user input other than mouse clicking, which is no different of what web browsing is all about (clicking) and what users usually do in "Organize bookmarks" and "Show all History" windows. So theses criteria are not determinant and/or specific enough to determine if an ellipsis is required or not.

I don't quite follow what you mean by "a direct continuation of the task" as each very new action by a user (be it in menu or elsewhere) is a break from the previous task.

So in my opinion and according to the guidelines linked above, "Organize bookmarks", "Show all History" and "Preferences" are each missing an ellipsis as there is objectively no (functional or whatever) difference between clicking a file in the Open file dialog and clicking a link in the History window.

I agree though that in some edge cases (eg your settings open tabs instead of windows) the ellipsis is somewhat useless.

**Comment by wolfbeast** [comment]
*sigh* you're not at all getting what I am saying. The ellipsis is a continuation character, also linguistically speaking. That is its definition and purpose. 
Open a file is one additional operation. doesn't matter where that file is, it's still just "browsing for a file". 
The menu choice "Open a file" is continued in the file open dialog where you perform one task: open a file.
Same with "Save As", same with "Print", but not with "Preferences" or "Add-Ons" or "Show history".

If you still don't get it then I'm sorry, but most of these ellipses ARE superfluous from a software perspective; if they aren't resulting in one contained task, they should be removed.

**Comment by tmtisfree** [comment]
A new task subsequently performed from whatever menu you clicked on is by definition a "continuation" of the act of clicking to do the action described in the menu, that is a kind of circular logic or truism, so this is not what the ellipsis is for, else we should put ellipsis in all menus and be done.

As an ex., I can paraphrase what you wrote as 

> Therefore: the menu choice "Show history" is continued in the history window where you perform one task: choose a history link.

This sentence is logically coherent, has a meaning, is easily understandable and is perfectly equivalent to yours, so "Show history" should have an ellipsis as "Preferences" and "Organize bookmarks" according to your position.

Rather the ellipsis is a mark to indicate to the user that he has to perform an additional operation, whatever its complexity or any subjective quality, which will disrupt his flow by the opening a new window/dialog element as per the guidelines say clearly.

"Software perspective" has nothing to do with that, only ergonomics: that is, the coherent arrangement of things to act clearly and safely. That is the purpose and sole aim of putting an ellipsis in a menu.

**Comment by wolfbeast** [comment]
Let's agree to disagree then. You're not willing to view this from a practical/UI perspective, dismissing the fact that software design is different from documentation, and I'm not willing to use semantic reasoning for something pragmatic. If you want to make a browser that is "safe and coherent by putting ellipses everywhere and the kitchen sink" then you're welcome to do so, but not in this project.

I invite you to examine any choice of software over the past few decades and see how many of them have ellipses in **every** menu entry that "opens a new window or dialog". Then also consider expectation of an intuitive UI in your argumentation.

Also: An ellipsis is a mark of continuation, exactly because the underlying input request is omitted from the menu. It's not a disagreement, but it stresses a different aspect of the same thing. This difference in weight is exactly where the reason for adding or omitting an ellipses is decided.

I think we're done here.

**Comment by tmtisfree** [comment]
It is not a matter of opinion. Ergonomics is about providing technical solutions to technical problems: that (the written guidelines) is pragmatism built on history of designing UI.

You view the problem from an engineering-only perspective, and the result according to your own made-up rule got you already an exception ("Print") and a _maybe_ exception ("Sync"). I and everybody else designing GUI (the U is for User remember) view it as an ergonomic problem: how to warn user that his thinking flow will be disrupted.

> INCORRECT

You can also rename, delete, search, reorganize, etc. files and folders in the "Open file" and the "Save as" dialogs. Will you remove the ellipsis then? We both know the response.

**Comment by tmtisfree** [comment]
A small point about the superfluous ellipsis in in-content (tab) versus window UI: that is a programming limitation which could easily be resolved like singular/plural programming, a matter of a conditional if/then based on UI expectation (tab/window) rather than number (n=1/n>1).

**Comment by JustOff** [comment]
I have to say that I'm also feel a bit confused by this changes, but I don't think they are so important to get involved in the discussion. 

I'm going to push the results to CrowdIn soon.

**Comment by wolfbeast** [comment]
I can continue and provide valid counter points to each thing brought up here but it's a glorious waste of my time so I'm not going to.

**Comment by wolfbeast** [comment]
For completeness, the following sentence from Microsoft's menu guidelines at https://msdn.microsoft.com/en-us/library/dn742392.aspx provides a compact, easy to follow rule:

> Using ellipses

> While menu commands are used for immediate actions, more information might be needed to perform the action. Indicate a command that needs additional information (including a confirmation) by adding an ellipsis at the end of the label.

Now, let's read this sentence properly, and the keyword is "immediate action" there:
- We're only talking about menu items that have an immediate action; otherwise, no ellipses.
- We're only talking about menu items that require additional information for that immediate action.

From this follows that any menu choice opening a window with multiple possible actions by design, unless it is commonly used to perform one task only, should _not_ have an ellipsis in its label.

They even specifically clarify it's _not_ to be used just whenever a new window is opened:

> This doesn't mean you should use an ellipsis whenever an action displays another window—only when additional information is required to perform the action. For example, the commands About, Advanced, Help, Options, Properties, and Settings must display another window when clicked, but don't require additional information from the user. Therefore they don't need ellipses.

> In case of ambiguity (for example, the command label lacks a verb), decide based on the most likely user action. If simply viewing the window is a common action, don't use an ellipsis.

All argumentation above aside, I hope this at least clarifies my decision to make these changes, and lifts any confusion.
