### ISSUE TITLE
crashes on live pixiv.

### ISSUE THREAD

**Issue by jj-7** [MoonchildProductions/Pale-Moon#1613]
-----
Tested on a clean profile (with ublock origin only) in "restart with addons disabled" or should I call it safe mode now?
Go to https://sketch.pixiv.net/lives and click any stream (requires an account).

Problem signature:
Problem Event Name: APPCRASH
Application Name: palemoon.exe
Application Version: 27.7.2.6604
Application Timestamp: 5a7064d7
Fault Module Name: xul.dll
Fault Module Version: 27.7.2.6604
Fault Module Timestamp: 5a7065af
Exception Code: c0000005
Exception Offset: 0000000000f567c6
OS Version: 6.1.7601.2.1.0.256.28
Locale ID: 3081
Additional Information 1: dd08
Additional Information 2: dd080f8f11759d2342a4bad3b21f82b4
Additional Information 3: 169e
Additional Information 4: 169e0d1bb2a58f53df66efe4d86df018

**Comment by Lorienna** [comment]
- mozilla-central pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=03297f8c28a08d2b39a252c7b368524d9e69da69&tochange=1dbe350b57b17ec1ce2887441b79c6f51b429378

- tinderbox mozilla-inbound pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=772dbb329a151adf98805a3b0cd5c713f5733e08&tochange=be37af7fca760487e789c13d21c748586e495db6

- [bug 1181981](https://bugzilla.mozilla.org/show_bug.cgi?id=1181981) - mozGetMediaSource doesn't work on youtube videos

**Comment by wolfbeast** [comment]
@trav90 I'll be using this forced hardcoding instead as it seems it will play more MSE videos that way instead of just working around the crashes.
The reason we couldn't find this is because it was spun off from a still unresolved/locked sec bug (probably for the same crashes)
