### ISSUE TITLE
Parent element line-height inflated when [minimum font size] on

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1615]
Demo: https://jsfiddle.net/z631k50t
Here is no `em`.

[minimum font size] off
<img width="200" alt="good" src="https://user-images.githubusercontent.com/15178410/36135641-7c9ccd52-10c7-11e8-9a12-464d7df16ac6.png">

[minimum font size] on
<img width="200" alt="bad" src="https://user-images.githubusercontent.com/15178410/36135728-e28a5576-10c7-11e8-9ade-023b543b4498.png">

**Comment by wolfbeast** [comment]
Same as #1614 -- more information needed.
Likely duplicate.

**Comment by zcyzcy88** [comment]
Look closely: parent element is `font-size: 1px`, is not `font-size: 0`

**Comment by wolfbeast** [comment]
Duplicate issue, rooted in the same calculation.

**Comment by wolfbeast** [comment]
Actually not a duplicate, but as-intended (because we cannot assume to know why there would be a specific larger line height stated for a specific font size, and need to scale proportionally).

**Comment by zcyzcy88** [comment]
No, here is `50px`, not `5` or `5em`.
`px` is absolute value, should not be inflated.

**Comment by wolfbeast** [comment]
No, you misunderstand. It doesn't matter what unit is used if it's a length unit (not percentage). Line heights need to be inflated to cater to the increased font size, or fonts will become clipped.
