### ISSUE TITLE
Linux version does not respect "new tab" option

### ISSUE THREAD

**Issue by whitebyte** [MoonchildProductions/Pale-Moon#1616]
Starting from PM 27.7.0 it's impossible to change "new tab behaviour" option. Related forum topic: https://forum.palemoon.org/viewtopic.php?f=37&t=18351

This is Linux-only issue, Windows version seems to be unaffected.

**Comment by wolfbeast** [comment]
This might already have been fixed through [45f933d] but a new unstable will have to verify.

**Comment by JustOff** [comment]
I can confirm this issue on Linux, and unfortunately I doubt it's related to non-ascii URLs in `browser.startup.homepage`.

**Comment by JustOff** [comment]
It seems it somehow related to the fact that `chrome://branding/locale/browserconfig.properties` isn't available on Linux.

**Comment by wolfbeast** [comment]
> It seems it somehow related to the fact that chrome://branding/locale/browserconfig.properties isn't available on Linux.

Which is what getComplexValue, among other things, should avoid errors around. At least if I go by the MDN docs.

**Comment by mattatobin** [comment]
`browserconfig.properties` not being on linux is impossible. It HAS to be there.

**Comment by whitebyte** [comment]
> It seems it somehow related to the fact that chrome://branding/locale/browserconfig.properties isn't available on Linux.

It is available on my system, but the bug persists.

**Comment by JustOff** [comment]
> `browserconfig.properties` not being on linux is impossible. It HAS to be there.

![vmware_2018-02-18_01-01-04](https://user-images.githubusercontent.com/340855/36346449-aa94a71c-1436-11e8-9886-0d3cc7863de3.png)

**Comment by mattatobin** [comment]
Where is that build from?

**Comment by JustOff** [comment]
It's the official release build, obtained through the pminstaller.

**Comment by JustOff** [comment]
Well, now I got it: `tabs.js` logic just don't work properly when `browser.preferences.instantApply` is `true` (default on Linux & OSX). The fix should be simple, I'll do it tomorrow, if no one does it until then.

**Comment by wolfbeast** [comment]
Ugh. I didn't think about `instantApply` when writing the functions, no.

**Comment by wolfbeast** [comment]
Not sure when @trav90 will get around to building the next unstable to test, but Windows versions have been built.

**Comment by JustOff** [comment]
I tested my patch by setting `browser.preferences.instantApply` to` true` using the Windows build. I think this emulates the Linux build behavior quite accurately. However, independent confirmation in the native environment would be helpful, of course.

**Comment by trav90** [comment]
Kicking off a build now. New unstable build will be published within the next couple hours.

**Comment by trav90** [comment]
New unstable 27.8.0a1 (64-bit) (2018-02-18) has been published.
