### ISSUE TITLE
Doorhangers overflow the browser window (and drawing behind vertical taskbar as a result)

### ISSUE THREAD

**Issue by PatchyKnowly** [MoonchildProductions/Pale-Moon#162]
I first posted this over at /gorhill/uMatrix, but apparently addon popup position is controlled by the browser and not the addon.

OS: Vista x64
Browser: Pale Moon x64

For some reason the addon popup sticks out of the browser window, and is only bounded by the edge of the monitor and not the taskbar. resulting in it being obscured. This doesn't appear to happen in Australis in the 2nd screenshot where it appears to draw away from the nearest monitor edge, generally keeping it inside the browser window.

![zxcxv](https://cloud.githubusercontent.com/assets/8378762/9721147/c0e544f0-558d-11e5-84af-895bf18d89af.png)
![150907-18 02 41](https://cloud.githubusercontent.com/assets/8378762/9721148/c464ac6a-558d-11e5-926e-57d65d6b1131.png)

**Comment by wolfbeast** [comment]
Thanks for the report. A quick search on the Mozilla bug tracker didn't find anything useful so far. If someone can find the relevant bug where this was changed in Firefox, we can have a look at the relevant code changes.

**Comment by win7-7** [comment]
Solved by Tycho. I don't use this add-on personally. I merely did quick test and it functions correctly in Tycho. @PatchyKnowly can you confirm this so issue can have label "Solved by Tycho"?

**Comment by PatchyKnowly** [comment]
I don't have Vista on any devices anymore, so I'm unable to test this, sorry.

**Comment by wolfbeast** [comment]
Assuming this is solved by Tycho based on the previous comments.
