### ISSUE TITLE
Developer tools -> theme settings is not saved

### ISSUE THREAD

**Issue by whitebyte** [MoonchildProductions/Pale-Moon#1624]
PM 27.7.2 64bit, Linux

Press F12, go to "toolbox options", change theme from "light" to "dark". After browser restart the theme will be set to "light" again.

**Comment by JustOff** [comment]
I can't confirm this neither on Linux, nor on Windows. Make sure that you exit the browser normally, not by kill its process.

**Comment by whitebyte** [comment]
Hmm. It seems that the bug caused not by PM itself but by Advanced Night Mode plugin, that, even being turned off, for some reason prevents theme switching.

Closing this.

**Comment by mattatobin** [comment]
Rule NUMBER 1.. Check extensions first ;)

**Comment by JustOff** [comment]
@whitebyte I can't confirm the problem with Advanced Night Mode either. Feel free to [fill an issue against ANM](https://github.com/JustOff/advanced-night-mode/issues) if you can provide exact steps to reproduce.
