### ISSUE TITLE
No copy-Paste from images into Facebook/Imgur possible

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1627]
As the user in this thread ( https://forum.palemoon.org/viewtopic.php?f=3&t=18514&p=136254#p136253 ) has posted, he is unable to copy-paste pics into Facebook or imgur.

Anyone has any ideas what is going on or to solve that? ;)  I can confirm that btw - tested with a Firefox user agent and Native Pale Moon one. Unable to copy-paste pictures into a Facebook post. Testing other browsers, works of course (as usual) with Chrome - which i know - means nothing in the end ;)

**Comment by wolfbeast** [comment]
Pasting actual image data from the clipboard isn't supported right now.

**Comment by wolfbeast** [comment]
Copying into a facebook post also works. Imgur doesn't.

**Comment by janekptacijarabaci** [comment]
It is associated with this bug: [Bug 906420](https://bugzilla.mozilla.org/show_bug.cgi?id=906420).
Also https://forum.palemoon.org/viewtopic.php?f=3&p=117639#p117639

**Comment by Sa-Ja-Di** [comment]
Sounds more like something which will be fixed in UXP - if one looks at that bug ;)

**Comment by saurabhdua82** [comment]
Why is the observation over Facebook varying among users? 
How come a few able to paste the image data onto Facebook with success & some not ?
Any ideas?
Nevertheless, consensus has emerged for Imgur one atleast ! :-)
Thanks.

**Comment by janekptacijarabaci** [comment]
> Why is the observation over Facebook varying among users?
> How come a few able to paste the image data onto Facebook with success & some not ?

AFAIK: Everyone is talking about something else.

What works for me:
Copy a file (image) SHORTCUT to the clipboard.

Does not work for me:
Copy the CONTENTS of the image file to the clipboard.

...and paste this image to Facebook (inputs - timeline... etc.).

**Comment by wolfbeast** [comment]
No, copying image data to the clipboard and pasting it in facebook works.

**Comment by janekptacijarabaci** [comment]
> No, copying image data to the clipboard and pasting it in facebook works.

OK, so it's something different (probably in settings).

However currently I cannot look for it...

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
