### ISSUE TITLE
Pale Moon is unable to play mov format videos on Google+

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1629]
https://forum.palemoon.org/viewtopic.php?f=3&t=18483&p=136298#p136037

and

https://forum.palemoon.org/viewtopic.php?f=3&t=18483&p=136298#p136292 - here a video link which does not play at all in a fresh stable portable

Seems Pale Moon has trouble with the mov format what other browsers (also IE) can play without issues.

**Comment by wolfbeast** [comment]
mov? You mean Apple Quicktime? Why are people still using that format?
Are you sure this isn't some broken google UA sniffing defaulting to .mov instead of normal video?

for mov, you need (and always have needed) the quicktime plugin.

**Comment by Sa-Ja-Di** [comment]
Yeah, it is mov. When you download the video over the playback link after playback fails - you get a mov file.

**Comment by janekptacijarabaci** [comment]
IMHO: This problem solves - Add trailing slash to referer header when referrer policy is set - [bug 1186072](https://bugzilla.mozilla.org/show_bug.cgi?id=1186072)

Some test/personal branch/commit (with the expected result):
[tree@network_referrer_slashes_1](https://github.com/janekptacijarabaci/Pale-Moon/commit/b7174ca842a6c0d5af4266d7b47143d3ba21a4f4)
