### ISSUE TITLE
Reactos 

### ISSUE THREAD

**Issue by blackcrack** [MoonchildProductions/Pale-Moon#1637]
Hi,

"The procedure entry point GetTickCount64 could not be located in dynamic link libary KERNEL32.dll "
Reactos Daily Build 20180308-0.4.9-173
"The procedure entry point GetTickCount64 could not be located in dynamic link libary KERNEL32.dll "

please read : 
https://jira.reactos.org/browse/CORE-14453

best regards
Blacky

**Comment by wolfbeast** [comment]
Sorry but it's not our problem that ReactOS still targets an obsolete kernel version to simulate.

**Comment by blackcrack** [comment]
who search for problems, it be an possible for supporting reactos to make able to runs 
Pale Moon also on Reactos.. well, if you are so "cordial" and cooperationful.
thank you for your Support .. bye...

"it's not our Problem" tzzhh....

**Comment by wolfbeast** [comment]
It's not possible for us to support ReactOS as long as their goals do not align with current-day windows compatibility.

If you'd still like to see a Pale Moon based browser on ReactOS the solution is simple: fork it, and re-brand it. maybe work together with the people on our forum who are working on an XP compatible fork. But our core development cannot and will not target NT5 any longer.
