### ISSUE TITLE
Virustotal.com - issue when up or downvoting

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1638]
Test link is here:

https://www.virustotal.com/#/url/3025dbde53e46da71548c46092fe08e99d1e1326f5b6f32b76e8e92c33b9ab3b/community

You have to be registered that you can use the vote feature. When clicking on the up or down-vote buttons one gets a failed to vote.

And in the web console the only error entry is something like that:

POST  XHR  https://www.virustotal.com/ui/urls/https://www.virustotal.com/3025dbde53e46da71548c46092fe08e99d1e1326f5b6f32b76e8e92c33b9ab3b/votes [HTTP/2.0 405 Method Not Allowed 213ms]

Works with IE11 for example - or Otter-Browser - tested with both to make sure page is not broken out of the box.

Tested in Pale Moon various user agents, still the same issue.

Tested with unstable latest, 64 Bit ;)

**Comment by wolfbeast** [comment]
I use that site regularly and never have an issue up or downvoting.

**Comment by Sa-Ja-Di** [comment]
@wolfbeast Tested with a fresh portable unstable and a new profile with it, error still happens

**Comment by wolfbeast** [comment]
The url posted is not the normal virustotal site -- it seems to be a mobile specific one.
the correct URL for that site for desktop use is https://www.virustotal.com/en/url/3025dbde53e46da71548c46092fe08e99d1e1326f5b6f32b76e8e92c33b9ab3b/analysis/

**Comment by Sa-Ja-Di** [comment]
Your link works, thanks :D
