### ISSUE TITLE
Web page image viewer issue

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1643]
Description:
An image viewer opens, but closes immediately.

URL:
`https://annasophiarobbnews.com/`

How to reproduce:
Go to the page above, scroll down a bit and click on one of those "GLAAD Media Awards" pictures.

Other info:
Works like intended with SeaMonkey.

**Comment by mattatobin** [comment]
Why are you filing this here?

This belongs on the forums. Stop posting to the issue tracker.

**Comment by wolfbeast** [comment]
Wordpress. 
Also, clicking the same image again will make it stay open. No errors, so nothing to investigate.

**Comment by THEtomaso** [comment]
I finally managed to make one of those pictures stay open, after clicking on it 17 times!
Don't understand how this doesn't classify as a bug.
