### ISSUE TITLE
Content Security Policy: Couldn't process unknown directive 'manifest-src'

### ISSUE THREAD

**Issue by Gpower2** [MoonchildProductions/Pale-Moon#1646]
When opening Yahoo Mail, this error appears in the browser console and most page's actions are not actionable, eg. pressing the settings button doesn't open the menu.

**Comment by wolfbeast** [comment]
Yahoo not functioning isn't related to CSP. disabling CSP still makes it not function.

**Comment by wolfbeast** [comment]
`e.parentnode is null` seems to be the issue with yahoo being broken, which is in a minified blob, which means Yahoo will respond with "use a supported browser or go away".

**Comment by Gpower2** [comment]
Hmm... I just didn't see any other errors in the browser console, so I assumed it was because of this.
Silly me! :p

**Comment by wolfbeast** [comment]
This should have been reported on the forum. Not a confirmed issue with CSP, nothing actionable on our side.
