### ISSUE TITLE
Valid EcmaScript identifier characters

### ISSUE THREAD

**Issue by Ud71p** [MoonchildProductions/Pale-Moon#1647]
let ℍ = 1; // Works.
let 𝕃 = 1; // SyntaxError: illegal character

𝕃 and ℍ are in the same unicode category Lu (Letter, Uppercase), and should both be accepted in {Java,Ecma}Script variable names.

**Comment by mattatobin** [comment]
They look blank here why are they allowed at all?

**Comment by wolfbeast** [comment]
@mattatobin it's insane, but according to the standard many extended Unicode characters that are categorized as "letters" are allowed. That doesn't mean that all browsers _accept_ it in their current implementation, though.

**Comment by janekptacijarabaci** [comment]
Ad `Solved by UXP` - IMHO it is not right. `Solved by moebius` yes, but for UXP (now): [pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=0534254e9a40b4bade2577c631fe4cfa0b5db41d&tochange=0ddfec7126ec503b54df9c4b7c3b988906f6c882)

**Comment by wolfbeast** [comment]
oh? hm.

**Comment by wolfbeast** [comment]
Nothing in that pushlog seems to be obviously related.

**Comment by janekptacijarabaci** [comment]
[Bug 1197230](https://bugzilla.mozilla.org/show_bug.cgi?id=1197230) - Correctly tokenize valid JS names that use non-BMP code points
(SyntaxError: illegal character when using Unicode mathematical alphanumeric symbols as variable name)

__Some test/personal branch:__
[tree@js_variable_unicode_1](https://github.com/janekptacijarabaci/UXP/tree/js_variable_unicode_1)
(I've created the new build (x32, Windows) and tested (shortly))

Before:
![char_1_1](https://user-images.githubusercontent.com/2373486/37566639-f000de18-2ab3-11e8-823d-136d68825a5d.png)
![char_1_2](https://user-images.githubusercontent.com/2373486/37566640-f027a1f6-2ab3-11e8-81d9-95cd0c7f23ad.png)

After:
![char_2_1](https://user-images.githubusercontent.com/2373486/37566642-f4afe814-2ab3-11e8-9968-2124d4b0831e.png)
![char_2_2](https://user-images.githubusercontent.com/2373486/37566666-56f228ca-2ab4-11e8-8c55-e890e06940a3.png)

**Comment by wolfbeast** [comment]
Ugh, thank you Mozilla for being nondescript. "Handle non-BMP identifier."

**Comment by wolfbeast** [comment]
OK, so, if you ask me, this is actually a spec bug, but too late to do anything about it. The symbols indicated are actually mathematical symbols and should _not_ be classified as _letters_ even if they are shaped after them.

**Comment by wolfbeast** [comment]
Solved in UXP T2 now. This won't be addressed further on Tycho because of the nature of the issue.
