### ISSUE TITLE
Prevent update PRIMARY selection when attempting to paste new url/text at addressbar

### ISSUE THREAD

**Issue by tanertas** [MoonchildProductions/Pale-Moon#1649]
I'm having an annoying issue when trying to paste a new url  or text to address bar via middle click (X11 PRIMARY selection) on Linux. For practical reasons, X11 PRIMARY selection is a defacto standard.

If any url or text is existing on address bar (which is the most case) and if you are trying to alter this information via middle click (PRIMARY paste), the information stored on PRIMARY selection is getting replaced by the text on the address bar, thus duplicates the text on address bar instead of pasting new one.

In proper operation, when clicking at address bar, PPRIMARY selection (X11 clipboard) shouldn't be updated until user selects the url/text intentionally. This behavior is well implemented in Chromium.

I tried to disable **clipboard.autocopy** option at about:config but it disables all x11 clipboard operations globally.

**Comment by wolfbeast** [comment]
This behavior was changed a long time ago to focus on current day (modern) clipboard usage, after getting feedback from our user base. It will not be changed to a different default now.
Please see the forum for changing the relevant preferences if you are stuck with using the old UNIX primary method.

**Comment by tanertas** [comment]
I wasn't asking about to change default clipboard usage. We can still prevent to updating of PRIMARY selection when clicking on address bar while all other things remains untouched. There's really no sensible reason to update PRIMARY selection. This issue is a side effect of auto-marking the text at address bar and has nothing to do with CTRL-C/CTRL-V routine.

**Comment by wolfbeast** [comment]
This isn't a bug, it's by design. You can change the default selection behavior to cater to primary buffer use if you have to: `browser.urlbar.clickSelectsAll` and `browser.urlbar.doubleClickSelectsAll`.

**Comment by tanertas** [comment]
I couldn't find any solution before submitting this report. Quite interesting to see that such config options exist. browser.urlbar.doubleClickSelectsAll worked for me. Thanks.
