### ISSUE TITLE
Firefox and Browsers based on it are not releasing memory after closing Tabs!

### ISSUE THREAD

**Issue by DavinderMaverick** [MoonchildProductions/Pale-Moon#165]
I created a new browser profile for this test and no addons and nothing! I used http://people.mozilla.org/~wmccloskey/mem.htm for testing! It opened 36 tabs! Then I closed all the tabs but one! And took memory measurement after waiting for even 20 mins! I have also provided task manager screenshots for inspection! I also tried this test with Firefox Fork Light and Palemoon but got the same result! After closing tabs memory was not released! Download the zip file below for all reports:- http://wikisend.com/download/626368/Memtestfirefox.zip Also, I am not able to create account on Bugzilla! " User account creation has been restricted. "

Based on some suggestions i tried the test with these settings! But, still the memory was not releasing! Limit max closed tabs you can reopen: Set the value of `browser.sessionstore.max_tabs_undo` to something like 6 if you do not undo tab closure frequently using <Ctrl-Shift-t>.

Limit maximum pages in session history: This indicates how many URLs you can traverse using the Forward or Back button in a browser session. Search the about:config page for `browser.sessionhistory.max_entries` and set it to a lesser value from the default 50. I use 5.

Tested again with these settings Still no effect!!!

Limit memory cache size: Add a new integer in the about:config page named `browser.cache.memory.capacity`. Set it to a lower value in KB. For example, for 100MB I use the value 102400. Not even with this!

>I hope *palemoon* community can help me with this!

**Comment by wolfbeast** [comment]
I'm not sure what your issue is, but you're obviously not understanding how these browsers use and manage memory. The preferences you changed would also not impact what you are looking at, at all.
If you want to discuss this, please go to http://forum.palemoon.org/ If you have a concrete issue to report, feel free to open a new one.
