### ISSUE TITLE
URL bar - placeholder - "Search or enter address" even if the feature "autocomplete" and "keyword.enabled" are disabled

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1651]
Ad https://forum.palemoon.org/viewtopic.php?f=3&t=18634

Preferences:
`browser.urlbar.suggest.history`
`browser.urlbar.suggest.bookmark`
`browser.urlbar.suggest.openpage`
__Edited:__
`keyword.enabled`

> On new tabs I get the following text in the address bar: "Search or enter address". This is incorrect if above prefs are set to "false" since "Search" (autocomplete and keyword) is not allowed.

If you agree - also `UXP-task`?

**Comment by wolfbeast** [comment]
This is front-end work, it won't be a UXP-task (and I don't see a point in doing this for Basilisk)

**Comment by JustOff** [comment]
Strings changes were pushed to CrowdIn.

**Comment by wolfbeast** [comment]
Apparently incomplete?
