### ISSUE TITLE
Provide an AppImage

### ISSUE THREAD

**Issue by Tvax** [MoonchildProductions/Pale-Moon#1654]
Providing an [AppImage](http://appimage.org/) for distributing application has, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

In other terms, you wouldn't need to make a version for each Linux distributions, and it would be easier to launch. I think that, this is the kind of time-saving tool that you guys need!

**Comment by JustOff** [comment]
Just wondering if you personally use Pale Moon or just an AppImage evangelist?

PS: I guess this will be [resolved as Wontfix](https://github.com/MoonchildProductions/moebius/issues/174).

**Comment by wolfbeast** [comment]
Smells like evangelism with a copy-pasta opening statement on a new issue.

> All in all there are way too many unanswered questions here that need to be addressed before considering this kind of approach, no matter how "cool" Linus thinks it is (and I agree it is a cool idea, but not something you can just wallpaper on any application).

**Comment by Tvax** [comment]
I personally use Pale Moon, and I'm not an AppImage evangelist haha, but I couldn't describe better what an AppImage is than copying its README explanations.
And I don't really see any drawbacks using it, so why not using it?
