### ISSUE TITLE
Does not define a certificate

### ISSUE THREAD

**Issue by Alzimzim** [MoonchildProductions/Pale-Moon#1655]
![_20180323_212746](https://user-images.githubusercontent.com/33716713/37847400-c9a1df56-2ee1-11e8-9584-193128b8243e.png)

Firefox and Chromium define.

**Comment by mattatobin** [comment]
I dunno what your issue is.. Can you try explaining it?

**Comment by wolfbeast** [comment]
Firefox and Chromium are wrong if they don't consider it broken because of mixed-mode.

The site explicitly links to an http-served asset:
```HTML
<link rel="shortcut icon" href="http://forum.rosalab.ru/favicon.ico" />
```
As such this is a mixed-mode site and the connection can not be considered fully secure.

**Comment by Alzimzim** [comment]
Thanks
