### ISSUE TITLE
Spellchecking per site

### ISSUE THREAD

**Issue by sergeevabc** [MoonchildProductions/Pale-Moon#1656]
At present we are able to allow pop-ups per site via GUI and override useragent per site via about:config. God bless those who contributed to such a flexibility. But what about spellchecking? Usually it is a good practice to keep it enabled, so fewer mistakes leak out when user types a feature request like this or an opinion on some forum. However, on sites such as Workflowy (outliner), Asana (task manager), etc, where you type something for your eyes only with non-dictionary abbreviations and non-alarming mistakes, you would prefer not to be disturbed by red emphasis here and there.

Could you consider implementing a way to manage spellchecking per site?

**Comment by wolfbeast** [comment]
Spellchecking is already stored per site.
You can also disable it from the context menu of text areas if it's annoying.
What else do you think is missing?

**Comment by sergeevabc** [comment]
@wolfbeast, thank you for a quick reply. Apparently spellchecking settings are not stored in about:config (prefs.js), so what is the proper way to backup here?

**Comment by wolfbeast** [comment]
Per site preferences are stored in an sqlite database (for obvious performance reasons).
the db is (obviously) `content-prefs.sqlite`

**Comment by sergeevabc** [comment]
Thank you, sir.
