### ISSUE TITLE
Images cannot be displayed

### ISSUE THREAD

**Issue by MichaelAtOz** [MoonchildProductions/Pale-Moon#1658]
I have a problem which I raised on the [forum](https://forum.palemoon.org/viewtopic.php?f=3&t=18588&p=137985#p137985), _some_ images not showing on Kickstarter, but Firefox works OK.
They may be two separate problems;
1. some images don't display, with error, eg, `The image &ldquo;https://ksr-ugc.imgix.net/assets/019/973/228/c270dbc4f5825f500761413b26cac599_original.gif?w=680&amp;fit=max&amp;v=1516896783&amp;auto=format&amp;gif-q=50&amp;q=92&amp;s=e84b22caa3dfb298852da9a9d5c7db49&rdquo; cannot be displayed because it contains errors."`
2. on the Kickstarter site images disappear after briefly showing

I looked deeper at 2.

It seems that the elements are wrongly handled.

It is meant to (and Firefox does) show the `<div class="loader-dots..." style="visibility: visible;..." ` while images load, and then when the image is unveil()'d (as `<img class="fit js-lazy-image"`), the `<div class="loader-dots..." ` is made hidden, and the `:before` CSS of the `<img` is removed.
 
On Pale Moon the `:before` is still there, the `<div class="loader-dots..." ` is not made hidden (you see them further down the visible page) and the image cannot be displayed (actually it is displayed briefly then disappears - you need a congested machine to observe that).

This is the section of code involved
```
    arWD: function (e, t, n) {
      'use strict';
      var i,
      a = n('l/Rs'),
      r = (i = a) && i.__esModule ? i : {
      default:
        i
      };
      n('yQDW'),
      n('LNuh'),
      (0, r.default) (function () {
        (0, r.default) ('.js-lazy-image').livequery( function () {
          (0, r.default) (this).unveil(500, function () {
            var e = (0, r.default) 
			        ('<div class="loader-dots loader-dots--mega loader-dots--inline loader-dots--overlay" />').css('visibility', 'hidden');
			(0, r.default) (this).after(e); 
			var t = {
              x: (0, r.default) (this).offset().left + this.clientWidth / 2 - e.width() / 2, 
			  y: (0, r.default) (this).offset().top + this.clientHeight / 2 - e.height() / 2
            }; 
			e.css('top', parseInt(t.y) + 'px').css('left', parseInt(t.x) + 'px').css('visibility', 'visible'), (0, r.default) (this).load(function () {
              return e.remove()
            })
          })
        })
      })
    }
```

I am not sophisticated enough (READ AS: I cannot cope with millions of nested anon functions passed by reference...) to test this supposition, but:
It appears to me that the cause is likely that the `this.after(e);` is not correctly positioning it 'after' and when the unveil() happens, the anon function with `e.remove()` executes, it is removing the image (from `<img class="fit js-lazy-image"`), instead of the `:before`. 

Thus the image "cannot be displayed because it contains errors".

This message also pops-up when you hover over the relevant `<img` in Inspector, as the URL actually loads (via Network), it is my supposition that the above is why it is not there to be displayed.
(possibly explaining some of 1.)

I also noticed while debugging, that sometimes the order of elements gets reversed:
This is shown in the Inspector:
`<div class="loader-dots loader-dots--mega loader-dots--inline loader-dots--overlay" style="visibility: visible; top: 2059px; left: 492px;"</div>`
But when you Edit As HTML or Copy Outer HTML it is shown as:
`<div style="visibility: visible; top: 2059px; left: 492px;" class="loader-dots loader-dots--mega loader-dots--inline loader-dots--overlay"></div>`

Possibly explained by a rouge .after() ?? (or is it trying to be helpful and re-ordrering the elements)

Or it could be something else entirely...as that doesn't explain why `.css('visibility', 'hidden')` doesn't work...

**Comment by MichaelAtOz** [comment]
p.s. Version: 27.8.1 (64-bit) on W7

**Comment by THEtomaso** [comment]
In relation to problems with displaying images, it would seem that both Pale Moon and SeaMonkey fails to display images when they're coded with a leading slash.
This was just pointed out by gorhill (uBO author) here (4th post):
https://github.com/gorhill/uBlock/issues/3665/
He just added this commit, to prevent the issue:
https://github.com/gorhill/uBlock/commit/2b92f114bb02787901181ced1cc664af1a9940bc/

**Comment by wolfbeast** [comment]
I doubt that a leading slash in a chrome URL has anything to do with this issue.

**Comment by THEtomaso** [comment]
Sorry, but it just felt a bit excessive to submit a separate report, since the above issue title already covers this problem perfectly.
I don't know much about programming, but it seems to me like it should be a simple fix..
One that will make Pale Moon more robust when it comes to displaying images, right?

**Comment by wolfbeast** [comment]
> Sorry, but it just felt a bit excessive to submit a separate report, since the above issue title already covers this problem perfectly.

No, it does not.

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.

**Comment by MichaelAtOz** [comment]
Umm "UXP-based Pale Moon" is like Swahili to me?

Do I down load an update or something else?

BTW while I'm here, do you want somewhat trivial reports, which I'm pretty sure are Pale Moon in contrast to Firefox, bugs, or do you have enough on your hands?

**Comment by THEtomaso** [comment]
A huge amount of bug reports have been closed today, assuming that they'll all be "Solved by UXP".
Wouldn't it be more proper to leave them all open, until a UXP-based Pale Moon actually exists?

**Comment by mattatobin** [comment]
It does exist. Tycho is being put into maintainance mode so we can focus on UXP.

**Comment by MichaelAtOz** [comment]
So @mattatobin, interpreting the above post, the answer to my question:
>BTW while I'm here, do you want somewhat trivial reports, which I'm pretty sure are Pale Moon in contrast to Firefox, bugs, or do you have enough on your hands?

As I can't possibly know whether a Pale Moon bug is Tycho related, and if it is, it WONTFIX; unless it is critical, best to not report it? Until UXP Pale Moon appears at least. (ie keep a list & check against UXP when(?) it's out)
