### ISSUE TITLE
XCTO: nosniff allowed script MIME types are not aligned with the spec

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1660]
Our initial `X-Content-Type-Options: nosniff ` implementation (#1343) used incorrect list of MIME types allowed for scripts.

This was fixed in [bug #1431095](https://bugzilla.mozilla.org/show_bug.cgi?id=1431095) and should be backported.

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
This fix I suggest for UXP also (e.g. https://github.com/janekptacijarabaci/UXP/commit/3968897fb4b227b1a634700cbeaea715e58ac543).
Or `UXP-task`.

**Comment by JustOff** [comment]
Yes, thanks, UXP needs this update as well, while [bug #1288768](https://bugzilla.mozilla.org/show_bug.cgi?id=1288768) is not a stopper and can be processed later if/when needed.

**Comment by janekptacijarabaci** [comment]
[Bug 1288768](https://bugzilla.mozilla.org/show_bug.cgi?id=1288768) is implemented (into the above tree). http://w3c-test.org/fetch/nosniff/worker.html is OK.
