### ISSUE TITLE
Add support for libavcodec 58/FFmpeg 4

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/Pale-Moon#1668]
FFmpeg published release 4.0 last week. As part of this release the libavcodec version was bumped to 58. Currently we only support up to version 57 of libavcodec. We need to add support for version 58 so that H.264/MP4 playback will work on newer distros releases (such as the upcoming Fedora 28) as well as continue working on Arch and other rolling-release distros once they update to FFmpeg 4.

This should be pretty straight forward and low-risk.

**Comment by trav90** [comment]
Running into a linking error when compiling. Going to take some additional research into what exactly is causing the linking error.

**Comment by wolfbeast** [comment]
Possibly missing symbols? if so you'll have to add them to the symbol definition files.

**Comment by trav90** [comment]
Yes it likely is I just haven't yet had a chance to look into it,

**Comment by jbeich** [comment]
Can you show patch/error message? Firefox fix is trivial to rebase:
https://github.com/freebsd/freebsd-ports/blob/6b93aba0a96e/www/palemoon/files/patch-bug1435212
http://beefy9.nyi.freebsd.org/data/111amd64-default/468602/logs/palemoon-27.9.0_1.log

**Comment by trav90** [comment]
Problem found - a dumb typo on my part. Testing is commencing now.
