### ISSUE TITLE
Complete documentation for Security preferences

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/Pale-Moon#1674]
The [documentation for Security preferences](http://www.palemoon.org/support/prefs-security) is, as of today, missing these two entries:

* dropdown "Add-on security level" (introduced in 27.5.0)
* checkbox "Automatically fill in log-in details" (introduced in 27.7.0)

Just posting this because the documentation is so close to 100% completion :)

**Comment by wolfbeast** [comment]
Fixed

**Comment by vlakoff** [comment]
Really great, thank you!

I have just noticed a typo: "long-in".
