### ISSUE TITLE
Weird behaviour of "https://www.vsynctester.com/gputest.html"

### ISSUE THREAD

**Issue by lewjasio** [MoonchildProductions/Pale-Moon#1675]
# Summary
When performing [this](https://www.vsynctester.com/gputest.html) "Web browser 'GPU memory usage' test" Pale Moon becomes unstable and crashes usually within two minutes of first glitches appearing. By glitches I mean this:
![ui1](https://user-images.githubusercontent.com/34216515/40282218-85e18d32-5c5b-11e8-9fd9-1978500e6f46.png)
# Steps to reproduce
1. Navigate to "[https://www.vsynctester.com/gputest.html](https://www.vsynctester.com/gputest.html)"
2. Click on "Run GPU Memory Test"
3. Wait
4. At some point (usually within the last twenty passes) the animation will freeze
5. Wait
6. The test will unfreeze, but browser window will look like the one above

To temporarily "fix" the UI you must force Pale Moon to redraw affected window. The 'corruption' may randomly reappear after doing that. Even if it does not, other glitches, like buttons disappearing or becoming black when you click them, can appear.
# Crashes
If you try to close Pale Moon in the glitched-out state it will usually crash in "2nd or 3rd" way (more on that later). If you try to use the browser instead, it will crash in the "1st" way.
## Types of crashes
This is xml exported from eventvwr.msc:
[event.xml.gz](https://github.com/MoonchildProductions/Pale-Moon/files/2020597/event.xml.gz)
The first event described in this file corresponds to the "1st" way of crashing. Similarly, the second and third events correspond to "2nd and 3rd" way of crashing.
##  Memory dump
I made mini and full memory dump of the "1st" type of crash, but since GitHub only allows files up to 10MB to be uploaded, here is the minidump:
[palemoon-mini.dmp.gz](https://github.com/MoonchildProductions/Pale-Moon/files/2020608/palemoon-mini.dmp.gz)
## about:memory reports
Before browser crashed (same session), I managed to save the memory usage report and GC & CC logs:
[memory-report.json.gz](https://github.com/MoonchildProductions/Pale-Moon/files/2020624/memory-report.json.gz)
[gc-edges.3264.1526828635.log.gz](https://github.com/MoonchildProductions/Pale-Moon/files/2020625/gc-edges.3264.1526828635.log.gz)
[cc-edges.3264.1526828635.log.gz](https://github.com/MoonchildProductions/Pale-Moon/files/2020626/cc-edges.3264.1526828635.log.gz)
## Error Console
In one session, I opened error console before running the test to check if there is anything there. There were no errors reported. Interestingly, the error console windows did not glitch-out, until I tried to move it (it did not move). After that, I tried to move it again (again, it did not move). This time browser crashed with "illegal instruction" or "access violation" error (sorry, I forgot to take a screenshot). After I dismissed that dialog, another one appeared:
![bp](https://user-images.githubusercontent.com/34216515/40282955-2af3a5ee-5c66-11e8-9b56-a5a83fe08c7a.png)
(Note: The "illegal instruction" or "access violation" dialog looked very similar to his one)
After seeing that, I decided to do another minidump:
[palemoon-mini-bp.dmp.gz](https://github.com/MoonchildProductions/Pale-Moon/files/2020636/palemoon-mini-bp.dmp.gz)
# Additional information
## about:support info
[about-support.json.gz](https://github.com/MoonchildProductions/Pale-Moon/files/2020638/about-support.json.gz)
## Machine
CPU: Intel i3-3110M
GPU: Intel HD 4000
RAM: 8 GB
OS: Microsoft Windows 7 SP 1 Professional (amd64)
## UXP
I could not replicate this behaviour in Basilisk, so UXP seems to be unaffected.

## off-topic
Several weeks ago I tried to register on the Pale Moon forum, but I have never received the activation email. Since making multiple accounts is forbidden the only thing I can do is wait until next database cleanup that should free the username that I was going to use and try to register again, right?

**Comment by wolfbeast** [comment]
As for the off-topic -- send an e-mail to forum@palemoon.org with details.

**Comment by lewjasio** [comment]
> Running a GPU memory stress test on integrated Intel graphics with a shared memory model is (unsurprisingly) not a very good idea.

That's probably right... ;)
> As for the off-topic -- send an e-mail to forum@palemoon.org with details.

Thanks, will do.
