### ISSUE TITLE
Unstable: can't open (XPCOM error), can't uninstall

### ISSUE THREAD

**Issue by Gittyperson** [MoonchildProductions/Pale-Moon#1678]
Just tried installing the current unstable. It installs but doesn't open, I get "can't load XPCOM". When trying to uninstall, the error is "can't find helper.exe". Indeed that file is not in C:\Program Files\Pale Moon\uninstall\. No security software interference, W10 x64 Pro. Upgraded from 27.9.2.

**Comment by Gittyperson** [comment]
Also noticed that for the first time Pale Moon adds inbound Windows Firewall rules. Are those necessary?

**Comment by spectatorBH** [comment]
I confirm the XPCOM issue on Win7 x64. 

The worst part is that my PM27.9.a1 have **silently** upgraded my profile in the process -- got the Alpha2 update thru About box, so there wasn't any warnings available about the forced one-way conversion. So now I'm stuck with a busted unusable profile which can't be downgraded and a "new" browser that can't even start :(

**Comment by grumpygeek** [comment]
Same error here.  Clean install to D: drive. W10home.  Did not try uninstall.  Replaced xul.dll with one from Basilisk, still same error.  I saw they were different.  Extracted omni.ja so if there is a particular file in there to replace I'll try that.

**Comment by Gittyperson** [comment]
About the uninstall failure, I just reinstalled 27.9.2 and all is fine using my backed up profile. I deleted the the contents of C:\Program Files\Pale Moon before re-installing 27.9.2 just in case, perhaps it's not even necessary.

**Comment by JustOff** [comment]
I confirm, it seems something is wrong with 64bit version, you can try 32bit until this is resolved.

**Comment by wolfbeast** [comment]
updated version published after testing

**Comment by Gittyperson** [comment]
(Uninstall issue remains)

**Comment by JustOff** [comment]
Just download the full installation package and install it over.

**Comment by Gittyperson** [comment]
Yes, the issue remained even after the 2nd full download and installation (where the XPCOM issue was solved). Perhaps it's ok now, thanks.
