### ISSUE TITLE
Compatibility issues with leboncoin.fr

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/Pale-Moon#1680]
[leboncoin.fr](https://www.leboncoin.fr/) is a *very* popular website in France ([top 10](https://www.alexa.com/siteinfo/leboncoin.fr)), though it isn't usable in Pale Moon.

I'm pretty sure the bugs are on the leboncoin.fr side, but I haven't figured out what is the cause, and I'm pretty confident if I only report to them that "it doesn't work", on a browser they probably don't even know, they won't consider the issue.

Hence this ticket, hoping someone could provide some help at finding out what are the causes. Then I could report them to leboncoin.fr

First, I have created a test account, if it may help:
> nickname : `UQYqo2z5A50x`
> email : `k1uplbugk@tmails.net`
> password : `T8yYudQE2XkWpfRWE7KW`

So, here are the steps:
1. Click on "Se connecter" ("log in") at top right.
2. Input **email** and **password**, click on the blue button.
3. You are redirected to https://www.leboncoin.fr/compte/part/mes-annonces/ (FWIW, it's the listing of user's active sales) — That's precisely this page that is faulty. As of today, it's showing again the login form. Don't waste your time filling it again, it will just appear again and again.
4. Rather, go to the root url: https://www.leboncoin.fr/ — You should actually be logged in. If so, the account nickname is displayed at top right.
5. If you click on this nickname, there's a menu… If you then click on "Mes annonces", you encounter again the issue of point 3.

This broken page is actually the main page of the website... Without it, the site is unusable.

Also, I do have disabled my adblocker. And I tried with Firefox and Chrome, it's working with them.

**Comment by wolfbeast** [comment]
Thanks for the clear report. It is very likely that our new platform will not suffer from this issue.
To test this, you can either try the [Basilisk web browser](http://www.basilisk-browser.org/) which is our reference application for the platform, or the [unstable channel of Pale Moon](http://www.palemoon.org/unstable/). For testing purposes the portable version of the unstable is usually your best choice so your existing profile remains untouched.

**Comment by vlakoff** [comment]
I have tested on Pale Moon 28.0.0a2, it works :)

Do you have a clue of what is the issue? Waiting for the release of this new platform, it would be great if leboncoin.fr could be fixed for the current Pale Moon :)

**Comment by wolfbeast** [comment]
Sorry, but unless it's a critical issue or a trivial fix, it won't make it into v27.*
