### ISSUE TITLE
Can you rework the debugger UI?

### ISSUE THREAD

**Issue by determin1st** [MoonchildProductions/Pale-Moon#1684]
It's not better than firefox's debugger. Hard to debug.

**Comment by SpockMan02** [comment]
No more work that isn't critical or for security will be done on this repository. (The README says this.)

Try out [the Unstable version of Pale Moon](https://www.palemoon.org/unstable/) (builds [on the forum](https://forum.palemoon.org/viewtopic.php?f=37&t=14482) if you're using Linux), and if you have a problem or problems, report them at https://github.com/MoonchildProductions/UXP.
