### ISSUE TITLE
self-destructing cookies add-on does not work

### ISSUE THREAD

**Issue by lashkevi** [MoonchildProductions/Pale-Moon#1686]
The Self-destructing cookies add-on does not work with PM 28 (unstable), though it installs successfully. The icon does not appear and cookies are not destructed.

System: OpenSUSE 42.3
PM version: the latest 28 for linux x64 (and all earlier versions, I used).

**Comment by JustOff** [comment]
Such issues should be discussed at the [forum](https://forum.palemoon.org/search.php?keywords=self-destructing+cookies).
