### ISSUE TITLE
palemoon recognized as (very) old browser

### ISSUE THREAD

**Issue by computersalat** [MoonchildProductions/Pale-Moon#1688]
Hi,

using palemoon in version 27.9.4 and can't access `OTRS` cause they are the meaning of the browser I am using is (very) old.
```
Sie verwenden leider einen (stark) veralteten Browser. OTRS funktioniert mit einer großen Auswahl an Browsern, aus denen Sie wählen können. Bitte installieren Sie einen neueren Browser oder upgraden Sie Ihren vorhandenen. Bitte lesen Sie auch die Dokumentation oder fragen Sie Ihren Systemadministrator.
```
so what `Version` is `palemoon` handing over that `OTRS` is perhaps misunderstanding ?

Also opened BUG on OTRS side:
[palemoon recognized as (very) old browser](https://bugs.otrs.org/show_bug.cgi?id=13974)

**Comment by wolfbeast** [comment]
You can try to use the "native" user agent compatibility mode for their site (Preferences -> Advanced) or enter an override, to work around it. (see the forum for help with that)
