### ISSUE TITLE
Please update your browser/config/version.txt file because it points to an incorrect version

### ISSUE THREAD

**Issue by sebma** [MoonchildProductions/Pale-Moon#1691]
Hi,

I have successfully build Palemoon from your git on Macos 10.13 and the version windows shows the version "27.9.1a1" instead of "27.9.4" : 

![screen shot 2018-07-27 at 18 57 09](https://user-images.githubusercontent.com/4569306/43335048-ea836226-91ce-11e8-9cee-9b295e47c895.png)

Can you please update your [browser/config/version.txt](../blob/master/browser/config/version.txt#L1) file because it points to an incorrect version ?

**Comment by sebma** [comment]
@JustOff So, in order to build Palemoon, do I have to clone from https://github.com/MoonchildProductions/UXP ?

Which subdirectory contains the Palemoon source ?

How do I build it ?

**Comment by wolfbeast** [comment]
If you need help building, please go to the forum (it has a Mac OS X board)
https://forum.palemoon.org/

**Comment by sebma** [comment]
To help others who meet the same questions I had, here are the command to build Palemoon from the new repo. : 

```bash
git clone https://github.com/MoonchildProductions/UXP
cd UXP
echo ac_add_options --enable-application=palemoon > mozconfig
./mach build
```

**Comment by wolfbeast** [comment]
No, no, no, no. That will build a full-fledged UXP with every default enabled component, which is NOT the way Pale Moon should be configured.
Follow the build instructions as posted elsewhere.

**Comment by sebma** [comment]
@wolfbeast That's the build instructions I've been given [there in the forum](https://forum.palemoon.org/viewtopic.php?f=41&t=19756#p146708) to build palemoon from the UXP repo. 

I use the UXP repo. because JustOff suggested it [here](https://github.com/MoonchildProductions/Pale-Moon/issues/1691#issuecomment-408485515).

Are there other build instructions except those from https://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/macOS which seem to use the wrong (master) branch of the previous repo. ?

Please, help me find the correct instructions to build palemoon from the UXP repo.

**Comment by sebma** [comment]
@wolfbeast Thanks
