### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by DrDonkey** [MoonchildProductions/Pale-Moon#1694]
Hi.
I downloaded palemoon from aur. Installed it. Tried to run it from terminal and get the following:
`[1]    4508 segmentation fault (core dumped)  palemoon`

How to fix it? Tried searching a bit but no luck.

**Comment by trav90** [comment]
Don't use Pale Moon from the AUR (they are unstable and have known issues). Please download it from the main Pale Moon website.

If you still have problems using the official build please open a new issue on the UXP repo.

**Comment by DrDonkey** [comment]
got it. Thank you.

**Comment by DrDonkey** [comment]
Downloaded tarball, but still I am getting same segmentation fault message.

**Comment by wolfbeast** [comment]
> Downloaded tarball, but still I am getting same segmentation fault message.

> If you still have problems using the official build please open a new issue on the UXP repo.
