### ISSUE TITLE
[Suggestion] Make "browser.download.lastDir.savePerSite" false by default

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/Pale-Moon#1696]
Today, I understood why Firefox was, on an irregular basis, not saving my downloads in the last used dir.

That's because I was downloading files from some CDN, i.e. several subdomains, attributed depending on their current network load. So because of the preference [browser.download.lastDir.savePerSite](https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preference_reference/browser.download.lastDir.savePerSite), Firefox was often picking back the dir from an old CDN server, instead of my last used dir.

So, today I discovered this setting, missing from the default configuration and set to true by default. For the reason exposed above, and generally speaking, I think it brings many confusion. See [bugzilla 702748](https://bugzilla.mozilla.org/show_bug.cgi?id=702748). Thus I think it should be false by default.

You may disagree, or want to limit the discrepancies with Firefox, in this case I would have an alternative suggestion: at least add this setting to the default configuration (currently to tweak it, it has to be created), to increase visibility/ease access of this setting.

**Comment by kn-yami** [comment]
Wrong repo, the correct one is here: [MoonchildProductions/UXP](https://github.com/MoonchildProductions/UXP).

**Comment by vlakoff** [comment]
Oops, right. Sorry...
New issue opened in the right repository.
