### ISSUE TITLE
Check (and fix) Pale Moon buildablity on Mac and Linux

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Pale-Moon#1697]
@trav90 and @adeshkp Could you please check this.

Clone this repository and then issue `git submodule init && git submodule update` and then see if everything builds properly.

If you have to make a pull request for fixes then follow UXP commit message style but use this issue number.

**Comment by mattatobin** [comment]
Blocks https://github.com/MoonchildProductions/UXP/issues/969

**Comment by trav90** [comment]
Will provide a report by tomorrow.

**Comment by trav90** [comment]
With the exception of a few scripts missing the executable bit (which a forthcoming PR will fix), all good on Linux x64.

**Comment by mattatobin** [comment]
Thank you Travis. Now that I know which files need to have their permissions change, I will do the same with the Basilisk repo so you won't have to.

**Comment by mattatobin** [comment]
@athenian200 reports everything is good on Solaris and with that I am closing this.

Thanks again @trav90 @adeshkp
