### ISSUE TITLE
Revise Google and Youtube UA overrides.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1703]
We'll have to test what works best with our current code state. Looks like Google (and likely YT) are in need of strict Firefox UAs now.

So far successful tests with:

**Google Apps:**
```
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
```
- [x] Maps: editing+route dragging works.
- [x] GMail
- [x] Other sites? Docs, calc, calendar...?

**YouTube:**
```
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
```
Polymer seems to be happy with this. It doesn't like 68/71 and will simply not load when fed that.

**Comment by wolfbeast** [comment]
Tested the overrides with other google products without issues. Considering this solved.

**Comment by mattatobin** [comment]
Of note `polymer-43` is Polymer v1 and `polymer-63` is Polymer v2.
