### ISSUE TITLE
audio playback in certain video streaming websites produces a robotic voice

### ISSUE THREAD

**Issue by UddipakBhuyan** [MoonchildProductions/Pale-Moon#1704]
Websites such as twitter, tubitv.com produces a robotic voice on video playback on my linux system. There is no issue with the firefox browser in this websites. 

Operating system: Arch Linux
Browser version: 28.8.0
32-bit or 64-bit?: 64-bit
Problem URL: many websites (like tubitv.com, twitter)
Theme: Pale Moon Classic
Installed extensions: butWhyMod; Pentadactyl
Installed plugins: (about:plugins): NONE

**Comment by wolfbeast** [comment]
Please go to the forum for first-line troubleshooting of this issue. Putting this on hold until it's clear whether this is a browser bug or not.

**Comment by UddipakBhuyan** [comment]
Troubleshooting information:

Name | Pale Moon
-- | --
28.8.0 (64-bit)
20191211020100
Show Update History
release
Mozilla/5.0 (X11; Linux x86_64; rv:68.9) Goanna/4.4 PaleMoon/28.8.0
Linux 5.4.8-arch1-1
/usr/lib/palemoon/palemoon
Open Directory
about:plugins
about:buildconfig
about:memory
about:performance
about:serviceworkers
false
about:profiles

**Comment by UddipakBhuyan** [comment]
This is solvable by user agent to 'firefox compatibility'. Credits to Walter Dnes of Pale Moon forum.
Closing this issue.

**Comment by wolfbeast** [comment]
Firefox Compatibility is the default for a reason. Why do people keep changing it then report website bugs as browser bugs?
