### ISSUE TITLE
Round brackets are escaped when copy-and-pasted from the location box

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1706]
Up until Firefox 47, there was a hack in `urlbarBindings.xml` that [explicitly encoded parentheses](https://bugzilla.mozilla.org/show_bug.cgi?id=458565) when copying from the location box. As noted [here](https://bugzilla.mozilla.org/show_bug.cgi?id=824887#c5), this behavior disagrees with [rfc3986](http://tools.ietf.org/html/rfc3986#section-2.2) and also goes against the [URL spec](https://url.spec.whatwg.org/#url-code-points).

[The fix](https://bugzilla.mozilla.org/show_bug.cgi?id=824887) is already included in Basilisk, and I believe it should be ported to Pale Moon as well. I can submit a PR if there are no objections.

**Comment by wolfbeast** [comment]
Go for it.
