### ISSUE TITLE
github.com breaks when using "Firefox Compatibility" User Agent Mode

### ISSUE THREAD

**Issue by quixoticaxis** [MoonchildProductions/Pale-Moon#1708]
Version: 28.8.1 (64-bit)
Steps to reproduce:
1) change User Agent Mode to Firefox Compatibility;
2) sign in to github.com.

Activity feed is infinitely loading, markdown insertion buttons do not work correctly when editing text, milestones popup picker also suffers from infinite loading, and so on.

If User Agent Mode is switched back to Native, everything works like a charm.

**Comment by wolfbeast** [comment]
We are aware. This is already being discussed on the forum.
