### ISSUE TITLE
Clean out sql-based cert and key db files from profile

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1711]
We've had a brief period where the cert and key database files were migrated to an sql format before we reverted this. We need to clean this up if we're going to have a clean migration to sql later on if/when that might happen. This would also help with people who have blatantly copied Firefox profiles across.

**Comment by JustOff** [comment]
I'd rather rename than remove. Let's not plant a time bomb against ourselves.

**Comment by wolfbeast** [comment]
There is no time bomb. As long as we're not using these files, it's safe to remove them. This only happens upon migration to a later UI version or if someone clears the migration pref. If we make sure to remove this block when we'd actually start using the sql-based files, then this can't bite us even if someone removes the pref.
Renaming is a lot more complex. What happens if the renamed versions already exist? etc. I'd rather avoid all that.

**Comment by JustOff** [comment]
I wouldn't want to be that "do you remember what I said" guy, but I always have serious misgivings about irreversible actions. You can call it over-concern, but still.

**Comment by wolfbeast** [comment]
Do you think I didn't give this any thought?
Unless I'm entirely mistaken, this isn't destructive for any intended use. Feel free to correct me if I'm wrong.

Current situation (not doing this): profile may or may not have the wrong files but it's very likely they do since the db was converted on the release channel when first running into the sql storage format becoming default for NSS issue. If we were _not_ to clean up these files, people would lose their updated password stores in favor of these ones if/when we'd move to using sql-based password stores. In that situation the simple act of upgrading would revert the passwords to a MUCH older store and people will lose access to all passwords since that created version. Upgrading would also revert to a state of the password store for Firefox profiles if they were blatantly copied.

Using this method + removing the routine when switching store format:
- Upgrade: new cert/keystore is created from the old format. Old format remains stored just-in-case, but no longer used or updated.
- Downgrade + Upgrade: People will lose access to their newly-added passwords but they are not removed. Downgrades are never recommended but it's been taken into account. If one upgrades again after that, the new passwords are still present and accessible again.
- Downgrade + prefs reset + Upgrade: This is the only situation where one might lose newly-added passwords since the first upgrade. This is very uncommon and only destructive insofar as the passwords are concerned added after the initial upgrade, since the upgrade would be similar to a new upgrade.

Doing nothing would be a lot worse than doing this.
