### ISSUE TITLE
Rewrite the Pale Moon padlock code

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1717]
The padlock code we're using is relying on very old nsIWebProgressListener code that makes assumptions about old IDL specifics and not using additional pieces of info it provides (e.g. weak cipher info). The platform has also done away with always providing a security level along with "is_secure" so the padlock code needs to get a once-over to modernize it based on our current API.

Specifically, anytime STATE_IS_SECURE it also returns STATE_SECURE_HIGH in most cases (STATE_SECURE_MED and STATE_SECURE_LOW were removed at some point along the way).

This makes STATE_SECURE_HIGH basically worthless and the other two still being bitwise values in the IDL seems to have been kept around only to satisfy consumers of nsIWebProgressListener in a rare case of not breaking extensions but most likely so internal consumers didn't have to be rewritten at the time.

What needs to happen in my view is either STATE_SECURE_HIGH and the idl bitwise definitions that aren't valid anymore need to be removed or they all need restored to working order. Otherwise we need to make notes and keep in mind that if STATE_IS_SECURE we should also set STATE_SECURE_HIGH to maintain consistancy.

As for the padlock component in browser base this simply needs aligned to what is actually being used in cpp and a condition should be added to switch logic for the possibility of being STATE_IS_SECURE but not having STATE_SECURE_HIGH. Which very well might be desirable for the case of local injection on a secure site in the uBO data: uri case.

**Comment by RealityRipple** [comment]
I have a... suggestion about this case. I don't really want to make two drafts to explain it, so I just referenced this issue with the commits and am making this comment. If you could, please take a look at the changes I'm suggesting.

I haven't actually compiled to see if this brings back the `identity-box` "Mixed Content" tooltip message and `urlbar` "security_level" value, but it seems like a valid methodology regardless. Note that I've kept the values defined to allow graceful deprecation of UXP applications, but that STATE_SECURE_HIGH will no longer be sent. A new STATE_SECURE_MIXED value is added with the same value as STATE_SECURE_LOW for compatibility with the old Mixed Content methodology. I also added it to the aState value in MapInternalToExternalState (which I think will bring back the Mixed Content functionality I mentioned above).

Also, I'm not sure what `is_insecure` was for, but I got rid of it because it wasn't being used. And I made sure `highlight_urlbar` was false for "about:" "chrome:" and "file:" protocols, just in case.

**Comment by wolfbeast** [comment]
No. nonononono. We do NOT want to change the way the platform works because it will break everything (extensions, etc.). The padlock code (meaning the specific padlock code used in Pale Moon) uses old calls/interfaces and needs to be rewritten. That is front-end code in `palemoon/base/content/padlock.js`
This issue was created on the Pale Moon repo and not on the UXP repo for a reason.

**Comment by wolfbeast** [comment]
In addition, the whole point of the rewrite would be to actually make use of "weak security" again as a visual indicator (_low) based on different states.

**Comment by RealityRipple** [comment]
Okay, Adding STATE_SECURE_HIGH back in is easy enough. But what about the return of the Mixed Content state? Should I scrap that, revert it to using LOW since we're keeping HIGH, or bring it back to life?

**Comment by wolfbeast** [comment]
I'm gonna need some time to think about this. `LOW` is not the same as `MIXED`. Mixed content is a separate state, and not necessarily indicating the security level of the parts that _are_ secured. Although mixed content does indicate of course that something isn't quite right, the unsecured content can be from trusted sources. Maybe your original approach was good after all, but I'm not sure if all of that pans out. The idea I had was to use the `nsISSLStatus` interface and `currentBrowser.SecurityUI` instead of the WebProgressListener (or maybe in combination) to get the various states of the page instead.

**Comment by RealityRipple** [comment]
I was using `BROKEN | LOW` for `MIXED` because that's how it was previously written. Backward compatibility and all that.

And, I see. That might be a little bit more intensive of a changeset, but it would undoubtedly allow for other information to be used in the process.

**Comment by wolfbeast** [comment]
I think your original proposed changes are good, after all, but it won't solve _this_ issue; it would make the rewrite later simpler, most likely?

What I'd ultimately want to end up with is a system where we have 4 distinct states:
**EV**, green, always high security. If mixed content or weak ciphers are used with EV it should **always** be considered **broken**.
**DV**, blue, secure ciphers used. High security. If mixed content is used (only _passive_) it should be considered OK. Mixed _active_ content should make it low security.
**Low security**: weak ciphers are used. RC4_SHA, 3DES, protocol SSL3 (potentially also TLS 1.0/TLS 1.1), weak signature algorithms.
**Broken**: Unacceptable ciphers used (EXPORT, RC2, RC4_MD5), unacceptable signature algorithms.

That is something we'd need nsISSLStatus for to get the cipher suites from.

**Comment by RealityRipple** [comment]
I was thinking SSL3 and TLS 1.0 should be `BROKEN`, TLS 1.1 `LOW`, since it's only vulnerable to POODLE downgrades, but yeah. I was thinking along the same lines looking at the `nsISSLStatus.idl` file.

**Comment by wolfbeast** [comment]
I disagree with broken for TLS 1.0 because it's perfectly possible to have TLS 1.0 in a secure manner! Indicating low should already draw attention to it not having a lot of trust. SSL3... I guess by now Broken is fine, yeah. People really really shouldn't be using that anymore.

**Comment by RealityRipple** [comment]
Alright, I dropped the UXP changes entirely. STATE_SECURE_* can be marked deprecated and eventually removed, but for now, we'll just ignore it completely in `padlock.js`. `STATE_LOADED_MIXED_ACTIVE_CONTENT` and `STATE_LOADED_MIXED_DISPLAY_CONTENT` are directly checked for now. And if the state isn't `null` or `"broken"` after checking against `aState`, then nsISSLStatus for gBrowser is loaded up. The `protocolVersion` is checked, then the `cipherSuite`. If any specific `signatureSchemeName` values should be added in, they should probably go between the protocol and the cipher in check order.

I have not opened this in an IDE or attempted a compile, so I'm sure I dropped at least one semicolon somewhere, but it should at least be a better starting point.

**Comment by wolfbeast** [comment]
Following the back-and-forth in the PR draft:

Hmm I'd have to look up what NSS's internal IDs are, then. I may misremember.
Also there is no point in taking suites into account that we don't enable at all in out PSM module even if NSS supports them.

I don't agree with 3DES ever being marked as medium anymore. Not only do we have the SWEET32 (and the same class of attacks) against it, there are also attacks against the fact that it uses 3 individually small keys and the fact that the common usage in browsers is only 112 bits. We haven't enabled 3DES for a few years so certainly not going to mark it "could be OK". No. it's considered a weak cipher.

`TLS_RSA_WITH_AES_128_GCM_SHA256` specifically is marked bad because it makes no sense to use plain RSA key exchange with AES-GCM. It indicates a misconfiguration more than anything else.

Localizing the padlock tooltips is a good idea. I just never got around to it, myself.

More details isn't needed and undesirable. It needs to hit the balance between general usability and tech goop so needs to provide clear concise descriptions of the status in general terms. There is the security info window with the cipher details, and if you want even more details there is cipherfox which targets Pale Moon.

**Comment by RealityRipple** [comment]
Let me know what you find in the ID list - far as I can tell, the best option would be what I originally had. `_EDE3_` only seems to be used by those two old and hopefully unused methods, and `_3DES_` will catch all the others.

Should we throw in `TLS_RSA_WITH_AES_128_GCM_SHA256` as "broken" just in case it somehow comes up, or will a more solid error page take care of that condition?

**Comment by RealityRipple** [comment]
Regarding the padlock state for Mixed pages: it's hidden by other logic in the browser. Do we want to keep the checks for `STATE_LOADED_MIXED_ACTIVE_CONTENT` and `STATE_LOADED_MIXED_DISPLAY_CONTENT` anyway?
Pale Moon also uses the "This website does not supply identity information." message on such pages, which is not technically accurate, but gives me the feeling it's because of the same logic I was working on in UXP when I first tackled this issue - with `Mixed` states essentially just converted to `Broken` states.
Since mixed content is essentially a privacy hole and active mixed content a giant security hole, it makes sense that they be considered "broken" and insecure, but it does prevent non-EV sites with only mixed display content from being in the clear.

**Comment by RealityRipple** [comment]
Let me know if the localization is named poorly, in the wrong place, or doesn't correctly handle missing strings in other locales.

**Comment by RealityRipple** [comment]
Alright, I've tried to document exactly what we're doing this time around, but I think I got things in the right paradigm now:
1. Check `isExtendedValidation`
   - Check for Mixed Content
2. If not "broken", Check `protocolVersion`
3. If not "broken", Check `cipherSuite`
4. If not "broken", Check `isUntrusted`, `isDomainMismatch`, and `isNotValidAtThisTime`
Note that at present, all four booleans in step 4 result in "broken", even if the problem is bypassed by the user. That keeps the warning there so users have a reminder to be careful. If any of those values should be "low" instead, (like the time, maybe?) let me know.
I'm also looking through `nsIWebProgressListener.idl` to see if there are any failure types that aren't included in `nsISSLStatus` right now.

**Comment by wolfbeast** [comment]
Sorry for not being responsive a few days. 
The logic flow described looks good. And no, step 4's checks should all be broken. We don't want to mark untrusted, mismatched or expired certificates as anything but broken.

As for the "does not supply identity information" when the status is mixed, that is correct if you look at what content is presented to the user. You don't want to indicate that the content is supplied by the secure party when it isn't true (because part of the content is not and you cannot say it is). It probably needs a better message in that situation though.

**Comment by RealityRipple** [comment]
Alright. That's probably work for a different PR tho.
I do think a few more glances over the code would be a good idea, but I guess it's time take the PR out of Draft. If you notice any faulty states or weird error types I failed to take into account, please let me know.

**Comment by JustOff** [comment]
@wolfbeast, сould you please give a hint for translation, can [these messages](https://github.com/RealityRipple/Pale-Moon/blob/1f488302c18e9d1ef14c333bb81bbdbab2485634/palemoon/locales/en-US/chrome/browser/browser.properties#L283-L286) be interpreted as follows:

```
Extended Validated [connection]
Secure [connection]
Weak security [connection]
Not secure [connection]
```
And can we use the full phrase as a source for translation if the short form does not give a clear enough result?

**Comment by wolfbeast** [comment]
It is the connection status, so yes, you should interpret it as such.
Please do note that EV/Extended Validated is a fixed term and should likely either not be localized, or at least have a mention of "EV" if it is localized, in brackets.

**Comment by wolfbeast** [comment]
FTR, the current unstables should have these changes in them.

**Comment by JustOff** [comment]
Thanks, strings changes were pushed to CrowdIn.

**Comment by wolfbeast** [comment]
OK, so there's an issue now with mixed passive content, as it no longer triggers the doorhanger/shield while it should, and kills the domain name otherwise in the identity panel.
https://mixed.badssl.com/
![image](https://user-images.githubusercontent.com/3359132/92554509-c8a38600-f265-11ea-9522-e2259045cf47.png)
@RealityRipple can you have a look at this particular situation?

**Comment by RealityRipple** [comment]
The changes I made only have an effect on the padlock, not the rest of the identity panel. That's handled elsewhere. And your instructions were:

> **DV**, blue, secure ciphers used. High security. If mixed content is used (only _passive_) it should be considered OK. Mixed _active_ content should make it low security.

So that's exactly the way it's written.

**Comment by wolfbeast** [comment]
I apologize, you are correct in what I asked. Not showing the domain name might not have been the best choice though; I'll have to think about what to do with mixed content some more. I'd prefer to block it outright but that would cause too much breakage so we need some other way to indicate this. Perhaps a unique icon for it instead of the padlock.

**Comment by wolfbeast** [comment]
Probably better is this for DV:

- Everything secure: High (subject to other checks like protocol etc.)
- Mixed display content: keep displaying domain name but make level "low"
- Mixed active content: broken, don't display domain name

**Comment by RealityRipple** [comment]
Just about any arrangement you want is possible. As is checking pref states, so we could code an alternate behavior if the "block mixed passive content" pref is true, and turn the pref on at a later time, possibly with the mixed content doorhanger to let users fix any breakage caused by that change.

**Comment by RealityRipple** [comment]
The way the code in browser.js is currently written, if `security.mixed_content.block_active_content` is false, `setMode()` gets called with `IDENTITY_MODE_MIXED_CONTENT` instead of `IDENTITY_MODE_MIXED_ACTIVE_CONTENT`, which means that if we display the identity label for mixed display content, it will also show up for mixed active content when mixed active content is allowed by pref. If you don't want that behavior, please let me know; it can be prevented, but it'd require a few extra changes.

**Comment by wolfbeast** [comment]
>  it will also show up for mixed active content when mixed active content is allowed by pref.

If people enable this pref themselves _they_ take responsibility for their browser use if so. There's no reason to go against the user's wishes (even if they are foolhardy), so displaying the domain in that case is fine.

**Comment by wolfbeast** [comment]
Actually, we already have a `level=mixed` state in our themes, so we should leverage that.

**Comment by RealityRipple** [comment]
`security_level=mixed` will provide a different urlbar shadow coloring, but the padlock's `mixed` styling is all `low` styling at present, and the identity panel is only styled for `verifiedIdentity` and `verifiedDomain`, so there'd be no visual difference to the padlock or the identity panel unless we make changes to `padlock.css` and/or `browser.css`.

**Comment by wolfbeast** [comment]
You're missing the point that not everyone might be on the default theme ;) other themes may have unique styling already.

**Comment by RealityRipple** [comment]
We might want to split this up into a few different issues going forward: Padlock, Panel, and Label. It might make deciding on courses of action for each element a little cleaner, and future research a little simpler. Changing the `security_level` on the urlbar as a whole will also change the padlock `level`, so those should probably remain together. And while the identity label is planned to be physically changed, the panel's CSS is the only thing that would potentially be changed for this, not any of the underlying JS.

Oh, also, it should be noted that at present, active mixed content pages are detected as secure when the mixed content is blocked. It only shows up as low security and removes the identity label if the user allows the mixed content. If you want any changes to that behavior, that's gonna be real messy.

**Comment by RealityRipple** [comment]
Oh, and if we are bringing mixed back, do we want to give it a unique (localized) tooltip or just use low's "Weak security" or broken's "Not secure"?

**Comment by wolfbeast** [comment]
Woah dude, slow down

Pages are secure if the mixed content is blocked. Think about it. We do NOT want to change that.
also, I'm saying that "level" should be changed, not "security_level"

But you know what, just leave it, I'll have a look at it myself because I'm thinking at this point you're trying to change way too much.

**Comment by RealityRipple** [comment]
And regarding adding the identity label to passive mixed content for domain-validated pages, do we want to color the panel or leave it transparent? I'm not any good with aesthetics, so while I can say exactly _where_ to add the right CSS changes, I would be completely the wrong person to make any decisions on _what_ those changes would be. Coloring and shading and all that. But leaving it transparent definitely looks... ![mixed_nopanelbg](https://user-images.githubusercontent.com/25967473/92573698-02ab6280-f23b-11ea-86dc-08d411a644d4.png) weird.

**Comment by RealityRipple** [comment]
> also, I'm saying that "level" should be changed, not "security_level"

`level` and `security_level` are set in the same place with the same passed variable. We'd need to add a second variable if you want them separated.

**Comment by wolfbeast** [comment]
Right, so i've taken all the info and come up with restyling for it all.

What I have now:
Mixed active content, blocked:
![mixed-act-blocked](https://user-images.githubusercontent.com/3359132/92731627-9f721b00-f375-11ea-9e54-daa89b489690.png)
Mixed active content, when protection is disabled from the doorhanger:
![mixed-act-protdis](https://user-images.githubusercontent.com/3359132/92731686-b153be00-f375-11ea-900c-6f3606320fbd.png)
Mixed active content, when protection is disabled from the pref:
![mixed-act-protdis-pref](https://user-images.githubusercontent.com/3359132/92731966-114a6480-f376-11ea-8a65-68fa96f4b228.png)
Mixed passive content:
![mixed-passive](https://user-images.githubusercontent.com/3359132/92732294-8a49bc00-f376-11ea-812b-c8e029467e5d.png)
and classic style: 
![mixed-passive-classic](https://user-images.githubusercontent.com/3359132/92732320-93d32400-f376-11ea-80f4-565571df4fd7.png)
Mixed passive _and_ active content on the same page:
![mixed-passive-and-active](https://user-images.githubusercontent.com/3359132/92732439-c11fd200-f376-11ea-8067-50daffda95a6.png)
Weak protocol or cipher:
![weak](https://user-images.githubusercontent.com/3359132/92732379-aa797b00-f376-11ea-9b78-300d559d825b.png)
(this disables the URL bar shading, too, which is good)

Feedback?

**Comment by RealityRipple** [comment]
Looks good and straightforward. If you want to add a tiny bit more of a "this is not a great state to be in" vibe, you could add a "⚠️" to the padlock, but it's already pretty obviously "not perfect" as-is.

Is adding the "mixed passive" padlock gonna be a breaking change for themes, tho? Or will there be a "low" or "broken" state fallback? And I'm guessing it'll get its own "Low security (HTTP Files)"-esque tooltip message, too?

It's also possible to give the "broken" padlock a "Warning - Contains HTTP scripts" tooltip when dealing with mixed content specifically, if you want.

**Comment by JustOff** [comment]
Sorry, but do you really think that most users know the difference between all the listed cases, and even more so that someone is able to remember what each icon and color mean? Perhaps it should be done in less detail, or somehow have a link to a page with a detailed explanation?

**Comment by RealityRipple** [comment]
When you click on the identity panel, the identity popup already has a line that says "your connection to this site is only partially encrypted".

**Comment by wolfbeast** [comment]
> Sorry, but do you really think that most users know the difference between all the listed cases

They don't have to - there are tooltips and details if clicked. Not sure why you are criticizing this since it's not all that different from what we've always had, the only difference being the more clearly indicated "mixed content" instead of just defaulting to "broken" in that case.

**Comment by wolfbeast** [comment]
@Lootyhoof There are some changes here that might affect full themes (primarily the identity panel styling, since the padlock code is theme-independent), although I don't know if "mixed" and/or "low" was already adopted because we did have that before.

**Comment by RealityRipple** [comment]
The [test extension](https://realityripple.com/Software/Mozilla-Extensions/1717/) I made for the last round of changes has been updated to match 2771b99 (minus the theme changes). While it'll seem broken when using the default theme, it should allow testing of other themes with the currently proposed changes.

**Comment by Lootyhoof** [comment]
The theme changes aren't breaking (worst case scenario is that the urlbar isn't styled for particular new security levels) but obviously do need updating.

@FranklinDM FYI for you too.

**Comment by RealityRipple** [comment]
While I was doing some extension work last night, I noticed something about browser.js (which was only minimally modified here) that kind of concerns me. There are quite a few If statements of the style `if (aValue !== undefined) {`. Correct me if I'm wrong, but isn't that a bad way to check for **undefined**? I'm pretty sure strict equality comparisons for **undefined** don't work that way in JS and need to be written as `if (typeof aValue !== 'undefined') {` instead, right?

**Comment by wolfbeast** [comment]
Please don't tack unrelated questions/observations onto issues.
And no, while it would be "more correct" to use typeof, JS's syntax parsing is anything but strict because that's how people like it. `== undefined` is fine.

**Comment by RealityRipple** [comment]
Yeah, sorry about being off-topic. And I know the abstract equality check works with undefined, but I think the strict equality checks are... less functional.

**Comment by wolfbeast** [comment]
No it isn't.
You can't redefine `undefined` to anything else (which would be possible before ES5, like... a decade ago) so it's not possible to misinterpret this in any way, least of all in static internal chrome scripting.

**Comment by RealityRipple** [comment]
Alright. And I guess if any variables are actually not defined, a reference error in the log would be a good thing. Sorry for the false alarm.

**Comment by wolfbeast** [comment]
Since this is live with no notable reports of regressions, I'm closing this.
