### ISSUE TITLE
Some JPEG pictures are displayed incorrectly

### ISSUE THREAD

**Issue by Egor-Skriptunoff** [MoonchildProductions/Pale-Moon#1720]
This is a picture:
https://66.media.tumblr.com/tumblr_m8cvygE8Ga1roedt4o1_640.jpg

This is how it is displayed in Firefox (on the left) and PaleMoon (on the right):

![jpg_problem_ff_vs_pm](https://user-images.githubusercontent.com/19153610/73418966-82309500-432e-11ea-90da-d736572db3a3.png)

My system:
Debian 8.11 with MATE 1.8.1
Pale Moon 28.6.1 (64-bit)

**Comment by Bfgeshka** [comment]
displays just fine on 28.8.2 in win7

**Comment by wolfbeast** [comment]
Your O.S. doesn't have a proper calibrated color profile to use. Either calibrate your color or disable color management in the browser by setting `gfx.color_management.mode` to 0.

This isn't a browser bug although we are adjusting defaults for Linux do disable it there.

**Comment by Egor-Skriptunoff** [comment]
> disable color management in the browser by setting `gfx.color_management.mode` to 0.

Thanks, this fixed the problem.

**Comment by Egor-Skriptunoff** [comment]
It seems that setting `gfx.color_management.enablev4` to `false` is another way to solve this problem.  
The default value of `gfx.color_management.enablev4` in Firefox is `false`, in PaleMoon is `true`.

**Comment by wolfbeast** [comment]
It wouldn't solve the problem. If you run across an image that has an ICCv2 profile in it, the colors would be wrong again. Disabling v4 on a v4-only image effectively disables color management on it, but images can have v2-only, v2 and v4, or v4-only ICC data.
The only proper solution is to either calibrate color or disable the color management system altogether.

If you have further questions or want to discuss, please use the forum.
