### ISSUE TITLE
Exclude pinned tabs from various tab views

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1722]
Should be behind prefs, disabled by default. `browser.{ctrlTab|allTabs}.hidePinnedTabs` or something.
Filter on pinned state and exclude from tab list array. Add null check. Enh.: Switch to pinned tabs display if list empty (only pinned tabs present)

Two distinct places where this should apply:
- [ ] Ctrl-Tab graphical pane
- [ ] All Tabs graphical pane

See also:
- https://github.com/MoonchildProductions/Pale-Moon/issues/27
- https://github.com/MoonchildProductions/Pale-Moon/pull/362

**Comment by mattatobin** [comment]
@FranklinDM Transfer of issue is complete. Good luck!
