### ISSUE TITLE
Latest unstable build rather slow and lags

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1725]
As already mentioned in the forum, so i am not the only one with this issue:

https://forum.palemoon.org/viewtopic.php?f=5&t=23756&p=183306

Browser start slow, session loading rather slow, also when quitting the new unstable it needs quite a long time to close the process. Same result with a fully fresh profile. So, it is no issue with my profile in use.

**Comment by JustOff** [comment]
Yep, and here is the difference in the dromaeo test:

[20200128175737](http://dromaeo.com/?id=280553) - 476.94runs/s (Total)
[20200205184404](http://dromaeo.com/?id=280554) - 118.50runs/s (Total)

**Comment by wolfbeast** [comment]
I'm performing several build configuration tests to optimize for the new milestone. Thanks for your feedback, it's very valuable!
