### ISSUE TITLE
Pale Moon: macOS: Emoji surrounded by black squares in titlebar when window loses focus

### ISSUE THREAD

**Issue by SpockFan02** [MoonchildProductions/Pale-Moon#1728]
When the window loses focus, if the titlebar contains emoji, they get little black square backgrounds. Returning focus to the window doesn't fix it, nor does moving/resizing, but switching tabs (thus rewriting the window title) does. This issue is not new in UXP (Tycho is also affected).

Here is what it looks like: <img width="71" alt="screenshot 2018-06-26 23 01 33" src="https://user-images.githubusercontent.com/11634417/41955453-9904c5dc-79cf-11e8-8027-3a65bf41562b.png">

**Comment by dbsoft** [comment]
This may be fixed, I can't seem to reproduce this... our titlebar changes earlier in the year may have resolved this... or it isn't an issue on current versions of MacOS... I'll do some tests on various versions shortly.

**Comment by wolfbeast** [comment]
OK, I'll mark this tentatively fixed then. Please reopen if it's still a problem.
