### ISSUE TITLE
Ram Usage limiter feature request

### ISSUE THREAD

**Issue by adamkenway007** [MoonchildProductions/Pale-Moon#1732]
i'm usually use pale moon with some issue with pale moon is sometime pale moon take much ram above 350 Mb while open some tab could you make build in memory editor/limiter for pale moon i'm low end user.btw my ram is 1.5 GB

**Comment by wolfbeast** [comment]
Modern browsers and the websites they are tasked to display simply require enough memory to work in. It's not possible to limit Pale Moon's memory without seriously compromising compatibility and performance.
