### ISSUE TITLE
Deal with UserAgentUpdates.jsm (dynamic SSUAO)

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1733]
`UserAgentUpdates.jsm` was introduced by [bug 897221](https://bugzilla.mozilla.org/show_bug.cgi?id=897221) to provide dynamic `SSUAO` for b2g and Android builds and, by default, relies on the data provided by Mozilla. 

At the moment it is included, initialized and installs its listeners on all platforms, but provides updates only for Android, using [https://dynamicua.cdn.mozilla.net/0/%APP_ID%](https://dynamicua.cdn.mozilla.net/0/%7Baa3c5121-dab2-40e2-81ca-7ea25febc110%7D).

We may consider using this service to provide our own `SSUAO` updates for all UXP applications, or build it conditionally for Android only, or remove it completely.

**Comment by wolfbeast** [comment]
Tested with server-side scripting in place and test script echoing back the user agent.
Unstable channel is getting the test UA for this with appended `(dua)`
http://testserver.palemoon.org/useragent.php

**Comment by JustOff** [comment]
> I've thought about this a bit and client-side OS substitution really isn't a good way to handle this. Regexes are the prime way of dealing with unknowns in a UA string.

Sorry, but I still think this is inconsistent with the way we provide SSUAO using `uaoverrides.inc`, where we use explicit `OS_SLICE` rather than regex (which is also allowed there).

> If people use a blanketing UA override then it is their own responsibility to deal with any fallout from that.

Why don't we exclude the very possibility of such problems using the following syntax

`{"testserver.palemoon.org": "Mozilla/5.0 (%OS_SLICE% rv:27.9) Gecko/20100101 Firefox/27.9 (Pale Moon) (dua)"}`

which gives a result equivalent to the test rule that you used

`{"testserver.palemoon.org": "Mozilla\\/5.0 \\((.+?); (.+?);.*#Mozilla/5.0 ($1; $2; rv:27.9) Gecko/20100101 Firefox/27.9 (Pale Moon) (dua)"}`

but will guarantee it is correct, regardless of the global override?

This requires a very small patch, which I am ready to submit if we agree. It will allow to use both override syntaxes discussed above.

<hr>

Also, we need to add the default `ua-update.json`, otherwise the console shows a non-fatal error, which, however, can slow down the application startup. I also have a patch ready to resolve this.

**Comment by wolfbeast** [comment]
You don't seem to get it... `%OS_SLICE%` is a define resolved at **build time** as a generic override for all entries using it (and therefore hard-coded) and isn't available at run-time.

Please submit the patch for the default if you have it ready.

**Comment by JustOff** [comment]
> You don't seem to get it... `%OS_SLICE%` is a define resolved at build time as a generic override for all entries using it (and therefore hard-coded) and isn't available at run-time.

I simply add the following lines to the `UserAgentUpdates.jsm`

```js
#ifdef XP_UNIX
#ifndef XP_MACOSX
const OS_SLICE = "X11; Linux x86_64;";
#else
const OS_SLICE = "Macintosh; Intel Mac OS X 10.11;";
#endif
#else
const OS_SLICE = "Windows NT 6.1; WOW64;";
#endif
```

and everything works as it should.

**Comment by wolfbeast** [comment]
I'm sorry but I disagree with hard-coding this when the more accurate selection is that which is in the browser's native UA. In fact, I'm sure if someone **explicitly** overrides useragents generically, they would want whatever OS they chose to override with to be applied in these cases as well.
If we want to hard-code something it would be supplied as such in the json.

**Comment by JustOff** [comment]
Well, you decide, but in my opinion this is a clear inconsistency. Why not change all the rules in `uaoverrides.inc` in the same way then?

**Comment by wolfbeast** [comment]
> And why should we even cater to those who change the default override?

Excuse me, **you** were the one starting to argue about it not being flexible enough when I said they were on their own. UA overrides in preset preferences can't use regexes because they aren't processed that way.
If you're a stickler for consistency then we shouldn't even be using this system anyway and have people have nothing at all instead, _or_ do everything with this service and not use pre-set overrides but I don't like that idea because then we're moving towards supplying the browser as a service.

**Comment by JustOff** [comment]
> Excuse me, you were the one starting to argue about it not being flexible enough when I said they were on their own.

My idea was to make our overrides always work, regardless of PEBCAK.

> UA overrides in preset preferences can't use regexes because they aren't processed that way.

Sorry, but you are wrong, they **can** use regexes. I can provide en example if you wish.

> If you're a stickler for consistency

I just propose using a single method of constructing overrides (_consistency_) and the option without regular expressions seems to me more _foolproof_.

**Comment by wolfbeast** [comment]
> Sorry, but you are wrong, they can use regexes. I can provide en example if you wish.

Oh? Well that's news to me. In that case we can switch the static UA overrides to them and it will always accurately reflect the OS. Please open a new issue for that then.

**Comment by JustOff** [comment]
> Please open a new issue for that then.

Ok, I'll do this, and I'm here if you need my help to implement, although I still don't like this approach.

> I also don't see how we need to make a json format that is supplied by US on the server to be "foolproof".

By not using regexes, 'cause I think this gives a better chance that the user will get exactly the override that we intended to set.
