### ISSUE TITLE
Status Bar seems to be non-functional

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/Pale-Moon#1742]
Setup:
* In Pale Moon's "status bar preferences" tool, choose "Show status in: Status Bar", also choose "Show links in: Status Bar".
* Of course, have the status bar displayed ;)

Issue:
* Nothing is displayed in the status bar: no page load progress, no link target.

Note that on the other hand, the "Pop-up" display works as expected.

<br> Pale Moon 28.8.4 - Windows 10

**Comment by wolfbeast** [comment]
In `about:config`, set `status4evar.firstRun` to `true` and restart the browser.
This is a known long-standing issue with the status bar code, but the exact cause is unknown.

**Comment by vlakoff** [comment]
Thanks, I did the manipulation and it has solved the error.

<br> If, by any chance, it may be of interest to you, I compared my Pale Moon profilte before/after the manipulation, and there might be interesting results in the `xulstore.json` file:

Before:

    "addon-bar":{"collapsed":"true","currentset":"addonbar-closebutton,spring,status-bar"}

After:

    "addon-bar":{"collapsed":"false","currentset":"addonbar-closebutton,status4evar-status-widget,status4evar-progress-widget,status-bar"}

(it replaced `spring` with `status4evar-status-widget,status4evar-progress-widget`)

**Comment by vlakoff** [comment]
I did some googling, and found out there is even a FAQ entry about this issue:
https://forum.palemoon.org/viewtopic.php?f=24&t=391

Hence closing. Thanks again :)
