### ISSUE TITLE
extremely high cpu usage on a news site with ryzen 2600

### ISSUE THREAD

**Issue by TheAquabat** [MoonchildProductions/Pale-Moon#1743]
this page is making my pc crawl
https://www.lanacion.com.ar/

check there is a big banner (header) image, they change the main news image from time to time to a smaller one but when the big header image from the main news is there it's makes my pc extremely slow I have to kill palemoon.

**Comment by Nuck-TH** [comment]
Issues are not for support. You should use Pale Moon forum for general troubleshoothing and finding exact cause of issue to report here.

**Comment by TheAquabat** [comment]
it happens also in safe mode.
