### ISSUE TITLE
Simultaneous requests for a master password

### ISSUE THREAD

**Issue by ghost** [MoonchildProductions/Pale-Moon#1744]
# Simultaneous requests for a master password
This is a minor UI annoyance that easily comes up when a master password is set and sync is enabled.

Launching the browser to, or quickly opening after launch, a login page for which a password is saved may result in two simultaneous prompts for the master password, as both the login form and Sync will request it at the same time. The second password prompt steals focus from the first while typing the password.

The ideal behavior would be that the second prompt is delayed, that it does not steal focus, or that it is cancelled if the correct password is entered in the first prompt.

This is happening on Linux Mint, Pale Moon 28.8.4 64-bit.

**Comment by wolfbeast** [comment]
The only real workaround for this is having the browser ask for the master password upon startup. Delaying a prompt or cancelling if another prompt has entered the correct password etc. is all technically very complicated and error-prone, so if there's going to be an improvement here it'll have to be a compromise, e.g. similar to what was done in Interlink to prevent multiple MP dialog pop-ups when external auth methods would be in use.
