### ISSUE TITLE
Palemoon 28.9.0.2 fails to display the login screen to tagesanzeiger,ch

### ISSUE THREAD

**Issue by dimmie** [MoonchildProductions/Pale-Moon#1746]
Hi !
After the upgrade to Palemoon 28.9.0.2, trying to access the login screen of https://tagesanzeiger.ch/ fails.
The login screen appears briefly on the display, to be replaced by a grey screen without any information. Looking at the page source doesn't show anythig like a login screen.

**Comment by wolfbeast** [comment]
Works fine here with&without adblocker enabled.
Please go to the [forum](https://forum.palemoon.org) for support and troubleshooting.

**Comment by adeshkp** [comment]
No issues here on Linux also.

But on Mac, I get the the grey page. This is most likely due to the version 2 of pollyfill.io library. If calls to cdn.pollyfill.io are blocked, login page is displayed properly. Both using Native and Fx compatibility UA modes.
Error in web console:
```f[Symbol.iterator] is not a function```

**Comment by dimmie** [comment]
@ wolfbeast
Starting palemoon from a terminal (NO privacy mode), disabling ADblock everywhere, accessing tagesanzeiger.ch, then the login screen : gray page.
Starting palemoon as above, disabling ADblock in the Tools menu, stopping and restarting palemoon, accessing tagesanzeiger.ch, then the login screen : gray page.

General setup: devuan beowulf/ceres ; palemoon

**Comment by wolfbeast** [comment]
Please go to the forum for support and troubleshooting.

**Comment by wolfbeast** [comment]
Closing: polyfill.io v2 issue, not a browser issue.
