### ISSUE TITLE
Add site indicator to downloads

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#175]
The download managers currently list what sites a file was downloaded from after completion, but not on in-progress downloads.

See also: https://forum.palemoon.org/viewtopic.php?f=13&t=9620

This would probably be a simple yet nice enhancement to give people some more information about their running downloads. Could be as simple as adding an extra label after the file name for running downloads with already-known domain information.

**Comment by Antonius32** [comment]
I can take a shot at this, if you want.

**Comment by wolfbeast** [comment]
Go ahead!

**Comment by wolfbeast** [comment]
Is this complete at this point or should I re-open this issue until it is?

**Comment by Antonius32** [comment]
It's complete now, no need to re-open this issue.

**Comment by wolfbeast** [comment]
Awsome then! Thanks :)
