### ISSUE TITLE
Make OS X default theme integrate better

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#1751]
Currently, the default theme on OS X appears with a very distinct titlebar, with the rest of the UI styled differently:

![Current](https://i.imgur.com/OSERtzc.png)
![Current tabs on top](https://i.imgur.com/8nNi7Xm.png)

This is, as it turns out, not the standard practice for applications on OS X, nor is it consistent with how we deal with this on Windows. Similarly, the search icon feels very out of place on this OS. What I would propose is, the below:

![New](https://i.imgur.com/mnrjO8J.png)
![New tabs on top](https://i.imgur.com/TJ2dxSP.png)

This would blend the top toolbar (either the `#nav-bar` or `#TabsToolbar` depending on tab placement) with the titlebar, making it look more flush with the OS. The fix should be a small change in CSS. I would also be aiming to fix the `clip-path` for `#forward-button` too as it actually looks for the Windows version (which isn't present on OS X) rather than the OS X one, meaning no clipping takes place for carving out the circular `#back-button`. As for the search icon, this is taken from the original OS X default theme.

If we're happy with this I can arrange it.

**Comment by SpockFan02** [comment]
A visually distinct titlebar like we have was the norm for native apps I think until OS X Yosemite (10.10), and in Australis and Firefox Quantum it is still available as an option (enabled in the `Customize...` menu), but these days most apps do look more like your mockup, with the caption buttons and tab bars in one tall titlebar. Personally I like the titlebar we have and if it's feasible to replicate the post-Australis toggle then I think we should.

As for the forward button, I didn't realize it wasn't as intended, but with a persona on I can see what you're talking about:
<img width="68" alt="Screenshot 2020-03-30 12 22 28" src="https://user-images.githubusercontent.com/11634417/77953319-f7aed800-7281-11ea-9da0-bf69aedf6956.png">

And I 100% approve of going back to the original search icon.

**Comment by wolfbeast** [comment]
I disagree with keeping the separate bar option in tabs-on-top mode -- that doesn't match what we do on other operating systems in that case either. So I'm fine with getting it look like the proposed new style all the way.

**Comment by Lootyhoof** [comment]
As an FYI anyway: OS X has had styling like that since at _least_ 10.7, which is out target anyway. For example (image not mine):

![10.7](https://i.imgur.com/Gp68Hfv.png)

**Comment by SpockFan02** [comment]
There has been a mix of [both](https://fthmb.tqn.com/M-7MExNSJphscAFumieGSZdOmDE=/2620x1761/filters:fill(auto,1)/MountainLionInstall-570abf063df78c7d9edd5072.jpg) I suppose. Seeing as the toggle exists in Basilisk, I'd like to see if we could adapt it.
<img width="1288" alt="Screenshot 2020-03-30 13 08 59" src="https://user-images.githubusercontent.com/11634417/77957021-b0c3e100-7287-11ea-8a8c-d99c6b334061.png">

**Comment by wolfbeast** [comment]
Pale Moon is not Basilisk, and shouldn't strive to be it either.

**Comment by Lootyhoof** [comment]
It's also unrelated to this issue, surely.

**Comment by SpockFan02** [comment]
My intention wasn't to say Pale Moon should become Basilisk, only to point out how Firefox and Basilisk handled the transition @Lootyhoof is suggesting, and that the code exists in another UXP application. I don't think it's unrelated as the titlebar is an important component of theme integration, but it has become a bit of a tangent. I'm alright with the blended titlebar (and even if I wasn't, I'm not in charge) so if you think it's simple and desirable I say go for it.

One other thing I would like to point out, over here the default theme doesn't look quite like your first screenshots:
<img width="811" alt="Screenshot 2020-03-30 13 16 18" src="https://user-images.githubusercontent.com/11634417/77958021-46ac3b80-7289-11ea-8335-efa538da8b74.png">
For me the toolbars look grey rather than white, and I think the grey is better-matching. I'm on macOS 10.12.

**Comment by Lootyhoof** [comment]
The screenshots were taken on 10.15, so take a pinch of salt as to the coloration. You can try this yourself with Stylem or similar:

````
#navigator-toolbox[tabsontop=false] > #nav-bar:not(:-moz-lwtheme) {
  -moz-appearance: toolbar !important;
}
#TabsToolbar[tabsontop=true]:not(:-moz-lwtheme) {
  -moz-appearance: toolbar !important;
}
````
I'm aware this could do with some work for private mode though. If nothing else though we could just leave things as-is for that (given we want to put a badge on the titlebar when in that mode, which makes things non-native anyway).

**Comment by SpockFan02** [comment]
Looks alright in a normal window, and for private browsing I think I agree. We could tweak it in various ways but just leaving it works fine too. Private window with above CSS in userChrome, for reference:
<img width="215" alt="Screenshot 2020-03-30 13 36 39" src="https://user-images.githubusercontent.com/11634417/77959599-b58a9400-728b-11ea-911d-a00ea69fe563.png">
<img width="146" alt="Screenshot 2020-03-30 13 36 56" src="https://user-images.githubusercontent.com/11634417/77959603-b6bbc100-728b-11ea-954b-88cd880a67d5.png">
(The blue bold bookmark folders are another userChrome tweak, so don't mind that)

**Comment by Lootyhoof** [comment]
OK...How about this?

````
#main-window[tabsontop=false]:not([privatebrowsingmode=temporary]) #nav-bar:not(:-moz-lwtheme) {
  -moz-appearance: toolbar !important;
}
#main-window[tabsontop=true]:not([privatebrowsingmode=temporary]) #TabsToolbar:not(:-moz-lwtheme) {
  -moz-appearance: toolbar !important;
}
#main-window[tabsontop=false][privatebrowsingmode=temporary] #nav-bar:not(:-moz-lwtheme),
#main-window[tabsontop=true][privatebrowsingmode=temporary] #TabsToolbar:not(:-moz-lwtheme) { 
  -moz-appearance: none !important;
  background-color: transparent !important;
}
#main-window[tabsontop=false][privatebrowsingmode=temporary] #nav-bar:not(:-moz-lwtheme) {
  border-bottom: 1px solid rgba(26,26,26,0.2) !important;
}
````
![Tabs not on top](https://i.imgur.com/OaBnhDH.png)
![Tabs on top](https://i.imgur.com/Ioz9bVx.png)

**Comment by SpockFan02** [comment]
Clever, and looks even better. :)

**Comment by Lootyhoof** [comment]
Although, now that I've had more of a play around with themes on OS X, I might have found a way to fix the private mode titlebar issue anyway (not the label though):

![Titlebar in private mode](https://i.imgur.com/1mVW3Kp.png)

Do we want this, and if so, rolled into the same PR?

**Comment by SpockFan02** [comment]
Is the issue that it doesn't have the -moz-window-titlebar appearance? I don't see why not, and I would say that counts as making it integrate better.

**Comment by Lootyhoof** [comment]
Yes, exactly. The other one was just `transparent` and taking its background from `#main-window` itself. This would add the correct appearance, with the privacy badge.

**Comment by SpockFan02** [comment]
BTW the privacy badge is done the old way as a positioned background-image on #main-window, which is why in the past personas couldn't be applied to private windows. Currently we allow it but it ends up squishing the persona background into the shape of the privacy indicator. At some point (I think in Australis) it got replaced in Firefox by a .private-browsing-indicator hbox, which allows for personas to work in private windows, so I think we should switch to that method. (That's off-topic for this bug though.)

**Comment by Lootyhoof** [comment]
After some more experimentation (in particular, testing fullscreen mode) I've realised my approach was wrong and would end up not having a badge on that occasion. I think we'll have to deal with it as-is.

Please disregard my past few comments, the original PR is what I'll intend to push.

**Comment by Lootyhoof** [comment]
@SpockFan02 Are we good to close this now?

**Comment by SpockFan02** [comment]
I think so @Lootyhoof.

**Comment by adeshkp** [comment]
I greatly appreciate this work. Now the theme sports a more professional and polished look. Good job!

However, I noticed that when bookmarks toolbar is hidden, there is a small triangular white space near the tab corners between the tabs, and it looks slightly odd. I hope this can be addressed.

<img width="1392" alt="tabs" src="https://user-images.githubusercontent.com/29352104/78424100-c6bb1280-7688-11ea-95d9-2f330314c1ce.png">

Also, I think there can be a 1-2 pixels of space between tabs to avoid the double border, but I guess we won't agree on this.

Thanks, @Lootyhoof !

**Comment by Lootyhoof** [comment]
The "triangle" is due to the tab curve. Unfortunately due to the way OS X handles toolbars, two things happen:

1. Only the top toolbar is merged with the titlebar.
2. This toolbar gets an automatic border styling from the OS.

You CAN style the tab bar in the same way if you want, though it will come out as below:

![Tab bar with toolbar styling](https://i.imgur.com/rUMoQk6.png)

I'm not a huge fan of the double border though (again, this is due to the `-moz-appearance` styling) and you'll still get the "triangles" either way.

As for the tabs: The above screenshot was taken with #1759 merged, with uses the same styling for tabs as Windows:

![Windows tabs](https://i.imgur.com/4w8jA0a.png)

**Comment by Lootyhoof** [comment]
Although...looking at that screenshot some more I'm kind of warming up to it a little, it gives off a Safari-ish vibe for the tab bar in that mode.

What do we think? @SpockFan02 @adeshkp ?

**Comment by adeshkp** [comment]
I have no issues with square tabs. Both Safari and Firefox have them anyway so people should be used to them on Mac.

**Comment by Lootyhoof** [comment]
I was referring to the background style of the tab bar, not the tabs themselves. I don't want to change the tab styling.

**Comment by adeshkp** [comment]
Oh, ok. Regarding the tab background, I'm in agreement. We can do that.

**Comment by Lootyhoof** [comment]
I've had similar opinions outside of this thread, so I'll go ahead and put another PR together. Re-opening this for now.

**Comment by SpockFan02** [comment]
So the change you're talking about is making the tab bar have its background styled like the titlebar when the bookmarks bar is hidden?

**Comment by Lootyhoof** [comment]
Yes. Though as per my previous screenshot it does have its own border (OS-provided) so it doesn't blend with the titlebar per se, but has a slight Safari-ish vibe about it (in my opinion anyway).

**Comment by SpockFan02** [comment]
I think I prefer it the way it is now: <img width="112" alt="Screenshot 2020-04-06 16 51 47" src="https://user-images.githubusercontent.com/11634417/78615651-fbfd6700-7826-11ea-8702-e1a91e896c03.png"> Although it would be good if we can figure out why it is white in Mojave and Catalina. Having the tab bar change colour depending on whether or not the bookmarks bar is present seems a little weird, but my opinion is not that strong.

**Comment by Lootyhoof** [comment]
It would be visually similar to how Windows implements it (minus the extra borders):

![Windows without bookmarks](https://i.imgur.com/KptDUHj.png)
![Windows with bookmarks](https://i.imgur.com/qiNK6mB.png)

**Comment by Lootyhoof** [comment]
As of #1767 this is complete. Closing.
