### ISSUE TITLE
Unable to view with the latest unstable my plain and simple server - certificate expired - no way to bypass as before, page blank

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1753]
Unable to view my own webserver anymore with the latest unstable.
https://saphirjd.me/root/pub/mods

It is a plain and simple website which requires no special webcompatibility featues. Works with latest stable - the server is hosted with the help of my own connection at home - my current connection over the mobile web of my provider.

No errors in the consoles appearing, browser just goes blank.

**Edit: I know the certificate is expired - but this should still be possible to bypass - this also allows Otter, IE11 or Chromium**

**Comment by SpockFan02** [comment]
You are using a certificate which expired on July 15.

**Comment by Sa-Ja-Di** [comment]
Does not explain why it does not work with unstable. Earlier it worked, even with an expired one.

**Comment by wolfbeast** [comment]
Should pop up the certerror page but it doesn't and silently fails. Just keep the server state as-is please so I can use it to test

**Comment by Sa-Ja-Di** [comment]
> Should pop up the certerror page but it doesn't and silently fails. Just keep the server state as-is please so I can use it to test. Will look at this for possible cause when I wake up again

This server is online 24 hours a day, as it is a special dedicated machine at home, so the url will stay relevant until further notice :D

**Comment by wolfbeast** [comment]
Yeah certerror pages were busted because it was still looking for HPKP information in the checks.

**Comment by wolfbeast** [comment]
Verified fixed in latest unstable.
