### ISSUE TITLE
macOS history swipe navigation does not work

### ISSUE THREAD

**Issue by SpockFan02** [MoonchildProductions/Pale-Moon#1754]
As mentioned in #1715, history swipe navigation does not work.

Expected: Two-finger horizontal swipes on a Mac trackpad should move back and forward in page history.

STR: Open a Pale Moon tab, navigate somewhere so there is history, and swipe horizontally with two fingers. Nothing happens, or if the page is wider than the window, it scrolls horizontally.

This is a regression from Tycho (the move to UXP broke it). Please assign me, I would like to work on it.

**Comment by SpockFan02** [comment]
Looks like my "This resolves" didn't work

**Comment by wolfbeast** [comment]
... great... OK I'll back it out then.

**Comment by SpockFan02** [comment]
@wolfbeast I apologize for the misunderstanding, I meant that in the pull request at the end I said "This resolves Issue" and then the issue number and I expected it to close the issue automatically. The feature works as intended, I only meant I didn't use the GitHub thing correctly.

**Comment by wolfbeast** [comment]
Oh.. sorry! Totally misunderstood.

**Comment by wolfbeast** [comment]
Re-landed

**Comment by wolfbeast** [comment]
Next time leave out the word "issue" -- `This resolves #1754` works.
