### ISSUE TITLE
28.9.0.2 / 28.9.0.1 crashes

### ISSUE THREAD

**Issue by tsifra** [MoonchildProductions/Pale-Moon#1757]
Don't know how to get tech details on this. I believe i was on 28.9.0(from ppa) and it was stable. Recently 28.9.0.1 was released and browser started to crash. I've waited for 28.9.0.2 but problem is still there. I'm on ubuntu 18.04 64 bit. To guarantee crash you can browse facebook.

Today i've tried to build from source 28.9.0 and had same result. Maybe it's somehow related to XUL Platform. Don't know. Please let me know how to collect needed data to investigate.

**Comment by wolfbeast** [comment]
Please head over to the forum for initial troubleshooting and for help with getting required data to investigate. https://forum.palemoon.org/

**Comment by wolfbeast** [comment]
This was determined to be a graphics driver issue.
