### ISSUE TITLE
Cleanup OS X default theme

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#1758]
Following the redesign work in #1751 I noticed this theme isn't quite up to par with the same on Windows. Specifically:

- CSS Variables aren't being used (code cleanup)
- HiDPI toolbar icons aren't being used (#1736)
- There are several `glass` icons which aren't required here (OS X has no glass), for example `Toolbar-glass.png` and `newtab-glass.png`.

I'm happy to do this if we're in agreement.

**Comment by wolfbeast** [comment]
Sounds like a plan.

**Comment by wolfbeast** [comment]
Was there anything else for the OS X side we need or is this it?

**Comment by Lootyhoof** [comment]
The PR does all I'd set out to do, so I'd say we're good. There might be some more cleanup application-wide for themes but I'll open another issue for that.
