### ISSUE TITLE
Please provide a workable exe/zip build

### ISSUE THREAD

**Issue by xalaineus** [MoonchildProductions/Pale-Moon#1765]
Hi,

Please provide a workable exe/zip build (also if portable too better)
after each verified commit so can test them and report then easily before
they are released.
Github with AppVeyor already provided an option for this and other software use this.
It will make life of a tester very easy so please strongly consider this.

EG of this automatic is here

URL: https://github.com/notepad-plus-plus/notepad-plus-plus/compare/v7.8.5...master

scroll to Update copyright 3de506b 

Click the green tick near the commit

details

Environment: platform=Win32, archi=x86, platform_input=Win32; Configuration: Unicode Release
Environment: platform=Win32, archi=x86, platform_input=Win32; Configuration: Unicode Debug
Environment: platform=x64, archi=amd64, platform_input=x64; Configuration: Unicode Release
Environment: platform=x64, archi=amd64, platform_input=x64; Configuration: Unicode Debug
Environment: platform=mingw-w64_810_X64, platform_input=mingw; Configuration: Unicode Release
Environment: platform=mingw-w64_810_X64, platform_input=mingw; Configuration: Unicode Debug

select any one

eg Environment: platform=Win32, archi=x86, platform_input=Win32; Configuration: Unicode Release

Jobs Console Messages Tests Artifacts  

now click artifacts tab

here the final exe is available to download and quickly test

Sorry for the bad English
Hope this will be available soon

Regards
JN

@JustOff 
@mattatobin 
@wolfbeast

**Comment by wolfbeast** [comment]
Standard CI is not possible with these projects. Custom CI is outside of our budget.

**Comment by mattatobin** [comment]
I see no point in CI period.

**Comment by wolfbeast** [comment]
CI _could_ have benefits if it was possible with something our size but it simply isn't (unless you own a build farm) even aside from the fact that our build system is non-standard and will never integrate with something generic.
Not to mention that building from each commit to the tree is nonsense.

Tobin does make a point, too. You haven't been in any way involved with this project yet you're making demands as if all of this is for your benefit and you somehow feel we should put in all this work just so you can perform unrequested tests on unspecified builds.

Please use the unstable channel if you're interested in testing and reporting issues.
