### ISSUE TITLE
Max concurrent loading tabs setting bypassed if cache_behavior = refresh

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1772]
Apparently, issuing a reload on restored tabs with `browser.sessionstore.cache_behavior` bypasses the normal mechanism for keeping the maximum number of concurrently reloaded tabs to 3 (or user value).
This results in all tabs being loaded concurrently which can completely lock up the browser and flood the network stack.

**Comment by xalaineus** [comment]
wasn't this reported by someone?
other setting were mentioned right?
can we look into it

**Comment by wolfbeast** [comment]
Wasn't reported as an issue. and commit comments get lost.

**Comment by xalaineus** [comment]
> 
> 
> Wasn't reported as an issue. and commit comments get lost.

oh i see
so new build to be expected?

**Comment by wolfbeast** [comment]
What's the hurry?
