### ISSUE TITLE
Javascript issue

### ISSUE THREAD

**Issue by danrobi11** [MoonchildProductions/Pale-Moon#1774]
Pale Moon wont let me click on some clickable js stuff. 
Matrix is disable and I made sure js was enable in about:config. 
So I dont understand whats wrong with Pale Moon. 
Other than this issue I really like the browser. I'd like to fix this to be able to use it. 
Thx!

**Comment by Nuck-TH** [comment]
Please use Pale Moon forum for troubleshooting and determining exact issue, as this tracker is only for actual bug reports and development tracking.
Also, if you will create topic in forum, please provide examples right away, because without them it is impossible to even look into issue.
