### ISSUE TITLE
Put osx private browsing indicator in its own element

### ISSUE THREAD

**Issue by SpockFan02** [MoonchildProductions/Pale-Moon#1776]
In MoonchildProductions/UXP#553 I restored the private browsing indicator, but because it was done as a background image on #main-window, it interferes with personas (as mentioned [here](https://github.com/MoonchildProductions/Pale-Moon/issues/1751#issuecomment-606879276) and described [on the forum (second point)](https://forum.palemoon.org/viewtopic.php?f=41&t=24185#p187551)). Later versions of Firefox and Basilisk fix this and allow personas to work in private windows by putting the indicator in a separate XUL element.

**Comment by Lootyhoof** [comment]
I think we need to [decide](https://freenode.logbot.info/binaryoutcast/20200410#c3614966) what to do about the titlebar before merging this.

**Comment by wolfbeast** [comment]
@Lootyhoof Trying to custom paint the windowframe on Mac doesn't work very well -- I say we set drawintitlebar to false and be done with it. Let the system handle it natively. It's already different than anything else because of the Mac style menubar, so just let Mac do what Mac should do.

**Comment by SpockFan02** [comment]
As far as I know just about every problem we've had with it originated [when BitVapor replaced the osx theme with the Windows theme](https://github.com/MoonchildProductions/Pale-Moon/commit/01681421e707f84319bc3fa21c8c88d6aabe4e51); all the hard-to-diagnose weirdness has been from misplaced CSS, and it actually works fine. Other than themes and this indicator though, the XUL titlebar is supposed to be identical to a native one anyway, so if you think that's the way to go then OK.

**Comment by Lootyhoof** [comment]
Based on MoonchildProductions/UXP#1516 we should probably close this and the associated PR.

@SpockFan02 There have been various other issues not just related to the theme (things that a theme couldn't possibly control) and since the titlebar doesn't seem to consistently work the way we want it's best this way. While I'm definitely biased I think with the recent changes the default theme is fine on Mac. Plus the original one tried to make itself look native with the OS X version of the time, it looks a little more out of place on later versions. The current theme does attempt to integrate, but has its own identity, so doesn't look overly out of place depending what version of the OS you use.

**Comment by SpockFan02** [comment]
I wasn't saying we necessarily have to go back to the old theme, just pointing to that change as the root of all the titlebar problems I've seen because I thought it was all just theme stuff. I wasn't aware of other issues. Since it seems the decision has been made and we can't put stuff in the titlebar anymore, shall I put it always in the highest toolbar instead? (The PR I made puts it in the nav bar/tabs toolbar depending on which is on top when the window is in fullscreen, because in fullscreen there is no titlebar).

**Comment by Lootyhoof** [comment]
It isn't necessary with the titlebar text being present. If we feel we must add it though, it could be added like it is on Linux, which uses a simple `::before` on the `#TabsToolbar`, no need for any extra XUL or other additional logic.

![Linux private mode](https://i.imgur.com/9huQ3Wd.png)

**Comment by Lootyhoof** [comment]
I should just mention too that the above is how I've personally been handling my themes on Mac for a while.

**Comment by wolfbeast** [comment]
Thanks for clarifying the situation and evaluating the need for doing this in potential other situations.
Looks like this is no longer desirable for any development path; closing.
