### ISSUE TITLE
Kill the maintenance service with fire!

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#178]
The updater "maintenance service" (created by Mozilla to bypass a UAC window that's there for a reason) has been unmaintained, is hazardous because of sec issues, and is never intended to be built as part of Pale Moon release code. It should be killed with fire.

Components:

* configure flag --enable-maintenance-service
* conditional code in MOZ_MAINTENANCE_SERVICE blocks
* NSIS Installer scripting cleanup (e.g. un.UninstallServiceIfNotUsed, etc.)

**Comment by mattatobin** [comment]
I'll take this and do it when I get around to it.. Next few days to next few years I assure you ;)
