### ISSUE TITLE
Duplicate icons in panel

### ISSUE THREAD

**Issue by blipk** [MoonchildProductions/Pale-Moon#1781]
There is a thread with the explanation here:
https://forum.palemoon.org/viewtopic.php?f=37&t=24090

Without the StartupWMClass attribute in the desktop file, duplicate icons will appear on the panel if you have Pale Moon as a favourite.

This had already been updated but the problem is it does not work when in double quotes on some systems. Unquoted value works.

https://github.com/MoonchildProductions/Pale-Moon/pull/1779/files

**Comment by wolfbeast** [comment]
From the PR suggesting `Pale moon` , unquoted:

> Did not work for me with the lower case.

Can someone please figure out why `Pale moon` would work and `pale moon` would not? What about `Pale Moon`? Isn't it just ignoring the "Moon" part in effect without the quotes?

I'd prefer not to break setups to fix others.

**Comment by blipk** [comment]
When I launch the application from the favourite icon on the panel without the StartupWMClass in the desktop file:
```
xprop | grep -i class
WM_CLASS(STRING) = "Navigator", "Pale moon"
```

Pale moon with the capital P is correct, both me and the user in the thread reported it with a capital P.

I have looked at a lot of .desktop files and none of them put the values in quotes.
I'm fairly positive this will work for most users:
`StartupWMClass=Pale moon`

**Comment by wolfbeast** [comment]
Change was merged but should be verified.

**Comment by blipk** [comment]
Works for me.

Probably a little unrelated, but I noticed this isn't even included in the tarball release?
I was using the Fedora COPR repo listed on the palemoon website but that hasn't been updated in close to a year and did not allow me to update from the help menu, I'd highly reccomend removing the COPR repo as a reccomendation.

Might be useful to convert the install instructions here into a shell script and include the .desktop file as well: http://linux.palemoon.org/help/installation/

Can also do a clickable installer with something like the following:
```
[Desktop Entry]
Version=1.0
Name=Install Pale Moon
GenericName=Install Pale Moon
Comment=Install Pale Moon Web Browser
Exec=bash -c "cd \"$(dirname %k)\" && chmod +x _install.sh && ./_install.sh && zenity --info --text='Pale Moon Web Browser has been installed.'"
Icon=icons/updater.png
Terminal=false
Type=Application
X-Desktop-File-Install-Version=0.24
```

**Comment by wolfbeast** [comment]
Please take unrelated discussion to the forum. this is an issue tracker, not a discussion group or suggestion board.

**Comment by wolfbeast** [comment]
Please don't close your own issues.

Was this verified on other systems than yours?

**Comment by blipk** [comment]
> Please take unrelated discussion to the forum. this is an issue tracker, not a discussion group or suggestion board.

The issue tracker also supports feature requests and is the case in many repositories, if you'd prefer otherwise, perhaps a note of where such requests should be made should be detailed somewhere.

**Comment by blipk** [comment]
Closing and looking at phasing out use of this product.

Devs have no respect for their long time users who are trying to contribute to making the project better.
