### ISSUE TITLE
-moz-appearance: none

### ISSUE THREAD

**Issue by em92** [MoonchildProductions/Pale-Moon#1786]
Hi!
Follow up from https://github.com/jdan/98.css/issues/76#issuecomment-622413113

**Comment by wolfbeast** [comment]
Please describe the issue.

**Comment by em92** [comment]
There is a css called [98.css](https://github.com/jdan/98.css) that can make your webpage look like you are in Windows 98.

Looks fine in Brave (chromium based browser) and Firefox 68.7.0esr. But in PaleMoon (at least in 28.9.1) checkboxes and radios are duplicated. 

Made an [issue](https://github.com/jdan/98.css/issues/76) about it. @jdan [said](https://github.com/jdan/98.css/issues/76#issuecomment-622413113) that it is possibly bug in PaleMoon, 'cos PaleMoon is not respecting "-moz-appearance: none".

Not a proffessional in CSS, so I can't say whose bug is this.

**Comment by Lootyhoof** [comment]
`-moz-appearance: none` is perfectly functional here, it's an issue with the site.

I'll follow up.
