### ISSUE TITLE
array subscript eCSSProperty_COUNT is above array bounds of 'const uint32_t [364]'

### ISSUE THREAD

**Issue by sedimentation-fault** [MoonchildProductions/Pale-Moon#1787]
My Gentoo system throws this QA Notice that I have not seen being discussed here, so I thought I would report it:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
...
46:17.40 /xxxx/portage/www-client/palemoon-28.9.2/work/palemoon-28.9.2/platform/layout/style/nsCSSProps.h:481:46: warning: array subscript eCSSProperty_COUNT is above array bounds of 'const uint32_t [364]' {aka 'const unsigned int [364]'} [-Warray-bounds]
```

Maybe you would like to have a look if this is a severe as it says.

P.S. The other two warnings that I left out (indicated by '...') have already been discussed in https://github.com/MoonchildProductions/Pale-Moon/issues/1581.

**Comment by wolfbeast** [comment]
**rpmlint needs to go back to school.** Please stop relying on its warnings and making issues about them unless you've verified that it is, in fact, a code error and not a linter error.

The arrays in question are defined using `eCSSProperty_COUNT` so by definition cannot go out of bounds. Also because it's 0-based, "count" will always be "max index + 1", so this is entirely accurate.
In addition there is an assert of this condition being true with a `<` not 2 lines up.

**Comment by sedimentation-fault** [comment]
I did not use _rpmlint_, it is not even installed here. This was a warning of my Gentoo build system, based on GCC warnings. As someone who is not versed with your code, I have neither the knowledge, nor the time to step into it as deep as you are asking (i.e. to _"verify that is, in fact, a code error and not a linter error"_). Besides, it was a warning and not an error, so you should treat it as such, i.e. take it with a grain of salt.

I am happy we have a place where this has been discussed once and for all - that was my intention, to let you have a look at it, just in case it was something serious.

P.S.: I don't know if, in your language, the expression _"X needs to go back to school"_ is a lovely way of expressing the need to improve X - to me it sounds arrogant and insulting. You should not then take exception if someone comes and says to you what @StefanBruens politely said in https://github.com/MoonchildProductions/Pale-Moon/issues/1581.

**Comment by wolfbeast** [comment]
You referred to another issue with a linter with no other context than an error thrown by the package manager in use, so the assumption was that this was another linter problem. As someone who is not versed in Gentoo or whatever its build system decides to label "severe" when it's not an error, I have neither the knowledge nor the time to analyze every warning it complains about that you are asking (i.e. "have a look if this is a severe as it says"). 

If you don't have the necessary knowledge to verify these issues you should raise them on the forum, not here.

**Comment by mattatobin** [comment]
BTW, This issue tracker is for our benefit not yours. Please refrain from making issues without direct request to do so.

Please fallback to the forum.

**Comment by sedimentation-fault** [comment]
Look, @wolfbeast, my Gentoo build system complained about "severe" warnings. Because I use Pale Moon (and very heavily), I want all the best for it. When I get such warnings that claim to be "severe", my first reaction is to report them - not to Gentoo, because they explicitly point "upstream" in such cases.

There were three such warnings and I made a _bona fide_ effort to report only the one that was not already treated here. My honest thinking was "the other two are known, but maybe this one is new". 

@mattatobin, if this is not a public issue tracker, isn't there a way to make it private, so we plain users don't waste our time (and yours) reporting severe warnings from our GCC that are not welcome here? And if this is not the right place for such reports, what is the right place?

At the very least, there should be a message warning the potential issue opener that issues should be opened _on direct request only._

Anyway, now that I know, be assured that I will abide by these "rules" and will not bother you again (unless explicitly requested, of course). :roll_eyes: 

And finally, @wolfbeast, **I am taking offense because you seem to expect from others a respect that you by no means are willing to offer**. It is disrespectful to talk in this manner for a tool - even if you may have valid reasons. The makers of the tool certainly put a lot of sweat, blood and tears into it - just as you do with yours.

**Comment by StefanBruens** [comment]
@sedimentation-fault - Pale Moon is a fork of heavily outdated firefox code, "maintained" by some guys who "know" C and C++ better than the GCC and LLVM folks. I leave it to you to draw any conclusions ...

**Comment by wolfbeast** [comment]
I responded in the context given, which is the context of a linter. You chose to escalate it.

Yes this is an open issue tracker. Yes anyone can create issues. I don't agree with the stance that it should _only_ be used on explicit request, but I _do_ ask that due to your chosen environment which **must** be first verified in a known environment that you direct further reports to the forum first.

All of this (as well as this tracker being public) is to help our development be better organized.
I already said the effort is appreciated. Don't make it into a drama fest worthy of attracting the shills.
