### ISSUE TITLE
Compatibility with website caf.fr

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/Pale-Moon#1788]
[CAF](https://fr.wikipedia.org/wiki/Caisse_d%27allocations_familiales_(France)) is the French social security system, therefore its website [caf.fr](https://www.caf.fr/) is amongst the most popular websites in France. Sadly, this website is unusable in Pale Moon currently.

How to reproduce:
* Go to [caf.fr](https://www.caf.fr/).
* Click on « 🙎‍♂️ MON COMPTE » (i.e. "login") at top right.

Current behaviour:
* User is redirected to [some useless page](http://www.caf.fr/page-carrefour?dest=monCompte&os=).

Expected behaviour:
* User is redirected to a login page, as you gets with the other browsers.

What I have tried:
* Other browsers (Edge, Chrome, Firefox) work correctly.
* Tried the different user agents in "Preferences > Advanced > User Agent Mode", without success.

The problem is possibly at the website end. Though, this issue might help gather more information on your side, that I could transmit to the webmaster.

**Comment by wolfbeast** [comment]
I'm sorry but I don't see the issue.
Aside from the website initially thinking Pale Moon is a mobile browser (which is indeed something the webmasters will have to fix) which requires a click on "register" next to the image of the mobile phone presented, the site simply and correctly forwards to the exact same page one gets in other browsers.
So the issue would be browser detection and presenting an extra page. That isn't a browser bug. Why did you create a tracker issue for it?

Please in the future with (perceived) web compatibility issues, always first and foremost post on the [Pale Moon forum](https://forum.palemoon.org).

**Comment by vlakoff** [comment]
I hadn't tried that huge blue button actually, I went too fast and I thought it was a fallback "go back to website home" button. But indeed, it leads to the desired login page.

The page was so strange-looking that I assumed it was a bug…

Still, I shall report the false-positive mobile detection to the webmaster, though I don't have much hope they will care to fix it…

**Comment by wolfbeast** [comment]
> though I don't have much hope they will care to fix it…

if they are a website of public interest, they _should_ pay attention to this kind of feedback.

**Comment by vlakoff** [comment]
I reported this issue to [service-public.fr](https://www.service-public.fr/P10017) (French administration) right after our discussion.

It seems they have fixed the issue already. Pretty impressive!
