### ISSUE TITLE
XPCOM Error

### ISSUE THREAD

**Issue by rcrx** [MoonchildProductions/Pale-Moon#1789]
Received the following error when attempting to run x86 tarball version 28.9.3 on Pop!_OS 20.04:

```
XPCOMGlueLoad error for file palemoon/libxul.so:
libfreetype.so.6: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

**Comment by wolfbeast** [comment]
Sounds like you need to install some additional dependencies that don't come default in your specified O.S. -- for support, please go to the forum https://forum.palemoon.org/

Unlikely this is a software bug, closing.

**Comment by rcrx** [comment]
```
$ whereis libfreetype.so.6
libfreetype.so: /usr/lib/x86_64-linux-gnu/libfreetype.so.6
```

```
$ export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
```

```
$ ./palemoon/palemoon
XPCOMGlueLoad error for file palemoon/libxul.so:
libfreetype.so.6: wrong ELF class: ELFCLASS64
Couldn't load XPCOM.
```
The solution was to run 32 bit version, which launches without error. `x86` tarball appears to be incompatible with the most recent Pop!_OS LTS release.
