### ISSUE TITLE
View Image Info not working some sites

### ISSUE THREAD

**Issue by davews1** [MoonchildProductions/Pale-Moon#1790]
For sites that use lazy-loads right-click view-image-information does not show the selected image file rather just a list of all files on the site.
eg https://www.bracknellnews.co.uk/

![image](https://user-images.githubusercontent.com/28691148/81819704-95572180-9527-11ea-94c2-761e1d1e668d.jpg)

Discussion at https://forum.palemoon.org/viewtopic.php?f=3&t=24378

**Comment by mattatobin** [comment]
This potentially affects all browser applications. Will have to check and if so this could be moved to UXP's issue tracker.

**Comment by wolfbeast** [comment]
No, it's something in the FE code. Basilisk has no trouble selecting the correct one.

**Comment by wolfbeast** [comment]
Following discussion and analysis on IRC this turned out to be absolutely invalid page design, misusing responsive elements.
FTR it causes the exact same issue in Fireflux.
