### ISSUE TITLE
browser "feature" detection...

### ISSUE THREAD

**Issue by Brian151** [MoonchildProductions/Pale-Moon#1793]
...looks like it's getting worse >.<
I've already had a small handful of sites/apps outright refuse to run on pale moon, but those have been fairly isolated incidents until last night...

This **could** be related to the other issue I just submitted, except it was observed last night before the strange behavior...

You may seriously want to look-into chrome user agent spoofing as it appears Unity WebGL and Cocos2D [not certain on this one as I only play two games made with it] now are pulling-out the big scary "browser not supported" warning... Unity for now simply complains/warns. Cocos2D [or at least the one game i tried to play last night] takes the more aggressive approach and REFUSES to boot the game, DEMANDING you play on chrome. 

I'd report this to the respective engines except given they know EXACTLY what they said in those messages, it wasn't "this feature isn't available" , it was "we're assuming the browser you use doesn't support it because we don't develop/test with your browser", i don't expect them to lift a finger unless this causes immense backlash. Youtube also tried this several months ago... 

This just needs to stop, but it seems making the browser commit identify fraud is more effective than telling developers to not use browser checking in their code... >.< [shall i grab my tinfoil hat, while i'm at it?]

**Comment by wolfbeast** [comment]
Please do not use this issue tracker as a discussion forum. -> https://forum.palemoon.org

**Comment by Brian151** [comment]
while i agree there needs to be a large and loud discussion about this, i didn't report an issue with that goal specifically in mind. 

rather, i suggested a possible and hopefully temporary solution, as well as to warn you and any users of this browser what's going-on. whether misguided or malicious, this damages your browser's reputation and possibly you as a developer. 

i won't discuss this further, but the response is disappointing and not the first time i've witnessed such. i thought one of the goals of this browser was to be pro-user like firefox once was. browser blacklisting is the exact opposite of that, but it's luckily often fairly easy to mitigate and bypass at the browser level, hence my suggestion. manual overrides and extensions both failed...

as for the forums, i both lack an account and rarely/never any time i landed on it found the answer i was looking for.

that will be all

**Comment by wolfbeast** [comment]
Look, it's something discussed with some regularity and we have site-specific user-agent overrides for a reason. There really is not much that should be discussed -here-. This is a bug tracker/issue tracker. it is not a place to discuss general design issues or directions. This is here to help our development in concrete ways. Everything else is discussed on the forum or to a lesser degree on IRC. The response is simply "you're using the wrong channel to raise this"; doesn't mean we aren't aware of it or actively working on it.
