### ISSUE TITLE
Request: Change default, privacy-invasive homepage

### ISSUE THREAD

**Issue by AlwaysLivid** [MoonchildProductions/Pale-Moon#1794]
Hello there, I recently decided to give Pale Moon a shot, since it seemed like a pretty interesting project that some of my other friends use as a daily driver.

However, I was fairly put off from the default homepage, which offers advertisements in the homepage, saves tracking cookies and [has a fairly transparent, albeit immensely concerning privacy policy](https://start.me/privacy) for a default option. Therefore, I'd like to request either the replacement of the home page with either a more privacy-friendly option or the introduction of a web interface that would simply include the logo and a search bar to a preferred service, which is a function that's similar to what Google Chrome and Firefox offer by default.

Should the latter route be considered, I'd also like to add that the default search engine doesn't necessarily have to be Google's search engine, which is offered to users by the most popular browser vendors due to monetary deals.

**Comment by AlwaysLivid** [comment]
Of course, I know that the homepage can be changed, but I just thought that it was a weird experience for someone who just tried out the browser after being introduced to it solely thanks to the word of mouth. It seemed a bit out of place and reminded me of that era in the late 2000s/early 2010s where I did have to remove adware and invasive browser "'toolbars" (which often changed the default search engine to the likes of [Yahoo](https://yahoo.com) and [start.me](https://start.me) from computers that were severely underperforming because of them a decade ago, and it didn't really make too good of a good first impression on me.

I'd like to stress that I'm not attempting to advocate for options that may risk the quality of the overall experience from a balanced perspective (since some solutions that are more privacy-friendly can be more inaccurate and frustrating to most people) or otherwise stripping freedom of choice from the user.

**Comment by wolfbeast** [comment]
Sorry but that will be a no.
We've had a partnership with start.me for 5 years now and it has been **by popular request of our user base** to have a solution to make the home page (traditionally offering links to popular sites) **configurable**.

They provide this service to Pale Moon users free of charge, even in an anonymous fashion that I worked with their team with to get implemented in a privacy-friendly manner. In turn they fund their service with affiliate linking from the portal -- it is a fair deal: people using the service provide income to them. People who don't use the service don't, and aren't subject to their privacy policy either.

It is our out-of-the-box setup. It takes exactly 10 seconds to change it in preferences to something you prefer and you will never have to deal with start.me again if you don't want to.

**Comment by AlwaysLivid** [comment]
> Sorry but that will be a no.
> We've had a partnership with start.me for 5 years now and it has been **by popular request of our user base** to have a solution to make the home page (traditionally offering links to popular sites) **configurable**.

Makes sense-- I wasn't aware of any open-to-the-public funding programs or find anything on the website about the partnership (although I did manage to find an article from 2015 about it). Anyways, thanks for the response, I appreciate your work.
