### ISSUE TITLE
Seperate Each tab per sub process instance in task manager

### ISSUE THREAD

**Issue by adamkenway007** [MoonchildProductions/Pale-Moon#1798]
Hello could you make palemoon seperate tab for apps subs processes similiar like chrome? so i could force close an not responding (when shows not responding for long time) tab without restart palemoon, i wish in task manager / show tab sub processes per instance.it's annoying when i can't close unrespond tab when task manager only show up the main active selected tab in task manager not others active tab

Sorry for my bad english :-)

**Comment by wolfbeast** [comment]
We do not support multi-process browsing.
