### ISSUE TITLE
Missing releases?

### ISSUE THREAD

**Issue by ironchicken** [MoonchildProductions/Pale-Moon#1801]
Hi there,

I need to get the source code for the 28.7.2 release from Oct 2019 but it seems to be missing from the releases. There's actually quite a big gap on the releases page from ~Mar 2020 to ~Jul 2018. The XUL source code releases (including 28.7.2) seem to be present, but not the Palemoon releases.

For background: I want to continue using Conkeror and 28.7.2 is the last Palemoon version with which Conkeror works. I currently have a Debian package for 28.7.2 installed but it has dependencies which are getting quite out of date so I'd like to try doing a build myself.

**Comment by wolfbeast** [comment]
Earlier UXP-based releases of Pale Moon are found in the UXP repo.

**Comment by ironchicken** [comment]
Ah I see, thanks!
