### ISSUE TITLE
How to cross compile PaleMoon for Illumos/OpenIndiana from Linux?

### ISSUE THREAD

**Issue by hoper-a11y** [MoonchildProductions/Pale-Moon#1803]
The compilation on OpenIndiana is too slow. It took nearly 4 hours to complete. The PaleMoon build on Linux, in the other hand, only took 45 mins to complete. So it's more than 5x slower than the Linux build! I asked here to know if I could cross compile PaleMoon for OI from my Linux system and how to do it. It will save me a lot of time. Thanks.

**Comment by hoper-a11y** [comment]
This cross compile stuff is hard. I tried to build the gcc cross compiler and followed all of the instruction but it finally failed. I think I would rather waiting for your official release for SunOS.

**Comment by Nuck-TH** [comment]
You may get help on Pale Moon forum instead of creating and then closing issue on bug tracker that is meant only for reporting actual bugs and development tracking.
