### ISSUE TITLE
Ignoring get or set of property that has [LenientThis] because the "this" object is incorrect. 

### ISSUE THREAD

**Issue by Brian151** [MoonchildProductions/Pale-Moon#1806]
while attempting to access a tbody element using the DOM, this was thrown and it has prevented me from accessing the rows of the table, which my application requires

a google search found this result:
https://stackoverflow.com/questions/27159967/javascript-dom-this-object-is-incorrect

since firefox is installed on this machine, i decided to test it there, and it works.

**Comment by wolfbeast** [comment]
What exactly are you trying to do? Using the devtools' debugger?

**Comment by Brian151** [comment]
something a bit unconventional, parse a webpage's HTML DOM [history page for one of the image booru sites] so i could view/download stuff a bit easier

anyways, the error is still there, but my actual problem was an off-by one error in the query string that made the page return an empty table...

sorry for bugging ya, thought i actually HAD something this time...
