### ISSUE TITLE
Some GitHub project main pages overload system

### ISSUE THREAD

**Issue by Symbian9** [MoonchildProductions/Pale-Moon#1808]
- **Version:** `28.10.0` (amd64); (from [Pale Moon repositories for Debian and Ubuntu](https://software.opensuse.org/download.html?project=home:stevenpusser&package=palemoon) — maintained by *Steve Pusser*)
- **OS:** MX Linux MX-19.1 (Debian 10)

Mostly all main pages of users project (except official GitHub repo pages) **overload system**, after *GitHub* rolled out new front-end update.

![pic.1](https://i.imgur.com/Z48Hfg2.png)

### *Pale Moon* repo main page: 90%

![pic.2](https://i.imgur.com/xWxm78r.png)

### Microsoft Visual Studio Code repo main page: 5%

> NOTE: Microsoft is GitHub owner, so all Microsoft's repo are "GitHub official repos"

![pic.3](https://i.imgur.com/kuTOIMb.png)

**Comment by wolfbeast** [comment]
Unable to reproduce. Please go to the [forum](https://forum.palemoon.org/) to troubleshoot (likely one of your extensions causing problems)

**Comment by Symbian9** [comment]
> Unable to reproduce.

To be honest, seems like GitHub dev team *optimized/fixed some issues with new front-end little later after I posted this issue report*. 

*Just now* so I has no such overload *on the same system with same addons configuration*

![pic.1](https://i.imgur.com/8qIDQi9.png)

So, issue fixed on GitHub side.
