### ISSUE TITLE
Allow using non-predefined search engines

### ISSUE THREAD

**Issue by veita** [MoonchildProductions/Pale-Moon#1809]
Currently users can configure the predefined search engines listed in https://addons.palemoon.org/search-plugins/.

Among them is Wikipedia which is fine. Unfortunately I do not only need the English Wikipedia but also the Wikipedia in my native language. Currently there seems to be no way to configure this - at least not in a user friendly way.

**Comment by wolfbeast** [comment]
Any website offering OpenSearch plugins can be used. You aren't restricted to what is on the add-ons site, and you can also use search functionality that websites offer on the websites themselves (it will add an entry to the search bar drop-down if so).
If you need help with this please use the forum.

**Comment by veita** [comment]
Great. So the trick is to visit the Wikipedia site one wants to search, then to open the search drop-down-box, and click on the `Add "Wikipedia (language)"` entry.

I never knew about that and always tried to add search engines via the `Manage Search Engines...` entry.
