### ISSUE TITLE
Update libjpeg-turbo to version 1.4.2.

### ISSUE THREAD

**Issue by Axiomatic-** [MoonchildProductions/Pale-Moon#181]
There is an update that would be nice to have (seeing that what is currently used is 1.3.0 in which as time has passed bug fixes, and enhancements have been done to libjpeg-turbo). Updating to version 1.4.2 does not seem hard to do. I plan on doing it myself, however I may not get around to it for awhile.

How to update:
See [MOZCHANGES](https://github.com/MoonchildProductions/Pale-Moon/blob/master/media/libjpeg/MOZCHANGES) file in directory.

In case following that does not work, Mozilla has a [diff file](https://github.com/mozilla/gecko-dev/blob/master/media/libjpeg/mozilla.diff) that could remedy any possible issues. 

@wolfbeast can this be a version 26 milestone?

**Comment by wolfbeast** [comment]
@Axiomatic- What is your likelihood of tackling this in the coming week?

**Comment by Axiomatic-** [comment]
Unlikely, sorry. I have a libjpeg-turbo branch [here](https://github.com/Axiomatic-/Pale-Moon/tree/libjpeg-work), which updates libjpeg-turbo to version 1.3.1 for Pale Moon. If you want I can create a pull request for it; however, I would need to check if there are any known CVEs affecting it.

**Comment by mattatobin** [comment]
I will uplift and make and make the build system changes for it after I complete Issue #100 Update libvpx to 1.4.x

**Comment by mattatobin** [comment]
Compile succeeded with v25Dev branch win64..

There shouldn't be any issue for any target platforms with this.

Also, it /should/ be cherry pick-able to Goanna trunk (master branch)

**Comment by mattatobin** [comment]
I left out targets for arm64 and mips because we don't actually build for those .. the un-translated moz.build code for those targets is quoted here for future reference.

'''
    elif CONFIG['CPU_ARCH'] == 'aarch64':
        SOURCES += [
            'simd/jsimd_arm64.c',
            'simd/jsimd_arm64_neon.S',
        ]
    elif CONFIG['CPU_ARCH'] == 'mips':
        SOURCES += [
            'simd/jsimd_mips.c',
            'simd/jsimd_mips_dspr2.S',
        ]
'''

**Comment by wolfbeast** [comment]
v25 updated to 1.4.0, Goanna to 1.4.2 -- closing.
