### ISSUE TITLE
palemoon 28.10.0 fail to build on gentoo x86 32bit 

### ISSUE THREAD

**Issue by custom82** [MoonchildProductions/Pale-Moon#1810]
103:28.86 ../../build/unix/gold/ld: fatal error: libxul.so: mmap: failed to allocate 1683959784 bytes for output file: Cannot allocate memory
103:28.86 collect2: error: ld returned 1 exit status
103:28.86 gmake[4]: *** [/var/tmp/portage/www-client/palemoon-28.10.0/work/palemoon-28.10.0/platform/config/rules.mk:773: libxul.so] Error 1
103:28.86 gmake[3]: *** [/var/tmp/portage/www-client/palemoon-28.10.0/work/palemoon-28.10.0/platform/config/recurse.mk:71: toolkit/library/target] Error 2
103:28.86 gmake[2]: *** [/var/tmp/portage/www-client/palemoon-28.10.0/work/palemoon-28.10.0/platform/config/recurse.mk:33: compile] Error 2
103:28.86 gmake[1]: *** [/var/tmp/portage/www-client/palemoon-28.10.0/work/palemoon-28.10.0/platform/config/rules.mk:494: default] Error 2
103:28.86 gmake: *** [client.mk:409: build] Error 2
103:28.89 1104 compiler warnings present.

**Comment by wolfbeast** [comment]
Make sure you have sufficient memory to build.

**Comment by custom82** [comment]
i have 32gb di ram on my notebook

**Comment by wolfbeast** [comment]
Then why are you running Gentoo 32-bits? it can't address more than 4GB max.

**Comment by custom82** [comment]
PAE kernel!

**Comment by custom82** [comment]
I use it to build the customrescuecd and palemoon is the default browser

**Comment by kn-yami** [comment]
Your **linker** can not address more than 4 GB of memory. The only program that can use PAE to address more memory is your PAE-aware kernel.

**Comment by wolfbeast** [comment]
Please take further discussion to the forum.
