### ISSUE TITLE
Per-monitor DPI change not picked up in Pale Moon

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1811]
Pale Moon, while building on widget code that supports it, is not treated as a per-monitor DPI-aware application.

Ref: https://forum.palemoon.org/viewtopic.php?f=3&t=23394

The fix should be as simple as adjusting the application manifest to indicate per-monitor DPI-awareness of the application (which we have).

@g4jc @mattatobin @Ascrod this might also affect your applications.

**Comment by Lootyhoof** [comment]
Looking at this a bit further it may also be worth including [Bug 1354020](https://bugzilla.mozilla.org/show_bug.cgi?id=1354020) (Use per-monitor v2 on Creators Update) if we're doing this.

**Comment by wolfbeast** [comment]
Per-monitor v2 opened as #1812. Closing this manually because apparently GitHub no longer picked up the need to close the issue through commit keyword.
