### ISSUE TITLE
Not working bypass cached pages when browser reload session

### ISSUE THREAD

**Issue by zgwerby** [MoonchildProductions/Pale-Moon#1815]
Not working force reload saved on last session pages on pinned tabs after startrup with this pref:
`browser.sessionstore.cache_behavior` `2`
Browser ignore this pref and load page from cache.
Where I can see more debug info?

Tech details:
```
Pale Moon 	28.11.0 (64-bit)	20200712131834
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:68.9) Gecko/20100101 Goanna/4.6 Firefox/68.9 PaleMoon/28.11.0
Linux 5.7.8-arch1-1
```

![Screenshot_20200715_191421](https://user-images.githubusercontent.com/30671470/87569381-b545c580-c6cf-11ea-9bb1-b8679089a0a4.png)

UPD: found workahond - clear cache on exit.

**Comment by wolfbeast** [comment]
For pinned tabs this is expected behavior.
