### ISSUE TITLE
Support for Bengali and Japanese fonts.

### ISSUE THREAD

**Issue by samiuljoy** [MoonchildProductions/Pale-Moon#1818]
I am using Pale-Moon on Puppy Linux. Legit one of my favorite browsers and might I add a definite lifesaver. Would love it more if support for Bengali and Japanese fonts were implemented. While logging in for the first time on Duolingo to learn Japanese, I noticed Japanese fonts showed empty squares. The same goes for Bengali fonts.

**Comment by wolfbeast** [comment]
We have full support for non-latin scripting but you have to make sure the required fonts for that kind of support are installed on your system.

**Comment by samiuljoy** [comment]
My bad, turns out it needs manual installations of font packages. Thank you for the response 👍

**Comment by samiuljoy** [comment]
My bad, turns out it needs manual installations of font packages. Thank you for the response 👍
