### ISSUE TITLE
The Blue + to open a new tab is broken some times

### ISSUE THREAD

**Issue by Danilopereira82** [MoonchildProductions/Pale-Moon#1819]
some times he gets stuck in the right with the little squares that show the tabs
and some times he follow the tabs
so i don't know what is going on but i think its a issue

**Comment by wolfbeast** [comment]
Please go to the forum for initial troubleshooting so we can find out if this is a browser issue or not.
https://forum.palemoon.org/

**Comment by Danilopereira82** [comment]
well
nothing
i can't make an account

**Comment by wolfbeast** [comment]
Everyone else can. This isn't the right place to try and help you get a forum account set up though.

**Comment by Danilopereira82** [comment]
yeah i sent an email but the problem is my dns blocking hcaptcha

**Comment by wolfbeast** [comment]
Unblock hcaptcha or if you don't have control over that, use a different DNS server, or register your account from a different computer that does not have overzealous blocking policies in place. We will not remove the captcha from our registration system for obvious anti-spam reasons.

**Comment by wolfbeast** [comment]
Please don't close your own opened issues, certainly not without a comment as to the reason.
Was this solved? Or are you simply not going to follow up on this on the forum?

**Comment by Danilopereira82** [comment]
i think i was just wrong
it was caused by werewolf i think
not a bug on the browser

**Comment by wolfbeast** [comment]
All right. Solving as incomplete.
