### ISSUE TITLE
Toolbarize Menu Button function as default?

### ISSUE THREAD

**Issue by DaniV5** [MoonchildProductions/Pale-Moon#1820]
Could Pale Moon have this instead of being in an add-on only?
https://addons.palemoon.org/addon/toolbarize-menu-button/

**Comment by Nuck-TH** [comment]
Integrating all neat functionality will be too much burden for developers and is not intended way of the browser - be base for user customization with add-ons.
Why **this** particular feature needs to be integrated, especially with working add-on being present?
Also please note that issue tracker is not place for feature proposal or discussion, there is forum for that. Issue tracker is for development coordination and tracking.

**Comment by wolfbeast** [comment]
While we understand it's important for your workflow, it's not something we want to impose on everyone. This is exactly why we have browser extensions that can completely change the UI as-needed.
