### ISSUE TITLE
Linux Mint: palemoon not opening in his icon

### ISSUE THREAD

**Issue by ArthurBacci64** [MoonchildProductions/Pale-Moon#1821]
Pale Moon browser (last version) is opening in his icon on the dock (planck), but after I restart the computer, on I click in the icon, the browser opens in a new icon:
![Captura de tela de 2020-07-30 11-37-15](https://user-images.githubusercontent.com/59983362/88937132-1c2fb680-d25a-11ea-80a2-d33419b0bd72.png)
This is not a big issue, but this is annoying
Thank you

**Comment by wolfbeast** [comment]
Please post on the forum in the Linux board. This Issue tracker is not for general support and integration questions with your O.S.
