### ISSUE TITLE
Some links are not working when nagivating GitHub

### ISSUE THREAD

**Issue by priv-kweihmann** [MoonchildProductions/Pale-Moon#1831]
Reproduction
- login to GitHub
- try to browse a repo you own
- try to click on "Insights"

Expected Behavior
- Insights subpage will be opened

Actual Behavior
- nothing
- `ReferenceError: AbortController is not defined` in JS console + `Strict-Transport-Security: The site specified a header that could not be parsed successfully`

Workaround:
- click on "security" link
- then on Insights -> this works

Version:
- 28.10.0 (64-bit) on Ubuntu 20.04
- no other active plugins/addins

**Comment by wolfbeast** [comment]
Your browser version is out of date.
