### ISSUE TITLE
Clicking "Get Bookmark Add-ons" leads users to Firefox's Add-on Repo

### ISSUE THREAD

**Issue by hujan86** [MoonchildProductions/Pale-Moon#1833]
In the Bookmarks menu, clicking "Get Bookmark Add-ons" would direct users to a page in Firefox's Add-on repository (e.g. "hxxps://addons.mozilla.org/en-US/firefox/search/?category=bookmarks&sort=recommended%2Cusers&type=extension"). Expected behavior is that it should direct to Pale Moon's own add-on page: "hxxps://addons.palemoon.org/extensions/bookmarks-and-tabs/" 

Pale Moon version: 28.12.0 (64-bit)
OS version: Windows 7 x64 & Windows 10 x64 2004

**Comment by wolfbeast** [comment]
Probably another case of hard-coded URLs.

**Comment by wolfbeast** [comment]
So where exactly is this menu entry? Because I don't see it ;)
![image](https://user-images.githubusercontent.com/3359132/92090177-68c55f00-edcf-11ea-8ce4-d2c7fe90123e.png)

**Comment by JustOff** [comment]
Is your browser profile really [that old](https://bugzilla.mozilla.org/show_bug.cgi?id=515435)?

**Comment by wolfbeast** [comment]
All right, so it's a bookmark entry in your places database. nothing for us to do here.
