### ISSUE TITLE
Possibly incorrect platform commit pointer listed on releases page

### ISSUE THREAD

**Issue by djames1** [MoonchildProductions/Pale-Moon#1834]
On the [releases](https://github.com/MoonchildProductions/Pale-Moon/releases) page it states that Pale Moon version 28.13.0 was built with the August 31, 2020 release of UXP.

Building on the August 31, 2020 release of UXP with `ac_add_options --enable-phoenix-extensions` in the mozconfig file causes the build to fail completely in the configure step.

According to [the repo](https://github.com/MoonchildProductions/Pale-Moon/tree/28.13.0_Release) the platform commit pointer for 28.13.0 is commit `42f895f`. This is one commit after the August 31, 2020 UXP release. This fixes the failure when building with `--enable-phoenix-extensions`. 

I was not sure which commit 28.13.0 was actually built with so I wanted to bring this to your attention just in case the commit listed on the releases page is incorrect.

**Comment by wolfbeast** [comment]
This has already been fixed with a re-tag.
