### ISSUE TITLE
Move the builder from Python2 to pure Make

### ISSUE THREAD

**Issue by megastallman** [MoonchildProductions/Pale-Moon#1839]
As long as Python2 has reached its end of its life, and the Palemoon's builder is not about to undergo any big changes, does it seem possible to replace those Python2 scripts with pure Make? Of course it would add more portability to the browser.

**Comment by wolfbeast** [comment]
Unlikely to happen, but if you want to have development discussion about it, this issue tracker is not the right place for it. Please go to the forum to discuss.

**Comment by micwoj92** [comment]
@megastallman wouldnt p2 to p3 be much more logical in that situation?

**Comment by wolfbeast** [comment]
Did I stutter or something?
 if you want to have development discussion about it, this (application-specific) issue tracker is not the right place for it. Please go to the forum to discuss.
