### ISSUE TITLE
plain html4 frames site not working

### ISSUE THREAD

**Issue by rofl0r** [MoonchildProductions/Pale-Moon#1840]
https://www.ra.is/unlagged/ 

> Content Security Policy: The page’s settings blocked the loading of a resource at https://www.ra.is/unlagged/contents.html (“default-src 'none'”).

**Comment by wolfbeast** [comment]
The content security policy given is:
```
default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';
```
Since there is no specific source rule given for frames, it falls back to default-src. Since that is set to "none", the load is denied. If it loads in any other browser then they are not spec compliant since Pale Moon is doing exactly the correct thing according to the CSP given.

**Comment by rofl0r** [comment]
did content security policy exist in the HTML4 age?

**Comment by wolfbeast** [comment]
That doesn't matter. CSP controls delivery, not content.
If CSP is enforced then it has to be correct, or pages might not load. And frames are still a thing in 2020, you know? that's why CSP has `frame-src` and `frame-ancestors`.

**Comment by wolfbeast** [comment]
Closing as WFM; the feature does exactly what it should be doing.

**Comment by rofl0r** [comment]
so for you it's OK that not a single frameset-based site from the past will work with palemoon (at least with default settings) ?

**Comment by wolfbeast** [comment]
With the CSP given? Absolutely.
You want the site to work? Then learn how to write a proper content security policy.

**Comment by rofl0r** [comment]
it's not my site, and i have my doubts i can convince its author to add a CSP just to make it work with palemoon 15 years after the site was written.

**Comment by rofl0r** [comment]
for the record, the site actually returns a CSP header (as can be seen with e.g. curl), so i guess it's its admin's fault after all.

> Content-Security-Policy: default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';

this wasn't quite clear when @wolfbeast said:

>The content security policy given is: ...

i assumed that was the default policy of palemoon.

**Comment by wolfbeast** [comment]
> i assumed that was the default policy of palemoon.

There is no default policy in any browser except "allow all". Any and all CSPs will be sent by the server, and it's the browser's task to adhere to the policy given.
