### ISSUE TITLE
Establish Golden Beta Branding

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Pale-Moon#1842]
Because the `unofficial` branding is now generic we need a non-`unstable` branding option for "should be stable but might have bugs" situations like `Macintosh`.

So I am creating this branding as `beta`.

@dbsoft You should take note of this **_BEFORE_** you release today's build. Though you will have to copy into the release code this one time. HOWEVER, I cannot create the `Macintosh` icons from here so you or @adeshkp need to to complete this issue. Whichever one of you gets to it first.

I am going to do part 1 of this issue my self so a `Issue #1842 - Part 2: Mac icons` commit will need to be done by one of you.

I appreciate it.

**Comment by wolfbeast** [comment]
I can create mac .icns files no problem.

**Comment by wolfbeast** [comment]
OK seems a few more things needed to be fixed anyway so I'm taking that part on me. Verification if the resulting .icns files are correct would be appreciated.

**Comment by dbsoft** [comment]
The icns worked fine, didn't notice any obvious problems with the branding.  Looks much better than the old New Moon branding to me!

**Comment by mattatobin** [comment]
Alright, since the icons are verified... Closing as **RESOLVED FIXED**
