### ISSUE TITLE
Bookmarked js code execution

### ISSUE THREAD

**Issue by kufue** [MoonchildProductions/Pale-Moon#1843]
I forgot how stylem works and searched again how to view sites darker. 
I found https://www.reddit.com/r/palemoon/comments/iy93tj/is_there_an_extension_or_addon_for_palemoon_to/ 
where one soulution is 

**Make a bookmark with this in it:**
``
javascript:(function(){N=document.createElement('link');S='*{background:black !important;color:grey !important}:link,:link *{color:#ddddff !important}:visited,:visited *{color:#ddffdd !important}';N.rel='stylesheet';N.href='data:text/css,'+escape(S);document.getElementsByTagName('head')[0].appendChild(N);})()
``

I think its a security bug because even if someone altered your bookmarks.html, you first must go through a dns and firewall and router, and pure js code is just executed on current tab

**Comment by wolfbeast** [comment]
Maybe you aren't aware but bookmarklets is a thing and has always been a thing in Pale Moon. It's not a security bug, it's a feature!
