### ISSUE TITLE
Convert hostname to upper case to detect link manipulation [security enhancement]

### ISSUE THREAD

**Issue by danykey** [MoonchildProductions/Pale-Moon#1844]
Hello,

To avoid link manipulation I suggest add an option which enables conversion hostname to upper case in address bar;

For exampe:
https://www.microsoft.com -> https://www.microsolt.com
https://www.MICROSOFT.com -> https://www.MICROSOLT.com

Thanks.

**Comment by wolfbeast** [comment]
Thanks for the suggestion but we already have domain highlighting which does not manipulate the casing of the domain name. In addition, this case changing would not work with IDNs.
