### ISSUE TITLE
[Question]How to "Report deceptive site..." ?

### ISSUE THREAD

**Issue by sebma** [MoonchildProductions/Pale-Moon#1846]
Hi,

In Firefox-ESR 52.9.0 and Firefox 81, there is in the "Help" menu a "Report deceptive site..." item.

It's not in Palemoon 28.14.2 for Linux.

What is the procedure to "Report deceptive site..." ?

**Comment by wolfbeast** [comment]
Please don't use this issue tracker for general support questions.
go to https://forum.palemoon.org
