### ISSUE TITLE
Github not working correctly in pale moon

### ISSUE THREAD

**Issue by fightthepower** [MoonchildProductions/Pale-Moon#1849]
Using the latest version of palemoon.

-After github login my home page shows **Loading activity...** loading screen  which doesn't load at all. 

-Can't edit comments because when I click on the three dots it just shows a infinity loading screen. 

-If we entera folder in any repo then  we are unable to see the dates or descriptions of any of the files or folders. all are blank.

-While submitting issues, we cant use any of the writing tools such as add bold texts, add italics text , add a link etc. clicking on those doesn't do anything.

**Comment by micwoj92** [comment]
Known issue, you should use this extension to fix https://github.com/JustOff/github-wc-polyfill

**Comment by fightthepower** [comment]
Can you please tell me how to  use that extension. Do I need to use greasemonkey or something

**Comment by micwoj92** [comment]
no, just go to releases tab and double click on the .xpi file, it will install and it does not require restart.
