### ISSUE TITLE
Align SVG-in-OpenType with the spec

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#189]
Although we do support SVG Glyphs in OpenType at the moment, it's a Mozilla vendor-specific implementation and not to spec.

To do this properly, we need to convert it to a spec-compliant implementation. It seems the following set of bugs do this. Fairly close to our Mozilla origin point, so may be relatively easy to implement:

- [x] Bug 906521 - Update SVG-in-OpenType implementation to new spec draft
- [x] Fix transforms when SVGiOT is used in display-lists (currently they are ignored... ?!)
- [x] Bug 916048 - SVG-in-OpenType glyphs use the font's unitsPerEm value, not a fixed 1000-unit space (follow-up for 906521)
- [x] Bug 906646 - Glyphs with an SVG representation should never try to use the "contained glyph width" fast-path to stand in for real glyph extents
- [ ] Bug 906643 - Support animation in SVG glyphs (optional)

**Comment by wolfbeast** [comment]
First checkpoint at Commit 0fa4e4156fdfb2f62a40260e36205ddd05826419

**Comment by wolfbeast** [comment]
Seems transforms are completely ignored when SVG-in-OpenType glyphs are in use, which was pointed out to me by the test sheet linked to from the forum.
Only happens with SVG display-lists, but this just needs fixing. Disabling those would likely be bad for performance; although the question would rather be if this is a concern for this scenario. Doesn't look like we *strictly* need this since we're not going to do this off-main-thread anyway.

**Comment by wolfbeast** [comment]
Unassigning myself since my work on this is apparently not appreciated. If anyone else wants to pick this up, go ahead. Patches welcome against the work branch created for this. bug numbers above should be implemented in order. second point is bug 875329 to fix. Will need manual porting.

**Comment by squarefractal** [comment]
Why drop implementing something that you've already spent considerable time and effort on?

**Comment by wolfbeast** [comment]
Because it'll require a considerable amount of additional time and effort to complete it.

**Comment by chaoskagami** [comment]
If nobody else is doing this at the moment, I'll take it. I've started working on porting bug 875329 into PM (lots of merge conflicts, nothing too difficult, mostly naming.)

**Comment by wolfbeast** [comment]
Thanks for helping out!
Do you want me to pull the work branch forward?

**Comment by chaoskagami** [comment]
I'm currently working on a local branch. I'll fork on my account, push changes there to a branch and PR when done. I think that's how I do it? I'm halfway through task #2 at this point. (My own fault for starting before working off a fork, hah.)

I'll just make sure it's mergeable to master. Does that work well enough? ;P

**Comment by wolfbeast** [comment]
Well you have to understand that the first checked-off point isn't merged to master, it only lives on its work branch. I'll pull it forward by merging master into it so you're at the current state.

**Comment by chaoskagami** [comment]
Okay. Sorry.

Either way, I'm going to clone PM now and push changes to a branch. The branch is based on master, though. For reference, next time, which branch should I work off of?

**Comment by wolfbeast** [comment]
It was more than 300 commits behind, so yeah.. the branch svg-in-opentype-work is what you'll want to work in and make PRs against. I've made it current.

**Comment by wolfbeast** [comment]
If you'll look at that branch you'll see the previous work in it to align it with the current spec for it, and that is what the rest will need to be based on.

**Comment by chaoskagami** [comment]
Okay. Got it. Sorry about the minor confusion.

**Comment by wolfbeast** [comment]
No problem, just wanting to make sure you're working on the version of the code that has the partial work already done, or it'd be a bust and require double work. :smile:

**Comment by chaoskagami** [comment]
I had to squash my commits and move them, but no double work, luckily. :P There's one merge conflict I had to fix, but I'll push it when done.

Provided my changes compile, that's #2 done and the bug #875329's fix imported.

**Comment by wolfbeast** [comment]
Good to hear! Thanks. Updated the task list.

**Comment by chaoskagami** [comment]
The test suite is proving difficult on task 3. Mainly due to our test suite being so uh...behind, or diverged maybe?

We're missing a bunch of svg files in layout/reftests that are patched by the second chunk in task 3. The stuff I just finished was okay aside from a missing README. The second chunk is literally just tests, so it *should* work as is.

How should I handle this? I got the actual code merged for the fix, but the test suite chunk of the bug is completely unmergable. I think we may need to just import newer reftests.

**Comment by wolfbeast** [comment]
We don't really rely on automated testing anyway so tests are not important. If tests become defunct because of the changes you should just remove them from the test suite/tree, and document in your commit message :)

**Comment by chaoskagami** [comment]
Alright. I didn't *break* the automated test for svg-in-opentype, but it's most certainly out of date. I think it still will run, but it will probably fail. I think it doesn't test against spec, but early mozilla implementation.

While we're at it; got a test page so I can see whether the changes are properly functioning? I searched around quickly and had issues finding use of svg-in-opentype in a standard compliant manner. Or any test pages really, for that matter.

Build still going. My processor is dual core, sorry. ;P

**Comment by wolfbeast** [comment]
Yeah I think I actually skipped the tests in my initial commits as well. might as well completely remove them.

As for examples, there are only a few that i know of as well; I think there's a bunch linked from https://hacks.mozilla.org/2014/10/svg-colors-in-opentype-fonts/ though.

**Comment by chaoskagami** [comment]
I made a few mistakes, so there's going to be a few 'fixed dumb mistake' commits.

Build is done. Color seems to work when toggling the about:config preference.

It's in my svg-in-opentype-work branch. Done, aside from the animations (I think?)

![colors](https://cloud.githubusercontent.com/assets/7855098/12006268/f84e83b4-ab9d-11e5-8cfb-32ce947b64d6.png)

**Comment by wolfbeast** [comment]
Yeah it looks the way it is supposed to look. Awesome!
Animations is really optional. Not even sure if I want to inflict this on people so it can be a follow-up for later. Please create a pull request for me to merge in?

**Comment by chaoskagami** [comment]
Can do. Merge to svg-in-opentype-work branch, and you merge from there, or merge directly to master?

**Comment by wolfbeast** [comment]
Merge to the work branch, please, and I'll take it from there to merge to master with pref flip etc after some testing my end.

**Comment by chaoskagami** [comment]
Okay, here we go.

**Comment by wolfbeast** [comment]
Looks like everything is A-OK also in a Windows build!
The only thing that doesn't seem to work on the emoji sheet is some glyphs that are fonts-in-svg-in-fonts :P corner case. Closing this as solved. Animations can be looked at later.

**Comment by chaoskagami** [comment]
I ported as-is from the incoming hg changeset on BMO (the accepted upstream patches) so that edge case probably existed in their source base as well at that point in time, I'd guess, unless I screwed up horribly somewhere (but those kind of mistakes tend to segv.)

Maybe there's another BMO referencing that one. Glad it works in windows, though!

**Comment by wolfbeast** [comment]
Quite possible this was addressed in a later bug that was not dep/block referred. If you feel like going on a hunt, feel free :)

**Comment by wolfbeast** [comment]
I've taken a jab at the animation support but couldn't get it to work. I'll be shipping it preffed-off in v26.0 since it's currently experimental and it's better to ship something that at least renders everything monochrome than having characters missing. If people want it they can enable it with the pref at their own risk.
