### ISSUE TITLE
Add Places context menu to History menu pop-up

### ISSUE THREAD

**Issue by Antonius32** [MoonchildProductions/Pale-Moon#202]
Currently, when a user right-clicks the Menu Bar's History menu pop-up, the Toolbar context menu is displayed. I think the Places context menu should be displayed instead.

**Comment by squarefractal** [comment]
[**@Antonius32**](https://github.com/Antonius32) commented on [Wednesday, October 28, 2015 7:29:59 AM](https://github.com/MoonchildProductions/Pale-Moon/issues/202#issue-113726585 "2015-10-28T01:59:59Z - Replied by Github Comment Enhancer"):
> Currently, when a user right-clicks the Menu Bar's History menu pop-up, the Toolbar context menu is displayed. I think the Places context menu should be displayed instead.

Issue #21
