### ISSUE TITLE
Detect whether the current Windows theme is dark

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#219]
On Windows 8 (and now Windows 10), the system colours can get quite dark. This can mean that dark icons are placed on a dark window frame, making things fairly hard to see. If we had a way to detect via CSS whether the window frame is dark, we could style things accordingly. This would also work for lwthemes.

BMO: [940393] (https://bugzilla.mozilla.org/show_bug.cgi?id=940393), [988191] (https://bugzilla.mozilla.org/show_bug.cgi?id=988191), [1012629] (https://bugzilla.mozilla.org/show_bug.cgi?id=1012629), [1008134] (https://bugzilla.mozilla.org/show_bug.cgi?id=1008134), [1061947] (https://bugzilla.mozilla.org/show_bug.cgi?id=1061947).

**Comment by wolfbeast** [comment]
940393 is the main implementation so that's what needs focus (specifically the part setting darkwindowframe). Immediately weave in the algorithm from 988191 when doing so.
Theme changes can be built for our specific theme on top of that, and small bugfixes implemented from the other related bugs, after that.

**Comment by chaoskagami** [comment]
This issue also applies on Linux when a dark gtk theme is used, fyi. I've had to resort to a modified chrome/userContent.js for a veeeeery long time to fix this one. If there's a way to do this cross platform, I'd be quite happy.

**Comment by wolfbeast** [comment]
This should be given some priority so setting this for the 26.1 milestone.

**Comment by Lootyhoof** [comment]
Note that the implementation linked above is Windows 8-specific, and will not work correctly on Windows 10. The only Mozilla-side bug tracking this is [1192622](https://bugzilla.mozilla.org/show_bug.cgi?id=1196266), and it's been labelled as low-priority with no work having been done to it yet.

It should however be noted that, in particular, the Windows 8 implementation looks for the `ColorizationColor` registry key, in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM`, however Windows 10 also appears to have a `AccentColor` key in this location. Both appear to change when the accent colour changes, though have different values.

**Comment by wolfbeast** [comment]
Apart from actually using this in the theme for e.g. inverted icons, the detection routine is in and seems to work as-intended with commit 07e3c01f5011974fdbd2f59cd37930d062b18ed3

**Comment by wolfbeast** [comment]
@chaoskagami With looking into this in detail with the implementation, there isn't a cross-platform way to do this. Linux may even have the additional problem that different WMs store this in different locations/properties/variables.

**Comment by Lootyhoof** [comment]
The `toolbar[brighttext]` selector, introduced in 1012629 (as linked above) should work for all platforms.

**Comment by wolfbeast** [comment]
Anyone is free to jump in and help, you know. This front-end stuff isn't particularly brain-melty.

**Comment by wolfbeast** [comment]
Is there anything left for this issue to tackle? I think we've got all things covered now?

**Comment by Lootyhoof** [comment]
Looks to be all covered. I rolled 1012629 and 1061947 into one commit in #437, and the rest was implemented previously in commits up to and including 07e3c01.

**Comment by wolfbeast** [comment]
Great then! closing this.
