### ISSUE TITLE
[Feature Request] Android: Update handling or notification

### ISSUE THREAD

**Issue by aphirst** [MoonchildProductions/Pale-Moon#226]
As I have [recently](https://forum.palemoon.org/viewtopic.php?t=10222&p=70537) mentioned on the PM forums, there is currently no means for automatic updates for Android users who do not use the Google Play store; and as web browsers can be particularly problematic regarding security if they happen to be outdated, this is a somewhat serious issue.

If the Android version had a means to, if the user installed the app by Sideloading, either automatically pull an updated .apk, or at least automatically direct users to the PM4A homepage (I found [this page](https://bugzilla.mozilla.org/show_bug.cgi?id=1220773) relating to Fennec describing one way that _they_ could in principle do the "was I sideloaded" check), then there would no longer be any _pressing_ need to do anything relating to F-Droid and so on.

Curious to know what you think.

**Comment by mattatobin** [comment]
It would have to be done VERY carefully and prove that it cannot be triggered when installed from the Marketplace because that is forbidden by Google Play Store policies. Apps MUST not be able to update their own code them selves.

However, a notification only is perfectly fine.

**Comment by squarefractal** [comment]
[**@aphirst**](https://github.com/aphirst) commented on [Fri 20 Nov 2015 12:23:32 PM UTC](https://github.com/MoonchildProductions/Pale-Moon/issues/226#issue-118030208 "2015-11-20T12:23:32Z - Replied by Github Comment Enhancer"):
> there would no longer be any _pressing_ need to do anything relating to F-Droid and so on.

Have a look at [this](https://forum.palemoon.org/viewtopic.php?f=39&t=10222&p=71102#p71102) too.

**Comment by mattatobin** [comment]
Already have...

**Comment by wolfbeast** [comment]
Update handling should be the task of the distribution platform on mobile devices (repositories/marketplaces/etc.) -- Sideloading is an advanced option that implies manual installation, so automatic updates aren't desired there anyway.
As for update notifications; that can be done many other ways than in-app, all equally effective.
