### ISSUE TITLE
Possible `optgroup` and `select` tags rendering issue

### ISSUE THREAD

**Issue by Martii** [MoonchildProductions/Pale-Moon#227]
So a colleague of mine pointed out there seems to be an issue with `optgroup` and `select` tags in the last 4 releases, or so, of PM.

It is best described at [this url](http://www.wunderground.com/wundermap/?lat=40.75013351&lon=-73.99700928&zoom=8&pin=New%20York%2c%20NY&rad=1&wxsn=0&svr=0&cams=0&sat=0&riv=0&mm=0&hur=0) and showing this screenshot:

![renderissue opt](https://cloud.githubusercontent.com/assets/114709/11317798/c3e7517a-8ff8-11e5-86e7-20c3806dd08e.png)

I have tried a basic `optgroup` on a web page and it seems fine but somehow this site doesn't render correctly in PM but does in other browsers. Tried in 32 bit PM and 64 bit PM under multiple Linux distros and Windows.

Have any suggestions or ideas pertaining to getting this to show properly in PM? TIA

**Comment by wolfbeast** [comment]
Can you let me know exactly which version regressed this? My guess is it's related to fixing the padding in form input elements. Might need a bit more tweaking for particular combinations of CSS.

**Comment by wolfbeast** [comment]
It seems wunderground is doing some really strange styling there. Anyone who hits this bug *really* should be styling the <select> dropdown arrow directly, rather than trying to make it invisible with "text-overflow" hacks like is done here. A simple -moz-appearance:none on the select will take care of that, instead of trying to hack the display with overflow styling that they seem to be doing here.

**Comment by wolfbeast** [comment]
I think the mentioned commit fixes this. At least a try build resolved the issue on wunderground with its hacky styling. :smile:

**Comment by trav90** [comment]
The mentioned commit fixes this for me on Linux as well.

**Comment by wolfbeast** [comment]
Great! I'll close this then.

**Comment by Martii** [comment]
Look forward to the release of this in the wild. Thank you all for the quick explanation and fix. I twiddled a little bit in Greasemonkey just to see if I could fix it but I guess I was on the incorrect path.

Keep up the great work! :)

**Comment by wolfbeast** [comment]
> twiddled a little bit in Greasemonkey just to see if I could fix it

No, this is something that's in the layout engine. Unless you would plan to rewrite the styling in GreaseMonkey, it wouldn't help.
