### ISSUE TITLE
Website bug

### ISSUE THREAD

**Issue by Tnebi** [MoonchildProductions/Pale-Moon#25]
Palemoon is not letting me to click on the icons of each game on twitch.tv (a popular game streaming website). Check here http://www.twitch.tv/directory

**Comment by Tnebi** [comment]
Ok nothing. Seems It was a coincidence. They did just update the website so it's not a bug. Sorry!

**Comment by wolfbeast** [comment]
Please do not post-edit issues to be completely different issues.
If something was invalid or a coincidence, just close the issue and create a new one for a new issue.

**Comment by wolfbeast** [comment]
The icons/thumbnails of videos and categories work fine on twitch.tv for me.

**Comment by Tnebi** [comment]
Sorry about that but I thought that making another thread would be annoying for you guys so I made this post. Anyways it doesn't happens always but seems it's something that happens with some tabs. I mean sometimes(rarely) one of them gets buggy but I can't understand what causes it. Closing the tab and opening another one fixes it while reloading the page doesn't.

**Comment by wolfbeast** [comment]
Sounds to me like a network issue. If it happens again, can you please first try using Ctrl+F5 to force-reload everything instead of closing the tab?
Also, checking if the error console provides any errors (with the red X icon) might help when it happens.

**Comment by Tnebi** [comment]
I will do everything you ask. Anyways it never did happen to me while using Firefox over 6months :)

**Comment by wolfbeast** [comment]
That doesn't mean a thing :)
You may have a particular connection or hardware that doesn't fully like Pale Moon's HTTP pipelining. You can also try switching that off and see if it helps with this issue.
network.http.pipelining and network.http.pipelining.ssl (set both to "false" in about:config)

**Comment by Tnebi** [comment]
Could be my intel graphic card (I have 2 commutable) mmh... I will see. My network no for sure. I'll keep defaults settings for now

**Comment by wolfbeast** [comment]
I don't think the graphics card would matter, because how a page is visually rendered on your screen doesn't change the behavior of clicks (unless of course it's completely misaligned and you're not actually clicking on anything, but that's very unlikely to happen)

**Comment by Tnebi** [comment]
Sorry to disappoint you but actually that can happen and I'm seriously thinking that was the cause because after using PaleMoon today with my ATI gpu I don't have any problem. Will keep you updated anyways.

**Comment by wolfbeast** [comment]
OK, I'll keep this on hold then. please keep me posted if you find out more.

**Comment by Tnebi** [comment]
Ok it happened with Mozilla Firefox too and seems a Mozilla bug then. Solved it by pressing ctrl+f5.

**Comment by squarefractal** [comment]
This one should be fine to close, since the OP has not followed up with details.

**Comment by wolfbeast** [comment]
Yup, fair enough.
