### ISSUE TITLE
import from firefox bookmarks

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#251]
upon a fresh install in windows, the option is given to take bookmarks from either IE, or chrome, even when firefox is installed.

OS: Win 7 x64 (professional?)

**Comment by chaoskagami** [comment]
Use this: http://www.palemoon.org/migrationtool.shtml

Or do it the manual way: http://forum.palemoon.org/viewtopic.php?f=24&t=144

It doesn't make sense to do import from firefox, because it's just a copy. This isn't a bug, really.

**Comment by themusicgod1** [comment]
New users are not going to know that palemoon is firefox underneath and will not use external tools like this.

**Comment by wolfbeast** [comment]
New users are generally aware that Pale Moon is Firefox-related. The migration tool is also quite easily discoverable.
New users also have had no issue being informed and migrating profiles across in the last 6 years.
