### ISSUE TITLE
Add support for encrypted connections to HTTP proxies.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#258]
It seems to generally desirable to use TLS-backed connections to HTTP proxies. Pale Moon currently doesn't support this.

Reference BMO bug: https://bugzilla.mozilla.org/show_bug.cgi?id=378637

This is **not** trivial, and will likely interfere with pipelining connections over proxies as well.
Back-burner material for me personally right now, so if you feel adventurous enough to take this, you are welcome to! :)

Situations that need to be accounted for:
Browser -> Proxy -> Site
Plain + Plain (http over http proxy) *existing* no end-to-end encryption
Plain + TLS (https over http proxy) *existing* end-to-end encryption
TLS + Plain (http over https proxy) *new* no end-to-end encryption
TLS + TLS (https over https proxy) *new* end-to-end encryption

**Comment by wolfbeast** [comment]
This should be solved by Tycho

**Comment by MingcongBai** [comment]
So is this issue fixed at the moment?

**Comment by wolfbeast** [comment]
Solved by Tycho. it will be fixed in the next milestone (v27)
