### ISSUE TITLE
Youtube Lag

### ISSUE THREAD

**Issue by Tnebi** [MoonchildProductions/Pale-Moon#26]
While watching a Youtube video with HTML5 on PaleMoon and I try to move the cursor on the video(so in the HTML5 content area) the video gets laggy. Once I stop moving the cursor it returns normal. I'm running the latest version of PaleMoon 64bit on my Windows 7 64 bit.
PS: Doesn't happen on any other browser

**Comment by Tnebi** [comment]
I've tried to use the flash version disabling HTML5 from here https://www.youtube.com/html5 and it works fine. So I guess it's something related to HTML5

**Comment by wolfbeast** [comment]
Please be aware that this may be a limitation of your 64-bit video driver being slow to draw the cursor over the video area. It's best if you initially try to troubleshoot this on the forum so the community can find out whether this is an actual browser bug or not.

**Comment by wolfbeast** [comment]
Closing this because it's an issue with being driver-locked to a very old hybrid driver version that doesn't work well for HW mouse cursor overlay in Pale Moon's rendering engine.
