### ISSUE TITLE
Open issue: Make WebVTT more useful.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#262]
Reference meta bug (not all deps listed there):
https://bugzilla.mozilla.org/show_bug.cgi?id=629350

Our current implementation of VTT is not mature enough *and* has had parts of the draft spec be changed from under it. It's been disabled for now with the "enable at your own risk" attitude attached to it until it's been updated (if ever...).

This is an open issue, patches are welcome to improve this. Please coordinate if you want to work on this in parallel.

**Comment by squarefractal** [comment]
Given [BMO bug #887463](https://bugzilla.mozilla.org/show_bug.cgi?id=887463), an evaluation of the legal situation with `media/webvtt` may be required.

**Comment by wolfbeast** [comment]
I wasn't aware of the legal issue. Thanks for pointing that out. In tandem with 887463, we also need https://bugzilla.mozilla.org/show_bug.cgi?id=895091 then to switch the parser over to JS if we want to continue supporting WebVTT in Pale Moon (Do we? How widespread is this used anyway?)

**Comment by wolfbeast** [comment]
Legal evaluation:

The LICENSE file in media/webvtt claims copyright to the Mozilla Foundation but also permits use in source and binary forms, so there is no direct legal conflict in the current state in our source tree, but modifications aren't explicitly allowed. This means it can't be maintained by us and should be removed, but there is no urgent need to do so. For further improvements, this library can't be used due to modification restrictions, so it is applicable to this tracked issue in that any improvements will first need a different implementation in place *or* permission from the Copyright holder (Caitlin Potter) to continue using this implementation.
Claim of the IP by Caitlin in the listed BMO bug is not contested, meaning the LICENSE file may, in fact, be incorrect here...? If it is incorrect (clarification needed from the Copyright holder) then we have been misinformed and should address this removal quicker since we are currently aware of the problem.

**Comment by squarefractal** [comment]
[**@wolfbeast**](https://github.com/wolfbeast) commented on [Friday, December 18, 2015 6:25:41 PM](https://github.com/MoonchildProductions/Pale-Moon/issues/262#issuecomment-165771455 "2015-12-18T12:55:41Z - Replied by Github Comment Enhancer"):
> Claim of the IP by Caitlin in the listed BMO bug is not contested, meaning the LICENSE file may, in fact, be incorrect here...?

Caitlin just mentions this on the BMO bug:
>I am also the SOLE INTELLECTUAL PROPERTY AND COPYRIGHT OWNER of this code, despite the LICENSE, until I am handed a diploma.

which means that LICENSE is incorrect here.

**Comment by chaoskagami** [comment]
For anyone who wants to take a stab at this, the js parser @wolfbeast is talking about is vtt.js over here: https://github.com/mozilla/vtt.js

This is probably a pretty easy thing to do; it's possible to load vtt.js via greasemonkey, I imagine since it can be included via a script tag and is cross-browser.
