### ISSUE TITLE
Allow Windows 10 Tablet Keyboard to auto pop-up

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#277]
On Windows 10, typical behaviour of the on-screen keyboard for a tablet is to pop-up whenever a text field is pressed; on Pale Moon, this does not occur. While this isn't an especially important feature (users can click the keyboard icon on the taskbar to manually pop-up the keyboard), it would be "nice to have" the ability to auto pop-up on text field press, especially as I suspect manually making the keyboard pop-up to type every time would get annoying rather quickly.

BMO: [1007063](https://bugzilla.mozilla.org/show_bug.cgi?id=1007063), [1192248](https://bugzilla.mozilla.org/show_bug.cgi?id=1192248), [1192573](https://bugzilla.mozilla.org/show_bug.cgi?id=1192573), [1192720](https://bugzilla.mozilla.org/show_bug.cgi?id=1192720), [1197722](https://bugzilla.mozilla.org/show_bug.cgi?id=1197722), [1221947](https://bugzilla.mozilla.org/show_bug.cgi?id=1221947)

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
