### ISSUE TITLE
Latest beta build (25.3.0_beta3) causes segmentation fault on Linux.

### ISSUE THREAD

**Issue by Axiomatic-** [MoonchildProductions/Pale-Moon#28]
Here is a [backtrace](https://gist.github.com/Axiomatic-/04b7709dbc25bf9e24de).

This occurs on a new profile, so I originally though it to be a GCC bug, as I am running a rolling release distro:
```
[ruby@self-referential ~]$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /build/gcc-multilib/src/gcc-4.9-20150204/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-cloog-backend=isl --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 4.9.2 20150204 (prerelease) (GCC) 
```
However, I have compiled Firefox, and it runs without problems so I cannot figure out what causes the segmentation fault exactly. 

The segmentation fault occured on [this webpage](https://wiki.mozilla.org/Releases).

**Comment by wolfbeast** [comment]
There's not much I can do without knowing where (which function) it crashes, which requires debugging symbols to be enabled (you seem to have disabled them). Also, if you can attach a debugger to get the source file location exactly, I can see what the problem might be - it can potentially be gcc version related and a compiler quirk.

**Comment by wolfbeast** [comment]
I'm leaving this bug open in case you find it's a source code issue. Please do get more info if you can.

**Comment by trav90** [comment]
I've no problems visiting the above mentioned site using 25.3.0b3 when built with GCC 4.7.2.

**Comment by Axiomatic-** [comment]
@trav90 can you share your about:buildconfig? (More specifically your compiler flags.)

**Comment by trav90** [comment]
Sure, here it is (it's the same as the regular Pale Moon for Linux releases):

```
Build tools
Compiler 	  Version 	        Compiler flags
gcc    	gcc version 4.7.2 20121015 (Red Hat 4.7.2-5) (GCC) 	-Wall -Wpointer-arith -Wdeclaration-after-statement -Werror=return-type -Wtype-limits -Wempty-body -Wsign-compare -Wno-unused -Wcast-align -std=gnu99 -fgnu89-inline -fno-strict-aliasing -ffunction-sections -fdata-sections -pthread -pipe -DNDEBUG -DTRIMMED -O3 -msse2 -mfpmath=sse -fomit-frame-pointer
c++ 	gcc version 4.7.2 20121015 (Red Hat 4.7.2-5) (GCC) 	-Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Wtype-limits -Wempty-body -Wsign-compare -Wno-invalid-offsetof -Wcast-align -fno-exceptions -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -std=gnu++0x -pthread -pipe -DNDEBUG -DTRIMMED -O3 -msse2 -mfpmath=sse -fomit-frame-pointer
Configure arguments

--enable-official-branding --enable-application=browser --disable-crashreporter --disable-accessibility --disable-parental-controls --disable-webrtc --disable-logging --disable-necko-wifi --disable-installer --disable-updater --disable-websms-backend --disable-tests --disable-mochitests --disable-debug --disable-debug-symbols --enable-strip --enable-jemalloc '--enable-optimize=-O3 -msse2 -mfpmath=sse' --enable-chrome-format=omni --x-libraries=/usr/lib
```

**Comment by Axiomatic-** [comment]
After some hassle with GCC, setting an exact replicate of trav90's flags produces a stable Pale Moon for me, so I did some testing, and it seems that cause of my issues are these two flags: -fstack-protector-strong, and --param=ssp-buffer-size=4, after some research it turns out it is a known issue that these two flags when used in conjunction can cause issues. 

Pale Moon runs fine on GCC version 4.9.2 20150204 without these two flags. Thank you both for helping me work this out.
