### ISSUE TITLE
Get rid of the identity module

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#281]
Once upon a time, mozilla had the bright idea to launch an identity service called Mozilla Persona.
Once upon a time, this seemed like a good idea. Documents were written, methods were thought out, and some sites started adopting it.

Mozilla then implemented a Toolkit module, and DOM interface to query this, in Firefox 18.
Then, Mozilla disabled this idea from being in use on Desktop, so they could focus on B2G "without also having to deal with desktop".
Many bugs were opened to implement new parts (UI, etc.) to complete this feature.

Time passed... Nobody else adopted Persona because there was no desktop client support, nobody running an e-mail server wanted to have to also run an HTTPS server to provide ID services, and FxOS was a failure. People who had been diverted to B2G had been too busy with actually getting it to work to worry about navigator.id and friends.

Come Firefox 31 (or 34? I don't remember), the module loading was moved to nightly only. The UI bugs to implement web signin for desktop were never finished. If the toolkit module is enabled, then Persona-supporting websites will break because there is no native UI.

This whole identity API is not in use AFAICT, preffed off by default, dead code, not working when actually enabled, still taking memory on startup, and is a complete waste of CPU cycles and memory. It should be removed.

**Comment by Axiomatic-** [comment]
Started this: https://github.com/Axiomatic-/Pale-Moon/tree/Code_Cleanup

I believe I am finished, I just need to start a build, and confirm everything functions. Then double check for anything I may have missed.

**Comment by wolfbeast** [comment]
Did you also make sure to check for loading of the modules from e.g. browser.js and friends?

**Comment by Axiomatic-** [comment]
The identity module is window independent, so it used the nsBrowserGlue service, the calls were removed. The majority of the removal was simply following the paths from the commits on [mozilla/gecko-dev](https://github.com/mozilla/gecko-dev) 

I did not bother with removing/editing the B2G Make files, should I?

**Comment by wolfbeast** [comment]
B2G is slated to be yanked out anyway someday, so no need to bother with it.

I'll merge it in and close this issue. if there's problems with a Win build I'll reopen as-needed. Thanks for your work!

**Comment by wolfbeast** [comment]
Missed a few things.
Packaging bustage fixed in [633220e]
Superfluous pref removed in [22363f0]
