### ISSUE TITLE
build on linux fails (25.3.0-beta3 / master branch on github)

### ISSUE THREAD

**Issue by FlaschePommes** [MoonchildProductions/Pale-Moon#29]
Pale Moon 25.3.0. beta 3 does not compile on linux. The error is similar to issue #19, but for a different file (`MediaPluginHost.cpp` instead of `GLContextProviderGLX.cpp`):

c++ -o MediaPluginHost.o -c -I../../../dist/stl_wrappers -I../../../dist/system_wrappers -include /var/lib/jenkins/palemoon/config/gcc_hidden.h -DMOZ_GLUE_IN_PROGRAM -DMOZILLA_INTERNAL_API -D_IMPL_NS_COM -DEXPORT_XPT_API -DEXPORT_XPTC_API -D_IMPL_NS_GFX -D_IMPL_NS_WIDGET -DIMPL_XREAPI -DIMPL_NS_NET -DIMPL_THEBES  -DSTATIC_EXPORTABLE_JS_API -DNO_NSPR_10_SUPPORT  -I/var/lib/jenkins/palemoon/content/media/plugins -I. -I../../../dist/include  -I/var/lib/jenkins/palemoon/obj-i686-pc-linux-gnu/dist/include/nspr -I/var/lib/jenkins/palemoon/obj-i686-pc-linux-gnu/dist/include/nss     -I/var/lib/jenkins/palemoon/content/media/plugins/../../base/src -I/var/lib/jenkins/palemoon/content/media/plugins/../../html/content/src   -fPIC  -Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Wtype-limits -Wempty-body -Wsign-compare -Wno-invalid-offsetof -Wcast-align -fno-exceptions -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -std=gnu++0x -pthread -pipe  -DNDEBUG -DTRIMMED -O3 -msse2 -mfpmath=sse -fomit-frame-pointer   -DMOZILLA_CLIENT -include ../../../mozilla-config.h -MD -MP -MF .deps/MediaPluginHost.o.pp  /var/lib/jenkins/palemoon/content/media/plugins/MediaPluginHost.cpp
/var/lib/jenkins/palemoon/content/media/plugins/MediaPluginHost.cpp: In function 'bool mozilla::IsOmxSupported()':
/var/lib/jenkins/palemoon/content/media/plugins/MediaPluginHost.cpp:117:3: error: 'ScopedGfxFeatureReporter' was not declared in this scope
/var/lib/jenkins/palemoon/content/media/plugins/MediaPluginHost.cpp:117:28: error: expected ';' before 'reporter'
/var/lib/jenkins/palemoon/content/media/plugins/MediaPluginHost.cpp:132:3: error: 'reporter' was not declared in this scope
make[7]: *** [MediaPluginHost.o] Error 1
make[7]: Leaving directory `/var/lib/jenkins/palemoon/obj-i686-pc-linux-gnu/content/media/plugins'
make[6]: *** [plugins_libs] Error 2
make[6]: Leaving directory `/var/lib/jenkins/palemoon/obj-i686-pc-linux-gnu/content/media'
make[5]: *** [media_libs] Error 2
make[5]: Leaving directory `/var/lib/jenkins/palemoon/obj-i686-pc-linux-gnu/content'
make[4]: *** [libs_tier_platform] Error 2
make[4]: Leaving directory `/var/lib/jenkins/palemoon/obj-i686-pc-linux-gnu'
make[3]: *** [tier_platform] Error 2
make[3]: Leaving directory `/var/lib/jenkins/palemoon/obj-i686-pc-linux-gnu'
make[2]: *** [default] Error 2
make[2]: Leaving directory `/var/lib/jenkins/palemoon/obj-i686-pc-linux-gnu'
make[1]: *** [realbuild] Error 2

I applied the changes in fix d6fef27b4b0f2294572f00ed845804b353d4ddef for `GLContextProviderGLX.cpp` also to `MediaPluginHost.cpp`. This solved the problem for me (tested on Debian wheezy i386).

**Comment by wolfbeast** [comment]
Hmm, I guess it is part of a conditional that doesn't always get hit when building on Linux.

I'll do a full-tree search to see if there are any others that I missed. I thought I got all of them but it seems some slipped through the cracks with the massive commit. Thanks for reporting!

**Comment by wolfbeast** [comment]
Fixed by commit 25bca06

**Comment by FlaschePommes** [comment]
Thanks for the quick reaction. I performed a full rebuild of the project, in order to confirm the fix. The build works again for me.
