### ISSUE TITLE
issue #608589

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#290]
just got an "assertion failed"

ASSERT: Giving up waiting for the tab closing animation to finish (bug 608589)
Stack Trace: 
0:([object XULElement],[object XULElement])

Palemoon: Version: 26.0.0b2 (x64) (2015-10-13) (commit d38679b)
Ubuntu: 15.10

**Comment by wolfbeast** [comment]
This can happen when something prevents the tab from being cleaned up. As a last-ditch, this assertion is thrown -- usually this is caused by extensions. So, this is "by design"
