### ISSUE TITLE
pale moon frozen

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#291]
pale moon: 25.8.1 (x64) 
Operating system : Ubuntu 14.04 LTS 
Linux tbpl-makerspace 3.16.0-56-generic #75~14.04.1-Ubuntu SMP Wed Dec 2 11:27:25 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
http://0bin.net/paste/+C3XueLrkrSeL4oN#kAXEQay+Ng12brAzFRT6wN2qHyBd1pJCICBoOvqisMD

**Comment by wolfbeast** [comment]
Jeff. Please:

- If you make a report, don't just dump a trace. Please describe the problem, the environment the problem occurred in, and steps to reproduce, (and if applicable expected results and actual results.)
- If you have a trace, make it an attachment or non-expiring pastebin. Dumping it in the issue tracker helps no man.

Please edit your issue report to reflect these two points. I can't do anything with this as-is.

**Comment by themusicgod1** [comment]
Looking closer there's no debugging symbols in those stack traces.  If it reccurs I will recompile with those in them and relook.
