### ISSUE TITLE
js/Vector.h produces dizzying number of "field 'storage' is uninitialized when used" warnings

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/Pale-Moon#298]
```
14:07.35 Warning: -Wuninitialized in /Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/include/js/Vector.h: field 'storage' is uninitialized when used here
14:07.35 ./../../dist/include/js/Vector.h:531:34: warning: field 'storage' is uninitialized when used here [-Wuninitialized]
14:07.37   : AllocPolicy(ap), mBegin((T *)storage.addr()), mLength(0),
14:07.37                                  ^
14:07.38 /Users/pale/jenkins/workspace/palemoon/js/src/jsgc.h:705:5: note: in instantiation of member function 'js::Vector<void **, 16, js::SystemAllocPolicy>::Vector' requested here
14:07.38     GCHelperThread(JSRuntime *rt)
```

A huge number (at least hundreds, maybe thousands?) of source files produce warnings much like the above -- I'm not sure whether it's harmful or not, but it seems like fixing it once in the header file could dramatically reduce the size of the build output (and probably therefore the speed of the build, as logging to stdout is a measurable amount of time in such a large build)

This is with:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.5.0
Thread model: posix
```

**Comment by wolfbeast** [comment]
The code is from this snippet:
```` C++
/* Vector Implementation */

template <class T, size_t N, class AllocPolicy>
JS_ALWAYS_INLINE
Vector<T,N,AllocPolicy>::Vector(AllocPolicy ap)
  : AllocPolicy(ap), mBegin((T *)storage.addr()), mLength(0),
    mCapacity(sInlineCapacity)
#ifdef DEBUG
  , mReserved(sInlineCapacity), entered(false)
#endif
{}
````
This is perfectly fine, code-wise (it's implicitly initialized as null). Your compiler just doesn't seem to like it and is trying to be helpful.

**Comment by stevenschlansker** [comment]
Good to know that it is fine code-wise.  I normally wouldn't push too hard for simple warning fixes given how many are emitted, but this is a very noticeable percentage of the entire output.  Let me know if I shouldn't file issues like this.

**Comment by trav90** [comment]
PR #302 causes GCC to throw way more warnings than I can count like the following:

```
./../../dist/include/js/Vector.h:530:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
./../../dist/include/js/Vector.h:531:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wuninitialized"
 ^
./../../dist/include/js/Vector.h:543:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
```

The pragma's added by the PR should have a clang conditional to prevent GCC from trying to use them as well.

I'll likely have a patch this weekend if no one else gets to it first.

**Comment by trav90** [comment]
Ah, yes. I had forgotten that since Clang aims to be GCC compatible, it can use most GCC pragma (though not always the other way around). We should be able to change the Clang pragma to GCC and it should solve the issue on both compilers. I'm testing this now and will report back.

**Comment by trav90** [comment]
Created PR #305

**Comment by stevenschlansker** [comment]
Damn, sorry about that! :(

**Comment by trav90** [comment]
No worries! :)
