### ISSUE TITLE
huge number of "replacement function 'operator new' cannot be declared inline" warnings

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/Pale-Moon#299]
`MOZALLOC_INLINE` is applied to `operator new`, which is apparently not legal and ignored.  This causes a warning in a large percentage of source files, which is an astronomical amount of output:

```
120:01.56 Warning: -Winline-new-delete in /Users/pale/jenkins/workspace/palemoon/obj-x86_64-apple-darwin12.5.0/dist/include/mozilla/mozalloc.h: replacement function 'operator new' cannot be declared 'inline'
120:01.56 ../../dist/include/mozilla/mozalloc.h:204:21: warning: replacement function 'operator new' cannot be declared 'inline' [-Winline-new-delete]
120:01.64 MOZALLOC_EXPORT_NEW MOZALLOC_INLINE
120:01.69                     ^
120:01.84 ../../dist/include/mozilla/mozalloc.h:44:27: note: expanded from macro 'MOZALLOC_INLINE'
120:01.90 #  define MOZALLOC_INLINE MOZ_ALWAYS_INLINE_EVEN_DEBUG
120:01.96                           ^

120:02.16 ../../dist/include/mozilla/Attributes.h:42:75: note: expanded from macro 'MOZ_ALWAYS_INLINE_EVEN_DEBUG'
120:02.31 #  define MOZ_ALWAYS_INLINE_EVEN_DEBUG     __attribute__((always_inline)) MOZ_INLINE
120:02.47                                                                           ^
120:02.63 ../../dist/include/mozilla/Attributes.h:20:33: note: expanded from macro 'MOZ_INLINE'
120:02.71 #  define MOZ_INLINE            inline
120:02.77                                 ^
```

Compiler is

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.5.0
Thread model: posix
```

**Comment by Axiomatic-** [comment]
BMO Reference #: [928808](https://bugzilla.mozilla.org/show_bug.cgi?id=928808)
@stevenschlansker it is a simple fix: https://hg.mozilla.org/mozilla-central/rev/bc69628e2ad1

Feel free to make a pull request. (I will get around to it eventually if you cannot, just let me know.)

**Comment by stevenschlansker** [comment]
I'm trying to figure out how to cherry-pick the hg commit into git; right now I'm using git-remote-hg to clone the upstream repo and hopefully then cherry-pick from there (but it's taking an age to clone).
Let me know if there's a recommended, easier way to get that commit as a PR without losing all the metadata.

**Comment by Axiomatic-** [comment]
Mozilla already has a public git repository, so you can skip the SCM conversion.
```
git clone https://github.com/mozilla/gecko-dev
<assuming you have cloned Pale Moon>
cd Pale-Moon
git --git-dir=../gecko-dev/.git \
format-patch -k -1 --stdout <commit SHA> | \
git am -3 -k
```

To find the commit use the web UI provide by GitHub history button on configure.in (on gecko-dev), or use git log, and grep till you find the proper SHA.

**Comment by wolfbeast** [comment]
Of note, we probably want Bug# [1155393](https://bugzilla.mozilla.org/show_bug.cgi?id=1155393) as well to transplant this to the js subtree.
