### ISSUE TITLE
Remove dead code for extensions/widgetutils and localize FIREFOX_VERSION to application specific configure

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Pale-Moon#30]
In the Mozilla source tree an extension used to be built called widgetutils which provided some manor of mouse related actions. This code however has not functioned since 2010 and has not been referenced anywhere for at least that long.

This will also end the only dependence on FIREFOX_VERSION variable for the build system in global configure. All other mozilla based applications do not require FIREFOX_VERSION and it is not needed outside of building the desktop browser.

I purpose removing extensions/widgetutils from the codebase and moving the configure code for setting FIREFOX_VERSION ala THUNDERBIRD_VERSION to the per-application configure file.

http://mxr.mozilla.org/mozilla-esr24/search?string=FIREFOX_VERSION
https://bugzilla.mozilla.org/show_bug.cgi?id=948251

**Comment by wolfbeast** [comment]
I've applied the code removal as per the BZ bug; feel free to poke at moving the configure statements to our browser PAC yourself :)

**Comment by wolfbeast** [comment]
Any idea about progress for this one, Tobin?

**Comment by mattatobin** [comment]
Currently.. On Hold due to differences in how comm and how central do preprocessing. I suspect the highly macro-ized call causes the python preprocessor not to somehow have access to the value when it is defined on a per-application basis.. so for the time being it cannot be done safely..

Basically it is on indefinite hold. You can mark it INCOMPLETE close it for now.. it can always be reopened later..

**Comment by mattatobin** [comment]
I am fixing this in Tycho
