### ISSUE TITLE
nsAppShell.mm: parameter type `nsIDOMMozWakeLockListener` is an abstract class

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/Pale-Moon#301]
I apologize for peppering the project with build issues, if it wasn't obvious already I am trying to fix the Mac build and I think that means I am exercising some code paths that are often not built currently.  Hopefully trying to fix the Mac build is a contribution that forgives my spam :smile: 

Again using `Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)` [the build fails on `nsAppShell.mm`](https://github.com/MoonchildProductions/Pale-Moon/blob/master/widget/cocoa/nsAppShell.mm#L305):

```
863:04.76 /Users/pale/jenkins/workspace/palemoon/widget/cocoa/nsAppShell.mm:305:65: error: parameter type 'nsIDOMMozWakeLockListener' is an abstract class
863:04.76 NS_IMPL_ISUPPORTS(MacWakeLockListener, nsIDOMMozWakeLockListener)
863:04.76                                                                 ^
863:04.77 ../../dist/include/nsISupportsBase.h:55:14: note: unimplemented pure virtual method 'QueryInterface' in 'nsIDOMMozWakeLockListener'
863:04.78   NS_IMETHOD QueryInterface(REFNSIID aIID, void** aInstancePtr) = 0;
863:04.79              ^
863:04.80 ../../dist/include/nsISupportsBase.h:63:25: note: unimplemented pure virtual method 'AddRef' in 'nsIDOMMozWakeLockListener'
863:04.80   NS_IMETHOD_(nsrefcnt) AddRef(void) = 0;
863:04.81                         ^
863:04.84 ../../dist/include/nsISupportsBase.h:72:25: note: unimplemented pure virtual method 'Release' in 'nsIDOMMozWakeLockListener'
863:04.85   NS_IMETHOD_(nsrefcnt) Release(void) = 0;
863:04.85                         ^
863:04.87 ../../dist/include/nsIDOMWakeLockListener.h:31:14: note: unimplemented pure virtual method 'Callback' in 'nsIDOMMozWakeLockListener'
863:04.89   NS_IMETHOD Callback(const nsAString & aTopic, const nsAString & aState) = 0;
863:04.89              ^
863:04.90 /Users/pale/jenkins/workspace/palemoon/widget/cocoa/nsAppShell.mm:305:1: error: C++ requires a type specifier for all declarations
863:04.91 NS_IMPL_ISUPPORTS(MacWakeLockListener, nsIDOMMozWakeLockListener)
863:04.92 ^~~~~~~~~~~~~~~~~
863:04.92 /Users/pale/jenkins/workspace/palemoon/widget/cocoa/nsAppShell.mm:306:32: error: expected ';' after top level declarator
863:04.93 nsCOMPtr<nsIPowerManagerService> sPowerManagerService = nullptr;
```

I will continue to try to determine a fix, but I know neither C++ nor XPCOM so I am posting this issue early in the hopes that it's obvious to someone who knows better!

**Comment by Axiomatic-** [comment]
/cc @trav90

This issue is likely related to the screensaver changes landed there. 
See: 085e1a6, 2ad22a9, and 243577a.

Current easiest work around is reverting those changes, I suppose more research will have to be done to get the screensaver changes working.

**Comment by trav90** [comment]
Yes, the Mac screensaver changes were committed, but I was never able to reach BitVapor in order to test them. I've reverted the changes [here] (https://github.com/trav90/Pale-Moon/commit/e080431872abcc78ae59b0b21c8e9ae7a23dfe69).

@stevenschlansker , could you try building from that branch and see if it works? If so, I'll submit a pull request and once we get a working Mac build we can revisit the screensaver changes at that time.

**Comment by adisib** [comment]
Don't know if it is the full extent of the problem (though errors are usually like that, and I don't have the tools to build it myself to check), but it looks like there is a missing semi-colon on line 305 of nsAppShell.mm "NS_IMPL_ISUPPORTS(MacWakeLockListener, nsIDOMMozWakeLockListener)" and line 50 of nsAppShell.cpp "NS_IMPL_ISUPPORTS1(WinWakeLockListener, nsIDOMMozWakeLockListener)".
