### ISSUE TITLE
Upgrade SQLite to a newer version?

### ISSUE THREAD

**Issue by Axiomatic-** [MoonchildProductions/Pale-Moon#32]
Hello,

Currently [SQLite version 3.7.17](https://github.com/MoonchildProductions/Pale-Moon/blob/master/db/sqlite3/README.MOZILLA) is being used in Pale Moon. SQLite version 3.8.8.3 is said to give up to 50% more work, for the same amount of delta cycles that SQLite version 3.7.17 used. (I read this somewhere on Hacker News.) 

So I ask is there any reason why we are not using a newer SQLite version?

**Comment by wolfbeast** [comment]
A simple reason: I didn't get around to updating this from upstream yet ;)

**Comment by wolfbeast** [comment]
Upgrade done in commit b6db7f54882eb43aa1a025a36c0b349c8489dea5

**Comment by Axiomatic-** [comment]
Awesome, thank you.
