### ISSUE TITLE
icons issue

### ISSUE THREAD

**Issue by finkiki** [MoonchildProductions/Pale-Moon#322]
I had some graphical issue in v26 beta 32bit, but it remains the same in v26.0 64 bit : 
![icones](https://cloud.githubusercontent.com/assets/12123582/12608656/a7578434-c4dd-11e5-825b-fce66a4ca80f.png)

Something similar happen in several websites. For exemple in discord : 
![discord](https://cloud.githubusercontent.com/assets/12123582/12608793/6a43130a-c4de-11e5-90e6-415bc3995006.png)

Or in a blogspot : 
![tags](https://cloud.githubusercontent.com/assets/12123582/12608808/7ea38460-c4de-11e5-80e8-16c5c79cc319.png)

I'm on Windows 7.

**Comment by wolfbeast** [comment]
Please check if there are video driver updates available for your system.

Please also let us know the output of help -> troubleshooting information, the graphics section there.

**Comment by mattatobin** [comment]
This hasn't seen any action for 9 months.. I suggest WORKSFORME
