### ISSUE TITLE
inoreader rss reader

### ISSUE THREAD

**Issue by g-alen** [MoonchildProductions/Pale-Moon#323]
Before:
![inoreader-palemoon258](https://cloud.githubusercontent.com/assets/16915495/12608959/5b07b76e-c4df-11e5-87f8-ce7d4d34b97e.jpg)
After:
![inoreader-palemoon26](https://cloud.githubusercontent.com/assets/16915495/12608958/5b076b42-c4df-11e5-925d-8224e568c892.jpg)

And keyboard shortcuts doesn't works.

**Comment by wolfbeast** [comment]
Please contact inoreader - they are detecting pale moon 26 as a mobile device which is incorrect and can't be solved on our side (unless we lie about what browser we are, which is just feeding into bad habits)

**Comment by wolfbeast** [comment]
Confirmed solved on inoreader's side.
