### ISSUE TITLE
Hangouts (hangouts.google.com) The chat doesn't load

### ISSUE THREAD

**Issue by Shurikn** [MoonchildProductions/Pale-Moon#324]
![palemoon_2016-01-27_19-03-02](https://cloud.githubusercontent.com/assets/7237650/12610004/bc6dd422-c528-11e5-965d-bbe4c089ed24.jpg)

Was working with version 25.8 before the update, and still works in chrome.
There's a lot of javascript warnings in the console, but not sure what could be causing it to not load.

**Comment by SJ-Diamond** [comment]
Seems there is not much what can be done, Google seems to have done some page changes which breaks the page in Pale Moon 26.

**Comment by chaoskagami** [comment]
Incidentally, I'd really love to get this working again. Having pidgin running 24/7 is a waste of ram and annoying.

Any ideas as to the cause of this one? Google's code is so obfuscated it's nigh impossible to make sense of it.

**Comment by wolfbeast** [comment]
It seems to be a refusal by Google Auth servers (somewhere) and not a scripting or client-side issue (there are no errors in any console). So i have no idea.

**Comment by Shurikn** [comment]
This issue is completely blocking me to upgrade to 26 on my other machines.
I also sent a feedback to Google, but I don't expect them to care...

**Comment by wolfbeast** [comment]
Without any information from Google, this can't be worked around. None of the useragents I've tried work around this problem, either, so it's going to depend on something specific and unknown they arbitrarily check for that Pale Moon 26 doesn't give them. What this "something" is, only Google can tell us.

Alternatives are using a different browser for hangouts, not using hangouts but a different IM network that isn't restricting you, or using a hangouts "App".

**Comment by Shurikn** [comment]
Last version fixed this.
