### ISSUE TITLE
Add "Currently Playing Sound" icon on tabs

### ISSUE THREAD

**Issue by Domochevsky** [MoonchildProductions/Pale-Moon#327]
For sites like youtube there used to be a Currently Playing Sound icon on the tab where... well, sound was playing. 

This seems to be gone now. What information do you require to get to the bottom of this?

System: Windows 7 (64bit) HP

**Comment by wolfbeast** [comment]
We've never had this in the browser. Maybe you're thinking of an extension that added this?

**Comment by Domochevsky** [comment]
Hm.. that seems entirely possible. Maybe I'm confusing things here.
In that case: a) nevermind me and b) ...can you add it natively? >_>

**Comment by wolfbeast** [comment]
Maybe a "nice to have" enhancement. Changed the issue to reflect this.

**Comment by Lootyhoof** [comment]
This was a YouTube-specific implementation; presumably culled when Chrome and friends got the tab audio indicator natively.

[118860](https://bugzilla.mozilla.org/show_bug.cgi?id=1188860) [meta] is the Mozilla implementation, though it's got quite a few bugs linked to it, probably quite a complex implementation. It would possibly be more worthwhile to port and integrate the [Noise Control](https://addons.mozilla.org/en-us/firefox/addon/noise-control/) addon, though this only works for HTML5 media, not plugins (e.g. Flash).

**Comment by wolfbeast** [comment]
I think plugin-based sound should be controlled by the user through already-existing control mechanisms anyway. Trying to do that downwards from the browser chrome is going to be both messy and prone to serious bugs.

If there is an extension already that does this, would it even be needed to integrate it into the core?

**Comment by Lootyhoof** [comment]
The linked addon is an SDK addon that only works for Firefox 38 - 41; it would need porting to us.

**Comment by mattatobin** [comment]
If you do port/create this functionality as an extension.. Please target Toolkit (Overlay) technology.

**Comment by trav90** [comment]
The [Expose Noisy Tabs](https://addons.palemoon.org/extensions/expose-noisy-tabs/) extension provides this functionality.

**Comment by vlakoff** [comment]
Just as a personal opinion, I think this functionality should be natively implemented, so that on a fresh Pale Moon installation one doesn't have to install that handful of extensions, you know, the "tiny but crucial extensions that fill the gaps".

Even if I have Flash disabled by default, there are more and more websites that use MP4 video ads, and **autoplay** them. Aaarrrgh. Being able to quickly shut them down by clicking on the speaker icon that appear on the tab is such a relief.

**Comment by wolfbeast** [comment]
@vlakoff I'm sure it'll be revisited as a native feature on the medium to long term, especially if we're going to move to UXP that already has platform code in place for this (just needs front-end work)
