### ISSUE TITLE
Browser fails to load some webpages with error: sec_error_ocsp_future_response

### ISSUE THREAD

**Issue by fbrau** [MoonchildProductions/Pale-Moon#329]
it refuses to render https://en.wikipedia.org/wiki/Home, for example.
![captura de pantalla_2016-01-29_03-34-09](https://cloud.githubusercontent.com/assets/8375315/12668866/f88ff9c8-c652-11e5-90de-a1bb9a1f8439.png)

My system time is correct. This is the only browser that fails with that message

**Comment by wolfbeast** [comment]
Check your clock and time zone.

**Comment by fbrau** [comment]
I use time in localtime. Changing to UTC solves the case.

Why am I forced to use UTC?

**Comment by wolfbeast** [comment]
Which operating system are you on?

**Comment by fbrau** [comment]
I'm on a slackware based distro (and i haven't updated it recently)

Even though the problem solved I can't get to reproduce it again.
When I installed palemoon it failed to load duckduckgo and wikipedia pages.

I'm pretty sure the system's timezone was set because the installer of the distro forces you
to set timezone.

I tried removing profile directory, changing between localtime and UTC, I removed
timezone settings, I even set system time in the future (for real) and palemoon proceeds
without displaying the error of this issue.

**Comment by chaoskagami** [comment]
Do you set your clock manually or sync it via ntp?

One time my clock skewed forward too much and this sort of error started happened. I fixed it by ntp-client'ing.

On January 29, 2016 11:22:40 PM EST, fbrau <notifications@github.com> wrote:
>I'm on a slackware based distro (and i haven't updated it recently)
>
>Even though the problem solved I can't get to reproduce it again.
>When I installed palemoon it failed to load duckduckgo and wikipedia
>pages.
>
>I'm pretty sure the system's timezone was set because the installer of
>the distro forces you
>to set timezone.
>
>I tried removing profile directory, changing between localtime and UTC,
>I removed
>timezone settings, I even set system time in the future (for real) and
>palemoon proceeds
>without displaying the error of this issue.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/MoonchildProductions/Pale-Moon/issues/329#issuecomment-177062633

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wolfbeast** [comment]
>  I even set system time in the future (for real) and palemoon proceeds without displaying the error of this issue.

Setting *your* time in the future won't actually trigger this error unless your time in the future exceeds the OCSP response TTL, making the response expired. The problem with this error is that the response received is in the future *for you* (i.e.: your time+timezone time point is behind the issuance point of the OCSP response, making the response "in the future" from the browser's point of view which shouldn't be possible, since OCSP servers aren't clairvoyant :smile:)

**Comment by wolfbeast** [comment]
Closing this since there was no further response. Assuming solved/answered.
