### ISSUE TITLE
Extension FlashGot 1.5.6.12.1-signed doesn't work with Pale Moon 26.0.0

### ISSUE THREAD

**Issue by pgeneste** [MoonchildProductions/Pale-Moon#330]
Extension FlashGot 1.5.6.12.1-signed doesn't work with Pale Moon 26.0.0 (x64) verified fully operational with 25.8.1 (x64) built in default down loader.

**Comment by wolfbeast** [comment]
Please keep this issue tracker for Pale Moon core issues only, not for extension compatibility issues.
