### ISSUE TITLE
installing addon dialog text gets trimmed

### ISSUE THREAD

**Issue by fbrau** [MoonchildProductions/Pale-Moon#331]
In the snapshot the dialog should display download speed I suppose, right?
![captura de pantalla_2016-01-30_01-36-34](https://cloud.githubusercontent.com/assets/8375315/12693744/c013b1f2-c6f2-11e5-816c-c38b16ec04e2.png)

Before installing the spanish locale the glitch was there too

**Comment by wolfbeast** [comment]
Looks like you've greatly enlarged the font sizes. This will make the designed space for text insufficient in some components of the browser. Please use standard font sizes if you want to see all text.
