### ISSUE TITLE
Regression after dab2fee747d1853d5e081f69750869d45b7cf6b0

### ISSUE THREAD

**Issue by MihailZenkov** [MoonchildProductions/Pale-Moon#339]
Browser freeze or crash after this commit: https://github.com/MoonchildProductions/Pale-Moon/commit/dab2fee747d1853d5e081f69750869d45b7cf6b0

Problem can be reproduced on this page: http://news.tut.by/society/482943.html
Step to reproduce: open page and scroll down.

**Comment by wolfbeast** [comment]
Confirmed. Seems the problem is the strange use of repeat transparent stops (css border `transparent transparent #coo transparent`) causing an infinite loop. A small oversight in repeated inserting into a shifting/growing list.

Thanks for reporting!
