### ISSUE TITLE
Google Calender - new entries problem

### ISSUE THREAD

**Issue by crestAT** [MoonchildProductions/Pale-Moon#340]
If one creates a new entry in the Google calendar it is not possible to get the input fields for "start time" and "end time" if "whole day" gets unchecked.

It works in Firefox ...

BR

**Comment by wolfbeast** [comment]
"it works in firefox" *really* doesn't help us.
Please provide more details, steps to reproduce, if you will.

**Comment by wolfbeast** [comment]
Please see if your issue still exists in v27 beta 2.

**Comment by wolfbeast** [comment]
Lacking further info or feedback, considering this resolved by Tycho.
