### ISSUE TITLE
Netflix is not working with Pale Moon v. 26

### ISSUE THREAD

**Issue by ltcomdata** [MoonchildProductions/Pale-Moon#342]
As soon as I upgraded to Pale Moon v. 26 I was unable to play any Netflix videos.  I get the "NOT-SUPPORTED" error window: "https://forum.palemoon.org/download/file.php?id=4238&mode=view".  Will there be a forthcoming user-agent hack to get around this issue?

**Comment by trav90** [comment]
Soon-to-be-released Pale Moon 26.0.2 will have a workaround in place for Netflix.
