### ISSUE TITLE
bnc.ca can't login into member zone

### ISSUE THREAD

**Issue by Shurikn** [MoonchildProductions/Pale-Moon#343]
The login page doesn't load.
Seems to be some javascrip problems, when loading the page I get this error in the console:
`[17:21:41.181] SyntaxError: missing variable name @ https://bvi.bnc.ca/auth/Login?GAREASONCODE=-1&GARESOURCEID=SbipBncA&GAURI=https://bvi.bnc.ca/bnc/page%3FaliasDispatcher%3Dstartup&Reason=-1&APPID=SbipBncA&URI=https://bvi.bnc.ca/bnc/page%3FaliasDispatcher%3Dstartup:1307`
At line 1307 is the following simple variable initialization:
`var let=0; `

To reach this page, from this page: [https://www.bnc.ca/fr/particuliers.html](https://www.bnc.ca/fr/particuliers.html) click on "ouvrir une session"

**Comment by wolfbeast** [comment]
`let` is a reserved keyword in ECMAv5 and later, which is why it doesn't work. Pale Moon 26.0.2 will address this issue by having an older scripting version as default (like previous).
