### ISSUE TITLE
Devtools 'Disable JavaScript' doesn't work when devtools are not docked

### ISSUE THREAD

**Issue by jez9999** [MoonchildProductions/Pale-Moon#345]
When dev tools are docked, one can go into options and select "Disable JavaScript" and JavaScript will indeed be disabled.  However when dev tools are undocked, this stops working.  When the option is checked, the page does not reload, and JavaScript is still enabled.

**Comment by wolfbeast** [comment]
Can you see if you can find a related BMO bug for this? devtools is very much a Mozilla child.

**Comment by jez9999** [comment]
Wasn't it Pale Moon that moved the "disable JavaScript" option into devtools?

**Comment by wolfbeast** [comment]
Nope, that was Mozilla.

**Comment by wolfbeast** [comment]
Is this still an issue in v27 with --enable-devtools?

**Comment by janekptacijarabaci** [comment]
IMHO: I can't reproduce this problem in v27...

**Comment by wolfbeast** [comment]
Both Mozilla commits are incorporated in Tycho's platform, so considering this solved and verified.
