### ISSUE TITLE
instructions for debian incomplete?

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#348]
steps:

git clone https://github.com/MoonchildProductions/Pale-Moon --recursive

devscripts:
  Installed: 2.15.10
  Candidate: 2.15.10

Tribler/Main/Build/update_version_from_git.py
makerspace@veritas:~/tribler/tribler$ echo $?
0

makerspace@veritas:~/tribler/tribler$ debuild -i -us -uc -b
 dpkg-buildpackage -rfakeroot -D -us -uc -i -b
...
copying Tribler/Main/Utility/version_check.py -> build/lib.linux-i686-2.7/Tribler/Main/Utility
error: package directory 'Tribler/Main/Utility/Feeds' does not exist
dh_auto_build: python setup.py build --force returned exit code 1
debian/rules:18: recipe for target 'build' failed
make: *** [build] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc -i -b failed

What am I missing to build tribler on debian unstable?

makerspace@veritas:~$ apt-cache policy fakeroot
fakeroot:
  Installed: 1.20.2-1
  Candidate: 1.20.2-1

**Comment by squarefractal** [comment]
@themusicgod1: Is this a Tribler problem that you are having, or a Pale Moon problem?
