### ISSUE TITLE
FTBFS: failure memory model cannot be stronger than success memory model for ‘__atomic_compare_exchange’

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#35]
mach build failed with : 

 0:04.57 In file included from /usr/include/c++/4.9/atomic:41:0,
 0:04.57                  from ../../dist/include/mozilla/Atomics.h:176,
 0:04.57                  from /home/themusicgod1/palemoon/Pale-Moon/mfbt/tests/TestAtomics.cpp:6:
 0:04.57 /usr/include/c++/4.9/bits/atomic_base.h: In static member function ‘static bool mozilla::detail::IntrinsicMemoryOps<T, Order>::compareExchange(typename mozilla::detail::IntrinsicMemoryOps<T, Order>::Base::ValueType&, T, T) [with T = unsigned int; mozilla::MemoryOrdering Order = (mozilla::MemoryOrdering)1u; typename mozilla::detail::IntrinsicMemoryOps<T, Order>::Base::ValueType = std::atomic<unsigned int>]’:
 0:04.57 /usr/include/c++/4.9/bits/atomic_base.h:581:70: error: failure memory model cannot be stronger than success memory model for ‘__atomic_compare_exchange’
 
On ubuntu 15.04, gcc Ubuntu 4.9.2-10ubuntu12 
(it's been failing to build this way for at least a few months).

**Comment by Axiomatic-** [comment]
Hello,

I do not build Pale Moon with tests enabled, and I am not sure about others. So it is possible that some of the tests are outdated an fail to work with the latest GCC. Easiest solution is disabling tests.

In your .mozconfig add:
```
ac_add_options --disable-tests
ac_add_options --disable-mochitests
```

You can get .mozconfig examples from the Pale Moon binary, just start it up, and navigate to 'about:buildconfig'

**Comment by themusicgod1** [comment]
That worked.  Pull request created based on your suggestion as baseline platform neutral .mozconfig seems to be necessary

**Comment by Axiomatic-** [comment]
Not sure if a neutral .mozconfig is necessary, rather it maybe a negative since people build from Pale Moon's master git branch with special .mozconfig settings (Arch Linux's AUR builds do this). I believe that you can in configure.in set builds to not do tests by default. See: https://github.com/MoonchildProductions/Pale-Moon/blob/master/configure.in#L4029

@wolfbeast probably can speak more about this.

**Comment by wolfbeast** [comment]
Seems like a bit of bitrot for using gcc 4.9.* for the test code.
What needs to be done is fix the test to be gcc 4.9 compliant (while not breaking backwards compatibility).
Workarounds in the source could be: excluding the test as a whole and/or change the default setting in configure to have tests at "false" until the test is fixed.

**Comment by WorMzy** [comment]
INcidentally

**Comment by trav90** [comment]
For what it's worth, release versions of Pale Moon are built with tests & mochitests disabled in mozconfig (and using gcc 4.7.2).

**Comment by trav90** [comment]
I think this issue can be closed, since it was never reproduced (and the tests are eventually going to be removed anyway).

**Comment by wolfbeast** [comment]
Since our GCC minimum is now 4.6 -- we should probably have a look at this to be able to build tests on later GCC versions.

**Comment by trav90** [comment]
This is solved by Tycho. Tycho currently builds successfully with tests and mochitests enabled when using GCC 4.7 (the new min required), 4.9, and 5.x.
