### ISSUE TITLE
Pale Moon v26.xx - Unable to log in at Indiegala.com

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#352]
To log in @ https://www.indiegala.com/ you first have to solve a picture CAPTCHA..
After solving it and clicking on "Login", the login window disappears (like it should), but nothing happens as the login has failed.

In the Console, I see the following errors with orange exclamation marks:

Pale Moon v25.8.1 (Login WORKS):
* SyntaxError: 08 is not a legal ECMA-262 octal constant
* Use of attributes' specified attribute is deprecated. It always returns true.

Pale Moon v26.0.0 / v26.0.2 (Login FAILS):
* SyntaxError: 08 is not a legal ECMA-262 octal constant
* Use of attributes' specified attribute is deprecated. It always returns true.
* Use of getAttributeNode() is deprecated. Use getAttribute() instead.

Pale Moon v26.0.3 (Login FAILS):
* SyntaxError: 08 is not a legal ECMA-262 octal constant
* Use of getUserData() or setUserData() is deprecated. Use WeakMap or element.dataset instead.

--

I initially posted the problem in Pale Moon's forum here:
http://forum.palemoon.org/viewtopic.php?f=29&t=10911
..but later continued in this thread:
http://forum.palemoon.org/viewtopic.php?f=3&t=10902

**Comment by wolfbeast** [comment]
The only difference between .0.2 and .0.3 is allowing cookies with spaces, which were also allowed in 25.8.1

Clear cookies? Maybe it got confused with having SOME cookies but not others.

**Comment by THEtomaso** [comment]
No.
I've configured PM to clear all cookies automatically upon exit, so that's not the problem here.
Also, I only do clean installs, so there's no chance of any leftovers from previous versions.

**Comment by wolfbeast** [comment]
As said the only difference between the two is cookie gating. There's no reason for it to work on .0.2 and not in .0.3 unless it's a cookie problem.
UNLESS, if the cookie failing in .0.2 made it work. (we also no longer accept cookie VALUES with invalid characters according (mostly) to RFC). Maybe you can check what cookies it stores in 25.8.1

**Comment by THEtomaso** [comment]
Eh..
Look at my first post.
The login didn't work in .0.2!
It only works with pre-v26 builds.

..but I'll see if I can find some info on the cookie, using v25.8.1.

**Comment by wolfbeast** [comment]
sorry. wasn't paying attention, i guess, focusing on the diff between output.
maybe it needs a ua override.

**Comment by wolfbeast** [comment]
ua sniffing is the culprit. I signed up for an account, tried logging in. the warnings you see are requestnotifier (internal) and the recaptcha. Login fails. Setting a ua override to "Firefox/38.9" and nothing else has the login succeed.

Not a browser issue at all. Please contact the site owners to have a look at it.

**Comment by wolfbeast** [comment]
wait... it didn't pop up the login again but I'm still not logged in.

**Comment by wolfbeast** [comment]
OK. The "octal" error is because of `Date.UTC()` for a countdown timer. has nothing to do with the login.
There are no other errors of consequence from the domain itself.
It's impossible to troubleshoot for a client because /ajaxlogin is a protected script. You'll have to ask them for help.

**Comment by THEtomaso** [comment]
OK, I've reported it to them.
Perhaps they will surprise us and actually fix it! :)
I've never contacted their support desk before, but from my experience with similar sites, they usually don't care about these sort of things, as long as their errors are overlooked by the major browsers.
I'll keep my fingers crossed.

**Comment by wolfbeast** [comment]
You never know ;) And if you don't try, the answer is always going to be "no" by default anyway.

**Comment by wolfbeast** [comment]
Caused by a non-RFC-compliant cookie

Cookie name:
`atgcocc42`
Cookie value (partial):
`"···kFRQ04\075|1455···"`
Contains a \ character which is not allowed. They base64-encode most other cookies properly but not that one.

**Comment by THEtomaso** [comment]
So, judging from the empty checkbox for backslash characters in your post here:
https://github.com/MoonchildProductions/Pale-Moon/issues/357/
..cookies that contains this character will still be refused by PM v26.1.0?

**Comment by wolfbeast** [comment]
No, an empty checkbox means its *not* RFC compliant. That issue is about making our behavior spec compliant. 26.1.0 will allow a backslash and a comma in cookies.

**Comment by THEtomaso** [comment]
OK.
Thanks for claryfying. :)
One more question; will v26.1.0 be the next stable release, or will there be more .0.x releases?

**Comment by wolfbeast** [comment]
I don't plan any more .0.x releases. I've made some good progress to warrant a major update.

**Comment by THEtomaso** [comment]
I can confirm that the login works again @ Indiegala, using Pale Moon v26.1.0 :)

**Comment by wolfbeast** [comment]
Thanks for verifying!
