### ISSUE TITLE
Unexpected scroll to top when using web version of Twitter

### ISSUE THREAD

**Issue by alemonmk** [MoonchildProductions/Pale-Moon#353]
This is a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1092626) which is reproducible in Pale Moon 26.0.3 and earlier.
Since it is annoying for daily Twitter users (like me), searching issues with query `is:issue twitter in:title,body` returns nothing related, and Devs at Mozilla have it fixed, I think I should bring it here.

**Comment by wolfbeast** [comment]
Thanks for reporting. Commit d8de9206dd7cca82e22c5cb9cabd4e2857751a2b should address your issue.
