### ISSUE TITLE
Pale Moon 26.0.3 causes rendering and navigation glitches on penny-arcade.com/comic

### ISSUE THREAD

**Issue by thegrandpoobah** [MoonchildProductions/Pale-Moon#355]
https://www.penny-arcade.com/comic

This page should have a bunch of navigation buttons around the comic for going back and forth in the comic history. The buttons are there and they seem to function alright, they are just using the wrong sprite in the sprite image. For example, the back image is the RSS image. The first image is the twitter icon and so on.

The Facebook link at the bottom also seems to be completely messed up.

I've highlighted both of these on the screenshot below.

<img width="844" alt="penny-arcade" src="https://cloud.githubusercontent.com/assets/278023/12876608/20f8b6b8-cdd1-11e5-9e86-aca7b3fb2b1f.png">

**Comment by trav90** [comment]
Site renders correctly for me:
![untitled](https://cloud.githubusercontent.com/assets/10595410/12877828/4ee6658a-cddf-11e5-8c76-916686ccb021.png)

**Comment by thegrandpoobah** [comment]
Interesting... My Pale Moon installation is pretty bog standard. I only have the Ghostery and uBlock Origin add-ons installed and I tried disabling them and restarting Pale Moon and had the same layout problems. I also tried it in Pale Moon's safe mode with the same problem.

I am running Pale Moon on Windows 10 x64 with Intel Broadwell graphics on a 4K display with 150% scaling. I tried setting scaling to 100% with the same rendering.

about:support https://gist.github.com/thegrandpoobah/5daaa7a7c7f9e432f94a

Really liking Pale Moon btw!

**Comment by wolfbeast** [comment]
![fireshot pro screen capture 135 - penny arcade - comic - decrepitude - www_penny-arcade_com_comic](https://cloud.githubusercontent.com/assets/3359132/12887416/5d92216a-ce74-11e5-881a-3ccade910dc8.png)

I'm unable to reproduce the issue as well.
Of note, if something has blocked/mangled a file in transit then it may be cached in an incorrect state. Ghostery seems to cause those issues sometimes. Try completely removing the ghostery extension, then clearing your cache, and see if the problem persists?

**Comment by thegrandpoobah** [comment]
That was it. I tried to clear all my history and did a refresh of the page and everything renders correctly now. Thanks for all your help and sorry for the false alarm!
