### ISSUE TITLE
Pale Moon 26.0 rejects cookies containing commas (e.g. JSON)

### ISSUE THREAD

**Issue by quietust** [MoonchildProductions/Pale-Moon#356]
Ever since I updated to Pale Moon 26.0, one of the internal websites I use at work stopped accepting login requests, and a bit of Google searching and source diving revealed it to be due to the addition of RFC 6265 compliance enforcement - the login cookie (which was being rejected) is a compact JSON blob, and since it contains a comma (as well as embedded quotes), it is rejected.

A quick search through my cookie database turned up a small handful of other sites whose cookie values contained commas: AccuWeather, Oracle, AT&T, Best Buy, VMware, and Twitter. Of these, 2 were JSON, while the others were comma-separated lists or unsanitized strings.

Technically, this is not a bug in Pale Moon, but in those particular websites; however, many users are unlikely to accept that as an excuse, given that other popular browsers are less strict (such as Firefox itself, mentioned in 4d3258e07362bbd10c60e4a76c3065b8519ad6dd).

Even if this is not fixed, it may be worth adding an FAQ entry so that users can bug webmasters and get them to fix their sites, though for high-profile sites such as the ones I listed above, this may be an exercise in futility.

**Comment by wolfbeast** [comment]
Unfortunately the RFC is very clear about what is allowable in a cookie value:
````
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
````
If people want to store arbitrary data in a cookie, the RFC even gives a hint as to how to handle this:
````
   To maximize compatibility with user agents, servers that wish to
   store arbitrary data in a cookie-value SHOULD encode that data, for
   example, using Base64 [RFC4648].
````

Now, given the term SHOULD, it would be OK (but with a critical note that servers SHOULD NOT do this) to store characters outside of these values even if it's not RFC compliant, so I could possibly make exceptions here for increased web compatibility.

**Comment by wolfbeast** [comment]
FAQ entry created: https://forum.palemoon.org/viewtopic.php?f=24&t=11121

**Comment by quietust** [comment]
It might be useful to have some sort of indicator/notification when an invalid cookie is rejected so that users can understand _why_ a particular website isn't working (and know that they need to complain to the site's webmaster rather than here).

An option to "allow anyways" (akin to popup blocking) would be really nice, though the potential technical challenges behind it (e.g. having to block in the middle of an HTTP redirect) make it unlikely at best.

**Comment by wolfbeast** [comment]
No, pulling this all the way to the front-end and designing a UI for it is most definitely not something that would be feasible. I'm just adjusting the gate to allow more through, because, honestly, cookies have an already sordid history and people are likely just not going to care on either side of the fence: users just want it to work, websites are too Google-focused to care, and Chrome is the one that did the half-job to begin with causing this very real issue even on high-profile sites that will have the ivory-tower attitude that they (1) don't support us and (2) say it is our problem -- despite the IETF documentation out there to the contrary.

I can only hope that this bump in the road causes a few webmasters to pay attention.

**Comment by wolfbeast** [comment]
Please confirm if 26.1.0 solves this issue.

**Comment by wolfbeast** [comment]
Assuming this is solved, considering lack of complaints to the contrary.

**Comment by quietust** [comment]
Sorry for the late reply - it is indeed solved for now.

**Comment by wolfbeast** [comment]
Thanks for verifying.
