### ISSUE TITLE
Re-add volume control to embedded HTML5 audio elements

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#358]
The rather broken volume control on HTML5 audio/video elements was removed, but is still desired by users.

We should re-implement this - but then in a non-broken way ;)

Ref implementation (FF28): https://hg.mozilla.org/mozilla-central/rev/9915d93be7b6

**Comment by wolfbeast** [comment]
Actually, this is only an issue on embedded audio. video is fine, standalone audio and video is fine as well because it uses the video player for both.

The horizontal implementation is still desirable, though. It's what a number of themes expect as well.

**Comment by wolfbeast** [comment]
@Lootyhoof You'll have to adjust your themes for this. Let me know if you need binaries with this issue patch included to test the necessary changes?

**Comment by Ryan659** [comment]
Work has started on including these, though a binary to test would be very much appreciated, yes. :)

**Comment by Lootyhoof** [comment]
Work has started, though a binary would be much appreciated, yes. :)

PS: disregard the previous comment if anyone saw it, logged into the wrong account (I blame being mobile currently personally...).

**Comment by wolfbeast** [comment]
Check your e-mail for FTP access details :)
