### ISSUE TITLE
Get a working Promises implementation

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#360]
This must get top priority. With disabling it in 26.1 due to non-functionality we are left without promises.

A few choices:
- Fix the injector, *or*
- Implement DOM promises following Mozilla's code, even if it's out of place in DOM (we already have the base work but it's not spec compliant), *or*
- Find a way to self-host Promises in the JS engine itself

**Comment by wolfbeast** [comment]
I'm working on a DOM implementation, since self-hosting in SpiderMonkey is currently not working (we need a way to hook it into the event loop, somehow)

**Comment by wolfbeast** [comment]
DOM Promises work is almost done as regards the basic implementation according to the current ES6 spec, but there is a problem with GC/CC yanking promises out from under us leading to crashes. Branch DOM-promises-work has the working DOM implementation.

After a week of research into GC and CC and trying to make these crashes stop, I'm at the end of my repertoire of options, have unassigned myself, and I'm now offering a bounty to whomever can make this a stable, non-crashing (and preferably non-leaking!) implementation. Bounty will be paid through PayPal.

**Comment by wolfbeast** [comment]
Cancelling the bounty on this. A stopgap injector extension is in place which helps for some sites, and Tycho will fix this in the DOM.

**Comment by hkmaly** [comment]
Which version will this be in? Because google AMP still doesn't work correctly in 26.3.0.

**Comment by trav90** [comment]
As mentioned by wolfbeast above, it will be fixed by Tycho (what will be Pale Moon 27.0).
