### ISSUE TITLE
Allow Horizontal scrolling with shift+scroll

### ISSUE THREAD

**Issue by Shurikn** [MoonchildProductions/Pale-Moon#363]
There's actually an [open bug](https://bugzilla.mozilla.org/show_bug.cgi?id=143038) (open for >13 years) on firefox for that, but since we're not following them anymore, I though it could be a good idea to create one here too.

The default values for mousewheel.with_shift_action (2) goes back and forth through page history... which is just annoying.
1 change it to normal scroll
0 stops the scrolling completely

Adding a new value to horizontal scroll could be pretty useful.

**Comment by wolfbeast** [comment]
There's no real reason why this bug was never addressed by Mozilla apart from being arbitrarily stale. It has a patch, with an r+ at that...

Well, another more than a decade old bug solved by us. ;)
