### ISSUE TITLE
Something on Thingiverse.com causes segfault in pale moon (GCC 4.9 related / Fixed Upstream) 

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#37]
Consistently crashes within a few seconds of clicking around randomly in thingiverse.  Usually allows main page to load, but something that that site is doing is causing a pretty reliable segfault.

stack trace:

  0x0000000000000000 in ?? ()
  0x00007ffff41070dd in TSymbolTableLevel::~TSymbolTableLevel (this=0x7fffb75cc010, __in_chrg=<optimized out>) at /home/themusicgod1/palemoon/Pale-Moon/gfx/angle/src/compiler/SymbolTable.cpp:174
  0x00007ffff40edbbc in TSymbolTable::pop (this=0x7fffb759b6d0) at /home/themusicgod1/palemoon/Pale-Moon/gfx/angle/src/compiler/SymbolTable.h:271
  0x00007ffff40eefb3 in TCompiler::compile (this=0x7fffb759b600, shaderStrings=shaderStrings@entry=0x7fffffffb220, numStrings=numStrings@entry=1, compileOptions=<optimized out>, compileOptions@entry=6220) at /home/themusicgod1/palemoon/Pale-Moon/gfx/angle/src/compiler/Compiler.cpp:207
  0x00007ffff410f05c in ShCompile (handle=<optimized out>, shaderStrings=0x7fffffffb220, numStrings=1, compileOptions=6220) at /home/themusicgod1/palemoon/Pale-Moon/gfx/angle/src/compiler/ShaderLang.cpp:190
  0x00007ffff346a46f in mozilla::WebGLContext::CompileShader (this=0x7fffbd75bc00, shader=0x7fffb750f480) at /home/themusicgod1/palemoon/Pale-Moon/content/canvas/src/WebGLContextGL.cpp:4466
  0x00007ffff3dc3ee3 in mozilla::dom::WebGLRenderingContextBinding::compileShader (cx=0x7fffe2dd0b00, obj=..., self=0x7fffbd75bc00, args=...) at /home/themusicgod1/palemoon/Pale-Moon/obj-x86_64-unknown-linux-gnu/dom/bindings/WebGLRenderingContextBinding.cpp:5171
  0x00007ffff3dc2ef5 in mozilla::dom::WebGLRenderingContextBinding::genericMethod (cx=0x7fffe2dd0b00, argc=<optimized out>, vp=0x7fffe2df6870) at /home/themusicgod1/palemoon/Pale-Moon/obj-x86_64-unknown-linux-gnu/dom/bindings/WebGLRenderingContextBinding.cpp:10681
  0x00007ffff41d670f in CallJSNative (args=..., native=<optimized out>, cx=<optimized out>) at /home/themusicgod1/palemoon/Pale-Moon/js/src/jscntxtinlines.h:321
  js::Invoke (cx=0x7fffe2dd0b00, args=..., construct=(unknown: 3178667032)) at /home/themusicgod1/palemoon/Pale-Moon/js/src/vm/Interpreter.cpp:481
 0x00007ffff41dcf7a in Interpret (cx=0x7fffffffbc20, state=...) at /home/themusicgod1/palemoon/Pale-Moon/js/src/vm/Interpreter.cpp:2303
 0x00007ffff41e3239 in RunScript (state=..., cx=0x7fffe2dd0b00) at /home/themusicgod1/palemoon/Pale-Moon/js/src/vm/Interpreter.cpp:438
 js::ExecuteKernel (cx=0x7fffe2dd0b00, script=..., scopeChainArg=..., thisv=..., type=<optimized out>, evalInFrame=..., result=0x0) at /home/themusicgod1/palemoon/Pale-Moon/js/src/vm/Interpreter.cpp:627
 0x00007ffff41e4163 in js::Execute (cx=0x7fffe2dd0b00, script=..., scopeChainArg=..., rval=0x0) at /home/themusicgod1/palemoon/Pale-Moon/js/src/vm/Interpreter.cpp:664
 0x00007ffff425f69d in JS::Evaluate (cx=0x7fffe2dd0b00, obj=obj@entry=..., options=..., chars=<optimized out>, length=length@entry=678, rval=rval@entry=0x0) at /home/themusicgod1/palemoon/Pale-Moon/js/src/jsapi.cpp:5475
 0x00007ffff366e3c6 in nsJSContext::EvaluateString (this=0x7fffcad4b5c0, aScript=..., aScopeObject=..., aOptions=..., aCoerceToString=<optimized out>, aRetValue=0x0) at /home/themusicgod1/palemoon/Pale-Moon/dom/base/nsJSEnvironment.cpp:1289
 0x00007ffff3438bc0 in nsScriptLoader::EvaluateScript (this=0x7fffc41080f0, aRequest=0x7fffbd2bb3d0, aScript=...) at /home/themusicgod1/palemoon/Pale-Moon/content/base/src/nsScriptLoader.cpp:855
 0x00007ffff343979d in nsScriptLoader::ProcessRequest (this=this@entry=0x7fffc41080f0, aRequest=0x7fffbd2bb3d0) at /home/themusicgod1/palemoon/Pale-Moon/content/base/src/nsScriptLoader.cpp:743
 0x00007ffff343ba1c in nsScriptLoader::ProcessScriptElement (this=this@entry=0x7fffc41080f0, aElement=aElement@entry=0x7fffbbef0450) at /home/themusicgod1/palemoon/Pale-Moon/content/base/src/nsScriptLoader.cpp:691
 0x00007ffff3438654 in nsScriptElement::MaybeProcessScript (this=0x7fffbbef0450) at /home/themusicgod1/palemoon/Pale-Moon/content/base/src/nsScriptElement.cpp:139
 0x00007ffff35c2135 in nsIScriptElement::AttemptToExecute (this=0x7fffbbef0450) at ../../../../dist/include/nsIScriptElement.h:220
 0x00007ffff377139e in nsHtml5TreeOpExecutor::RunScript (this=this@entry=0x7fffc2e02900, aScriptElement=<optimized out>) at /home/themusicgod1/palemoon/Pale-Moon/parser/html/nsHtml5TreeOpExecutor.cpp:797
 0x00007ffff377209b in nsHtml5TreeOpExecutor::RunFlushLoop (this=0x7fffc2e02900) at /home/themusicgod1/palemoon/Pale-Moon/parser/html/nsHtml5TreeOpExecutor.cpp:597
 0x00007ffff37721ee in nsHtml5ExecutorReflusher::Run (this=<optimized out>) at /home/themusicgod1/palemoon/Pale-Moon/parser/html/nsHtml5TreeOpExecutor.cpp:61
 0x00007ffff3e65909 in nsThread::ProcessNextEvent (this=0x7fffe9a4cba0, mayWait=<optimized out>, result=0x7fffffffc7a7) at /home/themusicgod1/palemoon/Pale-Moon/xpcom/threads/nsThread.cpp:626
 0x00007ffff3e35a06 in NS_ProcessNextEvent (thread=<optimized out>, mayWait=mayWait@entry=false) at /home/themusicgod1/palemoon/Pale-Moon/obj-x86_64-unknown-linux-gnu/xpcom/build/nsThreadUtils.cpp:238
 0x00007ffff3b244fd in mozilla::ipc::MessagePump::Run (this=0x7fffe9a81b80, aDelegate=0x7fffe9a62240) at /home/themusicgod1/palemoon/Pale-Moon/ipc/glue/MessagePump.cpp:82
 0x00007ffff3e8c31b in RunHandler (this=0x7fffe9a62240) at /home/themusicgod1/palemoon/Pale-Moon/ipc/chromium/src/base/message_loop.cc:212
 MessageLoop::Run (this=0x7fffe9a62240) at /home/themusicgod1/palemoon/Pale-Moon/ipc/chromium/src/base/message_loop.cc:186
 0x00007ffff3ab4e04 in nsBaseAppShell::Run (this=0x7fffb75cd730) at /home/themusicgod1/palemoon/Pale-Moon/widget/xpwidgets/nsBaseAppShell.cpp:163
 0x00007ffff398b7ad in nsAppStartup::Run (this=0x7fffdf90d650) at /home/themusicgod1/palemoon/Pale-Moon/toolkit/components/startup/nsAppStartup.cpp:269
 0x00007ffff308b8ac in XREMain::XRE_mainRun (this=this@entry=0x7fffffffca10) at /home/themusicgod1/palemoon/Pale-Moon/toolkit/xre/nsAppRunner.cpp:3427
 0x00007ffff308ba8d in XREMain::XRE_main (this=this@entry=0x7fffffffca10, argc=argc@entry=1, argv=argv@entry=0x7fffffffdf18, aAppData=aAppData@entry=0x7fffffffcc18) at /home/themusicgod1/palemoon/Pale-Moon/toolkit/xre/nsAppRunner.cpp:3495
 0x00007ffff308bca1 in XRE_main (argc=1, argv=0x7fffffffdf18, aAppData=0x7fffffffcc18, aFlags=<optimized out>) at /home/themusicgod1/palemoon/Pale-Moon/toolkit/xre/nsAppRunner.cpp:3683
 0x0000000000403ba4 in do_main (argc=argc@entry=1, argv=argv@entry=0x7fffffffdf18, xreDirectory=0x7ffff6c31780) at /home/themusicgod1/palemoon/Pale-Moon/browser/app/nsBrowserApp.cpp:272
 0x0000000000403396 in main (argc=1, argv=0x7fffffffdf18) at /home/themusicgod1/palemoon/Pale-Moon/browser/app/nsBrowserApp.cpp:632

Pale Moon: Version: 25.4.0a1 (x64)
Ubuntu: 15.04
gcc 4:4.9.2-2ubuntu2
Linux: Linux Hedy 3.19.0-10-generic #10-Ubuntu SMP Mon Mar 23 16:25:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Looks like this is the upstream bug (It's fixed in FF31): 

https://bugzilla.mozilla.org/show_bug.cgi?id=1025576 

*edit* removed stack trace depth numbers which were being interpreted as links to other tickets >_>

**Comment by wolfbeast** [comment]
Nice catch!

*GCC 4.9 doesn't put pointers to virtual destructors in pure virtual classes anymore.* :angry: 
Not the first problem GCC later than 4.7 causes for Pale Moon... :-1: 

The fix is easy and straightforward though. Just adding an extra check as in the upstream bug should get rid of the crash. Since you obviously have a build env. with GCC 4.9, could you perform the edit in ANGLE as posted in the BZ bugpatch and build, and see if that solves your issue?

**Comment by themusicgod1** [comment]
Their patch wasn't 1:1 compatible (the README file wasn't close enough for their patch to work directly), and I'm apparently teh suck at git, but sure seems like the change fixed I made in my fork based on their patch fixed it.

**Comment by wolfbeast** [comment]
Thanks for verifying. Pull request was a bit of a mess but the net result looks clean. Merging.
