### ISSUE TITLE
Including "--" class prefix in selector list prevents other selectors from matching

### ISSUE THREAD

**Issue by TuggyNE** [MoonchildProductions/Pale-Moon#374]
Recently I ran into an apparent rendering bug with Pale Moon 26.1.0; certain [Stack Exchange](http://stackexchange.com/) sites' review pages' disabled buttons were not showing up with the appropriate style, and after tracing it back, I found that Firefox applied the style, but Pale Moon did not. A test case follows, sufficient to reproduce the problem.

```html
<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
  input[type=button].--disabled, input[type=button][disabled] {
    color: red;
  }
  </style>
</head>
<body>
  <input type="button" value="Testing" disabled="disabled"></input>
</body>
</html>
```

Removing the first selector in the list is enough to allow the other one to match the element appropriately in Pale Moon. In fact, even removing a single hyphen is enough.

CSS allows class names (and other identifiers) to contain dashes freely, and failing to parse the entire compound selector because part of it contains an invalid identifier (as this is apparently being treated) seems like an extra bug. The `--*` syntax has a superficial similarity to CSS variables, but is syntactically distinct; CSS variables cannot be used in selectors ([or anywhere outside property values](https://www.w3.org/TR/css-variables/#using-variables)). It also has a superficial similarity to a blank vendor prefix, although that should also not be applicable.

**Comment by wolfbeast** [comment]
I gather the scanner code simply didn't take into account that people would ever be using -- at the start of a class name or otherwise in selectors (even if it would be allowed) and focusing on the use as vars when -- is encountered.

**Comment by wolfbeast** [comment]
Code hint relayed from IRC without context:

> [20160216.1401-07] <hatm> Replace line 1137 nsCSSScanner.cpp
> [20160216.1401-15] <hatm> if (IsIdentStart(c2)) {
> [20160216.1401-19] <hatm> with
> [20160216.1401-23] <hatm> (IsIdentStart(c2) || (c2 == '-' && c3 != '>')) {

Ref to the relevant BMO bug appreciated.

**Comment by Axiomatic-** [comment]
@wolfbeast BMO bug is https://bugzilla.mozilla.org/show_bug.cgi?id=985838 (at least that is what git is showing me.)

**Comment by wolfbeast** [comment]
Thanks for the info.
A 200 KB patch o.O? Oy.

I'll have to set some time aside for that, I guess.

**Comment by wolfbeast** [comment]
So yeah, the spec changed out from under us here. yay for "living standards"

**Comment by Lootyhoof** [comment]
The linked bug is actually to do with CSS variables, which we never had as it was introduced in Australis. The change it wants to work with was first introduced in [773296](https://bugzilla.mozilla.org/show_bug.cgi?id=773296), but be warned - it is BIG (28 parts!).

That said, it'd make my job a bit easier at least... ;)

**Comment by wolfbeast** [comment]
No, actually, the change that solves this particular issue is restricting '--' *to* variables. We already have a precursor to them (as `var-` instead of `--`). I don't particularly see a reason to jump into the thick of making CSS "yet another C-alike language" because it's nonsense.

**Comment by wolfbeast** [comment]
Also, there's been recent discussions on the www-style mailing list that will likely see CSS variables changed yet again in the spec this year... so...

**Comment by wolfbeast** [comment]
I'll be implementing a simple workaround to get this issue fixed; CSS variables themselves will have to be looked at later.
