### ISSUE TITLE
Pale Moon sometimes is not able to retrieve the search engine icon after adding it

### ISSUE THREAD

**Issue by JDarthenay** [MoonchildProductions/Pale-Moon#377]
Sometimes, when you add a search engine in your search engine list, Pale Moon fails to add the icon and adds the search engine to the list with no icon associated. I know this is not a major issue and I have found a workaround (adding directly the base64 encryption of the icon in the search.json file) but this is so ugly...
Before adding search engine:
![searh-engines-menu-00](https://cloud.githubusercontent.com/assets/17165152/13259420/8de1142c-da57-11e5-84bd-f9613b8cad99.png)
After adding search engine:
![searh-engines-menu-01](https://cloud.githubusercontent.com/assets/17165152/13259419/8de0163a-da57-11e5-9bf0-d8d9809d0fed.png)

I made a few tests and it seems this is due to the mere presence of some icon resolution (48x48, 64x64, 128x128) with color depth 32-bits, even if they are not necessary at all since Pale Moon need only the 16x16 resolution icon. Neither The same resolutions with 16 bits color depth nor other resolutions such as 16x16, 32x32 seem to give any problem.

Firefox and Seamonkey seems to have the same problem, so the code handling this is probably still the same.

Edit:
1/ just realized I was actually not able to generate a 256x256 icon, so I haven't done this test.
2/ I precize all my testing was done with BMP icons. (PNG icons also exist).
3/ I also realized some test I did was not with 8bits but with lower depth, I guess I have to do those tests again...

**Comment by wolfbeast** [comment]
Since this is universal to all Mozilla code, it may be a good idea to file a bug for this at bugzilla.mozilla.org -- that way the person who originally wrote this code can (potentially) have a look at it.

**Comment by JDarthenay** [comment]
It seems it is already there: [](https://bugzilla.mozilla.org/show_bug.cgi?id=928585)
They don't seem to have done my testing. I am going to do again my tests with Firefox and post there the results.

**Comment by wolfbeast** [comment]
Yup, particularly large icons (more than 10,000 bytes) are refused because of the internal conversion to a data uri that is expensive to use. Since there is no need for larger icons for search engine entries this limit was instated.
I can adjust this limit taking more modern computers into account, to, say, 25 or 30kB, but it won't be a full solution for all sites out there if they use very large icon sets in their favicons and try to just use that. The people who offer search engines need to use optimized search icons.

**Comment by JDarthenay** [comment]
I agree with your two points: 10kb is already enough (actually, it's even too much I believe), and search engines icons should not have so much useless data in them.
But would it be so much difficult to try to detect the file type, and if it is an icon to keep only the useful resolution inside?

By the way I have done a small Node.js script to extract icons from my search.json, and I noticed what is supposed to be a "image/x-icon" file can actually be a PNG or a GIF file...

**Comment by wolfbeast** [comment]
Processing icons like that on-the-fly would severely impact browser startup time if you have more than a few search engines in your list. They can be several formats, as you've seen, and one would need to task the browser with decoding, modifying a multi-image format into a single image, then re-encoding, and storing that data. That's already outside of the normal scope of what a web browser is supposed to do so we don't have code for that at the ready.
