### ISSUE TITLE
Print pages to Pdf extension fails after updating to PM 26

### ISSUE THREAD

**Issue by tumpio** [MoonchildProductions/Pale-Moon#378]
This was reported on the forum here:
https://forum.palemoon.org/viewtopic.php?f=16&t=11304

I found out that the add-on checks for platform version number when deciding between some chromeworker compatibility:
```
if (RRprintPages2Pdf.versionChecker.compare(RRprintPages2Pdf.xulAppInfo.platformVersion, "8.0") >= 0) {
    this.pdfWorker = new ChromeWorker(convPath);
}
else {
    var workerFactory = Components.classes["@mozilla.org/threads/workerfactory;1"].createInstance(Components.interfaces.nsIWorkerFactory);
    this.pdfWorker = workerFactory.newChromeWorker(convPath);
}
```

where xulAppInfo is 

    Components.classes["@mozilla.org/xre/app-info;1"]
                 						.getService(Components.interfaces.nsIXULAppInfo);

In Pale Moon 25.7.1 xulAppInfo.platformVersion returns _"25.7.1"_
while in Pale Moon 26.1.0 it returns _"2.0.1"_

And now on PM 26, the extension goes to the else block that expects platform compatibility of Gecko 8.0 or lower and fails.

AMO link to the addon:
https://addons.mozilla.org/En-us/firefox/addon/print-pages-to-pdf/

**Comment by tumpio** [comment]
In commit https://github.com/MoonchildProductions/Pale-Moon/commit/1c32255718e88b075d319efb7e7758782e5e729e  I can see that the milestone version was changed. 

So in PM 26 the _xulAppInfo.platformVersion_ is now the Goanna's version number, right? 

Can there be some compatibility layer for old Firefox extensions that expect Gecko version number when checking the platformVersion?

**Comment by wolfbeast** [comment]
> Can there be some compatibility layer for old Firefox extensions that expect Gecko version number when checking the platformVersion, so that these extensions would continue to work after the Goanna change?

We've considered it but the tradeoff for added confusion and complexity in code for a small number of extensions was too great. This platformVersion issue is a direct result of people using that to determine product version (which is a mistake).

So the answer is no. This will have to be addressed in the extension, either by using product version, or by dropping the check altogether (Firefox 8 is ancient, might not want to support that any longer...) or alternatively, if the extension dev refuses to acknowledge our presence, by forking the extension into a Pale Moon specific extension (license permitting).

There are alternatives available, as well, e.g. Fireshot, or using a "PDF printer" that is system-wide as a virtual printer.
