### ISSUE TITLE
Replicated reported issue: Pale Moon does not fire onLocationChange notifications during navigation

### ISSUE THREAD

**Issue by TPS** [MoonchildProductions/Pale-Moon#381]
From https://github.com/gorhill/uBlock/issues/1444#issuecomment-192685487, @gorhill reports:
> For unknown reasons, Pale Moon _[26.1.1 & 25.8.1]_ does not fire`onLocationChange`notifications during navigation, it fires the notification only for when a new tab is created, then goes silent.

>Can also reproduce with Firefox 31.
Can not reproduce with Firefox 38+.

Complete details @ linked issue, including replication steps.

**Comment by gorhill** [comment]
There is no issue, this can be closed.

**Comment by TPS** [comment]
@gorhill Thanks, & nevermind, then.

**Comment by msva** [comment]
Although, as @gorhill said,
> apparently older Firefox versions used the same context for all frame scripts. The `onLocationChange` not firing was a symptom of this.

(and palemoon too).

And since "not-firing" isn't a bug, yes, I'm not sure that shared context usage isn't a security issue ;)
