### ISSUE TITLE
XSS filter notification is displayed on the active tab of each opened browser window

### ISSUE THREAD

**Issue by soulweaver91** [MoonchildProductions/Pale-Moon#387]
Whenever the built-in XSS filter blocks resources from loading, the notification bar that informs the user about this is pushed not only onto the tab relevant to it, but also the active tab on each of the other browser windows open at that time. Or at least PM does that for me, and clearly it should not :)

[Example demonstration](https://soulweaver.fi/temp/FFsplit-160310-210303.mp4)

**Comment by wolfbeast** [comment]
We should probably make the notification tab-modal.

**Comment by wolfbeast** [comment]
Putting this on hold because we won't have this XSS filter until it's working on Tycho.
