### ISSUE TITLE
Site doesn't work with Pale Moon

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#395]
http://www.rbnett.no/livestudio/2016/03/07/Molde-Troms%C3%B8-rbnett-12249319.ece

Also posted here:
http://forum.palemoon.org/viewtopic.php?f=3&t=10902&start=80#p80959
..with a couple of screenshots two posts down.
The K-Meleon screenshots shows how the site is supposed to load.

**Comment by trav90** [comment]
Looks like it could be a scripting error. From the error console:

`(Timestamp: 03/14/2016 08:36:09 PM
Error: TypeError: g is undefined
Source File: http://www.rbnett.no/resources/min-js/widgets/xstream.js
Line: 1)`

`Timestamp: 03/14/2016 08:36:12 PM
Error: uncaught exception: [object StopIteration]`

`Timestamp: 03/14/2016 08:36:14 PM
Error: uncaught exception: [object StopIteration]`

The source file mentioned in the first error is this:
`define([],function(){var c;c=function(f,g){if(g.videoid==="undefined"){console.log("Undefined videoid");f.html("Beklager, teknisk feil. Ukjent videoklipp.")}else{a(f,g)}};function b(g,h){h=e(g,h);if(h.player==="new"){g.parent().height(h.height);try{}catch(i){g.html("<span>Beklager, teknisk feil. Pr??v igjen senere.</span>");console.error("Loading new xstream videoplayer failed")}}else{if(h.player==="snd"){try{var f={vendor:h.vendor?h.vendor:"",height:h.height,width:h.width,index:h.index?h.index:"",autoplay:h.autoplay==="true"?true:false,statistics:h.stats?h.stats:"",skin:h.skin?h.skin:"",related:h.related?h.related:true,node:g,settings:{na:h.vpflags==="nocom"?true:false,vp:{vphost:h.vphost?h.vphost:"",vptags:h.vptags?h.vptags:"",vpcategory:h.vpcategory?h.vpcategory:""}}};require([h.script],function(){if(typeof window.SVP!=="undefined"){if(h.loadonclick&&f.autoplay===false){f.autoplay=true;f.node.context.addEventListener("click",function(){initSVPplayer()})}else{initSVPplayer()}}else{g.html("<span>Beklager, teknisk feil. Pr??v igjen senere.</span>");console.error("SVP videoplayer api not loaded.")}});initSVPplayer=function(){var j=window.SVP.Player.load(h.videoid,f)}}catch(i){g.html("<span>Beklager, teknisk feil. Pr??v igjen senere.</span>");console.error("Loading SVP videoplayer failed")}}else{require(["lib/loadscript"],function(k){try{k(h.script+"&width="+h.width+"&height="+h.height)}catch(j){g.html("<span>Beklager, teknisk feil. Pr??v igjen senere.</span>");console.error("Loading old xstream videoplayer failed")}})}}}function e(f,g){if(g.mode==="carousel"){f.style="";g.width=f.parent().width();g.height=Math.floor(g.width/16*9)}else{if(g.mode==="mobile"||g.player==="new"){f.style="";g.width=f.parent().parent().width();g.height=Math.floor(g.width/16*9)}}return g}function a(g,i){if(i.ipblock){var h=new XMLHttpRequest(),f,j=function(k){if(k.country!=="undefined"){if(k.country==="NO"){b(g,i)}else{console.warn("Ip is blocked");g.html("<span>Beklager, dette videoklippet er ikke tilgjengelig utenfor Norge. Hvis du likevel befinner deg i Norge kan det v??re at du benytter proxy eller tjenester som g??r via andre land.</span>")}}else{console.warn("Ipcheck failed - check service response.");b(g,i)}};h.open("GET","http://mm.aftenposten.no/geo/",true);h.send();h.onreadystatechange=function(){try{if(h.readyState===4&&h.status===200){f=JSON.parse(h.responseText);j(f)}}catch(k){console.error("Ipcheck failed - check service.")}}}else{b(g,i)}}function d(g,h){var f=document.createElement("script");f.type="text/javascript";f.async=true;f.src=h.script;f.setAttribute("data-xs-id",h.videoid);f.setAttribute("data-xs-target",g.id);f.setAttribute("data-xs-version",h.newspapergroupversion);f.setAttribute("data-xs-locale",h.locale?h.locale:"no_NO");f.setAttribute("data-xs-width","100%");f.setAttribute("data-xs-height","100%");f.setAttribute("data-xs-autoplay",h.autoplay?h.autoplay:0);f.setAttribute("data-xs-vp-api-url",h.vpapiurl);f.setAttribute("data-xs-cue-points",h.cuepoints?h.cuepoints:"15,30");f.setAttribute("data-xs-vp-domain",h.vpdomain);f.setAttribute("data-xs-vptags",h.vptags);f.setAttribute("data-xs-vp-shares",h.vpshares);f.setAttribute("data-xs-vp-flags",h.vpflags);f.setAttribute("data-xs-vpcontentform",h.vpcontentform?h.vpcontentform:"short_form");f.setAttribute("data-xs-vp-translation",h.vptranslation?h.vptranslation:"ad:Annonce,second:sekund,seconds:sekunder,postrollText:Annoncen slutter om,prerollText:Din video starter om");(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(f);return f}return{load:c}});`

**Comment by THEtomaso** [comment]
Pale Moon v25.8.1 can't load the page properly either, so it's not a Goanna thing.

**Comment by THEtomaso** [comment]
It doesn't work with PM v26.2.0 either.

**Comment by wolfbeast** [comment]
Marking this on hold because it's not possible to reverse-engineer minified JS.

**Comment by gorhill** [comment]
I can reproduce the `[object StopIteration]` issue from the console, try:

    var ss = new Set(); var iter = ss.values(); iter.next();

Adding one single element to the Set doesn't cause the error:

    var ss = new Set([ 'allo' ]); var iter = ss.values(); iter.next();

But again, iterating over the last element does cause the error:

    var ss = new Set([ 'allo' ]); var iter = ss.values(); iter.next(); iter.next();

The spec<sup>[1]</sup> says that calling next when no more elements are available should return `{ done: true; }`.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#iterator

**Comment by wolfbeast** [comment]
Short of rewriting generators and iterators, this won't be possible in our current tree. This will be solved with the rebase that supports ES6-compliant generators and iterators (including a proper symbol for `@@iterator`.

**Comment by THEtomaso** [comment]
It works with v27.0.0.a1 :)
