### ISSUE TITLE
Anomalies when interacting with Facebook text fields in Pale Moon Version: 26.1.1 (x86) on Linux

### ISSUE THREAD

**Issue by kevjonesin** [MoonchildProductions/Pale-Moon#398]
Strange cursor behavior in Facebook text fields (using "www.facebook", "m.facebook" seems ok). 'Jams' and jumps at times when using the arrow keys. I've noticed spell-check only underlining part of a word when a jam/break-point falls within. Affects multiple distros.
More in Pale Moon IRC log here: http://pastebin.com/ajA2U0Vy

**Comment by wolfbeast** [comment]
It's a know issue with the "draft.js" Facebook editor. We've recently worked with them to pinpoint the cause (after 2 years of blackbox inability) and they are making some changes to their scripting, hopefully that will land soon.

See also: https://github.com/facebook/draft-js/issues/49

**Comment by stevenschlansker** [comment]
Thank you for being so persistent on the draft-js side!

**Comment by kevjonesin** [comment]
Thanks for elaborating!

**Comment by wolfbeast** [comment]
This was solved with the change in key handling in Pale Moon 26.3 and later.
