### ISSUE TITLE
Build on recently OS X failed

### ISSUE THREAD

**Issue by CNAmira** [MoonchildProductions/Pale-Moon#407]
There's the part of build log.
[build.txt](https://github.com/MoonchildProductions/Pale-Moon/files/184408/build.txt)
And there are also thousands of warning shows, maybe it is incompatible with Clang now?

**Comment by Axiomatic-** [comment]
It looks like you are building of a tagged release, I believe the OS X fixes landed after that, so try building from the trunk. Probably would not hurt to read issue #16 (Just encase you encounter Clang errors, since some stuff is discussed there.).

**Comment by stevenschlansker** [comment]
@CNAmira I am currently maintaining a series of patches here that fix the build for me:

https://github.com/MoonchildProductions/Pale-Moon/compare/master...stevenschlansker:macosx

Hopefully they will get integrated back into master soon to fix the build.

**Comment by CNAmira** [comment]
@stevenschlansker Great job!

**Comment by wolfbeast** [comment]
@stevenschlansker Please feel free to create a pull request when you think the patches are ready for integration into trunk?

**Comment by stevenschlansker** [comment]
Yup, that's my intention.  The remaining patches are too hacky or cause problems for other OS builds to be accepted as-is, hence the integration branch.

**Comment by wolfbeast** [comment]
Considering we have a working build now, closing this.
