### ISSUE TITLE
Various W3C Ruby Tests Failing with Pale Moon

### ISSUE THREAD

**Issue by TPS** [MoonchildProductions/Pale-Moon#409]
Since @sakai135 [will no longer be maintaining](https://github.com/sakai135/htmlruby-firefox/blob/master/README.md) https://github.com/sakai135/htmlruby-firefox, but PM includes it in the code base, I am replicating https://github.com/sakai135/htmlruby-firefox/issues/2 (& updating for current links) here, in hopes that ruby support can be improved:

These W3C tests from https://www.w3.org/International/tests/repo/results/css-ruby fail:
 - [ ] [ruby-align: start, long base](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-align-start-001.html)
 - [ ] [ruby-align: start, long annotation](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-align-start-002.html)
 - [ ] [ruby-align: center, long base](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-align-center-001.html)
 - [ ] [ruby-align: center, long annotation](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-align-center-002.html)
 - [ ] [ruby-align: space-between, long base](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-align-space-between-001.html)
 - [ ] [ruby-align: space-between, long annotation](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-align-space-between-002.html)
 - [ ] [ruby-align: space-between, multi-word Latin annotation](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-align-space-between-004.html)
 - [ ] [ruby-align: space-between, multi-word Latin annotation (zh)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-align-space-between-005.html)
 - [ ] [ruby-align: space-around, multi-word Latin annotation (zh)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-align-space-around-005.html)
 - [ ] [ruby-merge: separate](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-merge-separate-001.html)
 - [ ] [ruby-merge: collapse](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-merge-collapse-001.html)
 - [ ] [ruby-merge: collapse, line break](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-merge-collapse-002.html)
 - [ ] [ruby-merge: auto](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-merge-auto-001.html)
 - [ ] [ruby-merge: auto, line break](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-merge-auto-002.html)
 - [ ] [ruby auto-hide](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=prefix/ruby-autohide-001.html)

---
 - [ ] [vertical text support 1](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=defaults/vertical-support-001.html)
 - [ ] [vertical text support 2](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=defaults/vertical-support-prop-001.html)
 - [ ] [ruby-position: over (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=rubypos/ruby-position-over-101.html)
 - [ ] [ruby-position: under (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=rubypos/ruby-position-under-101.html)
 - [ ] [ruby-position: inter-character (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=rubypos/ruby-position-intercharacter-101.html)
 - [ ] [ruby-position: inter-character, tones (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=rubypos/ruby-position-intercharacter-102.html)
 - [ ] [ruby-position: inter-character, neutral tones (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=rubypos/ruby-position-intercharacter-103.html)
 - [ ] [ruby-align: start, long base (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-start-101.html)
 - [ ] [ruby-align: start, long annotation (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-start-102.html)
 - [ ] [ruby-align: center, long base (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-center-101.html)
 - [ ] [ruby-align: center, long annotation (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-center-102.html)
 - [ ] [ruby-align: space-between, long base (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-between-101.html)
 - [ ] [ruby-align: space-between, long annotation (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-between-102.html)
 - [ ] [ruby-align: space-between, long base, Latin rt (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-between-103.html)
 - [ ] [ruby-align: space-between, multi-word Latin annotation (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-between-104.html)
 - [ ] [ruby-align: space-around, multi-word Latin annotation (zh, vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-between-105.html)
 - [ ] [ruby-align: space-around, long base (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-around-101.html)
 - [ ] [ruby-align: space-around, long annotation (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-around-102.html)
 - [ ] [ruby-align: space-around, long base, Latin rt (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-around-103.html)
 - [ ] [ruby-align: space-around, multi-word Latin annotation (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-around-104.html)
 - [ ] [ruby-align: space-around, multi-word Latin annotation (zh, vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-around-105.html)
 - [ ] [ruby-merge: separate (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=collapsed-ruby/ruby-merge-separate-101.html)
 - [ ] [ruby-merge: collapse (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=collapsed-ruby/ruby-merge-collapse-101.html)
 - [ ] [ruby-merge: collapse, line break (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=collapsed-ruby/ruby-merge-collapse-101.html)
 - [ ] [ruby-merge: auto (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=collapsed-ruby/ruby-merge-auto-101.html)
 - [ ] [ruby-merge: auto, line break (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=collapsed-ruby/ruby-merge-auto-102.html)
 - [ ] [ruby auto-hide (vertical)](https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-model/ruby-autohide-101.html)

The other tests _seem_ to pass fine.

**Comment by TPS** [comment]
[According to](http://piro.sakura.ne.jp/xul/_rubysupport.html.en) @piroor, his https://github.com/piroor/rubysupport does pretty well on the W3C (as well as others') test cases.  Maybe consider switching backends or some version of hybrid implementation?

**Comment by wolfbeast** [comment]
The implementation of ruby annotations in Pale Moon has never been intended to cover all cases in the W3C spec. This was a practical and most-used feature implementation only that satisfies the use of ruby annotations for the people who have asked for it.

Any replacement should be able to be integrated as a "system extension" in Pale Moon the same way Sakai's extension has been integrated.

**Also**: Please understand that our implementation is ruby _annotations_ (with annotation _tags_), not CSS3 ruby _styling_. Those two are different beasts.

**Comment by chaoskagami** [comment]
No, his last commit was December 2015 in his repo. That doesn't look all that abandoned.

The date in the README is left over from long, long ago methinks.

**Comment by TPS** [comment]
@wolfbeast @chaoskagami The problem I see with https://github.com/piroor/rubysupport is that it's much less of a drop-in implementation than https://github.com/sakai135/htmlruby-firefox, as just changing `MaxVersion` in the latest Ff-released XPI doesn't make @piroor's implementation functional on current PM, but, when it _did_ work, I do remember it being more robust. However, the [commit history](https://github.com/piroor/rubysupport/commits/master) & [project history](https://raw.githubusercontent.com/piroor/rubysupport/master/history.en.md) shows he's been updating it continually (@ least 2× yearly) on Github since 2007.

**Comment by piroor** [comment]
I think that my implementation is completely outdated. All browser vendors ignored old W3C spec (except IE - because old W3C Ruby seems based on IE's spec) and transferred to new spec on HTML5. W3C's Ruby is abandoned by most Web people...

**Comment by wolfbeast** [comment]
Thanks for chiming in, @piroor 

I'm going to close this issue since there's apparently no clear spec at the W3C that is adhered to, and we already _have_ an implementation that people seem to be content with and that works (and is impactless for people who don't enable it). There's no pressing request from the real world to touch this at this time.

**Comment by TPS** [comment]
@piroor Is the HTML5 spec that is regularly used the 1 @ W3C's https://www.w3.org/International/tests/repo/results/ruby-html?  Or is that, again, ignored?  What would you consider to be a good `ruby`-in-the-wild test-suite?  (The previous link was CSS-based, & as you & @wolfbeast mentioned, is deprecated, though I hadn't noticed that when I posted all of the above.  My apologies! :bow:)
