### ISSUE TITLE
Abandoned add-ons donations?

### ISSUE THREAD

**Issue by TPS** [MoonchildProductions/Pale-Moon#411]
I'm looking for info on whether & how to contribute abandoned Firefox extensions as potential pseudo-static versions that many of us may have been keeping minorly-modified XPIs around because they've evaporated from Ff Addons site, but still are very useful & don't have better replacements. The closest link I find on PM Addons is http://dev.addons.palemoon.org/, which is not yet active.

The 2 major 1s I'm interested in are [JSView](https://github.com/MoonchildProductions/Pale-Moon/files/195790/jsview-2.0.5-fx.sm.xpi.zip) (which is a dead-simple menu which directly links to page JavaScript & stylesheet source files) & [SortExceptions](https://github.com/MoonchildProductions/Pale-Moon/files/195806/SortExceptions-0.9-fx.xpi.zip) (which optionally sorts any of the internal exception lists — cookies, popups, offline data — right-to-left, which is amazing for grouping domains).  Each of these are GPL≥2 (as contained in the XPIs) & work perfectly in current PM.

N.B.:  I've included the XPIs directly in the links above, but GitHub requires them to be .zip extensions.  Just remove the .zip.

**Comment by wolfbeast** [comment]
I've sent you an invite to the add-ons team. We can go from there.

**Comment by TPS** [comment]
Ok, thanks!

**Comment by TPS** [comment]
@wolfbeast @mattatobin I need a little guidance:  I've created repositories https://github.com/TPS/JSView & https://github.com/TPS/SortExceptions (also, relinked above);  what's my next step?

**Comment by wolfbeast** [comment]
@mattatobin maybe you can help guide TPS through this organizational challenge? I'm a bit swamped with PM-Android and FossaMail's sec releases.

**Comment by TPS** [comment]
@wolfbeast Just FYI, @mattatobin has blocked me outright, which makes issues like this/https://github.com/Pale-Moon-Addons-Team/phoebus/issues/13 very hard to get any guidance or support.

**Comment by wolfbeast** [comment]
I talked to him and he apparently blocked you for just blindly adding him to all your repos without a word otherwise. It's best if you sort these things out directly in the add-ons realm of things instead of this closed question.
