### ISSUE TITLE
[SECURITY] Older browser framework lead to open attack. Switch to Firefox.

### ISSUE THREAD

**Issue by ksylpfkf** [MoonchildProductions/Pale-Moon#414]
http://threatpost.com/firefox-add-on-flaw-leaves-apple-and-windows-computers-open-to-attack/117183/

Palemoon beware...

**Comment by wolfbeast** [comment]
When you have an actual security issue to report instead of just fear mongering BS, you're welcome to open an actual issue on the matter.
