### ISSUE TITLE
Release files on GitHub, or allow www.palemoon.org for Tor.

### ISSUE THREAD

**Issue by mishavila** [MoonchildProductions/Pale-Moon#419]
Related to https://github.com/MoonchildProductions/Pale-Moon/issues/413

I just want to let you know that I can't access to www.palemoon.org anymore.
I read forum.palemoon.org's post via proxy, and I know you use Cloudflare for spam blocking.

If so, you may continue using CF on forums.palemoon.org, but WHY DON'T YOU ALLOW www.palemoon.org for Tor users?
It's not a forum, no way to post a comment or register, right?

Also, I disagree on beast response on #413.
You will notice if you're using tor like me; Foss DO block tor. Other official links are almost same result.

---
One more step
Please complete the security check to access fosshub.com
---

Please consider provide a binary on this Github.

**Comment by wolfbeast** [comment]
"one more step" verification for Tor users does not equal being blocked.
In addition, we have plenty of mirrors listed that you can use.
If you want to complain about this policy, you should complain to CloudFlare.

**Comment by hook54321a** [comment]
You could also just use The Wayback Machine or Archive.is if you really don't want to do the verification.
