### ISSUE TITLE
templates are inaccessible in documents served with an XHTML mime type

### ISSUE THREAD

**Issue by anthonyryan1** [MoonchildProductions/Pale-Moon#420]
PaleMoon is unable to find elements within template tags in documents served with an XHTML mime type (`Content-Type: application/xhtml+xml`).

I have put together a minimal test case, available here: https://whatbox.ca/bugs/palemoon-xhtml

https://bugzilla.mozilla.org/show_bug.cgi?id=1011831 *may* be related.

**Comment by wolfbeast** [comment]
Looks like the right BMO bug, yes.

**Comment by mattatobin** [comment]
Since that bug landed in gecko/32 it /SHOULD/ be solved by Tycho
