### ISSUE TITLE
HTML5 media: set default volume

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#440]
It would be good to allow the user to set a default value for volume in HTML5 media.

This might be a more valid target for Tycho (given that it appears to be in a heavily refactored area), though I'll make the issue here just in case. Feel free to make me move it if it's more appropriate elsewhere.

For reference: the BMO below patches in `/dom/html/HTMLMediaElement.cpp`. PM equivalent appears to be `/content/html/content/src/HTMLMediaElement.cpp`.

BMO: [1274622](https://bugzilla.mozilla.org/show_bug.cgi?id=1274622)

**Comment by wolfbeast** [comment]
Most of the stuff from /content was moved over to /dom - doesn't necessarily mean the content was refactored ;)
