### ISSUE TITLE
FINN.no - Messaging system doesn't work

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#442]
Pale Moon completely fails to load the messaging system @ finn.no, which is the biggest Norwegian marketplace site.
I launched the console and found this error, which looks related:

> Error in parsing value for 'display'.  Declaration dropped. @ h**p://m.finn.no/finnboks/conversations/Yv8owRQSmOE2hT8TwVCpYJLt4RmAhrK_KQOcyCuUd6IN8nuv9pXkBqK259jC79RdMzJEN629uGvS5eZEzY5VEFO8JNmDR7nw2gJtVKw1ojw.html:74

(Tested with Pale Moon, x64, v26.2.2 and v25.8.1)

**Comment by wolfbeast** [comment]
Sorry, no, the type of error message mentioned is a CSS error - that won't have anything to do with failing to load anything.

**Comment by wolfbeast** [comment]
Can you check if the Tycho alpha fixes this?

**Comment by THEtomaso** [comment]
Unfortunately, it doesn't.

btw; I'd really wish you'd provide these test build as portables..
That way we could use the semicolon removal trick, and we could run them separately, without interferring with our installed stable build.

**Comment by THEtomaso** [comment]
..but there's a lot of other copatibility issues that HAS been fixed in the new alpha!

I've reported it here:
http://forum.palemoon.org/viewtopic.php?f=3&t=11501#p88797
http://forum.palemoon.org/viewtopic.php?f=3&t=11826#p88794
http://forum.palemoon.org/viewtopic.php?f=5&t=12428&start=20#p88800
http://forum.palemoon.org/viewtopic.php?f=29&t=11986#p88798
http://forum.palemoon.org/viewtopic.php?f=29&t=12504#p88795
http://forum.palemoon.org/viewtopic.php?f=29&t=12264#p88796
https://github.com/MoonchildProductions/Pale-Moon/issues/395#issuecomment-233959595

Great work! :)

**Comment by THEtomaso** [comment]
You can mark this issue as "Solved" now!
Wow, v27 really seems to take care of every compatibility issue that I've encountered with Pale Moon! :D
