### ISSUE TITLE
If site's domain uses Punycode,PM can't load the page.

### ISSUE THREAD

**Issue by quroe** [MoonchildProductions/Pale-Moon#443]
### Describe the issue
If site's domain uses Punycode,PM adds "/" to domain's suffix.
PM can't load the page.
When "network.IDN_show_punycode" is true,this issue doesn't occur.
Pale Moon 26.2.1 can load normally.

### One or more specific URLs where the issue occurs
http://xn--zck3adi4kpbxc7d.biz/
http://xn--eck7ao2dc0c4k1993bco4a.com/
http://xn--0ck4aw2hy751arkfgnx.jp/

### Steps for anyone to reproduce the issue
・Start Pale Moon.
・Open new tab.
・Paste "http://xn--zck3adi4kpbxc7d.biz/" in adress bar.
・Pale Moon displays error "The page isn't redirecting properly".

### Your settings
Windows7 x64
Pale Moon 26.2.2 x86

**Comment by wolfbeast** [comment]
It seems to be a server-side redirect loop that gets triggered by having a double forward slash in the URL. I think a forward slash gets added during the conversion, but I don't have time right now to dive into the relevant code.

**Comment by wolfbeast** [comment]
relevant code like in convertToDisplayIDN (idn-service)

**Comment by wolfbeast** [comment]
With the mention that this was caused in 26.2.2 specifically, I've pinpointed the change at the root of this problem. I'll investigate further.
