### ISSUE TITLE
Update Win8/Win10 dark window frame property dynamically

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#447]
Currently, our WCAG contrast calculation is put in the browser initialization function. As such, this property isn't updated unless the browser is completely restarted.

If people use dynamic accent colors, e.g. by using the combination of a desktop background slideshow and 'automatically pick a color", text may become unreadable because it doesn't update in the browser to take the new accent color into account.

We need to move this function somewhere else; preferably something that is called somewhat regularly in normal browsing operation (but not too often). Does anyone have a good idea which function to use for this?

**Comment by chaoskagami** [comment]
Would on page load/reload be a good place? It's something that will always be hit as long as the user is browsing (unlike new tab) and not often enough to cause a polling overhead.

That said, you could also set up PM to receive a registry change notification on the relevant keys so you don't have to poll: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724892%28v=vs.85%29.aspx

**Comment by wolfbeast** [comment]
The problem we have here is that any C++ method will need an interface construction for it to be accessible from JS, so although a nice idea to have it poll-less, it'd only be useful for something similar to having a -moz-* CSS variable (which would be nice to have, but not directly related to this issue and much more complex than what I want to do right now with this).

I actually think that page load might be too often, still, unless it's a user-initiated load only. I was actually thinking about finding where the browser handles window focus/blur and putting it in there (should already be present to manage changes for the UI, but needs some searching to find exactly where)

**Comment by wolfbeast** [comment]
With our work on Windows 10's accent color changes, this can now be solved. It's hooked up to actually having system settings change, meaning it will respond immediately to color changes.
I'm not sure if this can be transplanted to Windows 8 yet. See #1222

**Comment by wolfbeast** [comment]
Doesn't look like this is possible on Windows 8 this way, and none of the Windows 8 applications (even system ones) respond dynamically, so let's not bother with jumping through more hoops here.
