### ISSUE TITLE
(Some?) Google fonts look weird since upgrade to 26.3.0

### ISSUE THREAD

**Issue by hkmaly** [MoonchildProductions/Pale-Moon#448]
Hello,

I upgraded from 26.2.0 to 26.3.0 and noticed that the fonts on one game I'm playing look weird. In Firefox, it looks same (or at least almost same) as in 26.2.0 and in Chrome, when I remove style they use to override it just for webkit, it's closer to Firefox and 26.2.0 than 26.3.0, so I would assume the previous rendering was more correct.

Closer look show that the weird look is partly caused by text shadow, but nevertheless, if I disable the text shadow with Firebug the font is still rendered differently - much thinner.

The font is https://fonts.googleapis.com/css?family=Fredoka+One and the issue can be reproduced by following file, to not make advertising to that game :).

(I would attach it but it's not allowed)

```
<html>
<head>
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Fredoka+One">
<style>
body {
    background-color: #444444;
    padding: 20px;
}
p {
    color: #FDF517;
    font-family: "Fredoka One",Arial,sans-serif;
    font-size: 16px;
    letter-spacing: 1px;
    line-height: 16px;
    margin: 0 0 10px;
    padding: 0 22px 0 6px;
}
p.w {
    text-shadow: -1px -1px 0 #FA7800, 1px -1px 0 #FA7800, 1px 1px 0 #FA7800, -1px 1px 0 #FA7800, 0 2px 0 #FA7800, 0 0 2px #333333;
}
</style>
</head>
<body>
<p>Without text-shadow: 35</p>
<p class="w">With text-shadow: 35</p>
</body>
</html>
```

Attached correct and incorrect rendering (specifically, firefox and palemoon 26.3.0).
![correctrendering](https://cloud.githubusercontent.com/assets/4201080/16359420/b39afe7e-3b34-11e6-983e-2348e015a018.png)
![incorrectrendering](https://cloud.githubusercontent.com/assets/4201080/16359421/b39ea984-3b34-11e6-8561-2b85799e5d5e.png)

**Comment by hkmaly** [comment]
... It's not just that game. Other google fonts don't look correctly either ...

**Comment by wolfbeast** [comment]
Google Fonts uses useragent sniffing when they shouldn't, and end up sending stylesheets with single font definitions depending on what UA they sniff (as opposed to what the W3C indicates people should do) and end up sending us WOFF2 fonts with no fallback or alternatives.

This has been worked around in 26.3.1, but is an open issue that Google should address -- see also https://github.com/google/fonts/issues/277

**Comment by hkmaly** [comment]
You forgot to mention
>  and a better workaround would be:
> add a string pref general.useragent.override.fonts.googleapis.com
> with value Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.9) Gecko/20100101 Goanna/2.0 Firefox/31.9 PaleMoon/26.0

- I can confirm it works.
