### ISSUE TITLE
Documentation related question(s).

### ISSUE THREAD

**Issue by Axiomatic-** [MoonchildProductions/Pale-Moon#45]
@wolfbeast posted, "Needs a dev doc note, if you are compiling the browser yourself on Linux 3.*, you should not compile with jemalloc and use Linux's malloc() implementation."

We have no documentation of our own, at least none correlated with this repository, so I decided to, help out and copy, and paste some building instructions (only ones I can verify, so just one) from the Mozilla documentation. (Which is hopefully okay.)

See here: https://github.com/MoonchildProductions/Pale-Moon/wiki

Currently I have little to no idea on how things should be structured, should every odd Linux distro get their own page, or should there be just some huge monolithic Linux page?

Currently I am thinking about doing it the idea of:
- Distro 01
- Distro 02
  - Distro based on 02
- Distro 03

Where distro based on 02 will be inside of the documentation for distro 02. Mainly because the differences between ArchBang, Manjaro from Arch Linux is minimal same as in the sense of how Ubuntu is from Debian.

**Comment by wolfbeast** [comment]
I think it would be a good idea to coursely distribute it in categories of similar distros. I.e.: put all Red Hat(e) derivatives together, all Debian ones together (including Ubuntu), all Slackware ones together, etc.

**Comment by trav90** [comment]
We can also copy some (or all) of the info over from the SourceForge wiki page.

**Comment by Axiomatic-** [comment]
@wolfbeast is there any add-on SDK that has been modified to work with Pale Moon so issue like #140 can be referenced to see the documentation. If there is none, are add-ons using the add-on SDK on their own?

**Comment by wolfbeast** [comment]
Our own SDK works with our browser. It's included in the Pale Moon Source - and if people build their xpis against our SDK version, they will work in Pale Moon (as long as they stick to compatible SDK functions, of course)

**Comment by Axiomatic-** [comment]
I have gotten around to adding Nix, and NixOS build instructions. 

@trav90 since you build on CentOS (a Red Hat based distribution) can you add build instructions for that on the wiki? (Not sure if the ones on SF are update, or if there is a few changes.)

**Comment by trav90** [comment]
@Axiomatic sure, I'll get the CentOS instructions up in the next day or two.

**Comment by wolfbeast** [comment]
We have a work in progress on the wiki, which will be added to as-available. Closing this.
