### ISSUE TITLE
Remove the stub installer

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#450]
We never use the nsis stub installer and it's the reason for a whole bunch of code and media to be in branding that we don't need or want.

Thia should be removed.

**Comment by mattatobin** [comment]
We should target this for Tycho rather than the current codebase.

**Comment by mattatobin** [comment]
Assign this to me.. I am on a cleanup kick.

It really shouldn't be that difficult to work out.

**Comment by mattatobin** [comment]
RESOLVED FIXED
