### ISSUE TITLE
Official branding seems to be always applied in language packs

### ISSUE THREAD

**Issue by Pulfer** [MoonchildProductions/Pale-Moon#451]
Even if I build Pale Moon with "--disable-official-branding" option it still has "Pale Moon" name (in About window and many other places). This happens when language packs are installed and enabled.

Russian language pack disabled:
![palemoon-en](https://cloud.githubusercontent.com/assets/4058218/16414193/a9c5fad8-3d79-11e6-8c17-66a77d48eb7f.png)

Russian language pack enabled:
![palemoon-ru](https://cloud.githubusercontent.com/assets/4058218/16414173/97fb1a86-3d79-11e6-8015-eb830ae8e636.png)

**Comment by wolfbeast** [comment]
language packs only have officially-branded strings.
