### ISSUE TITLE
Revert mozilla decision on removing site-supplied text for beforeunload and onunload dialogs

### ISSUE THREAD

**Issue by hkmaly** [MoonchildProductions/Pale-Moon#452]
I realize this is going against  #169 but I just hit this problem with web application where you can actually lose data and after reading https://bugzilla.mozilla.org/show_bug.cgi?id=588292 I'm still not convinced preventing the applications to customize the message is good idea. Note that chromium allows site-supplied text.

(Of course, with config option which would turn it back to current behaviour.)

**Comment by wolfbeast** [comment]
I assume you've not run into many sites that wholly abuse this to present you with a huge spammy dialog when you want to navigate away?

"Wait! Before you go consider this special offer bla bla" filling half your screen with marketing BS...
or "Your computer has been infected with a virus!" or similar when you happen to stumble on a slightly shadier site.
Really, I **do** see the potential use of a custom message for some complex web-based applications, but having custom text does tend to get abused -- a lot.

**Comment by wolfbeast** [comment]
I guess there would be some room for improvement. I've read through the bug supplied and I think too many people are on their high horse there, Chromium also makes it too simple which can lead to abuse, but I gather there is a balance to be found, e.g.:
````
~ Are you sure?
This page is asking you to confirm that you want to leave:

[Site supplied text]

[Leave page][Stay on page]
````

**Comment by hkmaly** [comment]
You're right I did not run into many sites abusing that. But note that such sites will abuse EVERYTHING and we shouldn't shut down the internet because of them. We need to find some balance (as you mentioned).

When looking around for documentation of exit popups, I noticed ideas (and finished plugins) like watching mouse pointer and make overlay when mouse leaves window. There is much bigger potential for abuse here - but you can't really stop it as it's not using anything specific, just very general stuff.

I guess limiting the length of site supplied text makes sense, although there was at least one commenter who got legitimate idea for pretty long text ...

**Comment by wolfbeast** [comment]
Approaching it like "let's not do anything about any abuse because it'll be used anyway" is a bad (and extremist) approach I'm not willing to follow.
Also, you have to understand the essential difference here. This dialog is a browser-generated modal dialog -- not something on a page like an overlay that doesn't stop you from performing your intended action.

**Comment by hkmaly** [comment]
"Let's stop any abuse no matter the price" is bad and extremist too. That's why I was talking about balance. And I think that with some preface like the one you mentioned in your second comment - and most importantly, the buttons being "Leave page" and "Stay on page", as they already are - and perhaps some limit (on length or on window size with using scrollbar) - the site-suplied text won't make it more dangerous.

True. It's modal dialog like alert or confirm, not something on a page.

I would think that forbidding alerts inside the beforeunload event handler (mentioned in the bug) would make more sense than current situation which is basically forcing even "good" site authors to use alert to say the site supplied text (yes, I found page recommending that solution).

Or, there is (also mentioned) the model of asking user for permission for this behavior when first page on that domain install the handler, in similar way how now browser asks for allowing notifications or remembering password.

... but, of course, both those ideas looks like considerable more programming than just allowing the site-suplied text (with preface).

**Comment by elypter** [comment]
>Or, there is (also mentioned) the model of asking user for permission for this behavior when first page on that domain install the handler, in similar way how now browser asks for allowing notifications or remembering password.

it could be part of a site setting or even supplied by a filter list. i have a proposal about using filters/site setting lists more broadly here https://www.reddit.com/r/palemoon/comments/4yx4v0/are_there_ideas_to_implement_a_browser_wide/

**Comment by wolfbeast** [comment]
@JustOff I'll be making some string changes here because I need to split up the standard message into a pre-text and a default text if no message was supplied by the `beforeunload` function.

**Comment by JustOff** [comment]
I hope you as usual will introduce new strings (for pre-text and default text) to make possible LPs be compatible with previous browser versions.

**Comment by wolfbeast** [comment]
I didn't, but it's easy enough to rename. I'll do that.

**Comment by JustOff** [comment]
Thanks!
