### ISSUE TITLE
Source for compiling/packaging?

### ISSUE THREAD

**Issue by Lesik** [MoonchildProductions/Pale-Moon#456]
Hey,

I wanted to ask what source I should use for compiling/packaging Pale Moon? The FTP (ftp://source:current@ftp.palemoon.org/palemoon-26.3.3-source.7z) or the [GitHub releases](https://github.com/MoonchildProductions/Pale-Moon/releases)? Which are more up-to-date? Does it matter?

Thanks

**Comment by wolfbeast** [comment]
It doesn't matter. The main difference is that the GitHub releases are tag based, and the tarball ones have Linux filesystem flags included while the .7z does not.

**Comment by wolfbeast** [comment]
Assuming this is answered considering no further reply.

**Comment by Lesik** [comment]
I just realized that this is actually already mentioned in the [compile instructions](http://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/Linux):

> If you chose to use the 7zip packed sources from the website you may encounter compilation issues due to file permissions (or lack thereof).

I'm not sure if this has been recently added to the instructions or I simply somehow managed to miss this sentence, thus redundantly creating this issue. I apologize if the latter is the case.
