### ISSUE TITLE
Why is Pale-Moon so big?

### ISSUE THREAD

**Issue by konsolebox** [MoonchildProductions/Pale-Moon#458]
Why has Pale-Moon become so big that it even has to require at least 12G of filesystem space when compiling?  I'm curious about knowing the exact reasons, so I though it would be better to ask the devs directly.

**Comment by wolfbeast** [comment]
It's 14 million lines of source code. ;-)
Seriously, though, what do you expect from a modern web browser's build size? if you inspect the build/object directory, you can see the exact reasons; primarily it will be taken up by compiled object code. You can blame Mozilla for designing it in such a way.
