### ISSUE TITLE
user.js is read but not all preferences are honored (26.3.3 x86 linux)

### ISSUE THREAD

**Issue by unixpipecentipede** [MoonchildProductions/Pale-Moon#476]
Hello.

I keep a `.js` file with some `user_pref()` configurations which is then symlinked as `user.js` in my profile directory (thus making editing/backup a bit easier).

Version 26.3.3 of paleomoon is reading `user.js` but somehow refuses to change some preferences as if they were locked.

Real world examples of working preferences:

``` javascript
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
user_pref("font.default.x-western", "sans-serif");
user_pref("geo.enabled", false);
user_pref("pdfjs.disabled", true);
```

Real world examples of ignored preferences (defaults are kept intact):

``` javascript
user_pref("layout.css.dpi", 0)
user_pref("layout.spellcheckDefault", 0);
user_pref("services.sync.registerEngines", "");
user_pref("signon.autofillForms", false);
user_pref("signon.rememberSignons", false);
user_pref("status4evar.addonbar.windowGripper", false);
user_pref("status4evar.status.linkOver", 3);
user_pref("status4evar.status.network", false);
user_pref("webgl.disable-extensions", true);
user_pref("webgl.disabled", true);
```

AFAIK `user.js` is the last preferences file read on startup so it should override default settings (omni.ja, defaults directory, etc.).

Sadly I don't remember which previous palemoon version was behaving correctly (I'm sorry). Nevertheless, it might be of help mentioning that the problem also happens on my firefox-esr install (Debian Jessie) since the last upgrade from version `45.2.0esr-1~deb8u1` to `45.3.0esr-1~deb8u1`.

This has been tested on clean profiles and the issue persists.

**Comment by mattatobin** [comment]
Does this issue affect Tycho?

**Comment by Lorienna** [comment]
This is because `user_pref("layout.css.dpi", 0)` at the top of the 2nd list is lacking an obligatory enclosing `;` semi-colon mark :)

For some reason, this prevents the prefs below it from being recognized too.

**Comment by mattatobin** [comment]
Editing user.js manually is not a supported for this very reason. Please use about:config.

Also since no real followup has happened since last year.. I am closing this as WORKSFORME
