### ISSUE TITLE
Website Issue - FamilySearch.org

### ISSUE THREAD

**Issue by hook54321a** [MoonchildProductions/Pale-Moon#477]
FamilySearch.org does not load correctly the the first time whenever the history/cache is cleared. I'm running Windows 7.

What the page looks like in Pale Moon on the first load after clearing history/cache:
![familysearch-pale moon](https://cloud.githubusercontent.com/assets/7744057/17577506/641e538c-5f33-11e6-9d52-45f62b6e5004.PNG)

What the page looks like in Firefox, and Palemoon after the first load:
![familysearch-firefox](https://cloud.githubusercontent.com/assets/7744057/17577536/cafa7aea-5f33-11e6-99bc-c51c10a0483c.PNG)

**Comment by wolfbeast** [comment]
Unable to reproduce. Seems like a timing issue (possibly due to async loading) which ultimately is the web designer's responsibility to do correctly.

**Comment by hook54321a** [comment]
It doesn't seem to happen at all on Ubuntu.
