### ISSUE TITLE
Website Issue - dashboard.at.ninjawedding.org

### ISSUE THREAD

**Issue by hook54321a** [MoonchildProductions/Pale-Moon#479]
The website has a custom right click menu for certain parts of the page, but it doesn't work in Pale Moon.

Screenshot of right click menu in Firefox:
![screenshot from 2016-08-12 18-41-15](https://cloud.githubusercontent.com/assets/7744057/17633455/e6362ef0-60bc-11e6-8e8f-8d1173813611.png)

Screenshot of right click menu in Pale Moon:
![screenshot from 2016-08-12 18-46-27](https://cloud.githubusercontent.com/assets/7744057/17633507/2ff36a1c-60bd-11e6-926e-13255de59555.png)

**Comment by wolfbeast** [comment]
Did you disable the DOM setting that allow websites to disable or change the right-click menu, by any chance?
Do you have any errors in the error console (only list errors, not warnings/info etc.) when loading this dashboard or trying to use the menu?

**Comment by hook54321a** [comment]
[17:35:59.865] The connection to ws://dashboard.at.ninjawedding.org/stream was interrupted while the page was loading. @ http://dashboard.at.ninjawedding.org/:1595

**Comment by janekptacijarabaci** [comment]
See `view-source:http://dashboard.at.ninjawedding.org/#line1466` (Firefox 41+)

See also: [1012662](https://bugzilla.mozilla.org/show_bug.cgi?id=1012662), [1170911](https://bugzilla.mozilla.org/show_bug.cgi?id=1170911), etc.

**Comment by wolfbeast** [comment]
Can you check and see if this is fixed in the unstable channel? We now have clipboard handling in the HTML5 way implemented (for cut/copy) accessible from page content.

**Comment by JustOff** [comment]
For me custom menu shows even in 27.0.3, and in 27.0.1b1 copy function works properly.
