### ISSUE TITLE
Disabling address bar shading should apply to padlock box as well

### ISSUE THREAD

**Issue by vlakoff** [MoonchildProductions/Pale-Moon#480]
I'm setting [`browser.padlock.urlbar_background`](http://forum.palemoon.org/viewtopic.php?f=24&t=3357) to `0` to remove the annoying address bar shading on secure sites.

However, the padlock box still has the shading, so the appearance is quite inconsistent.

This is because the above setting changes `#urlbar[https_color]` so the browser.css doesn't apply box-shadow to the address bar, but `#identity-box` also has box-shadow CSS and these one are still applied.

Currently I'm just using this userChrome.css: `#identity-box { box-shadow:none !important; }`

**Comment by wolfbeast** [comment]
The identity box should always have a color indicator to the type of secure site visited. The box shadow on it has nothing to do with the URLbar shading, and isn't inconsistent in that respect.
 I can see if there's a way to make it blend better, though.

**Comment by vlakoff** [comment]
Thanks for considering this.

I have tested your changes in association with `browser.padlock.urlbar_background 0` and it looks really well. I'm not so sure in association with the default address bar glowing. If it were up to me, I'd reduce the address bar glowing as well, fwiw.
