### ISSUE TITLE
JavaScript `zIndex` seems to have a limitation

### ISSUE THREAD

**Issue by Martii** [MoonchildProductions/Pale-Moon#481]
Ref:
* sebaro/SaveTube#6
* [sebaro/SaveTube`bd82f69`/savetube.user.js#L270](https://github.com/sebaro/SaveTube/blob/bd82f695f413edaf616a5dc978ce241c501109c1/savetube.user.js#L270)

When setting an element to a `zIndex` JavaScript element to `9999999999` the element always stays visible in full screen mode. Setting to `1999999999` fixes that.

Thank you for the look and keep up the great work. :)

```
Mozilla/5.0 (X11; Linux x86_64; rv:2.1) Gecko/20100101 Goanna/20160629 PaleMoon/26.3.3
and Windows version too
```

**Comment by wolfbeast** [comment]
The limitation is the standard limitation for 32-bit integers. If you try to set it to an out-of-bounds value, it will not be honored.
Solution: use sane 32-bit int values for your z-index.

**Comment by Martii** [comment]
Hmm even on 64 bit PM ?

**Comment by wolfbeast** [comment]
> Hmm even on 64 bit PM ?
Yes. The bitness of the JS interpreter isn't dependent on the bitness of the platform. That would be a bad thing if so.

**Comment by Martii** [comment]
So dragging you over there to [this response](https://github.com/sebaro/SaveTube/issues/6#issuecomment-239677655) do you feel that anything can be done besides "using sane values" with 32 bit numeric limitations? I appreciate your assistance.

**Comment by wolfbeast** [comment]
Use sane value. anything about 2 billion for this kind of value is just silly.

**Comment by Martii** [comment]
Alright thanks. Closing... sebaro says that Fx/Chrome picks a value when out of range... suppose I'll go look it up in the w3 specs to be sure when I get back to dev station. Thanks.

**Comment by wolfbeast** [comment]
"just picking a value" is causing ambiguity. I assume it'll pick the limit value in that case -- so what if two exceedingly large values both cap to that? what z-index should the browser give priority to then? I think you get my drift ;)

**Comment by wolfbeast** [comment]
The W3C [says](http://www.w3.org/TR/CSS22/syndata.html#numbers) about specced values as `<integer>`:

> 4.3.1 Integers and real numbers
>
> Some value types may have integer values (denoted by `<integer>`) or real number values (denoted by `<number>`). Real numbers and integers are specified in decimal notation only. An `<integer>` consists of one or more digits "0" to "9". A `<number>` can either be an `<integer>`, or it can be zero or more digits followed by a dot (.) followed by one or more digits. Both integers and real numbers may immediately be preceded by a "-" or "+" to indicate the sign. -0 is equivalent to 0 and is not a negative number.
> 
> Note that many properties that allow an integer or real number as a value actually restrict the value to some range, often to a non-negative value. 

It does not determine any specific range, so using large values like that is at risk of differing per implementation/client.
