### ISSUE TITLE
Re-implement WebP decoding

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#489]
Created as a clone of MoonchildProductions/Tycho#4

This needs help from someone familiar with the changes to frame allocation as done by Mozilla (moving frame allocation to the decoder and then moving it off-main-thread)

The branch Pale-Moon/TY-libwebp-work has the work so far but it is not in a buildable state right now.

**Comment by wolfbeast** [comment]
Analysis:
Frame allocation was changed in Bug 1116735 to occur in the decoder, which was made OMT in 1116733. Added some changes to frameanimator and frameblender in 1119938 and 1116737 and a few more bugs to fix OMT issues due to locking, all leading up to 1079627 to support multiple decoders at once in RasterImage. This is all landed in our new code base for Tycho.

This sequence makes simply backing out the change to frame allocations not feasible. We have to pull the frame allocation forward to what is our current code, but there's no information available anywhere what the call should be converted to. posting in the Mozilla WebP take 2 bug seems to be inappropriate but considering a direct mail to @sethfowler (not sure if the e-mail address I found is monitored) didn't get a reply I'm running out of options.

Does anyone have any insight in this part of the image decoder code and frame allocation code to make this frame allocation call proper for our current code?
Reminder, the culprit is an .EnsureFrame() call in the WebP decoder that uses the old format and method to allocate a frame for the decoder:
````C++
imgFrame* aFrame;
nsresult res = mImage.EnsureFrame(0, 0, 0, width, height,
                                  gfxASurface::ImageFormatARGB32,
                                  (uint8_t**)&mImageData, &imagelength,
&aFrame);
````
Already known is that the gfxsurface should be `gfx::SurfaceFormat::B8G8R8A8` instead, but the actual frame allocation in /image/decoders/nsWEBPDecoder.cpp (WebP branch) is incorrect because of the above.

Mozilla's "take 3" builds on a completely different way of handling image decoding with Lexers, which can't be used by us.

**Comment by sethfowler** [comment]
Possibly instead of RasterImage::EnsureFrame(), you're looking for Decoder::AllocateFrame(). The version of the code you're using is years old. I don't remember the details of how it works anymore, and I can't offer you support. Sorry.

**Comment by wolfbeast** [comment]
Thanks Seth,
I'll see if I can figure out how `Decoder::AllocateFrame()` is supposed to be called; I did try to change the call to that before but obviously must have made a mistake somewhere -- unfortunately none of this is documented and has recently been changed again. If there's anything you happen to recall about the calling site's parameters that should be passed, that would be a massive help.

**Comment by sethfowler** [comment]
The current version of the code has much better comments, and AllocateFrame() has not changed recently. (Though I expect it will actually be removed pretty soon, as only a few decoders are still using it.) It may help a little to check out the current version of Gecko and take a look.

**Comment by wolfbeast** [comment]
The problem with looking at Gecko is that the decoders for the supported formats are all wildly different and provide no real pointers. Looking at some of the different headers did help though.

Seems like part of the problem was the WebP decoder allocating its own mImageData - since that wouldn't get initialized it caused crashes.

Commit 0abb271e53be13a19d77da4ca59ecd7e2d1b70b4 uses AllocateFrame() and NeedNewFrame() (might be redundant to use both?) to get a frame of the proper dimensions, and decoding works. Just needs the data transfer to be done properly from WebPDecoder::mData (holding decoded WebP data) to Decoder::mImageData -- the pointer magic used in the old decoder implementation obviously doesn't work for that (the data structure in rasterimage was different that what mImageData in Decoder uses).

**Comment by wolfbeast** [comment]
Turns out it was even simpler. Frame allocation isn't needed in the WEBPDecoder.cpp at all, considering the Decoder class already takes care of this. The only problem with the initial implementation was the allocation of disjointed mImageData blobs that was previously required for using RasterImage.

Follow-ups b30d5a00043ec5ebcc3d46f4d5ada48f271ac698 and 65868278b8ea52f831db0981cfa151c70716286b completely wrap up our WebP support.
Verified in several test runs.
