### ISSUE TITLE
Build fails when using --enable-shared-js

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#490]
Created as a clone of MoonchildProductions/Tycho#9

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1209684
_Bug 1209684 - --enable-shared-js builds are totally broken_

**Comment by win7-7** [comment]
--enable-shared-js works up to Firefox 36.
For some reason Firefox 37 causes build bustage with --enable-shared-js and compiler error is following:
browsercomps.dll linking, 7 unresolved externals: xpcomglue_s.lib(unified_cpp_xpcom_glue0.obj) 

![failpart1](https://cloud.githubusercontent.com/assets/16404264/18418395/1d8ef168-784e-11e6-8e0b-4bd900567da4.PNG)

Firefox 38 also gets further with https://github.com/mozilla/gecko-dev/commit/1e8c1994e1fa512c23b2c92bc1305877f747e5d7 reverted but also has same error in browsercomps.dll as Firefox 37 has.

**Comment by win7-7** [comment]
--disable-unified-compilation does produce working build with shared js enabled in Firefox 37 unfortunately Mozilla has removed this option from codebase in Mozilla 38 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1121000) so it would be need to be reimplemented or alternative fix unified compilation so it would be able to work with shared js like it actually did work in Firefox 36 before Mozilla changed something in codebase without testing these changes.

**Comment by mattatobin** [comment]
UNIFIED_SOURCES is totally responsible for this.. what would be the best call is to take spidermonkey out of UNIFIED_SOURCES and see what we get.. THEORETICALLY it should be as easy as changing UNIFIED_SOURCES to just SOURCES in moz.build in spidermonkey... But ICU may have indeed thrown a wrench in the works...

**Comment by win7-7** [comment]
modified xpcom/base and xpcom/glue moz.build files and changed UNIFIED_SOURCES to SOURCES.

Got working build of Tycho with shared js enabled! Now Moonchild just need to confirm this and then he can close this issue.

**Comment by mattatobin** [comment]
It isn't as simple of that.. We need to check for impacts.. Though, I would like to see what you actually reverted.

**Comment by win7-7** [comment]
I backed out/reverted entire patch from bug 1125784 (https://bugzilla.mozilla.org/show_bug.cgi?id=1125784) and changed code back to previous code before patch only difference is that I also restored RootedObject global(cx); as it was removed in the commit https://github.com/MoonchildProductions/Tycho/commit/1e8c1994e1fa512c23b2c92bc1305877f747e5d7 . I'm not sure if reverting whole patch + restoring RootedObject global(cx);  was needed because I'm not coder but it seemed to get past of initial error so it would be either your call mattatobin or Moonchild as you have actual coding knowledge as what do next to resolve this issue and test these changes properly.

**Comment by wolfbeast** [comment]
@win7-7 A lesson to learn about bugzilla: never fully trust posted patches; you should always look first at the hg changesets (what was actually landed) since more than occasionally there are additional changes that get landed that are not in the attached patch files and are important. So the additional change for `global(cx)` as in the Tycho history would indeed be required.

I've poked Mozilla people since there's still a needinfo flag on that bug and it's going stale, seeing if your blamed bug is in fact the cause or merely a symptom (people involved there are likely more at home with this part of Spidermonkey and symbols).

**Comment by wolfbeast** [comment]
Looks like the problem is dependencies. Unified sources is 100% at fault here, but not just because it busts some things when used, but rather because it makes missing dependencies slip through -- in this case `requireAtLeast()` which is a jsapi function that gets used outside of js in netwerk/ after the changes Win7-7 pointed out.

In a unified build, this doesn't break even if it should from a pure code perspective, because the right files just happen to be concatenated together for compilation. So unified building is a gigantic pitfall for source code dependencies.

IIUC, similarly but in the "other direction", XPCOM optimizes away certain calls to JSGC in unified mode and misses imports as a result that would be fine if in the (already dependent) libxul, but if in its own shared js library becomes a missing external when linking `browsercomps.dll`
