### ISSUE TITLE
Crash with GStreamer 1.x

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#497]
Created as a clone of MoonchildProductions/Tycho#111

@trav90 said:

> While Pale Moon 26 has multiple crash points with gst1.x (I've gotten several different backtraces, sometimes from the same site!), the backtraces I've gotten using Tycho have consistently been the same. At this point if we are going to start using gst1.x again, it should not be until v27.
> 
> Below is the backtrace from Tycho crashes with GStreamer 1.x:
> 
> https://gist.github.com/trav90/514aa433ac4845f85bf2ed1d9fb04e1f

**Comment by h1z1** [comment]
Do you get this randomly on sites like 9gag?  No matter what I've tried, PM crashes on videos.

**Comment by trav90** [comment]
I am marking this WONTFIX and closing since GStreamer will not be used for MP4/H.264 video decoding by default now that our FFmpeg support is fixed up and has landed on master. Our GStreamer code will not be receiving any further updates from myself, and will eventually be removed altogether.
