### ISSUE TITLE
Restore previous session feature doesn't work.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#499]
Created as a clone of MoonchildProductions/Tycho#124

See discussion in the Tycho bug.

**Comment by wolfbeast** [comment]
Quoting @Antonius32 

>Um, all changes made in bugs 881049 and 898308 are in the /browser subtree, or am I missing something? In other words, do we need all parts of the aforementioned bugs?

I was making a general approach remark - I didn't check if there's stuff outside /browser -- if there isn't, then yes, we'd need all code changes ported from the patches.

**Comment by wolfbeast** [comment]
Hmm this seems to be a bit more involved than expected There's obviously some dependent bugs that are not properly marked in the BMO bugs. This might make things complicated.

**Comment by wolfbeast** [comment]
I'm going to see if using the workaround @wsdfhjxc suggested is a good temporary measure. These promises are like temporal mechanics; they tend to give one headaches.

**Comment by hmazuji** [comment]
i was counting on the previous session opening when i restarted pale moon.  now that it didn't restart, how do i restart it manually ?

**Comment by wolfbeast** [comment]
For tech support, please go to the forum.
