### ISSUE TITLE
Consider dropping support for HTTP/0.9

### ISSUE THREAD

**Issue by KrzysiekJ** [MoonchildProductions/Pale-Moon#502]
As described in Chrome’s issue [“Security: Cross-Protocol Theft from non-HTTP services via DNS rebinding + HTTP/0.9”](https://bugs.chromium.org/p/chromium/issues/detail?id=600352), support for HTTP/0.9 can be used by a remote website to extract data from some local services. (The problem is also explained in [“How to steal any developer's local database”](http://bouk.co/blog/hacking-developers/)). However dropping support for HTTP/0.9 will not solve the general problem, in particular because some services (like ElasticSearch) use HTTP as a communication protocol.

**Comment by wolfbeast** [comment]
Cross-protocol attacks are well-known and cannot reasonably be mitigated by yanking out protocols until you have none left. These kinds of attacks should always be kept in mind in server implementations. I don't think this is any particular reason to remove the "raw http" fallback that HTTP/0.9 provides for non-standard services. In fact, I'm pretty sure removing this at this point in time would create significant web compat and even more so intranet issues which we'd rather avoid.

**Comment by wolfbeast** [comment]
@trav90 @mattatobin -- I think this should be wontfixed; insights?

**Comment by KrzysiekJ** [comment]
One of the comments in the Chrome issue states: “I remain convinced that disabling HTTP/0.9 globally is low-risk.”. I agree however that dropping it would only mean bypassing the problem for some cases, so it is not a general solution. Perhaps a better thing to do would be to implement this suggestion:

> Browser vendors could implement a ‘DNS pinning’ of sorts, which makes it ignore DNS changes that are made after the site is done loading.

**Comment by wolfbeast** [comment]
We already do this. We retain DNS entries for 10 minutes and they won't be able to be changed until the value expires.

**Comment by trav90** [comment]
It looks to me like this chromium issue started out as "this could happen and be _interpreted_ by Chrome as HTTP/0.9", and then morphed into "let's remove HTTP/0.9 altogether!".

@wolfbeast I agree and think this should be wontfixed as well.

**Comment by mattatobin** [comment]
Tentatively RESOLVED INVALID
