### ISSUE TITLE
Add Option or White/Blacklist to Disable Keyboard Shortcut Hijacking

### ISSUE THREAD

**Issue by ilikenwf** [MoonchildProductions/Pale-Moon#503]
Sites such as Twitter, Slack, Discord, Hipchat, and others tend to hijack/capture CTRL + [key] combinations, making it very frustrating when one tries to CTRL+[T,W,Tab,S,C,X,F] or whatever else.

Suggestions around the internet have implied various Greasemonkey scripts should fix this issue and having tried most of them, even with custom modifications, none of them to work at all, at least in Pale Moon. 

This is not only a usability issue, but a significant security issue as well, in my opinion, but if nothing else it would be nice to protect the defined list of shortcuts within Pale Moon, even if it is through a checkbox option somewhere in the preferences.

**Comment by janekptacijarabaci** [comment]
See also https://forum.palemoon.org/viewtopic.php?f=56&t=12928

**Comment by wolfbeast** [comment]
Actually, there is two sides of the story here.
This issue requests tighter control over tab hotkeys (which will be in v27), and the forum thread requests reversal of this tighter control for the sake of writing overriding extensions.

Tough cookie to strike a balance here.

**Comment by ilikenwf** [comment]
Indeed. I wouldn't even be speaking here if grasemonkey scripts that currently exist would actually work at preventing the interception of ctrl + [insert key here] codes but none of them do, unfortunately.

Even if an addon were created to allow such a thing, I'd be grateful.

Would a proper balance be attained if an addon or PM itself had a preference tool that allows you to set a list of "no override" key combinations, thus letting all the others be fair game? Likewise, it could even allow binding an alternative so that sites that rely on key combos can be customized, even if outside of their original spec.

**Comment by h1z1** [comment]
I never understood why browsers allow this at all without a warning?  Shouldn't users be given an option to accept such access first?

**Comment by wolfbeast** [comment]
Marking this wontfix for Tycho. If this still needs to be re-examined, a new issue should be opened on UXP, although breaking this status quo is going to be difficult with the increase of "Web Applications" that can't be arbitrarily restricted depending on which browser is in use.
