### ISSUE TITLE
Couterfingerprinting measures 

### ISSUE THREAD

**Issue by triceratops1** [MoonchildProductions/Pale-Moon#507]
Palemoon has  some setting for protect you againt canvas (2d) fingerprint.

but don't has any measures   against webgl and webaudio fingerprint

you could take as base this addon
https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf?hl=en-US  

and protect against 
WebGL fingerprint http://www.browserleaks.com/webgl 

AudioContext Fingerprint https://audiofingerprint.openwpm.com/

**Comment by wolfbeast** [comment]
Duplicate of #446
