### ISSUE TITLE
[Tycho] Get Mac builds working

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Pale-Moon#514]
This is a continuation of the various mac related issues from the now defunct Tycho repo.

@stevenschlansker 

I _may_ have found a clue regarding the resource/bin changes that you should likely look at.

In commit https://github.com/MoonchildProductions/Tycho/commit/7959bd3a2bf170b7713a3492cb44b043dc3e5f38 Mozilla made some changes to nsBrowserApp.cpp relating to the new signing .app bundle structure requirements nonsense.

Obviously, we have the platform parts but you can try adapting the changes for nsBrowserApp so that we may finally get you off and running.

**Comment by mattatobin** [comment]
I think this Tycho issue is the one with history: https://github.com/MoonchildProductions/Tycho/issues/97

**Comment by stevenschlansker** [comment]
I spent some time yesterday getting all my repos linked up, and porting over my branches to the new repo.  Losing the Tycho history was a bit unfortunate, but such is life.  I'm back to trying to figure out why it won't boot -- thanks for the reference, I'll check that commit out.

**Comment by stevenschlansker** [comment]
Oh ho!  That indeed was at least one of the problems!  I did a cherry-pick and now the browser boots to the start page, then immediately crashes.

**Comment by mattatobin** [comment]
Progress is progress.. Use the Tycho repo and I guess go through all the commits starting here: https://github.com/MoonchildProductions/Tycho/commits/master/browser?page=5 and going back in time looking for more mac changes related to that structure thing.

**Comment by stevenschlansker** [comment]
First Mac alpha available here: https://forum.palemoon.org/viewtopic.php?f=41&t=13083
