### ISSUE TITLE
Move WINVER globally to 0x0600

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#515]
We currently have several definitions of _WIN32_WINNT of 0x0600 to make sure that the correct windows kernel header versions are selected. We should move WINVER to 600 globally for the entire code base to be able to drop these duplicate definitions in individual source files.

Some 3rd party modules, however, seem to break when this is done, specifically the Adobe nICEr module in /media/mtransport but potentially others later in the build sequence too that expect older code/environments to work under -- this would require some further investigation and/or T&E to sort out.
Once breaking modules are sorted, redundant definitions for 0x0600 (NT6) can be removed from the code base.

**Comment by wolfbeast** [comment]
Looks like the source code misdefines WINVER to begin with. according to MS documentation it should be 0x0600 and not 600, but Mozilla uses the format 501 502 600 etc.

**Comment by wolfbeast** [comment]
Of note, WINVER is defined without 0x0 but AC_DEFINEd with it.
````
    AC_DEFINE_UNQUOTED(WINVER,0x$WINVER)
    AC_DEFINE_UNQUOTED(_WIN32_WINNT,0x$WINVER)
````

**Comment by Gpower2** [comment]
Currently configure.in has WINVER defined as "WINVER=502" in line 441.
Should it be changed to "WINVER=600"?

**Comment by wolfbeast** [comment]
@Gpower2 as stated in the original issue comment, this breaks the build.

**Comment by wolfbeast** [comment]
@Gpower2 I had to back your PR back out after merge. It does not build for me.

https://gist.github.com/wolfbeast/6587aacb863b2b5d0ec20e316418ed71

**Comment by Gpower2** [comment]
Could you send me the .mozconfig you use, since it doesn't fail for me and I tested it a lot of times before pushing it.

**Comment by Gpower2** [comment]
My bad... Actually x64 builds just fine, but that's x86 fails with the same error. I'll look into it, sorry for the mess...

**Comment by wolfbeast** [comment]
No worries. The end result is what matters ;)
Peculiar that it only fails on x86.

**Comment by Gpower2** [comment]
Turns out it was an easy fix. util.h had and ifdef for x86 builds, that redefined inet_ntop function with different type modifier than the one found in windows headers. So I changed that ifdef to check for WINVER value and not to redefine inet_ntop for WINVER >= 0x0600.
Created PR #527

**Comment by wolfbeast** [comment]
I've made a few builds now with this in place and they seem to be stable and properly using NT6 system/kernel calls (with noticeable slight performance increase with casual inspection).
Considering this resolved. Thanks for the help, @Gpower2 !

**Comment by Gpower2** [comment]
Glad to be of help! :)
