### ISSUE TITLE
Missing download progress on taskbar icon

### ISSUE THREAD

**Issue by wsdfhjxc** [MoonchildProductions/Pale-Moon#516]
The download progress on PM's taskbar icon is missing under Windows 7 and Windows 10.
This is about Tycho. Possibly something related to DownloadTaskbarProgress module?

**Comment by wsdfhjxc** [comment]
After uncommenting [these lines](https://github.com/MoonchildProductions/Pale-Moon/blob/9fcedeb3476c2174dbbb8a1a89285bbad05aec2a/browser/base/content/browser.js#L1088-L1090) an error is being thrown:

`Error: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIDownloadManager.addPrivacyAwareListener]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/DownloadTaskbarProgress.jsm :: DTPU_init :: line 139"  data: no]
Source File: chrome://browser/content/browser.js
Line: 7797`

It's coming after [this call](https://github.com/MoonchildProductions/Pale-Moon/blob/9fcedeb3476c2174dbbb8a1a89285bbad05aec2a/toolkit/mozapps/downloads/DownloadTaskbarProgress.jsm#L139), so that `addPrivacyAwareListener` method seems to be interrupted at execution or something.

**Comment by wolfbeast** [comment]
... Why do you think I commented those lines with
`TODO: fix taskbar-based download progress` ...?

**Comment by wsdfhjxc** [comment]
Didn't notice this was done by you. Sorry.

**Comment by wolfbeast** [comment]
PR #528 should fix this. I'll see if I can churn out a build to verify.

**Comment by wolfbeast** [comment]
Verified fixed.

![progress-taskbar](https://cloud.githubusercontent.com/assets/3359132/18614779/e12a1ed0-7d95-11e6-8b73-c5f6b6f01105.png)
