### ISSUE TITLE
[mac] Image decoding crashes on startup

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/Pale-Moon#517]
```
Process 75955 launched: '/Users/steven/code/Pale-Moon/obj-x86_64-apple-darwin15.5.0/dist/PaleMoon.app/Contents/MacOS/palemoon' (x86_64)
Process 75955 stopped
* thread #48: tid = 0x11a60b, 0x0000000104a82346 XUL`jsimd_ycc_extbgrx_convert_sse2.rowloop + 6, name = 'ImageDecoder #3', stop reason = EXC_BAD_ACCESS (code=1, address=0x17f9243c6398)
    frame #0: 0x0000000104a82346 XUL`jsimd_ycc_extbgrx_convert_sse2.rowloop + 6
XUL`jsimd_ycc_extbgrx_convert_sse2.rowloop:
->  0x104a82346 <+6>:  movq   (%rsi), %rsi
    0x104a82349 <+9>:  movq   (%rbx), %rbx
    0x104a8234c <+12>: movq   (%rdx), %rdx
    0x104a8234f <+15>: movq   (%rdi), %rdi
```

**Comment by stevenschlansker** [comment]
Might be related to aggressive clang optimization: https://github.com/libjpeg-turbo/libjpeg-turbo/pull/20

**Comment by wolfbeast** [comment]
Looks like it.

We're currently a little behind with libjpeg-turbo (1.4.0). I think the proper way forward is to update to current latest release (1.4.1) and apply this patch on top. Note the Mozilla code changes needed when updating (see `/media/libjpeg/mozilla.diff`)

**Comment by wolfbeast** [comment]
Please build from tip and verify if this still occurs.

**Comment by stevenschlansker** [comment]
Confirmed fixed on master!  Tycho now builds and launches the home page and http://arstechnica.com without crashing.
