### ISSUE TITLE
FTBFS recipe for target 'nsNSSCallbacks.o' failed

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#52]
* Ubuntu GNU/Linux 15.04
* gcc 4.9.2
* Linux Hedy 3.19.0-14-generic #14-Ubuntu SMP Mon Apr 13 22:18:24 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

59:26.34 nsNSSCertHelper.cpp
59:26.38 nsNSSCertificate.cpp
59:26.68 nsNSSCertificateDB.cpp
59:27.44 /home/themusicgod1/palemoon/Pale-Moon/security/manager/ssl/src/nsNSSCallbacks.cpp: In function ‘void HandshakeCallback(PRFileDesc*, void*)’:
59:27.44 /home/themusicgod1/palemoon/Pale-Moon/security/manager/ssl/src/nsNSSCallbacks.cpp:977:15: error: ‘class nsSSLStatus’ has no member named ‘mCipherSuite’
59:27.44        status->mCipherSuite.Assign(cipherInfo.cipherSuiteName);
59:27.44                ^
59:27.49 /home/themusicgod1/palemoon/Pale-Moon/security/manager/ssl/src/nsNSSCertificate.cpp: In member function ‘virtual nsresult nsNSSCertificate::GetChain(nsIArray**)’:
59:27.49 Warning: -Wunused-but-set-variable in /home/themusicgod1/palemoon/Pale-Moon/security/manager/ssl/src/nsNSSCertificate.cpp: variable ‘srv’ set but not used
59:27.50 /home/themusicgod1/palemoon/Pale-Moon/security/manager/ssl/src/nsNSSCertificate.cpp:831:13: warning: variable ‘srv’ set but not used [-Wunused-but-set-variable]
59:27.50    SECStatus srv;
59:27.50              ^
59:27.96 
59:27.96 In the directory  /home/themusicgod1/palemoon/Pale-Moon/obj-x86_64-unknown-linux-gnu/security/manager/ssl/src
59:27.96 The following command failed to execute properly:
59:27.96 c++ -o nsNSSCallbacks.o -c -I../../../../dist/stl_wrappers -I../../../../dist/system_wrappers -include /home/themusicgod1/palemoon/Pale-Moon/config/gcc_hidden.h -DNSS_ENABLE_ECC -DDLL_PREFIX="lib" -DDLL_SUFFIX=".so" -DMOZ_GLUE_IN_PROGRAM -DXPCOM_TRANSLATE_NSGM_ENTRY_POINT=1 -DMOZILLA_INTERNAL_API -D_IMPL_NS_COM -DEXPORT_XPT_API -DEXPORT_XPTC_API -D_IMPL_NS_GFX -D_IMPL_NS_WIDGET -DIMPL_XREAPI -DIMPL_NS_NET -DIMPL_THEBES -DSTATIC_EXPORTABLE_JS_API -DNO_NSPR_10_SUPPORT -I/home/themusicgod1/palemoon/Pale-Moon/security/manager/ssl/src -I. -I../../../../dist/include -I/home/themusicgod1/palemoon/Pale-Moon/obj-x86_64-unknown-linux-gnu/dist/include/nspr -I/home/themusicgod1/palemoon/Pale-Moon/obj-x86_64-unknown-linux-gnu/dist/include/nss -fPIC -Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Wtype-limits -Wempty-body -Wsign-compare -Wno-invalid-offsetof -Wcast-align -fno-exceptions -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -std=gnu++0x -pthread -pipe -DNDEBUG -DTRIMMED -g -Os -freorder-blocks -fomit-frame-pointer -DMOZILLA_CLIENT -include ../../../../mozilla-config.h -MD -MP -MF .deps/nsNSSCallbacks.o.pp /home/themusicgod1/palemoon/Pale-Moon/security/manager/ssl/src/nsNSSCallbacks.cpp
59:27.96 /home/themusicgod1/palemoon/Pale-Moon/config/rules.mk:1104: recipe for target 'nsNSSCallbacks.o' failed
59:27.96 make[7]: *** [nsNSSCallbacks.o] Error 1
59:27.96 make[7]: *** Waiting for unfinished jobs....
59:28.69 /home/themusicgod1/palemoon/Pale-Moon/config/makefiles/target_libs.mk:59: recipe for target 'libs' failed
59:28.69 make[6]: *** [libs] Error 2
59:28.69 /home/themusicgod1/palemoon/Pale-Moon/config/makefiles/target_libs.mk:59: recipe for target 'libs' failed
59:28.69 make[5]: *** [libs] Error 2
59:28.69 /home/themusicgod1/palemoon/Pale-Moon/config/makefiles/target_libs.mk:16: recipe for target 'libs_tier_platform' failed
59:28.69 make[4]: *** [libs_tier_platform] Error 2
59:28.69 /home/themusicgod1/palemoon/Pale-Moon/config/rules.mk:723: recipe for target 'tier_platform' failed
59:28.69 make[3]: *** [tier_platform] Error 2
59:28.69 /home/themusicgod1/palemoon/Pale-Moon/config/rules.mk:656: recipe for target 'default' failed
59:28.69 make[2]: *** [default] Error 2
59:28.69 /home/themusicgod1/palemoon/Pale-Moon/client.mk:372: recipe for target 'realbuild' failed
59:28.69 make[1]: *** [realbuild] Error 2
59:28.69 client.mk:172: recipe for target 'build' failed
59:28.69 make: *** [build] Error 2
59:28.73 522 compiler warnings present. 

This has started some time after commit on mar 28.  I will try to narrow down the commit where this started.

**Comment by wolfbeast** [comment]
Have you tried clobbering? The interfaces changed so you may need to start clean.

**Comment by themusicgod1** [comment]
that was fresh from git pull

**Comment by wolfbeast** [comment]
Oh right you're trying to build the very last commit, not the tagged beta. Please don't open issues for in-progress tree work.

**Comment by themusicgod1** [comment]
This also happens on 7d69e53 and e9e2898 so this is not just a 'very last commit' thing but something that affects a beta-tagged commit.

**Comment by themusicgod1** [comment]
oh I see that the change was backed out now, good good

**Comment by wolfbeast** [comment]
Jeff,
The commit causing this was not landed until after the tagged beta, so your build tree is likely not in a clean state at the moment. I suggest a fresh checkout and clean build.

**Comment by trav90** [comment]
It builds and runs successfully for me on Manjaro with GCC 4.9.2
