### ISSUE TITLE
Provide hints for parallelization

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#522]
Although the auto-parallelizer in MSVC will analyze and decide automatically, it's very conservative in where it applies multi-threading for multiple cores.

Providing hints with `#pragma loop(hint_parallel(n))` and where needed re-ordering surrounding code or making it more parallel-friendly (e.g. duplicating scalar variables to exclusives) will help the compiler to make the right decision and parallelize where possible.

**Comment by wolfbeast** [comment]
Vectorization is already used and in many cases this is mutually exclusive. Parallel code often means SIMD instructions can't be used; this is an important performance balance to keep in mind.

It may be a good idea to run with the vectorization reporter enabled to see what loops are already vectorized by the compiler and target loops for parallelization that aren't, first.

**Comment by wolfbeast** [comment]
Apparently, Qpar `#pragmas` require the inclusion of `vcomp{nnn}.dll`, likely for the CPU core detection routine and dispatcher code. this needs to be included in the build system (manually added for now before packaging)

**Comment by mattatobin** [comment]
Tycho's build system was updated to handle this in 993a7bc93c1855b1d9dda3768cc32cf91a4f15ec

Branch v26_Dev is WONTFIX unless I get bored
Branch v25_Dev is N/A

**Comment by wolfbeast** [comment]
> Branch v26_Dev is WONTFIX unless I get bored

Branch v26_Dev is a WONTFIX. I doubt I'll build much more on that and even if so, a manual copy or not using `-Qpar` is easy enough.

**Comment by wolfbeast** [comment]
Considering #915 we should remove the MSVC pragmas and replace them with standardized OpenMP pragmas.
