### ISSUE TITLE
Remove D3Dcompiler_43 usage

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#529]
For WebGL, we currently pull in D3DCompiler_43 (DX9) and D3DCompiler_47 (DX10/11).
The former is (I think) only needed for Windows XP support, and our sole dependency for having to install the DirectX SDK for d3dx9 headers (the latter lib is pulled from the Win 8.1 SDK).

We should be able to cut this away and have WebGL on supported operating systems through DirectX by way of the latter lib since we're no longer going to support XP.

**Comment by mattatobin** [comment]
I guess.. How happy is gl and angle gonna be?

**Comment by Gpower2** [comment]
I have a development setup where I haven't installed the DirectX 9 SDK, could I give this issye a try, or is someone else working on it?

**Comment by wolfbeast** [comment]
Nobody else is working on this right now. If you want to give it a shot, I'll label it as assigned.

**Comment by Gpower2** [comment]
Perfect! I'll get into it this weekend.

**Comment by Gpower2** [comment]
Unfortunately the task is so much more than it looks. Whole WMF backend in dom/media is completely dependent on DX9. Latest mozilla-central tree contains a new implementation in DX11, however it's not VS2013 compatible, apart from the fact that it requires some new files in other dirs as well.
Also, there's a new dir structure in dom/media, where wmf, android and other backeds are moved in a new dir platforms in order for the decoders to share common code. For example, in our current code, fmp4 contains its own WMF and android implemention, while it could just use the common code from platforms dir. So I guess the current code base should be changed to that direction.

I'll keep trying to make a buildable version, though I'm not so sure I'll manage.

**Comment by wolfbeast** [comment]
I didn't expect the WMF back-end to rely on DX9 -- that doesn't make much sense since the WMF side is NT6+ only anyway... And as far as I understood you can build without the DX SDK installed and the only thing it affects is whether WebGL is available or not.... Unless Mozilla has changed the way that works?

I don't think rewriting the media back-end is something we should consider viable, if that is what is required here.

**Comment by Gpower2** [comment]
Well, I finally managed to get a building version, without installing DirectX SDK.
However I just deleted the d3dcompiler_43.dll from all dependencies and replaced it with d3dcompiler_47.dll.
A lot of code depends on DX9 and perhaps it would be wise to port it to DX11 at some point.
I have locally reverted commit [https://github.com/MoonchildProductions/Pale-Moon/commit/9aab4b803034dbd503fe0477c596c890e6ab83d1](url) since it broke building for me, so I will wait until this is fixed before making my PR.

**Comment by mattatobin** [comment]
I am not sure how wise it is to substitute 43 for 47.. Does ANGLE's upstream still depend on 43? Maybe we need to simply update from upstream...

**Comment by Gpower2** [comment]
ANGLE built just fine here in both x86 and x86_64, without DirectX SDK installed, while keeping WebGL enabled. I thought about getting latest ANGLE from Mozilla, but they have switched to d3d11 with code that isn't compatible with VS2013. So if we want to get upstream code, we should start porting our code to VS2015...

**Comment by mattatobin** [comment]
Building fine != success.. I am concerned with actual functioning.. We need a test case to verify.

**Comment by Gpower2** [comment]
I tested my builds (both x64 and x86) with https://www.chromeexperiments.com/webgl and alla worked smoothly.

**Comment by mattatobin** [comment]
Well.. okay then. Please excuse what can be perceived as resistance.. It isn't just not all that unjustified caution.

I will play tryserver and report back.. May be tomorrow before I do though..

What about configure? Did you clean up DirectX SDK D3Dcompiler43 bits from the build system configure, installer, package-manifest?

**Comment by Gpower2** [comment]
No worries, I understand your caution, we all have acommon target and that is a working browser. ;)

The only thing needed is the removal of d3dcompiler_43 checking in configure.in, which I left in purpose, in order to be sure that Palemoon builds correctly in both x86 and x64 versions. I could remove it in a new commit.

**Comment by Gpower2** [comment]
Commited removal of d3dcompiler_43 check in configure.in

**Comment by wolfbeast** [comment]
This task has been completed and verified fixed. Beta 2 has the lib removed and works properly on supported operating systems.
