### ISSUE TITLE
Linking a flight from google flights site does not work.

### ISSUE THREAD

**Issue by MaartenDeen** [MoonchildProductions/Pale-Moon#535]
If you search for flights on the google flights page, it shows a button with a price. Clicking that button should direct you to the site of that airline and should show a pre-filled page with those flight details. This does not work in Pale Moon ( 26.4.1 (x64) on Windows 7).

Example: 
https://www.google.nl/flights/?f=0#search;iti=JFK_ORD,MDW_2017-04-01;tt=m;sel=JFKDTW0DL426-DTWORD0DL719;sc=b;eo=e
![pm1](https://cloud.githubusercontent.com/assets/1825970/18806421/4632e056-822c-11e6-9436-729dacd2e16e.png)

Click on the price button (€ 192) and you get this page:
![pm2](https://cloud.githubusercontent.com/assets/1825970/18806425/70cb41c8-822c-11e6-8f3d-00cfa8a0793f.png)

Do this in Firefox (48.0.2) and you see this:
![ff1](https://cloud.githubusercontent.com/assets/1825970/18806437/cddc5564-822c-11e6-9dac-f052f6dd93ac.png)
![ff2](https://cloud.githubusercontent.com/assets/1825970/18806438/cddd9708-822c-11e6-81ad-88ab168f4fe1.png)

I've tried this with different carriers: Delta, American Airline. LOT, Air Lingus, Icelandair, SAS, BA and it does not work. I found one flight for United where it does work, but also others for United where it does not work.

**Comment by wolfbeast** [comment]
Can you please see if the current beta of v27 fixes this?

**Comment by MaartenDeen** [comment]
I've tried 27.0.0b2 (x64) on Win7.
There are certainly more links that work. :)
But not all. I found two: from the page https://www.google.nl/flights/?f=0#search;iti=AMS,ZYA_MAD,XOC,XTI_2017-04-02;tt=m;sel=AMSOPO0TP659-OPOMAD1TP1002;sc=b;eo=e the link "Boeken met TAP Portugal"
FF goes straight to the selection of flights, PM only displays TAP startscreen.
And https://www.google.nl/flights/?f=0#search;iti=AMS,ZYA_MAD,XOC,XTI_2016-12-07;tt=m;sel=AMSMUC0LH2309-MUCMAD1LH1800;sc=b;eo=e "Boeken met Lufthansa", same thing.

**Comment by wolfbeast** [comment]
I've tried the first suggested sequence and it works correctly in my current working copy of Pale Moon v27
![image1](https://cloud.githubusercontent.com/assets/3359132/19342440/312a263c-9132-11e6-85f6-e2d1389d3186.jpg)
![image2](https://cloud.githubusercontent.com/assets/3359132/19342442/3334694c-9132-11e6-9cdd-fab781963085.jpg)

**Comment by wolfbeast** [comment]
Assuming this is solved.
