### ISSUE TITLE
Fix build on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by CNAmira** [MoonchildProductions/Pale-Moon#538]
Apple has defined “kVK_RightCommand“ officially in macOS 10.12 SDK, it will generate error when building.
Apply this patch will fix it up and won't break building with previous OS X SDKs.

[macos1012.diff.zip](https://github.com/MoonchildProductions/Pale-Moon/files/491509/macos1012.diff.zip)

**Comment by wolfbeast** [comment]
What branch is this diff against? Maybe you can create a pull request instead?
