### ISSUE TITLE
Implement exportFunction()

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#54]
As requested by an add-on developer.
This touches on the fickle XPC part of JS, so care must be taken to not cause any security holes in the wrappers.

Ref thread: https://forum.palemoon.org/viewtopic.php?f=5&t=7015

Relevant BZ Bugs:
References resulting from a quick walk (not reading the extensive bug discussions):
Main implementation bug #877673 - MakeObjectPropsNormal like API that matches jetpack requirements better.
C.u.* implementation bug #930910 - Export helpers should be available on Components.utils
Dependency bug #901362 - Refactor nsJSUtils::EvaluateString to take an option object and optionally propagate exceptions.
Possible dependency bug #901162 - Move JS execution routines from nsIScriptContext to nsJSUtils
Sec bugs: bug #821809 bug #894956 (and likely a few others)

**Comment by janekptacijarabaci** [comment]
Hello.

IMHO: This suggestion should be addressed at the same time as the implementation: cloneInto(), createObjectIn()
https://blog.mozilla.org/addons/2014/04/10/changes-to-unsafewindow-for-the-add-on-sdk/

Thank you.

**Comment by wolfbeast** [comment]
Removing the bounty since this will need to be addressed a different way, and Tycho should solve this once extension compatibility settles to a stable framework.
