### ISSUE TITLE
Website issue - Google Cloud Platform Console

### ISSUE THREAD

**Issue by vaygr** [MoonchildProductions/Pale-Moon#541]
When clicking on some menu items under "Networking" or "Compute Engine" at https://console.cloud.google.com Pale Moon just returns no content inside that page.

The example is "Compute Engine" => "VM instances":
![shot-2016-09-28_5636](https://cloud.githubusercontent.com/assets/8810597/18930499/43d6f62c-8596-11e6-92b3-1c047b090812.png)

Some of them work fine though. According to debugger, there are JSON syntax errors (which are supposed to be there, it seems), but in chrome-like browsers (Vivaldi) it works fine.

Setup:
- Linux x64
- `26.5.0` (actually tried many different versions)
- compiled with gcc `4.6.4`

Also tried with no plugins enabled and fresh profile.

**Comment by wolfbeast** [comment]
Can you please check if the pre-release (currently alpha, beta coming soon) version of v27 solves this for you?

**Comment by vaygr** [comment]
Confirming, `v27 alpha 2` works flawlessly.

**Comment by wolfbeast** [comment]
Thanks, marking this solved by Tycho and closing, then.
