### ISSUE TITLE
Run (Desktop) Notification twice (and more) in a row does not work

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#544]
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/544#issuecomment-250967854:
OK, I'm sorry.

Edited...

---

**Tested on**
Pale Moon 26.5.0 (in the next version - **27.0.0b1** - it will be similar)
Windows 7/8
Ubuntu 16.04

**Confirmed on**
Windows 7/8 (does not work)

**Not confirmed on**
Ubuntu 16.04 (works)

**Steps to reproduce**

1) Open Scratchpad

2) Menu: "Environment-Browser"

3) Insert the code:

``` javascript
// 1, 2
var type = 1;

var repeat = 4;

var timeout = 500;

var count = 0;

function log(count) {
  window.setTimeout(function () {
    if (count == repeat) {
      // Position the window at the end of all alerts.
      var windows = Services.wm.getEnumerator("alert:alert");
      while (windows.hasMoreElements()) {
        var alertWindow = windows.getNext();
        if (alertWindow != window) {
          console.log(
              "Position the window at the end of all alerts. - alertWindow.screenY: " +
              alertWindow.screenY);
        }
      }
    }
  }, 1000);
}

if (type == 1) {
  var i = 1;
  var interval = window.setInterval(function () {
    new Notification("Hi! " + i.toString() + " " + (new Date).getTime(), {});
    count++;
    log(count);
    if (i++ == repeat) {
      window.clearInterval(interval);
    }
  }, timeout);
} else if (type == 2) {
  for (var i = 0; i < repeat; i++) {
    window.setTimeout(function () {
      count++;
      new Notification("Hi! " + count.toString() + " " + (new Date).getTime(), {});
      log(count);
    }, timeout);
  }
}
```

4) Run
5) The result:

(see https://github.com/MoonchildProductions/Pale-Moon/blob/27.0.0b1/toolkit/components/alerts/resources/content/alert.js#L135)

**Windows 7/8**

_[type == 1]_
It shows 4(repeat) notifications (from bottom to top). Also after rerunning.

In Browser Console:

```
Position the window at the end of all alerts. - alertWindow.screenY: 784
Position the window at the end of all alerts. - alertWindow.screenY: 708
Position the window at the end of all alerts. - alertWindow.screenY: 632
Position the window at the end of all alerts. - alertWindow.screenY: 556
```

_[type == 2]_
Nothing is displayed.
It works properly (only) with `repeat=1`.

In Browser Console:

```
Position the window at the end of all alerts. - alertWindow.screenY: -76
Position the window at the end of all alerts. - alertWindow.screenY: -152
Position the window at the end of all alerts. - alertWindow.screenY: -228
Position the window at the end of all alerts. - alertWindow.screenY: -304
```

**Ubuntu 16.04**

_[type == 1,2]_
It shows 4(repeat) notifications (from top to bottom). Also after rerunning.

In Browser Console:

```
Position the window at the end of all alerts. - alertWindow.screenY: 34
Position the window at the end of all alerts. - alertWindow.screenY: 110
Position the window at the end of all alerts. - alertWindow.screenY: 186
Position the window at the end of all alerts. - alertWindow.screenY: 262
```

---

See also [bug 1263155](https://bugzilla.mozilla.org/show_bug.cgi?id=1263155) ([1294332](https://bugzilla.mozilla.org/show_bug.cgi?id=1294332), [1306822](https://bugzilla.mozilla.org/show_bug.cgi?id=1306822)).

But still not repaired in Firefox.

**Comment by wolfbeast** [comment]
If you report issues, please provide a clear description. It's fine to link to BMO bugs for reference but the issue itself should be clearly described _here_.

**Comment by janekptacijarabaci** [comment]
The testing branch:
https://github.com/janekptacijarabaci/Pale-Moon/tree/_testBranch_notification_repeat

I guess it works like it should - but you need to think about it... as the label `Verification Needed`.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=862395
(noted for context - the call of notification needs to be found anywhere...)

**Comment by wolfbeast** [comment]
I've pulled the patch across from your tes branch and it seems to work as-intended in both modes (current release version indeed shows negative Y-values in the rapid-fire mode)

Please make a pull request so I can merge it in.

**Comment by wolfbeast** [comment]
Assuming this is solved.

**Comment by janekptacijarabaci** [comment]
@wolfbeast
I suggest reopening and adding the label `UXP-task`.

**Comment by wolfbeast** [comment]
it's not an issue, PRs can't be "reopened" -- but labeling will certainly help.
