### ISSUE TITLE
Update Tycho to libvpx 1.4

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Pale-Moon#546]
DAMN IT! `*`

`*`  Translation: Because of the re-base, we ran into issues with video due to libvpx being older in the target code base and updating libvpx to 1.4.* needs to be re-done for Tycho.

**Comment by Conan-Kudo** [comment]
You probably want to move to 1.6.0 while you're at it, since it has lots of bug fixes and performance improvements related to real-time encoding/decoding on lower-end systems (lacking SSSE3 and whatnot).

**Comment by wolfbeast** [comment]
Since you own this part of the code, @mattatobin, assigning you right off the bat.

**Comment by wolfbeast** [comment]
Created #547 for a potential update to 1.6 - let's focus this one on getting our Tycho lib version up to PM-release level first.

**Comment by mattatobin** [comment]
We are green on Windows and Linux
