### ISSUE TITLE
Update libvpx to 1.6

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#547]
We should consider updating libvpx to 1.6

**Comment by mattatobin** [comment]
Assign me.

**Comment by wolfbeast** [comment]
This needs some movement in the coming week or it won't make the milestone.

**Comment by mattatobin** [comment]
Mozilla has not yet consumed libvpx 1.6 and never bothered to do 1.5 and are still shipping 1.4.

I don't think pulling from Google manually is a wise course of action because apparently this new release is ABI incompatible with 1.4 so it may involve modifications to glue as opposed to a simple pull and update.

I will come back to this when Mozilla has landed it on their tree and consume from there.

In any event this is no longer a blocker for Tycho as it stands today.

**Comment by wolfbeast** [comment]
Check! Thanks for the research. Sounds like a plan.
(incompatible ABI yet again hm?)

**Comment by adisib** [comment]
This has landed on Mozilla btw, if you want to reconsider the on-hold status.

**Comment by mattatobin** [comment]
adsib and what is the justification.. It is ABI incompatible which means the glue will likely have to be updated if not rewritten. The code in Mozilla's tree likely has vs2015 reliant stuff.. and it will require build system research.

I am not sure it is worth it. Though, I would like to know..

**Comment by wolfbeast** [comment]
Considering the performance improvements in libVPX 1.5/1.6, this needs to be kept in mind for our users who want to play 4k video in the browser. That is, **if** we're not switching to ffvpx instead.

**Comment by trav90** [comment]
Using ffvpx on Windows would be nice and is something I would like to see happen, it's not something I am going to have time to work on myself. Got bigger fish to fry at the moment.

**Comment by wolfbeast** [comment]
As of now, UXP still uses 1.4.0 so considering this a wontfix.

**Comment by trav90** [comment]
UXP applications primarily use ffvpx which will be periodically updated from upstream. If my memory serves, libvpx primarily benefits WebRTC (which does not use ffvpx).

**Comment by mattatobin** [comment]
So do we need to even build libvpx in Pale Moon on UXP then?

**Comment by trav90** [comment]
Possibly not. I know that WebRTC is the primary user of libvpx, however I am not 100% sure that it is the only thing that uses it. Might be something to look into.
