### ISSUE TITLE
Windows installer puts files in wrong directory

### ISSUE THREAD

**Issue by Neil-P** [MoonchildProductions/Pale-Moon#552]
All the program's files go into Appdata\local instead of Program Files(x86).

**Comment by Neil-P** [comment]
I found out what caused this problem.  I had 26.4.0 installed along with 27a2.  To prevent accidentally running the wrong browser, I went into the 26 directory in Program Files(x86) and changed the name of Palemoon.exe to Palrmoon.ex_ so it would not run.  I then installed 27b1.

What I discovered was that 26 could not be uninstalled or overwritten without the palemoon.exe file.  I gave back its name and uninstalled 26,  I then reinstalled 27b1, and things are in the right place now.

**Comment by wolfbeast** [comment]
We can't possibly account for this kind of user action, sorry.

**Comment by Neil-P** [comment]
You could have prevented the "user action" if you had named the alpha executable something like "newmoon.exe" sted "palemoon.exe".
