### ISSUE TITLE
Scroll arrows and bars displayed on textboxes and buttons

### ISSUE THREAD

**Issue by xbeyond1** [MoonchildProductions/Pale-Moon#555]
Pale Moon x86 v27 beta on Win 7 x64 Ultimate

![2](https://cloud.githubusercontent.com/assets/22633092/19108418/74ad1b74-8af9-11e6-91f0-ff46dcd60d57.png)
![3](https://cloud.githubusercontent.com/assets/22633092/19108420/74df79c0-8af9-11e6-9d4a-780543a7c7d9.png)
![1](https://cloud.githubusercontent.com/assets/22633092/19108419/74cc5db8-8af9-11e6-84eb-0ac70808277e.png)

**Comment by wolfbeast** [comment]
Works for me; unable to reproduce...

![image1](https://cloud.githubusercontent.com/assets/3359132/19111779/a05acb7e-8b01-11e6-80fe-e6d9c43073f8.png)

**Comment by xbeyond1** [comment]
That's interesting...

I installed it on my old laptop (Win 7 x64); this time I did a clean install, and the issue exists on it as well.

**Comment by wolfbeast** [comment]
Indeed strange since I tested on Win7 x64 as well.

**Comment by wolfbeast** [comment]
Okay, I've been able to reproduce this. Looks like one of the fixes I already applied to -release need to be re-applied.

**Comment by wolfbeast** [comment]
Looks like the styling (fixed height + border-box padding + no rule to hide overflow) makes the button content size _just_ too large to fit in the element size, making it trigger scroll bars. I'm not entirely sure who's at fault here.

**Comment by wolfbeast** [comment]
Looks like the website is at fault. If we explicitly enable Firefox compatibility mode, it renders correctly. i don't know what they fall back to otherwise (chrome perhaps?), but the metrics of the button are off in that case.

**Comment by wolfbeast** [comment]
Considering this is a website issue, there's nothing to do one this end.
