### ISSUE TITLE
segfault in  0x000000000040f12e in arena_dalloc

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#56]
This crash has been happening every once in awhile since 7d69e63 but this is the first time I've been able to catch it.  ( Currently on 6088af8 ).

0  jemalloc_crash () at /home/themusicgod1/palemoon/Pale-Moon/memory/mozjemalloc/jemalloc.c:1590
1  0x000000000040f12e in arena_dalloc (ptr=<optimized out>, offset=<optimized out>) at /home/themusicgod1/palemoon/Pale-Moon/memory/mozjemalloc/jemalloc.c:4668
2  0x00007ffff3241b17 in ~nsCacheMetaData (this=0x7fffa1cd3df0, __in_chrg=<optimized out>) at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheMetaData.h:21
3  nsCacheEntry::~nsCacheEntry (this=0x7fffa1cd3d80, __in_chrg=<optimized out>) at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntry.cpp:53
4  0x00007ffff3257191 in nsMemoryCacheDevice::EvictEntry (this=0x7fffd8ebf750, entry=0x7fffa1cd3d80, deleteEntry=<optimized out>) at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsMemoryCacheDevice.cpp:365
5  0x00007ffff32572c6 in nsMemoryCacheDevice::EvictEntriesIfNecessary (this=0x7fffd8ebf750) at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsMemoryCacheDevice.cpp:409
6  0x00007ffff325763a in nsMemoryCacheDevice::OnDataSizeChange (this=0x7fffd8ebf750, entry=0x7fff380af240, deltaSize=11614) at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsMemoryCacheDevice.cpp:331
7  0x00007ffff3242d92 in nsCacheEntryDescriptor::RequestDataSizeChange (this=0x7fffa7b82790, deltaSize=deltaSize@entry=11614) at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntryDescriptor.cpp:277
8  0x00007ffff3243141 in nsCacheEntryDescriptor::nsOutputStreamWrapper::OnWrite (this=this@entry=0x7fff275eab50, count=count@entry=11614) at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntryDescriptor.cpp:1153
9  0x00007ffff32431da in nsCacheEntryDescriptor::nsOutputStreamWrapper::Write_Locked (this=0x7fff275eab50, buf=0x7fff275f5000 "\003\004\a\005\004\004", count=11614, result=0x7fffdcefedec) at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntryDescriptor.cpp:1231
10 0x00007ffff32436b0 in nsCacheEntryDescriptor::nsOutputStreamWrapper::Write (this=0x7fff275eab50, buf=0x7fff275f5000 "\003\004\a\005\004\004", count=11614, result=0x7fffdcefedec) at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntryDescriptor.cpp:1220
11 0x00007ffff3eb229e in nsInputStreamTeeWriteEvent::Run (this=0x7fff1fcfc4c0) at /home/themusicgod1/palemoon/Pale-Moon/xpcom/io/nsInputStreamTee.cpp:105
12 0x00007ffff3ec4499 in nsThread::ProcessNextEvent (this=0x7fffddca4c40, mayWait=<optimized out>, result=0x7fffdcefee9f) at /home/themusicgod1/palemoon/Pale-Moon/xpcom/threads/nsThread.cpp:626
13 0x00007ffff3e98422 in NS_ProcessNextEvent (thread=<optimized out>, thread@entry=0x7fffddca4c40, mayWait=mayWait@entry=true) at /home/themusicgod1/palemoon/Pale-Moon/obj-x86_64-unknown-linux-gnu/xpcom/build/nsThreadUtils.cpp:238
14 0x00007ffff3ec4f1e in nsThread::ThreadFunc (arg=0x7fffddca4c40) at /home/themusicgod1/palemoon/Pale-Moon/xpcom/threads/nsThread.cpp:264
15 0x00007ffff69ea291 in _pt_root (arg=0x7fffdcf6d260) at /home/themusicgod1/palemoon/Pale-Moon/nsprpub/pr/src/pthreads/ptthread.c:204
16 0x00007ffff7bc26aa in start_thread (arg=0x7fffdceff700) at pthread_create.c:333
17 0x00007ffff6ec6eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

(gdb) print *arena
$1 = {magic = 2491235620, lock = {__data = {__lock = 2, __count = 0, __owner = 6281, __nusers = 1, __kind = 3, __spins = 24, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = "\002\000\000\000\000\000\000\000\211\030\000\000\001\000\000\000\003\000\000\000\030", '\000' <repeats 18 times>, __align = 2}, stats = {mapped = 1224736768, npurge = 3088, nmadvise = 276099, purged = 1690106, committed = 298028, allocated_small = 659406424, nmalloc_small = 104762269, ndalloc_small = 97895078, allocated_large = 533954560, nmalloc_large = 2001750, ndalloc_large = 1952697}, chunks_dirty = {rbt_root = 0x7fff27500000, rbt_nil = {arena = 0x0, link_dirty = {rbn_left = 0x7ffff7eb40d0, rbn_right_red = 0x7ffff7eb40d0}, ndirty = 0, map = {{link = {rbn_left = 0x0, rbn_right_red = 0x0}, bits = 0}}}}, spare = 0x7fff2cf00000, ndirty = 111, runs_avail = {rbt_root = 0x7fff90300a28, rbt_nil = {link = {rbn_left = 0x7ffff7eb4120, rbn_right_red = 0x7ffff7eb4120}, bits = 0}}, bins = {{runcur = 0x7fff26995000, runs = {rbt_root = 0x7fff8bc00980, rbt_nil = {link = {rbn_left = 0x7ffff7eb4148, rbn_right_red = 0x7ffff7eb4148}, bits = 0}}, reg_size = 8, run_size = 4096, nregs = 500, regs_mask_nelms = 16, reg0_offset = 96, stats = {nrequests = 3928009, nruns = 1329, reruns = 109745, highruns = 737, curruns = 736}}}}
(gdb) info locals
chunk = <optimized out>
arena = 0x7ffff7eb4040
pageind = <optimized out>
mapelm = <optimized out>

Attempt to 'info variables' failed (gdb choked under the load after growing to about 6gb large)

Platform:
* Ubuntu 15.04

Compiled with:
* gcc (GCC) 4.9.2

**Comment by wolfbeast** [comment]
Being on a bleeding edge release of your OS, you should have compiled with --disable-jemalloc (prior to the commit mentioned, you were actually not using jemalloc)

**Comment by wolfbeast** [comment]
It actually did point out a place where a nullcheck would be wise - cache metadata is not guaranteed to have its buffer filled, so the destructor might try to release an unallocated pointer.

**Comment by themusicgod1** [comment]
Yeah I know, I thought I was (turned out I was not) --- I was compiling with --disbale-jemalloc as you typed that :)

**Comment by wolfbeast** [comment]
Unless you've run into this crash again since, I'd like to close this issue as resolved.

**Comment by themusicgod1** [comment]
ok
