### ISSUE TITLE
Update internal PDF viewer to work with Tycho platform.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#560]
Because the platform has changed, the PDF viewer and its glue will need to be updated (especially for security reasons no longer allowing the definition of cross-origin objects as a property on content objects or XRay wrappers).

**Comment by mattatobin** [comment]
We can appropriate it from Browser 38..

But frankly I think this needs to be just yanked out.. The Internal PDF viewer to date has barely if ever been maintained and it is disabled by default anyway.. Also, it is better served by real PDF applications which every platform has at their disposal.

Now would be the time to do it.
