### ISSUE TITLE
Crash when watching a video on imdb.com

### ISSUE THREAD

**Issue by xbeyond1** [MoonchildProductions/Pale-Moon#562]
Pale Moon 27b1 x86 on Windows 7 Ultimate x64

Crashes when starting any video on imdb.com.

**Comment by wolfbeast** [comment]
Hm, looks like new functionality always needs a second pair of eyes if it comes from Mozilla.

The crash is in the new feature introduced to use event.offsetX/Y on mouse events.
Should be a simple nullcheck fix t correct this.
