### ISSUE TITLE
SIGABRT do_abort *** Error in `%s': %s: 0x%s ***\n"

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#58]
A few times now, pale moon has crashed ( currently at 7f1168a not sure when it started ):

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffcdeff700 (LWP 5146)]
0x00007ffff6df5267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
0  0x00007ffff6df5267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
1  0x00007ffff6df6eca in __GI_abort () at abort.c:89
2  0x00007ffff6e38c53 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff6f511a8 "\*\*\* Error in \`%s': %s: 0x%s \*\*\*\n")
    at ../sysdeps/posix/libc_fatal.c:175
3  0x00007ffff6e41391 in malloc_printerr (ptr=<optimized out>, 
    str=0x7ffff6f4d2dd "corrupted double-linked list", action=1)
    at malloc.c:4965
4  _int_free (av=0x7ffff7184c00 <main_arena>, p=<optimized out>, have_lock=0)
    at malloc.c:3981
5  0x00007ffff6e4489c in __GI___libc_free (mem=<optimized out>)
    at malloc.c:2950
6  0x00007ffff340312c in ~nsCacheMetaData (this=0x7fffb9b472d0, 
    __in_chrg=<optimized out>)
    at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheMetaData.h:23
7  nsCacheEntry::~nsCacheEntry (this=0x7fffb9b47260, 
    __in_chrg=<optimized out>)
    at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntry.cpp:53
8  0x00007ffff34187a5 in nsMemoryCacheDevice::EvictEntry (
    this=0x7fffb80044c0, entry=0x7fffb9b47260, deleteEntry=<optimized out>)
    at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsMemoryCacheDevice.cpp:365
9  0x00007ffff34188da in nsMemoryCacheDevice::EvictEntriesIfNecessary (
    this=0x7fffb80044c0)
    at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsMemoryCacheDevice.cpp:409
10 0x00007ffff3418c4e in nsMemoryCacheDevice::OnDataSizeChange (
    this=0x7fffb80044c0, entry=0x7fffb87a00b0, deltaSize=2337)
    at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsMemoryCacheDevice.cpp:331
11 0x00007ffff34043a6 in nsCacheEntryDescriptor::RequestDataSizeChange (
    this=0x7fffb86cbfb0, deltaSize=deltaSize@entry=2337)
    at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntryDescriptor.cpp:277
12 0x00007ffff3404755 in nsCacheEntryDescriptor::nsOutputStreamWrapper::OnWrite (this=this@entry=0x8d732e0, count=count@entry=2337)
    at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntryDescriptor.cpp:1153
13 0x00007ffff34047ee in nsCacheEntryDescriptor::nsOutputStreamWrapper::Write_Locked (this=0x8d732e0, 
    buf=0x2143fe80 "q\324\002ɜG\327\354/\314\337Zyf^+\232\302\215\205\357\060\221\367\"\t\230\233`\273\246\067\242\066yf<is]㒗f:\310GD84\347\224\310h\323M\346\234be:F)\220\334\016\223\252e", count=2337, result=0x7fffcdefedec)
    at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntryDescriptor.cpp:1231
14 0x00007ffff3404cc4 in nsCacheEntryDescriptor::nsOutputStreamWrapper::Write
    (this=0x8d732e0, 
    buf=0x2143fe80 "q\324\002ɜG\327\354/\314\337Zyf^+\232\302\215\205\357\060\221\367\"\t\230\233`\273\246\067\242\066yf<is]㒗f:\310GD84\347\224\310h\323M\346\234be:F)\220\334\016\223\252e", count=2337, result=0x7fffcdefedec)
    at /home/themusicgod1/palemoon/Pale-Moon/netwerk/cache/nsCacheEntryDescriptor.cpp:1220
15 0x00007ffff407380c in nsInputStreamTeeWriteEvent::Run (this=0xc4c2d60)
    at /home/themusicgod1/palemoon/Pale-Moon/xpcom/io/nsInputStreamTee.cpp:105
16 0x00007ffff4085a07 in nsThread::ProcessNextEvent (this=0xf82de0, 
    mayWait=<optimized out>, result=0x7fffcdefee9f)
    at /home/themusicgod1/palemoon/Pale-Moon/xpcom/threads/nsThread.cpp:626
17 0x00007ffff4059990 in NS_ProcessNextEvent (thread=<optimized out>, 
    thread@entry=0xf82de0, mayWait=mayWait@entry=true)
    at /home/themusicgod1/palemoon/Pale-Moon/obj-x86_64-unknown-linux-gnu/xpcom/build/nsThreadUtils.cpp:238
18 0x00007ffff408648c in nsThread::ThreadFunc (arg=0xf82de0)
    at /home/themusicgod1/palemoon/Pale-Moon/xpcom/threads/nsThread.cpp:264
19 0x00007ffff6baa291 in _pt_root (arg=0xf83170)
    at /home/themusicgod1/palemoon/Pale-Moon/nsprpub/pr/src/pthreads/ptthread.c:204
20 0x00007ffff7bc26aa in start_thread (arg=0x7fffcdeff700)
    at pthread_create.c:333
21 0x00007ffff6ec6eed in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

ubuntu:  15.04
gcc: 4.9.2

**Comment by trav90** [comment]
I'm not the expert, but I notice several mentions of "malloc" in your log. What does your mozconfig look like?

I was experiencing segfaults/crashes when building Pale Moon using "disable-jemalloc" and "enable-optimize="-O3 -msse2 -mfpmath=sse"" in my mozconfig. Changing the O3 flag to O2 fixed it for me.

**Comment by themusicgod1** [comment]
themusicgod1@Hedy:~/palemoon/Pale-Moon$ cat .mozconfig
# This make file should be identical to the beta mozconfig, apart from the
# safeguard below
# . "$topsrcdir/browser/config/mozconfigs/linux64/common-opt"

# ac_add_options --enable-official-branding

# mk_add_options MOZ_PGO=1

ac_add_options --disable-tests
ac_add_options --disable-mochitests
ac_add_options --disable-jemalloc

# safeguard against someone forgetting to re-set EARLY_BETA_OR_EARLIER in
# defines.sh during the beta cycle
# export BUILDING_RELEASE=1

# . "$topsrcdir/build/mozconfig.common.override"

**Comment by wolfbeast** [comment]
Not specifying --enable-optimize will likely use system-defined defaults for gcc
If you use -O3 for that, then you're using an unstable optimization.

**Comment by themusicgod1** [comment]
reproduced on -Os

**Comment by Axiomatic-** [comment]
I just built Pale Moon from the latest git revision at the time of posting this, I have the ```-O2``` enabled, as well as ```-march=native```.

@wolfbeast as far as I know most consider O3 as stable as O2, however O3 is known to caused issues in programs that rely on undefined behaviour, or so I have read. I can reproduce the segmentation fault with the O3 switch as indicated by @trav90 however not the O2 switch. (Anyway it should be noted using O3 is unlikely to give any speed benefits to a program as big as Pale Moon, and probably only slow down booting up Pale Moon due to having a larger binary to load into memory.)

@themusicgod1 
```-march=native``` turns on -msse4.2 for my machine, and other switches however I am not experiencing any segfaults.  
```-march=native``` on my machine turns on the following:
```
-march=btver2 -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -msse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mbmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mno-rdrnd -mf16c -mno-fsgsbase -mno-rdseed -mprfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=2048 -mtune=btver2
```

I went ahead an tried to see if ```-mfpmath=sse``` would cause any segmentation faults, as far as I tested, no segmentation faults occurred. 

So it can likely be ruled to that the ```-Os```, and ```-O3``` switches are the cause of the segmentation fault. I will compile Pale Moon later with ```-Os``` to comfirm. As it stands now, for both speed, and stability ```-O2``` is probably the best switch.

**Comment by wolfbeast** [comment]
See also issue #63 

-Os is just as specialized a switch as -O3 is. Please try to compile with standard optimizations (-O, -O1 or -O2)

**Comment by trav90** [comment]
I believe this can be closed since it is a known issue when using -O3 and GCC 4.9 or higher.

**Comment by wolfbeast** [comment]
SGTM
