### ISSUE TITLE
Add an indicator for FF/PM extensions

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#585]
We should add an indicator for installed extensions in the add-on manager to indicate if extensions are Firefox extensions or if they are targeting Pale Moon natively. A simple "Firefox Orange" glyph or "Pale Moon Blue" glyph (dot) would suffice -- also to prevent unnecessary bitmaps and potential ™ issues for use of the Firefox logo.

**Comment by wsdfhjxc** [comment]
Would something like this be acceptable?

![test](https://cloud.githubusercontent.com/assets/20323160/19324074/0b255618-90c0-11e6-870b-c99c349476ac.png)

**Comment by wolfbeast** [comment]
@wsdfhjxc Absolutely! Although the indicators should be a tad larger.

**Comment by wsdfhjxc** [comment]
Should this cover only extensions or these indicators can be also shown for themes?

**Comment by wolfbeast** [comment]
It's only needed for extensions. Firefox themes are not going to be compatible, anyway.

**Comment by wolfbeast** [comment]
Verified.
