### ISSUE TITLE
The website minds.com isn't loading properly

### ISSUE THREAD

**Issue by xbeyond1** [MoonchildProductions/Pale-Moon#591]
I noticed that with Pale Moon 27b2 x86 the website https://www.minds.com is loaded with a 2-3 second delay. Sometimes even the browser becomes unresponsive. It didn't happen with the earlier versions.

**Comment by wolfbeast** [comment]
The site has an initialization delay for any browser version due to the rotating globe in the background.
Nothing that can be done about that, it's just a CPU-heavy effect initialization.
