### ISSUE TITLE
Make SVG favicons work reliably

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#596]
More and more sites offer favicons in SVG format in order to improve the experience for HiDPI display users. I think it'd be worthwhile for our HiDPI users to let them view these high-resolution favicons.

BMO: [366324](https://bugzilla.mozilla.org/show_bug.cgi?id=366324)

**Comment by wolfbeast** [comment]
If you look at the testcases in that bug, Pale Moon already displays the favicons of the cat...

**Comment by Lootyhoof** [comment]
As per [comment 56](https://bugzilla.mozilla.org/show_bug.cgi?id=366324#) this already sort of works, but only on the initial page load. If the page is reloaded, the favicon disappears.

**Comment by wolfbeast** [comment]
Right, the problem is caching.

**Comment by wolfbeast** [comment]
Simple fix -- sniff less, trust what servers say more.
