### ISSUE TITLE
"If you get failures below, please file a bug" in x86_64-noinit.c

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#60]
While mach building, got this message.  Not sure what exactly is telling me to file a bug, or if it's the first time I've seen it (there's a lot of warnings/messages on build)...but here it is:

 0:52.07 x86_64-noinit.c
 0:53.55 ===
 0:53.55 === If you get failures below, please file a bug describing the error
 0:53.55 === and your environment (compiler and linker versions), and use
 0:53.55 === --disable-elf-hack until this is fixed.
 0:53.55 ===
 0:53.55  0x0000000000000019 (INIT_ARRAY)         0x2073d0
 0:53.55 test-array.so: Reduced by 12096 bytes
 0:53.56 ===
 0:53.56 === If you get failures below, please file a bug describing the error
 0:53.57 === and your environment (compiler and linker versions), and use
 0:53.57 === --disable-elf-hack until this is fixed.
 0:53.57 ===
 0:53.57  0x000000000000000c (INIT)               0x3fe8
 
Linux Hedy 3.19.0-15-generic 15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 
Ubuntu 15.04 vivid GNU/Linux 
gcc (GCC) 4.9.2  
GNU ld (GNU Binutils for Ubuntu) 2.25 
currently at palemoon commit: 7f1168a 
.mozconfig:
ac_add_options --disable-jemalloc
ac_add_options --disable-mochitests
ac_add_options --disable-tests
ac_add_options --enable-optimize="-Os -msse4.2 -mfpmath=sse"
mk_add_options MOZ_MAKE_FLAGS="-j6"

**Comment by wolfbeast** [comment]
If it doesn't fail (and it doesn't seem to) then there's no issue.
