### ISSUE TITLE
Add support for DuckDuckGo POST Requests in omnibox, search box, and via right-click menu

### ISSUE THREAD

**Issue by hook54321a** [MoonchildProductions/Pale-Moon#605]

**Comment by wolfbeast** [comment]
There is no need for this. We use an HTTPS version of DDG search in the browser which prevents search leakage. In addition, POST searches have issues, mostly on the user-convenience side of things (impossible to share searches, can't use back button, etc.). In addition, it would preclude search suggestions (which are always a GET request).

**Comment by hook54321a** [comment]
Can't network managers still see the URLs you are visiting even if they use HTTPS?

**Comment by wolfbeast** [comment]
Nope. HTTPS is end-to-end encrypted. That includes the request URL.
