### ISSUE TITLE
Menu: "History" - "Recently Closed Tabs" and "Recently Closed Windows" - strange context menu

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#608]
See:
![1](https://cloud.githubusercontent.com/assets/2373486/19420753/83eb3448-93f2-11e6-83c2-ba6127fcec28.png)

After run the function "Open All in Tabs"... nothing happens.
Also (AFAIK)... It makes no sense in this Popup menu: "Recently Closed Windows".

**The same problem is also in Pale Moon stable (including the latest version 26).**

I don't know how it was intended...

**Comment by wolfbeast** [comment]
"Open all in tabs" should only be displayed on folders. It doesn't make sense on individual items because they don't contain anything.

**Comment by janekptacijarabaci** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1006989

I don't know if it suits your needs.

**Comment by wolfbeast** [comment]
The marked BZ bugs are in UXP, so assuming this solved by it.
