### ISSUE TITLE
Keep a running update of HSTS preload lists

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#62]
Pale Moon should keep updated with somewhat recent HSTS preload lists.

@squarefractal has offered to do this.

(responsibility tracking issue, leave open)

**Comment by squarefractal** [comment]
Documentation:

HSTS preload lists have moved from `security/manager/boot/src` to `security/manager/ssl`:
Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1164714

**Comment by wolfbeast** [comment]
I don't really care where Mozilla stores their HSTS preload lists in the tree ;)

**Comment by squarefractal** [comment]
That was for documentation purposes, mostly for personal use.

BTW, is there some reason git is apparently doing the merge two times? It seems very odd and pollutes the commit history.

**Comment by wolfbeast** [comment]
It happens when your PR merge and someone else's edits mid-air collide. e.g. I make a commit while you make a PR. I try to push the commit but it collides, so the branch on GitHub has to be pulled down before I can push. Anyone's local repo copy is an inherent separate branch from the remote that has to be re-merged if they are out of sync.

**Comment by TPS** [comment]
#61, #69, #74, #82, #85, &c (just to pick 5 that auto-completed :wink:) were all not mentioned here....  If this issue isn't tracking, is there a reason to keep it open?

**Comment by wolfbeast** [comment]
It's an on-going task.

**Comment by wolfbeast** [comment]
Looks like we need a new person to pick this up and provide updates.

**Comment by TPS** [comment]
> Looks like we need a new person to pick this up and provide updates.

@wolfbeast I suppose https://github.com/squarefractal/encryptedweb/issues/6#issuecomment-239602542 is a related problem. 😭

**Comment by wolfbeast** [comment]
I don't mind if people get busy with other stuff but they should not let us hanging in limbo.
Communication is key.

**Comment by trav90** [comment]
I looked at this tonight, and Mozilla has changed the format of the file containing the HSTS preload list (actually made it more efficient). But as a result we can no longer simply pull the updated files from Mozilla as-is (i.e., we'll need to go though the files and make any relevant changes manually).

This will not be an issue with Tycho (and I'll volunteer to keep this updated since no one else has), but it's going to take a _lot_ of time to update this for Pale Moon -release.

**Comment by wolfbeast** [comment]
I think it'd be better if we stop depending on Mozilla for updates for this. We have all the tools in the tree that we can run in the xpcshell (I'll give that a poke today) to generate our own list by actually querying the chromium project's HSTS domain list and making https requests from the supplied script and checking responses. Especially since we obviously missed a good number of updates in the interim since the maintainer dropped off the face of the moon.

**Comment by wolfbeast** [comment]
Looks like anyone with a reliable internet connection can do this. All it takes is one command and some time to iterate over the domains in the list which can just sit in a command window until it's done.

I ran this from the Windows command prompt from `$objdir\dist\bin` without issues:
````
xpcshell.exe [path to]\getHSTSPreloadlist.js [real path to]\nsSTSPreloadlist.inc
````
**Note:** the path to the .inc has to be the path to the in-tree source file (it reads existing entries to merge with a downloaded list and update)
Checking and updating took about an hour and a half with conservative settings as-present in the script. this can probably be tweaked for more concurrent lookups to speed things up.

For *nix it'll likely need to use `run-mozilla.sh` (closer to what's in the header of the .js file)

**Comment by trav90** [comment]
Agreed. I think we should stop using Mozilla's updates as well and use our own in-tree tools. I've got xpcshell pulling an updated list for Tycho now. Guess I should have done my homework a little better.

Going forward, I still volunteer to keep this up to date.

**Comment by trav90** [comment]
It looks like the in-tree getHSTSPreloadlist.js is using an old copy of the chromium source code. Comparing the tool in our current tree and the one in Tycho:

Current pulls updates from https://src.chromium.org/chrome/trunk/src/net/http/transport_security_state_static.json  --  This URL points to revision 300703 which hasn't been updated in 2 years.

Tycho pulls from the URL https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json -- clicking on the log for this file reveals that it was updated only 6 days ago.

I'm going to update this for PM26 and submit a pull request once it's done.

**Comment by squarefractal** [comment]
I apologize for not having communicated my unavailability here.
It is unlikely that I will be able to resume work on things such as this due to other priorities; thus, I should be removed as an assignee from this bug.

**Comment by wolfbeast** [comment]
Thanks for the clarification. We can get this covered by someone else.

**Comment by wolfbeast** [comment]
@trav90 Since you volunteered above, I've assigned you to this issue now.

**Comment by wolfbeast** [comment]
I'll run the Feb 2017 one since you're probably busy enough already.

**Comment by wolfbeast** [comment]
As an aside, we also have HPKP preloading going on in our tree which has a (very similar) update method.
As long as we support that (I'm not sure if we should... potential web breakage there) it needs to also be updated:

- use `genHPKPStaticPins.js`
- `default-ee.der` can be found in `\security\manager\ssl\tests\unit\tlsserver\`
- `PreloadedHPKPins.json` is in the same dir as the script
- `StaticHPKPins.h` is in the same location as the .inc for HSTS
````
// 3. run `[path to]/run-mozilla.sh [path to]/xpcshell \
//                                  [path to]/genHPKPStaticpins.js \
//                                  [absolute path to]/PreloadedHPKPins.json \
//                                  [absolute path to]/default-ee.der \
//                                  [absolute path to]/StaticHPKPins.h
````

**Comment by wolfbeast** [comment]
I'll run the May 2017 one since you're probably busy enough already.

**Comment by trav90** [comment]
I actually checked this morning and upsteam doesn't appear to have updated the HSTS list since the last time I did it.

**Comment by wolfbeast** [comment]
You mean the Google upstream? Because Mozilla has pretty much religiously been running this script about every day XD

**Comment by trav90** [comment]
Yeah Google upstream (I don't pay any attention to Mozilla's HSTS list). Though obviously I was mistaken and there were some updates since I last did this (sorry about that).

**Comment by wolfbeast** [comment]
Like I said you are probably busy enough already. No need to be sorry!

Even if upstream would have no updates, it still serves to run the script to check the base list and check the servers on it to be at an accurate HSTS status for each to include in the preload list.

**Comment by wolfbeast** [comment]
I'll be re-generating this list from scratch, using just the HSTS source list and not our existing include file, since it seems there are a good handful of stale entries in there that are being carried forward each time.

**Comment by wolfbeast** [comment]
Hmm I wanted to run this one last time since it's 2 months stale but for some reason xpcshell just exits immediately without an error.

**Comment by trav90** [comment]
I'll update this either tonight or in the morning depending on when I get home.

**Comment by trav90** [comment]
xpcshell seems to be working here and the generation script is currently running. I'll submit a PR in the morning.

**Comment by wolfbeast** [comment]
No further updates of this list for Tycho.
