### ISSUE TITLE
Youtube does not work reliable with MSE and Webm activated

### ISSUE THREAD

**Issue by Lennium** [MoonchildProductions/Pale-Moon#628]
Steps: 

1)Activate MSE function for Webm
2) Open Video for example https://www.youtube.com/watch?v=imBT7LGgNug
3) start video and manually draw the video playback timeline back to start

Result: video runs without sound or does partly not load.

MSE in combination with Webm should be deactivated from start, as it is more than clear that it does not work reliable with the new Pale Moon 27 versions.

MSE with MP4 works flawless.

**Comment by wolfbeast** [comment]
MSE for WebM is disabled by default for a reason. We are aware of this problem on YouTube which is exactly _why_ it's off by default.
