### ISSUE TITLE
The context menu on the page vs. downloads (several problems) - part 1

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#629]
Tested on Windows, Pale Moon 27.0.0a1 - 27.0.0b3

---
## `Save Page As`

Displaying incorrect file (*.htm) size (it's size of other files: e.g. "last" image on the page).

**Steps to reproduce**
1. Go to: http://www.palemoon.org/
2. Right-click context menu on the page: `Save Page As`
3. The result (e.g.): `2,6 KB -> twitter.png` instead `23,6 KB -> The Pale Moon Project homepage.htm`

![1](https://cloud.githubusercontent.com/assets/2373486/19828923/bf795dec-9dd3-11e6-9625-17c5d15bbd8d.png)

---

See also #630

**Comment by wolfbeast** [comment]
Can you please split this up in one issue per separate issue entry? It's impossible to track otherwise.

**Comment by janekptacijarabaci** [comment]
__It's associated with larger change (downloads)...__

Last bad: 38.0a1 (2015-02-17)
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Built from https://hg.mozilla.org/mozilla-central/rev/09f4968d5f42

First good: 38.0a1 (2015-02-18)
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Built from https://hg.mozilla.org/mozilla-central/rev/9696d1c4b3ba

Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=09f4968d5f42&tochange=9696d1c4b3ba

**Comment by wolfbeast** [comment]
Likely culprit that needs to be ported to our FE:
Bug 1127867 - Use the new back-end property to get the size of downloads asynchronously.

**Comment by wolfbeast** [comment]
Clearing assignment -- Lack of time.

**Comment by Lorienna** [comment]
Introduced by:

Last good: [26.0a1 (2013-08-21)](https://hg.mozilla.org/mozilla-central/rev/b2486721572e) + [files](https://archive.mozilla.org/pub/firefox/nightly/2013/08/2013-08-21-05-01-36-mozilla-central/) => First bad: [26.0a1 (2013-08-22)](https://hg.mozilla.org/mozilla-central/rev/2ab07dec6404) + [files](https://archive.mozilla.org/pub/firefox/nightly/2013/08/2013-08-22-03-02-04-mozilla-central/) => [Pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=b2486721572e&tochange=2ab07dec6404)

**Comment by wolfbeast** [comment]
Assuming this is addressed in UXP. If still a problem, please open a new issue there.
