### ISSUE TITLE
The context menu on the page vs. downloads (several problems) - part 2

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#630]
Tested on Windows, Pale Moon 27.0.0a1 - 27.0.0b3

---
## `Save Image As`/`Save Link As`, `Save Page As`

It can't delete from history - using the context menu: `Remove From History`

_**Never:**_

**Steps to reproduce**
1. Go to: `about:...`
2. Right-click context menu on the page:
   `Save Image As` (e.g. `about:logopage`)
   `Save Link As` (e.g. `about:support` - the link `support website`)
3. The result: ...nothing happens.

![2](https://cloud.githubusercontent.com/assets/2373486/19829141/92febebe-9dd9-11e6-8a95-3a6794faf9aa.png)

_**Sometimes:**_

**Steps to reproduce**
1. Go to: http://www.palemoon.org/
2. Right-click context menu on the page:
   `Save Page As`
3. The result: ...nothing happens.

![3](https://cloud.githubusercontent.com/assets/2373486/19828930/d745cc76-9dd3-11e6-8e9d-67ecdf80ea28.png)

__Edited (Jun 30, 2017):__

Following functions are not started...:

`toolkit/components/places/nsNavHistoryResult.cpp`:

?
↓
`nsNavHistoryQueryResultNode::OnVisit()`
[nsNavHistoryResult.cpp#L2372](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/toolkit/components/places/nsNavHistoryResult.cpp#L2372)
↓
`rv = InsertSortedChild(addition);`
[nsNavHistoryResult.cpp#L2481](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/toolkit/components/places/nsNavHistoryResult.cpp#L2481)
↓
`nsNavHistoryQueryResultNode::InsertSortedChild()`
[nsNavHistoryResult.cpp#L1350](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/toolkit/components/places/nsNavHistoryResult.cpp#L1350)
↓
`return InsertChildAt(aNode, 0);`
[nsNavHistoryResult.cpp#L1356](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/toolkit/components/places/nsNavHistoryResult.cpp#L1356)
or
`return InsertChildAt(aNode, position);`
[nsNavHistoryResult.cpp#L1382](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/toolkit/components/places/nsNavHistoryResult.cpp#L1382)
↓
`nsNavHistoryQueryResultNode::InsertChildAt()`
[nsNavHistoryResult.cpp#L1303](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/toolkit/components/places/nsNavHistoryResult.cpp#L1303)
↓
`NOTIFY_RESULT_OBSERVERS(result, NodeInserted(this, aNode, aIndex));`
[nsNavHistoryResult.cpp#L1339](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/toolkit/components/places/nsNavHistoryResult.cpp#L1339)
↓

`browser/components/downloads/content/allDownloadsViewOverlay.js:`

`NodeInserted()`
[allDownloadsViewOverlay.js#L1259](https://github.com/MoonchildProductions/Pale-Moon/blob/27.3.0_Release/browser/components/downloads/content/allDownloadsViewOverlay.js#L1259)

...and this event (`nodeInserted`) will never/sometimes happen.

---

See also #629

**Comment by Lorienna** [comment]
Could these bugs possibly be related here?

`Bug 991965` - _Context menu items of Downloads Panel be invalidated after onDownloadMouseOut:_
https://bugzilla.mozilla.org/show_bug.cgi?id=991965

`Bug 1115964` - _Context menu items like "Remove from history" and "Open containing folder" fail to work, and the download loses its highlight:_
https://bugzilla.mozilla.org/show_bug.cgi?id=1115964

**Comment by janekptacijarabaci** [comment]
IMHO: I do not think it is related.

**Comment by Lorienna** [comment]
@janekptacijarabaci, do you think this issue is a Pale Moon-specific one?

**Comment by janekptacijarabaci** [comment]
@Lorienna
Maybe. Given a possibly inconsistent rebase.

**Comment by Lorienna** [comment]
@janekptacijarabaci, then hypothetically, should (then non-existent) patch for `Bug 991965` above or another similar fix have been applied first before rebasing in order to avoid further broadening of the regression, maybe?

**Comment by Lorienna** [comment]
<dl><dd>What do you think of the following ranges?<br><br>

<table>
    <tr>
        <td align="center" width="400"><b>Regressed by:</b></td>
        <td align="center" width="400"><b>Fixed by:</b></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td align="center"><a href="https://bugzilla.mozilla.org/show_bug.cgi?id=816254">Bug 816254</a><br>Add logging to Downloads Panel<br><a href="https://hg.mozilla.org/mozilla-central/rev/b16497a56714">Changeset 122092</a></td>
        <td align="center"><a href="https://bugzilla.mozilla.org/show_bug.cgi?id=842185">Bug 842185</a><br>"Remove From History" doesn't work<br><a href="https://hg.mozilla.org/mozilla-central/rev/673dd484f5b5">Changeset 122222</a></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td align="center">Last good: <a href="https://hg.mozilla.org/mozilla-central/rev/7bd555e2acfa">21.0a1 (2013-02-16)</a><br>First bad: <a href="https://hg.mozilla.org/mozilla-central/rev/c4de6de47382">21.0a1 (2013-02-17)</a><br><a href="https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=7bd555e2acfa&tochange=c4de6de47382">Pushlog</a></td>
        <td align="center">Last bad: <a href="https://hg.mozilla.org/mozilla-central/rev/0acbd06d48a9">21.0a1 (2013-02-18)</a><br>First good: <a href="https://hg.mozilla.org/mozilla-central/rev/e8f8a3f6f1f6">21.0a1 (2013-02-19)</a><br><a href="https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=0acbd06d48a9&tochange=e8f8a3f6f1f6">Pushlog</a></td>
    </tr>
</table>
</dd></dl>

**Comment by Lorienna** [comment]
Thank you for your kind work, Janek.

Haven't seen any issues.

**Comment by janekptacijarabaci** [comment]
IMHO: It's fixed.
