### ISSUE TITLE
Disable CSS Errors logging by default to improve performance

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#631]
By default CSS parser sends hundreds of errors to the Error Console for almost every page. This info is completely useless for the regular browsing and only wastes CPU time and memory. Such load can be quite significant, just open Error Console for evidences.

Setting [layout.css.report_errors](http://kb.mozillazine.org/Layout.css.report_errors) default to false will disable CSS Errors logging. The devs should turn it on only for actual purposes.

**Comment by wolfbeast** [comment]
This causes issues with expected behavior and extensions like Stylish no longer being able to check for errors.
I'm reverting this for the time being; maybe it should be a performance enhancing option in Pale Moon commander?

**Comment by janekptacijarabaci** [comment]
Tag https://github.com/stylish-userstyles/stylish/issues/303
