### ISSUE TITLE
Changed md5sum of release tarball

### ISSUE THREAD

**Issue by cwilling** [MoonchildProductions/Pale-Moon#651]
For a 1st Oct download of archive/26.5.0_Release.tar.gz, I recorded an md5sum of d7578845894fb58470b54d569615d32f. The same download today has an md5sum of 5556f1a1d668a0d1d71387a6e66b53ca.

What gives? Has the tarball been repackaged or perhaps interfered with or what ...?

**Comment by wolfbeast** [comment]
Download from where?

**Comment by wolfbeast** [comment]
I'm assuming here you're talking about the tarballs on GitHub. 
These are generated by GitHub based on tags in the source tree -- we have no control over this, and it's quite possible GitHub changed something in their packaging process and/or repackaged it with different parameters.

**Comment by cwilling** [comment]
Yes, downloaded from https://github.com/MoonchildProductions/Pale-Moon/archive/26.5.0_Release.tar.gz both times.
I understand about the possibility that something changed in GitHub's backend procedures but how to confirm that is the actual cause of the differences? Some of the alternative possibilities are not very attractive.

**Comment by wolfbeast** [comment]
You can always unpack both tarballs and run a diff. if there is a difference there, I'd appreciate it if you could let me know exactly.

**Comment by cwilling** [comment]
I have both tarballs. The only difference seems to be:
chris@d6:/tmp$ diff -r PM1 PM2
diff -r PM1/Pale-Moon-26.5.0_Release/addon-sdk/source/python-lib/cuddlefish/_version.py PM2/Pale-Moon-26.5.0_Release/addon-sdk/source/python-lib/cuddlefish/_version.py
12c12
< git_refnames = " (tag: 26.5.0_Release, v26_Dev)"
---
> git_refnames = " (tag: 26.5.0_Release)"
(where PM1 is the earlier version, PM2 is the current version).

Pretty insignificant after all (but that's good).

**Comment by wolfbeast** [comment]
Yup, well that's because GitHub apparently recreates the archives when branch pointers cause head tags to move, then. (v26_Dev is the branch tip, which eventually moved off of that tagged commit)
