### ISSUE TITLE
Ctrl+Arrows navigation

### ISSUE THREAD

**Issue by sergeevabc** [MoonchildProductions/Pale-Moon#656]
7x64, 27b3

1. Open https://workflowy.com/demo/embed/
2. Jump between words using common shortcuts Ctrl+Arrows.
3. You cannot go behind the last word in sentence with Ctrl+RightArrow.

[Brief IRC analysis](https://a.cocaine.ninja/vfpzas.png) suggests that it could be a Windows-only issue.

**Comment by wolfbeast** [comment]
Regression caused by pref flip.
