### ISSUE TITLE
gmx.de (german free email provider) non-functional with Pale Moon

### ISSUE THREAD

**Issue by katzenpapst** [MoonchildProductions/Pale-Moon#658]
As a web developer, it baffles me how GMX even managed to pull that off, but here we are: Everything works with Firefox, but if you log in into a GMX account with Pale Moon, you just get a white page with a grey border. I tried user agent spoofing, addon disabling, but even with a freshly-created user profile it's still the same.

Is there some ridiculous ancient legacy feature which you dropped in PM? Is there some other way except the user agent to tell Pale Moon and Firefox apart? There might be some other "enterprise" websites/"web applications" which break in Pale Moon out there which do the same thing, whatever it is...

Using Pale Moon Version: 26.5.0 (x86) on Windows 7 x64

**Comment by wolfbeast** [comment]
It's impossible to tell what exactly GMX does with their interface, but obviously it is a combination of expected things that simply don't work -- likely a combination of undocumented features, non-standard implementation quirks and let's not forget draft "specs" that are in no way even a recommendation to implement yet.

At this point I can only suggest you try the beta of v27; our platform and JS engine update there probably satisfies whatever GMX (and affiliated other webmail sites) requires. Let me know if v27 works for you.

**Comment by wolfbeast** [comment]
No further response received. closing as incomplete.

**Comment by katzenpapst** [comment]
Sorry, totally forgot about this. Apparently the problem was my profile all along (which I migrated from firefox and had it for quite a long time). No idea what exactly was broken, but a) I found a second site which didn't work (hermes package tracking) and b) everything worked when I created a clean profile and migrated just the relevant data to it.

**Comment by wolfbeast** [comment]
All right, thanks for the follow-up!

**Comment by ivanbistrovic** [comment]
I have to bump this topic as I have the problem with gmx.com provider. I am using dev version (29.0.0a3) of Palemoon. After login it always open a mobile version of the interface, so it has very basic functionality. Not sure exactly after which version it started to happen, maybe in the last two releases. In Firefox it functions normal.

**Comment by wolfbeast** [comment]
Please don't "bump topics" on an issue tracker. This has been closed in 2016 -- for first troubleshooting please use the [forum](https://forum.palemoon.org) and if there _is_ in fact a browser issue here then a new issue should be opened after confirmation.
