### ISSUE TITLE
Multi-DPI setup: popup menus appear on wrong monitor with custom devpixels/px.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#672]
As reported on the forum:

Operating System: Xubuntu 16.04
Pale Moon 26.4.0 (x64)
GPU: Intel HD Graphics 4600
Monitors: 3840x2160 (Primary) 1280x1024 (Secondary)

With the about:config setting layout.css.devPixelsPerPx set to any value between 1 and 2 (1.3 in my case), while right clicking a window on a secondary monitor, the context menu appears on the primary monitor.

Bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=959682

STR:
1: Open a Pale Moon window on secondary monitor
2: Navigate to a web page
3: Use right mouse click

Expected Result:
The context menu appears on the secondary monitor

Actual Result:
The context menu appears on the primary monitor

====
According to the referenced bug this also occurs on Windows at least, so probably cross-platform.

Prerequisites:
- Multiple monitors
- Multiple DPI settings per monitor
- Device pixels/px not set to automatic (-1), and in the range between 1.0 inclusive and 2.0 inclusive

**Comment by Lootyhoof** [comment]
Related bugs (mentioned in above BMO but linked here for reference):

[1240533](https://bugzilla.mozilla.org/show_bug.cgi?id=1240533), (possibly) [1247335](https://bugzilla.mozilla.org/show_bug.cgi?id=1247335)

1240533 looks to be the culprit, unknown if 1247335 will be related.

**Comment by Gpower2** [comment]
I gave it a try, but the code base that these BMO are based on is quite different for current PaleMoon's code base. Especially nsDocShell.cpp is quite different, as well as nsWindow.h which contains new namespaces. So I don't know if this change can be incorporated in the current codebase.

**Comment by wolfbeast** [comment]
Thanks for trying! It seems like this will need a new implementation then. Unfortunately for the reporters this is very much a corner case so it won't be on anyone's to-do list any time soon...

**Comment by Gpower2** [comment]
I am afraid that we will find a lot of these problems ahead of us, since newer Mozilla Code cannot be built with VS2013 and is using newer C++ features requiring VS2015.
Perhaps at some point it would be worth it to make the current code base VS2015 compatible, although I know how big this task is...

**Comment by wolfbeast** [comment]
This has very little to do with which VS version is in use, I think, and more to do with mindless refactoring.
