### ISSUE TITLE
Pale Moon 27 beta 3 doesn't process Zoho Writer document properly

### ISSUE THREAD

**Issue by truthnews-de** [MoonchildProductions/Pale-Moon#681]
What it says in the headline. You can only view it, not even edit it. With pale moon 26.5.0 it works.

My system is ubuntu.

URL: https://docs.zoho.com

**Comment by wolfbeast** [comment]
See if making the useragent "firefox compatible" helps, and kindly report back.
[Options|Edit -> Preferences] -> Advanced -> tab general -> User Agent Mode
Set to `Firefox Compatibility`

If it fixes the issue, please also report this problem to Zoho.

**Comment by wolfbeast** [comment]
@truthnews-de Please report if Firefox Compat fixes this problem?

**Comment by truthnews-de** [comment]
Hi, with pale moon 27.0.2 there is no issue, thanks.

**Comment by wolfbeast** [comment]
Great! thank you. Closing.
