### ISSUE TITLE
Pale Moon 26.5.0 doesn't display twitter video

### ISSUE THREAD

**Issue by truthnews-de** [MoonchildProductions/Pale-Moon#683]
See http://twitter.com/video/

Also not resolved in PM 27b3, only some twitter videos work there, but not the ones mentioned in the above link.

**Comment by SJ-Diamond** [comment]
As written in your other bug report, as the Pale Moon team is creating some new media format reader this will most likely fix your playback issues then.

**Comment by wolfbeast** [comment]
Twitter has removed direct MP4 videos and is currently limiting itself to MSE and HLS-playlist "video" which doesn't work (a playlist is not a playable media format).
For v26.* certainly not a consideration to work around.
