### ISSUE TITLE
per-extension update disable?

### ISSUE THREAD

**Issue by joey04** [MoonchildProductions/Pale-Moon#686]
I was wondering if I could disable update checking for specific extensions and found this comment in browser/app/profile/firefox.js#L180
`// Symmetric (can be overridden by individual extensions) update preferences.
// e.g.
// extensions.{GUID}.update.enabled`

But attempting it for specific extensions (whether GUID is number or text) doesn't work. Still checks PM and AMO sites.
If it's not implemented please remove the comment.

I'm using v26.5 but the same comment is in both that and the master repo.

**Comment by wolfbeast** [comment]
The update is disabled. The _checking for_ an update is not.

**Comment by joey04** [comment]
Ah, thanks for clarifying.
