### ISSUE TITLE
Flash Player issue (Tycho)

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#696]
At YouTube, when using Flash player, I'll run into problems sometimes.
First, the player controls will disappear, then the videos simply stop (the picture freezes).
Seems to happen mostly when playing videos in a small window.
I think I've been able to prevent it from happening a few times, simply by keeping the player controls visible all the time.
The problem never occurs when using Pale Moon v26.5.0.

(Pale Moon v27.0.0b3,x64 / Windows 8.1 Pro / Adobe Flash Player v23.0.0.207)

**Comment by wolfbeast** [comment]
The Adobe Flash plugin v23 is known to be problematic. it's an unstable PoS.
As far as I know there is nothing we can do about this on the browser side, and I suggest you go back to an older Flash plugin version, e.g. the last v18 ESR

**Comment by THEtomaso** [comment]
Like I pointed out, this particular issue doesn't affect PM v26.5.0.
I've been using v26.5.0 (install version) and v27.0.0b3 (portable) side by side for a long time now, and I've never run into this problem with v26.5.0!

**Comment by THEtomaso** [comment]
Adobe Flash Player v24.0.0.186 has been released today.
The changelog looks promising:

> * Flash Player quits unexpectedly while playing (4195719)

Let's see if it behaves better than the previous version!

**Comment by wolfbeast** [comment]
Fingers crossed!

**Comment by THEtomaso** [comment]
So far, so good! :)

**Comment by THEtomaso** [comment]
Unfortunately, the bug is still present. :(

**Comment by THEtomaso** [comment]
Good news is that with Flash Player v24.0.0.186, the freezing doesn't happen very often anymore.
In fact, it has only frozen once for me this far, so Adobe has definitey looked into this issue!

**Comment by wolfbeast** [comment]
Closing this issue then -- clearly an Adobe problem.

**Comment by THEtomaso** [comment]
I think perhaps someone should take another look at this issue, because the theory about it being a Direct3D11 compatibility issue in Flash Player might not be correct.
The problem still occurs when using Adobe Flash Player v25.0.0.127, and like I pointed out in the forum, setting layers.prefer-d3d9 to true and disabling H/W acceleration doesn't help at all:
https://forum.palemoon.org/viewtopic.php?f=4&t=14199&p=102146#p102099
Also, only YouTube seems to be affected.
When using Flash Player at other sites, the videos play just fine!

**Comment by wolfbeast** [comment]
And exactly what additional info do you have that helps us here?
- disabling H/W acceleratin... in flash or in the browser?
- layers.prefer-d3d9 is only a *preference*, not a hard setting. In addition that only deals with the compositing layers, not necessarily with drawing surfaces used by plugins (which are overlaid).

**Comment by THEtomaso** [comment]
> * disabling H/W acceleratin... in flash or in the browser?

Both.

--

> if it's just YT, then it's likely a specific problem with their player, not Flash itself -- and you could even think that it'd be on purpose to push HTML5 instead

Well, it only happens with PM27.*
I haven't been able to reproduce this issue with SeaMonkey, or any other Pale Moon version besides v27.*.

--

> why are you using Flash for YT in Pale Moon 27, exactly?

It's just a much better player to me, quality wise, like I mentioned here:
https://forum.palemoon.org/viewtopic.php?f=4&t=14199&start=20#p102185
