### ISSUE TITLE
Status bar options : progress color not used

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#697]
In Status Bar Options, the ability to customize page load progress color in the address bar no longer functions. it will always use the OS color.

**Comment by janekptacijarabaci** [comment]
Ad `Progress: Address Bar - Color`...

> "the OS color"

=>
https://github.com/MoonchildProductions/Pale-Moon/blob/27.0.0_Release/browser/themes/shared/statusbar/dynamic.css#L12

It also does not work:
- `Status: Address Bar - Status color`
- `Progress: Status Bar - Color`
- `Download: Progress color for active downloads`
- `Download: Progress color for paused downloads`

This CSS (the entire file `dynamic.css`) is not "rewritable".

**Comment by wolfbeast** [comment]
... wow, that's some strange design by the original author. I'll have to have a look at working around that somehow.
@mattatobin Looks like the S4E design requires being able to write to its own install location, that's a problem for having it included as-is in the browser core.

Possible solutions off the top of my head:
- Dynamically set the styles from JS
- Copy `dynamic.css` to profile and use that as write location

**Comment by janekptacijarabaci** [comment]
Sorry if I wrote it vaguely...

> This CSS (the entire file  dynamic.css ) is not "rewritable".

=> The rules are rewritten, but the elements remain with the initial value.

Maybe it's just a trifle...

**Comment by wolfbeast** [comment]
It was a simple matter of having a double-defined overlay. Kudos @janekptacijarabaci for spotting that one!

**Comment by janekptacijarabaci** [comment]
Three cheers for the full DevTools :-)
