### ISSUE TITLE
Let's Encrypt Cert  is Untrusted (PM27)

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#699]
https://decentraleyes.org/test

**Comment by wolfbeast** [comment]
Certificate chain is incomplete. That's a website administration mistake.

**Comment by JustOff** [comment]
Sorry for disturbing you in the release day, but why all is ok under Chrome, Firefox & even Edge?

**Comment by wolfbeast** [comment]
It'll be fine in Pale Moon as well, IF you have visited a site with a complete chain before on the same profile.
They are missing 1 or more intermediate certs.
