### ISSUE TITLE
Twitch playback broken with the release version of 27

### ISSUE THREAD

**Issue by SJ-Diamond** [MoonchildProductions/Pale-Moon#701]
https://forum.palemoon.org/viewtopic.php?f=15&p=97602#p97602

Someone posted that the Twitch playback in HTML5 mode is broken in version 27 - can confirm.

Beta 3 Twitch playback was possible, but now in the release version the thread opener and i get the following error message:

"Error while decoding media resource."

Perhaps an issue with the new added code for media playback?

**Comment by wolfbeast** [comment]
Duplicate, see #702
