### ISSUE TITLE
relocation R_X86_64_PC32 against protected symbol

### ISSUE THREAD

**Issue by awissu** [MoonchildProductions/Pale-Moon#704]
Hi!
I bumped into errors, when tried to build rpm in OBS:

> [  780s] /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: ../../xpcom/components/nsComponentManager.o: relocation R_X86_64_PC32 against protected symbol `end_kPStaticModules_NSModule' can not be used when making a shared object

See: https://build.opensuse.org/package/live_build_log/home:awissu:branches:network/palemoon/openSUSE_Leap_42.2/x86_64

Version palemoon: 27.0.0

**Comment by wolfbeast** [comment]
Which linker are you using? bfd? If so, try gold.

**Comment by awissu** [comment]
OK.
I switched to gold. 
The problem is solved now.
