### ISSUE TITLE
Update ICU to later version

### ISSUE THREAD

**Issue by awissu** [MoonchildProductions/Pale-Moon#705]
From openSUSE rpmlint...
```
[  812s] I: Statement might be overflowing a buffer in strncat. Common mistake:
[  812s]    BAD: strncat(buffer,charptr,sizeof(buffer)) is wrong, it takes the left over size as 3rd argument
[  812s]    GOOD: strncat(buffer,charptr,sizeof(buffer)-strlen(buffer)-1)
[  812s] E: palemoon bufferoverflowstrncat /home/abuild/rpmbuild/BUILD/Pale-Moon-27.0.0_Release/intl/icu/source/tools/pkgdata/pkgdata.cpp:282:87
```

**Comment by wolfbeast** [comment]
Unfortunately the source code location is given post preprocessing so it doesn't point to the right location in the actual source.
Can you find out exactly which statement it complains about?

**Comment by wolfbeast** [comment]
Actually, we should probably just update ICU to a later version. It's all in third-party code.

**Comment by awissu** [comment]
Problem temporarily solved.
Use "--with-system-icu".

**Comment by wolfbeast** [comment]
OK for a workaround but our in-tree ICU should be updated. making this issue about that.

**Comment by wolfbeast** [comment]
We'll be updating ICU to 58.2 (Unicode 9).
Taking this myself as it requires some patch juggling which needs some prior experience.
