### ISSUE TITLE
Awful font rendering (aliasing) on Pale Moon 27

### ISSUE THREAD

**Issue by MingcongBai** [MoonchildProductions/Pale-Moon#713]
Running Pale Moon 27 on Linux results in quite horrible font rendering, here below is my font matching info:

```
jeffbai@G5-AOSC [ ~ ] $ fc-match Sans
NotoSansCJK-Regular.ttc: "Noto Sans CJK SC" "Regular"
jeffbai@G5-AOSC [ ~ ] $ fc-match Serif
NotoSansCJK-Regular.ttc: "Noto Sans CJK SC" "Regular"
jeffbai@G5-AOSC [ ~ ] $ fc-match Monospace
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
```

And here is to show the font rendering situation (compare to the About dialogue itself, which obviously is a normal GTK+ window):

![snapshot10](https://cloud.githubusercontent.com/assets/5006263/20614644/9e277020-b296-11e6-98af-66ea6ae4f870.png)

You should be able to see that the fonts on the web page appears quite awfully aliased, illegible in some cases, while the about dialogue shows reasonable font rendering.

**Comment by wolfbeast** [comment]
adding the output from help -> troubleshooting information may help to diagnose.
Looks like content is simply not anti-aliased like it should be.

**Comment by MingcongBai** [comment]
Here's its content...

```json
{
  "application": {
    "name": "Pale Moon",
    "version": "27.0.0",
    "buildID": "20161123112322",
    "userAgent": "Mozilla/5.0 (X11; Linux ppc64; rv:3.0) Gecko/20100101 Goanna/20161123 PaleMoon/27.0.0",
    "supportURL": "http://www.palemoon.org/support/",
    "numTotalWindows": 4,
    "numRemoteWindows": 0,
    "remoteAutoStart": false
  },
  "experiments": [],
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "accessibility.typeaheadfind": true,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.cache.disk.capacity": 358400,
    "browser.download.importedFromSqlite": true,
    "browser.places.smartBookmarksVersion": 4,
    "browser.search.useDBForOrder": true,
    "browser.startup.homepage_override.mstone": "3.0.2",
    "browser.startup.homepage": "https://aosc.io/",
    "browser.startup.homepage_override.buildID": "20161123112322",
    "extensions.lastAppVersion": "27.0.0",
    "font.name.serif.x-western": "Noto Serif",
    "font.name.monospace.x-western": "Source Code Pro",
    "font.name.sans-serif.x-western": "Noto Sans",
    "media.mediasource.webm.enabled": true,
    "media.mediasource.enabled": true,
    "network.cookie.prefsMigrated": true,
    "places.database.lastMaintenance": 1480098487,
    "places.history.expiration.transient_current_max_pages": 104858,
    "plugin.importedState": true,
    "privacy.sanitize.migrateFx3Prefs": true,
    "storage.vacuum.last.places.sqlite": 1480098487,
    "storage.vacuum.last.index": 0
  },
  "lockedPreferences": {},
  "graphics": {
    "numTotalWindows": 4,
    "numAcceleratedWindows": 0,
    "windowLayerManagerType": "Basic",
    "windowLayerManagerRemote": false,
    "numAcceleratedWindowsMessage": [
      ""
    ],
    "adapterDescription": "nouveau -- Gallium 0.4 on NV43",
    "adapterVendorID": "nouveau",
    "adapterDeviceID": "Gallium 0.4 on NV43",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVersion": "2.0 Mesa 12.0.4",
    "driverDate": "",
    "webglRenderer": "nouveau -- Gallium 0.4 on NV43",
    "info": {
      "AzureCanvasBackend": "cairo",
      "AzureSkiaAccelerated": 0,
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "cairo"
    }
  },
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 1
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.12",
      "version": "4.12"
    },
    "NSS": {
      "minVersion": "3.19.5.0 Basic ECC",
      "version": "3.19.5.0 Basic ECC"
    },
    "NSSUTIL": {
      "minVersion": "3.19.5.0",
      "version": "3.19.5.0"
    },
    "NSSSSL": {
      "minVersion": "3.19.5.0 Basic ECC",
      "version": "3.19.5.0 Basic ECC"
    },
    "NSSSMIME": {
      "minVersion": "3.19.5.0 Basic ECC",
      "version": "3.19.5.0 Basic ECC"
    }
  },
  "userJS": {
    "exists": false
  },
  "extensions": []
}
```

**Comment by trav90** [comment]
Can't reproduce here. The most obvious differences between my box and yours is I do not use nouveau and I have not modified the three "font.name." prefs listed above.

**Comment by MingcongBai** [comment]
> Can't reproduce here. The most obvious differences between my box and yours is I do not use nouveau and I have not modified the three "font.name." prefs listed above.

Also it's a PPC64 (PowerMac G5), that explains the Nouveau part - as I am essentially stick with it (quite salty about it, as I have been battling with it for months to this point just to get it working semi-decently).

Anyhow, is there any apparent issue with my build config then? You can find it [here](https://github.com/AOSC-Dev/aosc-os-abbs/tree/staging/extra-web/palemoon/autobuild). I don't think graphics driver is really relevant here, as everything worked as normal.

The reason why I changed the font is to see if it's a fontconfig matching error (which I suspected initially, turned out negative).

**Comment by trav90** [comment]
Don't build with any system libs. That is known to cause problems.

**Comment by MingcongBai** [comment]
I guess I would try and build a fully bundled version then... Soon.

**Comment by trav90** [comment]
That is my recommendation.

**Comment by MingcongBai** [comment]
But with that said, did you guys really change anything around freetype, harfbuzz, or anything of that nature (that of controlling font rendering)?

**Comment by MingcongBai** [comment]
@trav90 Tried disabling system Cairo and Harfbuzz and nothing happened...

**Comment by trav90** [comment]
> But with that said, did you guys really change anything around freetype, harfbuzz, or anything of that nature (that of controlling font rendering)?

I know some of these components got updated with Tycho. Have to check commit history to see which ones.

**Comment by wolfbeast** [comment]
Most of these components got updated, as well as the surrounding code.
Not sure if *nix/PPC will get this pref or honor it, but try gfx.font_rendering.cleartype.always_use_for_content = true?

**Comment by MingcongBai** [comment]
That option does not exist on *Nix...

Also I should point out that this also exists on my AMD64 machine, running on Intel graphics.

**Comment by wolfbeast** [comment]
Hmm. Are there any specific custom configurations you do that are common to both machines that could influence this? On the AMD machine, did you also build from source or are you using the supplied binaries?

**Comment by MingcongBai** [comment]
They used the same mozconfig, see my comment above. And yes they are both
source builds...

2016年11月29日 01:26，"Moonchild" <notifications@github.com>写道：
