### ISSUE TITLE
About dialogue should not be resizable

### ISSUE THREAD

**Issue by MingcongBai** [MoonchildProductions/Pale-Moon#714]
If resized, the background will be stretched according to the width of the about dialogue, while the content of the about dialogue/window did not expand with the resized dialogue.

(Also, I do believe that we could use a more HD background on the about dialogue, I am trying to see what I can do.)

**Comment by wolfbeast** [comment]
The about dialog is marked as non-resizable. If it still is, then your window manager doesn't seem to honor the window setting?

**Comment by MingcongBai** [comment]
I am using TWin, a fork of KWin3 by Trinity Desktop Environment... And I can still reproduce this on my Plasma 5 if I remembered correctly.

**Comment by trav90** [comment]
Confirmed reproducible on Plasma 5.

**Comment by wolfbeast** [comment]
I can't really help here. if the XUL indicates non-resizable, then that is passed up to the WM - whether the WM honors this or not would be out of our control; it is however possible there's a bug in the widget code here that doesn't pass the correct flags up to the WM or similar, but that's out of my depth (I've never worked with X11 windows/widgets)

**Comment by MingcongBai** [comment]
Firefox 50 has the same issue. Oh well, I guess I should bug them about it instead...

But meanwhile, I think I could start working on a more high definition picture for the About Dialogue - I will see what I can do.
