### ISSUE TITLE
Strange requests from fresh Pale Moon installation

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#715]
From https://forum.palemoon.org/viewtopic.php?f=3&t=13846

I see following requests sent from fresh Pale Moon installation:

https://addons.palemoon.org/integration/addon-manager/internal/update?reqVersion=2&id={972ce4c6-7e08-4474-a285-3208198ce6fd}&version=27.0.0&maxAppVersion=27.0.0&status=userEnabled&appID={8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}&appVersion=27.0.0&appOS=WINNT&appABI=x86_64-msvc&locale=en-US&currentAppVersion=27.0.0&updateType=112&compatMode=normal

https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id={972ce4c6-7e08-4474-a285-3208198ce6fd}&version=27.0.0&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=27.9&compatMode=normal

http://ocsp.digicert.com/

http://blocklist.palemoon.org/27.0.0/blocklist.xml

https://www.palemoon.org/update/27.0.0/WINNT_x86_64-msvc/update.xml

Is this ok?

**Comment by wolfbeast** [comment]
That's all perfectly normal.
extension update check (and forward for external extensions to AMO), https OCSP certificate check for AMO, blocklist update check for extension/driver blocklist update, and finally Pale Moon application check update.

**Comment by JustOff** [comment]
But http://blocklist.palemoon.org/27.0.0/blocklist.xml returns 404 and I have no extension with id {972ce4c6-7e08-4474-a285-3208198ce6fd} installed, it's clean install. Is it ok too?

**Comment by wolfbeast** [comment]
Yes it's fine. there's no blocklist update yet for 27.0.0, it will just ignore it for 404
{972ce4c6-7e08-4474-a285-3208198ce6fd} is the default theme.

**Comment by JustOff** [comment]
Thank you for the detailed reply!
