### ISSUE TITLE
woff2: only latin and digits, cyrillic letters shown by system font

### ISSUE THREAD

**Issue by SLiTaz-Linux** [MoonchildProductions/Pale-Moon#716]
Solution: to switch U.A. from 'gecko compat' to 'native' in advanced prefs.

Some weird websites like dou.ua still uses systemfont even with woff2 disabled and override for fonts.googleapis...(like in 26.3.1 to 26.5), but please don't care it's google's troubles. I am just let you know that default settings is bad. sorry for my english.

**Comment by wolfbeast** [comment]
Default settings are fine. "Native" will break many more sites.
