### ISSUE TITLE
Reset general.useragent.locale on upgrade?

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#718]
Given the the number of problems occurring during the upgrade from 26 to 27 may be it makes sense to simply reset general.useragent.locale to en-US?

**Comment by wolfbeast** [comment]
The problems only occur if people themselves (or through an extension) have disabled compatibility checking. I verified the normal update procedure and it works just fine -- the initial check will inform people the language packs are incompatible, and they are disabled as a result. All of that works exactly as it should.

It may be something to consider in the future if we do have another big milestone release that needs a big change for language packs, but I'd rather find a better solution to prevent breakage in that case, like, moving away from this "replacement" setup for l10n and having English strings at all times as an internal fallback.

**Comment by JustOff** [comment]
Yes, I'm aware the cause of this problem (users side fault), I just thought that locale reset is simple and has no side effects. And I think it's not too late to implement it now to avoid such problem for updates from 26 to 27, that are still ongoing.

**Comment by wolfbeast** [comment]
It's too late for 27.0.1 that will be released in less than 2 hours.
Most people who are going to update have already updated by now (or will do so today or tomorrow) -- There really isn't anything to consider for this cycle any longer.

**Comment by JustOff** [comment]
During testing 27.2->27.3 update I found that LP not always updates automatically even if auto update of extensions is enabled. I predict a lot of questions will arise on the forum again so I think we finally should implement auto recovery.
