### ISSUE TITLE
Enable MSE + MP4 by default on Linux

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#723]
This depends on #719 to be completed.

Hook up MSE and H.264 video after we drop GStreamer for video and have reliable HD video decoding.

**Comment by trav90** [comment]
OK, looks like Mozilla's comments on various BMO bugs indicating extra work needed done to hook up HSE/FFmpeg were either incorrect or the changes were done elsewhere. In my testing today on YouTube, MSE/MP4 worked fine using our FFmpeg code in it's current state. So I'm going to morph this into a "Enable MSE + MP4 on Linux by default" issue.

**Comment by trav90** [comment]
MSE is enabled by default on Linux in PR #799!
