### ISSUE TITLE
Couple of problems with Openload videos

### ISSUE THREAD

**Issue by SJ-Diamond** [MoonchildProductions/Pale-Moon#725]
https://forum.palemoon.org/viewtopic.php?f=15&t=13933

Can confirm some problems which the thread opener experiences. Skipping in the video timeline makes the video load for half en eternity.. depending on which part of the video timeline you are skipping.

Also, sometimes i lost audio when having MSE checkboxes activated.

Happens with other Openload videos too. Tested of course in 27.0.1

Tested also with 26.5 - loading is way faster no matter at which time i skip and the audio issues are also not present. 

And there is also an entry in the error console, perhaps this can help if posting it?

Timestamp: 28.11.2016 22:45:20
Warning: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
Source File: https://openload.co/assets/js/video.min.js
Line: 21

Also can confirm that HTML5 videos are randomly freezing, for example that here: http://www.animestream.it/e5034-Macross_Delta-06 - if i skip a bit into the video

**Comment by SJ-Diamond** [comment]
Some more tests, that video issues also exist in Beta 3 of 27.0.0 - Mp4 streams do not work reliable at all in Pale Moon 27 - 27.0.1

**Comment by wolfbeast** [comment]
Please indicate exactly what environment you are experiencing this in. Linux?

**Comment by Zetsbo** [comment]
I'm also experiencing this, I'm currently on windows, it doesn't work.

**Comment by wolfbeast** [comment]
> Also, sometimes i lost audio when having MSE checkboxes activated.
At default settings? WebM for MSE is disabled by default for loss-of-audio reasons.

**Comment by wolfbeast** [comment]
The macross video is a direct-stream MP4 that also causes issues in the internal standalone player when trying to search, so it's likely a bad encoding lacking key frames -- not the browser's fault.

Checking the video of the original post it seems to be encoded the exact same way (only 1 channel audio, etc.) -- "fixing" those kinds of errors are really beyond what a web browser should be doing. People need to encode stuff properly.

**Comment by wolfbeast** [comment]
Perhaps this is also related to or a dup of #841 -- the behavior seems to be similar with delays after seeking.

**Comment by wolfbeast** [comment]
I've built a binary with the latest patches in and apart from the one mentioned on the forum being a PITA because of popunders and slow servers, the videos play fine after seeking on the latest trunk (to be published in the next unstable).

Considering this resolved by the continued work on the media back-end and the recent fixes in particular.
