### ISSUE TITLE
Touchscreen issue

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#728]
Don't know how useful this bug report will be, because I can't give you access to the site in question.
But anyways, here's the problem:

At work, when out in the field, we use Windows tablets to access a online map service, and there's a problem when using Pale Moon..

Here's a screenshot:
http://i.imgur.com/AHQIBbs.jpg

The problem occurs when using the touch gesture to zoom in/out on the map.
The toolbars that I've marked with red are also affected by the gesture (gets smaller/bigger when zooming), although they should NOT be!

Below are the codes that reveal themselves when inspecting the toolbars, using the dev. tools.

Toolbar 1 (the blue area):

> <span style="z-index:-1;" class="posA t0 l0 b0 r0 ofH">
      <a title="Gemini Portal" href="/portal/VA/" tabindex="-1"><img alt="Gemini Portal" src="/portal/VA/Images/LogoGeminiPortal.png"></a>
        
    </span>

Toolbar 2 (the grey area in the top right corner):
`<div class="background"></div>`

Changing User Agent Mode doesn't help either.

(Pale Moon v27.0.1,x64 / Windows 8.1 Pro)

**Comment by THEtomaso** [comment]
After further testing, it seems that Firefox is also affected by this issue.
In other words; there's a fair chance that the problem lies with the site code.
I've sent a mail to the service provider, informing them of this.

**Comment by wolfbeast** [comment]
In light of your comment, marking this invalid.

**Comment by THEtomaso** [comment]
This issue was fixed somewhere in between FF v54.0.1 and v55.0, so I guess that makes it a valid bug.
Perhaps someone could take a look at the commits and see if anything stands out?

**Comment by wolfbeast** [comment]
Please run a `mozregression --find-fix` to find a nightly range -- "somewhere between FF54.0.1 and FF55.0" encompasses way too many code changes. 
See: http://mozilla.github.io/mozregression/

**Comment by THEtomaso** [comment]
I have a hard time getting my head around the version numbering, when it comes to comparing FF's release branch with its nightly branch.
But after messing around with mozregression-gui today, I was finally able to narrow it down to this:
**Last bad: Firefox v47.0a1 (2016-01-30)
First good: Firefox v47.0a1 (2016-01-31)**
:)

**Comment by THEtomaso** [comment]
I found the changelog for **FF v47.0a1 (2016-01-31)** here:
http://forums.mozillazine.org/viewtopic.php?f=23&t=2987525/
Four of the listed fixes are labeled "[Core:Panning and Zooming]", so this must be it!

**Comment by THEtomaso** [comment]
I don't know much about this stuff, so I wonder about the fixes that I linked to in my previous post..
Are they applicable to Pale Moon, or is Electrolysis actually required for proper touchscreen support?

**Comment by wolfbeast** [comment]
> is Electrolysis actually required for proper touchscreen support?

Absolutely not. e10s isn't required for anything.

**Comment by THEtomaso** [comment]
> e10s isn't required for anything.

Good to hear. :)
I only ask because I found this post at Bugzilla, which describes the exact same issue that I've reported:
https://bugzilla.mozilla.org/show_bug.cgi?id=1204250#c0
Further down, there are a couple of post pointing out that e10s needs to be enabled for it to work properly.

**Comment by wolfbeast** [comment]
Assuming this is fixed in UXP looking at the version range mentioned.
