### ISSUE TITLE
CSP blocked neterror page doesn't show

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#738]
If a frame-ancestor directive blocks the load of a frame's content, the corresponding neterror page isn't shown.

This is likely because Mozilla moved these errors into Firefox code from docshell code, and we don't have the corresponding FE page to show, as a result.
Because it was -also- refactored at the same time, it may be a little difficult to figure out what is going to be needed to reinstate these errors properly in the platform/toolkit code, instead.

Likely related: https://bugzilla.mozilla.org/show_bug.cgi?id=982347
Potentially also related: https://bugzilla.mozilla.org/show_bug.cgi?id=1106132

**Comment by wolfbeast** [comment]
It's actually simpler.
Mindless renaming of cspFrameAncestorBlocked to cspBlocked caused a mismatch in overrides/appstrings.properties in our FE with the docshell xhtml.

**Comment by JustOff** [comment]
Pushed to CrowdIn
