### ISSUE TITLE
Offline data is saved without asking

### ISSUE THREAD

**Issue by sergeevabc** [MoonchildProductions/Pale-Moon#739]
7x64, PM 27.0.2

1. Open Options-Advanced-Network and make sure [ x ] Tell me when a website asks to store…
2. Visit https://stackedit.io/editor and type a few random lines.
3. Re-open O-A-Network and be surprised with 2.9 Mb of fresh offline data w/o asking.

**Comment by THEtomaso** [comment]
SuperA posted a solution back in January, on how to always deny offline data:
https://forum.palemoon.org/viewtopic.php?f=3&t=10420#p74482
..but I'm uncertain as to whether this actually works or not.

**Comment by sergeevabc** [comment]
@wolfbeast, what’s your take on that?

**Comment by wolfbeast** [comment]
My take is that this is a simple matter of Mozilla having renamed the platform pref (fnar).
`about:config`, set `offline-apps.allow_by_default` to `false`

To solve this in the UI, the pref needs to be properly hooked up to the checkbox.

**Comment by wolfbeast** [comment]
In this day and age, allowing this by default is a sane default. Offline web application file storage is limited by a quota so there won't be any serious abuse possible (after the quota is exceeded the user will always be warned).

Hooking up the pref is 15 minutes of work at most, I'll have a commit later to fix this in the UI.

**Comment by wolfbeast** [comment]
Looking into this a bit more, it actually hasn't changed, the only difference is that `offline-apps.allow_by_default` is now present and platform-enabled, which short-circuits the prompt. So, it's allowed by default; in that case, the prompt will never be shown, regardless of what you choose in the Options, which is... rather confusing, to say the least ;)

**Comment by wolfbeast** [comment]
As a workaround for this particular bug, flipping the pref is good enough (it works as-intended then).
I'll open an enhancement issue to actually make this a clearer design in the preferences UI.
