### ISSUE TITLE
Location bar suggests too much

### ISSUE THREAD

**Issue by sergeevabc** [MoonchildProductions/Pale-Moon#740]
7x64, PM 27.0.2

1. Open Options-Privacy-Location bar and set [Bookmarks].
2. Type something in location bar, it still uses history to make suggestions.

**Comment by wolfbeast** [comment]
Looks like a dumb typo >.<

**Comment by wolfbeast** [comment]
Actually, no, it's correct (enabled/disabled is returned which gets put into the pref when writing the behavior value)
Needs some more research why `browser.urlbar.default.behavior` is ignored.
This worked in v26.*, correct?

**Comment by sergeevabc** [comment]
> This worked in v26.*, correct?
Yes.

**Comment by wolfbeast** [comment]
OK thanks, marking as regression.

**Comment by wolfbeast** [comment]
Tycho toolkit refactoring issue.
Previous prefs are no longer used -> `browser.urlbar.suggest.*` is the new color.
_Cue Wizard of Oz music_
