### ISSUE TITLE
Internal updater: UAC elevation for all accounts

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#744]
When using the internal updater check ~~on a timer~~, the update process on a **standard account** fails because it fails the "UserCanElevate" check in v27.0.*.

Updater log:
````
AUS:SVC Creating UpdateService
AUS:SVC Checker:getUpdateURL - update URL: https://www.palemoon.org/update/27.0.0/WINNT_x86-msvc/update.xml
AUS:SVC gCanCheckForUpdates - able to check for updates
AUS:SVC Checker: checkForUpdates, force: false
AUS:SVC Checker:getUpdateURL - update URL: https://www.palemoon.org/update/27.0.0/WINNT_x86-msvc/update.xml
AUS:SVC Checker:checkForUpdates - sending request to: https://www.palemoon.org/update/27.0.0/WINNT_x86-msvc/update.xml
UTM:SVC TimerManager:notify - notified @mozilla.org/updates/update-service;1
AUS:SVC Checker:onLoad - request completed downloading document
AUS:SVC Checker:getUpdateURL - update URL: https://www.palemoon.org/update/27.0.0/WINNT_x86-msvc/update.xml
AUS:SVC Checker:onLoad - number of updates available: 1
AUS:SVC getCanApplyUpdates - testing write access C:\Users\Moonchild\AppData\Local\Moonchild Productions\Pale Moon\Pale Moon\update.test
AUS:SVC getCanApplyUpdates - windowsVersion = 6.1
AUS:SVC getCanApplyUpdates - on Vista, userCanElevate: false
AUS:SVC getCanApplyUpdates - testing write access C:\Program Files (x86)\Pale Moon\update.test
AUS:SVC getCanApplyUpdates - unable to apply updates. Exception: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.create]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/components/nsUpdateService.js :: getCanApplyUpdates :: line 582"  data: no]
AUS:SVC UpdateService:_selectAndInstallUpdate - the user is unable to apply updates... prompting
AUS:SVC getCanApplyUpdates - testing write access C:\Users\Moonchild\AppData\Local\Moonchild Productions\Pale Moon\Pale Moon\update.test
AUS:SVC getCanApplyUpdates - windowsVersion = 6.1
AUS:SVC getCanApplyUpdates - on Vista, userCanElevate: false
AUS:SVC getCanApplyUpdates - testing write access C:\Program Files (x86)\Pale Moon\update.test
AUS:SVC getCanApplyUpdates - unable to apply updates. Exception: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.create]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/components/nsUpdateService.js :: getCanApplyUpdates :: line 582"  data: no]
AUS:UI gUpdates:onLoad - setting current page to startpage manualUpdate
````

**Comment by wolfbeast** [comment]
This may not necessarily be a bug; if a user isn't part of the admin group they can't elevate their own account and will have to enter credentials for an admin account instead -- that's not part of the Pale Moon updater check and never was.
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=747390

**Comment by LimboSlam** [comment]
Question @wolfbeast: 

I have been locked out of my admin account (lost admin privileges apparently) on my Vista machine. I have contacted my admin adviser and he wont be able to assist me with this issue. So could there be an easier way to update or uninstall Pale Moon for us users who don't have an admin account or privileges? Not to mention, knowing how strict Vista is with UAC, could accommodations be made?  

I will continue to use the zip versions of Pale Moon until a solution is worked out for me.  

Thanks!

**Comment by wolfbeast** [comment]
@LimboSlam No, there is no way for a non-admin to change files in the $programfiles folder. If you're locked out, then you can't update the browser. That is an essential feature of using privileges and user accounts in Windows. This has not changed since Vista and the code mentions Vista because it has not been touched in any significant way since.

**Comment by LimboSlam** [comment]
Ah I see, thanks again.

**Comment by wolfbeast** [comment]
This would be an enhancement to think about. The main problem is that we have to be very careful not to get users into an "update loop" when they can't elevate to install the update.
