### ISSUE TITLE
Support libxul-sdk builds again

### ISSUE THREAD

**Issue by cbehan** [MoonchildProductions/Pale-Moon#746]
It looks like you've rewritten PaleMoon to be against Mozilla Central's 38-ESR instead of 24-ESR. Thanks! They went into XUL-killing mode a bit before that so this brings in some regressions too. Specifically, bug 1038639 removed the --with-libxul-sdk option. If describing our separately versioned Goanna as a maintained fork of XUL is going to make any sense, we need this option back. Developers targeting this platform should be able to use Goanna on the system instead of building it every time.

The first patch I'm attaching simply reverts bug 1038639. This is not enough because it also has conflicts with bugs 1036894 and 1077148. I'm attaching a second patch which works around those on my system but it might be too hackish to work for everyone.

http://pastebin.ca/3744239
http://pastebin.ca/3744240

The second patch edits mozbuild so that it treats USE_LIBS the same as OS_LIBS for a libxul-sdk build. But it also edits goanna_templates.mozbuild which I don't understand enough. Specifically I don't know the difference between mozglue and xpcomglue and why it matters to link against the static ones instead of shared.

**Comment by wolfbeast** [comment]
Right now we're still in the process of fixing up our platform after this massive rewrite, and will have to work on a re-base of FossaMail and potentially Mobile, so I'm afraid a pre-built XULRunner SDK is lower priority. I haven't even checked if XULRunner as a target application builds currently (it might not, in which case that needs fixing first).

**Comment by cbehan** [comment]
Building xulrunner worked on Linux before I tried --with-libxul-sdk. But I'm fine with waiting. I hope the other rebases go well.

**Comment by wolfbeast** [comment]
Xulrunner stubs should remain possible; libxul-sdk for embedding is likely too much of a stretch goal for our team so I'll be closing this.
