### ISSUE TITLE
Broken url bar text rendering after Pale Moon 26 -> 27 update with FT Graphite Glow theme

### ISSUE THREAD

**Issue by Pulfer** [MoonchildProductions/Pale-Moon#758]
See screenshot, it describes everything:

![screenshot](https://cloud.githubusercontent.com/assets/4058218/20998374/0936e112-bd59-11e6-8985-2288ad0218b7.png)

How to reproduce:

1. Install FT Graphite Glow theme to Pale Moon 27.0.2
[ft-graphite-glow.xpi.zip](https://github.com/MoonchildProductions/Pale-Moon/files/638471/ft-graphite-glow.xpi.zip)
2. Go to any URL.
3. Start typing another URL in url bar. New text is rendered over old text.

**Comment by trav90** [comment]
See https://forum.palemoon.org/viewtopic.php?f=45&t=14082

**Comment by Pulfer** [comment]
It works, thanx :-)
