### ISSUE TITLE
Clarify UI for off-line data storage (and enable by default)

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#760]
The current check-box UI in Advanced -> Network for asking the user to allow off-line storage is in conflict with the "always allow" preference that bypasses this selection (see #739).

What we need to do here is make this from a check-box into a 3-state choice:
1. *Allow by default* (similar to default 27.0.0 release, never prompts except for over-quota)
2. *Ask me every time* (similar to default 26.* and prior)
3. *Don't allow by default* (similar to default 26.* and prior with the prompt disabled)

The new **default** should be to **always allow** (because it's the sane choice for 2016/2017 and Web 2.0/3.0).

For the different states:
1. `offline-apps.allow_by_default` = `true` and `browser.offline-apps.notify` = `true`
1. `offline-apps.allow_by_default` = `false` and `browser.offline-apps.notify` = `true`
1. `offline-apps.allow_by_default` = `false` and `browser.offline-apps.notify` = `false`

These preferences should both be synced (only notify is synced currently).

**Comment by THEtomaso** [comment]
More than those other options, I'd much rather like to see an option to always DENY offline data, without asking!
This option was missing in v26.* and prior as well.

**Comment by wolfbeast** [comment]
No, it wasn't missing, just not explicitly stated. If you disabled the "ask" option (checkbox) then it would by default deny. The v26 option is "prompt to allow" or "deny", with a list of sites where you've chosen "never allow" and they would silently block.

Denying off-line data by default **will** break web applications. just be aware of that.

**Comment by wolfbeast** [comment]
@JustOff Please note the string changes for 27.2 (not 27.1)

**Comment by JustOff** [comment]
Yes, thanks. And it's good that you add new names for new strings so we can keep old ones for the backward compatibility.
