### ISSUE TITLE
Rework the Options window

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#766]
The Options window is currently a little unbalanced which causes it to grow to a too-large vertical size.
It needs a redesign pass to distribute options better, maybe add options tabs to the Privacy category (since there are likely going to be more privacy options we want there anyway, like referrer control)

**Comment by JustOff** [comment]
How about to replace 'radiogroup' to 'menulist' for tracking option?

![palemoon_2016-12-18_15-04-16](https://cloud.githubusercontent.com/assets/340855/21293653/be4a910c-c533-11e6-8648-c50e7d28100f.png)
![palemoon_2016-12-18_15-12-16](https://cloud.githubusercontent.com/assets/340855/21293678/6ce30244-c534-11e6-9ea5-e9ddc9a2fa67.png)

**Comment by wolfbeast** [comment]
That's at most a quick temporary fix to reduce the window size, but ultimately there should be more privacy options that aren't going to fit into a single pane comfortably -- making it a tabbed setup is better.

**Comment by wolfbeast** [comment]
![image1](https://cloud.githubusercontent.com/assets/3359132/21902243/7c9eb78e-d8fb-11e6-8870-73ed356ff8be.png)
![image2](https://cloud.githubusercontent.com/assets/3359132/21902244/7ca26e24-d8fb-11e6-8910-2b1286fbb23b.png)
![image3](https://cloud.githubusercontent.com/assets/3359132/21902242/7c9e60d6-d8fb-11e6-8e83-bb04a0c557ec.png)

**Comment by mattatobin** [comment]
Frankly, and in my opinion. The Preferences window has been limited ever since Phoenix's inception. It was an attempt to make it more appealing to people and to not have so many options that people could readily mess up. However, at the time no one knew of about:config.

If you guys are serious about redesigning the options window.. I would suggest something more akin to the older suite style preferences window. With a tree at the left.

But that is just my suggestion.

**Comment by wolfbeast** [comment]
Sorry but I disagree. I think the category view works well and is easily accessibly to all levels of expertise, as well as working well for a graphical presentation.
Tree views for options are in my opinion a last-ditch effort to organize options if you have so many that it would be unworkable in any other format. i.e.: it's a good solution for an overwhelming amount of configuration otherwise.

I know at least one extension that uses a tree view like this and I found it too user-unfriendly - which is why I made Pale Moon commander instead with the same category view we have in the main preferences window. I gather you can use that extension on Pale Moon as well if you wish, with some editing to include our options.
