### ISSUE TITLE
Fix hard-coded support URLs

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#769]
The window triggered when Pale Moon detects a very slow startup links hardcoded to a Firefox support URL from nsbrowserglue.

This needs to be made a pref, and made to point to a relevant palemoon.org page (similar work to the get more devtools link)

http://xref.palemoon.org/palemoon-trunk/source/browser/components/nsBrowserGlue.js#492

**Comment by mattatobin** [comment]
Ditto for these as well:
http://xref.palemoon.org/palemoon-trunk/source/browser/base/content/utilityOverlay.js#515
http://xref.palemoon.org/palemoon-trunk/source/browser/base/content/browser-syncui.js#358

I figure if you're gonna go to the trouble.. May as well get all of them.

This also exists but just needs killed but likely separate bug:
http://xref.palemoon.org/palemoon-trunk/source/browser/base/content/browser.js#2429

**Comment by wolfbeast** [comment]
> This also exists but just needs killed but likely separate bug:

See #937
