### ISSUE TITLE
Enable let without version=1.7+ in non-strict mode

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#773]
It seems to be generally desired (for browser parity rather than best practices) to allow `let` without `version=1.7` or higher in non-strict mode.

To remain compatible with older code, it needs a bit of magic that determines when let is used as a keyword and when it's used as a variable.
Info and patch found in https://bugzilla.mozilla.org/show_bug.cgi?id=932517 -- looks fairly self-contained and straight-forward.

What needs doing:
- [x] Check for and convert any `let (x=y) { something; }` blocks in our internal code to `{ let x=y; something; }`
- [x] Remove support for `let (x=y) expr;` deprecated let expressions (es6 conflict)
- [x] Remove support for `let (x=y) { }` deprecated let blocks (es6 conflict)
- [ ] Make `let` versionless and put in code to adaptively use it as a keyword in sloppy mode

**Comment by wolfbeast** [comment]
There is one problem. If we want to do this, then we must remove support for `let (x=y) { something }` blocks first.

**Comment by JustOff** [comment]
I think it's worth it. I never seen the correct javascript version declaration in the wild web since the time of Netscape, but more and more sites are starting to use let ...

**Comment by wolfbeast** [comment]
It's not a matter of using `let` or not. It's people using sloppy mode (not using `use strict`) but still expecting strict standards to be followed while at the same time not indicating what JS version they want to be using. It's really bad practice but because other browsers allow it (I blame Google for starting this) web developers just use it without understanding.

**Comment by wolfbeast** [comment]
This kind of has priority right now, so self-assigning and getting this done and out of the way.

**Comment by wolfbeast** [comment]
Looks like most of the remaining let () {} blocks were in tests (PITA and we should get rid of those) and toolkit. Lots of it was already landed in the platform by Mozilla for this prior to 38.

**Comment by wolfbeast** [comment]
I'm foregoing the needlessly complex (and terribly implemented) odd-ball corner case adaptive interpretation of let in sloppy mode as a variable for now. From the past it was clear that this hardly occurs (when we were experimenting with changing the default version of JS for non-tagged scripts) and is an easy, proper fix for webmasters if they happen to use `let` as a variable.

If it turns out to be a significant problem, this can be re-opened.

**Comment by wolfbeast** [comment]
Verified ES6 compatibility:
![image1](https://cloud.githubusercontent.com/assets/3359132/21750845/3a03e6b0-d5bd-11e6-98bc-a0eb98372ea8.png)
