### ISSUE TITLE
Pale Moon Linux Installer doesn't work with sudo passwords that contain control characters

### ISSUE THREAD

**Issue by nathalie-tate** [MoonchildProductions/Pale-Moon#812]
sudo passwords are allowed to contain control characters (ctrl+S for example) but the pale moon installer cannot accept these characters. Don't know if this is something you can or will fix, but thought I should mention it.

**Comment by wolfbeast** [comment]
I think it's a limitation of the way the installer is made. I don't think there's a reason to go out of our way for this corner case as well. Certainly inconvenient, but having control characters in a password IMHO is only making it more difficult for yourself and not significantly increasing security of your password.

**Comment by trav90** [comment]
Patches are always welcome!

I'm going to close this issue, as it is not a problem with the browser itself. If you'd like to re-open this issue on the pminstaller repo, I'll mark it as an enhancement and help wanted.
