### ISSUE TITLE
Chat on YouTube livestream no longer working

### ISSUE THREAD

**Issue by xbeyond1** [MoonchildProductions/Pale-Moon#827]
Seems that the chatroom feature doesn't work with PM anymore, since YouTube thinks the browser is outdated. 

![youtubechat](https://cloud.githubusercontent.com/assets/22633092/21923000/5052adf0-d97a-11e6-8d92-887cad819487.png)

**Comment by janekptacijarabaci** [comment]
Dupe of https://github.com/MoonchildProductions/Pale-Moon/issues/816
