### ISSUE TITLE
27.1.0b2 Windows: Dailymail video playback issues because of media.fragmented-mp4.enabled

### ISSUE THREAD

**Issue by SJ-Diamond** [MoonchildProductions/Pale-Moon#831]
http://www.dailymail.co.uk/video/index.html?ito=embedded

Videos there fail under Windows if the about:config value for "media.fragmented-mp4.enabled" is true - Setting it to false is no option because it makes the memory usage of the browser sky-rocking.

There seems to be some large issues with that feature/function which makes Mp4 playback either a hit or a miss.

With that one disabled other problematic Mp4 videos are also running... at least until memory runs out ;)

Seems Mozilla has done something after ESR 38 was done in that department which made Mp4 playback more problem free but which is still missing or not working as it should in your implementation?

System is 8.1 with 64 Bit

**Comment by trav90** [comment]
While I do have issues playing videos on 27.0.3, They play perfectly for me on current 27.1.0b2 builds.

**Comment by JustOff** [comment]
Just for the record, I can't play any videos from the link above (27.0.1b2, win7).

**Comment by SJ-Diamond** [comment]
@JustOff you will see it will work if you set "media.fragmented-mp4.enabled" to false in about:config - but then Pale Moon consumes all memory available until Windows complains nothing is left anymore.

So there is indeed something either missing or not complete or bugged with that special value and it's surrounding. Because it is clearly visible that MP4 videos - even problematic are still playing... only not with that pref on.

**Comment by wolfbeast** [comment]
I can confirm that the latest trunk does not play the dailymotion videos with the fragmented mp4 reader enabled. I do however not see any memory inflation with it disabled.

I can see if I can find out where this regressed, @trav90

**Comment by wolfbeast** [comment]
Looks like this broke with PR #707

**Comment by SJ-Diamond** [comment]
@wolfbeast Well, here under Windows 8.1 64 Bit every second where i play MP4 videos without media.fragmented-mp4.enabled set to true, it consumes more and more memory until Windows has no free memory anymore ;)

**Comment by wolfbeast** [comment]
I don't think the memory inflation issue is directly related.

**Comment by wolfbeast** [comment]
I've narrowed it down to commit 7f2dd37de3120bdf4347c9a5c5adbb477518eb85 -- after that commit, the types of MP4 found on dailymail (I've saved one locally) stop playing.

**Comment by wolfbeast** [comment]
Considering this breaks fragmented MP4 playback of a good percentage of videos on the web, this is considered a blocker. A solution must be found before the next release version for this.

@trav90 -- Any idea of the actual cause of this non-playing? I looked up the relevant Mozilla bugs and it seems obvious dependencies were all ported over.

**Comment by wolfbeast** [comment]
Backing out 244720b01b5ab07450c265ac85197538cb6fb2eb and 7f2dd37de3120bdf4347c9a5c5adbb477518eb85 (basically restoring previous handling of edit lists but keeping the start offset calculation added in eefda063b4b77dde81757421dda4cc8e3eff1094) fixes the playback problem here.

From what I understood of the relevant bug, this is an optional fix for non-standard encoded videos to begin with (using some edge case MP4 feature to let video and audio start at an arbitrary time point after video starts) so it would be lower priority than fixing video playback in general, don't you agree?

**Comment by trav90** [comment]
@wolfbeast that sounds like a plan. PR #707 included some fixes needed for FFmpeg as well, but I don't think backing out those 2 commits should hurt anything, but I'll run a build shortly to confirm.

Sorry you had to do the legwork for this. I've been AFK today taking care of things and didn't see all this until now.

**Comment by wolfbeast** [comment]
> Sorry you had to do the legwork for this. I've been AFK today taking care of things and didn't see all this until now.

It wouldn't have been easy for you anyway since it's apparently only affecting WMF playback. I didn't see that being quick or easy for you anyway :smile:
