### ISSUE TITLE
BankID 2.0 - Compatibility issue (PM27.*)

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#835]
All PM27 builds (including v27.1.0b2) still fails to pass the "support for recommended functions" part of this BankID 2.0 test:
https://tools-preprod.bankid.no/browser-test/
..and of course, PM v27.1.0b2 is only provided as 32-bit builds, so whether it's a 32-bit or 64-bit build doesn't seem to matter.

This issue was also discussed here (with screenshots):
https://forum.palemoon.org/viewtopic.php?f=56&t=13391/

And by the way; PM v26.4.1 passes the test with flying colours!

**Comment by SJ-Diamond** [comment]
Seeing all sub-tests as successful.

**Comment by JustOff** [comment]
I've success with all tests in both 27.0.3 & 27.1.0b2.

**Comment by THEtomaso** [comment]
I've narrowed the issue down now, and it's somewhat strange..
For me, the test seems to fail with PM v27.* because I've disabled Geolocation (geo.enabled = false).
..but with PM v26.4.1, the test comes out just fine, even though I've configured it the exact same manner!
So, has something changed in the way PM27 handles location-awareness, compared to older versions?

**Comment by THEtomaso** [comment]
I tested it here (with Geolocation disabled):
http://benwerd.com/lab/geo.php

Pale Moon v26.4.1:
> The page could not get your location.

Pale Moon v27.x:
> Your browser does not support geolocation.

So, it would seem that PM v26.4.1 tells sites that it DOES support Geolocation, even though it's disabled.
Whilst PM v27.x on the other hand, simply says that it doesn't support it at all!

Any thoughts on this?

**Comment by SJ-Diamond** [comment]
well the behavior of PM 27 seems more logical to me. When a feature is disabled it should NOT work.

**Comment by THEtomaso** [comment]
Well, not that it really matters, since BankID 2.0 still works for practical use, even with Geolocation disabled.
I'm just curious to know why these two PM versions behaves differently.
..and which one does it "correctly", if there's such a thing.

**Comment by janekptacijarabaci** [comment]
The difference is the following:
https://bugzilla.mozilla.org/show_bug.cgi?id=884921

**Comment by THEtomaso** [comment]
OK, guess it's by design then.
If Moonchild can confirm this, then we'll just close this issue.

**Comment by wolfbeast** [comment]
@janekptacijarabaci No, it isn't. That was fixed in 25.5.0 already

As for the desired behavior: getting a "not available" when the user has disabled geo completely is correct.

**Comment by janekptacijarabaci** [comment]
@wolfbeast:
There was a misunderstanding. I mean this only:
https://bugzilla.mozilla.org/show_bug.cgi?id=884921#c4

For:
```
if ("geolocation" in navigator) {
  alert("The GEO API - yes");
} else {
  alert("The GEO API - no");
}
```

Pale Moon 26.5.0:
`geo.enabled` = `true`/`false` - always returns `yes`

Pale Moon 27+:
`geo.enabled` = `true`/`false` - always returns "geo.enabled" (`true` - `yes`, `false` - `no`)

**Comment by wolfbeast** [comment]
Yeah, looks like the navigator object was previously not changed, even though it was aligned with the spec.
Regardless, what v27 does is more correct and less ambiguous. Not sure why BankID thinks that geolocation is important (do they use it? and why?)...
