### ISSUE TITLE
[Linux] ICU version detection broken with sed 4.3

### ISSUE THREAD

**Issue by WorMzy** [MoonchildProductions/Pale-Moon#836]
Related mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1329272

https://github.com/MoonchildProductions/Pale-Moon/blob/master/build/autoconf/icu.m4#L76 currently causes build failures on systems with an up-to-date version of sed:

```
 0:05.57 sed: character class syntax is [[:space:]], not [:space:]
 0:05.57 configure: error: cannot determine icu version number from uvernum.h header file
 0:05.57 ------ config.log ------
 0:05.57 configure:25957: checking for fontconfig
 0:05.57 configure:25964: checking _FONTCONFIG_CFLAGS
 0:05.57 configure:25969: checking _FONTCONFIG_LIBS
 0:05.57 configure:26168: checking for stdint.h
 0:05.57 configure:26181: gcc-5 -c -march=x86-64 -mtune=native -O2 -pipe -fstack-protector-strong -g -fvar-tracking-assignments -g -fvar-tracking-assignments -std=gnu99 -fgnu89-inline -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -pipe -D_FORTIFY_SOURCE=2 -O2 conftest.c 1>&5
 0:05.58 configure:26168: checking for inttypes.h
 0:05.58 configure:26181: gcc-5 -c -march=x86-64 -mtune=native -O2 -pipe -fstack-protector-strong -g -fvar-tracking-assignments -g -fvar-tracking-assignments -std=gnu99 -fgnu89-inline -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -pipe -D_FORTIFY_SOURCE=2 -O2 conftest.c 1>&5
 0:05.58 configure:26168: checking for sys/int_types.h
 0:05.58 configure:26181: gcc-5 -c -march=x86-64 -mtune=native -O2 -pipe -fstack-protector-strong -g -fvar-tracking-assignments -g -fvar-tracking-assignments -std=gnu99 -fgnu89-inline -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -pipe -D_FORTIFY_SOURCE=2 -O2 conftest.c 1>&5
 0:05.58 configure:26175:27: fatal error: sys/int_types.h: No such file or directory
 0:05.58 compilation terminated.
```

Mozilla have "fixed" this by adding additional square brackets to the first instance of [[:space:]]. It doesn't deal with the underlying problem with the brackets being consumed, but it will fix the problem for the time being.

**Comment by mattatobin** [comment]
My only question is will this affect older versions in any way?

**Comment by trav90** [comment]
Should be simple fix. Can you please build from [this branch](https://github.com/trav90/Pale-Moon/tree/issue836) and verify?

**Comment by mattatobin** [comment]
Don;t you think you should follow the bug and do version detection so there isn't a risk of breaking backwards compatibility?

**Comment by trav90** [comment]
I did a direct port of the Mozilla patch and am running a build now to ensure backwards compatibility has not been broken.

**Comment by mattatobin** [comment]
I stand corrected... Sorry

**Comment by trav90** [comment]
No worries. I can confirm that the patch does not break builds on CentOS 7 (which has sed 4.2.2 for the record).

**Comment by WorMzy** [comment]
Works here, thanks trav90.
