### ISSUE TITLE
clipboardevents not prevented

### ISSUE THREAD

**Issue by joey04** [MoonchildProductions/Pale-Moon#839]
today's Unstable beta

#761 still works (i.e. can copy github SHAs via the commit page buttons) despite
dom.event.clipboardevents.enabled = false

Should be blocked, no?

**Comment by janekptacijarabaci** [comment]
IMHO no:
https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preference_reference/dom.event.clipboardevents.enabled

e.g. (Scratchapad - and run on a page)
```
var element = document.getElementsByTagName("body")[0];
element.addEventListener("copy", function (e) {
  alert("Copy!");
});
element.addEventListener("cut", function (e) {
  alert("Cut!");
});
element.addEventListener("paste", function (e) {
  alert("Paste!");
});
```

**Comment by wolfbeast** [comment]
No, this should not be blocked by that pref.

**Comment by joey04** [comment]
Thanks for the links. The special case in the code does make sense. Good to know those details are covered.
