### ISSUE TITLE
HSTS still writes site state to file when disabled.

### ISSUE THREAD

**Issue by joey04** [MoonchildProductions/Pale-Moon#840]
today's Unstable beta

per https://forum.palemoon.org/viewtopic.php?f=13&t=14486&p=103730#p103730

**Comment by wolfbeast** [comment]
HPKP should not be disabled by the HSTS disable pref. They are two entirely different things and HPKP can't be used in a privacy-compromising way like HSTS can.

**Comment by wolfbeast** [comment]
Commit af23abba6f4823f146ea0d20a9c64fcf41127208 disables writing to file and also adds a missing pref observer so flipping the pref should now immediately take effect.
