### ISSUE TITLE
Hotfix add-on

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#844]
Today I've noticed that Pale Moon made a request to following url: 

`https://addons.palemoon.org/integration/addon-manager/internal/update?reqVersion=2&id=firefox-hotfix@mozilla.org&version=&maxAppVersion=%ITEM_MAXAPPVERSION%&status=userEnabled,incompatible&appID={8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}&appVersion=27.1.0b2&appOS=WINNT&appABI=x86-msvc&locale=en-US&currentAppVersion=27.1.0b2&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%`

It seems to related to [this feature](https://wiki.mozilla.org/Features/Desktop/Add-on_hotfix) and [#694068](https://bugzilla.mozilla.org/show_bug.cgi?id=694068). As far as I understand Pale Moon does not use it, so probably it should be disabled. Setting [checkHotfix](http://xref.palemoon.org/palemoon-trunk/search?string=checkHotfix+%3D&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=palemoon-trunk) to false is likely to be enough until proper cleanup.

**Comment by mattatobin** [comment]
`http://xref.palemoon.org/palemoon-trunk/ident?i=PREF_EM_HOTFIX_ID`
`http://xref.palemoon.org/palemoon-trunk/ident?i=hotfixID`
'http://xref.palemoon.org/palemoon-trunk/source/browser/app/profile/firefox.js#59'
'http://xref.palemoon.org/palemoon-trunk/source/mobile/android/app/mobile.js#198'

Would be very simple to strip out. I would recommend you kill it with propane and propane accessories.

Also, seems odd that some vars aren't filled.. Did you construct this URI?

**Comment by JustOff** [comment]
> Also, seems odd that some vars aren't filled.. Did you construct this URI?
No, I just copied it from debug console as is.

**Comment by mattatobin** [comment]
Maybe because it is a ridiculous hack is why it didn't bother to fill in all the vars as it should have.. Anyway, have fun! I always did on these kinds of runs!

**Comment by JustOff** [comment]
Ok, I'll try to wipe it out carefully and send a PR.
