### ISSUE TITLE
Improve toolbar button visuals for brighttext situations

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#849]
As noted in #695, the gradient on toolbar buttons in the UI is less than optimal in `[brighttext]` situations (the gradient lightens button faces too much on dark colors to make light text stand out).

This could be addressed by making the gradient on toolbar buttons darker to blend in better with dark accent colors and improving contrast with white text as a result.

**Comment by Lootyhoof** [comment]
This is something I've been looking into lately. How does this look?

![Brighttext buttons](http://i.imgur.com/8IVg6U2.png)

I've yet to test it on Win7 et al still, though.

**Comment by wolfbeast** [comment]
I think it looks fine - it's a special-case button anyway if it works like an indicator, so special-case styling when it's active in that role would be fine.

**Comment by wolfbeast** [comment]
Considering this resolved.
