### ISSUE TITLE
Video on Twitter starts without sound

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#857]
For example:
https://twitter.com/NASASolarSystem/status/823954420526292992
https://twitter.com/BoeingDefense/status/824300485557493760

Sound appears only after pressing pause/play manually.

Tested on 27.0.3 - 27.2.0a1 x86 @ Win7x64.
ATTN: @trav90

**Comment by wsdfhjxc** [comment]
According to [this article](http://www.telegraph.co.uk/technology/twitter/11680291/How-to-turn-off-Twitters-annoying-new-autoplay-feature.html), it's expected behavior.

>  Twitter has introduced a new autoplay feature, meaning all videos, Vines and gifs in your timeline will automatically start playing as you scroll down. While the sound is muted until you actively click on it, some users are already complaining about autoplay.

**Comment by JustOff** [comment]
@wsdfhjxc thank you for clarifying! I couldn't imagine such madness.
