### ISSUE TITLE
clarify "Local Storage" usage

### ISSUE THREAD

**Issue by joey04** [MoonchildProductions/Pale-Moon#859]
Unstable 20170124053246

Checked [weather.com](https://weather.com/) earlier and saw a new site look. So I was curious to see if their cookies changed, and they did; no longer were they setting big DOM cookies. Then I went into my profile/ and saw a new storage/ folder with a couple of .sqlites they put there, presumably with same type of data as before.
(Note: I've since gone back a few times, but it's the familiar look with DOM cookies. I saw this new look once before, about a week ago, and storage/ was set then too. Perhaps they're testing a new design. I'm using the default useragent, no overrides.)

I have browser.offline-apps.notify = true
So I was expecting that I'd get a notice of local storage, but I didn't get one today or last week. I searched the forum and [others have experienced](https://forum.palemoon.org/viewtopic.php?f=3&t=14023
) this type of thing too.

The thread includes [bug 959985](https://bugzilla.mozilla.org/show_bug.cgi?id=959985) where Mozilla has refused to fix the above pref.

Overall I'm still not clear how this "local storage" is supposed to work. And judging from the thread others have this confusion as well.

So a few requests/ideas

1) Clearly explain these on a Help page:
* "Offline Cache" in Options->Advanced->Network
* "Offline Website data" in Privacy->History->Settings
* storage/ in profile folder (is this the same as indexDB/ prior to v27?)
* cookies (regular and DOM)
* any others I've missed

Currently the Options window "Help" button goes to a TODO page for the first item and a 404 for the second.

It'd be nice to have them all on a single Help page, so that we the users can know what all this stuff is.

2) Perhaps group these "local storage" items together in the Options window. The current arrangement is scattered, and having cache options in the Network tab is odd.

3) Fix browser.offline-apps.notify to actually notify. If it can't/won't be fixed then perhaps remove the pref. Or the Help page would explain the behavior. Either way, it shouldn't give us the sense that we'll get notified when in fact we won't.

**Comment by wolfbeast** [comment]
I'm sorry but this has already been addressed in another issue. See #760 that fixes this confusion with a 3-state option.

Also, I'd appreciate it if you have general questions or want to discuss something, that you don't use the issue tracker for it. That's better done in the development (discussion) board on the forum. Lumping together multiple things in a single issue is also not very helpful to keep track of things.

As for point 2: no, cache options most definitely belong in the networking tab.

**Comment by joey04** [comment]
Disagree.
I'm well aware of #760 and already had set offline-apps.permissions = 1 after the latest Unstable

I've raised a number of new issues, including TODO and 404'd Help pages from Options window. That's a bad thing on its own.
Plus 760 doesn't clarify any of the things I'm asking. Just perpetuates the broken behavior Mozilla wouldn't fix.

**Comment by wolfbeast** [comment]
The behavior *is* fixed by #760. Use the UI. It's there for a reason.

**Comment by wolfbeast** [comment]
Also, the help buttons from the preferences menu is already on the radar. See #635.

**Comment by joey04** [comment]
760 changed default prefs and UI. As stated, I already did use UI to change to "Always Ask" which under the hood means offline-apps.allow_by_default = false and browser.offline-apps.notify = true

But when a site plops down stuff in profile/storage shouldn't that be asking me? That's where the bugzilla wontfix and some confusion on my and other user's part comes into play.

As for Help pages, would it be okay to post that to development (discussion)?

**Comment by wolfbeast** [comment]
I think you're confusing HTML DOM storage and Offline App storage here. They are not the same thing.

**Comment by joey04** [comment]
Okay, so #760 only covers [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache)?

I know DOM cookies are deletable via extensions like Cookie Keeper.

So what about the profile/storage/.sqlite in my OP? Is the browser able to automatically delete it? I already have this set true: "Offline Website data" in Privacy->History->Settings

(Seems like profile/storage is a very niche thing I've only seen on one site so far, as described. But if not deletable by browser then it's effectively a super-cookie, and workarounds like CCleaner needed, as suggested in the forum thread.)

**Comment by wolfbeast** [comment]
If you deny the use of cookies ("never"), it will also deny `localStorage`.
Clearing cookies also clear localstorage (as long as you don't restrict the time range since local storage isn't a cookie and doesn't have that kind of time mechanism).

The only thing we currently don't do is restricting 3rd party use of local storage. I've opened issue #860 to address this.

**Comment by joey04** [comment]
I don't deny any cookies; I have Cookie Keeper delete all of them when I close the browser except the few I want to persist. It's part of my overall approach of allowing sites to do what they need to while I use them, then later getting rid of data I don't want or need. Perhaps it's overkill, but it's a peace-of-mind thing.

Being a non-developer (both of the browser and websites/webapps) means I don't really understand what I've been calling "local storage" (in a general sense per my OP list) in much detail. This thread and looking at MDN articles exposes my lack of detailed knowledge.

So, in closing, I thank you for taking the time on this issue and revisiting the spec, resulting in #860. And I appreciate all your work on this browser, managing all manners of problems and details.
