### ISSUE TITLE
Update NSS to a later version.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#861]
If we want to support things like Chacha and better aead support, then we need to update to a later version of NSS.

- [x] Update from upstream NSS code (3.28.3-RTM)
- [x] Update NSPR to matching version for NSS
- [x] Check and fix any build bustage
- [x] ~~Apply patches for Camellia-GCM and re-version~~
- [x] Add ChaCha20-Poly1305 and enable
- [x] Add AES-256-GCM but do not enable
- [x] Distrust CNNIC
- [x] Restore trust of StartCom CA certificates.

**Comment by CNAmira** [comment]
It seems that there are lots of websites in China still use WoSign's service.
I think it will be better to distrust those BAD certificates unless locale is zh-CN.

**Comment by wolfbeast** [comment]
This has nothing to do with WoSign.

**Comment by CNAmira** [comment]
StartCom SSL is a product of WoSign

**Comment by wolfbeast** [comment]
StartCom has also been separated from it. What do you assume I'm going to do?

**Comment by wolfbeast** [comment]
>Notable Changes in NSS 3.28
> {...}
> The certificate validation code contains checks to no longer trust certificates that are issued by old WoSign and StartCom CAs after October 21, 2016. This is equivalent to the behavior that Mozilla will release with Firefox 51.

This means it'll need an additional patch to revert this change for StartCom CA. In my professional opinion, StartCom has not been at fault for WoSign's transgressions, has taken every step necessary to correct issues, and should not be "banned by association with its parent company", especially with the official split that was immediately done.

Mozilla's move here is part of a political step to promote their own sponsored CA with free certificates (Let's Encrypt -- which upholds worse practices than StartCom ever has, including refusal of revocation and issuance of DV certificates without domain owner registry verification).

**Comment by JustOff** [comment]
Btw, Google did the same in Chrome 56, so those certs can be considered dead.

**Comment by wolfbeast** [comment]
I don't care what Google and their puppy does. I'm not going to distrust them when they are, in my evaluation, more trustworthy than LE (which will not get a trusted root in Pale Moon)

**Comment by JustOff** [comment]
I just meant that probably none will use the certs which are not accepted by majority of browsers.

**Comment by wolfbeast** [comment]
StarCom certs are cross-signed, though. And half a million sites aren't all just going to swap over overnight.

**Comment by wolfbeast** [comment]
Since nobody seems interested in implementing Camellia-GCM (and it's actually been dropped from a few libs that supported it previously like PolarSSL), I'll drop the re-implementation since Adding ChaCha20-Poly1305 will provide a sane alternative to the AES monopoly.

Sad about it though. I'll definitely keep Camellia-CBC in place because it's a strong, modern cipher that is supported by all libs.

**Comment by wolfbeast** [comment]
CNNIC is already handled responsibly with specific checks in NSS, and Startcom/WoSign is handled in Firefox itself, not the lib, so no further action is required.

**Comment by wolfbeast** [comment]
Resolved by merge 638bf73af66d5c2b17b4caef2ff8c50d66692b77

**Comment by trav90** [comment]
On Linux, this caused build bustage (resolved by PR #923). But now it fails at the packaging stage:

https://gist.github.com/trav90/ebea6a44017c44c78c2ce154a796bc22

A build with all the recent NSS/NSPR related commits backed out compiles and packages successfully.

**Comment by wolfbeast** [comment]
@trav90 Commit 115d296d0150cddb50adf01f1bf92bbf0a4d04bd should take care of your packaging issue on linux, I think.

**Comment by trav90** [comment]
RESOLVED FIXED.
