### ISSUE TITLE
Make javascript.options.strict debug-only

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#866]
For release versions, this pref is nothing but a footgun since it will break some FE and lots of extension code. It's only useful for tightening up chrome scripts to a stricter format.

**Comment by adisib** [comment]
Wouldn't it be simpler/better to just make it a hidden pref? Or is that what you mean?

**Comment by wolfbeast** [comment]
No I mean only honoring it in debug builds. People are still going to mess with hidden prefs without knowing what they are doing.

**Comment by JustOff** [comment]
Since it's only warnings I think we should leave this as is to simplify debugging, because not every extensions developer can build debug version of browser.

**Comment by janekptacijarabaci** [comment]
> Since it's only warnings I think we should leave this as is to simplify debugging, because not every extensions developer can build debug version of browser.

I agree.

**Comment by wolfbeast** [comment]
@janekptacijarabaci that depends on the answer to my question in the other issue. Are they just warnings as I think they should be?

**Comment by wolfbeast** [comment]
AFAICT these are not actually errors but just warnings. So this would be beneficial to leave as-is.

As for your question @janekptacijarabaci : What PRs are you talking about?...

**Comment by janekptacijarabaci** [comment]
> What PRs are you talking about?

PRs are nowhere. Yet.

And their type would be: #864 

Never or ever? :-)

**Comment by wolfbeast** [comment]
Oh, improving chrome scripts is certainly a good thing :) Just don't make it about this pref ;) and please ensure the new code is 100% functionally equivalent (can be tricky sometimes)
