### ISSUE TITLE
HTML5 Test Your browser scores 393 out of 555 points

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/Pale-Moon#867]
You are using an unknown browser that imitates Pale Moon 27.0.3 on Linux
https://html5test.com/index.html

There are different malfunction behaviours on different pages.
Like opening a photo in facebook makes an infinite loop of showing the photo on the site and then showing the photo in a popup and so on.

**Comment by janekptacijarabaci** [comment]
IMHO:
1) Yes. WebRTC has a lot of points (and too many security holes).

2) Ad Facebook: https://forum.palemoon.org/viewtopic.php?f=29&t=13005

**Comment by MartinX3** [comment]
Confirm, changing the usergaent to
Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko
for fbcdn and facebook.com worked.
Thank you!
