### ISSUE TITLE
Progressbar linestyle not used in newtabpage

### ISSUE THREAD

**Issue by dukfnx** [MoonchildProductions/Pale-Moon#868]
I have already post this in forum but reporting it here is much proper, I guess.
I attached an image to demonstrate. The progress bar use bottom style while settings is fill style.
Hope it will be fixed when the whole status bar renovation finish.
Using latest unstable build.
![probar](https://cloud.githubusercontent.com/assets/25418650/22406130/80339ef0-e67f-11e6-8e86-ac7ecd401bd9.jpg)

**Comment by janekptacijarabaci** [comment]
AFAIK:
"It is not a bug, it is a feature".

If the urlbar has focus, this style will change the "center" to "end", see:
https://github.com/MoonchildProductions/Pale-Moon/blob/27.1.0b2/browser/components/statusbar/content/urlbarBindings.xml#L317

**Comment by wolfbeast** [comment]
It's an internal page and as such doesn't have any progress, to begin with.

In addition, yes, this is by design when the address bar has focus, so the progress color doesn't interfere with active input.
