### ISSUE TITLE
Allow specifying scope for importRelative()

### ISSUE THREAD

**Issue by jez9999** [MoonchildProductions/Pale-Moon#88]
A small patch was checked into the Mozilla codebase some time ago that adds the ability for importRelative() to import a JSM into a scope, which my extension uses.  The bugzilla page is here:
https://bugzilla.mozilla.org/show_bug.cgi?id=998291

As I don't have VS2012 and don't want to install it alongside 2013, I can't build and test it myself with Pale Moon.  But I suggest you merge that patch in (or something similar adding that functionality).

**Comment by mattatobin** [comment]
https://hg.mozilla.org/mozilla-central/rev/8f5f134ee116

**Comment by wolfbeast** [comment]
Done.
