### ISSUE TITLE
Build failure gcc 32-bit linux unstable branch

### ISSUE THREAD

**Issue by walterdnes** [MoonchildProductions/Pale-Moon#880]
git rev-parse HEAD
43f79b181f4d0ed687ee42cc85c0d927fab6fb10

This occured in CentOS 6.5 32-bit environment with standard mozconfig intended for SSE contributed build. Builds were working as of last week. I am not a programmer, so don't know what went wrong.  zipped buildlog attached

[buildlog.zip](https://github.com/MoonchildProductions/Pale-Moon/files/759273/buildlog.zip)

**Comment by trav90** [comment]
Confirmed. Appears to be related to Mozilla renaming.
