### ISSUE TITLE
Missing OnTaskQueue() breaks debug build

### ISSUE THREAD

**Issue by rhinoduck** [MoonchildProductions/Pale-Moon#882]
OnTaskQueue() is called in assertions in the following files:

dom/media/MediaDecoderStateMachine.cpp
dom/media/MediaFormatReader.cpp
dom/media/MediaFormatReader.h

Grepping for the name yields no definition or even declaration.

ATM, I use the following to quickly comment out the offending lines so that I can compile debug builds:

```sed -i 's@^\(\s*\)\(.*OnTaskQueue().*$\)@\1//\2@' dom/media/*```

Pinging @trav90 because he might be the one to know the best what the intent was.

**Comment by wolfbeast** [comment]
Looks like more renaming going on @ Mozilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1144519

**Comment by trav90** [comment]
Yup. I have ported the patches listed in that bug, but haven't had a chance to test yet.
