### ISSUE TITLE
Undeclared identifiers used in an assertion in js/src/gc/Marking.cpp break debug build

### ISSUE THREAD

**Issue by rhinoduck** [MoonchildProductions/Pale-Moon#883]
Introduced in: https://github.com/MoonchildProductions/Pale-Moon/commit/daeb68a71fdd13308865e86a2269a892a89b12fb

Undelared identifiers: `ThingIsPermanentAtomOrWellKnownSymbol`, and potentially `js::Zone::isSelfHostingZone` (at least that was what the second error the compiler produced contained)

Offending lines highlighted: https://github.com/MoonchildProductions/Pale-Moon/blob/daeb68a71fdd13308865e86a2269a892a89b12fb/js/src/gc/Marking.cpp#L158-L160

**Comment by rhinoduck** [comment]
You might want to merge or at least look at https://github.com/MoonchildProductions/Pale-Moon/pull/884 before doing something about this.

**Comment by wolfbeast** [comment]
I just copied the assertion, not checking for stupid renames.

https://bugzilla.mozilla.org/show_bug.cgi?id=1147670#c6
`ThingIsPermanentAtom` -> `ThingIsPermanentAtomOrWellKnownSymbol`

I need to see the compiler output to know what exactly your second error would be.

**Comment by wolfbeast** [comment]
Never mind, looks like another wrapper function that got added, and we don't have that in js::zone -- it just needs to call the runtime directly.
