### ISSUE TITLE
Packaging debug builds fail

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/Pale-Moon#888]
PR #887 fixes compilation of debug builds, but they now fail at the packaging stage:
```
Error: /home/trava90/PaleMoon/pmbuild/browser/installer/package-manifest:436: Missing file(s): bin/components/TestInterfaceJS.js
Error: /home/trava90/PaleMoon/pmbuild/browser/installer/package-manifest:437: Missing file(s): bin/components/TestInterfaceJS.manifest
```

**Comment by trav90** [comment]
Looks like a simple fix. Tests are disabled by default, therefore these files are not available for debug builds.

**Comment by wolfbeast** [comment]
One of the many examples of Mozilla not taking anything but how they do things into account ;)
"Why would you not build tests for a debug build?" :P
