### ISSUE TITLE
Implement rel=noopener

### ISSUE THREAD

**Issue by 0strodamus** [MoonchildProductions/Pale-Moon#890]
I noticed an [article on ghacks](http://www.ghacks.net/2017/01/24/web-security-add-relnoopener-to-external-links/) that explains how "sites that you load by clicking on links may manipulate the page the link was posted on". According to [this testing website](https://mathiasbynens.github.io/rel-noopener/), other modern browsers are implementing changes to mitigate this potential security risk. Is this something that should be implemented in Pale Moon?

**Comment by wolfbeast** [comment]
rel=noopener is already implemented in Pale Moon on link elements.

**Comment by 0strodamus** [comment]
I was using the `Click me!!1 (same-origin)` and `Click me!!1 (cross-origin)` links. It looks like I am failing to grasp the details of the testing website, but that's my problem to continue to research. My apologies for the invalid issue report.

Thanks for the prompt response, for having already implemented this, and for developing the world's best web browser!

**Comment by wolfbeast** [comment]
The first two links demonstrate the potential problem (they are links that do not use any mitigation for it). The under the solution section it displays several ways to prevent it. The first being noopener, the second being noreferrer, the third using a JS juggling method to clear the opener manually before setting the URL in the opened window.
