### ISSUE TITLE
Asus ROG forum doesn't work with Pale Moon

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#892]
Drop down menus doesn't work:
https://rog.asus.com/forum/

Some will pop up, but will quickly disappear before you're able to click on them.
Others doesn't appear at all.

I've tried with all compatibility modes (Firefox / Native / Gecko), but to no use.

(Pale Moon v27.1.0,x64 / Win8.1Pro,x64)

--

**EDIT:**
Works just fine with SeaMonkey v2.46

**Comment by janekptacijarabaci** [comment]
Throws an errors in Browser Console:
```
ReferenceError: menuToggle is not defined
main.js:321:8
ReferenceError: menuWidthInit is not defined
main.js:105:8
```

Last bad: Firefox 46.0a1 (2015-12-20)
Built from https://hg.mozilla.org/mozilla-central/rev/388bdc46ba51ee31da8b8abe977e0ca38d117434

First good: Firefox 46.0a1 (2015-12-21)
Built from https://hg.mozilla.org/mozilla-central/rev/e6ba2d4a2e4930bb359f90312ef6f1ebdc34c0ac

Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=388bdc46ba51ee31da8b8abe977e0ca38d117434&tochange=e6ba2d4a2e4930bb359f90312ef6f1ebdc34c0ac

[Bug #1071646](https://bugzilla.mozilla.org/show_bug.cgi?id=1071646) (and [bug #1231758](https://bugzilla.mozilla.org/show_bug.cgi?id=1231758)) is the suspect.

See also https://forum.palemoon.org/viewtopic.php?f=13&t=14349&p=102414#p102414

__Most likely it's the same problem...__

**Comment by THEtomaso** [comment]
So, that's another "won't fix"?
Unfortunately, there seems to be a lot of sloppy web coding going on these days, and because all major browsers contains functioning workarounds for those sort of things, the codes are here to stay.
If you continously refuse to implement similar workarounds in PM, the number of incompatible sites will only increase exponentially!

**Comment by JustOff** [comment]
> So, that's another "won't fix"?

Why do you think it is? Be more patient please.

**Comment by SJ-Diamond** [comment]
Depends for sure if the ECMAScript feature in question can be implemented more straight forward, less straight forward or if it is beyond complex to do.

Also, i wonder if that ES6 target really is the culprit, because in Otter-Browser with revived QT-Webkit that entry is also not present and it works.

**Comment by THEtomaso** [comment]
> Why do you think it is? Be more patient please.
Sorry, I might have misinterpreted that forum thread. :)

**Comment by Atavic** [comment]
It doesn't work on K-Meleon, too. Seems more bad code on the page than a Palemoon issue here.

**Comment by wolfbeast** [comment]
Implementing the entirety of "Annex B" which is a descriptive addendum to ES6 describing how various browsers (mainly Chrome and IE) **don't** follow what was previously defined is a project all on its own. Websites should **not** be relying on anything defined in that annex.

**Comment by wolfbeast** [comment]
A quick look shows there's intermittent failure to drop-down the main "menu" which displays a bunch of icons in a vertical strip (probably also not intended) because a fucntion is called that isn't defined.

`ReferenceError: menuWidthInit is not defined main.js:105:8`

In addition, their HSTS header is invalis, and they have a couple of CORS failures on fonts. Someone with proper tech knowledge should look at their forum code to fix this.

**Comment by wolfbeast** [comment]
The underlying issue with sloppy coding like this is that it's allowed per ES6. I'd love to go back in time and remove whomever has been responsible for this backwards idea, but unfortunately we'll just have to deal with it.
Function hoisting in block scopes is #900 -- the other issues are most definitely ROG's side, and if they want to be more compatible with the browser world at large they should re-order their script functions.

**Comment by THEtomaso** [comment]
I just noticed that the drop down menus doesn't work at this page either:
http://www.philips.co.uk/c-m-pc/monitors/
Is this the same issue?

**Comment by wolfbeast** [comment]
Looks like it. Using function `y()` before it's being defined further down.

**Comment by Atavic** [comment]
I can't see _Monitor_ menu but I can see the _Product support_ one. A real mess.

**Comment by Lorienna** [comment]
Do you think selecting <tt>View</tt> => <tt>Page Style</tt> => <tt>No Style</tt> in non-compact main menu of Pale Moon could be a simple emergency work-around here, and in situations of this kind, anyone?

**Comment by Atavic** [comment]
I did it and you can see that it's definitely an error in the page.

**Comment by Lorienna** [comment]
But at least you're being able to access the desired "Monitors" sub-menu, aren't you?

**Comment by Atavic** [comment]
No, meanwhile... site has changed and their problem is still there.

**Comment by Lorienna** [comment]
How about these links, at the top left:

* Home monitors
* Office monitors
* All monitors
* Discover our full range

Can you see them now?

**Comment by Atavic** [comment]
- View > Page Style > Basic Page Style 
Load: `https://rog.asus.com/forum/`
Result: By clicking Products on top I get `https://rog.asus.com/forum/#` on URL adress and nothing loads.

- View > Page Style > No Style 
Load: `https://rog.asus.com/forum/`
Result: By cloicking Monitors on the list on the left I get no result as 1-st click, while a second click opens a new tab. By closer inspection, a mouseover reveals: https://www.asus.com/ROG-Republic-Of-Gamers/Monitors-Products/ while the new tab has a Google Analitics string `?_ga=` attached.

**Comment by Lorienna** [comment]
I was talking about this one, actually:
http://www.philips.co.uk/c-m-pc/monitors/

Anyway, it doesn't seem like the solution for everyone.

Thank you for the feedback!

**Comment by wolfbeast** [comment]
ES6 classes will be implemented in a UXP-based Pale Moon. closing.
