### ISSUE TITLE
Investigate moving to VS2017 CE

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#902]
In March, Visual Studio 2017 CE will be released along with the professional lines.
We should investigate if it is something we want to move to as regards feature set, compiler maturity and OS support, since it'll be more standards compliant for C++11 and later.

**Comment by wolfbeast** [comment]
No breaking changes apparently between 2015 and 2017 for C++, but from 2013 to 2015 there were (which will also apply here).
Reference: https://msdn.microsoft.com/en-us/library/bb531344.aspx#Visual%20C++%202015%20Conformance%20Changes

**Comment by Bfgeshka** [comment]
By the way, about compilers: will new browser support building with GCC 7+?

**Comment by wolfbeast** [comment]
As far as I know building UXP with a recent enough version of GCC 7 works.

**Comment by trav90** [comment]
Yes GCC 7.x works fine. In fact current Basilisk release and Pale Moon unstable are both built using GCC 7.
