### ISSUE TITLE
timeouts not working

### ISSUE THREAD

**Issue by mattenklicker** [MoonchildProductions/Pale-Moon#905]
When a web site doesn't respond, Palemoon shows the spinning wheel forever, no matter what timeouts are set in `about:config`. When this happens, i.e. a tracking site can't be reached during shopping, it blocks all other tabs, that have a link to this site also. Which means you can't go on shopping by open a new tab. The only workaround is to restart the browser.  
Easiest way to reproduce: Open a port with netcat `nc -l -p 9999` and surf to http://127.0.0.1:9999/.

Version: 27.0.3/Linux

**Comment by wolfbeast** [comment]
Hmm.. this shouldn't happen and I don't think the instability I ran into in Windows in particular applies here, although it may be a side-effect of the media issue we've seen -- I did just commit a change in f52d61f2b2fa29f8516fafa54c52d540dacaede2 that might be related to this. The latest unstable of today or later (when it's available on Linux) should have this change in it. Can you let me know if:
- 27.1.1, to be published tomorrow, displays this issue?
- Our current trunk with the indicated commit included displays this issue?

**Comment by trav90** [comment]
> The latest unstable of today or later (when it's available on Linux) should have this change in it.

I just made a new Linux unstable build available.

**Comment by wolfbeast** [comment]
@mattenklicker Are you still interested in following up on this issue?

**Comment by mattenklicker** [comment]
I'm quite busy and can't test it, so I close the bug for now. I'll reopen when I can test and it is still an issue. Some more context:
    In fact the problem happens during TLS handshake. In my network https traffic is intercepted by squid. Squid does hostname forgery checks: It resolves the hostname it got from SNI on it's own and when it gets a different IP than the original destination IP from the client, it stops doing anything and keeps the connection open (see http://wiki.squid-cache.org/KnowledgeBase/HostHeaderForgery). This happens regularly on sites, that often return different IP addresses (i.e. googletagservices.com). This blocked sites like amazon.com during the whole runtime of palemoon for me. Because I use squid only to extract the SNI hostname I patched these forgery checks out of squid.

**Comment by wolfbeast** [comment]
So, the problem is that your proxy accepts the connection, and leaves it half-open while waiting for the upstream server... Also, your initial report stated to connect over http, not https -- if you're mixing TLS/non-TLS without proper transcription then you can also run into protocol conflicts and cause broken protocol dialogues that won't time out.
