### ISSUE TITLE
Issue with media.mediasource.format-reader.mp4 enabled on Vimeo

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#908]
People have reported on https://forum.palemoon.org/viewtopic.php?f=29&t=14887 that Vimeo videos fail to play when MSE is activated. Also MSE-MP4.

For example that video here: https://vimeo.com/203451175?ref=em-share

Tested a bit with the about:config entries responsible for Mediasource. If the media.mediasource.format-reader.mp4 entry is activated it makes Vimeo videos fail, but deactivated - while not totally shutting down MSE the videos are playing.

So something seems to be not working as expected in combination with media.mediasource.format-reader.mp4

**Comment by THEtomaso** [comment]
Like I posted here:
https://forum.palemoon.org/viewtopic.php?f=29&t=14887#p107283
..this issue might possibly have to do with this bug:
> MediaSource sourceopen event does not fire when video preload attribute is set to "none":
https://bugzilla.mozilla.org/show_bug.cgi?id=1211752

There's a test here (from the first post of that Bugzilla report):
https://craig.is/demoing/sourceopen-bug
..and indeed, the "MediaSource sourceopen" event does not fire in the "preload none" test!

Also, from reading that same Bugzilla report, this particular issue was apparently fixed back in April, with updated MediaSource specs, instructing that the "preload attribute" should be ignored:
https://github.com/w3c/media-source/commit/8aba06a6a10d8fe0bf26b2e4c11a3e5a209244e0/

**Comment by trav90** [comment]
@Sa-Ja-Di thanks for excellent information! Looks like something in the new MediaFormatReader (introduced with 27.1.0) isn't playing nice with MSE.

If the media.mediasource.format-reader.mp4 pref is set to false, then Pale Moon falls back to the pre-27.1 method of playing MP4 + MSE.

**Comment by JustOff** [comment]
> If the media.mediasource.format-reader.mp4 pref is set to false, then Pale Moon falls back to the pre-27.1 method of playing MP4 + MSE.

How can it be? When `media.mediasource.format-reader.mp4` is `false`, then `window.MediaSource.isTypeSupported()` also always returns `false`, so, as far as I understand, MSE can't be used.

**Comment by wolfbeast** [comment]
Reopening this for now based on feedback on the forum. Please close manually when it's sorted.

**Comment by trav90** [comment]
It would appear that some Vimeo videos _do_ play, while others still do not with media.mediasource.format-reader.mp4 set to "true". Will continue to investigate.

**Comment by THEtomaso** [comment]
I would like to get a comment from you tech guys on that preload attribute issue that I linked to.
Like I pointed out, Pale Moon does NOT pass the "preload none" test, so it sure seems to be related to me.
Even if it's not related, there must still be something wrong with the way Pale Moon handles MSE, as long at it doesn't pass that test, don't you think?

**Comment by Sa-Ja-Di** [comment]
@trav90 I guess @THEtomaso has found something, perhaps you could take a look to what he suggests?

**Comment by trav90** [comment]
In this case, I don't think @THEtomaso's bug is applicable in this case. That bug is specifically talking about the MSE spec. While it's true that our MSE code is not currently up to spec, if that was the root of the issue then MSE videos likely wouldn't play regardless of if the format-reader pref is set to true.

**Comment by trav90** [comment]
Alright, after spending a good part of the day looking at this I think I found the root cause. The MediaFormatReader introduced in Pale Moon 27.1 is in many ways a rewrite of the existing media code that is highly backwards-compatible, but not 100% (MSE apparently being one of those not quite 100% areas). Similar to the way that I added a new MP3 and MP4 Demuxer objects that better interfaces with MFR, I believe the same needs done here (create a "MediaSouceDemuxer" object).

**Comment by trav90** [comment]
Looks like when Mozilla implemented their new "MediaSourceDemuxer" they took the opportunity to update their MSE code closer to spec. Probably worth doing the same here.

**Comment by trav90** [comment]
All my time the past 3 or 4 days has been spent attempting to fix the hangs in the media code that some people have reported. I _do_ intend to get to this soon, but the hanging issue has been top priority.

**Comment by THEtomaso** [comment]
Yeah, I've noticed the hangs too.
On several sites, if MSE is enabled, videos will freeze momentarily for a second or so.
However, the sound is unaffected, and when the video unfreezes, it catches up with the sound immediately and gets back in sync.

Good to hear that you're working on it, trav90! :)

**Comment by Sa-Ja-Di** [comment]
The latest unstable also has now again improved Twitch playback with MSE-MP4 as it seems. Can switch with activated "media.mediasource.format-reader.mp4" between Twitch quality steps without the video suddenly looping or stopping in playback. Testing now a couple of streams and so far stuff also in that section has improved as it looks like. 

So, the hangs reported for Facebook and others are also related with Twitch video playback problems. So, a part of #920  at least is related to this bug too.

Good work so far from you guys :) :+1:

**Comment by wolfbeast** [comment]
Of course it's all related, all of these sites use HTML5 media elements and all of them will start/stop decoders in rapid succession. So all of them run the risk of re-entrancy in the decoder if not carefully sequenced.

**Comment by THEtomaso** [comment]
I don't notice any difference.
For me, videos at certain sites still freeze momentarily during playback with MSE enabled, just like before.
Here's an example:
http://www.vgtv.no/#!/video/137889

**Comment by Sa-Ja-Di** [comment]
@THEtomaso http://www.vgtv.no/#!/video/137889 works fine here in combination with MSE-MP4 - No freezing, it only needs a while until it starts.

The only problem is a bit of buffering which is most likely because of my bad Wireless connetion here.

**Comment by THEtomaso** [comment]
> works fine here in combination with MSE-MP4 - No freezing, it only needs a while until it starts.

The video starts right away for me, but with MSE enabled, I'm never able to play through the entire video without a single freeze.
With MSE disabled, it plays just fine.

--

> More links of freezing videos please for testing would be nice

Here's another example:
http://tv.aftonbladet.se/abtv/articles/210961/
..and it this case, if I disable MSE, the video won't play at all!

--

> I suggest you try with a fresh profile

I only do clean installs.

**Comment by Sa-Ja-Di** [comment]
@THEtomaso That one works too. I guess you have a different problem then.

**Comment by THEtomaso** [comment]
I'll try to disable some extensions and stuff like that.

**Comment by Sa-Ja-Di** [comment]
@THEtomaso btw. a clean install is not the same like a clean profile. Not talking about the intallation, but the used profile in combination with an installation ;)

**Comment by THEtomaso** [comment]
> a clean install is not the same like a clean profile

Sure it does.
I'm talking about a TRUE clean install, which also involves deleting the profile and creating a new one.
Like I described here:
https://forum.palemoon.org/viewtopic.php?f=3&t=11170&p=78365#p78365

--

BTW; I've tried all sorts of things now, to get to the bottom of the MSE freezing issues..

Disabling all my extensions and reverting a bunch of settings didn't help at all.

But I DID however find one thing that fixed it, other than disabling MSE:
- Setting the User Agent Mode to "Native"!
Only drawback with this was that the videos didn't play in HD by default, so I had to change the resolution manually.

I think this shows that the UA string is related to the freezing issues somehow.
But of course, adding UA overrides for every affected site doesn't seem like a viable solution to this problem.

**Comment by Sa-Ja-Di** [comment]
@THEtomaso The downside of having  a full "Firefox" slice in the user agent string is that pages could deliver features which may work with latest Firefox only.

So, Pale Moon gets served in a situation like that a certain feature set which has a certain side effect. Can be that a page shows the correct (not mobile) page layout to Pale Moon or in the worst case is making the browser freeze if the page in question has no fallback mode which Pale Moon can understand.

Gecko or Native user agent mode works indeed best, but has the problem that pages could show the mobile layout instead a full desktop based on.

My personal experience is it is best to set as written the user agent to the Gecko mode and add afterwards a general user agent override for all pages at once - which somehow does not work as problematic in combination with pages as if you set in the options the user agent mode.

For example a user agent which works best for me (although  it does not make much sense user agent wise) is the following:

Mozilla/5.0 (Windows NT 6.3; WOW64; rv:3.2) Gecko/20100101 Goanna/20170224 Version/10.0.2 Safari/602.3.12 PaleMoon/27.2.0a1

And for the handful of pages which are problematic i create manually site specific user agents, for example Twitch, which works best with the Gecko user agent variant.

**Comment by THEtomaso** [comment]
So, you've been watching the videos at the links that I posted with PM's User Agent Mode set to "Gecko Compatibility"?
For me, "Native" mode is the only one that doesn't seem to be affected by the freezing issue.

..but if it works just fine for you in "Gecko" mode, then it seems plausible that some kind of client-side differences plays a part in this.
If someone could figure out what the problem is exactly, then perhaps something can be done to make the videos run properly in all UA modes?

Most people don't mess around with UA overrides (or even know what it is, for that matter), so I think the goal should be to make as many things as possible work by default!

**Comment by Sa-Ja-Di** [comment]
@THEtomaso I suggest make a small test on your own to see if it really is that way ;)

Switch on Gecko user agent mode in options, then go into about:config and add the following :)

1) right mouse click - new - string

2) First field:
general.useragent.override

3) Second field:
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:3.2) Gecko/20100101 Goanna/20170224 PaleMoon/27.2.0a1

**Comment by mattatobin** [comment]
One should never modify general.useragent.override as this completely negates the preferences in the Options Window.

This is WHY we have site specific UAs.. Use them.

Additionally, this bug is getting a little too forum thread. May want to move discussion back to the forums unless one has something technical to say.

**Comment by THEtomaso** [comment]
> I suggest make a small test on your own to see if it really is that way

I switched to "Gecko" mode and added these strings, with the override values that you suggested:
**general.useragent.override.aftonbladet.se
general.useragent.override.vgtv.no**
It didn't fix the issue though.
The videos that I linked to in my previous posts still froze. :(

--

> May want to move discussion back to the forums unless one has something technical to say.

OK

**Comment by THEtomaso** [comment]
Here's another example that might help you to troubleshoot MSE issues in PM27.. 
Playing Dropbox videos in Pale Moon doesn't work:
https://www.dropbox.com/sh/wackcyek8nzziaf/wJ1hAkF49U?preview=wx_fin.mp4
Disabling MSE doesn't work either, as this will just give you the download option instead.

**Comment by mattatobin** [comment]
@THEtomaso WORKSFORME

**Comment by THEtomaso** [comment]
> WORKSFORME on unstable at least

hmm..
Another example to confirm that these HTML5 problems somehow depends on system differences then.
I guess this makes the issues much harder to get to the bottom of.
We can only hope that it fails for trav90 too, making it somewhat easier for him to troubleshoot. :)

Anyway, these are the different Pale Moon versions that I tried with (and they all failed):
* v27.1.2 (64-bit) [Installed]
* v27.2.0a1 (32-bit) (2017-03-05) [Portable]
* v27.2.0a1 (32-bit) (2017-03-08) [Portable]

**Comment by wolfbeast** [comment]
I've had some weird things going on there on that URL.
First time I tried, it tried to send me some binary blurbs that were supposed to be javascripts. Hard refresh fixed that but no playback, neither in release nor in the latest unstable.
They may be tinkering with it on dropbox's side?

**Comment by mattatobin** [comment]
Still working just fine for me.. Very strange.

**Comment by wolfbeast** [comment]
````
20:40:07.361 Content Security Policy: The page's settings blocked the loading of a resource at https://cdn.rawgit.com/gkatsev/vtt.js/vjs-v0.12.1/dist/vtt.min.js ("script-src 'unsafe-eval' https://www.dropbox.com/static/compiled/js/ https://www.dropbox.com/static/javascript/ https://www.dropbox.com/static/api/ https://cfl.dropboxstatic.com/static/compiled/js/ https://www.dropboxstatic.com/static/compiled/js/ https://cfl.dropboxstatic.com/static/javascript/ https://www.dropboxstatic.com/static/javascript/ https://cfl.dropboxstatic.com/static/api/ https://www.dropboxstatic.com/static/api/ 'nonce-0uSMhJTvmFr2dYNLjgDX'").1 <unknown>
````
Doesn't load because cdn.rawgit.com isn't allowed. Might still work for you because of your geolocation.

**Comment by wolfbeast** [comment]
Confirmed that disabling CSP fixes playback.

**Comment by mattatobin** [comment]
No.. I know why it works for me... I have CSP off.

Confirmed CSP issue on their end.

**Comment by THEtomaso** [comment]
I was just about to post those CSP warnings, but you beat me to it! :)

**Comment by wolfbeast** [comment]
Also.. dropbox != vimeo. Why was this added to this issue?

**Comment by THEtomaso** [comment]
> dropbox != vimeo. Why was this added to this issue?

I thought it might be related, so I posted it for comparison and further troubleshooting, since these MSE issues seems to be a hard nut to crack.

BTW; the Dropbox video plays just fine in SeaMonkey, with CSP enabled.

**Comment by wolfbeast** [comment]
SeaMonkey likely has the deprecated "child-src" directive implemented.

**Comment by Sa-Ja-Di** [comment]
@trav90 @wolfbeast In the latest unstable Twitch has now some problems with looping/stuttering videos on the Twitch main/Start page from time to time (Version: 27.3.0a1 (32-bit) (2017-03-22))

**Comment by trav90** [comment]
I haven't had internet access for the greater part of the week so apologies for there being little movement on this so far. It's still on my radar and I am working on it.

**Comment by Sa-Ja-Di** [comment]
@trav90 No problem :D Actually i wanted to say that there was some kind of regression lately. Twitch worked better before with media.mediasource.format-reader.mp4 set to false.

Now this work-around is somewhat broken and Twitch runs rather bad partly, like i wrote, stocking and looping streams now, and changing the quality wheel is a hit or miss that the quality is actually changed - wheel is spinning most of the time.

**Comment by Sa-Ja-Di** [comment]
@trav90 Getting also a lot of errors in the error console too:

Timestamp: 25.03.2017 13:30:27
Warning: TypeError: asm.js type error: fixnum is not a subtype of double? or floatish
Source File: https://cvp.twitch.tv/1.6.3/player-core-min.js
Line: 1, Column: 268009
Source Code:
0;r=e+72|0;f=r+36|0;do{t[r>>2]=0;r=r+4|0}while((r|0)<(f|0));l[i>>2]=1;sh(e+112|0);r=e+216|0;t[r>>2]=0;t[r+4>>2]=0;t[r+8>



Timestamp: 25.03.2017 13:30:25
Warning: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
Source File: https://cdn.krxd.net/ctjs/controltag.js.6f097431db32c7c9f9254dccb9812402
Line: 7


Timestamp: 25.03.2017 13:30:19
Warning: Expected media feature name but found '-webkit-min-device-pixel-ratio'.
Source File: from DOM
Line: 0, Column: 17
Source Code:
only screen and (-webkit-min-device-pixel-ratio: 1.3)


Timestamp: 25.03.2017 13:30:31
Error: Error: Experiment `039bcc41-baa9-4351-8a76-3bcece6aec44` is deprecated
Source File: https://player.twitch.tv/js/player.js
Line: 11

Timestamp: 25.03.2017 13:30:31
Error: uncaught exception: [object Object]

Timestamp: 25.03.2017 13:24:55
Warning: Unexpected end of file while searching for length value for matched media condition.
Source File: from DOM
Line: 0

**Comment by trav90** [comment]
The video listed in the first post here (https://vimeo.com/203451175?ref=em-share) now plays perfectly for me (as well as several other videos on Vimeo that I tried) on both -release and unstable with both "dirty" and clean profiles. Can anyone else confirm?

Also, can we please keep this issue strictly about Vimeo? Please open a new issue for Twitch if problems are still being encountered there.

**Comment by JustOff** [comment]
> The video listed in the first post here now plays perfectly for me
> Can anyone else confirm?

Same to me (release & unstable).

**Comment by trav90** [comment]
Did you try other videos on Vimeo as well?

**Comment by THEtomaso** [comment]
Yes.
The video in the first post works for me too now, with MSE enabled! :)

Pale Moon still fails the "preload none" test that I linked to in my post here though:
https://github.com/MoonchildProductions/Pale-Moon/issues/908#issuecomment-281684018
..so I guess that there's still a potential buffering issue for certain videos, when MSE is enabled.

**Comment by wolfbeast** [comment]
So, I gather Vimeo changed something on their end and the "knownissues" entry can be changed to "some stuttering can occur' instead of "not playing"?

**Comment by wolfbeast** [comment]
On Win 7 x64 /PM-release x86, confirmed vimeo on-site videos now play.

**Comment by trav90** [comment]
> Pale Moon still fails the "preload none" test

This is a separate issue than the one this Issue is about (Vimeo).

> Also, the videos that I linked to in these posts still freeze momentarily for me during playback, with MSE enabled:

I just played both videos linked all the way through with no freezing of any kind.

> So, I gather Vimeo changed something on their end

That's what I'm gathering.

**Comment by wolfbeast** [comment]
I'll just remove the known issue point then. Seems to be solved.

**Comment by trav90** [comment]
Agreed. People, please re-open or create a new issue if problems are encountered again.

**Comment by THEtomaso** [comment]
I've posted new reports for the different issues that have been discussed here now:
https://github.com/MoonchildProductions/Pale-Moon/issues/981/
https://github.com/MoonchildProductions/Pale-Moon/issues/982/
