### ISSUE TITLE
uclibc-ng 32-bit linux: conflicting types for 'arc4random_addrandom'

### ISSUE THREAD

**Issue by walterdnes** [MoonchildProductions/Pale-Moon#910]
I don't know if you support uclibc-ng Gentoo linux. Even if it ends up being a bug-report for the uclibc-ng maintainer, it'll help. I have a build failure in both Master and 27.1.1 with uclibc-ng 32-bit Gentoo linux, but regular 32-bit and 64-bit glibc linux build successfully.

Preliminary, which may or may not be relevant, but I'm including this just in case. At first there was an early failure at line 99 of pmsrc/testing/mozbase/mozinfo/mozinfo/mozinfo.py

ctypes.CDLL("libc.so.6", use_errno=True).prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, 0)

There was a "/lib/libc.so.0" file, but no file "/lib/libc.so.6". "libc.so.0" is actually a symlink pointing to to "libuClibc-0.1.0.22.so". So I created a symlink named "/lib/libc.so.6" pointing to "libuClibc-0.1.0.22.so". That got a lot further, but eventually ran into an error where "arc4random_addrandom" is declared twice with incompatible types. Here's the segment from the buildlog where it trips up. I'm also attaching zipped buildlog.txt with the full buildlog.

4:46.34 /home/waltdnes/pmmain/pmsrc/ipc/chromium/src/third_party/libevent/./arc4random.c:449:1: error: conflicting types for 'arc4random_addrandom'
4:46.34 arc4random_addrandom(const unsigned char *dat, int datlen)
4:46.35 ^
4:46.35 In file included from ../../dist/system_wrappers/stdlib.h:3:0,
4:46.35 from /home/waltdnes/pmmain/pmsrc/ipc/chromium/src/third_party/libevent/util-internal.h:35,
4:46.35 from /home/waltdnes/pmmain/pmsrc/ipc/chromium/src/third_party/libevent/evutil_rand.c:39:
4:46.35 /usr/include/stdlib.h:927:13: note: previous declaration of 'arc4random_addrandom' was here
4:46.35 extern void arc4random_addrandom(unsigned char *, int);
4:46.35 ^
4:46.36 In the directory /home/waltdnes/pmmain/uclibc/pmbuild/ipc/chromium

[buildlog.zip](https://github.com/MoonchildProductions/Pale-Moon/files/795390/buildlog.zip)

**Comment by wolfbeast** [comment]
We only support glibc.
