### ISSUE TITLE
about:support buttons non-functional in Linux under 27.1.1

### ISSUE THREAD

**Issue by agilbertson1977** [MoonchildProductions/Pale-Moon#911]
Going to about:support and clicking on any of the buttons available there does nothing.  This has been confirmed on the forum (https://forum.palemoon.org/viewtopic.php?f=37&t=14882) for Debian and Arch and I have reproduced under Linux Mint as well.

**Comment by wolfbeast** [comment]
Linux specific; unable to reproduce on Windows.

**Comment by graciecat** [comment]
Reproduced in Ubuntu as well.

**Comment by wolfbeast** [comment]
Is there anything of note in the browser console and/or error console when you try to use the buttons?

**Comment by JustOff** [comment]
Ubuntu 14.04, Pale Moon 27.1.1 (stevenpusser), error on  open about:support:

```
stack of load error for about:support: TypeError: $(...) is null: setupEventListeners@chrome://global/content/aboutSupport.js:614:3
onload@chrome://global/content/aboutSupport.js:25:3
```

**Comment by JustOff** [comment]
I think this is because $("show-update-history-button") == null

**Comment by wolfbeast** [comment]
Easy fix.

**Comment by wolfbeast** [comment]
Commit 61ce72d7ad1702a784960680e1f4bff16db53a04  should fix this.

**Comment by JustOff** [comment]
Should we probably also consider [#ifndef ANDROID](https://github.com/JustOff/Pale-Moon/blob/master/toolkit/content/aboutSupport.xhtml#L99)?

**Comment by wolfbeast** [comment]
no

**Comment by trav90** [comment]
Confirmed that commit 61ce72d fixes this issue.
