### ISSUE TITLE
linux: not enough application handlers of mime types

### ISSUE THREAD

**Issue by danykey** [MoonchildProductions/Pale-Moon#913]
I have use PM 27.1 on Ubuntu 16.04 and found some trouble.

The PM always opens a save dialog for PDF, ZIP and so on without suggestion to open by some application.
As a temporary solution I had copy $profilePath/mimeTypes.rdf from Firefox.

I have guess that the mimeTypes.rdf is generated while creating a new profile but don't see a reason why it so poor.

So, it will be fantastic if user can add/remove/edit manually a new actions for mime types in the GUI preferences.

Thanks a lot.

**Comment by Atavic** [comment]
Tools > Options > Applications 
Then click on right column Actions and choose Use other...

**Comment by danykey** [comment]
Atavic, you seems didn't understand..
The Applications list(in PM) is doesn't contain pdf, zip and others, but Firefox does.

**Comment by Atavic** [comment]
Ah, ok. Have you set a system default for PDF and Zip files? If so they should handle the files in PM.

**Comment by walterdnes** [comment]
What we need may be an xml-editor extension that edits mimeTypes.rdf, e.g. let's say I want to add "*.pls" (playlist) files. What do I have to do? Other options to look at...
1) Can this be simplified to create a mimeType_template_fragment.rdf that you can insert and edit?
2) Can mimeTypes.rdf be scrapped, and replaced with a .ini file that a mere mortal can hope to edit with a text editor?
3) If we insist on sticking with the current format, please consider putting in dummpy mimeTypes "00", "01", "02"... "99". This would allow a person with a text editor to do a global search+replace, and hopefully get the new mimeType working.

**Comment by wolfbeast** [comment]
MIME types should be picked up from the O.S. -- I don't see a way forward here because manual editing of profile files is never a valid consideration. If there is a bug with the browser not picking up existing MIME types from the O.S. then that should be looked at, but the suggestions made so far are not acceptable.
Please check if UXP still exhibits this problem and if so, create a new issue on that repo.
