### ISSUE TITLE
Use OpenMP for parallelization

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#915]
So far we've been using the Microsoft-specific auto-parallelizer, which is good when it kicks in, but seems to not be developed further with additional features.
At the same time, OpenMP has been standardized as a stable extension to C++, and is also supported by GCC 4.9; as such, we should change our parallelization efforts to using the more standardized method with OpenMP.

Since these are `#pragma` based directives, code impact when not supported by the compiler is non-existent (at most some warnings about unrecognized pragmas).
To effectively use OpenMP, usage has to be done carefully and efficiently, with maximum leverage of the supported clauses to avoid variable tainting or unexpected results (use `reduction`, `shared`, `ordered` and `section` as-appropriate to guide the code flow over multiple threads)

**Comment by trav90** [comment]
FWIW, I experimented with using OpenMP on my personal builds about a year ago (maybe a little more), and the performance benefits were quite noticeable.

**Comment by wolfbeast** [comment]
To leverage this, Windows builds will need to get `-openmp` added to the CL optimization when building.

**Comment by wolfbeast** [comment]
@trav90 can you share what you experimented with? Where did you add the pragmas and which ones did you use?

**Comment by trav90** [comment]
My experimentation with OpenMP parallelization happened pre-v26 and only consisted of passing compiler and linker flags (`-ftree-parallelize-loops` and `-lgomp` respectively). I never added any pragmas or touched the source in any way.

**Comment by trav90** [comment]
Turns out that enabling OpenMP with GCC creates a dependence on the libgomp.so.1 lib (the browser won't start without it). AFAIK most modern distros ship this lib by default (Gentoo being one exception I know of), but older distros and older still supported distro releases may not. To my knowledge no reports have been received about unstable builds (which have used the `-fopenmp` flag for a while) not starting, but this may need to be better evaluated before shipping it in -release?

**Comment by mattatobin** [comment]
Perhaps, Linux shouldn't introduce this until the next Milestone. I mean is there any harm in not specifying -fopenmp on Linux builds?

**Comment by trav90** [comment]
The only "harm" would be GCC complaining about an unknown pragma.

**Comment by Bfgeshka** [comment]
> Gentoo being one exception I know of

Not an issue if gcc is compiled with openmp support, which is enabled by default. So, missing openmp support is rare situation and can be worked around (since ebuild can explicitly ask for enabled or disabled USE flag on specific package).

**Comment by chaoskagami** [comment]
@trav90 - Gentoo does ship libgomp, afaik. It should be in a GCC-specific subdirectory like /usr/lib/gcc/<arch>/<version>, not /usr/lib. This is in the search path for gentoo systems, so I wouldn't think it'd pose a problem.

**Comment by trav90** [comment]
I specifically mentioned Gentoo because it was reported to me that the browser would not start when built with `-fopenmp`. I have not tested on Gentoo personally.

**Comment by chaoskagami** [comment]
Weird. Was the binary built on the gentoo system or elsewhere?

The only thing I can think of if it's not their system is somehow an absolute path ended up in the binary.

**Comment by wolfbeast** [comment]
If we're talking about Gentoo, it was probably all built on the Gentoo system since it's an LFS setup.

**Comment by wolfbeast** [comment]
On Windows, we supply the OpenMP lib with the browser (`vcomp120.dll` which is packaged into the archive/installer along with the other runtimes) that gets installed in the application's installation folder/directory -- can this be done the same way on Linux, or not?

**Comment by mattatobin** [comment]
I don't think so.. You can't just ship pecies of gcc as local redist like that without the rest of the runtime and it would be totally against linux to do so..

**Comment by wolfbeast** [comment]
Then the installer script probably needs to check for the lib and not install if the lib is missing, with a message to the user.

**Comment by mattatobin** [comment]
We can't do that either.. It would break package management expectations on something outside of the application's scope.

**Comment by Bfgeshka** [comment]
> can this be done the same way on Linux, or not?

You can ship 3rd party libs with portable version of some sort, yes. But it shouldn't be done with usual installation, dependencies _must_ be handled via package managers.

> If we're talking about Gentoo, it was probably all built on the Gentoo system since it's an LFS setup.

In this case browser won't be built in a first place. If build was successfull then issues with missing libraries just cannot happen.

You shouldn't worry about missing libs for application in source-based distros, this question is handled by package managers. If this kind of problem occurs then it supposed to be an issue with package build configuration in most cases.

**Comment by trav90** [comment]
> Then the installer script probably needs to check for the lib and not install if the lib is missing, with a message to the user.

The script already checks for the liboxygen-gtk.so and displays a warning if it is found so this shouldn't be too hard to do.

**Comment by trav90** [comment]
I've added a check to the installer script that checks for libgomp.so.1 and should not allow installation it if is not found (will test this later today).

However, another thing to consider is that due to our environment/compiler version Pale Moon likely specifically requires version 'GOMP_4.0' of libgomp.so.1. Distros that ship older versions will not be able to run Pale Moon without first updating the library. This potentially would include Ubuntu 14.04/Mint 17 LTS distros (which I believe ship with an older version; need to check) and possibly others.

**Comment by JustOff** [comment]
Yes, both Ubuntu 14.04 LTS & Mint 17 (EOL April 2019) use libgomp 1.0.0:
```
# ldconfig -v | grep libgomp
	libgomp.so.1 -> libgomp.so.1.0.0
```
I'll be very upset if Pale Moon not run on them.

**Comment by trav90** [comment]
Running that exact command on my Manjaro box (which does have a new enough GOMP) produces the exact same output. Does the current unstable build run on 14.04?

**Comment by JustOff** [comment]
> Does the current unstable build run on 14.04?

```
XPCOMGlueLoad error for file /home/justoff/palemoon/libxul.so:
/usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /home/justoff/palemoon/libxul.so)
Couldn't load XPCOM.
```

**Comment by JustOff** [comment]
Via [stackoverflow](https://stackoverflow.com/questions/1304363/how-to-check-the-version-of-openmp-on-linux):
> For quick reference (copied from openmp.org/wp/openmp-specifications), the mapping of #define _OPENMP to the OPENMP API version is {200505:'2.5',200805:'3.0',201107:'3.1',201307:'4.0'} where each pair is 'value of _OPENMP : OpenMP API Version'.

```
$ echo |cpp -fopenmp -dM |grep -i open
#define _OPENMP 201107
```

So 14.04 supports only openmp v.3.1.

**Comment by JustOff** [comment]
> I've added a check to the installer script that checks for libgomp.so.1 and should not allow installation it if is not found

I'd probably consider providing a separate non-openmp build for systems not supporting it.

**Comment by wolfbeast** [comment]
And this is exactly why I prefer Windows. If you can't be sure the system has a specific runtime DLL, then you can just provide it yourself in a redist runtime file in the app folder.

What percentage of Linux distros are we talking about here that actually don't support the already conservative toolchain we use for building?

**Comment by JustOff** [comment]
I personally don't know how to estimate the percentage, but since we are talking about LTS release with EOL of April 2019, I think it will be wise not to drop it so early.

**Comment by trav90** [comment]
Any distro that ships with GCC 4.8 or below wouldn't support our builds (GCC 4.9 added support for OpenMP 4.0). That said, by now the only supported distros without a new enough libgomp are likely to be various LTS releases, CentOS, and other older distros that only receive sec backports (such as Puppy).

**Comment by trav90** [comment]
*buntu 14.04 (and related distros such as Mint 17, etc.) are still fairly widely used, so I'm not sure if having our generic binary not be able to run on them would be a good idea at this point in time.

**Comment by wolfbeast** [comment]
It's probably better not to use -fopenmp then on Linux release builds. It's not like we have widespread of use of OpenMP directives yet, so the optimization would not provide a big impact.

**Comment by trav90** [comment]
Agreed. As Tobin mentioned above the next milestone would likely be the better target for Linux (assuming that we are still using GCC 4.9 at that time).

**Comment by squarefractal** [comment]
The redist/ functionality can be implemented by patching the binaries to include shared objects with patchelf, and then adding the libgomp.so file.

**Comment by wolfbeast** [comment]
No further work on this will be done on Tycho.
