### ISSUE TITLE
false security warning on vk.com

### ISSUE THREAD

**Issue by leedoyle** [MoonchildProductions/Pale-Moon#919]
Every now and then when browsing https://vk.com the red exclamation mark near the address bar appears, even though everything seems to be OK with the certificate and with the cipher suite used (according the info in page info > security details > view certificate), and there's no reason to suspect a MITM-attack.
It occurs randomly, and if I reload the web page it disappears — only to come back again some time later.
System: Ubuntu 14.04, Browser: Pale Moon 27.1, no addons related to TLS/https
Herewith a screenshot:
![falseWarning](https://cloud.githubusercontent.com/assets/25978190/23315834/625caf90-fae1-11e6-9f2e-d667ce8cb198.png)

**Comment by wolfbeast** [comment]
Pay attention to the output. You're looking at broken security because of mixed-mode content.

**Comment by leedoyle** [comment]
@wolfbeast thanks for your reply. That's what I thought, too, but it doesn't seem to occur in Firefox... 
Could it be that Firefox blocks mixed content while Pale Moon doesn't?

I'll try to investigate it by sniffing traffic.

**Comment by leedoyle** [comment]
@wolfbeast okay, so I opened the built-in network inspection tool, reloaded https://vk.com/video until I got the warning. Then I checked the log if there was any **http://** link. There was none.

**Comment by wolfbeast** [comment]
Well, there's certainly a reason why you get a "broken" indicator. It may not necessarily be a directly-loaded page element, but the page status will not come back as "broken" unless there is a good reason for it.

**Comment by leedoyle** [comment]
@wolfbeast yes, there's certainly a **good reason** I get a broken indicator, and that reason is a **BUG** in Pale Moon 27.1.0 32bit for Linux. 
There is NO mixed content on the webpage, and this bug is not present in Mozilla Firefox 51.0.1, which makes it a Pale Moon specific bug. 
Why are you ignoring the issue? At least have the courage to mark it as "wontfix" if you don't feel like it.

**Comment by mattatobin** [comment]
@leedoyle And you think that attitude will motivate anyone? You are cute.

I checked it out.. Seems not to be an issue here all is unbroken. May want to check if you are running any extensions that could be injecting non-https resources into the html or rewriting pieces of it. Try a clean profile or at least disable your extensions. Also, ensure you don't have some a/v suite doing crazy things or an ISP that isn't injecting things on the fly either.
