### ISSUE TITLE
Stop preloading HPKP certificate data

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#925]
We also have HPKP preloading going on in our tree which has a (very similar) update method to HSTS preloading.

We need to investigate whether we want to either run regular updates of this as well or if we want to forgo preloading of this.

As long as we support that (I'm not sure if we should... potential web breakage there since it has a blanket expiry time for all domains) it needs to also be updated as follows:

-    use `genHPKPStaticPins.js`
-    `default-ee.der` can be found in \security\manager\ssl\tests\unit\tlsserver\
-    `PreloadedHPKPins.json` is in the same dir as the script (does this need updating? does the script update it?)
-    `StaticHPKPins.h` is in the same location as the .inc for HSTS

````
// 3. run `[path to]/run-mozilla.sh [path to]/xpcshell \
//                                  [path to]/genHPKPStaticpins.js \
//                                  [absolute path to]/PreloadedHPKPins.json \
//                                  [absolute path to]/default-ee.der \
//                                  [absolute path to]/StaticHPKPins.h
````

None of this is effective right now since the static expiry is June 2016, so just spinning its wheels.

**Comment by Atavic** [comment]
I'm asking a question here: the expiration date is set on which basis?

>a value on the order of 60 days (5,184,000 seconds) may be considered a balance between the two competing security concerns.

http://www.rfc-editor.org/rfc/rfc7469.txt

**Comment by wolfbeast** [comment]
The expiration is set on the basis of "last update + x time" by the update script.

**Comment by wolfbeast** [comment]
Giving this some more thought we should probably just do away with preloading this, and rely on the 'net to give use the proper data when visiting sites.
