### ISSUE TITLE
devtools (plugin) JSON resonse not "browsable"

### ISSUE THREAD

**Issue by schnepe2** [MoonchildProductions/Pale-Moon#926]
When clicking e.g. in the "Console" on a JSON response, one could open any Maps/Arrays by clicking on the [+] Symbol.
This worked up to PaleMoon 27.0.3, but fails since 27.1.0

At first I thought this is a "devtools" plugin issue, but I think it has to do with a PaleMoon-packaged CSS.

To reproduce/show:

1.  install the [devtools for PaleMoon](https://addons.palemoon.org/extensions/devtools/) plugin
2. go to [REST Test site](https://resttesttest.com/)
3. open the devtools (e.g. with `F12`) Console _(you might have to _**enable**_ the Console)_
4. click the `Ajax request` button

In the JSON Tab of the response you should be able to expand the `headers` map, but since 27.1.0 you can't
![issue-devtool](https://cloud.githubusercontent.com/assets/18400313/23405049/8e08c6fe-fdb8-11e6-95bc-88d1d4251c60.jpg)

This is how it looks (how it should work) with PaleMoon 27.0.3
![no-issue-devtool](https://cloud.githubusercontent.com/assets/18400313/23405177/59176120-fdb9-11e6-97aa-661f05c3cd69.jpg)

**Comment by janekptacijarabaci** [comment]
Throws an error in Browser Console:
```
[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND)
[nsIXPCComponents_Utils.import]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"
location: "JS frame :: chrome://firebug/content/lib/promise.js :: <TOP_LEVEL> :: line 13"
data: no]1 mini-require.js:92:0
```

@mattatobin 

Ad https://github.com/Pale-Moon-Addons-Team/devtools/blob/DEVTOOLS_1.0.0a1/src/content/firebug/lib/promise.js#L13

I suggestion:

From:
``` javascript
Components.utils["import"]("resource://gre/modules/jetpack/sdk/core/promise.js", imported);
```

To:
``` javascript
try {
  // Pale Moon 27.1+
  Components.utils["import"]("resource://gre/modules/commonjs/sdk/core/promise.js", imported);
} catch (e) {
  // Pale Moon 27.0-
  Components.utils["import"]("resource://gre/modules/jetpack/sdk/core/promise.js", imported);
}
```

**Comment by schnepe2** [comment]
...so this actually _is_ a devtools issue...?
Should I create an issue at their repository, or is @mattatobin or you ( @janekptacijarabaci ) handling this already?

**Comment by wolfbeast** [comment]
The extension needs to be updated for use with Pale Moon 27.1 because the path to some modules have changed. Web Developer Tools was written initially for the different path specific to v27.0 which was changed to make Pale moon more compatible with SDK add-ons, with less need for edits for those add-ons to make them PMkit ones.

**Comment by wolfbeast** [comment]
(iow: not a browser bug, but a breaking change in the browser needing an update in the extension)

**Comment by mattatobin** [comment]
I am on it.. I am not gonna set a trycatch block.. Simply next version will require 27.1.0.. I need to do some slight re-branding anyway since it needs to differentiate its self from the mozilla-devtools.

**Comment by mattatobin** [comment]
While we are at it @janekptacijarabaci are there any other glaring issues with the extension that may be a result of changes made to devtools related files?

**Comment by janekptacijarabaci** [comment]
@mattatobin 
Unfortunately, I do not use this extension. I don't know about any problem at this moment.

**Comment by schnepe2** [comment]
Just a heads up...

Changing https://github.com/Pale-Moon-Addons-Team/devtools/blob/DEVTOOLS_1.0.0a1/src/content/firebug/lib/promise.js#L13
... from ...
```javascript
Components.utils["import"]("resource://gre/modules/jetpack/sdk/core/promise.js", imported);
```
... to ...
```javascript
Components.utils["import"]("resource:///modules/promise.js", imported);
```
... works perfectly on either 27.0.3 and 27.1.0++  :grinning:

**Comment by mattatobin** [comment]
Yeah that's because in Tycho we localized a copy of jetpack's self-contained old-style promises.js hack that ties into Promises,jsm for internal browser use until such time as those bits are converted to use Promises.jsm directly and as jetpack was then a great target for removal. Things change however, whatever happens the local browser version isn't hurting anything and it is good to have one native to what the frontend exactly wants.

In any event, I will be releasing a rebranded version of the extension soon and will contain this fix.

**Comment by wolfbeast** [comment]
Closing this - it's an extension task, not a browser bug.
