### ISSUE TITLE
Multiple "Warning: -Wtype-limits" under gcc linux

### ISSUE THREAD

**Issue by walterdnes** [MoonchildProductions/Pale-Moon#928]
I'm doing test builds of the Master branch, today's code, similar to my contributed SSE build. Yes it compiles and runs, but I worry about some of the warnings. Doing

`grep -C3 "Warning: -Wtype-limits" buildlog.txt`

gets multiple "warning: comparison is always false" or "warning: comparison is always true". I'm not a C programmer, but this scares me. This is not a dummy  "if true" or "if false" hack. This seems to occur with real-life comparisons, and could mean "dead code", if not outright bugs. File-attached is what I grepped from my buildlog.txt.
[wtype.txt](https://github.com/MoonchildProductions/Pale-Moon/files/809665/wtype.txt)

**Comment by trav90** [comment]
Looks like all those warning happened in third party code only.

**Comment by walterdnes** [comment]
> Looks like all those warning happened in third party code only.

Even so, don't you have the source code? An "IF" that's always, forcibly, true or always, forcibly, false ddoesn't seem right.

**Comment by trav90** [comment]
Yes, but those warnings should (and may have been in newer versions than we currently have in-tree) be fixed by upstream.

**Comment by trav90** [comment]
That said, it is my intention to go through and attempt to fix (or silence if need be) compiler warnings soon, but other things (e.b. media) are more pressing at the moment.

**Comment by wolfbeast** [comment]
I just had a look at the log:

In libevent, it seems to trip over a comparison between `size_t` on the left-hand side and what resolves to an `int64_t` at max value at the right-hand side, in the first bunch of warnings.

That's a perfectly valid comparison to make; size_t does not have a hard upper bound and in many implementations/compilers' `<stdint.h>` its max will be larger than the max 64-bit int. In fact, C99 only defines that it has to be "at least" 65535.
Doing this sanity check is therefore good and needed if you use `size_t` as a type and don't want to deal with overflows in assignments if it ends up being larger than your target type (not being `size_t`). These kinds of situations do happen, and warnings will be thrown, but that doesn't mean the code is wrong.

The ICU lib comparison is indeed folly. It may be historical and left in on purpose -- you'd have to report this to the ICU maintainers.

The jxrlib warning is once again for a `size_t` type.
http://xref.palemoon.org/palemoon-trunk/source/media/jxrlib/image/decode/strdec.c#2624
It would be a problem if it were not the case that it will always hit a point where the loop breaks.
This could use some rewriting to avoid the _potential_ of an endless loop if for some inexplicable reason the data never contains a non-0 entry, and depending on how `size_t` is internally defined by the compiler...
