### ISSUE TITLE
Large pictures are not loaded and displayed

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#932]
Large pictures are not loaded and displayed (blank page or page with error text).

__Steps to reproduce:__

_Go to:_

http://imgsrc.hubblesite.org/hu/db/2003/28/images/a/formats/full_jpg.jpg
\- OK
(Pale Moon 27.1.1 - x32, x64)

http://imgsrc.hubblesite.org/hu/db/2006/10/images/a/formats/full_jpg.jpg
\- OK
(Pale Moon 27.1.1 - x64)
\- The image [...] cannot be displayed, because it contains errors.
(Pale Moon 27.1.1 - x32)

http://imgsrc.hubblesite.org/hu/db/2006/01/images/a/formats/full_jpg.jpg
http://www.vidiani.com/maps/maps_of_the_world/large_scale_detailed_satellite_map_of_the_World.jpg
\- The image [...] cannot be displayed, because it contains errors.
(Pale Moon 27.1.1, Firefox Nightly 54.0a1 (2017-03-02) (64-bit))

There are more images to test at http://hubblesite.org/ and http://hiroc.lpl.arizona.edu/images/PSP/

See:
https://bugzilla.mozilla.org/show_bug.cgi?id=370763

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1283961

See also (downscale all important image formats during decode):
https://bugzilla.mozilla.org/show_bug.cgi?id=1045926

**Comment by mattatobin** [comment]
Stunning images but god even chrome is having some difficulty coping.. Obviously coping better than we are but jesus.

**Comment by Atavic** [comment]
Both K-Meleon and Pale Moon load the stunning galaxy image here.

**Comment by wolfbeast** [comment]
We are a web browser, not an image viewer - such resolutions are not really within scope and if too large (based on available resources or settings), Pale Moon should refuse to display them instead of gobbling up RAM (and crashing if OOM).

**Comment by mattatobin** [comment]
I had a thought that was the case.

**Comment by wolfbeast** [comment]
I don't particularly see a reason to have the browser display images > 16k pixels wide/high (which is about our current limit), so it'll be a wontfix.

**Comment by Atavic** [comment]
Such images should be available from ftp, to be d/l and opened locally.

**Comment by THEtomaso** [comment]
> http://imgsrc.hubblesite.org/hu/db/2006/10/images/a/formats/full_jpg.jpg

That picture actually crashes Pale Moon for me.

**Comment by JustOff** [comment]
> That picture actually crashes Pale Moon for me.

I can confirm the crash at the end of the image load with 27.2.0a1 x86 ([custom](https://github.com/MoonchildProductions/Pale-Moon/tree/d830c6870daad1abbd8bbcb25079fdde9e79da1f)) @ Win7 x64.

**Comment by janekptacijarabaci** [comment]
Version (unstable - http://www.palemoon.org/unstable/):
27.2.0a1 (32-bit) (2017-03-08), Win7 x64

This image shows OK (for me).

**Comment by JustOff** [comment]
I've tried official unstable with clean profile, it also hangs for me and unfortunately AppCrashView see nothing about it.

**Comment by janekptacijarabaci** [comment]
> with clean profile

It is also not confirmed (for me).

**Comment by THEtomaso** [comment]
> 27.2.0a1 (32-bit) (2017-03-08), Win7 x64
This image shows OK (for me).

I tried with that version too.
It still crashes.

**Comment by THEtomaso** [comment]
As a workaround, setting **image.high_quality_downscaling.enabled** to **false** fixes it.
..but when zooming in, to view the image in full size, it turns all black!

**Comment by wolfbeast** [comment]
What part of "out of scope" don't you guys understand?
