### ISSUE TITLE
Be smarter about resolution safety limits of images.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#936]
The current Mozilla safety limit handling for PNG image sizes is rather naive and could be improved to be smarter. Potentially the resulting check can be extended to other image formats as well.

Currently, a hard check is performed on width _or_ height being larger than a set resolution (32k pixels). This is fine for a DoS sanity limit if you assume normal image proportions.
Images with odd aspect ratios, however, like e.g. a narrow horizontal or vertical strip, could easily be decoded within safe limits even if that height or width is larger than 32k pixels, so it needs to be smarter.

The best way to go about this would be to keep the width and height limits, at safe maxima (e.g. 64k pixels, double the current limit) and also check for the actual image area to keep total pixel size under control to prevent DoS. A 32k x 32k image is way beyond reasonable for a browser, and half that in image area is likely pushing the limit, so making this 16k x 16k = 256Mpix seems like a safe upper cap.

Narrow strips will then be accepted (if < 64k wide or high) because e.g. 1000 x 40k (40Mpix) < 16k x 16k (256Mpix).

**Comment by wolfbeast** [comment]
Unstable has a fix for this -- kindly verify.

**Comment by mattatobin** [comment]
**VERIFIED FIXED** on GMail

**Comment by wolfbeast** [comment]
Verified by forum people as well, marking this fixed and closed.
