### ISSUE TITLE
Remove references to Firefox marketplace

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#937]
about:home content and browser.js need to have links/refs to the Firefox Apps marketplace removed.

- http://xref.palemoon.org/palemoon-trunk/source/browser/base/content/browser.js#2429
- about:home content files.
- css (+ potentially remove graphics no longer used)

Simple stuff anyone can do ;)

**Comment by walterdnes** [comment]
I'm not a programmer, but I just did a scan of "about:config" for instances of Firefox/Mozilla. I figure it's part of the same overall problem as this item, so no point opening another one. There are multiple hits in the sourcecode for some of the preferences listed below...

Occurences of firefox...

```
browser.dictionaries.download.url;https://addons.mozilla.org/%LOCALE%/firefox/dictionaries/
devtools.devedition.promo.url;https://www.mozilla.org/firefox/developer/?utm_source=firefox-dev-tools&utm_medium=firefox-browser&utm_content=betadoorhanger
dom.mozApps.signed_apps_installable_from;https://marketplace.firefox.com
extensions.getAddons.browseAddons;https://addons.mozilla.org/%LOCALE%/firefox
extensions.hotfix.id;firefox-hotfix@mozilla.org
identity.fxaccounts.auth.uri;https://api.accounts.firefox.com/v1
services.sync.fxa.privacyURL;https://accounts.firefox.com/legal/privacy
services.sync.fxa.termsURL;https://accounts.firefox.com/legal/terms
toolkit.telemetry.infoURL;https://www.mozilla.org/legal/privacy/firefox.html#telemetry
```
And mentions of Mozilla (some overlap)

```
browser.trackingprotection.gethashURL;https://tracking.services.mozilla.com/gethash?client=SAFEBROWSING_ID&appver=%VERSION%&pver=2.2
browser.trackingprotection.updateURL;https://tracking.services.mozilla.com/downloads?client=SAFEBROWSING_ID&appver=%VERSION%&pver=2.2
devtools.devedition.promo.url;https://www.mozilla.org/firefox/developer/?utm_source=firefox-dev-tools&utm_medium=firefox-browser&utm_content=betadoorhanger
extensions.blocklist.detailsURL;https://www.mozilla.org/%LOCALE%/blocklist/
extensions.getAddons.browseAddons;https://addons.mozilla.org/%LOCALE%/firefox
extensions.hotfix.id;firefox-hotfix@mozilla.org
media.gmp-manager.certs.1.commonName;aus4.mozilla.org
media.gmp-manager.certs.2.commonName;aus4.mozilla.org
media.gmp-manager.url;https://aus4.mozilla.org/update/3/GMP/%VERSION%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/update.xml
plugins.update.url;https://www.mozilla.org/%LOCALE%/plugincheck/
security.ssl.errorReporting.url;https://data.mozilla.com/submit/sslreports
services.sync.tokenServerURI;https://token.services.mozilla.com/1.0/sync/1.5
social.directories;https://activations.cdn.mozilla.net
toolkit.telemetry.infoURL;https://www.mozilla.org/legal/privacy/firefox.html#telemetry
toolkit.telemetry.server;https://incoming.telemetry.mozilla.org
toolkit.telemetry.server_owner;Mozilla
```
Also, with Mozilla/Firefox abandoning XUL, there's no point in listing the two Mozilla add-on sites. I believe that they can still be used without whitelisting, but with the user having to override warnings.

```
services.sync.addons.trustedSourceHostnames;addons.palemoon.org,addons.mozilla.org
xpinstall.whitelist.add;addons.mozilla.org,www.palemoon.org,addons.palemoon.org
```

**Comment by Atavic** [comment]
@walterdnes a personalized user.js may help, there are many ones:
[user.js](https://github.com/pyllyukko/user.js)
[ghacks-user.js](https://github.com/ghacksuserjs/ghacks-user.js)
[legacy-user.js](https://github.com/Atavic/legacy-user.js)

**Comment by walterdnes** [comment]
@Atavic I already use that, but the issue here is that Pale Moon source code references those entries. Deleting these entries means that we end up with, at best "dead code", or at worst bugs when the source code can't find an expected "about:config" entry. The relavant source code should be modifed/deleted. That's why I feel it belongs as part of Issue #937, which is labelled "Code Cleanup".

**Comment by mattatobin** [comment]
I think your comments here are baseless and unproductive.

**Comment by wolfbeast** [comment]
Please keep things on-topic. referring to pre-configured pres is pointless. I'm removing off-topic comments.

**Comment by wolfbeast** [comment]
There are still some references regarding the marketplace in e.g. certificate stores and actually using apps, but that is currently of no consequence. Closing this.
