### ISSUE TITLE
Problems with weather.com - weather in motion - elements are not shown - missing ES6 feature?

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#939]
https://forum.palemoon.org/viewtopic.php?f=15&t=15039

The topic opener describes that the weather in motion part is not working and not shown. Can confirm that problem

Error console output offers something like that:

Timestamp: 06.03.2017 21:41:51
Warning: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
Source File: https://weather.com/weather/assets/twcM ... 95e208f.js
Line: 1

A quick search with Google shows that that is somehow related to ES6 functions.

example url:

https://weather.com/en/weather/radar/interactive/l/AUXX0025:1:AU?layer=sat&zoom=8&animation=true

Perhaps related to the bugs #892 and follow-up  #900 - topic opener describes that the link works fine with IE, and the not showing content was also a topic in #892  - IE supports the ES6 block-level functions function and Pale Moon not - which was leading in the mentioned bug to missing web-content.

**Comment by wolfbeast** [comment]
Mutation of a prototype happens on many sites that don't use the preferred way of creating objects in ES6. It won't prevent these things from working, at most it will make them slow.

**Comment by wolfbeast** [comment]
If this was related to #900 then I'd expect the browser/error/web console to spit out error messages.

**Comment by trav90** [comment]
The weather.com weather in motion map appears to be working again. Been using it off and on for the past several hours with no problems.

**Comment by wolfbeast** [comment]
I guess this and Vimeo was fixed upstream in the VideoJS lib as they both seem to be using it?

**Comment by wolfbeast** [comment]
I had a look at it working now -- seems to be something specific changed on their end. Their animation is the repeated addition and removal of DIV elements with the different radar images. Purely JS/element driven. Must have been a bug in there somewhere.

**Comment by trav90** [comment]
This isn't the first time weather.com has broken (on other browsers also I might add) due to changes they've made.
