### ISSUE TITLE
Screensaver should be disabled when playing HTML5 video

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#94]
Fairly simple: add a WakeLockListener to the <video> element.

Bugs that need porting:
https://bugzilla.mozilla.org/show_bug.cgi?id=968603 (add WakeLockListener)
https://bugzilla.mozilla.org/show_bug.cgi?id=1063995 (ignore HTML5 audio)
and perhaps for the nonstandard case of loading audio in a video element:
https://bugzilla.mozilla.org/show_bug.cgi?id=1022669

Feel free to take this bug and work on it.

**Comment by trav90** [comment]
I volunteer to take this.

**Comment by wolfbeast** [comment]
Travis' PR should fix this on the OSes where this matters most.

**Comment by wolfbeast** [comment]
Re-landed with fixes as commit 085e1a6322d6cc5890078a6c3b296bc171b12ff2
Travis: the culprit was a missing MOZ_FINAL on the class; without it, the class is made abstract for inheriting it to child classes. While there I removed some double declarations of pointers and made them a single nsCOMPtr for the power management interface.

**Comment by trav90** [comment]
OK, I see. Thanks for the info. Glad it's working!

**Comment by trav90** [comment]
Should the fixes for Windows be included in Mac also?

**Comment by wolfbeast** [comment]
I haven't looked at the Mac code. If it's stated similarly there then you probably do need to make the same changes.

**Comment by wolfbeast** [comment]
Reopening this since it should probably be verified building on all platforms and verified working as intended ;)

**Comment by trav90** [comment]
PR #98 Please double check make sure I didn't miss any changes.

**Comment by trav90** [comment]
PR #101 Linux patch.

**Comment by wolfbeast** [comment]
Now we need to build and test that it actually works ;)

**Comment by trav90** [comment]
Sorry, should have mentioned that I tested it before submitting the PR (for Linux anyway). It builds successfully and works with the proper services enabled in CentOS. Icouldn't get it to work on my Manjaro box, but I believe it is related to the newer package versions Manjaro uses (see comments on the PR). I don't have a way to test on Mac. @BitVapor, could you take a look?

**Comment by trav90** [comment]
The Linux patch is apparently still not fully complete per issue #109

**Comment by wolfbeast** [comment]
We'll have some time to sort this out; if not for 25.6, then I'll back it out for the release.

**Comment by squarefractal** [comment]
Will this backout be on the relbranch or master?

**Comment by wolfbeast** [comment]
> Will this backout be on the relbranch or master?

That depends on if we have any sort of progress on cause and solution at that time. It'll be backed out just for the affected OS, though.

**Comment by trav90** [comment]
PR #113 should resolve this for Linux.

**Comment by wolfbeast** [comment]
Now we just need people to test and verify that it works as-intended re: disabling the screensaver timer.

**Comment by wolfbeast** [comment]
I backed out #101 and #113 from the tree because of segfaults when playing HTML5 video (as noted on the forum when testing beta1)

**Comment by wolfbeast** [comment]
I'm closing this issue since Linux has been given an follow-up issue #119 and it seems to work otherwise (beta tested) on Windows. Mac is unknown at the moment since dev there is stalled. if mac needs more work than what was submitted, please open a new issue.
