### ISSUE TITLE
Remove gamepad support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#943]
Our survey has shown a massive majority of people finding the ability to use a gamepad to control/interface with the browser absolutely unnecessary and not desired.
We should remove everything related to this feature.

**Comment by THEtomaso** [comment]
Just be careful in the process, so you don't break gamepad support for HTML5 games:
http://html5gamepad.com/

**Comment by wolfbeast** [comment]
They are one and the same.

**Comment by THEtomaso** [comment]
Ah, I see.
I think there might have been a misunderstanding amongst users that took the survey then (myself included).
HTML5 gaming is on the big rise, so removing gamepad support really doesn't sound like a good idea with prospects for the future.

**Comment by wolfbeast** [comment]
HTML5 gaming overall may be on the rise, but with a gamepad? I don't think so. Most HTML5 games will be focusing on pointer/touch controls instead, not analog stick/gamepad controls.

**Comment by THEtomaso** [comment]
Well, I was reading a article the other day, regarding Epic Games' work to convert their Unreal Engine into HTML5.
They even went as far as calling it the future of gaming!
It just seems a bit odd to me that you'd want to remove a perfectly working feature from Pale Moon, that only serves to make it a more complete browser for the future.

**Comment by wolfbeast** [comment]
The same can be said about DRM or WebRTC.

**Comment by wolfbeast** [comment]
The code can be left in our tree for the time being, but it'll be unsupported and might bitrot. Code cleanup can be done later if things pan out as expected.

**Comment by THEtomaso** [comment]
Speaking of HTML5 gaming..
The latest games requires WebGL 2.0:
https://www.khronos.org/registry/webgl/specs/latest/

Here's an example:
https://s3.amazonaws.com/mozilla-games/ZenGarden/EpicZenGarden.html
When supported, the above demo looks like this:
https://www.youtube.com/watch?v=TwuIRcpeUWE

**Comment by wolfbeast** [comment]
Completely off-topic and unrelated
