### ISSUE TITLE
mac 27.1.2: missing includes under mozilla/dom/

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/Pale-Moon#956]
I'm currently trying to track down where these headers disappeared / moved to.  They aren't obviously in the current tree but I'm seeing references to them sprinkled through the history.

```
2:10.91 In file included from /Users/pale/jenkins/workspace/tycho/default/obj-x86_64-apple-darwin12.5.0/dom/cellbroadcast/Unified_cpp_dom_cellbroadcast0.cpp:2:
 2:10.91 In file included from /Users/pale/jenkins/workspace/tycho/default/dom/cellbroadcast/CellBroadcast.cpp:6:
 2:10.91 In file included from ../../dist/include/mozilla/dom/CellBroadcast.h:10:
 2:10.91 In file included from ../../dist/include/mozilla/DOMEventTargetHelper.h:18:
 2:10.92 ../../dist/include/mozilla/EventListenerManager.h:10:10: fatal error: 'mozilla/dom/EventListenerBinding.h' file not found
 2:10.93 #include "mozilla/dom/EventListenerBinding.h"
 2:10.93          ^
 2:11.02 libbrowser_components_about.a.desc
 2:11.38 Unified_cpp_dom_xslt_xpath2.o
 2:11.85 nsCOMPtr.o
 2:12.23 nsCategoryCache.o
 2:12.34 libtoolkit_components_finalizationwitness.a.desc
 2:12.38 nsCOMArray.o
 2:12.52 Unified_cpp_uriloader_prefetch0.o
 2:12.75 In file included from /Users/pale/jenkins/workspace/tycho/default/obj-x86_64-apple-darwin12.5.0/dom/xslt/xpath/Unified_cpp_dom_xslt_xpath0.cpp:2:
 2:12.76 In file included from /Users/pale/jenkins/workspace/tycho/default/dom/xslt/xpath/XPathEvaluator.cpp:6:
 2:12.76 In file included from ../../../dist/include/mozilla/dom/XPathEvaluator.h:15:
 2:12.76 ../../../dist/include/nsIDocument.h:24:10: fatal error: 'mozilla/dom/DocumentBinding.h' file not found
 2:12.76 #include "mozilla/dom/DocumentBinding.h"
 2:12.76          ^
 2:13.22 nsCOMPtr.o
 2:13.27 nsClassInfoImpl.o
 2:14.07 nsCategoryCache.o
 2:15.14 In file included from /Users/pale/jenkins/workspace/tycho/default/obj-x86_64-apple-darwin12.5.0/dom/xslt/xpath/Unified_cpp_dom_xslt_xpath1.cpp:2:
 2:15.14 In file included from /Users/pale/jenkins/workspace/tycho/default/dom/xslt/xpath/txNameTest.cpp:9:
 2:15.14 In file included from /Users/pale/jenkins/workspace/tycho/default/dom/xslt/xpath/txXPathTreeWalker.h:10:
 2:15.16 In file included from /Users/pale/jenkins/workspace/tycho/default/dom/xslt/xpath/txXPathNode.h:11:
 2:15.16 ../../../dist/include/nsIDocument.h:24:10: fatal error: 'mozilla/dom/DocumentBinding.h' file not found
 2:15.16 #include "mozilla/dom/DocumentBinding.h"
 2:15.16          ^
 2:15.67 nsClassInfoImpl.o
 2:15.96 nsComponentManagerUtils.o
 2:16.11 nsComponentManagerUtils.o
 2:17.23 nsCycleCollectionParticipant.o
 2:17.32 In file included from /Users/pale/jenkins/workspace/tycho/default/obj-x86_64-apple-darwin12.5.0/uriloader/prefetch/Unified_cpp_uriloader_prefetch0.cpp:2:
 2:17.32 In file included from /Users/pale/jenkins/workspace/tycho/default/uriloader/prefetch/OfflineCacheUpdateChild.cpp:8:
 2:17.32 In file included from ../../dist/include/mozilla/dom/ContentChild.h:11:
 2:17.32 In file included from ../../dist/include/mozilla/dom/ContentBridgeParent.h:11:
 2:17.32 In file included from ../../dist/include/mozilla/dom/nsIContentParent.h:12:
 2:17.32 In file included from /Users/pale/jenkins/workspace/tycho/default/dom/base/nsFrameMessageManager.h:30:
 2:17.32 In file included from ../../dist/include/mozilla/dom/StructuredCloneUtils.h:12:
 2:17.32 In file included from ../../dist/include/mozilla/dom/File.h:17:
 2:17.32 In file included from ../../dist/include/mozilla/dom/indexedDB/FileManager.h:11:
 2:17.32 ../../dist/include/mozilla/dom/quota/PersistenceType.h:12:10: fatal error: 'mozilla/dom/StorageTypeBinding.h' file not found
 2:17.33 #include "mozilla/dom/StorageTypeBinding.h"
 2:17.33          ^
 2:17.51 nsCycleCollectionParticipant.o
 2:17.56 In file included from /Users/pale/jenkins/workspace/tycho/default/obj-x86_64-apple-darwin12.5.0/dom/xslt/xpath/Unified_cpp_dom_xslt_xpath2.cpp:2:
 2:17.57 In file included from /Users/pale/jenkins/workspace/tycho/default/dom/xslt/xpath/txUnionExpr.cpp:8:
 2:17.57 In file included from /Users/pale/jenkins/workspace/tycho/default/dom/xslt/xpath/txNodeSet.h:15:
 2:17.57 In file included from /Users/pale/jenkins/workspace/tycho/default/dom/xslt/xpath/txXPathNode.h:11:
 2:17.57 ../../../dist/include/nsIDocument.h:24:10: fatal error: 'mozilla/dom/DocumentBinding.h' file not found
 2:17.57 #include "mozilla/dom/DocumentBinding.h"
 2:17.57          ^
 2:18.14 nsEnumeratorUtils.o
 2:18.50 1 error generated.
```

**Comment by mattatobin** [comment]
Those headers are autogenerated not simply copied. The real question is why aren't they being generated for you.

BTW 3 seconds from a last successful obj-dir told me that.

**Comment by stevenschlansker** [comment]
Thanks for the tip, Tobin.  But I could do without the patronizing, I don't have a last successful directory, because I had to replace the disk on the build machine...

**Comment by stevenschlansker** [comment]
@mattatobin @wolfbeast @trav90 as of `27.2.0` the Mac build is stable again -- the `27.1` series still doesn't build but whatever problem there was got fixed.  New build is up on the forum.  Thanks all for the fixes.

**Comment by JustOff** [comment]
> New build is up on the forum

Thanks, and looks like the problem with [missed checkmarks](https://forum.palemoon.org/viewtopic.php?f=41&t=14124#p100392) is also solved at last! Btw, why do you build without devtools but with official branding, despite of "[Current Mac development status](https://forum.palemoon.org/viewtopic.php?f=41&t=15130#p109360)"?

**Comment by stevenschlansker** [comment]
I believe the removal of developer tools was intentional, it's now distributed as an addon.  The official branding is an accident -- it's not official, I was playing around with making it so, but haven't done it yet.  The build file change got lost in a hard drive crash and the last one I'd checked in had official.  I'll fix it when I get a moment.

**Comment by JustOff** [comment]
The built-in devtools were back since [27.0.2](https://forum.palemoon.org/viewtopic.php?f=1&t=14018), so currently both windows and linux releases are built with `--enable-devtools`.

**Comment by stevenschlansker** [comment]
@JustOff I made the following changes and am rebuilding now, does this look right?
```diff
diff --git a/build/macosx/mozconfig.tycho b/build/macosx/mozconfig.tycho
index 705e7cd..e14d881 100644
--- a/build/macosx/mozconfig.tycho
+++ b/build/macosx/mozconfig.tycho
@@ -1,10 +1,10 @@
 mk_add_options MOZ_MAKE_FLAGS=-j8
 # Pale Moon branding
 
-ac_add_options --with-distribution-id=MCP
+#ac_add_options --with-distribution-id=MCP
 #
 ac_add_options --enable-update-packaging
-ac_add_options --enable-official-branding
+#ac_add_options --enable-official-branding
 ac_add_options --enable-release
 # ac_add_options --with-branding=browser/branding/unstable # disable for release
 export MOZILLA_OFFICIAL=1
@@ -19,3 +19,4 @@ ac_add_options --enable-shared-js
 #
 #ac_add_options --enable-debug
 ac_add_options --enable-strip
+ac_add_options --enable-devtools
```

**Comment by JustOff** [comment]
I'd also advise to uncomment `ac_add_options --with-branding=browser/branding/unstable`, and not sure about `ac_add_options --enable-release` - it's better to ask @wolfbeast.

**Comment by mattatobin** [comment]
JustOff is quite correct. Moonchild said you could use Unstable branding and --enable-release and export MOZILLA_OFFICIAL=1 should keep appdata paths consistent. Remember this is dependent on Application Name and Vendor.

Let's just stick with JustOff is quite correct.

**Comment by stevenschlansker** [comment]
OK, I will make those changes as well.

Is there some reference I can see exactly which options are encouraged / supported for Pale Moon, and under what circumstances?  For example in this case to me `27.2.0` is clearly a "release" build (although not official) and I am not sure how I would have determined that I shouldn't include that option.

As an example, [Firefox has this](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Configuring_Build_Options) although I certainly don't expect that documentation to apply one-for-one to PM.

I found [this Linux build document](https://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/Linux) but it mostly focuses on the "how" to build not "why" you would turn certain options on or off.

Thanks for helping me increase my understanding of the build process.

**Comment by wolfbeast** [comment]
Since the intention is to provide an unfinished, but otherwise "like official" build, I said you could use the unstable branding (the same branding used for unstable channel builds). That's an exception to what applies to completely independent builders who may not use that.
**On second thought it's probably not a good idea**, since the unstable branding is specifically set up for the unstable channel and point to the wrong release notes and enables quick-fire update checks and such which you don't want. So please, don't use unstable branding as-is. **Sorry for the confusion there.**

_The reason why I thought about allowing unstable branding is that this makes it easier for people to transition to official builds if and when they happen in the future, because the vendor and product names will be the same (as opposed to unofficial branding which uses "New Moon") and as such the profile will be in the same place._

"--enable-official-branding" is the option you must **never** use unless it's a fully official release build. The Linux doc also has a comment about this at the top of the mozconfig.

it's best if you just use unofficial "New Moon" branding for now. We can worry about transitioning people to official profile locations when the time comes for official releases.

**Comment by wolfbeast** [comment]
To wrap it up, you want the following in mozconfig (commented out what you shouldn't use):
````
mk_add_options MOZ_MAKE_FLAGS=-j8
# Pale Moon branding

ac_add_options --with-distribution-id=MCP
#
ac_add_options --enable-update-packaging
# ac_add_options --enable-official-branding
# ac_add_options --enable-release
# ac_add_options --with-branding=browser/branding/unstable # disable for release
# export MOZILLA_OFFICIAL=1
# export MC_OFFICIAL=1
# 
#
mk_add_options MOZ_CO_PROJECT=browser
ac_add_options --enable-application=browser
#
ac_add_options --enable-optimize="-O2"
#
ac_add_options --enable-jemalloc
ac_add_options --enable-shared-js
#
#ac_add_options --enable-debug
ac_add_options --disable-tests
ac_add_options --enable-strip
ac_add_options --enable-devtools
````

**Comment by stevenschlansker** [comment]
Thank you for clearing this up, I'm producing a (hopefully final) 27.2.0 build now.

**Comment by mattatobin** [comment]
@stevenschlansker You are still using unstable branding.. Quit it, please.
