### ISSUE TITLE
The '--enable-update-packaging' configure options seems to do nothing

### ISSUE THREAD

**Issue by rhinoduck** [MoonchildProductions/Pale-Moon#965]
Firstly, this is a cosmetic issue at most, so just skip it if there are more important things to do now.

I was revisiting my build configuration and when looking into what `--enable-update-packaging` does, I found out that it does not seem to do anything.

Here is the output of a grep run on the source tree:
```
configure:    MOZ_UPDATE_PACKAGING=1
configure:    MOZ_UPDATE_PACKAGING=
configure:    (''' MOZ_UPDATE_PACKAGING ''', r''' $MOZ_UPDATE_PACKAGING ''')
configure.in:    MOZ_UPDATE_PACKAGING=1,
configure.in:    MOZ_UPDATE_PACKAGING= )
configure.in:AC_SUBST(MOZ_UPDATE_PACKAGING)
obj-i686-pc-mingw32/config/emptyvars.mk:MOZ_UPDATE_PACKAGING =
obj-i686-pc-mingw32/config.status:    (''' MOZ_UPDATE_PACKAGING ''', r'''  '''),
tools/update-packaging/confvars.sh:MOZ_UPDATE_PACKAGING=1
```

`--enable-update-packaging` shows up in `about:buildconfig` of both the stable and unstable Pale Moon builds, but maybe it does not need to anymore as per https://bugzilla.mozilla.org/show_bug.cgi?id=1272483 (the other bug the first comment links to has been closed at the end of 2014 which is well before Tycho came to be).

**Comment by wolfbeast** [comment]
`--enable-update-packaging` was always needed prior to make sure MARs could be built.
`MOZ_UPDATE_PACKAGING` is also still in use by other applications, e.g. FossaMail

**Comment by rhinoduck** [comment]
The first comment mentions `MOZ_AUTOMATION_UPDATE_PACKAGING` as a "replacement" as far as I understood it (I didn't go very deep).

This is its presence in the PM tree (including what gets generated during build):
```
build/macosx/mozconfig.common:  MOZ_AUTOMATION_UPDATE_PACKAGING=1
build/mozconfig.automation:mk_add_options "export MOZ_AUTOMATION_UPDATE_PACKAGING=${MOZ_AUTOMATION_UPDATE_PACKAGING-0}"
build/mozconfig.win-common:  MOZ_AUTOMATION_UPDATE_PACKAGING=1
build/unix/mozconfig.linux:  MOZ_AUTOMATION_UPDATE_PACKAGING=1
obj-i686-pc-mingw32/tools/update-packaging/Makefile:full-update:: complete-patch $(if $(MOZ_AUTOMATION_UPDATE_PACKAGING),automation-partial-patch)
tools/update-packaging/Makefile.in:full-update:: complete-patch $(if $(MOZ_AUTOMATION_UPDATE_PACKAGING),automation-partial-patch)
```

This isn't something I ever worked with so I am mentioning it more or less blindly. If `MOZ_UPDATE_PACKAGING` is in use anywhere, just disregard my blabbering and close this.

**Comment by wolfbeast** [comment]
We use an added command to mach in our tree (`mach mar`) to package MAR files (courtesy of Tobin). The automation stuff is only important for Mozilla's build slave infra and not in use.
