### ISSUE TITLE
toLocaleDateString() not working properly after ICU58 update

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#976]
It looks like some API changes were made to ICU, and we'll have to check what needs changing in `/js/src/builtin/Intl.cpp` to match the new API in ICU58+

Potentially relevant BMO bugs: 1075758 1210165 1299615 1323254

re: https://forum.palemoon.org/viewtopic.php?f=3&t=15227

**Comment by wolfbeast** [comment]
We went from 52.1 to 58.2 - might serve to check release notes for the ICU lib.

**Comment by wolfbeast** [comment]
Considering this to be a back-burner issue for now. Bigger fish to fry and all that -- feel free to help out if you can.

**Comment by JustOff** [comment]
It seems I found exactly corresponding bug: [1175347](https://bugzilla.mozilla.org/show_bug.cgi?id=1175347), PR will follow.

**Comment by wolfbeast** [comment]
> Awesome! Great work :)
