### ISSUE TITLE
Investigate using embedding standalone Spidermonkey

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#978]
Since it's rather silly to have to re-invent wheels all the time when Mozilla publishes a standalone version of Spidermonkey, we should see how it can be used for our purposes for web content scripting.
Alex Kontos (Waterfox) indicated he had done similar work for specialized versions of the browser in the past, so let's hope he's willing to share his knowledge on that part - documentation on this kind of thing is pretty much nonexistent.

**Comment by Sa-Ja-Di** [comment]
Why not asking him for some kind of cooperation work? Pretty sure both of you have knowledge which the other one is either partly or fully missing.

So an exchange of information's (which could give Waterfox for example the option to use the old customizable UI without classic theme restorer like Pale Moon has done it) would be for your both benefit.

**Comment by wolfbeast** [comment]
We've already been in touch.
Alex thinks at this point that we have different views on what a potential cooperation might be headed for. I want to maintain XUL as a platform, and he seems to be interested in just making a browser with "maintaining XUL being optional" - no commitment to wanting to maintain XUL/XPCOM in other words.

That aside, he stated he used the standalone Spidermonkey version for 'specialized versions of the browser" and I just want to know how that was done. Because it doesn't seem feasible, and there's no documentation.

**Comment by wolfbeast** [comment]
As it turns out, Alex' specialized version of the browser apparently just involved transplanting `js/src` from one later version back to the base build they had to pick up some essential changes - something completely different than what I thought he meant, and also something that can't possibly be done for keeping the JS engine updated on a future browser development track.

As it is, it seems the problem would be much deeper rooted. Jan de Mooij (one of the main Mozilla devs) provided some much-needed insight into what has been going on underneith all the fluff of pointless renames and busy-work:

> Some of the JSAPI changes you could work around or support with some effort, but we have also made large architectural changes that required lots of changes to both SpiderMonkey and other parts of Gecko, and you can't easily backport these. Examples are the JSContext/JSRuntime unification (older branches use multiple contexts per runtime so you would have to backport all these patches too), the error handling cleanup (again, lots of non-SpiderMonkey patches to make this work), the GC has stronger asserts now and to make that work you need to either disable them or make a lot of platform changes. These are just a few things that come to mind but there are many more.

Especially the first point would make it completely incompatible with the rest of the back-end components that make up our platform. It's all interwoven with the DOM code and the main event loop.

This means we're in a bit of a pickle as far as JS is concerned. The only way forward would be manual implementation of about half of the ES6 standard we're missing (including Annex B which is about as much), OR changing our approach completely and using the Gecko+Spidermonkey platform as a whole since they are thoroughly joined at the hips.

**Comment by wolfbeast** [comment]
As far as this particular investigation is concerned: We can safely say that using the standalone Spidermonkey implementation is a no-go. Closing.

**Comment by Sa-Ja-Di** [comment]
So that means basically either keeping all the unique features of the UI now and having an incredible complex work which can't almost be done or riding the Firefox release train again and losing all unique features in a while

Both ways do sound like hell. Perhaps QT with the revived QTWebkit or QTWebengine would be an idea? You could maintain your own UI with features and the engine work is done by someone else. How about either forking Otter or Qupzilla?

That way sounds for me much more simpler without having to accept the fate of a feature less browser sooner or later or being forced to give up if stuff can't be brought over somehow. Seems this is another Javascript promises like dead-end sadly...

Highly annoying and disappointing.

**Comment by wolfbeast** [comment]
Doing anything but Mozilla-based work will lose our UI, period.

As for QT: I'm sorry but in my opinion QT is one of the longest perpetuated failures to ever hit Windows. None of the QT-based applications I know work properly or reliably, so I won't touch it.

Depending on what Alex responds to my question whether he's going to commit to fully backing a new browser as he announced (can't be a hobby or side project as Waterfox has always been) I'll have one of 2 realistic choices for Pale Moon. Either will need some discussion with our team of core devs, because they will both inevitably mean we'll lose part of what we've worked on for some time now.

**Comment by Gpower2** [comment]
Would it be possible to try and decouple Spidermonkey from Gecko, providing a glue interface, in order to make Spidermonkey render agmostic and Gecko/Goanna JS agnostic?
Is this something that the mozilla devs would consider?
I think that would benefit both projects for the long run and it would make changing JS engines a lot easier and safer.
However I understand how huge a task this is, that's why I am asking if the mozilla devs would also consider this.

**Comment by wolfbeast** [comment]
> Would it be possible to try and decouple Spidermonkey from Gecko, providing a glue interface, in order to make Spidermonkey render agmostic and Gecko/Goanna JS agnostic?

I looked into that but that simply can't be done. DOM is an integral part of Gecko/Goanna (via layout), and also an integral part of JS. While it would theoretically be possible to break those hard links, you'd also end up with something that won't have any semblance to what webdesigners would expect.

Thanks for your input though - I'm looking over the options with our active devs and we'll come up with something that can align us with the current web one way or another.
