### ISSUE TITLE
page/writing-mode: lacking vertical-rl (vertical, right to left) page rendering support

### ISSUE THREAD

**Issue by MingcongBai** [MoonchildProductions/Pale-Moon#979]
When opening this vertical right-to-left test page http://steph.hanfucw.com/webserver/featureTest/, instead of a correctly rendered... vertical right-to-left page, as follows:

![2017-03-26 10-42-02](https://cloud.githubusercontent.com/assets/5006263/24332225/e1199ba4-1210-11e7-87f7-8ff0bf03b115.png)

Pale Moon shows the following (just a plain left-to-right and horizontal page):

![2017-03-26 10-43-32](https://cloud.githubusercontent.com/assets/5006263/24332238/1923d172-1211-11e7-8d21-30d48fcf3cad.png)

Which should suggest that the support for `vertical-rl` writing mode is completely missing from Pale Moon as it stands now (27.1.1).

**Comment by janekptacijarabaci** [comment]
See #632 
(`about:config` - `layout.css.vertical-text.enabled`)

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1166147

**Comment by MingcongBai** [comment]
Good to know, thanks a lot.
