### ISSUE TITLE
Re-implement spellcheck dictionary language override

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#980]
With the platform update we lost the ability to always override the chosen spellchecking dictionary.
This should be reintroduced.

See: https://forum.palemoon.org/viewtopic.php?f=13&t=15287

A simple `all.js` addition of a predefined empty `spellchecker.dictionary.override` and adding it to `nsEditorSpellCheck.cpp` as an override check should do the trick.

**Comment by Feodor2** [comment]
all.js of Pale moon 26 and 27, neither "spellchecker.dictionary" nor "spellchecker.dictionary.override" are predefined. Why it is needed?

**Comment by wolfbeast** [comment]
An empty override is should just be there for convenience.
spellchecker.dictionary will always get filled and defined automatically by the browser (which is why it's not a good place to put in an override)

**Comment by Feodor2** [comment]
Here the code to add in all.js

`// To set one particular spellcheck dictionary everywhere
pref("spellchecker.dictionary.override", "");`

**Comment by wolfbeast** [comment]
Solved by 0381c6af924b366ae24e9339d55e57e3d2a9ef81
