### ISSUE TITLE
MSE issue: Sourceopen event does not fire when video preload attribute is set to "none"

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#981]
With MSE enabled, Pale Moon failes the "preload none" test here:
https://craig.is/demoing/sourceopen-bug/

Bugzilla reference:
https://bugzilla.mozilla.org/show_bug.cgi?id=1211752

Judging from the above Bugzilla report, the MediaSource specs were apparently updated back in April 2016, instructing that the "preload attribute" should be ignored:
https://github.com/w3c/media-source/commit/8aba06a6a10d8fe0bf26b2e4c11a3e5a209244e0/

**Comment by trav90** [comment]
It's known that our MSE code is not spec compliant. It will be looked into after the various media-related hangs are taken care of (unless this becomes a bigger issue again, such as Vimeo or other popular video sites not working with our current implementation).

**Comment by wolfbeast** [comment]
The bugzilla bug isn't confirmed and doesn't have any code patches or discussion about implementation. It's completely useless as a reference.

**Comment by wolfbeast** [comment]
It needs to be enforced at the HTML level, not in MSE; I'll be taking this -- should actually be really simple since some MSE checks are already in place at that level.

**Comment by wolfbeast** [comment]
Basically a one-liner fix. Anyone taking the time to research this could have done it. Even you, Tomaso.
