### ISSUE TITLE
issues with password filling in unstable Version: 27.3.0a1 (32-bit) (2017-03-31)

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#992]
Since today's update for example if i visit pages (for example box.com) i may be able to chose which username i want to use - but the password is not filled in the password field.

Happens with other pages too. So i guess that update has broken something ;)

**Comment by Sa-Ja-Di** [comment]
Additional problem:

custom user agent overrides do no longer work here for me.

**Comment by wolfbeast** [comment]
Unable to reproduce the SSUAO not working. I don't have passwords stored in my test setup so I can't really test the former.

Does the browser console or error console give you anything specific in the realm of errors?

**Comment by Sa-Ja-Di** [comment]
Hmm.. i guess that issue can be closed, tested now with a fresh profile where all worked fine and an older backup of stored profile files works also flawless, so guess my profile became corrupt partly ;)

And i really hoped that day would never come :D
