### ISSUE TITLE
PageMenu.jsm - Ci.nsIXULContextMenuBuilder no longer exists (throws an error)

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#993]
__Steps to reproduce__

1) Go to: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu

2) Go to: `Examples` - `Context menu`

3) Click to button: `OPEN IN JSFIDDLE`

4) Open the context menu... - throws an error in Browser Console:

```
NS_ERROR_XPC_BAD_CONVERT_JS: Could not convert JavaScript argument arg 0
[nsISupports.QueryInterface] PageMenu.jsm:48:0
```

See also:
http://xref.palemoon.org/palemoon-rel25/search?string=nsIXULContextMenuBuilder&find=&findi=&filter=%5E%5B%5E%5C0%5D*%24&hitlimit=&tree=palemoon-rel25
http://xref.palemoon.org/palemoon-rel25/search?string=nsIXULContextMenuBuilder&find=&findi=&filter=%5E%5B%5E%5C0%5D*%24&hitlimit=&tree=palemoon-rel26
https://bugzilla.mozilla.org/show_bug.cgi?id=1066383

**Comment by wolfbeast** [comment]
Resolved by #1013
