### ISSUE TITLE
Use system certificates

### ISSUE THREAD

**Issue by l29ah** [MoonchildProductions/Pale-Moon#995]
I'm visiting https://cacert.org/ and it says:

> The certificate is not trusted because the issuer certificate is unknown.

Even though i have the cert in my system store (/etc/ssl/certs/) and qutebrowser has no problem connecting. How do i make palemoon use the system store instead of its own?

**Comment by wolfbeast** [comment]
You can't.
Pale Moon uses its own truststore.

**Comment by wolfbeast** [comment]
Closing as by design.
